### ISSUE TITLE
libsockets.a unnecessarily linked in even in hello world

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#10035]
In `EMCC_DEBUG=1` output of just building `tests/hello_world.c` there is
```
system_libs:DEBUG: including libsockets (libsockets.a)
```
Apparently no code is actually linked in, as our tests on code size have not changed, but this does build the library unnecessarily the first time (how I noticed it) and adds extra work for the linker, so it's worth fixing this.

@juj I think this is the library you recently added? Please take a look.

**Comment by juj** [comment]
This was discussed in proxy_posix_sockets PR. I did not change any behavior here, sockets was unconditionally linked against already before (as it was part of libc), the proxy_posix_sockets branch just moved those symbols to their own file (instead of being in libc), so they still need to be unconditionally be linked against. I.e. there has been no change in amount of work that is done by the linker.

**Comment by kripken** [comment]
I see, thanks @juj!
