### ISSUE TITLE
Question: what does this mean "wasm streaming compile failed: LinkError: import object field '_t_pShadowStackTop' is not a Number"

### ISSUE THREAD

**Issue by yowl** [emscripten-core/emscripten#10047]
I have the following cpp
```
extern Object **t_pShadowStackTop;
```
and I have in another llvm bitcode file the following emitted:
```
 s_shadowStackTop = LLVM.AddGlobal(Module, LLVM.PointerType(LLVM.Int8Type(), 0), "_t_pShadowStackTop");
                    LLVM.SetLinkage(s_shadowStackTop, LLVMLinkage.LLVMInternalLinkage);
                    LLVM.SetInitializer(s_shadowStackTop, LLVM.ConstPointerNull(LLVM.PointerType(LLVM.Int8Type(), 0)));
                    LLVM.SetThreadLocal(s_shadowStackTop, LLVMMisc.True);         
```
 I `emcc` with 
```
"E:\GitHub\emsdk\fastcomp\emscripten\emcc.bat" "E:\GitHub\corert\tests\src\Simple\HelloWasm\obj\Debug\wasm\native\HelloWasm.bc" -o "E:\GitHub\corert\tests\src\Simple\HelloWasm\bin\Debug\wasm\native\HelloWasm.html" -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s DISABLE_EXCEPTION_CATCHING=0 --emrun  "E:\GitHub\corert\tests\\..\bin\WebAssembly.wasm.Debug/sdk/libPortableRuntime.bc" "E:\GitHub\corert\tests\\..\bin\WebAssembly.wasm.Debug/sdk/libbootstrappercpp.bc" "E:\GitHub\corert\tests\\..\bin\WebAssembly.wasm.Debug/sdk/libSystem.Private.CoreLib.Native.bc"  -g3
```
Where the llvm is emitted to HelloWasm.bc and the cpp to `libPortableRuntime.bc`.  Do I need to explicitly say somehow how to link this `extern`?

**Comment by sbc100** [comment]
This mean you the symbol `t_pShadowStackTop` was undefined at link time. 

First thing I recommend doing is to stop building with `ERROR_ON_UNDEFINED_SYMBOLS=0`.  This will give you your errors at build time which is way better than getting them at runtime.

I'm not sure, but I think the problem here might be the leading underscore in the name of your global.   I think the underscores get added automatically by fastcomp so bitcode symbols themselves shouldn't have leading underscores.

**Comment by yowl** [comment]
Thanks, noted on the `ERROR_ON_UNDEFINED_SYMBOLS` (I have a bunch of others so would like to do this but can't right now).    I removed all the leading underscores and changed the linkage to `LLVMAvailableExternallyLinkage` and that has cured it.
