### ISSUE TITLE
Building Standalone WASM with TOTAL_MEMORY

### ISSUE THREAD

**Issue by danec020** [emscripten-core/emscripten#10049]
I have been working with Standalone WASM's and I was looking to have my WASM determine its memory size. That way I wouldn't have to create a Memory object in JS and pass it to the Module. I am currently using this to compile my cpp file.
``emcc renderer.cpp -s STANDALONE_WASM=1 -O1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -o renderer.wasm -s TOTAL_MEMORY=1MB -s TOTAL_STACK=10KB``

This is halfway working. When you check the buffer size of the Module.memory, it is correct. The issue I am having, when mallocing linear memory greater than 1024kb, any memory after the initial 1024 is corrupted. So if you malloc(2048) and use that to hold an array of Intergers or anything really, after you surpass the 1kb mark, your data seems corrupted. 

Testing showed that the malloc(2048) did indeed allocate that memory though. The next malloc continued right after the firsts address + 2048.  

Is this a known issue and I should be always declaring my linear memory in chunks of 1kb? Seems very limiting and clunky and I hadn't seen anywhere stating they had to be 1kb sizes.

Thanks!
Dane

**Comment by sbc100** [comment]
No this is not a known issue or expected.  Can you post a simple example showing this corruption?        What do you man "your data seem corrupted"?

Your stack is very small, and when the stack overflows if can corrupt global data so that could be one explanation.   Can you see if setting you stack to 512k makes the issue go away?   We are currently considering a change to place the stack first in memory so if that is the issue it will be more obvious in the future.

**Comment by danec020** [comment]
When building a simpler example I found the code worked as intended thus there has to be a corruption issue with my original code somewhere. It was just unlucky it happened exactly after 1KB I am guessing. Sorry for opening the issue.
