### ISSUE TITLE
Custom impl of std::random_device?

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#10068]
Right now we use libc++'s impl, which accesses `/dev/random` as a file. That brings in the filesystem support code which is bad for code size, and also as filesystem code it currently gets proxied to the main thread.

Instead, a simple C++ impl could just call `emscripten_random` which calls into JS.

This might be upstreamable into libc++. If not, maybe we can have a directory of things that override the default files in libc++?

**Comment by sbc100** [comment]
A separate file or a local patch to libc++ seem reasonable.

Upstream would be even better

**Comment by Akaricchi** [comment]
> Instead, a simple C++ impl could just call emscripten_random which calls into JS.

`emscripten_random` just calls `Math.random`, which isn't cryptographically secure. On the other hand, `/dev/random` is emulated with the crypto API, and actually refuses to work if that's not available. So do we want `std::random_device` to be a real entropy source or not? [cppreference](https://en.cppreference.com/w/cpp/numeric/random/random_device) says it's fine to implement it as a deterministic PRNG (it says nothing about the nature or quality of the PRNG):

> std::random_device may be implemented in terms of an implementation-defined pseudo-random number engine if a non-deterministic source (e.g. a hardware device) is not available to the implementation. In this case each std::random_device object may generate the same number sequence.

If we don't care about real randomness, then wouldn't it be better to implement a tiny and fast PRNG in C++ like splitmix64 or [the xoshiro family](http://prng.di.unimi.it/), to avoid calling into JS every time? `emscripten_random` can be used to just seed it once.

Otherwise, `crypto.getRandomValues` should be exposed more directly by emscripten (an `emscripten_get_entropy` function?)

**Comment by Akaricchi** [comment]
Well here's SplitMix64

```c
uint64_t splitmix64(uint64_t *state) {
	uint64_t z = (*state += 0x9e3779b97f4a7c15);
	z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9;
	z = (z ^ (z >> 27)) * 0x94d049bb133111eb;
	return z ^ (z >> 31);
}
```

And xoshiro256++

```c
static inline uint64_t rotl(const uint64_t x, int k) {
	return (x << k) | (x >> (64 - k));
}

static uint64_t s[4];

uint64_t next(void) {
	const uint64_t result = rotl(s[1] * 5, 7) * 9;

	const uint64_t t = s[1] << 17;

	s[2] ^= s[0];
	s[3] ^= s[1];
	s[1] ^= s[2];
	s[0] ^= s[3];

	s[2] ^= t;

	s[3] = rotl(s[3], 45);

	return result;
}
```

There are plenty other potential options too.

**Comment by sbc100** [comment]
Unless we have a compelling reason I think we should just call the existing emscripten JS function rather than inventing more than one way to do this.

**Comment by kripken** [comment]
I think the JS function is [documented as pointing to `Math.random`](https://emscripten.org/docs/api_reference/emscripten.h.html#c.emscripten_random), so it has that behavior. But `std::random_device` according to the spec doesn't need those requirements, and implementing a fast compact PRNG in C would be more efficient (avoiding calls to JS).

I'd be in favor of the most compact of the reasonable C PRNGs.

**Comment by ad8e** [comment]
My cultural understanding of ``std::random_device`` is that its major purpose is to act as a seed sequence, and that its fallback to nondeterminism is seen as a regretful spec mistake. (Even without this problem, it has other critical flaws.) "return 0;" can be considered for a deterministic ``std::random_device``. This is because no deterministic PRNG satisfies the main purpose of providing a seed sequence, so an obviously failing sequence has some advantages over a "secretly" failing sequence.

Fine C PRNGs are:

http://prng.di.unimi.it/xoshiro128plusplus.c
https://en.wikipedia.org/wiki/Permuted_congruential_generator#Example_code
https://github.com/svaarala/duktape/blob/master/misc/splitmix64.c

They are all reasonably small and behave reasonably well. The performance and quality difference between them is marginal for reasonable uses of ``std::random_device``. [Other PRNGs, sorted by most recent first,](https://en.wikipedia.org/wiki/List_of_random_number_generators#Pseudorandom_number_generators_(PRNGs)) may also be fine, but there's little point in testing them.

**Comment by peteroupc** [comment]
> 
> 
> My cultural understanding of `std::random_device` is that its major purpose is to act as a seed sequence, and that its fallback to determinism is seen as a regretful spec mistake. (Even without this problem, it has other critical flaws.) "return 0;" can be considered for a deterministic `std::random_device`. This is because no deterministic PRNG satisfies the main purpose of providing a seed sequence, so an obviously failing sequence has some advantages over a "secretly" failing sequence.

And in fact, the situation with `random_device` in this respect may be much worse: https://github.com/cplusplus/papers/issues/786 .  Here, it seems that the direction is to "bring a proposal for deprecating `std::random_device::entropy`", which is the only way, in theory, to determine whether `random_device` is implemented as a deterministic engine.  With such a change, `random_device` could eventually go from "falling back to a random engine _without much warning_" to "falling back to a random engine _without any warning at all_".  As this [Stack Overflow question](https://stackoverflow.com/questions/18880654/why-do-i-get-the-same-sequence-for-every-run-with-stdrandom-device-with-mingw) shows, this problem is not merely theoretical.
