### ISSUE TITLE
CMake find_path's PATHS argument is not observed (via emcmake, etc.)

### ISSUE THREAD

**Issue by DavidLudwig** [emscripten-core/emscripten#10078]
When using CMake in conjunction with Emscripten's CMake toolchain file (such as applied via 'emcmake'), the CMake ```find_path``` command will reliably fail to find files that are in directories specified in find_path's PATHS argument.

For example, given a project with two files, ```foo.txt``` (empty) and ```CMakeLists.txt``` (contents to follow), both in the same directory, and with CMakeLists.txt being the following:

```
cmake_minimum_required(VERSION 3.15)
project(test-bug-find_path)
find_path(FOO foo.txt PATHS "${CMAKE_CURRENT_LIST_DIR}")
if (NOT FOO)
    message(FATAL_ERROR "Can't find directory that contains foo.txt")
endif()
``` 

If the above project is compiled with plain, non-Emscripten CMake (i.e. without emcmake, or with Emscripten's CMake toolchain file), cmake will run successfully, finding ```foo.txt``` as expected.

If the above project is compiled with Emscripten CMake (with emcmake, or with Emscripten's CMake toolchain file), CMake will fail, with ```foo.txt``` never being found.

This seems related to Emscripten's CMake toolchain file setting a CMAKE_FIND_ROOT_PATH, and then setting various CMAKE_FIND_ROOT_PATH_* variables to ONLY, which seems related to using Emscripten as a cross-compiler and not using system-provided libraries, headers, etc.

Might there be a way to get Emscripten to look for it's own 'system' libs, headers, etc. without breaking find_path for user-provided CMake scripts, installing custom content into Emscripten's 'system' directory, or mandating Emscripten-specific modification to user-provided CMake scripts?

**Comment by sbc100** [comment]
Sounds like something that we should fix.

**Comment by DavidLudwig** [comment]
Minor update: I tweaked my original code-sample's content in order to invoke find_path(), which is referenced in this bug's title, and not find_file(), which is not.  Both functions do, as of Emscripten 1.39.5 (the current "latest" release in emsdk, as far as I see) under MacOS 10.15.2, exhibit behavior whereby PATHS isn't respected.  I'm unsure if this ought to warrant a new bug-report, but if it might help, I could file one, or modify this one further.

**Comment by sbc100** [comment]
I think it sounds like the same issue so one bug is fine.

**Comment by jhagmar** [comment]
I ran into this problem yesterday when trying to use FindBoost.cmake, that calls find_path() to find the location of Boost headers. I also believe that it is this bug that is the issue in [this StackOverflow question](https://stackoverflow.com/questions/59696327/compile-big-c-project-that-uses-cmake-to-webassembly/59944171#59944171).

Any hints on workarounds or where to address the problem in Emscripten would be appreciated.

**Comment by DavidLudwig** [comment]
@jhagmar Augmenting the CMake variable, CMAKE_FIND_ROOT_PATH, with "/", seems to do the trick for me.  Just note that system headers and libraries (from /usr/include, /usr/lib, and so on) might get picked up as well, though I am unsure of this last point.

Here's an example work-around:

```emcmake cmake path/to/CMakeLists.txt/ -DCMAKE_FIND_ROOT_PATH=/```

**Comment by jhagmar** [comment]
@DavidLudwig I think I understand how CMake find commands work under emconfigure/emcmake now, and I would argue that there is no bug.

The important thing to note is that find commands search the given PATHS/HINTS relative to the find root path(s). In "normal" CMake, the root paths include the system root, which is why a command such as `find_path(FOO foo.txt PATHS "${CMAKE_CURRENT_LIST_DIR}")` succeeds when not running under emconfigure.

Under emconfigure, the find root path `CMAKE_FIND_ROOT_PATH` is set to `<emsdk>/upstream/emscripten/system`, and other paths are excluded in the find commands through `set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)` and similar find mode variables. Since emscripten is a cross-compiler, this makes sense, since it prevents the build system from picking up host-native headers and libraries.

By augmenting `CMAKE_FIND_ROOT_PATH` with the system root "/" that you suggest, you essentially negate `set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)`. The command `find_path(FOO foo.txt PATHS "${CMAKE_CURRENT_LIST_DIR}")` will succeed, because the absolute path `${CMAKE_CURRENT_LIST_DIR}` will make sense as a relative path when glued on to "/". But, as you note yourself, the build system will start picking up unwanted host files.

The path I have taken after realizing this is to set the install prefix when building packages to a directory dedicated as the emsdk library root. When building packages that depend on other, previously built packages, `CMAKE_FIND_ROOT_PATH` is augmented with this directory in order to find the appropriate artifacts.

**Comment by MutterPedro** [comment]
Hello all, I am the author of the StackOverflow question mentioned above by @jhagmar. I am still having trouble to compile my C++ project to WebAssembly. I tried the `-DCMAKE_FIND_ROOT_PATH=/` workaround, but the same error occurs. The command I am running is :
```sh
emcmake cmake .. -DCMAKE_CXX_LINK_FLAGS=-no-pie -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_ROOT_PATH=/
```
And the errors is the following:
>CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1947 (message):
  Unable to find the requested Boost libraries.

 > Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  src/framework/CMakeLists.txt:205 (find_package)
  CMakeLists.txt:12 (include)


>CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Lua (missing: LUA_LIBRARY LUA_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  src/framework/cmake/FindLua.cmake:17 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/framework/CMakeLists.txt:217 (find_package)
  CMakeLists.txt:12 (include)

Ps: before throwing those errors, CMake logs the following warning:
>CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
>Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  src/framework/CMakeLists.txt:205 (find_package)
  CMakeLists.txt:12 (include)

**Comment by sbc100** [comment]
I've been looking into this issue while working on #14291.

One solution I found was to add `NO_CMAKE_FIND_ROOT_PATH` to:

```
find_path(FOO foo.txt PATHS "${CMAKE_CURRENT_LIST_DIR}" NO_CMAKE_FIND_ROOT_PATH)
```

That is basically saying not to look inside the sysroot when searching for this file.   Is that an acceptable solution?
