### ISSUE TITLE
Question : Web API/IDL DOM manipulation

### ISSUE THREAD

**Issue by yowl** [emscripten-core/emscripten#10084]
My understanding is that WebIDL will allow Wasm to manipulate the DOM without JS.  For that to happen Wasm will need WebIDL, interface adapters, (and other stuff most likely that I've missed due to a lack of understanding on my part).  All this does not exist yet, but from emscripten's points of view, or maybe its more a LLVM question, are you expecting emscripten to require a lot of changes to support this?

**Comment by kripken** [comment]
There definitely is significant work that needs to be done for all that to work. On the LLVM side, support for reference types etc., and on the emscripten side, binding improvements. All that is being worked on, but not sure if there's anything worth taking a look at yet, cc @tlively @jgravelle-google

**Comment by tlively** [comment]
There is a draft PR for adding reference types to the LLVM backend, but even you built it locally, there still would be nothing to look at because there are no corresponding clang patches for using that functionality. There is still a lot to do there, and that’s just for reference types. @jgravelle-google is actively working on interface types, though, so basic interface types may be implemented before reference types.

**Comment by yowl** [comment]
Thanks for the info.
