### ISSUE TITLE
Add some kind of install script to aid downstream packaging of emscripten

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#10169]
Today packaging emscripten is kind of pain and not well supported.   For example its not clear which files should be included in the package.  See:
https://github.com/emscripten-core/emscripten/issues/10093

This should be done in cooperation with downstream package maintainers (or at least one so we know it works).

Current packages of emscripten can be found here: https://repology.org/project/emscripten/versions

**Comment by yurivict** [comment]
You should implement the following items:
1. configuration step: configure command should check that all dependencies are installed.
2. installation procedure: it should install all required files into $DESTDIR$PREFIX
3. regression suit: there should be a command that runs some basic tests and makes sue they produce expected results.

Currently the FreeBSD port is broken because it has no ```binaryen``` dependency, and bonaryen also breaks with invalid compilation flags.

As another example, Arch linux port is broken for the same reason: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=emscripten-git

Brokenness of ports is a result of you not providing configuration/installation/regression procedures.

**Comment by juj** [comment]
Open source rarely works by placing demands on other people's free time. As has been stated before, Emscripten core team maintains distribution/installation via emsdk and via direct clone from repository.

If you would like to take the mantle of developing and maintaining Emscripten distributions to Linux distros you care about, or producing documentation to others for how they should do that, that would be great. You seem to know where to start the research already!

**Comment by yurivict** [comment]
I don't put demands, I am making a suggestion.

**Comment by kripken** [comment]
I think there might have been a misunderstanding here. Just to clarify - thanks @yurivict for the suggestions/ As @juj said, the main active devs here probably don't have time to look into it themselves, since we focus on emsdk packaging. But we'd be happy if someone did, and we'd like to help them. But it would require someone to take on the work.

**Comment by sbc100** [comment]
This was fixed in #10761
