### ISSUE TITLE
Do I have to use MinGW/WSL on Windows to get emcmake work?

### ISSUE THREAD

**Issue by shrinktofit** [emscripten-core/emscripten#10212]
I can't get `emcmake` work on Windows. 
![image](https://user-images.githubusercontent.com/28807867/72403720-0bbc6080-378e-11ea-93f5-2f31f137d931.png)

Here's a similar issue but closed: https://github.com/emscripten-core/emscripten/issues/4364 . This issue only suggest that Windows user can only use `emcmake` through WSL.

**Comment by sbc100** [comment]
Do you have cmake itself installed in your PATH?

**Comment by shrinktofit** [comment]
> Do you have cmake itself installed in your PATH?

Yes, I can directly run `cmake`.

**Comment by juj** [comment]
Try running via the emcmake.bat instead of invoking directly in python. I wonder if that might have any difference.

Also, emcmake wrapper itself does not need MinGW or WSL (not sure if anyone has tested it to work on WSL), but for CMake you do need a generator. MinGW Makefiles is a good one (there is a mingw toolchain in emsdk that enables MinGW Makefiles), also Ninja works quite well. If you do get emcmake running and it chooses to target Visual Studio, then it means CMake was unable to find a suitable generator. (emcmake does not work on Visual Studio generator)

**Comment by juj** [comment]
Try running via the emcmake.bat instead of invoking directly in python. I
wonder if that might have any difference.

Also, emcmake wrapper itself does not need MinGW or WSL (not sure if anyone
has tested it to work on WSL), but for CMake you do need a generator. MinGW
Makefiles is a good one (there is a mingw toolchain in emsdk that enables
MinGW Makefiles), also Ninja works quite well. If you do get emcmake
running and it chooses to target Visual Studio, then it means CMake was
unable to find a suitable generator. (emcmake does not work on Visual
Studio generator)

su 19. tammik. 2020 klo 4.25 Leslie Leigh (李的序) (notifications@github.com)
kirjoitti:

**Comment by shrinktofit** [comment]
> Try running via the emcmake.bat instead of invoking directly in python. I wonder if that might have any difference.

Thx. Directly running emcmake works.
