### ISSUE TITLE
Unexpected Error with miniaudio library

### ISSUE THREAD

**Issue by wini3d** [emscripten-core/emscripten#10213]
I'm curious as to why this is throwing exception and unexpected errors with emscripten 1.35, but not with latest?

https://github.com/dr-soft/miniaudio/issues/125
https://raw.githubusercontent.com/dr-soft/miniaudio/master/miniaudio.h

Demo:
https://wini3d.github.io/miniaudio/test.html

**Comment by juj** [comment]
The error comes from line

 function() { { var device = miniaudio.get_device_by_index($0); if (device.scriptNode !== undefined) { device.scriptNode.onaudioprocess = function(e) {}; device.scriptNode.disconnect(); device.scriptNode = undefined; } if (device.streamNode !== undefined) { device.streamNode.disconnect(); device.streamNode = undefined; } device.webaudio.close(); device.webaudio = undefined; if (device.intermediaryBuffer !== undefined) { Module._free(device.intermediaryBuffer); device.intermediaryBuffer = undefined; device.intermediaryBufferView = undefined; device.intermediaryBufferSizeInBytes = undefined; } miniaudio.untrack_device_by_index($0); }, deviceIndex, deviceType },

it looks like the EM_ASM block was somehow badly formatted in code. Try adding extra `()` or `{}` around `EM_ASM`, e.g. `EM_ASM({ ... }, params...);` to make sure it parses correctly in C/C++ compiler.

In particular the above should start with `function($0) {` instead of `function() {`, which suggests the compiler misparsed it.

**Comment by wini3d** [comment]
Thanks. Adding the ($0) manually still throws an error. Here's what is showing on the console:

https://github.com/dr-soft/miniaudio/issues/125#issuecomment-574870918

**Comment by wini3d** [comment]
Updating to the latest solves this issue.
