### ISSUE TITLE
"unreachable" OpenSSL function

### ISSUE THREAD

**Issue by TuckWa** [emscripten-core/emscripten#10226]
We've been having this problem with one function in OpenSSL:
https://github.com/openssl/openssl/blob/OpenSSL_1_1_1a/crypto/evp/digest.c#L54

When we hit this function I see the cryptic exception **unreachable:EVP_MD_CTX_free**
Normally, an error like this would mean to me that we're simply hitting an undefined function, but that's not the case here. All i can find about this error is the WASM spec specifying that this is an inserted trap meant for functions that don't return. 

The main problem I'm having is that I don't have a real indication of where this is coming from, why it was added (and only to this function, from what i can see in the .wasm), and what it _means_. 
Is this something emscripten is adding? Is it coming from clang? Would it indicate a problem with the function itself, or could it be in the way we use it?

For reference, we are building OpenSSL in a "shared" configuration, and statically linking libcrypto.so(obviously not a real shared library) to everything else when generating the final .wasm. This is with OpenSSL 1.1.1a and Emscripten 1.39.5

**Comment by kripken** [comment]
There might be more info in the JS console or debugger, with a full stack trace. But if that's an `unreachable` exception, it means and `unreachable` instruction was executed. clang will emit those for things like `__builtin_unreachable` or `__builtin_trap` (ways to tell the C/C++ compiler that a region of code should never be reached), and also for things like a function with a non-void return type but somehow control flow has reached a location without a return of a value.

To investigate you might build without optimizations (to avoid inlining) and then inspect the wasm emitted for that function. If it's not clear feel free to paste the source + wasm here.

**Comment by sbc100** [comment]
Actually this special `unreachable:` prefixed function name is one that is generated by the linker when there is a signature mismatch.

You should be seeing linker warnings about this? 

We use the `unreachable:` prefix because the body of the function contains only unreachable, but I see now that perhaps we could call its something more meaningful, such as "signature_mismatch:"?

See https://github.com/llvm/llvm-project/blob/master/lld/wasm/SymbolTable.cpp#L722

**Comment by TuckWa** [comment]
Good catch, thanks! I had looked around in this project hoping that it was emscripten itself adding it.

During linking, the signature mismatch warning was being output immediately before thousands of instances of "wasm-ld: warning: unexpected existing value for R_WASM_MEMORY_ADDR_I32", which I haven't dug on yet. I feel like function signature mismatches were errors in the past but i may be mistaken.

Is there a flag I can specify that would treat those llvm warnings as errors? 
Also, is there a reason why there isn't a more descript runtime error and they just use the generic "unreachable:" ?

**Comment by TuckWa** [comment]
For context on the actual mismatch: 
One of the things we build as part of our project is a small library that contains wrappers around many OpenSSL functions. The openssl headers that were used for this didn't contain any declaration of EVP_MD_CTX_free, so when building the library EVP_MD_CTX_free was assumed as having an int32 return rather than the correct void. Is this standard when you don't have a function available?.

**Comment by sbc100** [comment]
If you don't forward declare your function then I believe C will assume it returns and int yes.

You can turn warning into errors with `-Wl,--fatal-warnings`.. although you will also need to modify `SUPPORTED_LLD_LINKER_FLAGS` in emcc.py in order to allow that to pass through.

The reason we don't make it an error is that cmake always includes a signature mismatch when testing for functions.  

The reason we can't give a better error at runtime is that the function is generated by the linker and it doesn't have any better way to generate a runtime error (at least none that I can think of).

I think the best we can do is rename that `unreachable:` prefix to something more readable.

**Comment by sbc100** [comment]
See https://reviews.llvm.org/D72881

**Comment by TuckWa** [comment]
Wow, thanks a ton, @sbc100. Appreciate the help and the error naming change!
