### ISSUE TITLE
g++ -fpermissive similar option

### ISSUE THREAD

**Issue by wini3d** [emscripten-core/emscripten#10223]
I'm trying to port a g++ code to em++ which allows conversion from void* to a custom type using g++ `-fpermissive`, it actually is a port from C and works without errors and warnings compiling with emcc when it is set as .c file.

Is there a similar flag/option that allows this to work?

**Comment by kripken** [comment]
Looks like `clang++` also has `-fpermissive`, so `em++` should support it automatically - does that not work?

**Comment by wini3d** [comment]
yes, it's still throwing errors using `em++`

**Comment by sbc100** [comment]
Can you post a snippet of example code that generates this warning?

**Comment by wini3d** [comment]
@sbc100 
sure, here you go:
```
#include <stdio.h>
#include <stdlib.h>

void * obj(int size)
{	
	return malloc(size);
}

typedef struct mystruct * data;

struct mystruct {
	const char * name;
};

int main(int argc, char *argv[]) {

	data sample[1];	
	sample[0] = obj(sizeof(struct mystruct));
	sample[0]->name = "wini3d";

	printf("%s", sample[0]->name);
	return 0;
}
```
**g++**
```
test.c: In function 'int main(int, char**)':
test.c:18:41: error: invalid conversion from 'void*' to 'data {aka mystruct*}' [-fpermissive]
  sample[0] = obj(sizeof(struct mystruct));
                                         ^
```

**Comment by sbc100** [comment]
I simplified you test case a little:

```
struct mystruct {
  const char * name;
};

void bar() {
  void* foo;
  struct mystruct* sample = foo;
}
```

This is valid C but invalid C++.

It works if you use the C compiler rather than the C++ compiler:

```
$ gcc -c test.c 
$ clang -c test.c 
```

With the C++ compiler you get errors from both g++ and clang++ as you have seen:

```
$ g++ -c test.c 
test.c: In function ‘void bar()’:
test.c:7:29: error: invalid conversion from ‘void*’ to ‘mystruct*’ [-fpermissive]
   struct mystruct* sample = foo;
                             ^~~
```

```
$ clang++ -c test.c 
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
test.c:7:20: error: cannot initialize a variable of type 'struct mystruct *' with an lvalue of type 'void *'
  struct mystruct* sample = foo;
                   ^        ~~~
1 error generated.
```

g++ with -fpermissive turns this into a warning.  clang++ doesn't seem have any way to disable this error.

This is one of those areas were emscripten can't do anything differently to upstream clang since that is our compiler frontend.  If you can make this work with regular `clang++` then the same technique will work with `em++`.   If not, you will have use the C compiler, or modify your code.

If you feel strong that -fpermissive should do that same thing in clang++ that is does in g++ you could try asking upstream clang developers.

**Comment by wini3d** [comment]
I see. Yes, I figured it is more of a clang issue rather than emscripten.

btw, can you still use g++ as the compiler instead of clang?
https://github.com/emscripten-core/emscripten/issues/437

**Comment by sbc100** [comment]
As far as I know emscripten never supported gcc

**Comment by wini3d** [comment]
> As far as I know emscripten never supported gcc

I see. that's really weird, I don't know how I compiled those years of c++ code to before while now I am getting errors that I am only encountering when I have updated to the latest. must be the clang version? but 1.35 is still throwing errors when I reverted back.

**Comment by kripken** [comment]
Perhaps clang got more strict about c/c++ differences? Or perhaps the project used to use CC instead of CXX, or somehow an environment change causes the c++ frontent to be used somehow?
