### ISSUE TITLE
Running npm install adds a diff

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#10294]
```
$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: google-closure-compiler-osx@20191111.0.0 (node_modules/google-closure-compiler-osx):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for google-closure-compiler-osx@20191111.0.0: wanted {"os":"darwin","arch":"x64,x86"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: google-closure-compiler-windows@20191111.0.0 (node_modules/google-closure-compiler-windows):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for google-closure-compiler-windows@20191111.0.0: wanted {"os":"win32","arch":"x64,x86"} (current: {"os":"linux","arch":"x64"})

audited 39 packages in 1.049s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details



$ git diff
diff --git a/package-lock.json b/package-lock.json
index b36751ec3..849dc1c7c 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -82,7 +82,9 @@
         "chalk": "2.x",
         "google-closure-compiler-java": "^20191111.0.0",
         "google-closure-compiler-js": "^20191111.0.0",
+        "google-closure-compiler-linux": "^20191111.0.0",
         "google-closure-compiler-osx": "^20191111.0.0",
+        "google-closure-compiler-windows": "^20191111.0.0",
         "minimist": "1.x",
         "vinyl": "2.x",
         "vinyl-sourcemaps-apply": "^0.2.0"
@@ -98,12 +100,24 @@
       "resolved": "https://registry.npmjs.org/google-closure-compiler-js/-/google-closure-compiler-js-20191111.0.0.tgz",
       "integrity": "sha512-W3Oy5NF5CMgUv31CMbgLN7zhdCTVMTnNI//iEPYMotzXfX8viyOnTMipDDwJNeMnY7lfXbQrYOo+QkWP6WzZtg=="
     },
+    "google-closure-compiler-linux": {
+      "version": "20191111.0.0",
+      "resolved": "https://registry.npmjs.org/google-closure-compiler-linux/-/google-closure-compiler-linux-20191111.0.0.tgz",
+      "integrity": "sha512-pxxB83Ae7G9OHFSOEzOYlp844YyqQgU1RXBpCGBKeDAQrs3dykHqRhNGZdI7N1tsby/pT+hKL1US2l/CslPqag==",
+      "optional": true
+    },
     "google-closure-compiler-osx": {
       "version": "20191111.0.0",
       "resolved": "https://registry.npmjs.org/google-closure-compiler-osx/-/google-closure-compiler-osx-20191111.0.0.tgz",
       "integrity": "sha512-sviL1DLN+dDfYBLzmU6+2Yk19P1uzUHQuKaXrHxEYZkU4jTJNq/TC4xi6t0ZgvLQEm2Vf7xhOrt80TYKnoQaVg==",
       "optional": true
     },
+    "google-closure-compiler-windows": {
+      "version": "20191111.0.0",
+      "resolved": "https://registry.npmjs.org/google-closure-compiler-windows/-/google-closure-compiler-windows-20191111.0.0.tgz",
+      "integrity": "sha512-iKdz2bWrrM4zLv3USCRtWX4kLWzZhbj/afh/W6giLxg5XQzbNg+UpVF+2G6f/LEYK9UNBgS2TdyNTuw8mod+Mg==",
+      "optional": true
+    },
     "has-flag": {
       "version": "3.0.0",
       "resolved": "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz",
```

Are developers expected to have to always remove this diff before submitting a PR? Or is this something we should commit?

cc @juj @sbc100

**Comment by juj** [comment]
Two thoughts:

1) Try deleting `node_modules/` and then git reset the working tree. Does `npm install` then produce a change? In other words, `npm install` will produce changes to package-lock.json if user's `node_modules/` directory happened to have some custom edits that came about via other means.

2) Instead of running `npm install`, run `npm ci`. (with `node_modules/` nuked) Does that cause a package-lock.json change?

**Comment by juj** [comment]
https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json has some info. Seems there is a bit of controversy about user workflows there.

It might be that `npm ci` would be the command we want, instead of `npm install`.

**Comment by sbc100** [comment]
Interesting.  For me this diff doesn't get generated on first run (after nuking node modules).  But it does get generated the second time I run it.

`npm ci` never seems to generate this issue.   BTW, I didn't know about that command. We should presumably be using that when we run in CI :)

**Comment by juj** [comment]
The way I understand it, it might be that our users will want to run `npm ci` as well. The behavior of `npm install` seems just odd and weird, as other people very vocally note in the thread.

**Comment by sbc100** [comment]
Agreed.  I do find this rather strange.   

Would another option be to simply remove the package-lock.json file from git?  I guess that would make things less reproducible.

I also find it strange the they say that `npm ci` is fast than `npm install` because it starts by completely removing node_modules.  I would have through that would make it slower.

**Comment by sbc100** [comment]
Regardless, why are there differences in the contents of the lock file between the checked in one and the one that we generate?  I would expect to see that if a minor version bumped or something but in this case the versions look identical, just with some extra entries.

**Comment by juj** [comment]
I think we should want to have every single version should be locked, we don't want to enable automatic updates of anything, not even by a minor versions.

Hmm it's annoying that `npm ci` nukes everything..

**Comment by juj** [comment]
`npm ci` can solve the issue for CI bot, but it is not good practice for emsdk/end users, because it will always repeat the installation, slowing down install times. I think given that `npm install` causes a diff to package-lock.json, we should just go and remove package-lock.json altogether from the repository and put it to .gitignore, until https://github.com/npm/npm/issues/21043 is fixed.

**Comment by sbc100** [comment]
Hopefully #10306 makes this issue go away.

For what its worth the npm developers seems to think that clean install via `npm ci` is actually faster than regular `npm install`.  Perhaps because a dirty install needs to do so much extra checking of the existing node_modules tree?  Perhaps because all the data to be installed is already cached somewhere like $HOME/.npm anyway?
