### ISSUE TITLE
Consider using assertFileContents for JS output with MINIMAL_RUNTIME

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#10301]
Now that we have MINIMAL_RUNTIME which is designed to output a minimal amount of support JS code, it think it would be nice to see exactly how a given change effects that output JS.

We have an assertFileContents which can be used to maintain a golden files which can be automatically updated as the expected output changes using `EMTEST_REBASELINE=1` environment variable.

If we use this method then any change to the code that generates the minimal JS will end up being accompanied by the change to the expected output.   This would probably only make sense for `-00` (or some opt level that doesn't do JS minification).

I for one would like to see how my changes effect the output (and how the changes made my others do) without having to run emscripten before and after the change and do a manual diff.

I was thinking we could just start with 1 or 2 minimal tests such as `
test_minimal_runtime_hello_world`.

Thoughts?  @juj and @kripken

**Comment by juj** [comment]
> it would be nice to see exactly how a given change effects that output JS.

> This would probably only make sense for `-00` (or some opt level that doesn't do JS minification).

Yeah, the reason why I went with just code file size tests is that the output JS is minified, and doing small changes to a variable or two often relayouts the whole output for minification, so all variables end up shifting their minified var names by a character or two. That makes diffing much harder.

I have not been as bold as to propose code size tests for -O0 builds - I thought that would have been a big point to complain, as there is still a lot in Emscripten that depends on minification and optimization passes to optimize the code size for.

Current test_minimal_runtime_code_size would be good to be updated to support EMTEST_REBASELINE=1 though, as one does need to manually copy-paste the expected size numbers in otherwise.

Btw looking at the above commit, I am not a big fan of the @parameterized machinery. It feels more bloated compared to a simple one-liner for loop, and it is not easy to nest multiple levels of args permutations with that, e.g. single_file=1 enabled or not, times wasm=0 or wasm=1. Also often when I see a failing test on the CI, I search for test_core/test_browser.py for the name of the failing test, but with @parameterized, you cannot find it, and then after scratching your head for a minute or two, you remember to look for a name prefix, and then start to work to piece together what the test combo is. Reading a for loop-based test seems to be much easier for my thought and work process.

**Comment by juj** [comment]
> it would be nice to see exactly how a given change effects that output JS.

Oh, storing the files instead of just the lengths might help us diagnose why we need a couple of bytes of slop in the build sizes atm - currently the build outputs are not deterministic across machines or OSes.

**Comment by sbc100** [comment]
Lets discuss the use of @parameterized separably in #10302.  Its actually un-related to this change.

I've got another PR I'm working on to prototype what I'm talking about here.  

I have had some success using `-O3 --closure=0 --minify=0` .. it seems produce relatively meaningful and representative results.

**Comment by kripken** [comment]
Maybe it would be useful to have a tool that gets a build command and a branch name, and shows the diff between the outputs between the two branches on that command? (I agree that adding JS outputs might be too far - too many PRs would need to update those).

**Comment by sbc100** [comment]
Yes, many PRs would need to update these diffs, but that process is automated and trivial.  And the result would be that reviewers of the PR to see the effects of changes very clearly.

Kind of like in llvm where if you change the compiler output you also need to change a whole bunch of test expectations (except there is not always automate-able!).  We do this binaryen too.

I'm only proposing this initially for a couple of minimal tests so only PRs that touch the fundamentals would would be effected initially.

**Comment by kripken** [comment]
I think that while the process is simple with stuff like REBASELINE, it does pose an annoyance for new contributors, which might be a factor against it. (However, if we could automate that - so just opening a PR applies a commit with that - I wouldn't have that concern.)

A tool that shows a code output diff for a PR, that we can run on the commandline, seems like it would provide much of what you want, though?

I'm not strongly opposed to this, though. If you think it's useful we can try it out, and worst case we can remove the tests or refine them (like we do with metadce outputs, where we removed some over time).
