### ISSUE TITLE
emscripten_pthread_attr_settransferredcanvases with std::thread

### ISSUE THREAD

**Issue by malytomas** [emscripten-core/emscripten#10307]
Is it possible to use this function with eg. std::thread or boost::thread?

If there was a function like emscripten_request_canvas_transfer that would do a blocking call to main thread and transfer the canvas from there to the original calling thread, this would make canvas transfer work irrespective of how the thread was created. This would also simplify/obsolete the `-s OFFSCREENCANVASES_TO_PTHREAD`.

**Comment by juj** [comment]
Currently transferring canvases is tied to thread creation, and only works with pthread api. It would be possible to implement a push model for` emscripten_transfer_canvas_to_thread(pthread_t)` to transfer a canvas to another thread after the thread has been created, but would require considerable refactoring. Not a bad idea though.

Unfortunately a blocking pull model `emscripten_request_canvas_transfer()` cannot be implemented because the worker cannot receive the canvas until control flow yields back to the worker event loop. That is because JS event loop can only pumped when no JS code is executing in the Worker.

**Comment by malytomas** [comment]
Could the blocking `emscripten_request_canvas_transfer` periodically call `emscripten_current_thread_process_queued_calls`? I think I have seen similar pattern to not block on the main thread. But I have no idea how applicable it would be here.

**Comment by juj** [comment]
It could, but it would not do anything as it cannot observe browser postMessage()s that the Web Worker is about to receive (a postMessage() would contain the transferred canvas). Only when the code yields back to the browser event loop, postMessages are pumped forward.
