### ISSUE TITLE
DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR and Shadow DOM

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#10311]
A user has repored that the new behavior, after removing the special `#canvas` behavior etc., is a problem with shadow DOM. IIUC the new behavior just does a `document.querySelector`, but that won't work with shadow DOM in all cases, as the canvas may not be accessible that way.

If that's correct, maybe we need to keep around special event targets?

cc @juj

**Comment by juj** [comment]
I don't know. Ask for a repro.

**Comment by kripken** [comment]
I've seen the repro (non-public codebase), I just don't know enough shadow DOM to understand it :smile: or write a minimal one myself, sorry.

The basic issue is that with shadow DOM, IIUC, one can't use a `document.querySelector` to get the canvas if it is inside a shadow DOM subtree (I may be using the terms wrong). The shadow DOM "encapsulates" its internal content. One has to traverse the shadow DOM subtree and select inside it or something nontrivial like that.

So the best thing is probably to get it from the Module object. For canvas, perhaps we can restore the `#canvas` special casing? Or maybe we can generalize the ID mechanism to allow stuff like `"Module.canvas"` meaning "get property 'canvas' from Module"?

**Comment by kripken** [comment]
ping @juj

**Comment by juj** [comment]
There are a couple of ways that I can think of that could be used to solve this in a way that does not require re-establishing "always there for all users" variables to `Module` or increase code size.

1. Following the method in PR #10594, it would be possible from custom JS library to route `_findCanvasEventTarget` to a `_findCanvasEventTarget_orig` variable, and then create a custom replacement to `_findCanvasEventTarget` that first does a custom lookup to e.g. `Module['canvas']` or to a custom established scheme on the input string (`"shadowDOM@myCanvasSelector"`) or something like that.

The drawback of that is that it will replace an internal field that is not guaranteed to stay the same, so may break in the future. Although it feels like Shadow DOM is such a special need that it may be most flexible to process it like that.

Alternatively, 

2. we could follow the same pattern we did with `PTHREAD_POOL_SIZE` to support `navigator.hardwareConcurrency`, and do
```diff
diff --git a/src/library_html5.js b/src/library_html5.js
index 2f9236cd3..9f302c3e4 100644
--- a/src/library_html5.js
+++ b/src/library_html5.js
@@ -332,7 +332,13 @@ var LibraryJSEvents = {
   },
 #else
   _findCanvasEventTarget__deps: ['_findEventTarget'],
-  _findCanvasEventTarget: function(target) { return __findEventTarget(target); },
+  _findCanvasEventTarget: function(target) {
+#if CUSTOM_CANVAS_LOOKUP_RULE
+    var customCanvas = CUSTOM_CANVAS_LOOKUP_RULE(target);
+    if (customCanvas) return customCanvas;
+#endif
+    return __findEventTarget(target);
+  },
 #endif

 #else
```
and let `CUSTOM_CANVAS_LOOKUP_RULE` resolve to either a function that does something manual on `target`, or let one directly specify `Module['canvas']` there or some other fixed thing to get a behavior that ignores `target` altogether.

Or perhaps instead of adding `-s` variables, we'd try formalizing the above to some kind of extension mechanism. For example, could we do
```diff
diff --git a/src/library_html5.js b/src/library_html5.js
index 2f9236cd3..9c25d9ee0 100644
--- a/src/library_html5.js
+++ b/src/library_html5.js
@@ -332,7 +332,13 @@ var LibraryJSEvents = {
   },
 #else
   _findCanvasEventTarget__deps: ['_findEventTarget'],
-  _findCanvasEventTarget: function(target) { return __findEventTarget(target); },
+  _findCanvasEventTarget: function(target) {
+#if userProvidedJsLibraryFunction('canvasLookup')
+    var customCanvas = {{{ userProvidedJsLibraryFunction('canvasLookup') }}} (target);
+    if (customCanvas) return customCanvas;
+#endif
+    return __findEventTarget(target);
+  },
 #endif

 #else
```
to make the linker generate specific code if a custom function is present in the link? (similar to how we have the has_library function?)

**Comment by kripken** [comment]
Interesting ideas @juj. I kind of think we should make this as easy as possible, ideally without the user needing to provide an entire js library just for this. So the second option seems best out of those three.

However, reading the code, I had another idea just now: findEventTarget does this:
```
    var domElement = __specialEventTargets[target] || document.querySelector(__maybeCStringToJsString(target));
```
So if a user does `__specialEventTargets['#canvas'] = myCanvasObject` then that would work, I think? If so maybe we can just document that. But maybe I'm missing something.

**Comment by kripken** [comment]
Ah, I was missing something, but I have an idea for how to make it work. Will open a PR in a bit.
