### ISSUE TITLE
Statically linked dependencies have broken strings and other issues

### ISSUE THREAD

**Issue by emily33901** [emscripten-core/emscripten#10355]
Hello,
Recently ran into this issue whilst trying to link dependencies to a main project which uses emscripten to target wasm. First encountered inside of imguis `DebugCheckVersionAndDataLayout` which prints the assertion ![](https://i.f1ssi0n.com/DevoutIllAffectedAardwolf.png) which as you can see has a mangled assert message.

I have attached a [simple meson project](https://github.com/emscripten-core/emscripten/files/4155587/linking-emscripten-test.zip) for a simple version of the same issue. Run meson initially with `meson --cross-file=emscripten.txt --wipe build` and then `cd build && ninja` to build it. This code does work if instead of creating a dependency and linking with it I instead just compile the dependency directly into my target output.

In this example (atleast for me) the printfs dont print anything and the returned string is garbaged by something.

Overall I'm not sure whether the underlying issue here is that I'm linking the problem wrong or whether its meson screwing up or whether I need to set some environment variables to make it build and link properly or similar.

Thanks in advance,
Emily.

**Comment by sbc100** [comment]
Could it be that when meason is creating the dependency its tying to build it as a shared object with `fPIC`?    (if so can you find a way to force it to assume static libraries and see if the fixes it.. if it does than this is an issue with fPIC that we need to address).

I would look at the differences in the way meason builds and links the dependencies compared to when compiler the dependency directly.   It might offer some clues as to what the real issue is here. 

Also, can you specify the version of emscripten you are using?

**Comment by emily33901** [comment]
Iirc its building .a files without -fPIC (because `pic: true` isn't specified in the static library configuration. Once again iirc it just passes the .a to the invocation of the linker at the end but I'll check that when I'm back at home and same with my emscripten version.

**Comment by emily33901** [comment]
Just tried compiling this on my linux box and it worked first time... So not sure what is going on there - could just be an outdated emscripten on my windows machine or similar. Ill report back when i get round to checking that

**Comment by emily33901** [comment]
Yeah tried on a mates windows laptop and looks like its probably becuase my emscripten is out of date... Gonna close this for now and if its still a problem ill reopen
