### ISSUE TITLE
getBinaryPromise() in asm.js module?

### ISSUE THREAD

**Issue by slimbuck** [emscripten-core/emscripten#10352]
Hi,

It seems the asm.js version of modules now include the function getBinaryPromise() which in turns uses Promises.

This means newly compiled fallback modules no longer work in IE.

Why does this code exist in the asm.js and can it possibly be removed from generated code?

**Comment by kripken** [comment]
This should be fixed in 1.39.6, thanks to #10064 - we include a small polyfill.

(The reason the code is included is that in our new JS support with the wasm backend the JS is made to look like it's using wasm APIs, which we polyfill. That makes things much simpler, removing a lot of old differences we had between the JS and wasm paths. However, we missed that it depends on Promise, and that was a bug until it was fixed in that PR.)

**Comment by slimbuck** [comment]
Hi @kripken,

With 1.39.7 toolchain:
- WASM=0 and WASM=1 still generates code with Promise and no polyfill.
- WASM=2 generates a different set of files (including .mem) with Promise but no polyfill.

Am I missing a setting perhaps?

Thanks!

**Comment by slimbuck** [comment]
(I am attempting to compile the basis transcoder for use in IE).

**Comment by kripken** [comment]
Oh, sorry, I forgot - we don't include the polyfill by default, only when supporting legacy browsers. To do that, build with `-s MIN_IE_VERSION=11` (or `-s LEGACY_VM_SUPPORT` to enable maximum support for all legacy browsers).

**Comment by slimbuck** [comment]
Yes that works. Thank you @kripken!
