### ISSUE TITLE
How To Have Generated JS Code Use let or const Instead of var In Strict Mode

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emscripten#10381]
Hi.  So as the title says, how do I have Emscripten-generated JavaScript code use `let` or `const` instead of `var`?  I enabled "strict mode" via `-s STRICT=1` when compiling code, but in the JS code there's still `var` being used.  How do I have it support the latest version of JavaScript and also have it not use `var` and other stuff that shouldn't be used?

**Comment by sbc100** [comment]
The emscripten codebase is currently written to support older versions of JS.  I believe we don't allow any ES6 features currently (correct me if I'm wrong @kripken?)

There is currently no way that I know of it have it produce anything else.

**Comment by kripken** [comment]
We don't use newer features in order to allow support of old browsers, correct.

Note that `var` is still ok to use, even if it may be slightly confusing for humans, and it's smaller than `const` too. But yes, modern JS tends to prefer `let/const` - that's just a preference, though, that's not a requirement of modern JS, `var` is still fully supported.

**Comment by DragonOsman** [comment]
Okay, I guess I'll just have to make do with editing the JS code on my own I don't want `var`.  I do understand it's still fully supported.  It's just considered bad practice to use it.  Just saying.

**Comment by TJKoury** [comment]
@kripken Just FYI, [unflagging es6 modules in Node >=13.2](https://github.com/nodejs/node/commit/796f3d0af49164314868c4778af90eca356f1fef) breaks the entire wrapper due to the use of `require`, and `__dirname`.

I have a build script now that is cleaning it up, would be willing to work on a flag that can integrate Node-specific es6 syntax.

**Comment by sbc100** [comment]
I think we would certainly accept patches for support the latest versions of node.   I see that as node-compatibility goal rather than a goal of moving to ES6.   Presumably node continues to full support ES5, right?

**Comment by TJKoury** [comment]
@sbc100 To be specific, Node does not support CommonJS modules if you use > Node 13.2.  While I applaud the push to make ES6 modules the official thing, the change is causing havoc on multiple projects of mine at the moment, and the Node community will certainly have its hands full if 13.2 or above becomes LTS.

**Comment by sbc100** [comment]
I'm pretty sure we would accept any patches required to make emscripten output work in 13.2, whatever that looks like (as long as it doesn't break out support for browsers).
