### ISSUE TITLE
Why isn't --use-preload-plugins enabled by default?

### ISSUE THREAD

**Issue by dom96** [emscripten-core/emscripten#10432]
I had to scour the issue tracker to find https://github.com/emscripten-core/emscripten/issues/5076 and get a hint that I may need to use the --use-preload-plugins flag.

The error I was getting from SDL was: "Unsupported image format". But is there any reason these plugins cannot be enabled when --preload-file is used or when an SDL plugin is used?

**Comment by kripken** [comment]
I think we don't enable them by default because they add overhead: each image for example is decoded, but if you don't need them decoded - maybe you use a compiled libpng to decode them - then that's wasted.

I agree we should document this better if it was confusing for you. Maybe an FAQ entry for that SDL error would be useful, or somewhere else - did you look in some place it should have been?

**Comment by dom96** [comment]
Do we have the ability to customise the SDL error message? maybe the best thing would be to change it to "Unsupported image format, have you compiled with --use-preload-plugins" or similar. Or maybe we could detect if any image formats are supported and then give that hint.

Btw any ideas if emscripten SDL supported loading SVG images? I received similar errors when trying :/

**Comment by kripken** [comment]
Not sure about the error message, cc @Daft-Freak 

Btw, another option aside from preloading is to use libpng, with `-s USE_LIBPNG` - I think SDL2_image would use that automatically.

About SVG, do you mean using preloading? I think don't SDL `IMG_Init` has a flag for that, https://www.libsdl.org/projects/SDL_image/docs/SDL_image_8.html Separately from SDL, looks like our preload plugins code has a list of mimetypes here:

https://github.com/emscripten-core/emscripten/blob/master/src/library_browser.js#L540

That doesn't include SVG, so it doesn't work currently, but perhaps it could be added.

**Comment by Daft-Freak** [comment]
By default, SDL2_image is compiled without any of the formats enabled (I can't remember why, probably code size reasons). We have a patch that tries to load from preloaded data, otherwise it fails with that error as no formats are supported. `-s SDL2_IMAGE_FORMATS='["png", ...]'` (I think that's the right syntax) can be used to enable formats which should automatically pull in any dependencies.

It looks like SDL2_image added SVG support in 2.0.2, we're still on 2.0.0 (latest is 2.0.5, which includes our patches).
