### ISSUE TITLE
Latest-upstream for WASM compilation

### ISSUE THREAD

**Issue by videetparekh** [emscripten-core/emscripten#10431]
Hey team,

I'm a complete Emscripten/LLVM noob and trying to figure out this monstrous environment as best as I can for a small project. I'm trying to compile from TVM's IR to WASM following this guide: https://github.com/apache/incubator-tvm/tree/master/web, but trying to generate a `.wasm` file instead of a `.js` file that the `fastcomp` asmjs backend is capable of generating. 

From reading through the documentation (https://emscripten.org/docs/porting/simd.html), I understand that TVM generates SIMD operations and that `fastcomp` doesn't support those, so I'm trying to use the `upstream` version instead. 

1. What I found is that the `latest-upstream` version does not have a `llvm-config` file in `emsdk/upstream/bin`, and so I have no feasible way of linking TVM to the `upstream` LLVM. Is my installation process incorrect? I'm following the guide here: https://emscripten.org/docs/getting_started/downloads.html

2. If not the above, what other version of `upstream` is there in `emsdk list` that you suggest I use, and that might support TVM?

Sorry for the dumb questions, and have a good weekend!

**Comment by sbc100** [comment]
The prebuilt version of llvm that we supply does not contains llvm headers or llvm-config or other things you might need if you want to extent llvm itself.  Its shipped as a standalone compiler.

I don't know what TVM is or how it wants to fit into emscripten here but you have a couple of options I think.

1.  Build llvm from source.   You can do however you like but one way to do it would be to use emsdk (`./emsdk install llvm-git-master-64bit`).  Once you have done that it should include all the development stuff you need to extend it or link with it

2. Build compatible bitcode files with a separate toolchain and pass those to emcc.   Any llvm 11.0 based toolchain should be able to produce bitcode files that are acceptable as inputs to emcc (as lone as the target triple is `wasm32-emscripten`).  For example if TVM is already available built aginat stock llvm.   

It could be that a lot of the instructions you are following no longer apply now that you are switching away from fastcomp since emscripten's llvm is now just vanilla upstream llvm.

**Comment by VirtualTim** [comment]
Just a warning, SIMD support in browsers is still pretty experimental. I _think_ currently only Chrome supports it with the `WebAssembly SIMD support` flag set.

Also personally I've had great success using [trzeci's docker image](https://hub.docker.com/r/trzeci/emscripten/tags) to build my Emscripten projects.
I basically do `docker run -it --rm -p 8080:8080 -v /c/source_location_on_local_disk:/src -w /src/subdirectory_for_build_script -u emscripten trzeci/emscripten:1.39.7-upstream bash` then run a shell script which configures some parameters, then runs `cmake --build . -- -s`.
It sounds like the easiest way to do this is pull the source, mount the docker image, mapping the source to an internal file, run `make web`. But theres a good chance that the makefile is out of date. But I guess you have to tackle one problem at a time.

**Comment by videetparekh** [comment]
@VirtualTim The tip about browser support was very useful. That is definitely something I'll have to take into account. I still have to try out the docker image but hopefully that makes my life easier. 

@sbc100 TVM is a toolchain to compile down from Python ML models to bitcode specific to architecture. It has the option to use LLVM to compile down to certain architectures and `wasm`. I installed `llvm-git-master-64bit` which installed LLVM version 11.0, but TVM seems to have issues with that. (I wanted to ask, as a side note, why Emscripten ships LLVM 11 even though the latest release according to LLVM's website is 9.0.1) 

I finally used an independent installation of llvm (LLVM-8 using `sudo apt-get`) and plugged that into TVM to get things up and running. After generating the bitcode file I passed it to `emcc` and managed to get the expected `wasm` file! I'm hoping this method survives some more complex testing.

**Comment by sbc100** [comment]
We depend on ToT llvm because we are simultaneously working on the wasm backing in upstream llvm.    Perhaps one day when the upstream backend is "done" and we don't want any more new features we can downgrade our coupling with llvm to depend on stable releases.   But I don't see that happening any time soon since WebAssembly is continuing to evolve and developers want to try out the latest features.

While you maybe be able to feed bitcode from llvm 8 into emscripten there is no guarantee that the bitcode will be compatible with llvm 11.   So, it if work thats great, but its not guaranteed by llvm.
