### ISSUE TITLE
ffmpeg compile error

### ISSUE THREAD

**Issue by Y0QIN** [emscripten-core/emscripten#10443]
I use emscripten version 1.39.4 to compile ffmpeg and error:
/emsdk_portable/clang/tag-e1.39.4/build_tag-e1.39.4_64/bin/llvm-ar: libavcodec/l
ibavcodec.a: Text file busy.
ffbuild/library.mak:21: recipe for target 'libavcodec/libavcodec.a' failed
make: *** [libavcodec/libavcodec.a] Error 1

But it success when I use version 1.39.4-upstream 
What's the difference?

Meanwhile I use the .a files which compiled by 1.39.4-upstream to compile my project and there  appered  --shared-memory error,Then I use version 1.39.4 to compile my project with those .a files and printed  undefined exported function: "_av_dict_set"

**Comment by kripken** [comment]
I'm not sure what could cause `Text file busy`. Perhaps a race condition in the build script? If not then a reproducible testcase could help. But as that's in fastcomp, which we are deprecating, perhaps best to focus on upstream.

An error on shared memory may be because some object files are compiled with pthreads and some are not. What's the full error message?
