### ISSUE TITLE
Webaudio crashes if heap resizes

### ISSUE THREAD

**Issue by Jonathhhan** [emscripten-core/emscripten#10488]
I wanted to ask if it is expected behaviour that Webaudio drops out if the heap resizes.
It makes a short noise, and then the page needs to be reloaded to have sound again.

This is an example message (in the Java Script console) when audio drops out:

`Heap resize call from 1073741824 to 1181548544 took 12.850000000034925 msecs. Success: true`

**Comment by kripken** [comment]
This definitely sounds like a bug = some view is likely not updated properly.

What API are you using for WebAudio? (SDL, OpenAL, something else?)

**Comment by Jonathhhan** [comment]
I use Open Frameworks with Emscripten, I think this is the audio API (sorry, I am not sure):
RtAudio
https://openframeworks.cc/documentation/sound/ofSoundStream/
or
https://github.com/openframeworks/openFrameworks/tree/patch-release/addons/ofxEmscripten/libs/html5audio

**Comment by kripken** [comment]
Ah, then I'd guess this is a bug in

https://github.com/openframeworks/openFrameworks/blob/patch-release/addons/ofxEmscripten/libs/html5audio/lib/emscripten/library_html5audio.js

in Open Frameworks. Specifically, it probably keeps a view alive to the old data. My guess is it's in `html5audio_stream_create`, where `inbufferArray` is captured once, then referred to from later callbacks, at which time it may be invalid. If that's it, the fix is to not create a subarray once and reuse it, but create one in each callback.

We should probably file an issue for them, unless you are one of the developers there?

**Comment by Jonathhhan** [comment]
Thanks for your answer. Great, so it  sounds solvable (I will try later)... No, I am not one of the developers. I think it would be very helpful to file an issue (or PR?). Would you do that? Because you understand the problem better. Otherwise I will do it, and reference/link to this issue...

**Comment by kripken** [comment]
Thanks for filing that issue - I'll follow that, and try to help if they have emscripten questions or anything!

Let's close this as it isn't a bug in this project.
