### ISSUE TITLE
Loading deadlock when --separate-metadata is used and resources are loaded in pre-run.

### ISSUE THREAD

**Issue by eugeneko** [emscripten-core/emscripten#10555]
Hello,

I'm not JS developer at all, and I'm trying to tackle this issue with resource loading.

There are two snippets of code generated by file_packager.py.
This one in main function:
```
   if (Module['calledRun']) {
    runMetaWithFS();
   } else {
    if (!Module['preRun']) Module['preRun'] = [];
    Module["preRun"].push(runMetaWithFS);
   }
```

This one in `loadPackage`, asynchronously called from `runMetaWithFS`:

```
    if (Module['calledRun']) {
      runWithFS();
    } else {
      if (!Module['preRun']) Module['preRun'] = [];
      Module["preRun"].push(runWithFS); // FS is not initialized yet, wait for it
    }
```

In my case, both snippets fall into `preRun` branch because... well, run is not called yet.
However, `preRun` callbacks have already finished executing at the moment of second snippet execution, because it is async. Therefore, `runWithFS` is never called.

This code drives all this process and execution never goes past `if (runDependencies > 0)`:

```
  preRun();

  if (runDependencies > 0) return; // a preRun added a dependency, run will be called later

  function doRun() {
    // run may have just been called through dependencies being fulfilled just in this very frame,
    // or while the async setStatus time below was happening
    if (calledRun) return;
    calledRun = true;
    Module['calledRun'] = true;
```

Am I missing something or it is plain logic bug?
Unfortunatelly, I cannot provide simple test because I have no idea how to use emscripten from scratch.

I can try to make test later, if necessary.

Thanks.

**Comment by Akaricchi** [comment]
Seems like a bug. I'll see if I can look into it tomorrow or so.

Out of curiosity, what is your use-case for `--separate-metadata`? I've been contemplating just plain removing this mode earlier.

**Comment by eugeneko** [comment]
@Akaricchi I have no clue, I'm just trying to make existing code work.
Maybe the author remembers, tho...

@weitjong Do you remember why we needed this feature and whether we need it now?
https://github.com/emscripten-core/emscripten/pull/3410

Urho uses it for debug only.
https://github.com/urho3d/Urho3D/commit/f9060b7831b5b2d417ba45f7bad13c01f1ebbb37#diff-9b346d758f1ac511ca2c7be75e595215R1116-R1118

**Comment by weitjong** [comment]
@eugeneko It was introduced to speed up the build time by preventing unnecessary re-linking being triggered due to js-output file changing in timestamp. As you know before the upstream LLVM WASM is available, the Emscripten's linking phase is really slow. By separating the metadata (like the UUID which keeps changing) from the js-output file and by carefully preventing file-packager.py to not changing js-output file's timestamp if there is indeed no change in its content, we have successfully achieved this goal at that time with this option.

Just a little more background. As you also know in Urho, we do everything in the build in a single bound, i.e. one `make` command. In order to do that, we have configured build rules to check if resource dirs got changed and if so invoke the file packager, and when the js-output file got change then there is build rule to trigger a link phase, etc, etc. All is good, except during development phase (presumably using Debug build config) and time was lost because the linking was being triggered unnecessarily just because the UUID got changed.

Fast forward to today, I don't think the intention in my original proposed code has been "preserved". And, I don't think the `--separate-metadata` is functioning as it used to be now. As such, personally I don't mind if it eventually get removed and I am not interested in fixing it either because the linking time with upstream LLVM backend is super fast and I have a new octa-core processor :)

**Comment by sbc100** [comment]
Sweeet!  Lets kill it.

**Comment by Akaricchi** [comment]
>By separating the metadata (like the UUID which keeps changing)

That's another issue I've been annoyed by, so much that I made my build system replace the random UUID with the package's sha256 sum (ugly hack). I think that should just be a feature of the file packager, I just never found the time to implement it or even bring it up...
