### ISSUE TITLE
implicit declaration of function 'arc4random' is invalid in C99

### ISSUE THREAD

**Issue by Beuc** [emscripten-core/emscripten#10709]
Hi,

When compiling libzip 1.6.1 with Emscripten I got:
```
libzip-1.6.1/lib/zip_random_unix.c:48:5: error: implicit declaration of function 'arc4random_buf' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    arc4random_buf(buffer, length);
    ^
libzip-1.6.1/lib/zip_random_unix.c:56:12: error: implicit declaration of function 'arc4random' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return arc4random();
           ^
2 errors generated.
```

These functions are provided by Emscripten:
https://github.com/emscripten-core/emscripten/blob/4b6eba96c40e58e83aa1c45dc565ac4e312cc6f7/src/library.js#L933
but don't seem to be declared.
If we're going for *bsd compatibility here, I believe function prototypes needs to be added to stdlib.h.

**Comment by sbc100** [comment]
I don't think we should be aiming for such compatibility.  

It looks like it was added in  a5c78a58902abd6166a81a895cc9eea141c9cab4, but without any explanation or tests, then has remained around since then including a test being added but without any rational that I can find.  Can we just remove this?  Its not present of any windows or linux desktop.  @azakai ?

**Comment by Beuc** [comment]
Thanks!
