### ISSUE TITLE
EXCEPTION_CATCHING_WHITELIST does not call destructors unless functions with stack-allocated objects are whitelisted

### ISSUE THREAD

**Issue by trylle** [emscripten-core/emscripten#10752]
It looks like every function within a catch has to be included in the whitelist for destructors of objects on the stack to be called - not only the function that catches exceptions. This makes the usability of EXCEPTION_CATCHING_WHITELIST very limited in practice.

Is this possible to fix? If not, maybe it should be documented so as not to lead other users astray.

Example:
```c++
#include <iostream>

struct resource
{
	resource() { std::cout << "alloc" << std::endl; }
	~resource() { std::cout << "dealloc" << std::endl; }
};

extern "C" void thrower() { throw 1; }

extern "C" void runner()
{
	resource t;

	thrower();
}

extern "C" void catcher()
{
	try
	{
		runner();
	}
	catch (...)
	{
		std::cout << "caught" << std::endl;
	}
}

int main()
{
	catcher();

	return 0;
}
```
Produces the following results:
```
> em++ test.cpp -s DISABLE_EXCEPTION_CATCHING=2 -s EXCEPTION_CATCHING_WHITELIST=[catcher] -o test.js && node test.js
alloc
caught
```
```
> em++ test.cpp -s DISABLE_EXCEPTION_CATCHING=2 -s EXCEPTION_CATCHING_WHITELIST=[catcher,runner] -o test.js && node test.js
alloc
dealloc
caught
```
```
> em++ --version
emcc (Emscripten gcc/clang-like replacement) 1.39.9 (commit a1153bdaa8e15dfbbe56ac5591c3e30f8824684b)
```

**Comment by kripken** [comment]
I believe that `runner` here will have some exception handling code for the RAII, or maybe the throw itself is inlined - either way, LLVM emits some exceptions code in the IR there. In general the whitelist mechanism is useful hack, but a hack - it expects you to know what needs to be in the whitelist, and that depends on how LLVM emits IR, which can be surprising.

I agree it would be good to document this - PR would be welcome!

In the long term, we are making good progress on native wasm exception support (the main emscripten-side PR has just been approved today actually). That will have very low overhead, like native builds, and so we won't need the complex whitelist mechanism (again, like native builds don't). For that reason I don't think it's worth spending time to try to fix this, especially as the fix is likely not simple.
