### ISSUE TITLE
How to compile C ++ AMP project with emcc

### ISSUE THREAD

**Issue by xmq1996** [emscripten-core/emscripten#10805]
For the C ++ AMP project, I just included the amp.h file in vs2015, and vs2015 can execute correctly. But when compiling with wasm, it will report amp.h errors; then I found the location of amp.h myself, included the path with -I in the emcc code, and then reported that many files were not found It is the official C ++ library), and I also add the path to the emcc code, and the final error will be a series of errors about the header file vcruntime.h.
My compile command is as follows:emcc -I "D:\vs2015.com_chs\VC\atlmfc\include" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt" -I "C:\Program Files (x86)\Windows Kits\8.1\Include\um" -I "C:\Program Files (x86)\Windows Kits\8.1\Include\shared" -I "D:\vs2015.com_chs\VC\include" main.cpp -s "EXPORTED_FUNCTIONS=['_getPoint']" -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" -s ERROR_ON_UNDEFINED_SYMBOLS=0 -o math.js

**Comment by xmq1996** [comment]
![image](https://user-images.githubusercontent.com/29848518/78005135-b72c8880-736d-11ea-9d55-15adbadd8df7.png)

**Comment by sbc100** [comment]
emscripten doesn't support any of the windows header files.    Since its a cross compiler you can't use header from the system you are building on (be that windows, linux or mac).   Any code that tried to include ctddbg.h would need to be modified to work with emscripten.

The first thing to do is to remove all the visual studio include paths, since you never want to include those headers.
