### ISSUE TITLE
How to bind constant array from C++ to JavaScript?

### ISSUE THREAD

**Issue by dirkarnez** [emscripten-core/emscripten#10801]
![image](https://user-images.githubusercontent.com/26408605/77929444-3ffae400-72dc-11ea-8eb4-31d430766c0e.png)
![image](https://user-images.githubusercontent.com/26408605/77929507-5143f080-72dc-11ea-8a9c-17b48c4fdc1d.png)

How do you guys bind constant array (e.g. of type `int`) to JavaScript? It seems not supported. Binding constant `int` is fine i tried.
The documentation mentioned binding `std::vector`, but i need to do some compile-time stuff and it seems `constexpr` is not for `std::vector`.

Thanks!

**Comment by jgravelle-google** [comment]
My guess from taking a quick look is that this would need to have WireType bindings set up for `std::array<int, n>`. [There's a number of types that have built in binding support](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#built-in-type-conversions), but note that in those examples STL types need to be declared explicitly, presumably because otherwise it's not clear which template instantiations are needed in the wasm side of things.

[There's a test that shows how to write a custom binding wrapper](https://github.com/emscripten-core/emscripten/blob/02532df58a7991c00d0bb31e0e95a16b9e779a24/tests/embind/test_custom_marshal.cpp), I imagine that kind of approach should work with `std::array<int, 5>`?

**Comment by dirkarnez** [comment]
Going to study how to write a custom binding wrapper, thanks!
However, i came up with some dirty work like this, which converts an array to vector before binding:

![image](https://user-images.githubusercontent.com/26408605/78003913-f659da00-736b-11ea-97af-dea7255a4221.png)

Does this piece of code achieve compile-time array initialization and filling please?

> My guess from taking a quick look is that this would need to have WireType bindings set up for `std::array<int, n>`. [There's a number of types that have built in binding support](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#built-in-type-conversions), but note that in those examples STL types need to be declared explicitly, presumably because otherwise it's not clear which template instantiations are needed in the wasm side of things.
> 
> [There's a test that shows how to write a custom binding wrapper](https://github.com/emscripten-core/emscripten/blob/02532df58a7991c00d0bb31e0e95a16b9e779a24/tests/embind/test_custom_marshal.cpp), I imagine that kind of approach should work with `std::array<int, 5>`?

**Comment by dirkarnez** [comment]
Just found that the library [nbind](https://github.com/charto/nbind) having [similar wrapper code](https://github.com/charto/nbind/blob/master/include/nbind/em/BindingStd.h). Shall i make reference to it please? Thanks!

**Comment by dacodas** [comment]
Would love to hear more about this
