### ISSUE TITLE
wasm size increase after 1.39.11

### ISSUE THREAD

**Issue by jpharvey** [emscripten-core/emscripten#10803]
I was trying tot version from today (after merge of Fix lax option parsing for `--` options that take an argument) to test the larger address space. With that version and using the same compiler flags as we use with 1.39.11 the size of our wasm file has grown from 13Mb to 16Mb.

I tested with MaximumMemory=1Gb & =3Gb and see no size change in the wasm file size.
The flags we are compiling and linking with are
--bind -s ALLOW_MEMORY_GROWTH=1 -s NO_EXIT_RUNTIME=1 -s FULL_ES2=1 --memory-init-file 0 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s EMBIND_STD_STRING_IS_UTF8=0 -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s DISABLE_EXCEPTION_CATCHING=0 -s MAXIMUM_MEMORY=1GB  -O3 -s ASSERTIONS=0 -s DEMANGLE_SUPPORT=0 -DNDEBUG=1  -flto   --std=c++14

Is there anything i can do to help identify what changed? The only other thing that seems like a candidate for me is the exception handling changes?

**Comment by sbc100** [comment]
There have been some lto related changes recently. For example https://github.com/emscripten-core/emscripten/pull/10606.  This change means that we no longer default to passing `-lto-O0` to the linker.   This means the default linker level of `lto-O2` is used which could increase code size due to inlining.

Does the difference go away when you remove `-flto` from you compile and link commands?   
If you don't want the code side increase of LTO the best thing to do is probably just to not use LTO.

It might not be LTO but thats my current best guess :)

As a general housekeeping thing you might want to removing some superfluous options.  
- `ERROR_ON_UNDEFINED_SYMBOLS=1` (thats been the default for while now)
- `NO_EXIT_RUNTIME=1` (thats always been the default IIUC)
- `--memory-init-file 0`(wasm doesn't use memory init file).
-  `DEMANGLE_SUPPORT=0` (thats the default).

**Comment by jpharvey** [comment]
Thanks for the feedback. Yes just tried without -flto and it shrinks & then with 1.39.11 with -flto --llvm-lto 2 and the size grows to 16Mb so yes that looks like the change. 
I will investigate the performance difference to see if the size is worth while.

For those variable yes they can be tidied up but we started this a long time ago so things get left behind.

I'll close the issue.
