### ISSUE TITLE
SPIR-V support

### ISSUE THREAD

**Issue by szilardszaloki** [emscripten-core/emscripten#10969]
Hi there,

I'd like to link SPIR-V shader objects into a shader program. While `glShaderBinary()` is available, `glSpecializeShader()` is not. Are you planning to add support for SPIR-V shaders?

Thanks,
Szilard

**Comment by kripken** [comment]
cc @kainino0x

**Comment by kainino0x** [comment]
There is no plan to support SPIR-V in Emscripten. For one thing, the SPIR-V extension for OpenGL is desktop only, and Emscripten focuses on supporting OpenGL ES (because WebGL is OpenGL ES-based, and desktop OpenGL can only be emulated).

glShaderBinary is there for OpenGL ES compatibility (it is core in ES 2.0+) and doesn't support GL_SHADER_BINARY_FORMAT_SPIR_V (core in OpenGL desktop 4.6). Though it doesn't exist in WebGL, I believe it's emulated for compatibility of programs written against OpenGL ES.

Look into [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross) if you need to translate SPIR-V into GLSL.

**Comment by jarble** [comment]
@kainino0x It still might be possible to develop a GLSL backend for Emscripten. You can compile LLVM IR to SPIR-V using the [SPIRV-LLVM-Translator](https://github.com/KhronosGroup/SPIRV-LLVM-Translator), and then compile it to GLSL ES using SPIRV-Cross.

**Comment by kainino0x** [comment]
This question is about allowing apps to provide SPIR-V shader binaries to WebGL (which could possibly be done in the app by using SPIRV-Cross inside the app to translate SPIR-V to GLSL ES). I think you're talking about compiling C++ code through SPIR-V to GLSL. That would be a very niche thing, and not strictly related to Emscripten or WASM or the Web.
