### ISSUE TITLE
CentOS 7 (GLIBC 2.17) compatibility

### ISSUE THREAD

**Issue by DoDoENT** [emscripten-core/emscripten#10992]
I've upgraded from emscripten 1.39.11 to 1.39.13 (I've skipped 1.39.12) and now wasm-opt has stopped working. It fails with error:

```
bin/wasm-opt: /lib64/libc.so.6: version `GLIBC_2.18' not found
```

Against which glibc are default builds made? Is there a reason for not supporting GLIBC 2.17 anymore?

**Comment by kripken** [comment]
cc @dschuff - did we change something on the waterfall that could explain this?

**Comment by sbc100** [comment]
We did move to building against a debian stretch sysroot: https://www.debian.org/releases/stretch/

We need to use a sysroot (and not a docker image to chroot) in order to be compatible with GOMA.  In order to build against an older distro we would need to build a sysroot based on something olderm which is sadly not trivial.

**Comment by sbc100** [comment]
For a workaround you can build from source using emsdk: https://github.com/emscripten-core/emsdk#i-want-to-build-from-sourcei-want-to-download-a-precompiled-build

**Comment by DoDoENT** [comment]
Thank you, guys, for the tips. I'll explore the possibility of using the newer distribution on my CI system and, if not possible, I'll build the EMSDK from the source.

**Comment by sbc100** [comment]
If you have docker you can also use the emsdk docker container to run you CI on: https://hub.docker.com/r/trzeci/emscripten/
