### ISSUE TITLE
`-msimd128` works with `i32` but not `f64`

### ISSUE THREAD

**Issue by GirkovArpa** [emscripten-core/emscripten#11004]
This gets compiled with `v128` instructions:

```cpp
typedef long int i32;
extern "C" {
  i32 dot(i32 *vec1, i32 *vec2, i32 len) {
    i32 prod = 0;
    for (i32 i = 0; i < len; i++) {
      prod += (vec1[i] * vec2[i]);
    }
    return prod;
  }
}
```

But this doesn't:

```cpp
typedef long int i32;
typedef double f64;
extern "C" {
  f64 dot(f64 *vec1, f64 *vec2, i32 len) {
    f64 prod = 0;
    for (i32 i = 0; i < len; i++) {
      prod += (vec1[i] * vec2[i]);
    }
    return prod;
  }
}
```

These are the flags I'm using:

```
emcc -O3 -Wl,--no-entry -s INITIAL_MEMORY=64kb -s MAXIMUM_MEMORY=6400kb -s ALLOW_MEMORY_GROWTH=1 -s TOTAL_STACK=0kb -s STANDALONE_WASM -s EXPORTED_FUNCTIONS="['_dot']" "index.cpp" -o "index.wasm" -msimd128
```

**Comment by tlively** [comment]
I have found that the autovectorizer is much more conservative with floating point types than with integer types because it is hard to preserve all their edge case semantics with infinities and nans and negative zeroes and so on. If this is a problem for you, you should probably be using the [wasm_simd128.h](https://github.com/llvm/llvm-project/blob/master/clang/lib/Headers/wasm_simd128.h) intrinsics to get finer-grained control over where SIMD is used.

**Comment by GirkovArpa** [comment]
Any examples of how to use those for a ... noob C++ programmer?

**Comment by tlively** [comment]
Sure, in this example you would want something like this:

```
#include <wasm_simd128.h>
extern "C" {
    double dot(doublet* vec1, double* vec2, int len) {
        v128_t sums = wasm_f64x2_make(0, 0);
        for (int i = 0; i < len; i += 2) {
            v128_t a = wasm_v128_load(vec1 + i);
            v128_t b = wasm_v128_load(vec2 + i);
            sums = wasm_f64x2_add(sums, wasm_f64x2_mul(a, b));
        }
        return wasm_f64x2_extract_lane(sums, 0) + wasm_f64x2_extract_lane(sums, 1);
    }
}
````

This steps through the vectors two elements at a time using `f64x2` vector operations. It will only work correctly if `len` is a multiple of 2. Notice that the loop has half as many iterations because it processing twice as much data on each iteration.

The general strategy should be:

 1. Figure out generally how your code should operate on vectors
 2. Figure out what [SIMD instructions](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md) you can use
 3. Figure out what intrinsinsics in the header correspond to those instructions.

**Comment by GirkovArpa** [comment]
I was actually hoping for an example exactly like this 😃 Thank you sir!
