### ISSUE TITLE
WASM_4GB=1 setting?

### ISSUE THREAD

**Issue by zeux** [emscripten-core/emscripten#11043]
I'm not 100% sure what the correct way to use a 4GB heap is right now:

- Is it -s MAXIMUM_MEMORY=4294967296? Worried that this is 2^32 so it doesn't fit into a 32-bit integer and is thus invalid.
- Is it -s MAXIMUM_MEMORY=4294967295? It's definitely not, since the value needs to be 64 KB aligned
- Is it -s MAXIMUM_MEMORY=4294901760? (2^32-64KB) It probably is but I'm not sure.

Would it make sense to add something like -s WASM_4GB=1 to simplify the configuration here?

**Comment by sbc100** [comment]
Any reason not to just it to `-1` which means no upper limit?

**Comment by zeux** [comment]
Ah, this works! For some reason I thought I saw a change that compared MAXIMUM_MEMORY vs a 2GB limit without comparing it to 0, but I must have been mistaken. Thanks!

**Comment by kripken** [comment]
`-s MAXIMUM_MEMORY=4GB` would also work here, btw. There would actually be a difference in the wasm between `-1` and `4GB`: with `-1` the wasm just doesn't have a max, while with `4GB` the max is `64K pages = 4GB`. But of course since 4GB is all we can do in wasm32 anyhow, it's effectively the same...

**Comment by kripken** [comment]
Btw @zeux , do you have a nice demo using 2-4GB maybe? I'm working on a blogpost about 4GB, would be nice to include links to cool examples!
