### ISSUE TITLE
wasm-ld doesn't support required flags - rpath

### ISSUE THREAD

**Issue by danj** [emscripten-core/emscripten#11076]
Hi,

Trying to build ijg (lib-jpeg) with latest version 3.9.14 and getting an error about wasm-ld not supporting -rpath

Building with version 3.9.11  works.
Adding -rpath to the UNSUPPORTED_LLD_FLAGS seems to work

**Comment by sbc100** [comment]
Yes, this is not a supported linker flag in the wasm world, and we decided to switch from just ignoring such flags to letting them surface as errors.

We can add that flag the list of ignored flags, but maybe we can figure out a way to avoid adding instead?

Can you include your build command so we can see how its getting added?  Is this an autoconf-based build?  If so can see if `--disable-shared` helps?

**Comment by Akaricchi** [comment]
> Yes, this is not a supported linker flag in the wasm world, and we decided to switch from just ignoring such flags to letting them surface as errors.

Meson currently still adds rpath flags with emscripten, and there's nothing end users can do about it.

**Comment by sbc100** [comment]
OK we can certainly add it to the list of linker flags to warn about and drop on the floor.

However, it is somewhat worrying no, that the build system links we support a behaviour that we don't.  Is that flag really hardcoded into the guts of the build system?  What about, for example, building on windows where that flag is not supported?   Isn't the toolchain configurable at some low level?

**Comment by Akaricchi** [comment]
>However, it is somewhat worrying no, that the build system links we support a behaviour that we don't. Is that flag really hardcoded into the guts of the build system? What about, for example, building on windows where that flag is not supported? Isn't the toolchain configurable at some low level?

Meson has a lot of special cases based on compiler/linker/platform combinations. It abstracts away most differences between toolchains, allowing the build definitions to be clean, portable, and correct, but sometimes it gets things wrong in not very well tested cases.

I don't know what it does here on windows specifically. I assume it still passes the rpath flags in this case, because things like that depend on the target platform, not the build platform. When building *for* windows it does not pass the rpath flags, though.

I believe the current behavior is actually a regression introduced in https://github.com/mesonbuild/meson/commit/654f427759d5aa3be55d8929b18c17a2b8fcac69, it used not to pass those flags with emscripten in some older versions. It inherits this behavior from the "GNU-like" compiler/linker case. I'll see if I can contribute a patch.

**Comment by sbc100** [comment]
I see, that makes sense.  

I landed the change to only warn when  we see this flag which should unbreak anyone who was passing it before.

**Comment by danj** [comment]
it is an autoconf based build.
--disabled-shared doesn't help doesn't seem to help.

anyway, I think that ignoring it is safe in the WASM context
