### ISSUE TITLE
pthreads broken when using EXPORT_NAME=xxx parameter

### ISSUE THREAD

**Issue by Lyve1981** [emscripten-core/emscripten#11112]
Pthreads are broken when using any other module name than the default one.

In this test project, the errors are *only* some Javascript errors that you instantly notice in the browser. What happened in my larger project though is that the threads heap was not identical to the main heap, leading to segfaults because a thread tried to call a virtual function of a class but the vtable was invalid.

Small test project, C source:

    #include <pthread.h>
    #include <stdio.h>
    
    void *threadProc(void *arg)
    {
        int i = *((int*)arg);
    
        printf("The answer is %d", i);
    
        return 0;
    }
    
    int main(int argc, char *argv[])
    {
        int* testValue = new int;
        *testValue = 42;
    
        pthread_t bg_thread;
    
        // Create the background thread
        if (pthread_create(&bg_thread, NULL, ::threadProc, testValue))
        {
            puts("Thread create failed");
            return 1;
        }
    
        if (pthread_join(bg_thread, NULL))
        {
            puts("Thread join failed");
            return 2;
        }
    
        puts("All done, exiting");
    
        return 0;
    }

Everything works as expected with this command line:

`call emcc -g -s -Werror -s STACK_OVERFLOW_CHECK=2 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=3 -s ASSERTIONS=2 -s WASM=1 -s DEMANGLE_SUPPORT=1 -o test.js code.cpp`

However, it terribly fails when using this one instead

`call emcc -g -s -Werror -s STACK_OVERFLOW_CHECK=2 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=3 -s ASSERTIONS=2 -s WASM=1 -s DEMANGLE_SUPPORT=1 -o test.js code.cpp -s EXPORT_NAME="'MyCustomModule'" `

Notice the added  **-s EXPORT_NAME="'MyCustomModule'"**

Version info:

    emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.15
    clang version 11.0.0 (Cswircachegitchromium.googlesource.com-external-github.com-llvm-llvm--project 57d361bd2f3668eefa7028ad4a2d616317ed437c)

The issue can be reproduced in both upstream and fastcomp

Simple html code to test:
	
    <!DOCTYPE html>
    <html>
      <title>Threads test</title>
      <body>
        <script src="test.js"></script>
      </body>
    </html>

**Comment by kripken** [comment]
It's possible we have `Module` somewhere we should have `{{{ EXPORT_NAME }}}`.

Finding that place in the output JS might be the simplest way to debug this - that is, find where a replacement of `Module` by your proper exported name fixes things. Then find where that was generated from.

**Comment by RReverser** [comment]
@Lyve1981 Does this still fail for you? I've been successfully using pthreads with `EXPORT_NAME`, perhaps the issue has been fixed since.

**Comment by goncalomb** [comment]
I'm also seeing an issue with EXPORT_NAME + pthreads. I think it stems form the fact that in the [worker.js](https://github.com/emscripten-core/emscripten/blob/main/src/worker.js) the `Module` is always initialized as:

    var Module = {};

When it receives the load message it sets the ENVIRONMENT_IS_PTHREAD and loads the main .js:

    Module['ENVIRONMENT_IS_PTHREAD'] = true;
    importScripts(...);

Then the main .js is initialized with:

    var Module = typeof MyCustomModule != 'undefined' ? MyCustomModule : {};

But because `MyCustomModule` is not set at that point (the worker.js used `Module`). It just creates another `Module` and the worker thinks it it is the main thread and breaks everything.

I think the fix is just to make the worker.js initialize with the proper name `MyCustomModule`. Something to the effect of:

    var Module = {};
    var MyCustomModule = Module;

I'm new to emscripten and I don't have my environment setup to build it, so if someone wants to fix it, please do. Otherwise I'll try to fix it another time.
