### ISSUE TITLE
simplifying builds...

### ISSUE THREAD

**Issue by jeffatrad** [emscripten-core/emscripten#11115]
emcc.bat runs python.exe, which runs clang.

Can we just call clang and the linkers directly?  Is there a commandline switch to dump the low-level command that pythons makes so we can convert over?

**Comment by sbc100** [comment]
You can pass `-v` to see (most) of the major sub-commands that emscripten is running under the hood.

For compilation, yes, you can probably produce a working clang command.   However during linking emscripten performs many many steps.  Reproducing all of those steps would essentially be re-implementing the python script.   

Of course we are always looking forward for ways to simplify the compiler wrapper.  A lot of the complexity that exists today is because we currently support two different compiler backends: fastcomp + the llvm backend.   Once we remove fastcomp a lot of the compiler driver complexity will hopefully be eliminated.

**Comment by jeffatrad** [comment]
I think it's always better to be just show all the commands that are running.  I understand you are transitioning away from the fastcomp stuff, but simple commands that hide what's happening behind simple command lines hurt too.  Like with my question about whether the objs are the same.  That would be clear with an explicit set of build steps.  Big commands that try to simplify building almost always make things more difficult for shops like ours that ship on 33 platforms.  Just fyi.  Thanks for the -v tip!

**Comment by sbc100** [comment]
I couldn't agree more regarding keeping things simple.

The idea is that emcc should behave like a normal toolchain does from the users perspective.  Shops like yours should treat it like a drop in replacement for a gcc, clang or msvc.   There should be no need to decompose it anymore than you currently decompose your use of gcc into calls to cpp, cc1, as and ld. 

It just happens that in our case the driver is a python rather, and that on windows in order to run a python program a .bat file is the most convenient way.

**Comment by jeffatrad** [comment]
But we do call cpp, cc1, as and ld.  That's what we would like - we're using clang for 18 of our platforms.  The driver stuff is fine, that's just something that makes this more, not less complicated for us.  But the -v is fine.

**Comment by juj** [comment]
There is simplicity, and then there is illusion of simplicity.

Calling clang directly might make you think you'll get the former, but in
practice you'll end up with the latter.

Your train of thought is understandable, "let me just use clang directly
like I use on all my other platforms, look how simple it is there". The
other platforms are not the web, and they do not have to deal with
targeting JavaScript. If you only needed to build a .wasm file, and did not
need to
 a) link together any JavaScript code,
 b) use any web APIs (DOM, WebGL, Web Audio, ...),
 c) use multithreading,
 d) use IndexedDB or persistent filesystem,
 e) use POSIX,
 f) use dynamic linking,
 g) need infinite synchronous code execution,
 h) want to co-target WASM and WASI,
 i) want to minify your resulting code,

... to name a few, then directly using clang to build a .wasm is a viable
approach. Chances are that you do need at least some of the above. Rolling
through your own solution with direct clang calls will quickly makes you
realise that you are reinventing the wheel to re-solve one or more of the
above points.

If you google e.g. for "wasm without emscripten" you can find dev stories
of such work, which invariably end up rewriting portions of the toolchain
on their own (for some of a)-i) use cases, and ignore the rest. Those dev
stories are good examples of how to miss the proverbial forest. Further,
given that there is (unarguably) joy in architecting a system on one's own,
the time spent in re-writing a)-i) gets kinda clouded in the cost-benefit
analysis of whether one should avoid emcc or not.

If upstream LLVM and its IR representation was architected to allow
representing JavaScript language and Node.js/V8/SpiderMonkey/web browser
runtime APIs built-in, and LLVM/Clang toolchain shipped with a JS execution
environment like Node.js, then it would probably be possible to redevelop
all of the Emscripten tooling into clang.exe. But you can imagine such a
"let's make JavaScript/EcmaScript a first class language in LLVM IR" is
probably not a sensible goal due to the sheer complexity, and after all you
can replace clang.exe with emcc.bat and get to the same result already.

You are not the first to discover such a "just fyi" thought, it has been
discussed time and time again in the past near decade of Emscripten's
lifetime. It is not a bad discovery to make, but it needs a solid
understanding of the whole problem domain to get right.


la 9. toukok. 2020 klo 19.06 jeffatrad (notifications@github.com) kirjoitti:

**Comment by jeffatrad** [comment]
I'm not trying to get rid of Emscripten at all.  I'm saying conflating Emscripten build switches with clang and with linker and with everything else switches in a big compiler driver, makes things worse, not better (the fact that it's in python makes it even worse on Windows, but that's another thing).

No big deal, the -v did the trick and I'm running directly.

**Comment by sbc100** [comment]
Ok to close this now?

**Comment by jeffatrad** [comment]
Of course, thank you.

**Comment by kripken** [comment]
Btw, for compilation flags, there is `emcc --cflags` which prints out what you need to pass to clang if you want to invoke it directly. A build system can run that once, then use clang to compile source files with those.

For linker flags though, as discussed above there's a lot more going on. That's where most of the complexity is, and most of it is unavoidable.

**Comment by jeffatrad** [comment]
Cool, thanks!

> there's a lot more going on

I dunno - it calls 4 things - that just ain't a big deal.  I have 8 post build steps on ios that are a lot more tweaky.  I get it for basic use, but it would be nice to just document the stages when you drop fast-comp and settle things down for those of us that don't want to deal with python stuff, commandline ambiguities, etc.

**Comment by sbc100** [comment]
> Cool, thanks!
> 
> > there's a lot more going on
> 
> I dunno - it calls 4 things - that just ain't a big deal. I have 8 post build steps on ios that are a lot more tweaky. I get it for basic use, but it would be nice to just document the stages when you drop fast-comp and settle things down for those of us that don't want to deal with python stuff, commandline ambiguities, etc.

I think you will find that there is a lot more going on than you think.. its not just calling those 4 external programs, there is a lot work actually performed in the python driver too.   You will end up trying to understand the full emscripten linking process, which is very complicated.   If you are feel like going on an adventure then by all means do, but be warned.. there be dragons in there.

**Comment by kripken** [comment]
> I dunno - it calls 4 things - that just ain't a big deal.

To add a concrete example: i you enable `SAFE_HEAP` then it triggers changes in both the JS compiler, in `wasm-opt`, and in emscripten's python JS codegen, and all those need to be synchronized.

Right now it's just `-s SAFE_HEAP` for a user of `emcc.py` to get all that. But to do it manually would be tedious and error-prone (especially for a user that just wants to add `SAFE_HEAP` support because they were told it might help diagnose a bug they are working on atm).

And `SAFE_HEAP` is actually one of the simpler things, since it mostly just enables a pass and some extra functions to be emitted. Things like minifying import/export names, metadce, etc., have a lot more interactions between components, because those things have a lot of necessary complexity (parse JS, parse wasm, calculate, modify JS, modify wasm, etc.).

**Comment by jeffatrad** [comment]
>  it triggers changes in both the JS compiler

?  I used SAFE_HEAP yesterday, and I used on link line alone and it flagged everything.

Look, it's not something worth arguing about - I'm trying to give you a data point, from a professional development house of 35 years that is shipping on 32 platforms.  We just don't want this stuff, we'd rather have stages just be documented.  That's all. I understand the easy of use argument, but I'm telling you that some of us don't want that, because we'd rather understand what's actually happening.  This doesn't seem like something to be precious about.

Ignore if you want.

**Comment by kripken** [comment]
>  I used SAFE_HEAP yesterday, and I used on link line alone and it flagged everything.

Oh, then I may have misunderstood you overall, sorry. Yes, my point was that doing `emcc -s SAFE_HEAP` at link time will do everything for you. So maybe we agree but misunderstood each other?

**Comment by sbc100** [comment]
> > it triggers changes in both the JS compiler
> 
> ? I used SAFE_HEAP yesterday, and I used on link line alone and it flagged everything.
> 
> Look, it's not something worth arguing about - I'm trying to give you a data point, from a professional development house of 35 years that is shipping on 32 platforms. We just don't want this stuff, we'd rather have stages just be documented. That's all. I understand the easy of use argument, but I'm telling you that some of us don't want that, because we'd rather understand what's actually happening. This doesn't seem like something to be precious about.
> 
> Ignore if you want.

We don't want to ignore you.  I think we all agreement in general.  I have a similar background skipping SDK and toolchains (my numbers aren't quite as big as yours!  probably 22 years and ~18 platforms :) so I really do think we should be able to understand each other there.

The issue is that the emcc *link* process (not the compile process) is very complex and intertwined.  We would *love* to have it separated out so that our users could run it as sequence of separate steps.  I have personally dedicated a lot of the past 3 years to trying to move the codebase in that direction.  And we are making process.  But we are not there yet. 
  
Your last comment makes it sound like you *are* indeed running the `emcc` driver for linking (since `-s SAFE_HEAP` is a driver command line flag) .. so I guess maybe you are not trying to decompose the link process yet / after all?     I/We have lot of on going projects to try to reduce the amount of magic happening at link time and make the process more composable and transparent and would welcome any patches that make it easier.

Once again, the only point that we were trying to make clear here is that turning the `emcc` link command into something like a small shell script is not something that is possible today..  we all wish it was.

**Comment by jeffatrad** [comment]
Yeah, today was going to be link into commands, but the when you said the driver was doing work, I bagged it.  I guess the small step for us would be breaking out the "work" being done in the driver to another python script that you shell to, and that is documented in the -v command list stream.

I have some other minor suggestions for the installer, which was kind of painful for a first time install (once you have a version installed, it updates nicely, but until then, it's hard).  I'll make a new issue for that.

**Comment by sbc100** [comment]
One big step in this direction is the ability to run emscripten as post-link step.  This way the actual linking of the native code (done by wasm-ld these days) could be be performed ahead of time and then used as the input to the emcc post-link phase.   This is something we are hoping to achieve this quarter.

The would be pretty big improvement I believe for a lot users who want to decompose the toolchain.   It would still require a fair amount of logic to generate the correct link flags to pass to wasm-ld but at least hat is feasible today I believe.  

It would open up some pretty cool opportunities like being able to take fully linked wasm binary produced by the wasi-sdk and feed it into emscripten to run it on the web.

**Comment by jeffatrad** [comment]
Yup, totally.  Baby steps are great.
