### ISSUE TITLE
-s WASM=0 vs -s WASM=1 mode...

### ISSUE THREAD

**Issue by jeffatrad** [emscripten-core/emscripten#11113]
We build our codec library for both AsmJS (WASM=0) and WASM (WASM=1).

However, when we link an emrun HTML test, in AsmJS mode, we get lots of corruption and audio artifacts.  You can still see most of the video and can make out the audio somewhat, so it is *almost* working (usually when complicated codecs fail, it's much worse).

How do I even attempt to find such a problem?  The optimization level seems to not matter (-01 to -O3 vs even debug mode), the AsmJS module always fails (and seems like the same way).

Suggestions??

**Comment by jeffatrad** [comment]
BTW, we are on emscripten latest (as of today), and all browsers (chrome, firefox and edge) all fail the same way.

**Comment by sbc100** [comment]
Sounds like you might have found a bug in wasm2js.  (assuming you using the llvm backend to build both the wasm and the amsjs build).

@kripken might have some advice on how to debug.   If you can narrow it down to find a location whee the two build diverge that would be very useful/actionable.

**Comment by brion** [comment]
If this is the first time building to JS and not a recent regression, check especially for memory access alignment issues. Unaligned memory access in JS fails silently by rounding the address down to an aligned one, which can create corruption. Use of double-precision floats to copy arbitrary memory can also cause corruption due to NaN canonicalization in some browsers.

**Comment by jeffatrad** [comment]
Yeah, it's a codec - it's all unaligned accesses.  WASM supports unaligned and wasm2js doesn't?

**Comment by brion** [comment]
Well, my theora, vp8, vp9, av1, vorbis and opus codecs work fine in wasm2js builds, so it doesn't have to be broken. :) But if you're using a uint8_t* as uint32_t* and the compiler doesn't recognize the unalignedness and break it down into aligned accesses in wasm2js, you're gonna have a bad time. This is because of the API for JavaScript TypedArrays, which only provides a way to access them on alignment boundaries. WebAssembly is not restricted in this way, yes.

**Comment by jeffatrad** [comment]
The unaligned accesses are marked up with __attribute__((aligned(1))) and __unaligned on msvc.  Are those supposed to carry over?  You can obviously make a codec work with unaligned accesses, it's just massively slower, of course.  We can just support wasm, I'm fine with that too.

**Comment by sbc100** [comment]
Unless you have have a compelling use case for JS (such as needing to support some embedded device such as a TV that doesn't have any way to upgrade its browser/webview) then I would avoid creating a JS build and only build wasm.  The wasmjs is path is designed mainly for legacy use cases.   All modern JS engines support wasm.

Having said that we do need to continue to maintain it so if you fine bugs there we should fix them.

But I wouldn't waste your time in wasm2js until you have a compelling use case.

**Comment by juj** [comment]
You can try building with `-s SAFE_HEAP=1` linker flag to add in runtime alignment fault checks.

**Comment by jeffatrad** [comment]
> -s SAFE_HEAP=1

Excellent.  It wasn't hard to find in my code, since we markup with a unaligned attribute, but that's to find bugs for sure!  Thanks!

**Comment by jeffatrad** [comment]
Yeah, it was for a customer on ios 11 where the wasm support was a bit janky.  I think we'll just bail - I made a byte copy mo-comp and it works, it just makes things that much slower.  Not really worth it.

Also,
