### ISSUE TITLE
Why are 0 error codes in Fetch changed to 404?

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#11132]
@juj , this code confuses me:

https://github.com/emscripten-core/emscripten/blob/12b23e588da87495c113fe9ff480735ac30d5051/src/Fetch.js#L405

Could we instead leave it as `0` there? Or is there a reason to change the default browser behavior here?

**Comment by juj** [comment]
This is because at least Firefox did report error 0 on file not found when downloading `file://` urls. It was a common gotcha to miss this in user code and only look out for 404s, leading to hairscratchers when doing local testing.

I am open to removing that line altogether, since this might be relevant only for back in the day when people still were able to do local testing via file:// urls without a web server.

**Comment by johncarlanderson** [comment]
If not removed, would it be possible to only change the status for URLs with file: scheme and to leave http(s): statuses unchanged?
