### ISSUE TITLE
no exception error should name the library

### ISSUE THREAD

**Issue by Shachlan** [emscripten-core/emscripten#11164]
When compiling and linking with -fno-exceptions, this error might be thrown:

`error: DISABLE_EXCEPTION_THROWING was set (likely due to -fno-exceptions), which means no C++ exception throwing support code is linked in, but such support is required by symbol __cxa_allocate_exception. [...]`

What the error doesn't say is which library contains the `__cxa_allocate_exception` (or other exception) symbol. Is there a way to add to the log what's the problematic library?

**Comment by sbc100** [comment]
Can you try adding `-Wl,--trace-symbol=__cxa_allocate_exception` to your link command?

If that works we can update the error message to recommend this.

**Comment by Shachlan** [comment]
Yes, that works. Thanks :)

**Comment by tml1024** [comment]
Is there a way to figure out the opposite, what object file or library it is that as been compiled with DISABLE_EXCEPTION_THROWING set?

**Comment by sbc100** [comment]
I think its hard to detect a file compiled with `DISABLE_EXCEPTION_THROWING` because it would be trying to detect that absence of the feature.  I'm not sure how you could tell the difference between an object file that simply doesn't thrown any exceptions, and one where throwing is disabled.

BTW, what is the issue you are running into?  Are you seen build failures, or runtime errors?

**Comment by tml1024** [comment]
The issue is (was) that I got the error mentioned in the initial comment., which isn't helpful in figuring out the root cause. But luckily I guessed correctly which libraries I needed to re-compile, being more careful to make sure -fwasm-exception was used, so the problem went away.
