### ISSUE TITLE
GLFW key listener blocking backspace and tab

### ISSUE THREAD

**Issue by clapragr** [emscripten-core/emscripten#11221]
https://github.com/kripken/emscripten/blob/master/src/library_glfw.js#L410

This blocks backspace and tab on the entire page, making text inputs on the page completely unusable.

#6143
#6148

**Comment by diegurrio** [comment]
This is also causing issues for us. Is there a workaround? Even though we target our canvas it keeps intercepting input even when the canvas is not in focus.

**Comment by kripken** [comment]
I think we need someone to volunteer think about the big picture here and decide on a good overall policy - we have a bunch of different approaches in the different backends (glfw, sdl, etc.), and I personally don't actually know what the best approach would be. A starting point might be to investigate the current status among the backends and summarize that.

**Comment by diegurrio** [comment]
I understand why capturing those keys is needed, but I still think that it should be left to the user wether to bubble up those events of filter them out. Maybe the solution is for emscripten to provide a default keydown call back that captures and prevents certain input from bubbling up. The moment someone decides to provide their own call back, or passes `nullptr` to deregister it's up to them to decide what needs to be bubbled up. Something along the lines of:

```
    int keyDownCallback(int eventType, const EmscriptenKeyboardEvent *event, void* userData) {
        return event->key == SDLK_BACKSPACE || event->key == SDLK_BACKSPACE;
    }
```

**Comment by diegurrio** [comment]
@kripken Hi Alon,
What do you think about the approach I describe above? If it sounds reasonable I can go through with a pull request following your guidelines.

**Comment by kripken** [comment]
@diegurrio I'm not the best person to talk with about the details here, hopefully @juj can provide feedback. But reading that, there isn't enough information for me to understand the proposal, sorry. May be my fault, but maybe sketching out the concrete API details would help? Or, if it's easier, opening a PR and discussing on the code there is an option too.

**Comment by kripken** [comment]
At a high level, though, my main question would be whether the proposal breaks existing users, and after that, how easy is it to use and the impact on code size.

**Comment by juj** [comment]
Each of the native "emulated"/"ported" APIs, GLFW, GLUT and SDL, share this exact same problem: since there are no two target actors/recipients for input events in the native world like there is in the browser environment, these APIs do not have a concept about "did the app handle/consume the input event" vs "should the system handle/consume the input event".

This problem was solved with the introduction of the browser-friendly HTML5 input event API: in html5.h input events are passed directly to the user and the user can [indicate with the return value from that function](https://emscripten.org/docs/api_reference/html5.h.html#id3) whether to consume the event or not. Targeting that API is the primary recommendation, as that gives the direct/bare web-aware way to register to input events that matches the JS DOM API feature set.

If someone would like to extend GLFW (, GLUT and/or SDL) APIs with some Emscripten-specific extensions, e.g. a `emscripten_set_glfw_keyfunc()` that would expand the API behavior to somehow enable controlling when/which input events to suppress, that sounds fine. Extra points for consulting upstream core authors of GLFW (and/or SDL) of how such an API might want to look like upstream, although that is probably not necessary.

Not breaking existing codebases is critical, so changing up existing function entry points is undesirable. I am not that worried about code size creep on GLFW, GLUT and/or SDL, since those are so heavily in the emulation land already.
