### ISSUE TITLE
Where did non-Closure minification go?

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#11232]
Hmm, just realized that if one does a build without Closure, it is no longer minified:

```bash
emcc tests/hello_world.c -o a.html -O3
```
will generate a JS output file that has only whitespace minified, but function&variable names are not.

I wonder what point did we regress? Do we no longer run JS through uglify by intent, or by accident?

**Comment by kripken** [comment]
Did we ever run uglify's full optimizations? Maybe in the far past that I've forgotten, but for years we've just used it as an IR I believe. We don't even use it as that with most passes today since we use acorn.

Uglify's optimizations are not as good as closure advanced, so I believe our focus has been on enabling closure and not supporting something in the middle like uglify's opts (maybe even minifying whitespace is not needed, but it's trivial).
