### ISSUE TITLE
how to complete emsdk activate latest

### ISSUE THREAD

**Issue by leemke** [emscripten-core/emscripten#11236]
When running "emsdk activate latest", at the end of the activation it displays:

Set the following tools as active:
   node-12.9.1-64bit
   releases-upstream-ae5001fac3849895a873e422a2a80afc90f3b798-64bit

Did it do this or do I need to do something else?  It looks like a command to be done.
How do I do this?

**Comment by sbc100** [comment]
Yes, those tools are now installed and active in the sense that the config file points to them.

In order to actual use that active tools one would normally also then run `source ./emsdk_env.sh`.  This will add the relevant tools to your path and set some environment variables.  See: https://emscripten.org/docs/tools_reference/emsdk.html.

**Comment by leemke** [comment]
Thanks for the documentation "link"  It is good to know that this exists, and the other commands that it provides. I did not know it existed from the install documentation that I read. Thanks again.
