### ISSUE TITLE
"emsdk update" detects git install - why not just branch to emsdk update-tags

### ISSUE THREAD

**Issue by leemke** [emscripten-core/emscripten#11235]
I did not find a different way to install emsdk. Searching for emsdk install I found
"https://github.com/emscripten-core/emsdk"  This lead me to install via gitHub.

Now after installing "lastest-upstrem", I did "emsdk update".
Of course it detected that I had used git to install emsdk. It gave me two options
"get pull" or "emsdk update-tags". I don't know if there is any difference between
the two options, but why not automatically branch to "update-tags", rather than tell
me to choose. Now I have to remember to use update-tags, for the update.

**Comment by kripken** [comment]
I am not sure why we have separate `update` and `update-tags` commands. Perhaps it's less error-prone as they do quite different things, even though you need one of the two commands for each type of checkout? cc @juj

**Comment by sbc100** [comment]
I'm not sure we want to be running `git fetch && git merge` under the hood.   We kind of assume that if you are git user you will handle your own updates.

IIUC orginally "get pull" and "emsdk update-tags" did quite different things.  The first one pulls the latest tags from the emsdk repo itself so it won't do anything if you have the latest already.  The later pulls in tags from the sdk builders and will update your local files, which could then submitted back to git to publish those tags.

These days things work a little differently since we don't manage the tags in the same way,  my understanding is that update-tags these days is mostly about updating the `tot` tags which are not stored in git at all, only locally.   Perhaps we can completely remove `update-tags` and always fetch the `tot` information on `install tot`?

Anyway its not simple sadly.

I don't think you need to run `update-tags` unless you are trying to install a `tot` build.   So just updating from git should be fine.

**Comment by juj** [comment]
> I am not sure why we have separate `update` and `update-tags` commands.

Historically we supported installing emsdk via downloading it from a binary zip file, and not via git. `emsdk update` would go to mozilla download servers to download a new emsdk update zip, and if you bootstrapped via git, it'd do a git pull.

Emsdk update-tags on the other hand just updated the new packages info (redownloading the emsdk update zip file every time wouldn't make sense back then)

Now that everyone is bootstrapping via git, I think the emsdk update abstraction is indeed a bit silly, since all it'll do is a git pull, that one could do manually as well. (and followed by emsdk update-tags, but which is just for convenience)

**Comment by sbc100** [comment]
Is everyone bootstrapping via git?    Emsdk update seems to pull from a github archive, not from mozilla:

`emsdk_zip_download_url = 'https://github.com/emscripten-core/emsdk/archive/master.zip'`

This is where emsdk update pulls from.   So its perfectly reasonable to download an archive and then update it with `emsdk update` without using git.     Do we want to continue to support that?   If not why did we ever support it?  Was the idea to servive users who didn't have or know git?  If we maybe we should continue to serve them.

**Comment by juj** [comment]
> Emsdk update seems to pull from a github archive, not from mozilla

Oh gotcha, forgot where the download was sourced. I thought with mozilla->google migration the zip path would have become unavailable.

> Do we want to continue to support that?

I don't know. Personally I don't care, as our workflows are git-based.

> Was the idea to servive users who didn't have or know git?

Yeah, this was the original goal - to keep the needed installations on e.g. a fresh Windows box to a minimum. Having to install git was not placed on the requirements list.

**Comment by sbc100** [comment]
sounds like it work keeping this features and maybe advertising it better.  

In terms of fixing this issue I think we can just remove the reference to "update-tags" and inform git users to use "get pull" since the self-update mechanism doesn't work in that scenario.
