### ISSUE TITLE
may need well-documented description about Module.arguments

### ISSUE THREAD

**Issue by y-ich** [emscripten-core/emscripten#11239]
My old emscripten project did not work after compiling by the latest emcc.
The reason was failing to pass arguments to this.program by Module["arguments"].
I had prepared it in one of preRun functions.
To fix it, I needed to prepare "arguments" property in Module in the top level of a script.
This behavior itself is fine for me now but it is developer-friendly to document it.

emcc version.
    emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.16
    clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm- 
    llvm--project 3774bcf9f84520a8c35bf765d9a528040d68a14b)
    Target: x86_64-apple-darwin19.4.0
    Thread model: posix

**Comment by sbc100** [comment]
Sorry about that, lets see if we can figure out what changed, and whether it was intentional.    If it turns out to have been accident that we needs to add more testing.

Can you share the code you used before and the code you are using now?

Did it result it an error being reported or was it silently failing?

**Comment by sbc100** [comment]
Oh and the last known version when it worked for you the old way would be great to know.

**Comment by y-ich** [comment]
I think that the version is the one before 2019/08/18, which is the starting day of my old project.

I prepared the reproduction code.
https://github.com/y-ich/emscripten_reproduction_11239
Please see Module definition in hello.html.

**Comment by kripken** [comment]
What options does this project use at link time? MODULARIZE is one possible
relevant thing that changed. If we confirm it's that I can update the docs.

Looks like the relevant code is this?

// arguments: [], // This line is necessary for the lateset(1.39.16)
emscripten.
preRun: [function() {
  if (!("arguments" in Module)) {
    Module["arguments"] = [];
  }
  Module["arguments"].push("test");
}],

Is the change you needed to make for 1.39.16 to comment out that first
line, and add the if?
It might be helpful to see a concrete diff of what you needed to change to
get things to

**Comment by y-ich** [comment]
No options.
I did `emcc hello_world.c -o hello.html` and edited hello.html

hello.html on the repository with the js compiled by the latest emcc fails to run.
Uncommenting the line `// arguments: [], // ...` solves the problem.

**Comment by kripken** [comment]
Thanks, I think I see now. When I build with no flags, and change the HTML your way, it throws `Module.arguments has been replaced with plain arguments_`. Does it not do that for you? It should if assertions are enabled, which they are without optimizations, by default. (I'll open a PR to improve that error message, which is not clear enough, as well as the docs.)

If that is the issue, then this changed in https://github.com/emscripten-core/emscripten/pull/9072 which was released in 1.38.41.

You can still provide `Module.arguments`. However, after getting the initial value there, emscripten saves them to locals. Specifically here there is a local variable `arguments_` which is why when I change the JS like you said and build with no optimization flags (which means assertions are enabled),. I'll improve that error message now.

(The reason for the change is to improve code size. Constantly looking at `Module.arguments` throughout the the code wastes space.)
