### ISSUE TITLE
Memory grows each time a request is done in NodeJS until error appear : Uncaught RangeError: WebAssembly.Memory(): could not allocate memory

### ISSUE THREAD

**Issue by Luisibear98** [emscripten-core/emscripten#11276]
Hello!

I have been playing arround with NodeJS and WebAssembly for some university researchs. 
I have been observing if memory leaks are possible by allocating memory (i.e a big matrix of uint) in WebAssembly running on NodeJS withouth freeing them.

I observed that NodeJS starts serving the requests but once a point It returns WebAssembly.Memory(): could not allocate memory
RangeError: WebAssembly.Memory(): could not allocate memory

I would like to ask If this is an expected behaviour or NodeJS should be suppose to empty all WebAssembly.Memory() objects after a request has been served?
What should be the behaviour?

Thanks before hand!

node version v10.20.1
Latest Emscripten version

I saw there was something related in the issue  #8126

**Comment by sbc100** [comment]
There is no no way that I know of to shink a WebAssembly memory.   If you want to avoid such memory leaks its seems like you could either keep a long running WebAssembly instance and use malloc or some other allocator to manage the memory and avoid leaks.   Alternatively you could create a new wasm instance and a new memory for each request.

I don't think there is any link between a node request and WebAssembly instance or memory.   Its up to you to decide how long to hold references to your instances and memories.

**Comment by Luisibear98** [comment]
Thanks for the fast response!
Each time a receive a request I do the following 

`const Module = require('./test.js');
const wasm = Module({wasmBinaryFile: 'test.wasm'});
wasm.onRuntimeInitialized = function() {
    console.log(wasm._test(40, 40));
};`

Is this the reason why Im having this memory error?

**Comment by sbc100** [comment]
It seems like node should be able to collect the wasm module and its memory after each request.   I would use whatever tools node gives to track down any references to the module might be sticking around after the request.

Are you using MODULARIZE?     I'm not sure what the effect of using `require()` on each request is, vs simply using single `require()` at the top level?

Perhaps someone else with more node knowledge might be able to give a more helpful answer?   @RReverser ?

**Comment by Luisibear98** [comment]
> It seems like node should be able to collect the wasm module and its memory after each request.
That was what I was thinking about!

Im compiling with MODULARIZE.
Calling a single require at the top level doesnt seems to be loading the module when a request takes place. 
cheers

**Comment by sbc100** [comment]
Wouldn't it make more sense to load the module just once on startup and the instantiate it for each request?

**Comment by Luisibear98** [comment]
I think so, but this: 
`const Module = require('/test.js');
const wasm = Module({wasmBinaryFile: '/test.wasm'});
router.get('/test', function(req, res, next) {
  wasm.onRuntimeInitialized = function() {
    wasm._create(1000,1000);
  };
  res.send('respond with test');
});

It does not return nothing

**Comment by RReverser** [comment]
> It does not return nothing

@Luisibear98 It's because `onRuntimeInitialized` fires off once and asynchronously, but you are subscribing to it inside the request handler. By that point it might have either already fired, or, even if not, will fire only once.

Instead you should do something like:

```js
const Module = require('/test.js');
const wasm = Module({wasmBinaryFile: '/test.wasm'});

wasm.onRuntimeInitialized = function() {
  router.get('/test', function(req, res, next) {
    wasm._test(40, 40);
    res.send('respond with test');
    ...
  });
};
```

or an equivalent with Promises.

That is, you want to be sure that Wasm is already initialised by the time you're handling the request.

**Comment by Luisibear98** [comment]
@RReverser  thanks for the reponse!
I will use the formatting :+1: 

Now it throws me the following "Cannot enlarge memory arrays to size 17248256 bytes (OOM)" But using the flag ALLOW_MEMORY_GROWTH=1 solve the problem.

Just curious, node should be cleaning up memory after the request?

**Comment by RReverser** [comment]
No, in this case instance is shared across requests so memory will be reused (and responses will be faster since they don't need to initialise Wasm every time anymore).

As long as you correctly free everything on the C / C++ side, you should be fine, just check that memory usage stays ~constant over time no matter how many requests you send.

**Comment by RReverser** [comment]
I'll close this for now since it sounds like there is no issue here.

I suggest checking out https://emscripten.org/docs/debugging/Sanitizers.html#memory-leaks if you want more information on debugging memory leaks (in case you're suspicious you still have them) as well as asking questions on StackOverflow where more people would be able to help.

**Comment by sbc100** [comment]
I think perhaps the original request to deliberately leak the memory on the wasm side but then create a whole new wasm memory for each req?     But that does seems a little odd.

**Comment by Luisibear98** [comment]
Thanks to both for the help!
