### ISSUE TITLE
Question about String formats in printf

### ISSUE THREAD

**Issue by Luisibear98** [emscripten-core/emscripten#11316]
Hello!

I been testing the available formats for the printf functions and found that the format %m is looping and printing 0's in an infinite way.

Is this normal?

```c
int main(void) {
    printf("%m");
    return 0;
}
```

Thanks before hand

**Comment by sbc100** [comment]
It looks like we don't support %m in emscripten: https://github.com/emscripten-core/emscripten/blob/20ecfa2f8101fb21a9c0f9d75e3aa2dee6468e95/system/lib/libc/musl/src/stdio/vfprintf.c#L648

However we should probably not loop forever and print garbage :)

Since since is a GNU extension so you have an alternative code path you can use perhaps (based on strerror?)?

**Comment by Luisibear98** [comment]
What do you mean by that? :) @sbc100

**Comment by Luisibear98** [comment]
I found that some string format attacks can be executed by if the printf is wrongly coded.
But I asume that that is something more attached to the coders quality of code?

**Comment by sbc100** [comment]
I mean we have a real bug in here, but even when we fix this we will only print `%m` because we explicitly remove support for `%m` from our implementation.    

Either way I think you won't be able to use %m I'm afraid.

And yes, I'm sure there are string format attacks that exist if you allow users controlled format strings, but few programs do this (often for this reason).

**Comment by Luisibear98** [comment]
Thanks so much!
Then it will be removed to avoid printing garbage?

**Comment by sbc100** [comment]
Yes we should fix it to correctly ignore `%m` as was the original intention.
