### ISSUE TITLE
Sanity check can't work if emscripten is installed in non-writeable directory

### ISSUE THREAD

**Issue by svenstaro** [emscripten-core/emscripten#11415]
Running `emcc` when emscripten is installed to a non-writeable directory, we get

```
⌂149% θ87° [svenstaro:/tmp] % emcc main.c 
shared:INFO: (Emscripten: Running sanity checks)
Traceback (most recent call last):
  File "/usr/lib/emscripten/emcc.py", line 3937, in <module>
    sys.exit(run(sys.argv))
  File "/usr/lib/emscripten/emcc.py", line 783, in run
    shared.check_sanity(force=DEBUG)
  File "/usr/lib/emscripten/tools/shared.py", line 566, in check_sanity
    with open(sanity_file, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/usr/lib/emscripten/.emscripten_sanity'
```

Shouldn't it prefer the user home dir for this same as with the cache?

As a side note, I know I can disable the cache via env var but that's not the point of this bug report.

**Comment by sbc100** [comment]
The idea is to completely avoid writing to $HOME.

In this case I think we probably want to avoid running the sanity test if possible.  The sanity is kind of one of thing to verify that that config is good.  There is no need to do this per user since the config is shared between all users.   

I think we have a few different options:

1. Ship a copy of `.emscripten_sanity` along with `.emscripten`.  Seem slight odd but maybe the easiest fix.  This ways you are basically saying the the config is know good.
2. Set EMCC_SKIP_SANITY_CHECK in the environment.. maybe not easy way for you to do that.
3. Modify emscripten to detect read-only config skip sanity in this case (assume its a good config).

**Comment by sbc100** [comment]
4.  Allow SKIP_SANITY_CHECK to be set in the config itself?

**Comment by svenstaro** [comment]
I'm currently doing 2. via global automatically sourced profile.d file. However, I'd prefer if you could implement 3. or 4.
