### ISSUE TITLE
P is not a function: when compiling with -Os and ASM_JS=1 

### ISSUE THREAD

**Issue by simon-jentzsch** [emscripten-core/emscripten#11456]
If I compile my project as release ( `-O2`) the js-file is about 1MB and all tests pass, but using `-Os` reduces the size to 600k, but when running the tests some function names git wrong and I get an exception `P is not a function``

the linkinig command uses those options:

```sh 
emcc -DNDEBUG -Os  -s ALLOW_MEMORY_GROWTH=1  -s FINALIZE_ASM_JS=1 -s NODEJS_CATCH_REJECTION=0  -s SEPARATE_ASM=1 -s WASM=0 -s ASM_JS=1 -s EXPORT_NAME=in3w  -s FILESYSTEM=0 -s  'EXTRA_EXPORTED_RUNTIME_METHODS=["ccall", "cwrap"]' -s SINGLE_FILE=1 -s MALLOC=emmalloc @CMakeFiles/in3w.dir/objects1.rsp  -o bin/in3w.js 
```

as sdk I'm using `latest-upstream` (1.39.18 node-12.9.1-64bit)

To reproduce:

```sh
git clone --single-branch --branch develop https://github.com/slockit/in3-c.git
cd in3-c

mkdir build
cd build

emcmake cmake -DWASM=true -DASMJS=true -DWASM_EMMALLOC=true  -DCMAKE_BUILD_TYPE=MINSIZEREL .. 
make -j8 in3_wasm
make test
```

(building it with -DCMAKE_BUILD_TYPE=RELEASE works fine)

**Comment by kripken** [comment]
Thanks @simon-jentzsch ! This turned out to be a bug in binaryen, fix is in https://github.com/WebAssembly/binaryen/pull/2926

What happens is when optimizing for size we do metadce. That removes getTempRet0 in this case. But wasm2js then legalizes some internal stuff that adds a new import, which then breaks. The fix removes creation of new imports at that stage, which we don't need.

**Comment by kripken** [comment]
Fixed by that PR.

**Comment by simon-jentzsch** [comment]
thanks
