### ISSUE TITLE
Supporting '-skey=value'

### ISSUE THREAD

**Issue by tay10r** [emscripten-core/emscripten#11463]
There's an issue happening when `em++` is run with CMake, that some flags get reduced using the `-s` option, due to preexisting CMake behavior. For example:

```cmake
target_compile_options(example PRIVATE -s key1=value -s key2=value)
# Becomes '-s key1=value key2=value
```
This is documented in the 3.12.4 and up, [here](https://cmake.org/cmake/help/v3.12/command/target_compile_options.html). The working around is to use the `SHELL` syntax, but it causes extra verbosity.

```cmake
target_compile_options(example PRIVATE "SHELL: -s key1=value -s key2=value")
```

I'd like to advocate supporting arguments like this:

```cmake
em++ -skey1=value -skey2=value
```

I also believe this is related to #5852, which never got resolved.

**Comment by sbc100** [comment]
Seems like a reasonable request.  That duplication feature of cmake seem pretty crazy/risky.

**Comment by tay10r** [comment]
Thanks! Just to be clear, because I forgot to explicitly say it at first, adding this would allow these options to be used normally:

```cmake
# Doesn't reduce
target_compile_options(example PRIVATE -skey1=val -skey2=val)
```

Internally, CMake uses `std::unordered_set`, which is what reduces the options.

If I had to guess, they decided to document the behavior instead of break backwards compatibility by changing it.

**Comment by apples** [comment]
I am also running into this issue.

Regarding CMake, duplicate arguments can be handled with the `SHELL:` syntax. This is not ideal, and is an annoying hurdle for newcomers. But at least there is a way to deal with it. Lots of things in CMake are "risky" 😅 

I am also running into microsoft/vscode-cmake-tools#1350, which is probably just a bug in CMake Tools since it also occurs when using the `SHELL:` syntax.
