### ISSUE TITLE
Typedef redefinition in emscripten.h when using the Cross-compiling toolchain.

### ISSUE THREAD

**Issue by Bambofy** [emscripten-core/emscripten#11502]
I am playing with CMake and emscripted with the cross-compiling toolchain, once i set up the cmake file below, Xcode returns this error on building:
```

cmake_minimum_required(VERSION 3.0.0)

project (Proj)

#################
# C++ Standards #
#################
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_BUILD_TYPE Debug)

file(GLOB_RECURSE ALL_SRCS
        "${CMAKE_CURRENT_SOURCE_DIR}/src/*.c*"
        )
file(GLOB_RECURSE ALL_HEADERS
        "${CMAKE_CURRENT_SOURCE_DIR}/src/*.h*"
        )

source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}" FILES ${ALL_SRCS})
source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}" FILES ${ALL_HEADERS})

add_executable(Proj ${ALL_HEADERS} ${ALL_SRCS})
target_include_directories(Proj PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)

find_path(EMSCRIPTEN_INCLUDE_DIRS EMSCRIPTEN)
target_include_directories(Proj PUBLIC ${EMSCRIPTEN_INCLUDE_DIRS})
```

<img width="1135" alt="Screenshot 2020-06-26 at 09 43 31" src="https://user-images.githubusercontent.com/1304898/85838443-7fc55080-b791-11ea-87ab-910c23f459ef.png">

The previous definition was found at:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_stdio.h

**Comment by sbc100** [comment]
You should never be including any files from `MacOSX.sdk` when building for emscripten.   Emscripten is a cross compiler ans doesn't support system headers or libraries.

The easiest way to use emscripten with cmake is to use the toolchain that we ship in `cmake/Modules/Platform/Emscripten.cmake` and the easiest way to do that is by running `emcmake` rather than cmake directly.
