### ISSUE TITLE
Emscripten intercepts Errors, even with NODEJS_CATCH_EXIT=0

### ISSUE THREAD

**Issue by maierfelix** [emscripten-core/emscripten#11532]
I build with:
````
-s ASSERTIONS=0 -s WASM=1 -s MODULARIZE=1 -s WASM_ASYNC_COMPILATION=0 -s NODEJS_CATCH_EXIT=0
````

The problematic line is:
````
process["on"]("unhandledRejection", abort);
````
Which intercepts all errors. This seems to be the same issue as why the `NODEJS_CATCH_EXIT` flag was invented.

**Comment by kripken** [comment]
That does sound like a bug, thanks @maierfelix . Would you like to open a PR to fix it? I think just `#ifdef`ing that line with that flag would do it.

**Comment by PietroMarchini94** [comment]
I gave an eye to the code and found that process["on"]("unhandledRejection", abort) is conditioned as follow

```
#if NODEJS_CATCH_EXIT
  process['on']('uncaughtException', function(ex) {
    // suppress ExitStatus exceptions from showing an error
    if (!(ex instanceof ExitStatus)) {
      throw ex;
    }
  });
#endif

#if NODEJS_CATCH_REJECTION
  process['on']('unhandledRejection', abort);
#endif
```

where 

```
// Catch unhandled rejections in node. Without this, node may print the error,
// and that this behavior will change in future node, wait a few seconds, and
// then exit with 0 (which hides the error if you don't read the log). With
// this, we catch any unhandled rejection and throw an actual error, which will
// make the process exit immediately with a non-0 return code.
var NODEJS_CATCH_REJECTION = 1;
```
(link to the process node API [https://nodejs.org/api/process.html#process_event_rejectionhandled](url))

Considering that not handling `unhandledRejection` is deprecated 

> Event: 'unhandledRejection'
>  
> Version | Changes
> -- | --
>  v7.0.0 | Not handling Promise rejections is deprecated.
>  v6.6.0 | Unhandled Promise rejections will now emit a process warning.
>  v1.4.1 | Added in: v1.4.1
> 

**I wonder if it make sense to set `--unhandled-rejections=strict` in order to redirect all the `unhandledRejection` into the `NODEJS_CATCH_EXIT` case through another #define to keep divided the 2 distinct events.
(reference below)**

> --unhandled-rejections=mode#
> Added in: v12.0.0, v10.17.0
> By default all unhandled rejections trigger a warning plus a deprecation warning for the very first unhandled rejection in case no unhandledRejection hook is used.
> 
> Using this flag allows to change what should happen when an unhandled rejection occurs. One of the following modes can be chosen:
> 
> throw: Emit unhandledRejection. If this hook is not set, raise the unhandled rejection as an uncaught exception.
> strict: Raise the unhandled rejection as an uncaught exception.
> warn: Always trigger a warning, no matter if the unhandledRejection hook is set or not but do not print the deprecation warning.
> warn-with-error-code: Emit unhandledRejection. If this hook is not set, trigger a warning, and set the process exit code to 1.
> none: Silence all warnings.

(for reference [https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode](url))

**Comment by kripken** [comment]
@maierfelix Does `-s NODEJS_CATCH_REJECTION=0` fix your issue, as @PietroMarchini94 mentioned?

@PietroMarchini94 Interesting. What does `Not handling Promise rejections is deprecated` mean, though? (In general, I think we can do whatever makes sense for Node 12+, as that's the current LTS release.

**Comment by maierfelix** [comment]
Yep indeed, that fixed it.

**Comment by PietroMarchini94** [comment]
@kripken  As per Nodejs API documentation before v7.0 was allowed to leave a promise rejection event falling into nothing without interrupt the execution.
I highlighted this because from the 7.0 not handling that event cause application to exit with non-zero value in the same way as `uncaughtException`.

For this reason I think that `NODEJS_CATCH_EXIT` can handle the 2 different scenarios, this way with the `NODEJS_CATCH_EXIT=0` flag the 2 exceptions are free to bubble up causing application exit.

From my point of view the are 2 possibile solutions :

   - allow to set nodejs argument `--unhandled-rejections=strict` in order to handle `unhandledRejection` as `uncaughtException`
   - change shell.js from this:

```js
#if NODEJS_CATCH_EXIT
  process['on']('uncaughtException', function(ex) {
    // suppress ExitStatus exceptions from showing an error
    if (!(ex instanceof ExitStatus)) {
      throw ex;
    }
  });
#endif

#if NODEJS_CATCH_REJECTION
  process['on']('unhandledRejection', abort);
#endif
```

to something like this

```js
 
#if ( NODEJS_CATCH_EXCEPTION && NODEJS_CATCH_EXIT )
  process['on']('uncaughtException', function (ex) {
    // suppress ExitStatus exceptions from showing an error
    if (!(ex instanceof ExitStatus)) {
      throw ex;
    }
  });
#endif

#if ( NODEJS_CATCH_REJECTION && NODEJS_CATCH_EXIT ) 
  process['on']('unhandledRejection', abort);
#endif
```
this way `NODEJS_CATCH_EXIT=0` flag has its proper function and it's still possible to set  `NODEJS_CATCH_REJECTION=0 ` and  `NODEJS_CATCH_EXCEPTION=0 ` separately.

**Comment by sbc100** [comment]
I'm quit understand that problem here, we already have two different flags for controlling uncaught exceptions and unhanded rejections. 

Why would need a third option?   What purpose would it serve?    Is it just that you want single option to disable both behaviours? 

Why would you want to disable NODEJS_CATCH_REJECTION?   Is it that you app already has its own unhandledRejection handler?

**Comment by PietroMarchini94** [comment]
As signed as bug I supposed that the expected behavior of `NODEJS_CATCH_EXIT=0` was intended to allow bubble up preventing handling by default to avoid issue with user's handlers.
If the expected behavior is only to block exception rised by ExitStatus exception I obviously agree that issue was closed with `-s NODEJS_CATCH_REJECTION=0` and I'm sorry for the pointless discussion!

**Comment by sbc100** [comment]
Sorry, I didn't mean to shut down the discussion here.  I would just err on the side of not adding yet more options if possible.

It sounds like you think it make more sense to have a single option for controlling both these things maybe thats what people will want most of the time?

We could have to worry about users setting NODEJS_CATCH_EXIT=0 and NODEJS_CATCH_REJECTION=1 at the same time.. I guess that would be an error?

For the node behaviour change..perhaps we can check if we are running a on recent node version and in that case always avoid the unhandledRejection thing?

**Comment by pmarchini** [comment]
I think that all depends on how this part of source is expected to work.
I think that NODEJS_CATCH_EXIT at the moment has not any documentation ( if I've not missed something ) and for that reason is not so clear.

```
// Emscripten uses an ExitStatus exception to halt when exit() is called.
// With this option, we prevent that from showing up as an unhandled
// exception.
var NODEJS_CATCH_EXIT = 1;
```
Reading the source it becomes clear : this setting was made only to avoid unwanted error spawning on exit().
I expect an user to set NODEJS_CATCH_EXIT=0 if his app has (as I would expect) its proper handler.

this issue was caused by this misconception : user expected to remove handlers with `-s NODEJS_CATCH_EXIT=0 ` and found exceptions handled by `process['on']('unhandledRejection', abort);` .


To reply to your questions  : 

> It sounds like you think it make more sense to have a single option for controlling both these things maybe thats what people will want most of the time?

Yes, I think that it would be clearer but I don't have a total vision of the project as you have and so it's your opinion what I'm looking for.

> We could have to worry about users setting NODEJS_CATCH_EXIT=0 and NODEJS_CATCH_REJECTION=1 at the same time.. I guess that would be an error?

I would expect a message of warning or an error to come out in case of bad combinations of flags (as it was done in other parts of the source).

> For the node behaviour change..perhaps we can check if we are running a on recent node version and in that case always avoid the unhandledRejection thing?

I think that it would be a way considering that not handling the Rejection will in any case led to exit with error.

My question is : 
From your point of view handling by default `uncaughtException` and `unhandledRejection ` can lead to conflicts with external user handlers?
