### ISSUE TITLE
Import #1 module="env" function="dlopen" error: function import requires a callable

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#11707]
I have no idea what this means. I have complied a side module and imported it like this,

`	dlopen("side.wasm", RTLD_NOW);

I've pre-loaded it using --preload-file side.wasm

The side module doesn't export any functions other than printing "Hello World" via std::cout

**Comment by sbc100** [comment]
It looks like `dlopen` is undefined in your main module.. which is strange.

Can you share the command line you are using to build your main module?  I assume you are outputing to JS and using emscripten-generated JS code?

**Comment by gerald-dotcom** [comment]
Here it's,

`em++ Entry.cpp -o Entry.js -Oz --bind -I C:\EntryCore\ -s FETCH=1 -s MODULARIZE=1 -s MAIN_MODULE=1  -s EXPORT_ALL=1 -s "EXPORT_NAME='CoreEntry'" -s DISABLE_EXCEPTION_CATCHING=0 -s ASYNCIFY=1 -s NO_EXIT_RUNTIME=1 -s "ASYNCIFY_IMPORTS=['getOne', 'getTwo']" -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap', 'malloc', '_malloc']" -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --preload-file side.wasm
`

**Comment by sbc100** [comment]
And it fails on startup when run Entry.js?   I can't see how dlopen could be missing.  Can you build without `Oz` and look at the resulting js file.   It should contain the dlopen function from src/library.js.   

Can you reduce this to test case that you can share?

If I take a simple test program I can't reproduce this with roughtly the same flags you passed:

```
$ cat test.cpp 
#include <dlfcn.h>
#include <stdio.h>

int main() {
  printf("dlopen returned: %p\n", dlopen("foobar", 0));
  return 0;
}
$ ./em++ test.cpp -o test.js -Oz --bind -s FETCH=1 -s MAIN_MODULE=1 -s EXPORT_ALL=1 -s "EXPORT_NAME='CoreEntry'" -s DISABLE_EXCEPTION_CATCHING=0 -s ASYNCIFY=1 -s "ASYNCIFY_IMPORTS=['getOne', 'getTwo']" -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap', 'malloc', '_malloc']" -s WASM=1 -s ALLOW_MEMORY_GROWTH=1
$ node ./test.js 
dlopen returned: 0
```

I had to remove `MODULARIZE=`1 to make it work from the command line, and  `--preload-file` because i don't have the file.

But as you can see the dlopen symbol is there, and works and returns null as expected in this case.

Is MODULARIZE the problem?  I doubt it some how.  I can't see how dlopen is any different to any other symbol referenced by your main module.

**Comment by gerald-dotcom** [comment]
@sbc100 I was clueless. I found a file called Entry.data on the root dir and it had same size of side.wasm, now I copied it to my server /src dir and the error seems to be gone, however; I don't see anything get printed out. 

I'm not sure what's this .data file is

**Comment by gerald-dotcom** [comment]
I'm closing this for now..
