### ISSUE TITLE
Loading WASM modules change the NodeJS unhandled-promise-rejection behavior

### ISSUE THREAD

**Issue by yllan** [emscripten-core/emscripten#11768]
Hi.

I don't even know if this is actually an emscripten bug or node's bug. Just observed some strange behavior.

If I load a wasm module compiled by emscripten in NodeJS 12, the unhandled-promise-rejection behavior is changed: if I comment out line 2, the unhandled-promise-rejection will not terminate the node. However, if I uncomment line 2, it immediately crash the node.

<img width="913" alt="Screen Shot 2020-07-31 at 4 19 40 PM" src="https://user-images.githubusercontent.com/76055/89017760-6b0a4880-d34d-11ea-9c6a-6597723ae616.png">
<img width="913" alt="Screen Shot 2020-07-31 at 4 20 00 PM" src="https://user-images.githubusercontent.com/76055/89017774-71002980-d34d-11ea-80ec-f3a0d0db227b.png">

Here's a demonstration project:
https://github.com/yllan/unhandled-promise-rejection/

**Comment by yllan** [comment]
OK. I've found that's because this line:

```javascript
  process['on']('uncaughtException', function(ex) {
    // suppress ExitStatus exceptions from showing an error
    if (!(ex instanceof ExitStatus)) {
      throw ex;
    }
  });

  process['on']('unhandledRejection', abort);
```

But why? What will happened if I delete these handler?

**Comment by sbc100** [comment]
Some version of node will just exit with 0 in this case.   I believe we had issues where failures in testing were going unnoticed because tests returning 0 is signal of success.

It could be that recent versions of node have fixed that.. i seem to remember them promising they would do that.

In the mean time I think you can build with `-s NODEJS_CATCH_REJECTION=0` to fix this no?

**Comment by yllan** [comment]
Thanks. It works.
