### ISSUE TITLE
Closure mode doesn't support ES6+

### ISSUE THREAD

**Issue by curiousdannii** [emscripten-core/emscripten#11893]
Closure is still being called with options specifying ES5. If you want to use, for example, async functions with Asyncify, then you can't run Closure.

```
tmp/emscripten_temp__mkbpedk/tads-core.wasm.o.js.jso.js.jso.js.jso.js.jso.js:640: ERROR - [JSC_LANGUAGE_FEATURE] This language feature is only supported for ECMASCRIPT8 mode or better: async function.
 return Asyncify.handleAsync(async () => {
                             ^
```

**Comment by kripken** [comment]
I looked into this a little but ran out of time when it wasn't trivial,

https://github.com/emscripten-core/emscripten/compare/es6?expand=1

That diff (temporarily) removes support for old browsers so that we can assume ES6, and then runs closure with ES6 support. It increases code size as the diff shows. I think that's because the license text is no longer handled properly, see the code. Fixing that might let us make this change, would be good if someone wants to look into it.

**Comment by kripken** [comment]
Oh, I think it was a combination of the license and that it also emits "use strict" automatically for ES6. We need to remove that too.
