### ISSUE TITLE
Document embind limitations regarding library (.a) files

### ISSUE THREAD

**Issue by IvanRomanovski** [emscripten-core/emscripten#11973]
Compiling quick_example.cpp (https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#a-quick-example) directly via emcc works as expected:
```
emcc --bind -o quick_example.js quick_example.cpp
```

Compiling to a static archive first and then binding does not produce JS bindings.
```
emcmake cmake .
emmake make
emcc --bind -o emsdktest.js libemsdktest.a
```

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.10)
set(CMAKE_CXX_STANDARD 14)

project(emsdktest)

file(GLOB emsdktest_sources "./quick_example.cpp")

add_library(emsdktest ${emsdktest_sources})
```

Adding following lines to CMakeLists.txt resolves the problem and produces JS bindings:
```
set(CMAKE_STATIC_LIBRARY_SUFFIX ".bc")
set(CMAKE_C_CREATE_STATIC_LIBRARY "emcc -o <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_CXX_CREATE_STATIC_LIBRARY "emcc -o <TARGET> <LINK_FLAGS> <OBJECTS>")
```
This is what option EMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES used to enable but now it was removed (https://github.com/emscripten-core/emscripten/pull/10909). 

Am I doing something wrong?

**Comment by sbc100** [comment]
I think this is because of the way library code works.   I think perhaps the binding code is run as a static constructor and static constructors only get run if the object file is included in the link.   When an object file lives inside an archive file the default behaviour is to exclude the object file unless it is explicitly needed.

You can work around this behavior by using the `'--whole-archive` and `--no-whole-archive` linker flags around your library. e.g.

`-Wl,--whole-archive -lemsdktest -Wl,--no-whole-archive`

Here is some info on how to do this from cmake:

https://stackoverflow.com/questions/53071878/using-whole-archive-linker-option-with-cmake-and-libraries-with-other-library

**Comment by IvanRomanovski** [comment]
Thanks @sbc100. You put me on the right path, indeed the following worked:
```
emcmake cmake .
emmake make
emcc --bind -o emsdktest.js -Wl,--whole-archive libemsdktest.a -Wl,--no-whole-archive
```

It mind be beneficial to put this in the embind guide. I am sure I am not the only one who was stumped by this.

Thanks again for the explanation!

**Comment by sbc100** [comment]
PRs to update the embind docs would certainly be welcome.  I'll tag this bug with "good first bug" in case anyone wants something easy to take on.

**Comment by IvanRomanovski** [comment]
Thanks. Sorry for the mixup with closing the issue.
