### ISSUE TITLE
Lack of wasm_i8x16_mul in emscripten 2.0.0 makes an error in the building of OpenCV.js with SIMD optimization

### ISSUE THREAD

**Issue by lionkunonly** [emscripten-core/emscripten#12018]
In the building of OpenCV.js with SIMD optimization, the intrinsic of OpenCV.js which uses the APIs of WASM SIMD utilizes the function `wasm_i8x16_mul`. Now, in the 2.0.0 version, the function `wasm_i8x16_mul` is removed, which causes an error in the building of OpenCV.js.  Cloud you support this function in the emscripten 2.0.0.

**Comment by tlively** [comment]
This intrinsic was removed because there is no `i8x16.mul` instruction in the SIMD proposal, so using it would have resulted in a scalarized operation. You should update the OpenCV code to use some other code sequence or to scalarize the operation in the source. Note that the SIMD intrinsics should not be considered stable until the proposal is standardized.
