### ISSUE TITLE
Uncaught ReferenceError: autoResumeAudioContext is not defined

### ISSUE THREAD

**Issue by Ghabry** [emscripten-core/emscripten#12063]
Hello,

I just updated to emscripten 2.0.1 (with emsdk) and to the latest SDL2 with

```
git clone --depth=1 https://github.com/emscripten-ports/SDL2.git
emconfigure ./configure --prefix=$WORKSPACE --host=asmjs-unknown-emscripten \
  --disable-shared --enable-static --disable-assembly --disable-threads --disable-cpuinfo
make install
```
(this is how I compile SDL2 emscripten since the beginning)

When i compile now my application as usual with CMake and run it through a html shell file I get the following error when SDL code is entered:

``Uncaught ReferenceError: autoResumeAudioContext is not defined``

I see the autoResumeAudioContext in the library.js file and attempted ``-s EXTRA_EXPORTED_RUNTIME_METHODS="['autoResumeAudioContext']"`` but it still fails.

My CMake build flags are:
```
set_property(TARGET ${PROJECT_NAME}_exe PROPERTY LINK_FLAGS "-s ALLOW_MEMORY_GROWTH=1 -s ASYNCIFY=1  --pre-js ${PLAYER_JS_PREJS} --post-js ${PLAYER_JS_POSTJS}")
set_target_properties(${PROJECT_NAME}_exe PROPERTIES SUFFIX ".html")
set_property(TARGET ${PROJECT_NAME}_exe APPEND_STRING PROPERTY LINK_FLAGS " --shell-file ${PLAYER_JS_SHELL}")
```
The prejs and postjs add a few new fields to the Module dict.

Did I miss any information in the docs?

**Comment by kripken** [comment]
You may be using a different/older SDL than emscripten expects. Instead of building it manually, does using `-s USE_SDL=2` work?

**Comment by kripken** [comment]
The problem also might be the reverse - is there an older emscripten in your path maybe, that you are using by mistake? You need the newest emscripten + SDL together.

If that's not it, maybe you've found a bug, please try to provide a testcase.

**Comment by Ghabry** [comment]
I didn't knew about ``-s USE_SDL=2`` but with this flag it works!

I looked in the ports directory now and there is a:
```
settings.DEFAULT_LIBRARY_FUNCS_TO_INCLUDE += ['$autoResumeAudioContext']
```

Linking with my manually built SDL and adding ``-sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=['$autoResumeAudioContext']`` fixes it. So this seems to be more of a documentation issue, maybe this should be mentioned somewhere.

**Comment by kripken** [comment]
Great!

That makes sense, yes, the ports code also does other setup that is necessary.

I agree the docs could mention more about this. I was working on a separate PR for docs anyhow so I added a little for that now, https://github.com/emscripten-core/emscripten/pull/12064

**Comment by sasq64** [comment]
I get the exact same issue with latest at the moment.

I use the included SDL2 and nothing special (USE_SDL=2)
I've updated emscripten with `git pull` and install/activate latest
I've made sure I do a complete rebuild.

**Comment by sasq64** [comment]
Also did --clear-ports and --clear-cache

**Comment by sasq64** [comment]
Solved.
To others; I had used "-sUSE_SDL=2" _only_ in my compile flags, not in my linker flags.
Strangely this worked fine until I started using Audio.

**Comment by rokups** [comment]
I recently updated my project to a new SDL version and now that upstream SDL contains needed changes i can switch to using my in-tree SDL instead of one bundled with emscripten. However i bumped into this exact issue and i cant find a solution. I tried everything described in this issue... I updated my sdl2 cmake script with these statements:
```cmake
target_compile_options(SDL2-static PUBLIC -sUSE_SDL=0)
target_link_libraries(SDL2-static PUBLIC -sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=$autoResumeAudioContext)
```

> -sUSE_SDL=0

Since i use in-tree SDL i suppose i should disable a port, right?

> -sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=$autoResumeAudioContext

This does not make function available somehow. I also tried different variations of this flag (`-sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE` vs `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE`) (`=$autoResumeAudioContext` / `=autoResumeAudioContext` / `=['$autoResumeAudioContext']`). I also tried to add these flags directly to executable target instead of SDL library. I also tried using `target_compile_options()` for `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE`. It always results in same exception of `autoResumeAudioContext` being missing.

I am using:
SDL v2.24.0
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.21 (f9e81472f1ce541eddece1d27c3632e148e9031a)
clang version 16.0.0 (https://github.com/llvm/llvm-project a4a29438f451370ed241dde30bfcaab0fdf2ab71)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/rk/src/games/SDKs/emsdk/upstream/bin
```

Could we get some documentation on how we are supposed to build with our own SDL version instead of a port?

Also, upstream SDL cmake script should probably include needed `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` flag.

**Comment by sbc100** [comment]
I think the problem is that cmake is turning `$autoResumeAudioContext` to the empty string.  So you end up with `-sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=` on th command line (with nothing after the equals sign).  Can you run your build with verbose enabled (https://bytefreaks.net/programming-2/make-building-with-cmake-verbose) so you can see the full link line and confirm that that $autoResumeAudioContext appears there.

Fundamentally I think we need to make it so that the EM_ASM code inside of he SDL library can express this dependency directly.  I'm working on that here: https://github.com/emscripten-core/emscripten/pull/17854

**Comment by sbc100** [comment]
Reopening now that #17854 is coming.  We can close once the SDL2 source code itself contains this dependency.

**Comment by rokups** [comment]
I tried to follow `$` down the rabbit hole, but no matter what i could not get around the error. I am using a ninja generator and i was inspecting generated output, verifying that `$` is escaped correctly... But something is still missing. `EM_JS_DEPS()` will make our live so much easier, thanks!

**Comment by Ghabry** [comment]
We use this in a project to pass the exported functions with CMake:

```
set_property(TARGET ${EXE_NAME} PROPERTY LINK_FLAGS "-s ALLOW_MEMORY_GROWTH=1 -sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=['$autoResumeAudioContext','$dynCall']")
```

**Comment by sbc100** [comment]
Can you somehow confirm that the `-sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE` is making to all the way to the emcc command line?   You should do this my linking with `EMCC_DEBUG=1` .. or maybe just adding `-v` the link command would be enough?

**Comment by sbc100** [comment]
Oh, wait, it sounds like @Ghabry's solution is working .. can you try that?
