### ISSUE TITLE
Consider running clang with -fno-limit-debug-info for -g

### ISSUE THREAD

**Issue by pfaffe** [emscripten-core/emscripten#12060]
When building with debug symbols, clang normally optimizes the generated symbols and removes those from the binary that it expects to be present on the system. That includes symbols for the STL for example. To see the effect, compile a C++ file to a native binary and inspect the debug info. The information for things like std::string will be incomplete. Actually debugging the program with gdb without having the libstdc++ (e.g.) will get you a bunch of Python errors in that case.

For emscripten, this optimization is problematic, because the symbol libraries don't exist there. The optimization can be switched off by passing `-fno-limit-debug-info`. Size and performance will inevitably suffer, but the quality of the symbols is improved.

**Comment by sbc100** [comment]
I have had success using this flag with emscripten?   It does seem like good idea, as long as users can opt out if they want.

**Comment by sbc100** [comment]
We currently don't ever build our standard libraries (libc++, libc, etc) with debug information.   Would building them with debug info also solve this issue?

**Comment by pfaffe** [comment]
> It does seem like good idea, as long as users can opt out if they want.
Clang limits the amount of exported debug info because it expects developers to load symbols from their standard library installation. In wasm land, the library is statically linked,  I don't expect developers to have matching library version lying around. There's also currently no way for a wasm module to indicate that it requires additional externally loaded symbols.

>  Would building them with debug info also solve this issue?
I haven't tried that yet, but I can if you'd like. We'd need to teach emscripten to distinguish debug and release builds of the system libs and to pick up cached debug builds of the system libs if building with -g. It seems much simpler to just never limit debug info, given that we don't profit from the benefits of limiting anyways.

**Comment by sbc100** [comment]
Are you saying that with fully static linking there is just no advantage to limiting debug info?    `-fno-limit-debug-info` doesn't cause the size of the debug into to be unnecessarily bloated or anything like that?     I guess we can just try building with it and make sure it doesn't increases the size and redundancy of the debug information too much (presumably it will get somewhat larger as that is what you are asking for right?)

**Comment by sbc100** [comment]
I'm having trouble getting good documentation on exactly how this option works, but looking at https://reviews.llvm.org/D72427 it seems like this option limits debug info to only be emitted when a constructor is found.   Is that right?    So if you have 100 source files including the same type, but that type's constructor is only present in a single one of them, then only that one source file will get debug info for that type?   Is that right?     If so it seems that would not just effect user system libraries but also user code too, and could result in larger debug info sections in the final binary?  I'm just trying to understand all the ramifications here.

**Comment by sbc100** [comment]
I did a little more digging.  It looks like `-fno-limit-debug-info` is an alias for `-fstandalone-debug` (which is why its a little hard to google:

https://github.com/llvm/llvm-project/blob/164bcbd40e6d10cd8a01477e2e9029b955fea93b/clang/include/clang/Driver/Options.td#L2272

The behaviour of `-fstandalone-debug` is documented here:

https://clang.llvm.org/docs/UsersManual.html#cmdoption-fstandalone-debug

It does looks like this could result in more redundancy if we enable it by default.   @dschuff @kripken what do you think?   From the documentation it says: "This is useful when working with 3rd-party libraries that don’t come with debug information."    It seems like choice between (a) bloating all debug wasm files or (b) shipping debug info with all our system libraries.

I wonder if simply adding `-g` to our existing optimized standard libraries would work?   It would make the stdlibs larger the cost of the extra debug info would only be paid when building with `-g`.   Non-debug builds are linked with `-strip-debug` so should not be effected.

**Comment by pfaffe** [comment]
Even when stripping symbols after the fact, we'd still pay some price during linking.

**Comment by sbc100** [comment]
Are you think of the cost of mmap'ing larger system libraries (with debug sections that are then ignored)?    I guess we should compare that cost to cost of shipping a completely separate set of debug libraries.

For large application I imagine that the link-time cost of a release build will be dominated by user-code rather that system libraries.   libc++ itself is a really tiny library (since its mostly implemented in headers) so we are mostly talking about libc and compiler-rt here I guess.   I'll see if I can measure the link time cost.

**Comment by sbc100** [comment]
I put up https://github.com/emscripten-core/emscripten/pull/13078 as an experiment

**Comment by pfaffe** [comment]
I'm not sure I see the upside of offloading the symbols to the system libraries instead of just using no-limit-debug-info. We need to manage extra libraries builds, extra cache entries, extra cache invalidation. That's a lot of complexity compared to just passing a single extra flag to clang.

**Comment by sbc100** [comment]
I'm not sure what extra complexity you are referring too.   The change proposed in #13078 doesn't add any extra builds, it just adds debug into the existing system libraries.

Are you not worried that `-fstandalone-debug` (can we refer to it by that name) would add more duplication in the final output?   Imagine a large program where the debug info the std::string is present in every single object file rather than just in the the object in libc++.a... it seems like it make the effect of https://bugs.llvm.org/show_bug.cgi?id=48828 even worse.

**Comment by pfaffe** [comment]
Were you able to measure the cost for non-debug builds?

**Comment by sbc100** [comment]
Yes, it looks like there was no measurable effect (see https://github.com/emscripten-core/emscripten/pull/13078#issuecomment-756183287).   The linker just completely ignores those extra sections.    I also measured (I think) in such a way as to maximize the effect: using a program that was 99.9% system libraries and 0.01% user code.

**Comment by pfaffe** [comment]
Those results do look promising! Happy to withdraw my concerns in that case! I understood out were planning to build system libs with and without symbols and pick the right ones depending on `-g`.

> Do our users want to step into system libraries often enough?

It's important to note that this feature (or standalone-debug at least) is not only necessary to step into system code. It's also necessary to look at standard library types. Without it, you can't inspect `std::vector` for example.
