### ISSUE TITLE
A case for 64-bit emscripten

### ISSUE THREAD

**Issue by Zelex** [emscripten-core/emscripten#12087]
Trying to do inference with deep neural networks on 32-bit memory limitations is extremely limiting. I'm sure 32-bit was the lowest-common-denominator and stuff, but having a 64-bit option would really enable many more applications - even if it didn't work on ALL platforms - that's ok! Let the website switch between 64-bit and 32-bit WASM options based on browser capabilities.

**Comment by sbc100** [comment]
This is not really something emscripten can provide, but more something for the WebAssembly spec itself.   The proposal you want to check out is probably: https://github.com/WebAssembly/memory64.

**Comment by kripken** [comment]
I believe @aardappel is looking into this on the toolchain side.

**Comment by aardappel** [comment]
Yes, I am modifying Binaryen to support it as we speak, and already modified LLVM, LLD and WABT to support it. At some point that will come together in Emscripten support. Then you need VMs to support it as well.. I believe it is being explored in V8.

**Comment by sbc100** [comment]
This is being worked on.  I'm not sure if we want to keep this open a tracking bug.  I've close it for now.  @aardappel do you have a tracking bug open already that folks can watch?

**Comment by aardappel** [comment]
@sbc100 no, there is no tracking bug for Memory64 support in Emscripten.. it is probably early days for that.

**Comment by jreininghaus** [comment]
@sbc100 do you know if this issue (Memory64 support in Emscripten) is still being worked on by someone? @aardappel told me that he is no longer working on it.

**Comment by sbc100** [comment]
Yes, I am actively working on it, and its improved a lot recently.  For example embind support is now there.  The remaining missing features I believe the exception handling (setjmp/longjmp), threading and dynamic linking.  If you don't use any of these features you should give it a try.

**Comment by jreininghaus** [comment]
@sbc100, that is great news! Thanks a lot for the update, we are going to try this out in the coming weeks. Do you happen to know if the Chrome support for Memory64 support is also coming along? According to https://webassembly.org/roadmap/ there is currently only support for this in Firefox nightlies on the browser side.

**Comment by sbc100** [comment]
In v8 is currently behind a flag.  I'm not sure how enable it chrome I'm afraid but I guess there must be some way.

**Comment by PhM81** [comment]
@sbc100 i have tried to get a wasm64 build of an opengl based rendering framework to work.
The primary stumbling blocks for this are on the emscripten side of things (there are a lot of issues related to BigInt and Number being used in one expression). I have been able to get most of this to work by adding a lot of hacks. If you are interested i can provide a more detailed list of changes that were required.

Now i am wondering how i can get beyond the 4GB limit of the wasm memory. I am currently using firefox nightly builds and something like this

const memory = new WebAssembly.Memory({
  initial: 1,
  maximum: 100000
});

results in a "RangeError: bad Memory maximum size" exception (this should allow for roughly 6GB of memory).
Is there a development flag i have to enable in order to be able to go beyound 4GB?

**Comment by sbc100** [comment]
If you build with `-sMEMORY64` emscripten will produce a module that creates (and exports) a 64-bit memory.   In terms of the JS API for creating a 64-bit memory, that has not yet been speced.

See: https://github.com/WebAssembly/memory64/blob/main/proposals/memory64/Overview.md

Here is the issue if you want to be part of adding it: https://github.com/WebAssembly/memory64/issues/24

**Comment by PhM81** [comment]
Thanks for the quick reply,
I think i might have posed my question a little misleadingly (i assumed that creating a new Wasm Memory via JS would be similar to how emscripten runtime allocates its memory). 

What i waned to know was:
Is there a way to set up the emscripten build such that the compiled code can allocate more than 4GB of memory on the heap? 

I now have been able to go beyound 4GB to 8GB (which i assume is the current maximum for firefox nightlies?) by setting "-s MEMORY64=1 -s INITIAL_MEMORY=8GB". Using memory growth to reach beyond 4GB was not (easily) possible since a lot more code in emscripten would have to be fixed.
I had to jump through quite a few hoops to get this to work. For one, the sbrk implementation of emscripten has a hardcoded 4GB limit and a lot of the code that is being put into the .js file of the build is also not capable to properly handle lookups into HEAPXX instances that are larger than 4GB. Other than that, the whole OpenGL emulation layer currently also cannot deal with this.

I can provide notes on the changes that i had to make in order to get my code to

**Comment by sbc100** [comment]
Indeed, as you have discovered `-sMEMORY64` is still a work in progress.  If you would like to help out by submitting your changes here that would be very welcome. 

In the mean time I guess we should probably at a warning to let folks you use `-sMEMORY64` that it is still very experimental.

**Comment by PhM81** [comment]
@sbc100 how do you want me to submit the (hacky) changes i had to make?
I have attached a patch file. As noted, these changes are in no way production quality code, but they might help with identifying stuff that has to be fixed up in order to advance the memory64 project.

[0001-memory64-fix-for-opengl.patch.txt](https://github.com/emscripten-core/emscripten/files/9425677/0001-memory64-fix-for-opengl.patch.txt)

**Comment by sbc100** [comment]
Uploading PRs would be great.  But attaching patches works too.   The good thing about the PR is that we can iterate on it and see if it passes tests.   Obviously there is no obligation to do this, but if you have time it would be great.

**Comment by PhM81** [comment]
I have created the following pull request
https://github.com/emscripten-core/emscripten/pull/17743
