### ISSUE TITLE
Bug in page:Interacting with code 

### ISSUE THREAD

**Issue by mingodad** [emscripten-core/emscripten#12137]
There is a space in the code to run -> **'["ccall", "cwrap"]'** should be -> **'["ccall","cwrap"]'** otherwise we get a shell error:
```
emcc: error: "cwrap"]: No such file or directory (""cwrap"]" was expected to be an input file, based on the commandline arguments provided)
```
```
<p>To compile this code run the following command in the Emscripten
home directory:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="o">./</span><span class="n">emcc</span> <span class="n">tests</span><span class="o">/</span><span class="n">hello_function</span><span class="o">.</span><span class="n">cpp</span> <span class="o">-</span><span class="n">o</span> <span class="n">function</span><span class="o">.</span><span class="n">html</span> <span class="o">-</span><span class="n">s</span> <span class="n">EXPORTED_FUNCTIONS</span><span class="o">=</span><span class="s1">'["_int_sqrt"]'</span> <span class="o">-</span><span class="n">s</span> <span class="n">EXPORTED_RUNTIME_METHODS</span><span class="o">=</span><span class="s1">'["ccall", "cwrap"]'</span>
</pre></div>
</div>
```

URL: ../../../docs/porting/connecting_cpp_and_javascript/Interacting-with-code

**Comment by r-pankevicius** [comment]
The issue is about documentation https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html showing how to compile hello_function.cpp.

However, the issue is not in space between "ccall", "cwrap" but it's aboud a different command line "spaces spacing" in Linux compared to Windows. So if you'd swap ' and " in Windows (my guess is that you use Windows), then this syntax will work fine:

`emcc hello_function.cpp -o function.html -s EXPORTED_FUNCTIONS="['_int_sqrt']" -s EXPORTED_RUNTIME_METHODS="['ccall', 'cwrap']"
`
Of course documentation shall tell this difference.
