### ISSUE TITLE
Example docker command doesn't work

### ISSUE THREAD

**Issue by vedantroy** [emscripten-core/emscripten#12246]
The example Docker command at: https://hub.docker.com/r/emscripten/emsdk

```
docker run \
  --rm \
  -v $(pwd):$(pwd) \
  -u $(id -u):$(id -g) \
  emscripten/emsdk \
  emcc helloworld.cpp -o helloworld.js
```
results in the following error:
```
emcc: error: helloworld.cpp: No such file or directory ("helloworld.cpp" was expected to be an input file, based on the commandline arguments provided)
```

**Comment by sbc100** [comment]
Ah, it looks like the volume mount is wrong.  Should be `-v $(pwd):/src`

**Comment by sbc100** [comment]
Fixed.  Looks like the upstream doc was already updated: https://github.com/emscripten-core/emsdk/tree/master/docker

(I guess it would be nice if they are automatically in sync).

**Comment by samcov** [comment]
On Windows 10, I get the following error.
**emcc: error**: helloworld.cpp: No such file or directory ("helloworld.cpp" was expected to be an input file, based on the commandline arguments provided)

Running the following command:
docker run  --rm  -v /D/Dev/Emscripten  emscripten/emsdk  emcc helloworld.cpp -o helloworld.js

I'm having trouble with emcc finding the file for some reason. BTW, I removed the -u stuff because it generated errors.

**Comment by sbc100** [comment]
The idea is that you would have a file such as `helloworld.cpp` somewhere on your host filesystem.  The `-v` flag then mounts that filesystem. 

emcc runs in the `/src` directory within the container by default so if you want it to find `helloworld.cpp` as a relative path you need to ensure that `helloworld.cpp` exists in `/src`.  This is why the example mounts the current directory on `/src` using `-v $(pwd):/src`.   You could do that same assuming your helloworld.cpp file lives in `/D/Dev/Emscripten` via `-v /D/Dev/Emscripten:/src`. 

Alternatively you specify an absolute path as input to emcc. e.g.: `emcc /D/Dev/Emscripten/helloworld.cpp`.

**Comment by samcov** [comment]
Holy Smokes, it WORKED!!!

I used: -v /D/Dev/Emscripten:/src, and no problems, it generated the .js & .wasm files perfectly.

Thanks a LOT!!!
