### ISSUE TITLE
Unknown option '--dyncalls-i64'

### ISSUE THREAD

**Issue by svenstaro** [emscripten-core/emscripten#12252]
Hey I'm using the most recent emscripten (2.0.4) together with the most recent version of binaryen (96). I get this error compiling a minimal C file:

```
emcc main.c 
shared:INFO: EM_IGNORE_SANITY set, ignoring sanity checks
Unknown option '--dyncalls-i64'
emcc: error: '/usr/bin/wasm-emscripten-finalize --detect-features --minimize-wasm-changes --dyncalls-i64 --global-base=1024 /tmp/emscripten_temp_q570gpoy/a.out.wasm -o /tmp/emscripten_temp_q570gpoy/a.out.wasm.o.wasm' failed (1)
```

**Comment by sbc100** [comment]
To ensure emscripten and binaryen work together you need to install the specific revision of binaryen that a given emscripten release depends on.

In the general case is not enough to have the most release (or closest) binaryen release installed.  Emscripten depends on tip-of-tree binaryen, not on a specific released version.  The same is true for our LLVM depedency (although I would love to change that: https://github.com/emscripten-core/emscripten/issues/11362).

This should all be documented in https://github.com/emscripten-core/emscripten/blob/master/docs/packaging.md

**Comment by sbc100** [comment]
In short, if you are packaging emscripten you need to bundle and internal version binaryen, not depend on the binaryen package, just like for the llvm (and previously fastcomp) dependency.    Its a sad state of affairs but its where we are today.

**Comment by svenstaro** [comment]
Optimally, you'd always release a new version of binaryen once its current version is too old for the given new emscripten release. Does that sound reasonable to you?

**Comment by sbc100** [comment]
In general its a good idea, but Im not sure how practical it is today since binaryen's wasm-emscripten-finalize is changing quite a bit and in ways that emscripten immediately depends on.  They are essentially evolving in tandem right now.

In order to do what you suggest we I think we would need to do something like this:

1. As we prepare for each emscripten release (which happens every week or two) we could speculatively tag a binaryen release.
2. Once the binaryen release is done we would change emscripten to depend on that specific version.
3. Now we do the the normal emscripten tagging process.
4. Hopefully the release is successful and doesn't require any binaryen changes otherwise we have to go back to (1) and repeat.

Given then the emscripten tagging process itself (3) is already fairly complex and involves changes in 3 different repositories (emscripten-releases, emsdk, and emscripten itself), I'm not sure it worth it add more complexity.

Perhaps one day when the dependency is less on wasm-emscripten-finalize and more just about wasm-opt could decouple?

Would it be particularly hard on your end to package an internal version binaryen with emscripten like we do in emsdk?  I know its inelegant to bundle a custom version of another package inside of another, but emscripten is a strange beast and we already require this for llvm.

**Comment by svenstaro** [comment]
I gave up and followed your suggestion: https://github.com/archlinux/svntogit-community/commit/c14caf2b19ad8a14836fb18b517aa3ac4e51d392#diff-8d0411b338c83cd8cd8ad9d9db127101

**Comment by sbc100** [comment]
Awesome!  Thanks @svaarala .. I do sympathize with your POV and will let you know if we can move to a less coupled model in the future.
