### ISSUE TITLE
Websocket server failed

### ISSUE THREAD

**Issue by VivianoRiccardo** [emscripten-core/emscripten#12432]
Hi,
I tried to implement the tests https://github.com/emscripten-core/emscripten/blob/master/tests/sockets/test_sockets_echo_server.c and https://github.com/emscripten-core/emscripten/blob/master/tests/sockets/test_sockets_echo_client.c with a lot of modifications making them multithreading and with sempahores. In C they both work using websockify as websocket bridge, even the client side works when compiled into wasm and run in the browser (while the server still runs in C using websockify as bridge). But when i try to implement the server side compiling it into wasm when i try to run it just says: "listen failed, not supported". Is there anyway to get around of this? thx in advance.

**Comment by jonassmedegaard** [comment]
[ I am not one of the emscripten developers (so if you get other conflicting suggestions then probably those are more relevant than mine ]

I guess this issue is easier for others to help resolve if you can share your failing code - or even better if you can isolate and describe a failing scenario using only emscripten code.

**Comment by VivianoRiccardo** [comment]
I just figured out that you can t open a websocket server, only a client one. You can open a websocket server only if you implement the things that WebRtc uses. But anyway i don t need it anymore. I wanted to implement a peer to peer system but i got around of this just creating a peer to proxy communiciation system.
