### ISSUE TITLE
Imply MODULARIZE when EXPORT_ES6 is set

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#12525]
Currently trying to use `-s EXPORT_ES6=1` fails with an error:

> emcc: error: EXPORT_ES6 requires MODULARIZE to be set

It seems like, instead of throwing an error, a better development experience could be auto-implying `MODULARIZE` too (since `EXPORT_ES6` is already unambiguously requires the output to be a module).

**Comment by tigercosmos** [comment]
@RReverser  I would like to take this issue. Could you kindly give me some hints to finish this one?

**Comment by RReverser** [comment]
@tigercosmos Sorry, it's already taken - see the in-progress PR above.

**Comment by dcodeIO** [comment]
As it [turns out](https://github.com/WebAssembly/binaryen/pull/3304), implying `MODULARIZE` with `EXPORT_ES6` is mixing two different concepts. In Emscripten, `MODULARIZE` evolved over time and doesn't necessarily imply that something is a (JS) module, but that something can be instantiated multiple times purely in user code, which is not identical to ESM. The PR linked above tries to build an ES module for example, but has no need for instantiating a module multiple times. Not sure how to tackle this ideally, but as it seems to result in quite a bit of confusion I thought I mention. Binaryen.js for example really just wants to legalize ESM syntax, but has no need for MODULARIZE because that does something, well, different.

**Comment by RReverser** [comment]
Oh, looks like we didn't close this issue when PR was merged.

@dcodeIO I still don't fully understand the use-case, but let's open a separate issue for that discussion, since `EXPORT_ES6` was something that was always working only with `MODULARIZE`, and whatever we end up doing, it's likely to be a new option or mode.
