### ISSUE TITLE
Why does the WASM binary file contain paths of the included header files?

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#12541]
While inspecting the generated `.wasm ` file I noticed that it contains paths of the included header file along with my computer username. 

I build with -Oz and didn't include any debug related flags while compiling. 

Closely related to https://stackoverflow.com/questions/30139852/why-does-the-executable-binary-file-contain-paths-of-included-header-files

**Comment by kripken** [comment]
Clang may do this if you use things like `__FILE__`, which various projects use in their logging code, for example (to log the line from where it is printing). Looks like that's similar to the `wxAssert` mentioned in that link - your project may have something similar in its source code.

(There is no way for emscripten to be aware of this or strip them out - it has to be fixed in your source.)

**Comment by gerald-dotcom** [comment]
You're right. The issue caused by dependency. 

-DNDEBUG=1 fixed the problem.
