### ISSUE TITLE
dynamic linking: Weak undefined functions are not handled correctly

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#12819]
When building a dynamic module it seems like there are two possible way to handle weak undefined symbols:

1. Treat the symbol like and undefined symbol in a static binary (resolve its address to zero).
2. Treat it like a dynamic import and let the dynamic linker decide if it exists.

Right now we try to do (1) but it seems there is bug in wasm-ld were function addresses of undefined weak symbols are not correctly resolved to zero.

Ideally I think we should switch to (2) and let the dynamic linker make the decision,  but that would require some kind of annotation on the import.   For example importing `foo@weak` rather than just `foo`.

**Comment by sbc100** [comment]
See emscripten's test_extern_weak for an example of how this is currently broken:

```
extern int __attribute__((weak)) externWeak();                                      
                                                                                                          
int main() {                                                                     
#ifdef LINKABLE                                                                  
  printf("in linkable code, we don't handle this properly quite yet - we create a function pointer, but do not have a way to change that at runtime\n");
  assert(externWeak != nullptr);                                                 
#else                                                                            
  printf("all linking is done, we should have set to null this thing that was not linked in\n");
  assert(externWeak == nullptr);                                                 
#endif                                                                           
  printf("ok.\n");                                                               
}  
```

**Comment by Faless** [comment]
I am not sure if this is the root cause of the issue we have been experiencing with Godot using newer emcc.
We use a Zstandard library which define weak symbols (https://github.com/facebook/zstd/blob/ea763f33cb706d7febf2f0e39f0c6811e9333ba1/lib/common/zstd_trace.h#L28) .
Our version is slightly behind the latest released (doesn't have the `__ELF__` define so that might fix it upstream by excluding wasm builds I think), but it did work with previous emscripten version so I thought it was worth reporting.
What happens with newer emscripten is that it cannot find functions with the weak attribute at runtime (note that all the code is compiled as a side module, with a very simple main module that acts as an initializer)
