### ISSUE TITLE
"Fatal: Module::addGlobal: __stack_base already exists" when linking with ASSERTIONS=2

### ISSUE THREAD

**Issue by DDoS** [emscripten-core/emscripten#12834]
Using the "tot" release, a linkage fails with "Fatal: Module::addGlobal: __stack_base already exists".

The command line looks like:
`em++.bat -g -s SAFE_HEAP=1 -s ASSERTIONS=2 --bind Redacted.cpp.o -o Redacted.js libRedacted.a libktx.a`

Switching to ASSERTIONS=1 fixes the problem.

**Comment by donalffons** [comment]
I'm experiencing the same issue here with the `2.0.10` Docker image. My full command is
```
emcc
--bind bindingsfile.cpp
-frtti
-fPIC
-s ENVIRONMENT='web'
-s EXPORT_ES6=1
-s USE_ES6_IMPORT_META=0
-s MAIN_MODULE=1
-s ALLOW_MEMORY_GROWTH=1
-s AGGRESSIVE_VARIABLE_ELIMINATION=1
-s ASSERTIONS=2
-o output.js
```

The error message goes away if I set `ASSERTIONS` to 1 instead of 2.

**Comment by sbc100** [comment]
I believe there is a binaryen fix on the way for this issue: https://github.com/WebAssembly/binaryen/pull/3390

I'm not sure why its not landed yet or why other folks haven't been running into this.

**Comment by kripken** [comment]
I think we need a testcase for this. My PR works around the issue, but people rightfully pointed out that we shouldn't just do that. We need to understand how it's possible to end up with this error.

**Comment by kripken** [comment]
Building a hello world with the above flags doesn't show the issue. @donalffons @DDoS perhaps you can provide a tescase?

**Comment by sbc100** [comment]
So on the emscripten side we have `__stack_base` defined as a static global in `system/lib/compiler-rt/stack_limits.S`.    

Since this is static it should never be imported or exported or conflict with any other names.   I imagine the problem will occur of you `__stack_base` ends up in the name section...     it sounds like binaryen is taking the name from the name which then prevents this code from creating another global with this name.   @kripken  Did you try building with `-g`?

**Comment by kripken** [comment]
Right, thanks @sbc100 , that's indeed the issue! I pushed a fix to https://github.com/WebAssembly/binaryen/pull/3390, PTAL
