### ISSUE TITLE
What does  BINARYEN_METHOD=native-wasm flag do?

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#12870]
I found this flag used by many open source repo and wonder what it does compared to WASM=1

**Comment by kripken** [comment]
That is an old flag, that no longer does anything. It used to say "emit actual wasm" back when there were no VMs that could run it, and we mostly tested by running in interpreters and stuff like that.

A project still using the flag can remove it if it upgrades to a more recent emscripten versions. `WASM=1` is now the default so that isn't necessary either.
