### ISSUE TITLE
What is the GOT?

### ISSUE THREAD

**Issue by SoniEx2** [emscripten-core/emscripten#13039]
Is there anywhere where the emscripten ABI is documented?

**Comment by sbc100** [comment]
If you see imports from `GOT.mem` and `GOT.func` those relate to dynamic linking: https://github.com/WebAssembly/tool-conventions/blob/master/DynamicLinking.md.

The term comes from ELF's concept of "Global Offset Table".

We don't currently document the JS/wasm ABI used by emscripten.  We also don't currently report changes to this ABI in he changelog or consider changes to this layer to be breaking changes since they are mostly and internal contract between JS and wesm, both generated by emscripten.

We do have the `STANDALONE_WASM` option where we do try use public APIs such as WASI where possible, but if you use more advanced emscripten features the resulting wasm file will end up containing emscripten internal APIs too.  There is some (perhaps outdated) documentation on that here: https://github.com/emscripten-core/emscripten/wiki/WebAssembly-Standalone.

But as I warn most folks who try to consume emscripten-generated wasm without using emscripten-generated JS, you may be exposed to undocumented/unstable ABIs.   In particular, trying to make a generic loader that loads wasm files from multiple versions of emscripten would be a hard task today, because some part of the ABI will almost certainly change with each release.

**Comment by sbc100** [comment]
Having said that if you sick to `STANDALONE_WASM` and avoid web APIs it should be possible.

We are working to improve in this area.  For example, I'm looking at adding a PURE_WASI option to allow more standard binaries to be both produced and consumed by emscripten: https://github.com/emscripten-core/emscripten/pull/12704

**Comment by SoniEx2** [comment]
Does PURE_WASI support runtime-adjustable stack/heap/memory layout?

**Comment by sbc100** [comment]
The RELOCATABLE option should still work with PURE_WASI yes.  On its own WASI doesn't not support imported memories or flexible memory layouts, so if you use `RELOCATABLE` you won't get a module is actually pure WASI.   

The meaning of PURE_WASI is more like "use WASI where ever possible, even when its less efficient" .. but it doesn't preclude the use of non-wasi stuff such as web APIs or imported memory.
