### ISSUE TITLE
dynamic linking + ASSERTIONS=2: assertion on "function in Table but not functionsInTableMap"

### ISSUE THREAD

**Issue by donalffons** [emscripten-core/emscripten#13040]
This is in response to @kripken's request for a test case in #12834. I haven't yet managed to reproduce the error mentioned in this issue, but I came across another one.

```
Uncaught (in promise) RuntimeError: abort(Assertion failed: function in Table but not functionsInTableMap) at Error
    at jsStackTrace (https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:1806:19)
    at stackTrace (https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:2328:16)
    at abort (https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:1547:44)
    at assert (https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:717:5)
    at addFunctionWasm (https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:571:5)
    at updateGOT (https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:1871:34)
    at relocateExports (https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:1896:7)
    at postInstantiation (https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:2089:27)
    at https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:2108:20
    at async Promise.all (index 0)
    at abort (https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:1553:11)
    at assert (https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:717:5)
    at addFunctionWasm (https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:571:5)
    at updateGOT (https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:1871:34)
    at relocateExports (https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:1896:7)
    at postInstantiation (https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:2089:27)
    at https://embind-dynamic-libs-01.vercel.app/emscripten/build/main.js:2108:20
    at async Promise.all (index 0)
```

Repo with test case: https://github.com/donalffons/embind-dynamicLibs-01
Deployment of test case: https://embind-dynamic-libs-01.donalffons.vercel.app/javascript

The case is working with ASSERTIONS != 2.

If this is of any help for you, please let me know (in that case, I might add more cases). Cheers!

**Comment by kripken** [comment]
Thanks @donalffons !

It seems like the issue is that the assertion there checks that our map of functions to the table is up to date:

https://github.com/emscripten-core/emscripten/blob/de12acd3becf7b0b3aec02316456d44bc205ad2c/src/runtime_functions.js#L137-L144

It expects not to see something in the table that isn't in our map. But when we load the library, it adds functions to the table directly - not through `addFunction` which is where that assertion is - so we need to refresh the map. This should do that:
```diff
diff --git a/src/library_dylink.js b/src/library_dylink.js
index 583e3fe77..ed21e58f8 100644
--- a/src/library_dylink.js
+++ b/src/library_dylink.js
@@ -415,7 +415,13 @@ var LibraryDylink = {
         for (var i = 0; i < tableSize; i++) {
           assert(table.get(tableBase + i) !== undefined, 'table entry was not filled in');
         }
-#endif
+#if ASSERTIONS >= 2
+        // The table has new entries now, so force functionsInTableMap to be
+        // re-created on next use.
+        functionsInTableMap = null;
+#endif // ASSERTIONS >= 2
+#endif // ASSERTIONS
+
         moduleExports = relocateExports(instance.exports, memoryBase);
         if (!flags.allowUndefined) {
           reportUndefinedSymbols();
```
However, with that it still doesn't fully work. The console is full of warnings like this:
```
main.js:2248 warning: symbol '__wasm_apply_relocs' from '/emscripten/build/library.wasm' already exists (duplicate symbol? or weak linking, which isn't supported yet?)
main.js:2248 warning: symbol '_ZNSt3__211char_traitsIcE6lengthEPKc' from '/emscripten/build/library.wasm' already exists (duplicate symbol? or weak linking, which isn't supported yet?)
```
So something seems to have gone wrong here. And it then crashes on a stack overflow.

That the example here is basically a "hello world" of dynamic linking + embind suggests to me that that combination may not be tested, and not work. @sbc100 you know more about dynamic linking - thoughts?

**Comment by kripken** [comment]
Actually, I see that this may be due to `ASSERTIONS=2`. Our test suite seems to disable all dynamic linking + `ASSERTIONS=2` tests, so that code isn't being checked, and it looks like aside from the failed assertion it also causes those warnings and stack overflow - adding `ASSERTIONS=2` to say `test_dylink_global_inits` causes the same.

So the problem here seems to be dynamic linking + `ASSERTIONS=2`. @sbc100 should we maybe disallow that combo for now?

**Comment by sbc100** [comment]
Why would want to disallow it?    Is there some logical reason why those two couldn't be used together, or are you just talking about buying us time to fix it?   I think we should at least try and fix first.

**Comment by kripken** [comment]
I'm not opposed to fixing it, of course - I was just wondering if you knew if there was a reason why all the current dylink tests avoid that flag. That seems like it might be intentional? But maybe it's an oversight.

**Comment by sbc100** [comment]
I don't think that was intentional.

**Comment by kripken** [comment]
Sounds good, thanks @sbc100 

@donalffons for now, you can just change `ASSERTIONS=2` to 1 as a workaround.

**Comment by donalffons** [comment]
Thanks a ton for looking into this. Setting `ASSERTIONS` to something != 2 works fine for this simplified example. However, the *actual* problem I'm having are randomly occurring errors during instantiation (with an optimized release build an `ASSERTIONS=0`) and my hope was that maybe using a higher `ASSERTIONS` level might help in tracking down the underlying problem. Since these errors are happening in a large project and cannot be reproduced deterministically, I have been struggling with identifying the root cause.

However, I have been working on bisecting the problem and I think I will have a better "test case" that is closer to the actual issue, soon. Will open another issue, as soon as I have that identified.

I appreciate your great work on this project!

**Comment by jprendes** [comment]
As @donalffons pointed out in #13347, I think #13347 and this are the same issue.

> However, with that it still doesn't fully work. The console is full of warnings like this:
> 
> ```
> main.js:2248 warning: symbol '__wasm_apply_relocs' from '/emscripten/build/library.wasm' already exists (duplicate symbol? or weak linking, which isn't supported yet?)
> main.js:2248 warning: symbol '_ZNSt3__211char_traitsIcE6lengthEPKc' from '/emscripten/build/library.wasm' already exists (duplicate symbol? or weak linking, which isn't supported yet?)
> ```

As to those warnings, I would say they are expected. From what I've seen, it looks like all the duplicated symbols are either module setup code (like `__wasm_apply_relocs`), or C++ template instantiations (like `_ZNSt3__211char_traitsIcE6lengthEPKc`, which demangles to `std::__2::char_traits<char>::length(char const*)`).

I would expect to see `__wasm_apply_relocs` in most modules, and to see `std::__2::char_traits<char>::length(char const*)` in every module that instantiates that template. I don't think those warning mean that anything has gone wrong.

In this example, the warnings are easily resolved by compiling with `-s SIDE_MODULE=2` since the side module doesn't really need to export those symbols. I think there might be a case for adding more symbols like `__wasm_apply_relocs` to `isInternalSym`?

**Comment by sbc100** [comment]
> As @donalffons pointed out in #13347, I think #13347 and this are the same issue.
> 
> > However, with that it still doesn't fully work. The console is full of warnings like this:
> > ```
> > main.js:2248 warning: symbol '__wasm_apply_relocs' from '/emscripten/build/library.wasm' already exists (duplicate symbol? or weak linking, which isn't supported yet?)
> > main.js:2248 warning: symbol '_ZNSt3__211char_traitsIcE6lengthEPKc' from '/emscripten/build/library.wasm' already exists (duplicate symbol? or weak linking, which isn't supported yet?)
> > ```
> 
> As to those warnings, I would say they are expected. From what I've seen, it looks like all the duplicated symbols are either module setup code (like `__wasm_apply_relocs`), or C++ template instantiations (like `_ZNSt3__211char_traitsIcE6lengthEPKc`, which demangles to `std::__2::char_traits<char>::length(char const*)`).
> 
> I would expect to see `__wasm_apply_relocs` in most modules, and to see `std::__2::char_traits<char>::length(char const*)` in every module that instantiates that template. I don't think those warning mean that anything has gone wrong.
> 
> In this example, the warnings are easily resolved by compiling with `-s SIDE_MODULE=2` since the side module doesn't really need to export those symbols. I think there might be a case for adding more symbols like `__wasm_apply_relocs` to `isInternalSym`?

Sadly we don't support weak exports yet so you will warning for duplicate C++ methods that are compiled as COMDAT (weak groups of symbols.

Regarding `__wasm_apply_relocs`.    That symbol was renames in upstream llvm and is now called `__wasm_apply_data_relocs`.  It is already part of `isInternalSym`.   I'm surprised that you are seeing a warning about that symbol.   Could it be that you are using a mismatched version of llvm?  Are you using emsdk?   Which version?

**Comment by jprendes** [comment]
> Sadly we don't support weak exports yet so you will warning for duplicate C++ methods that are compiled as COMDAT (weak groups of symbols.

That's why I wouldn't consider those warning as an indication of anything wrong, or a blocker for a fix to the "function in Table but not functionsInTableMap" problem.

> Regarding __wasm_apply_relocs. That symbol was renames in upstream llvm and is now called __wasm_apply_data_relocs. It is already part of isInternalSym. I'm surprised that you are seeing a warning about that symbol. Could it be that you are using a mismatched version of llvm? Are you using emsdk? Which version?

My bad, I don't actually see `__wasm_apply_relocs`, I based my comment on @kripken's previous comment.
The one I do see is `__clang_call_terminate`. I've also seen `__tls_size`, `__tls_align` and `__wasm_init_tls`, but I guess those only apply for pthread support.
