### ISSUE TITLE
Can we give a better warning when loading wasm file:// URL

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#13207]
It seems to come up fairly often that new users try to load via `file://`.    We have an FAQ entry: https://emscripten.org/docs/getting_started/FAQ.html#faq-local-webserver, but maybe we should add a UI-visible error in our default html so its even more clear?

**Comment by vadimkantorov** [comment]
What may also be interesting: some notice in docs on how to embed javascript + wasm + data in a single giant HTML (if needed), then it probably would work even from file:///

**Comment by sbc100** [comment]
Ah yes I forgot we have the SINGLE_FILE settings for doing that.  

The SINGLE_FILE setting is document at  https://emscripten.org/docs/compiling/Building-Projects.html#emscripten-linker-output-files,

I'm not sure its a good idea to recommend that method as way to avoid running a server though.    Better to recommend running a local server, no?

**Comment by vadimkantorov** [comment]
I guess, in general it's better to recommend running a local server, but e.g. a multi-threaded server is required when streaming compilation is happening or several modules are requested, otherwise a deadlock sometimes in the serving code (also probably worth a mention). This is only possible in python3.8: https://github.com/busytex/busyide/blob/main/serve.py. Maybe best to include such a debugging server in Emscripten?

The single-file scenario is good for distributing an app: just download and launch a self-contained HTML is a good option to have and know about

**Comment by kripken** [comment]
Thanks @vadimkantorov , I think adding docs for SINGLE_FILE there makes sense. I opened https://github.com/emscripten-core/emscripten/pull/13232 now.

**Comment by vadimkantorov** [comment]
Also, python's http.server is not enough. You need sth to return correct MIME codes + it'd better to be multi-threaded. Otherwise browser can sometimes deadlock and wait for the server forever - happened to me in practice (related to serving a few large WASM modules + data files simultaneously, don't remember the exact setup), I had to swith to threaded python server

**Comment by sbc100** [comment]
I would have hoped the python 3 server had the wasm mine times by now.. :(

Yes we should drop python 3 mention probably, since emscripten itself no longer supports it.

**Comment by vadimkantorov** [comment]
@sbc100 btw created a feature request in CPython to update their default extensions_map for MIME:
- https://github.com/python/cpython/issues/106900

Please upvote / chime in or maybe suggest other new useful MIMEs defaults for WASM world
