### ISSUE TITLE
problem with dynamic linking in a super simple demo

### ISSUE THREAD

**Issue by g1204** [emscripten-core/emscripten#13226]
main_module.cpp:
`int bar(); // to be implemented in side module
`
`
EMSCRIPTEN_BINDINGS(test_dynlink) {
    function("bar", &bar);
}
`

compile with emscripten 2.0.12:
`emcc --bind main_module.cpp -o main_module.js -s NO_EXIT_RUNTIME=0 -s MAIN_MODULE=1`

when I run it with:
`node main_module.js`

output this error:
Assertion failed: undefined symbol `_Z3barv`. perhaps a side module was not linked in? if this global was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment

**In further check the demo works in 2.0.8 and fails since 2.0.9.**

**Comment by sbc100** [comment]
How are you linking in the side module?

I can make the above example work if I add `-s RUNTIME_LINKED_LIBS=[libside.wasm]` to the command line and build the `libside.wasm` side module first.   Are you saying this somehow worked without `RUNTIME_LINKED_LIBS` in 2.0.4?

**Comment by g1204** [comment]
> How are you linking in the side module?
> 
> I can make the above example work if I add `-s RUNTIME_LINKED_LIBS=[libside.wasm]` to the command line and build the `libside.wasm` side module first. Are you saying this somehow worked without `RUNTIME_LINKED_LIBS` in 2.0.4?

Yes, in 2.0.4 It worked without RUNTIME_LINKED_LIBS, so as I can delay loading side module(by calling loadDynamicLibrary) to right before calling bar() method.
RUNTIME_LINKED_LIBS seems will load side modules at startup, that is not what I desire.

**Comment by sbc100** [comment]
Oh I see..  so we must have changed default policy for symbol resolution from `BIND_LAZY` to `BIND_NOW`.   If that is the case we should have documented that change.   We can revisit if needed.

Is this an important use case for you?   i.e. do you need to be able to start main before the side module is loaded at all?   Would it make sense to use `dlopen` + `dlsym` in this use case?

**Comment by g1204** [comment]
Unfortunately this is important for us. Delay loading is why we switch to dynamic linking. It's convenient and transparent for c++ developers in that they don't have to care about how symbols shared between main/side module. 
In more complicated cases it's impossible to use `dlopen` + `dlsym` way. It may work for this super simple demo though.

**Comment by sbc100** [comment]
In your application how to ensure that the code doesn't make any calls to missing functions before the code is loaded?   Presumably if this happened the application would crash right away right?    i.e. how to you avoid the race between the loading of the code and using of the code?

**Comment by g1204** [comment]
Normally it's easy for us to deside whether need to load side module first. Either by class name or method name with a specific postfix. 

e.g. main module is like:
```cpp
struct B
{
    void bar() const; // to be implemented in side module
};

struct A
{
    void foo(){};
    void call_b(const B &b)
    {
        b.bar();
    }
};

EMSCRIPTEN_BINDINGS(test_dynlink)
{
    class_<A>("A")
        .constructor<>()
        .function("foo", &A::foo)
        .function("call_b", &A::call_b);

    class_<B>("B")
        .constructor<>()
        .function("bar", &B::bar);
}
```
No need to load side module, we could write `let a = new instance.A;` and `a.foo();`
And then before we use B class, e.g. `new instance.B` or `a.call_b()`, we need to load side module first.

This is a simple demo, in reality B could be a feature name and contains lots of classes.

**Comment by sbc100** [comment]
So you have explicit checkpoint if you code?   e.g.

```
void DoSomething() {
     DoWork();
     // We know we need the side module at this point. 
     LoadTheSideModule(MoreWork);
}
```

In this case calling the MoreWork function (that needs the side module) before loading the side module would crash?

Its kind of like using dlopen, but all the symbol get hooked up for you.   And its a little dangerous since at any given time in your program you can't be sure that all functions are callable.   Is that about right?   do you think his is useful/reasonable approach that we should make an effort of officially support?

**Comment by g1204** [comment]
Yes, it's like the before-2.0.8 way. A little dangerous but acceptable, as we know the explicit checkpoint.

**Comment by sbc100** [comment]
After looking at a solution to this for while now I have concluded that, sadly, the new PIC API makes it hard/impossible to go back to how things were where functions could be resolved lazily.   The reason is that we have lost the signature information associated with function address imports.   If you have a module that imports the address of `foo` we can't know what the signature is, and therefore we can't create a suitable placeholder function for it in the table for `foo`.

This is the same reason why we now require the `__sig` attributes for JS functions that are address taken. 

This is fairly serious limitation, although as far as I know @g1204 is the only user that was relying on this features.

**Comment by g1204** [comment]
thx, it's a little clearer to me now. I tested it with following code. inside bar(), the first statement is ok while the other two will trigger an error of undefined symbol, is it because they try to use address of foo?

```cpp
void foo(); // to be implemented in side module 
void invoke(void(*func)()) { (*func)(); }

void bar()
{
    foo(); // ok
    // auto p = foo; // Assertion failed: undefined symbol `_Z3foov`.
    // invoke(foo); // Assertion failed: undefined symbol `_Z3foov`.
}

EMSCRIPTEN_BINDINGS(test_dynlink) { function("bar", &bar); }
```

If I edit main module .js such that don't abort when meet undefined symbol, even last two statements now runs ok. (sounds like a false alarm?)

**Comment by sbc100** [comment]
Yes, its taking the address of `foo()` that will trigger the undefined symbol.

The main problem is that when the program first loads we want to put a placeholder functions in the location in the table where `foo` will eventually live.     Because we don't know the signature of foo we can't construct a suitable stub function.   Perhaps it could work if we just leave the table slot empty .. this means that program will just crash if it calls foo() to early.  Perhaps this is OK for some use cases.

**Comment by g1204** [comment]
sounds great! So if i load side module later, the empty slot of `foo` will be filled, until which it's safe to call foo().
