### ISSUE TITLE
Minimum in HTML to run emscripten generated file.js

### ISSUE THREAD

**Issue by capiman** [emscripten-core/emscripten#1326]
I know i can compile via

python emcc test.cpp -o test.html

But know i want to use the generated Javascript code in an existing webpage
or page with own layout.

Therefore i compile it like the following:

python emcc test.cpp -o test.js

and want to include the test.js manually into a webpage.

What is the minimum needed in a HTML file 
to call and run an emscripten generated JavaScript program?

The program needs only printf to a textarea in main and
emscripten API calls like emscripten_set_main_loop,
emscripten_async_wget2, ... no "graphical" output.

Something like:

text is not displayed by github, rework in second windows...

**Comment by matthewwiese** [comment]
Due to the happenstance of Google's SEO, this issue comes up when searching for simple templates to use with the generated JavaScript file in HTML without the additional scaffolding that doing `-o test.html` directly with `emcc` provides.

Below is the most basic HTML I was able to get working with Emscripten:

```
<html>
	<body>
		<p id="output" />
		<script>
			var Module = {
				print: (function() {
					var element = document.getElementById('output');
					return function(text) {
						element.innerHTML += text + "<br>";
					};
				})(),
				printErr: function(text) {
						if (arguments.length > 1) text = Array.prototype.slice.call(arguments).join(' ');
						if (0) {
							dump(text + '\n');
						}
				},				
				canvas: (function() {
					var canvas = document.getElementById('canvas');
					return canvas;
				})()
			};
		</script>
		<script src="bare.js"></script>
	</body>
</html>
```

The code above appears in my [BASIC to C to WebAssembly](https://github.com/matthewwiese/basic-to-c-wasm-example) project repository. My included sample BASIC code brute forces the primes up to 1000 and "prints" them. This skeleton HTML provides the means to retrieve that output and redirect it to the page in the form of a `<p>` tag.
