### ISSUE TITLE
Add options to skip deps_info / llvm-nm phase

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#13409]
We use llvm-nm + deps_info.py to get a conservative list of reverse dependencies based on the input object and libraries.

For large projects this can add a fair amount to the link time (~3 seconds or 5-10%, for example, when building llvm).

Perhaps we should add an option (possibility enabled by default at lower opt levels) to be even more conservative and simply include all these symbols by default.   This would speed up link time at the cost of some code size.

**Comment by sbc100** [comment]
See https://bugs.chromium.org/p/chromium/issues/detail?id=1171844.

My understanding is that any extraneous symbols added during this phase should be removable by metadce which is a possible argument for doing this whenever metadce will run later?   This would seems to suggest doing it at both low and high optimization levels...

**Comment by kripken** [comment]
Metadce cannot remove any data, and it has limitations with indirect calls. But it should otherwise do what you expect. So we might want to check if any of those symbols bring in data or table elements.

But doing it all the time would mean `-O2` (not low, and not running metadce) would suffer. `-O2` is an optimized build but that doesn't run extra build stages like metadce, and it's a useful compromise I think, so I'm not sure it's worth changing.

I'd be in favor of including all potentially-needed symbols in -O0 and -O1, but not otherwise.

**Comment by pfaffe** [comment]
My vote is for -O0 and -O1 as well for pretty much identical reasons.

**Comment by kripken** [comment]
> Metadce cannot remove any data, and it has limitations with indirect calls. But it should otherwise do what you expect. So we might want to check if any of those symbols bring in data or table elements.

It turns out that indeed some of them do. Including malloc/free will bring in some data section changes (initialization of global data structures, I believe) that are non-zero and so they end up increasing size even if malloc/free are removed later.

**Comment by sbc100** [comment]
I added up adding a new option that allows for all 3 mode:  'auto' (current state and default), 'none' (must export everything manually) and 'all' (conservatively include everything).   We can consider changing the default to 'all' in -O0/O1 as a followup.

I'm also working a set of changes to cleanup and verify all entries in `deps_info.py`
