### ISSUE TITLE
Is EM_IGNORE_SANITY redundant?

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#13459]
We have both EM_IGNORE_SANITY and EMCC_SKIP_SANITY_CHECK environment variables that do about the same thing. EMCC_SKIP_SANITY_CHECK is more comprehensive, looks like EM_IGNORE_SANITY gates out less stuff.

With Emsdk having sanity checks enabled is kind of pointless, it slows down the build with little benefit, as emsdk guarantees that the configuration is proper-ish so defensive sanity checks don't need to be run. I could have sworn that Emsdk set EMCC_SKIP_SANITY_CHECK=1 by default, but now when I check, it does not.At Unity we deploy with EMCC_SKIP_SANITY_CHECK=1 to get a noticeable perf improvement. (and avoid the Java nag dialog on macOS)

**Comment by sbc100** [comment]
I've wondered this myself too.   I think my conclusion was that they server different purposes... but I forget how.

EM_IGNORE_SANITY is designed to ignore failures in the sanity checks.   This is for folks who want to run emcc with unsupported versions of various tools..  it still shows warnings but it won't fail.

EMCC_SKIP_SANITY_CHECK is designed to signal that you already ran that sanity checks.   emcc sets this internally to avoid running sanity checks recursivly.

I wouldn't want to have emsdk skip running the sanity checks since there are installation issues that it can help to diagnose.   Remember we have the sanity timestamp which should mean the expensive checks only run once and then never again unless you change the configuration.

**Comment by sbc100** [comment]
I would not oppose it if you wanted to propose removing one of these... I'm always in favor of removing options and settings :)

**Comment by juj** [comment]
Thanks, now in the morning with a pair of fresh eyes I understand, EM_IGNORE_SANITY still runs the checks, but just ignores the results, whereas EMCC_SKIP_SANITY_CHECK does not even run.

We do have the sanity timestamp, though the last time I benchmarked build times on a large project, EMCC_SKIP_SANITY_CHECK was a several second improvement, so maybe it adds up. (That was a while ago, not sure if the sanity mechanism has improved since.. I'll try to benchmark again at some point)
