### ISSUE TITLE
wasm-ld, not understanding LDFLAGS?

### ISSUE THREAD

**Issue by LocutusOfBorg** [emscripten-core/emscripten#13479]
Hello, in Ubuntu we inject LDFLAGS during build process, and in particular this flag:
```
	# Per https://wiki.ubuntu.com/DistCompilerFlags
        $flags->prepend('LDFLAGS', '-Wl,-Bsymbolic-functions');
```

This causes wasm-ld to fail to build because of flag not understood, e.g. olm is failing for this reason:
               -o javascript/olm.js build/javascript/src/account.o build/javascript/src/base64.o build/javascript/src/cipher.o build/javascript/src/crypto.o build/javascript/src/memory.o build/javascript/src/message.o build/javascript/src/olm.o build/javascript/src/pickle.o build/javascript/src/pk.o build/javascript/src/ratchet.o build/javascript/src/session.o build/javascript/src/utility.o build/javascript/src/ed25519.o build/javascript/src/error.o build/javascript/src/inbound_group_session.o build/javascript/src/megolm.o build/javascript/src/outbound_group_session.o build/javascript/src/pickle_encoding.o build/javascript/src/sas.o build/javascript/lib/crypto-algorithms/sha256.o build/javascript/lib/crypto-algorithms/aes.o build/javascript/lib/curve25519-donna/curve25519-donna.o
EMCC_CLOSURE_ARGS="--externs javascript/externs.js" emcc -Wl,-Bsymbolic-functions -Wl,-z,relro -Wall -Werror -O3 --memory-init-file 0 -s NO_FILESYSTEM=1 -s INVOKE_RUN=0 -s MODULARIZE=1 \

wasm-ld: error: unknown argument: -Bsymbolic-functions
wasm-ld: error: unknown argument: -Bsymbolic-functions

Do you know how to best fix this issue?

thanks

Gianfranco

**Comment by tlively** [comment]
cc @sbc100

**Comment by sbc100** [comment]
Not all the linker flags that are supported by the ELF linker are supported by wasm-ld.   This is one such flag.
  
`-z,relro` is also not support although I think we ignore unsupported `-z` flags.    The best thing to do he is most likely to modify your build system not to pass these flags when building with emscripten.

**Comment by sbc100** [comment]
BTW what are you trying to do here?  Are are trying to somehow build ubuntu or some subset of it with emscripten?

**Comment by LocutusOfBorg** [comment]
I'm trying to make emscripten build in Ubuntu.
I achieved a full build and test after disabling test test_cmake_with_embind_cpp11_mode

but then, when I used emscripten to build olm, and the build failed in the very same way
https://launchpad.net/ubuntu/+source/olm/3.2.1~dfsg-7/+build/20928516

**Comment by sbc100** [comment]
When you say "trying to make emscripten build in Ubuntu" do you mean you are trying to build a version of emscripten that runs in Ubuntu?   I assume not, since there are already several ways to run emscripten *in* ubuntu (e.g. https://packages.ubuntu.com/xenial/emscripten, or just using emsdk should work fine).

It sounds like you maybe trying to build Ubuntu packages *with* emscripten?  If that is the case, then you will most likely need to make modifications to your build system, such as updating the link flags.   Its unlikely that much software in ubuntu will work unmodified.. for example building and running a shell (such as bash) will be not just work because emscipten doesn't support multiple processes (no fork or exec).

**Comment by LocutusOfBorg** [comment]
"https://packages.ubuntu.com/xenial/emscripten"
this one exists for xenial and bionic, and then was removed in the archive due to it not compiling correctly anymore.
and this is exactly the issue I'm reporting now here.
I tried to "fix the package" for the current Ubuntu development release to bring it back, but even if now I made it build by disabling the failing test, I can't use it to build olm (something in the archive that can't migrate in release pocket due to buggy emscripten)

I'm trying this patch
```diff
--- emscripten-2.0.12~dfsg.orig/emcc.py
+++ emscripten-2.0.12~dfsg/emcc.py
@@ -100,6 +100,8 @@ UNSUPPORTED_LLD_FLAGS = {
     '-rpath': True,
     '-rpath-link': True,
     '-version-script': True,
+    '-Bsymbolic-functions': True,
+    'relro': True,
 }

 LIB_PREFIXES = ('', 'lib')
```
I hope it works to make the package suitable for Ubuntu releases again, because otherwise it won't be in Ubuntu until somebody fixes it.

**Comment by sbc100** [comment]
I think if you want to build parts of ubuntu with emscripten you will need to do some porting, and removing those incompatible link flags seems like part of that work.   That could either be done by modifying your build scripts or by creating a wrapper around emcc that silently ignores those flags. 

I'm not sure it makes sense for emscripten to silently ignore those flags... but I guess its not completely out of the question since we do go out of our way to be compatible sometimes in other ways.

**Comment by LocutusOfBorg** [comment]
@junyuecao please try --error-limit=0. With llvm-15+ it has a double "-" at the begin.

**Comment by junyuecao** [comment]
@LocutusOfBorg  Thank you. 
Partially works. But I have to add this flag in emcc.py.  But  `emcc --error-limit=0 xxxx ` seems not supported.

**Comment by sbc100** [comment]
BTW, `--error-limit=0` and `-error-limit=0` are both valid in wasm-ld (and you do need the `-Wl,` prefix when passing ld flags via clang).
