### ISSUE TITLE
Browser.createContext doesn't always fallback to WebGL 1

### ISSUE THREAD

**Issue by JCash** [emscripten-core/emscripten#13501]
The [documentation](https://emscripten.org/docs/porting/multimedia_and_graphics/OpenGL-support.html?highlight=webgl%20fallback#webgl-friendly-subset-of-opengl-es-2-0-3-0) talks about a fallback to WebGL 1 if WebGL2 isn't supported.

The documentation also (correctly) mentions that the application can choose to fallback to WebGL 1 or not.

The fallback does work automatically if the browser doesn't support WebGL2 at all.
However, if the browser is new, but the graphics card/driver is old, you end up in a poor situation where the context creation returns null.
https://github.com/emscripten-core/emscripten/blob/master/src/library_browser.js#L326

Since there are a few libraries in emscripten where this function is called, I would propose a fix inside the function.

I think this issue is still important since not all people can afford to upgrade their hardware, and I anticipate this issue living on for a fairly long time.

## Repro
To repro, start (latest) Chrome.exe with `chrome.exe --disable.webgl2` (or `chrome.exe --use-angle=d3d9`)
Then you can go to https://www.webglreport.com and you'll see this message:
"This browser supports WebGL 2, but it is disabled or unavailable."

## A fix
The fix in (our copy of) `library_glfw.js`
```
    Module.ctx = Browser.createContext(Module['canvas'], true, true, contextAttributes);
    if (Module.ctx == null) {
      contextAttributes.majorVersion = 1; // Try WebGL 1
      Module.ctx = Browser.createContext(Module['canvas'], true, true, contextAttributes);
    }
```

**Comment by juj** [comment]
You are using GLFW? What does it say about context creation of GLES2 vs GLES3 contexts? If one attempts to create a GLES3 context via GLFW, and it is not available, will GLFW automatically attempt to create and return a GLES2 context instead?

If so, then the above fix to GLFW is likely appropriate. If not, then applications should manually try to first create a GLES3 context via GLFW, and then a GLES2 context if that fails.

**Comment by JCash** [comment]
I'm using (an old version of) the `library_glfw.js` found in Emscripten:
https://github.com/emscripten-core/emscripten/blob/master/src/library_glfw.js

Not sure who maintains that file, but since it's part of the Emscripten core, I thought I should post this issue, if nothing else for visibility/searchability.

Our version is old (2012 it looks like), but the `createWindow` of your current version looks the same.
Looking at the documentation for  the `src/library_glfw.js` refers to (https://www.glfw.org/docs/latest/) it doesn't mention anything about WebGL.

[Searching the code](https://github.com/emscripten-core/emscripten/search?q=Browser.createContext), it seems `library_glut.js` and `library_sdl.js` has the same behavior as `library_glfw.js`.

**Comment by juj** [comment]
The files library_egl.js, library_glemu.js, library_glew.js, library_glfw.js, library_glut.js, library_sdl.js and library_xlib.js are all kind of adrift in Emscripten without maintainer. They are from an old era of Emscripten, when it was starting out, and improving portability was a key problem. Now Emscripten is much more mature, and more libraries are cross-compilable directly (.e.g SDL 2), or developers have migrated to more "direct" APIs such as HTML5 WebGL API (library_html5.js, library_html5_webgl.js) for better codegen and multithreading and OffscreenCanvas support.

I used to maintain these files when I was still working at Mozilla, though that was now a bit more than three years ago, so basically these files are going without a maintainer since. I think Google stewarding Emscripten does tend to these files occassionally when bug reports come up, but there is no active development going into them (e.g. for adding multithreading support).

Emscripten has not wanted to delete these files, since there are probably a number of users, and for the purpose and features that they were built, they do still work.

> Looking at the documentation for the `src/library_glfw.js` refers to (https://www.glfw.org/docs/latest/) it doesn't mention anything about WebGL.

GLFW is an API to create GLES contexts. They certainly would not be mentioning WebGL there. The relevant documentation for how they handle GLES2 vs GLES3 should probably be documented here https://www.glfw.org/docs/latest/group__window.html#ga5c336fddf2cbb5b92f65f10fb6043344 , but did not find anything at least at a cursory glance.

**Comment by JCash** [comment]
I think what you say makes a lot of sense.
Perhaps it's even time to move these libraries to a different folder, so signify that they're not actively maintained or part of the emscripten-core anymore.

Anyways, I've mentioned the current caveats with the libraries, and mentioned a fix, so I think my main goal is achieved at least.
