### ISSUE TITLE
DWARF `.debug_line` section contains same file twice when using -gdwarf-5 and specifying an absolute path to the input

### ISSUE THREAD

**Issue by ktran** [emscripten-core/emscripten#13555]
The linking step seems not to correctly deduplicate files in the '.debug_line' section when using `-gdwarf-5` and specifying an absolute path. For this repro I'm using a `helloworld.c` file:

``` c
#include <stdio.h>

int main() {
  printf("Hello World!\n");
}
```

Try running:

```bash
$ emcc  -g -gdwarf-5 -O1  -o helloworld.o -c /absolute/path/to/helloworld.c
$ emcc  -O1 -g -o helloworld.js  -sWASM_BIGINT  -sERROR_ON_WASM_CHANGES_AFTER_LINK  helloworld.o
$ llvm-dwarfdump-11 -debug-line helloworld.wasm

file_names[  0]:
           name: "/absolute/path/to/helloworld.c"
      dir_index: 0
   md5_checksum: e267cff5498417b963e4afa45aee635f
file_names[  1]:
           name: "helloworld.c"
      dir_index: 0
   md5_checksum: e267cff5498417b963e4afa45aee635f

Address            Line   Column File   ISA Discriminator Flags
------------------ ------ ------ ------ --- ------------- -------------
0x0000000000000005      3      0      1   0             0  is_stmt
0x0000000000000006      4      3      1   0             0  is_stmt prologue_end
0x0000000000000015      5      1      1   0             0  is_stmt
0x0000000000000016      5      1      1   0             0  is_stmt end_sequence
```

`helloworld.c` is specified twice.

**Comment by kripken** [comment]
I assume this must be in LLVM since `WASM_BIGINT` is used at link, so binaryen is not run - cc @aardappel

**Comment by aardappel** [comment]
We probably don't support DWARF5 (yet), or at least it is untested. Why are you specifying it, and what happens if you just generate the default debug info instead?

@dschuff

**Comment by dschuff** [comment]
The devtools team is considering switching to DWARF5 in order to get some index and/or accelerator table sections that would improve debugger performance. The current state for DWARF5 is that it is bare-minimum/untested, but that's why they are testing it :)

I tried it out, and got the same behavior (and it's the compiler, not the linker, since the object file is the same). Clang for Linux also has the same behavior as clang for wasm. It's also interesting that all the entries point to the version with just the filename, and that the checksums are the same. My guess based on that would be that this is the intended behavior. Clearly the compiler knows that this is the same file and is encoding that information into the debug info. A consumer is able to find the file using either its bare filename or its absolute path.
Is this causing a particular problem?

**Comment by ktran** [comment]
Thanks for giving the context, Derek! So yes, as Derek mentioned we're considering to switch to DWARF5.

Currently we wouldn't be able to find line information if we were only to use the relative path for compilation, as in that case we only have one entry (at file index 0) and lldb currently doesn't search for files starting at index 0 [(lldb bug)](https://bugs.llvm.org/show_bug.cgi?id=49340). This is how we encountered the difference between specifying a relative path and an absolute path to begin with. 

However, it didn't cause a particular problem for us, but it seemed as if this list should be unique.

**Comment by ktran** [comment]
Closing this issue, since it seems to be expected behavior as Derek has pointed it out. Regarding the mentioned problem of us not being able to find the relevant file if there was only one file specified at index 0 (when using relative paths), this is [fixed now](https://bugs.llvm.org/show_bug.cgi?id=49340)
