### ISSUE TITLE
MAXIMUM_MEMORY at Module creation instead of compile time

### ISSUE THREAD

**Issue by niklasf** [emscripten-core/emscripten#13569]
I am looking to provide one (multi-threaded) module with multiple possible values for `MAXIMUM_MEMORY`.

Is there a reason why `-s MAXIMUM_MEMORY` is needed at compile time, or would it be realistic to set it dynamically at runtime?

**Comment by sbc100** [comment]
I think it would be reasonable to set this at runtime but you would also need to build with `-s IMPORTED_MEMORY` so that the memory is defined dynamically in JS rather than statically in the WebAssembly module.

We would need to modify `src/runtime_init_memory.js` to handle 
MAXIMUM_MEMORY in the same way we handle INITIAL_MEMORY (i.e. make it a JS variable rather than a hardcoded constant).   So it would need patch.   Do you fancy working it?  It should be fairly straight forward.

**Comment by sbc100** [comment]
We might need to also make sure the wasm module it self doesn't set an upper limit

**Comment by niklasf** [comment]
Thanks for the pointers. If I understand the code correctly, I could get away with:

```javascript
// Module built with USE_PTHREADS, implying IMPORTED_MEMORY

const initial = ...; // same as INITIAL_MEMORY / page size
const maximum = ...; // less or equal to MAXIMUM_MEMORY / page size
Module({
  wasmMemory: new WebAssembly.Memory({initial, maximum, shared: true}),
});
```

So far, trying this does not fail in any obvious way. If it's really ok to do that, no patch might be required.

**Comment by sbc100** [comment]
Oh I see yes, if you are creating the memory outside of the generated JS you can do whatever you want.   I was thinking you wanted the JS to create the memory and honor `Module['MAXIMUM_MEMORY']` in the same way it honors `Module['INITIAL_MEMORY']` today.  But if you are handling memory creation yourself then you don't a patch... and I guess this issue can be closed?

**Comment by niklasf** [comment]
Awesome. Yeah, this is barely more effort than passing MAXIMUM_MEMORY on its own, so closing.
