### ISSUE TITLE
Microaggresions like whitelist/master/dummy/sanity/master

### ISSUE THREAD

**Issue by kungfooman** [emscripten-core/emscripten#13626]
WHITELIST

![image](https://user-images.githubusercontent.com/5236548/110446640-b218a300-80bf-11eb-8f99-c835a693e9ca.png)

BLACKLIST

![image](https://user-images.githubusercontent.com/5236548/110446806-de342400-80bf-11eb-8b93-bc1840e1dd1c.png)

DUMMY

![image](https://user-images.githubusercontent.com/5236548/110446945-03289700-80c0-11eb-89fe-88d0a98131a9.png)

SANITY

![image](https://user-images.githubusercontent.com/5236548/110447029-19ceee00-80c0-11eb-8260-b96c78c84e26.png)

MASTER

![image](https://user-images.githubusercontent.com/5236548/110447100-2e12eb00-80c0-11eb-8cb1-4e61d1f09783.png)

To become better at preventing subconscious microaggresions, I recommend this article: https://www.cnet.com/news/twitter-engineers-replace-racially-loaded-tech-terms-like-master-slave/

**Comment by sbc100** [comment]
Indeed, perhaps close this issue and open another on with reference to the current codebase?

**Comment by kungfooman** [comment]
@kripken I don't know how to make PR's for something like this, because basically it would break `emcc` command line arguments and `C` defines.

The documentation is also still referring to `master` everywhere.

Sorry for the screenshots from old code, this is from HEAD (just cloned):

BLACKLIST

![image](https://user-images.githubusercontent.com/5236548/110582629-c36bb900-816c-11eb-8e59-fb5e68070d4c.png)

WHITELIST

![image](https://user-images.githubusercontent.com/5236548/110582667-d088a800-816c-11eb-94da-5c0711a0f747.png)

SANITY

![image](https://user-images.githubusercontent.com/5236548/110582703-df6f5a80-816c-11eb-9aa6-3a3e30dc3fe7.png)

SLAVE

![image](https://user-images.githubusercontent.com/5236548/110582580-b353d980-816c-11eb-99d5-f0c2e1f1f622.png)

MASTER

![image](https://user-images.githubusercontent.com/5236548/110583048-5efd2980-816d-11eb-9a7a-92031623eff7.png)

**Comment by curiousdannii** [comment]
1. It's quite debateable whether many of these are microaggressions in the first place.
2. Any changes to upstream files need to be made upstream. (I think that includes all the slave references.)
3. The changelog is a record of history and it would be highly inappropriate to change what these settings etc were called in previous versions.
4. Your searches have even found the code to map from the old setting names to their new names, which obviously can't be removed.

Feel free to submit a PR to fix up the documentation. But honestly, this feels like concern trolling, especially coming from someone who's profile lists their organisation as "Hurr Durr".

**Comment by yowl** [comment]
Masters on ships rejoice at the their new pariah status.

**Comment by Akaricchi** [comment]
Are you fucking serious?

**Comment by kripken** [comment]
@Akaricchi Let's please keep things polite. People might disagree on what the best language is, or other details, but in general we should assume good intentions and be friendly to everyone here.

Note that if there are such specific disagreements on the offensiveness of terms, this probably isn't the right place for them. Emscripten is just one project in the entire ecosystem. We should follow general best practices. Otherwise the same debates on terminology will happen in each project again and again.

In any case generally the new terms are simply clearer and worth doing even without a theoretical debate. For example, I'm not a native speaker of English, and replacing "whitelist" with "allow" as in #13634 seems obviously better - when I was new in the field "allow" would have been easier for me to understand, and I'm sure it might help other people starting out now. So more PRs in this area are definitely welcome.

**Comment by Akaricchi** [comment]
> We should follow general best practices.

Who decided this kind of absurd language policing is "best practice" now? Since when? Show me **one** living person who is genuinely offended by the word "master" or "whitelist" and not just blindly parroting an out of touch "woke"-pandering corporation. I refuse to yield to and support this nonsense.

> Otherwise the same debates on terminology will happen in each project again and again.

The correct response to such 'debates' is to immediately close the issue and to refuse to change established terminology for no good reason. Not wasting everyone's time and potentially breaking people's workflows in a futile pursuit of nebulous "inclusivity". The global failure to do so is an embarrassment to the open source community at large, not a "best practice". 

> In any case generally the new terms are simply clearer and worth doing even without a theoretical debate. For example, I'm not a native speaker of English, and replacing "whitelist" with "allow" as in #13634 seems obviously better - when I was new in the field "allow" would have been easier for me to understand, and I'm sure it might help other people starting out now.

This is just a post hoc rationalization. The intention matters. I'm sorry, but it shouldn't take you more than 5 seconds to find out what "whitelist" means, regardless of how good you are at English. I'm saying this as a non-native speaker, too. If this is an actual barrier to entry for you (generic "you", not you specifically), then you're probably not equipped to meaningfully contribute to an open source project anyway.

And yes, I understand that you're not going to give two shits about my opinion on this issue. Nevertheless, I don't want to remain in the silent majority anymore. It pains me to see this newspeek development in open source communities. Hey, you could even say I'm "offended" and feel "excluded" by it.

**Comment by sbc100** [comment]
Closing this issue since I think we have addressed pretty much all of it.   If there are oversights feel free to open a new issue.

**Comment by kripken** [comment]
@Akaricchi 

It would be ok to debate which terms are clearer, but we'd need to do it in a friendly and respectful way, which your comment is not.

In addition, as I said, it's off topic to debate larger cultural issues here.
