### ISSUE TITLE
'emmalloc' allocation error: "memory access out of bounds"

### ISSUE THREAD

**Issue by DanielMehlber** [emscripten-core/emscripten#13727]
Hey everyone,
in the last couple of days I ran into an error I can't fix:

I've heard of this lightweight malloc implementation called 'emmalloc' which is a lighter alternative to 'dlmalloc', but unfortunately 'emmalloc' shows a behaviour I can't explain: the first allocation works perfectly fine, but any following allocations throw an error:
```
Uncaught RuntimeError: memory access out of bounds
        at SAFE_HEAP_LOAD_i32_4_4 (http://0.0.0.0:8000/output.wasm:wasm-function[32]:0xc6f)
        at attempt_allocate(Region*, unsigned long, unsigned long) (http://0.0.0.0:8000/output.wasm:wasm-function[10]:0x874)
        at emmalloc_memalign (http://0.0.0.0:8000/output.wasm:wasm-function[9]:0x6c2)
        at malloc (http://0.0.0.0:8000/output.wasm:wasm-function[11]:0xa11)
        at single_allocation (http://0.0.0.0:8000/output.wasm:wasm-function[4]:0x225)
        at <anonymous>:1:1
```
As you can see it traces the error down to the emmalloc implementation in 'emmalloc.cpp'
This error doesn't occur when I'm using 'dlmalloc'.
I've narrowed down the problem to the following source code, so this is a very plain and simple version causing the error above:

```c
#include "emscripten.h"
#include "malloc.h"

EMSCRIPTEN_KEEPALIVE
void* single_allocation() {
    return malloc(8); 
}

EMSCRIPTEN_KEEPALIVE
void error_here() {
    // first allocation works just fine (size irrelevant)
    single_allocation();
    // every allocation after the first one doesn't due to 'segmentation fault', but only when using emmalloc
    single_allocation();
}
```

its compiled using
```
emcc program.c -o output.wasm -g --no-entry -s MALLOC="emmalloc" -s ASSERTIONS=1 -s SAFE_HEAP=1 -s STANDALONE_WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s BINARYEN_ASYNC_COMPILATION=0
```
and loaded using

```javascript
importObject = {
    'env':{
        'emscripten_notify_memory_growth': alert, // because heap is growable
        'segfault': function () {alert('Segmentation fault occured')}, // because of ASSERTIONS=1 and SAFE_HEAP=1
        'alignfault': function() {alert('Alignment fault occured')}, // because of ASSERIONS=1 and SAFE_HEAP=1
    }
};

WebAssembly.instantiateStreaming(
    fetch('./output.wasm'),
    importObject
).then(result => {
    // module exports its memory because it's standalone
    memory = result.instance.exports.memory;

    // load exported functions
    single_allocation = result.instance.exports.single_allocation;
    // calls single_allocation twice => error
    error_here = result.instance.exports.error_here;

    // causes error
    error_here();
});
```

I reproduced this error on Chrome and Firefox, so I don't think it's a browser bug.

All of those (including compilation scripts for Linux and Windows, a summary and html to load into web-browser for easy reproduction) are here:
[emmalloc_error_reproduce.zip](https://github.com/emscripten-core/emscripten/files/6175535/emmalloc_error_reproduce.zip)

I don't know if I'm doing something wrong or if there's a bug in the emmalloc.cpp implementation.

Thanks in advance :)

**Comment by juj** [comment]
The issue here follows from attempting to load up the program by replacing the Emscripten-provided loader. The loader in the test case omits the needed global ctor loading, which is the cause of the crash. The problem is not with emmalloc.

@azakai I am not familiar with the latest on `-s STANDALONE_WASM=1` mode, as I don't use it myself, but I wonder how the ctors are supposed to be exported and called there?  It looks like there is an extra function `_initialize` in the exports that does not exist in regular builds. Calling that before doing any memory allocations resolves the problem, as `_initialize` calls `__wasm_call_ctors`. Is `_initialize` a needed thing in STANDALONE_WASM? Is that documented somewhere for people writing their own loaders from scratch?

**Comment by sbc100** [comment]
The STANDALONE_WASM mode tried to conform to WASI whee it can.  In his case the the startup sequence comes from WASI:

https://github.com/WebAssembly/WASI/blob/main/design/application-abi.md#current-unstable-abi

So yes, if a user wants to do something like this they would need to make sure they call `_initialize`.

I think this issue can probably be closed since there is no emmalloc issue.

**Comment by DanielMehlber** [comment]
Thanks, you really helped me out here! I called _initialize from JS, and it now works perfectly fine!
