### ISSUE TITLE
Call wasm-to-js and js-to-wasm frequency

### ISSUE THREAD

**Issue by xdestiny110** [emscripten-core/emscripten#13854]
I found there are too much 'wasm-to-js' and 'js-to-wasm' when I use performance tool in browser
![image](https://user-images.githubusercontent.com/10414623/114162278-8a855680-995b-11eb-84ca-db883512d4c2.png)
Compile option:
em++ -Oz -g0 -w --no-heap-copy -s INITIAL_MEMORY=128MB -s DISABLE_EXCEPTION_CATCHING=0 -s ALLOW_MEMORY_GROWTH=1 -s DEMANGLE_SUPPORT=1 -s FORCE_FILESYSTEM=0 -s NO_EXIT_RUNTIME=1 -s USE_FREETYPE=1 -s USE_LIBPNG=1 -s WARN_UNALIGNED=1 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s USE_WEBGL2=1 -s MODULARIZE -s WASM=1 -s 'EXPORT_NAME="createModule"' --bind

Is this normal?

**Comment by juj** [comment]
These occur when calling between the JS and Wasm language boundaries. Try
building with -g2 or --profiling-funcs to see proper callstacks of the wasm
functions.

Whether those are normal probably depends on your own application: are all
those transitions essential to implementing your program logic? Or do you
see some of those being redundant that you could optimize away?

pe 9. huhtik. 2021 klo 12.49 Xdestiny ***@***.***) kirjoitti:

**Comment by kripken** [comment]
In addition, those looks like invokes, which are because of either longjmp or exceptions. I see exceptions are enabled in the link command, so it can be that.

Assuming that is the reason, then it is normal atm. But there is [experimental support for proper wasm exceptions](https://emscripten.org/docs/porting/exceptions.html#overhead), and that will avoid the invokes into JS and be much faster.

**Comment by xdestiny110** [comment]
Invoke disappear when I close exception. Thanks~
