### ISSUE TITLE
Mixed JS / WASM usage of WebGPU

### ISSUE THREAD

**Issue by austinEng** [emscripten-core/emscripten#13888]
Most native WebGPU apps using `webgpu.h` can be ported to WASM using the current implementation in library_webgpu.js.
However, there are various non-native features that are very important for the Web Platform.

For example, `GPUQueue.copyExternalImageToTexture` and `GPUDevice.importTexture` for efficient interop with `HTMLVideoElement` and `HTMLCanvasElement`. Today, a WASM application cannot use these, because it cannot get the JS object from the raw `WGPUQueue/Device/Texture*`.

We could add functions for these in `webgpu.h` that access the ImageBitmap / HTMLVideoElement / HTMLCanvasElement by CSS selector, but not all JS objects are accessible by CSS selector (may not be in the DOM), and the CSS query probably isn't particularly efficient. Also, it does not solve the reverse direction where an application might want to us the WebGPU JS API, and then inject results into native.

Not sure if there's an existing Emscripten solution for this. But here are some ideas I'm thinking about so far. @kainino0x @Kangz @azakai 

### Idea 1: By adding some import/export JS functions to the global Module object:

I think this one is mostly straightforward and works using existing facilities - it just requires a lot of casting around and exposing per-object global methods on the `Module` object.

Example usage:

```c++
WGPUDevice cDevice = reinterpret_cast<WGPUDevice>(EM_ASM_INT({
  const adapter = await navigator.gpu.requestAdapter();
  const device = await adapter.requestDevice();
  return Module.WebGPU.importJSDevice(device);
}));

wgpu::Device device = wgpu::Device::Acquire(cDevice);

wgpu::TextureDescriptor desc = { ... };
wgpu::Texture texture = device.CreateTexture(&desc);

EM_ASM({
    var someCanvasElement = ...;
    const jsDevice = Module.WebGPU.getJSDevice($0);
    const jsTexture = Module.WebGPU.getJSTexture($1);

    jsDevice.queue.copyExternalImageToTexture(
      someCanvasElement,
      jsTexture,
      ...,
    );
  }, 
  reinterpret_cast<int>(device.Get()),
  reinterpret_cast<int>(texture.Get()),
);

```

```javascript
// library_webgpu.js
// TODO: I'm not sure how to export this stuff on the Module object
{
  getJSDevice: function(id) {
    return WebGPU.mgrDevice.get(id);
  },

  importJSDevice: function(device) {
    // Probably also include something to assert or de-duplicate imports. Or maybe duplicate imports will be fine.
    return WebGPU.mgrDevice.create(device);
  },
}
```

### Idea 2: By adding EM_ASM_ macros and a C "emscripten_" api that exports/imports

Example usage:

```c++
WGPUDevice cDevice = EM_ASM_WEBGPU_DEVICE({
  const adapter = await navigator.gpu.requestAdapter();
  const device = await adapter.requestDevice();
  return device;
});

wgpu::Device device = wgpu::Device::Acquire(cDevice);

wgpu::TextureDescriptor desc = { ... };
wgpu::Texture texture = device.CreateTexture(&desc);

EM_ASM({
    var someCanvasElement = ...;
    const jsDevice = $0;
    const jsTexture = $1;

    jsDevice.queue.copyExternalImageToTexture(
      someCanvasElement,
      jsTexture,
    );
  }, 
  emscripten_get_webgpu_js_device(device.Get()),
  emscripten_get_webgpu_js_texture(texture.Get()),
);

```

Implementation looks a bit like:

```c
// emscripten_webgpu.h
#define EM_ASM_WEBGPU_DEVICE(code, ...).       \
  reinterpret_cast<WGPUDevice>(EM_ASM_INT({   \
    const result = (function() ## code ## )();              \
    assert(!result || result instanceof GPUDevice);      \
    /* how to get a reference to WebGPU.mgrDevice?*/ \
    return WebGPU.mgrDevice.create(result);             \
  }))
  
struct EmJSValue* emscripten_get_webgpu_js_device(WGPUDevice device);
struct EmJSValue* emscripten_get_webgpu_js_texture(WGPUTexture texture);
// ... etc.
```

```javascript
emscripten_get_webgpu_js_device: function(id) {
  return WebGPU.mgrDevice.get(id);
}
// ... etc.
```

 - For the JS -> WASM path: `EM_ASM_WEBGPU_<OBJECT_TYPE>` would be a per-object macro which expects the code block to return a JS object of that type. It then registers it in Emscripten's WebGPU object tables and casts the id into a pointer.
 - For the WASM -> JS path: inside, `EM_ASM`, `__em_asm_sig<struct EmJsValue*>::value` would translate to "j". `readAsmConstArgs` would detect this "j" in the signature and pass the argument directly through instead of indexing in the HEAP.

**Comment by juj** [comment]
> We could add functions for these in `webgpu.h` that access the ImageBitmap / HTMLVideoElement / HTMLCanvasElement by CSS selector, but not all JS objects are accessible by CSS selector (may not be in the DOM), and the CSS query probably isn't particularly efficient.

Agree completely that even though `HTMLVideoElement` and `HTMLCanvasElement`s (and `HTMLImageElement`s) can be added to the DOM, the Wasm<->JS binding interop should not be achieved via that and CSS selectors.

> For example, `GPUQueue.copyExternalImageToTexture` and `GPUDevice.importTexture` for efficient interop with `HTMLVideoElement` and `HTMLCanvasElement`. Today, a WASM application cannot use these, because it cannot get the JS object from the raw `WGPUQueue/Device/Texture*`.

This is very similar to the challenge with WebGL interop with `.texImage2D()` called with a foreign `HTMLImageElement`.

Ideally we'd have one of the following two methods:
1. implement a public-facing JS API that one can be guaranteed to be able to rely on to be stable in order to pull out the internal JS context object, or
2. implement a public-facing JS API that one can rely on to be able to wrap and unwrap a JS object into the Wasm<->JS bindings realm.

In the WebGL use case we settled with the case 1: When one wants to call texImage2D on a foreign HTMLImageElement (or a HTMLVideoElement), which is quite a common "webby" task to do, we provide the guarantee that the global variable `GLctx`, and also the global variable `GL.currentContext` give access to the currently activated `WebGLRenderingContext` and Emscripten GL rendering context object respectively.

This enables code to simply write stuff like this:

https://github.com/juj/webgl_render_test/blob/bb517e34dfaa13404feaa8a5ba8bf42c32581c44/src/library_js.js#L2-L6

i.e. `GLctx` is the public API for WebGL.

I think that is a simple way that works for the immediate JS-side "I-know-what-calls-to-inject" use cases.

For WebGPU we don't want to have a concept of "currently active WebGPU context" since we don't need to do the "glMakeCurrent" style of design. For there the stable JS side API interface would looks something different (maybe a `WebGPU.getContext()` function or something like that)

The method 2 would be that we'd expose a global function that one calls from JS, say

```js
wrapHtmlVideoElement: function(someHtmlVideoElement) {
  var counter = WebGPU.wrappedVideoElementsCounter++;
  WebGPU.wrappedVideoElements[counter] = someHtmlVideoElement;
  return counter;
}

emscripten_queue_copy_external_image_to_texture: function(queue, videoElement) {
  var q = WebGPU.queues[queue];
  var ve = WebGPU.wrappedVideoElements[videoElement];
  q.copyExternalImageToTexture(ve);
}
```

this way one can wrap a JS-side object into a unique ID object that one can carry around in Wasm, and call `emscripten_queue_copy_external_image_to_texture()` with that ID to point to the wrapped video element.

The method is generic enough that arbitrary types can be marshalled, i.e. there is no need to namespace `WebGPU.wrappedVideoElements` vs `WebGPU.wrappedImageElements` etc. - just had that there to illustrate an example.

See the function `wgpuStore()` in my WebGPU bindings library: https://github.com/juj/wasm_webgpu/blob/master/lib/lib_webgpu.js#L33 which achieves that idea.

> ### Idea 1: By adding some import/export JS functions to the global Module object:
> 
> I think this one is mostly straightforward and works using existing facilities - it just requires a lot of casting around and exposing per-object global methods on the `Module` object.

For all intents and purposes, a good bindings library should not touch or interact with the `Module` object in any way. That is a bad practice, a pattern that we used to do a long time ago in the absence of better ways to organize code. The issue is that it mixes imports, exports and namespace visibility for the sake of "easy routing", and it heavily prevents minification and Closure oportunities. So basically the `Module` object should not be touched or relate in any way for a bindings library - its use should be strictly restricted to the user to control to decide what symbols they need exported unminified out from the JS Module scope.

**Comment by austinEng** [comment]
Thanks for the `wgpuStore` reference. I think that doing something like `wrapHtmlVideoElement` would work, and you're right we could make it a generic object store. Perhaps it should be a general object store for Emscripten, and not WebGPU-specific (I guess namespacing the wrappings helps mitigate eventually overflowing the counter though). We will need an `unwrap` method as well though so that the object store doesn't hold onto JS references forever.

How is `wrapHtmlVideoElement` exposed to JS?

**Comment by juj** [comment]
> Perhaps it should be a general object store for Emscripten, and not WebGPU-specific

We have discussed a global Emscripten object store in the past on a number of occassions. The biggest benefit/user of that would have always been WebGL, other APIs don't have as much of a need to wrap a large number JS objects over to Wasm side. 

However the realisation was that for WebGL, the lifetime of the WebGL objects is tied to the GL context lifetime, rather than being global, so WebGL would not want to use a global object store anyways. (although a wrapping of HTMLImageElement/HTMLVideoElement/etc. one could see as being independent of the GL context)

> How is `wrapHtmlVideoElement` exposed to JS?

It would be exposed as a JS library function, like other JS library functions in src/library_*.js are.

**Comment by alienself** [comment]
Any updates on this issue? Any example out there implementing either technique 1 or 2?

**Comment by austinEng** [comment]
I implemented `JsValStore` in https://github.com/emscripten-core/emscripten/commit/c6f8c071b04cda24bf088d7bee0ed6af068c3832 which is most like technique 1.
