### ISSUE TITLE
⚠ RuntimeError: function signature mismatch

### ISSUE THREAD

**Issue by danbugs** [emscripten-core/emscripten#14034]
I'm trying to get a very simple example of passing functions pointers from JS to C++ using a `WebAssembly.Table` without Emscripten's auto-generated JS and I'm getting the error in the title ("RuntimeError: function signature mismatch").

Here's my C++:

File `misc.cpp`:
```
#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#endif

#ifdef __cplusplus
extern "C"
{
#endif
    typedef void (*consoleLog)(const char *);

#ifdef __EMSCRIPTEN__
    EMSCRIPTEN_KEEPALIVE
#endif
    void misc(consoleLog fn)
    {
        fn("Hello, JS. This is C++");
    }

#ifdef __cplusplus
}
#endif
```

... and, here's my JS with relevant comments:

File `misc.js`:
```
let moduleExports = null;
let moduleTable = null;

const init = () => {
  moduleTable = new WebAssembly.Table({ initial: 1, element: "anyfunc" });
  moduleTable.set(0, convertJsFunctionToWasm(consoleLog, "vi"));
  //                 ^^^ got this fn from Emscripten's auto-generated JS

  let importObject = {
    env: {
      table: moduleTable,
    },
  };
  WebAssembly.instantiateStreaming(fetch("misc.wasm"), importObject).then(
    (result) => {
      moduleExports = result.instance.exports;
      moduleExports._initialize();
    //   moduleTable = moduleExports.__indirect_function_table;
    //   ^^^ is this necessary? 
    }
  );
};

const consoleLog = (strPointer) => {
    console.log(strPointer);
}

const misc = () => {
  moduleExports.misc(0);
  //                ^^^ 0 because that's the table index we put the consoleLog function at `moduleTable.set(...)`
};

```

What am I doing wrong? I'm compiling the code with `emcc misc.cpp -o misc.wasm --no-entry`.

(ps. for the HTML side of things, I just have a button that calls `misc` when `onclick`, a body calls `init` when `onload`, and `script` tags with `src`s of `misc.js` and `emscripten.js`.)

**Comment by sbc100** [comment]
emscripten-generated wasm modules export the table rather than importing it.  At least if you are using STANDALONE_WASM (which is implicit of you do `-o` to a file that ends with `.wasm) and not SIDE_MODULE.      So yes you will need to pull the table object out of the exports of the module.

Also you will almost certainly not want to use table slot zero as that corresponds to the NULL function pointer in C/C++.   Instead the best way to get a new table slot is probably to see how big the table it and `.grow` the table and put your function in that new slot.  Emscripten does this in getEmptyTableSlot: https://github.com/emscripten-core/emscripten/blob/f2c2432c43e2392473582e31484232bea047b324/src/runtime_functions.js#L100.

**Comment by danbugs** [comment]
> emscripten-generated wasm modules export the table rather than importing it. At least if you are using STANDALONE_WASM (which is implicit of you do -o to a file that ends with `.wasm) and not SIDE_MODULE. So yes you will need to pull the table object out of the exports of the module.

Thank you so much ~ using the exported table and having the `.set(...)` method call after getting the `__indirect_function_table` **fixed my issue** 🎉

>Also you will almost certainly not want to use table slot zero as that corresponds to the NULL function pointer in C/C++.

Somehow, I did not know this — Appreciate it haha

>  Instead the best way to get a new table slot is probably to see how big the table it and .grow the table and put your function in that new slot. Emscripten does this in getEmptyTableSlot:

Thanks for the resource too! ;D 

... closing the issue!
