### ISSUE TITLE
Undefined non-function symbols not detected

### ISSUE THREAD

**Issue by vargaz** [emscripten-core/emscripten#14106]
Version: 2.0.18

Testcase:
```
#include <stdio.h>

extern void *missing_sym;
extern void *missing_sym2;

int
main (void)
{
	fprintf (stderr, "DOH: %p\n", missing_sym);
	fprintf (stderr, "DOH2: %p\n",missing_sym2); 
	fflush (stderr);
	return 0;
}
```
Compile with:
```emcc -s ERROR_ON_UNDEFINED_SYMBOLS=1 -g bug.c -o bug.js```
Expected result: a link error
Actual result: linking succeeds, the app can also be ran:
```v8 --expose_wasm bug.js```
produces:
```
DOH: 0x63736d65
DOH2: 0x63736d65
```

**Comment by kripken** [comment]
This happens in `2.0.19` as well.

@sbc100 is this a known limitation with `wasm-ld` perhaps? It seems to happen with any extern `void*`, `int`, etc., anything that is not a function.

**Comment by sbc100** [comment]
I don't think this has ever worked with emscripten.  At least I can go back as far as 2.0.0 and I see the same behaviour.

Arguably we can/should do better, but we never has as far as I can tell.

The `0x63736d65` value by the way is a result of reading a null pointer.  If you build with `SAFE_HEAP` you will that this program segfaults trying to read from an undefined symbol.

I think we have some other issues related to how to make this better.. I'll try to find them and to link to them.

**Comment by sbc100** [comment]
Actually this did previously work in fastcomp... at least it would report undefined symbols.  So we should try to do that same with upstream llvm.

**Comment by sbc100** [comment]
Ah yes, I remember why we can't do this with the llvm backend.  

The reason is that at code-generation time clang assumes it can use immediate values for the address of data symbols (e.g `i32.const XX` and `i32.load XX`).    So if the linker finds that a symbol is missing it cannot represent the undefined symbol as an import (e.g. and imported global) without also re-writing all the uses to use `global.get` (which the linker generally cannot do).

The fixes we have available depend on which of the two desired outcomes we are looking for:

1. Undefined data symbols (at least non-weak ones) cause link time errors.
2. Undefined data symbols can be turned into imports from, for example, JS.

(1) is fairly straight forward and I think we have gone back and forth on this a few times.   Its just a question of what we want to allow to slip through in emscripten.

(2) is harder.  One possible solution is to switch to always conservatively using `global.get` in codegen for data addresses (we do this in PIC mode already I think), and try to do either linker relaxation of rely on binaryen to relax this to `i32.const` when the symbol is actually defined at static link time.

**Comment by kripken** [comment]
I think I used to believe 2 was important, but now I think 1 would be enough. What do you mean by "slip though", though? (can't it be precise?)

**Comment by sbc100** [comment]
By slip through I meant programs that contain undefined symbols to link without error. 

I will looks into changing the meaning of `--allow-undefined` or perhaps adding a new option to the `--unresolved-symbols` handling argument that I added in https://reviews.llvm.org/D79248.

**Comment by sbc100** [comment]
There is some history here:

I originally made lld report errors on undefined symbols even when `--allow-undefined` was specified:

https://reviews.llvm.org/D60882

This change was essentially reverted:

https://reviews.llvm.org/D79247

The discussion around this was is:

https://groups.google.com/g/emscripten-discuss/c/HSRgQiIq1gI/m/Kt9oFWHiAwAJ

It sounds like we need to revisit to add more flexibility here.

**Comment by kripken** [comment]
This came up again in https://github.com/GoogleChromeLabs/squoosh/pull/1017#issuecomment-849211629 , which shows how this bug can be quite annoying for users.

If modifying LLVM codegen is difficult, perhaps this could be handled using the linking custom section? That is, we could still lower globals to linear memory addresses as we do now, plus a relocation (no change). And also we could note in the linking section that so-and-so global is required. Then the linker could verify that all required globals have actually been linked in (which would ensure we replaced the 0 with a proper address).

**Comment by sbc100** [comment]
Are you suggesting that we do runtime relocation.. even for normal static binaries?

**Comment by sbc100** [comment]
BTW.. there are two different issue here I think. 

1. Reporting of error on undefined data symbols
2. Allowing JS to support data addresses at runtime

This issue is just about reporting the error, not about supplying such address at runtime.

**Comment by sbc100** [comment]
Regarding (2), given that for static binaries wasm-ld has already performed that full memory layout its not clear how JS could possibly inject any static data anything.. that static data and stack and heap are all fixed for non-PIC binaries with no room for JS to add anything new.

**Comment by kripken** [comment]
Sorry, no, I'm not suggesting runtime relocation. Also I'm not talking about allowing JS to supply data symbols. The only thing I think is urgent here is to error on undefined data symbols statically at link. I think we should do that, and users that want a 0 for such undefined globals can set `ERROR_ON_UNDEFINED_SYMBOLS=0`, the same as with functions.

**Comment by sbc100** [comment]
I see.. Yes I think we can achieve that using linker flags.    I'll take a look today.
