### ISSUE TITLE
Endless recursion in emscripten_thread_sleep after dispatching in worker thread

### ISSUE THREAD

**Issue by MizantropLoL** [emscripten-core/emscripten#14116]
I have an endless recursion, if call emscripten_thread_sleep inside dispatched (with emscripten_dispatch_to_thread) function, when it  dispatching to working thread.
Here the code to reproduce:
```
#include <stdio.h>
#include <emscripten/threading.h>
#include <emscripten/emscripten.h>

void work()
{
  printf("Begin work\n");

  emscripten_thread_sleep(100);

  printf("End work\n");
}

void * thread_func(void * _param)
{
  while (1)
    emscripten_thread_sleep(1000);

  return NULL;
};

int main() {
  pthread_t thread;
  pthread_create(&thread, NULL, thread_func, (void *)0);

  emscripten_dispatch_to_thread(thread, EM_FUNC_SIG_V, &work, 0);

  emscripten_exit_with_live_runtime();

  printf("Test finish\n");
}
```

The reason is inside emscripten_current_thread_process_queued_calls. Queue head increment goes after _do_call method, which call emscripten_thread_sleep, which call emscripten_current_thread_process_queued_calls and so on.

**Comment by MizantropLoL** [comment]
Bump

**Comment by sbc100** [comment]
@juj, any ideas?   Is this pattern supposed to work?

**Comment by juj** [comment]
This issue is similar in spirit to the conversation in #14292.

Originally proxy queue was only used for system implemented proxied events, which were carefully crafted not to execute any priority inverting code. After opening up the machinery for user submitted proxy calls, there is now a possibility to do all kinds of priority inversion lockups.

However for this very specific pattern, the issue is due to the missing TODO in https://github.com/emscripten-core/emscripten/blob/f56479d4e8f40156c90e0d3dadf549b5fe13ddfa/system/lib/pthread/library_pthread.c#L662-L665

Originally when that was written, we did not have good TLS support. I think that could now be replaced by a .S file that implements a wasm global variable for a proper per-thread re-entrancy guard check. That should fix up this issue.

**Comment by sbc100** [comment]
Since we have TLS now I tried uploading PR: #14315.  Still need to construct a test case..
