### ISSUE TITLE
WebIDL Binder assumes `_free` is available

### ISSUE THREAD

**Issue by dasa** [emscripten-core/emscripten#14125]
_free reference:
https://github.com/emscripten-core/emscripten/blob/b8724b8e58e4f580623e187abd9b626e42b1bba5/tools/webidl_binder.py#L178

I assume this was broken by #12213.

The workaround is to add `_free` to `EXPORTED_FUNCTIONS`.

I'm not sure if this is a bug, or just needs to be doc'ed.

**Comment by kripken** [comment]
Thanks @dasa , good point. The JS emitted by the webidl binder does call malloc and free arbitrarily, so we should keep them alive for it.

We don't know to keep them alive in emcc, though, since from emcc's perspective the webidl binder is an external tool that runs before it, and just provides JS and cpp inputs to emcc. I'm not sure offhand if there's a good way to add a keepalive in a cpp file... we want to add something like
```cpp
EMSCRIPTEN_KEEPALIVE void* malloc(size_t);
```
and for that to tell the compiler to link in malloc and also export it.

@sbc100 maybe you have an idea? Also @floooh I remember you were interested in such a thing - maybe you found a way?

If nothing else, we could add a check in emcc for the webidl exports perhaps, but that feels like a hack.

**Comment by sbc100** [comment]
Its really the external JS code that is depending on those symbols so somehow the JS code needs to specify those symbols are needed.  I'm not to familiar with WebIDL binder.  I guess its not using the normal JS library system?

**Comment by sbc100** [comment]
I think having the C code express the dependency is backwards.  Its the JS code that needs malloc and free but there is no way for external JS code like this to express dependencies on native symbols today other than via `EXPORTED_FUNCTIONS`.  

I wonder if we can have webidl binder write a file do disk that contains a list of symbols it needs.. then users would be expected to pass `-sEXPORTED_FUNCTIONS=binder_deps.txt` at link time?

**Comment by dasa** [comment]
> The workaround is to add `_free` to `EXPORTED_FUNCTIONS`.

I found with 3.1.31+ that `_malloc` needs to be added as well.

**Comment by sbc100** [comment]
Yes, currently webidl binder requires both `_malloc` and `_free`.   Currently there is no way to express this dependency so they need to be exported manually.  I'd love to find a way to express this dependency but we don't have one today.

**Comment by sbc100** [comment]
I did try using EM_JS_DEPS but sadly it looks like this method cannot be used to export new native functions like `_malloc` and `_free`.    At least not yet.

One option is to create new wrappers for malloc and free and tag the wrappers with `EMSCRIPTEN_KEEPALIVE` in the generated .cpp file.
