### ISSUE TITLE
Symbols map no longer accurate with SPLIT_MODULE

### ISSUE THREAD

**Issue by Mintyboi** [emscripten-core/emscripten#14133]
@sbc100 We are currently using the `--emit-symbol-map` flag to generate a map between the index in the wasm table and the actual function such that we could reconstruct a callstack.

However, after splitting the module into main and deferred using wasm-split, the mapping is no longer accurate. Can I check if there are any plans to support symbol maps in the SPLIT_MODULE feature?

**Comment by sbc100** [comment]
Interesting, from the docs for `--emit-symbol-map` I thought it mapped minified function names to original function names, but it looks like it actually maps function indexes to names  (is that right @kripken?  do we need to update the docs?)

With `SPLIT_MODULE` there are two different modules in the final output so we would probably need to create two different symbol map files, one for each module, and depending on where in the pipeline we run wasm-split it might need to take case of modifying those file.    Could be a bit of work there.. @tlively

**Comment by tlively** [comment]
Taking a look at the Emscripten code for this, it looks like `--emit-symbol-map` just 1) builds the module while keeping the names, then 2) runs the equivalent of `wasm-opt output.wasm --print-function-map -o output.wasm > output.wasm.symbols` to strip the names and produce the symbol map.

So you could produce symbol maps for the split modules by similarly running `wasm-opt --print-function-map` on them individually.

Since the current wasm-split workflow does not have Emscripten being responsible for splitting the modules, I don't see how we could build support for producing split symbol maps directly into Emscripten.

I'm not familiar with how symbol maps are consumed, so I'm not sure what would need to change to consume split symbol maps.

**Comment by Mintyboi** [comment]
At the risk of sounding ignorant, I understand that when we do a split, wasm-split actually replaces functions from the deferred module with a placeholder in the wasm table. So we may actually know the index of each functions.

If we pass in the original symbol map in the wasm-split workflow, are we able to populate a new symbol map?

**Comment by sbc100** [comment]
I believe that at runtime, when you have backtrace it will contains function indexes that belong to both the main module and the side module.    Some of the functions in the backtrace will be from the side module and some will be from the main module.  Each module has its own index space, and you would need to map both of them separately in order to add names to your backtrace.

For example you might have a backtrace that contains function 1 from the size module and function 1 from the main module, so `1` not longer uniquely identifies functions, you would need (module,number) pair to do that.

**Comment by Mintyboi** [comment]
@sbc100 In the SPLIT_MODULE feature, I believe the main and deferred module shares the same wasm table, so the indexes will be unique.
e.g. This is the wasm table before the deferred module is loaded:
```
1. $placeholder.0
2. $placeholder.1
3. $placeholder.2
4. $placeholder.3
5. $placeholder.4
6. $placeholder.5
7. $%fn4\28\29
8. $placeholder.7
9. $placeholder.8
```

After the deferred module is loaded, the wasmtable gets replaced to:
```
1. $f26
2. $f45
3. $f29
4. $f30
5. $f31
6. $f32
7. $primary.%fn4\28\29
8. $f33
9. $f34
```

Please correct me if I'm wrong @tlively

**Comment by sbc100** [comment]
They do share a table and there they do share table indexes.  However, the symbol map does not contain *table* indexes, so the table in is not relevant.   The symbol map (and the backtraces produced by the via) refer instead to *function* indexes.  Function indexes are not shared between modules and each function can have a different index in each module.

Therefore, with mutiple modules, a function index alone is not enough to uniquely identify a function, you also need the module in which the function index lives.

**Comment by tlively** [comment]
@Mintyboi, I uploaded a binaryen PR adding symbol map support to wasm-split: https://github.com/WebAssembly/binaryen/pull/3894. When building the initial module, you will have to keep the function names in the module by passing `--profiling-funcs`. That will allow wasm-split to see the names and write the symbol maps when you pass `--symbolmaps`. If you don't pass `-g` to wasm-split, it will also remove the names from the two output modules after writing the symbol maps.

**Comment by Mintyboi** [comment]
@sbc100 Got it, thanks for the explanation.

@tlively Sounds good! I'll try it. Thanks

**Comment by tlively** [comment]
Nevermind, I figured out that I could just run the module directly in node 👍 I got it working to produce the profile and I got it working with the split modules as well.

I noticed that the symbol map function indices were wrong, so I wrote https://github.com/WebAssembly/binaryen/pull/3900 to fix that problem.

With that fix, I'm getting the matching symbols to be `placeholder_474` in the primary module and `jsmain` in the secondary module. This at least makes more sense. `jsmain` is being called on the primary module, but that's just a wrapper that calls out to the real `jsmain` on the secondary module.

The `<anonymous>` module name in the stack trace is due to the way the Module is compiled in the JS. `new WebAssembly.Module(...)` does not associate a name with the module. If we were to switch to using `WebAssembly.instantiateStreaming` to load the Modules, this problem would go away.

**Comment by tlively** [comment]
I wrote https://github.com/WebAssembly/binaryen/pull/3901 to add a new wasm-split option, `--emit-module-names`, that emits module names in the final split binaries even if all other names are stripped. That helps differentiate them in stack traces.

In the course of playing around with that, I realized that even without `-g`, not all function names are fully stripped when the module passed to wasm-split contains function names. This is because the primary functions that wasm-split exports for use in the secondary module are exported with their full original names. I will make a follow-up PR to minimize those newly exported function names when `-g` is not passed to wasm-split.

**Comment by waterlike86** [comment]
Thanks @tlively for following up, and sorry for the lack of instructions on how to run the test i shared. 
tested https://github.com/WebAssembly/binaryen/pull/3900 and verified that its good. 
would `--emit-module-names` give the module names even when `WebAssembly.Module(...)` is used instead of `WebAssembly.instantiateStreaming`?

we have another case where a side module triggers the secondary module. because it also uses the sync api and not the streaming api could we get the module name as well? will this ever happen? or would the side module always call the wrapper in the primary module, then followed by the the implementation in the secondary module?

**Comment by tlively** [comment]
> would --emit-module-names give the module names even when WebAssembly.Module(...) is used instead of WebAssembly.instantiateStreaming?

Yes, that's correct. The way I have it written now, it will generate module names from the output filenames given to wasm-split. So even after I copy pri.wasm and sec.wasm to index.wasm and index.deferred.wasm, I get these lines in the stack trace:

```
    at sec.wasm (<anonymous>:wasm-function[461]:0x1566c)
    ...
    at pri.wasm.jsmain (<anonymous>:wasm-function[851]:0x11e76)
```

> we have another case where a side module triggers the secondary module. because it also uses the sync api and not the streaming api could we get the module name as well?

Do you mean the module name of the side module? Maybe we could look at generating names for side modules as a separate issue.

> will this ever happen? or would the side module always call the wrapper in the primary module, then followed by the the implementation in the secondary module?

If I understand correctly, and perhaps @sbc100 can confirm, main modules and side modules expose functions to each other via exports. If that is the case, then when the side module calls a secondary (i.e. deferred) function from the main module, it will always go through a wrapper function in the primary module followed by the implementation in the secondary module, just as you say.

**Comment by waterlike86** [comment]
Thanks @tlively i verified that the module names are generated and they are very helpful in helping us identify the correct module map to use. 
yes I will log a seperate issue for generating names for side modules if we need it. so far just having the names for the primary and deferred is good enough.

I created another test where the side module calls a function in the deferred module.

```
  at jsStackTrace (/home/leezh/git/EmscriptenTestProjSkeleton/build/index.js:1088:14)
    at abort (/home/leezh/git/EmscriptenTestProjSkeleton/build/index.js:854:14)
    at _abort (/home/leezh/git/EmscriptenTestProjSkeleton/build/index.js:1828:2)
    at index.wasm.deferred (<anonymous>:wasm-function[531]:0x12a8c) <-- main module placeholder
    at index.wasm.add2 (<anonymous>:wasm-function[873]:0x12265) <-- main module placeholder 
    at obj.<computed> (/home/leezh/git/EmscriptenTestProjSkeleton/build/index.js:1321:22)
    at sideAdd (<anonymous>:wasm-function[4]:0x112) <-- side module function 
    at _sideAdd (/home/leezh/git/EmscriptenTestProjSkeleton/build/index.js:4391:28) <-- exported side module function 
    at index.wasm.deferred (<anonymous>:wasm-function[578]:0x168f9) <-- deferred module implementation
    at /home/leezh/git/EmscriptenTestProjSkeleton/build/index.js:935:45
    at index.wasm.jsmain (<anonymous>:wasm-function[874]:0x12273)  <-- main module placeholder
    at Object.Module._jsmain (/home/leezh/git/EmscriptenTestProjSkeleton/build/index.js:23451:65)
    at saveProfileData (/home/leezh/git/EmscriptenTestProjSkeleton/build/index.js:23876:19)
    at callRuntimeCallbacks (/home/leezh/git/EmscriptenTestProjSkeleton/build/index.js:1038:4)
    at postRun (/home/leezh/git/EmscriptenTestProjSkeleton/build/index.js:794:2)
    at doRun (/home/leezh/git/EmscriptenTestProjSkeleton/build/index.js:23820:3)
    at run (/home/leezh/git/EmscriptenTestProjSkeleton/build/index.js:23831:3)
    at runCaller (/home/leezh/git/EmscriptenTestProjSkeleton/build/index.js:23756:18)
    ```
    
    in    ` at index.wasm.deferred (<anonymous>:wasm-function[531]:0x12a8c) <-- main module placeholder` i expected the function to call directly the actual implementation since the deferred module was loaded earlier in the call stack , but it went and called the place holder in the primary function first. why is that?

**Comment by tlively** [comment]
Just looking at this section of the stack trace:

```
 (1)   at index.wasm.deferred (<anonymous>:wasm-function[531]:0x12a8c) <-- deferred module implementation
 (2)   at index.wasm.add2 (<anonymous>:wasm-function[873]:0x12265) <-- main module placeholder 
 (3)   at obj.<computed> (/home/leezh/git/EmscriptenTestProjSkeleton/build/index.js:1321:22)
```

It looks like some JS in frame (3) is calling an exported wasm function to create frame (2). Since the secondary module is meant to be transparently loaded as an implementation detail, most JS does not know that the secondary module exists. That means that exported secondary functions still need to be exported from the primary module, just as they would if the module were not split. So frame (2) is just a wrapper function that the primary module can export and that calls the real implementation in the secondary module. You're right that the secondary module has already been loaded, and we can see that the JS placeholders are no longer being called because there is no JS frame between the export wrapper in (2) and the implementation in (3). I hope that made sense, but let me know if I can clarify anything.

Also, I have a PR up for minimizing the names of the new imports and exports that wasm-split creates: https://github.com/WebAssembly/binaryen/pull/3905

**Comment by waterlike86** [comment]
Thanks @tlively that makes alot  of sense. Wiill be testing out https://github.com/WebAssembly/binaryen/pull/3905. this should help our code size.
also created a new issue in identifying the missing function.
https://github.com/emscripten-core/emscripten/issues/14330

**Comment by Mintyboi** [comment]
Seems like this issue has been resolved. Thanks for your help @tlively, @waterlike86 
Should this issue be closed? Or we expecting more changes?
