### ISSUE TITLE
Error in python script

### ISSUE THREAD

**Issue by DartPower** [emscripten-core/emscripten#14176]
I tried to compile this:
https://github.com/gabrielcuvillier/d3wasm
But IDK this related to emscripten or d3wasm

```
dartpower@DPTN:~/Downloads/d3wasm/build-wasm$ make package_demo_data
  File "/home/dartpower/Downloads/emsdk/upstream/emscripten/tools/file_packager.py", line 140
    'virtual file system.' % fullname, file=sys.stderr)
                                           ^
SyntaxError: invalid syntax
make[3]: *** [CMakeFiles/package_demo_data.dir/build.make:57: CMakeFiles/package_demo_data] Ошибка 1
make[2]: *** [CMakeFiles/Makefile2:105: CMakeFiles/package_demo_data.dir/all] Ошибка 2
make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/package_demo_data.dir/rule] Ошибка 2
make: *** [Makefile:131: package_demo_data] Ошибка 2
```

OS: Debian GNU/Linux 10 (buster) x86_64
Kernel: 4.19.0-13-amd64

**Comment by DartPower** [comment]
Oops this is emsdk problem

**Comment by sbc100** [comment]
This looks like file_packager.py being run under python2 instead of python3.

Looks like we have the wrong `#!` line in there.. so I think this is a real bug.   However I would probably be better if you used the launcher script called `file_packager` (with no extension on unix or `.bat` extension on windows).  This will always use the correct python version.
