### ISSUE TITLE
MAIN_MODULE=2 link with side modules cause side module loaded automatically

### ISSUE THREAD

**Issue by EvanZhao1003** [emscripten-core/emscripten#14225]
I build a main module wasm with -s MAIN_MODULE=2 and list all side modules needed on the command line.
I notice there's a "dylink" section in main module .wasm file. In glue js function "receiveInstance", it will read this section and add all needed wasm names to "dynmaicLibraries".Then the module will load these "dynmaicLibraries" automaticlly.
Can these side module not be added to main module's "dylink" section? I want to load side module with function "loadDynamicLibrary" mannually. I may want to change side module wasm's name after build.

**Comment by sbc100** [comment]
Can you simply stop specify the side module on the command line?  Perhaps not, if you relying on emcc reading the symbols from them in order to do its DCE correctly?

I'd like to keep the current behaviour as the default but perhaps we can find an option for you.  

How about this: We could specify that if you pass `RUNTIME_LINKED_LIBS` explicitly on the command line it overrides any implicit deps.  So you could pass `-s RUNTIME_LINKED_LIBS=[]` as a way to signal that you don't want the deps to be read implicitly.   I don't love it but I can't think of another way without adding an entirely new option.

**Comment by EvanZhao1003** [comment]
> Can you simply stop specify the side module on the command line? Perhaps not, if you relying on emcc reading the symbols from them in order to do its DCE correctly?
Yes, I want its DCE 
> I'd like to keep the current behaviour as the default but perhaps we can find an option for you.
> 
> How about this: We could specify that if you pass `RUNTIME_LINKED_LIBS` explicitly on the command line it overrides any implicit deps. So you could pass `-s RUNTIME_LINKED_LIBS=[]` as a way to signal that you don't want the deps to be read implicitly. I don't love it but I can't think of another way without adding an entirely new option.
Yes, I think it will work for me

**Comment by sbc100** [comment]
I ended up creating a new setting for this: https://github.com/emscripten-core/emscripten/pull/14245
