### ISSUE TITLE
Displacement warning(a<<=32)

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14239]
`unsigned int a =1;
a= a<<32;`
compile it , there are warning :"shift count >= width of type [-Wshift-count-overflow]".

And , the result after displacement is 0。and in windows the result is 1。

could you tell me why? how sovle the problem?

**Comment by sbc100** [comment]
Left shift by more than the size of the type is undefined behaviour apparently:
https://docs.microsoft.com/en-us/cpp/code-quality/c26452?view=msvc-160
https://blog.regehr.org/archives/226

"Reason: Unsigned Left Shift Error: Right operand is negative or is  greater than or equal to the width of the promoted left operand"

So you can't rely on the result of such an operation, and I think code need to be fixed in order to be portable.
