### ISSUE TITLE
"Unable to find library -ljpeg" after update from 2.0.15 to 2.0.16

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#14488]
In version 2.0.15, the following call works, whereas in 2.0.16 it does not:
```
emcc -O2 -g -fPIC -s USE_ZLIB=1 -s USE_LIBJPEG=1 \
   -s USE_FREETYPE=1 -Wno-unused-result -Wsign-compare \
   -DNDEBUG -g -fwrapv -Wall -fPIC -DHAVE_LIBJPEG -DHAVE_LIBZ -DPILLOW_VERSION="8.0.1" \
   -I/root/repo/cpython/installs/python-3.8.2/include/python3.8 \
   -c src/_imaging.c -o build/temp.linux-x86_64-3.8/src/_imaging.o
```
With the working v20.0.15 build it says:
```sh
system_libs:INFO: retrieving port: libjpeg from https://storage.googleapis.com/webassembly/emscripten-ports/jpegsrc.v9c.tar.gz
system_libs:INFO: unpacking port: libjpeg
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libjpeg.a... (this will be cached in "/root/repo/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libjpeg.a" for subsequent builds)
root:INFO: building port: libjpeg
cache:INFO:  - ok
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libz.a... (this will be cached in "/root/repo/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libz.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libfreetype.a... (this will be cached in "/root/repo/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libfreetype.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/pic/libjpeg.a... (this will be cached in "/root/repo/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libjpeg.a" for subsequent builds)
root:INFO: building port: libjpeg
cache:INFO:  - ok
```
In the nonworking v20.0.16 build:
```sh
system_libs:INFO: retrieving port: libjpeg from https://storage.googleapis.com/webassembly/emscripten-ports/jpegsrc.v9c.tar.gz
system_libs:INFO: unpacking port: libjpeg
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libjpeg.a... (this will be cached in "/root/repo/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libjpeg.a" for subsequent builds)
root:INFO: building port: libjpeg
cache:INFO:  - ok
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libz.a... (this will be cached in "/root/repo/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libz.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libfreetype.a... (this will be cached in "/root/repo/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libfreetype.a" for subsequent builds)
cache:INFO:  - ok
src/_imaging.c:3928:26: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
wasm-ld: error: unable to find library -ljpeg
```
In the nonworking 20.0.16 build, the `generating port: sysroot/lib/wasm32-emscripten/pic/libjpeg.a` message is missing.

**Comment by sbc100** [comment]
The command you sent is the compile command, but from the error message it looks like the link command is the one that fails.  Can you attach the failing link command?

**Comment by hoodmane** [comment]
`emcc -s BINARYEN_EXTRA_PASSES="--pass-arg=max-func-params@61" -O2 -s MODULARIZE=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1 -s SIDE_MODULE=1 -s USE_LIBJPEG=1 -s USE_FREETYPE=1 -ljpeg build/temp.linux-x86_64-3.8/src/_imagingft.o -o build/lib.linux-x86_64-3.8/PIL/_imagingft.cpython-38-x86_64-linux-gnu.so`

**Comment by sbc100** [comment]
I found the issue.  It seems that it still exists in `main` too. 

There are several issues at play here and we can solve this in various ways:

1. With emscripten MAIN_MODULE/SIDE_MODULE split, the ports libraries are always linked into the main appliction, and not the side module.  At least that as been the assumption.  See https://github.com/emscripten-core/emscripten/blob/f46fbc5a1eb5dc878c3bdd5a505fc17142875961/emcc.py#L2413-L2415 (excuse the typo).  This means that `-s USE_LIBJPEG=1` is expected to have an effect on the main module rather than that side module.  This policy seems like it might be worth revisiting (I pre-dates my involvement with emscripten I believe).    I think the idea was to avoid multiple copies of a given library existing in every side module.  For libraries like libc this is more clearly the right thing to do.
2. Even when building the main module the `-s USE_LIBJPEG=1` flags is all that is needed to include libjpeg.  Add `-ljpeg` in addition is at best redundant.

My advice for now, especially if you are stuck on an older emsdk version, would be to use `./embuilder` to build the libraries you need.  In that case you can even drop the `-s USE_LIBJPEG=1 -s USE_FREETYPE=1` flags too I think.  e.g. `./embuilder build libjpeg --pic`.   You can use `./embuilder --help` to see a full list of libraries you can build.

**Comment by sbc100** [comment]
Another alternative would be to add the `-s SIDE_MODULE` (or `-s RELOCATABLE`) flag during compilation which would cause the `pic` versions of the libraries to be built.

**Comment by hoodmane** [comment]
Okay I added `-s SIDE_MODULE` to the compile flags and that indeed fixes the problem. If I remove `-ljpeg` from the linker flags it fails at runtime:
```
Assertion failed: bad export type for `jpeg_resync_to_restart`: undefined 
Couldn't instantiate wasm: /lib/python3.8/site-packages/PIL/_imaging.so 'RuntimeError: abort(Assertion failed: bad export type for `jpeg_resync_to_restart`: undefined). Build with -s ASSERTIONS=1 for more info.'
```

**Comment by sbc100** [comment]
OK that makes sense.  I not the way the ports are designed to be used but I guess it works!

**Comment by hoodmane** [comment]
The `-s USE_LIBJPEG=1 -s USE_FREETYPE=1` linker flags are unnecessary as you said.

**Comment by sbc100** [comment]
https://github.com/emscripten-core/emscripten/pull/14490 will part of the problem going forward in that you won't need that `-s SIDE_MODULE` at compile time anymore.  `-fPIC` should be enough.

**Comment by hoodmane** [comment]
From my perspective this issue is resolved but I am will leave it open because there is a linked PR.

Really appreciate your prompt and detailed support with these issues @sbc100!
