### ISSUE TITLE
Use same javascript runtime across wasm binaries (using STANDALONE)

### ISSUE THREAD

**Issue by jfizz** [emscripten-core/emscripten#14499]
Is it possible to have emcc emit a JS runtime file which would contain all possible imports needed for wasm binaries compiled using STANDALONE? My goal is to use the same JS runtime across wasm binaries (assuming other compiler settings are the same).  From my understanding, the current behavior is to only include the imports needed.
Note: I understand the required imports could change between emscripten versions.

**Comment by sbc100** [comment]
We have no support for this today but its always been something that seems like an interesting idea to pursue.

I imagine that any such solution would require the use of MODULARIZE, right?  Since there are a lot of JS globals that needs to be specific to each instance (e.g. wasmMemory, HEAP8, etc, etc,).

I imagine we you start with INCLUDE_FULL_LIBRARY + MODULARLIZE only then you (or somebody) could get a prototype working fairly quickly.

**Comment by jfizz** [comment]
Right, my plan is to use MODULARLIZE and then pass in `wasmBinary` to dynamically specify the binary.

INCLUDE_FULL_LIBRARY looks like it'll work for me. That'll give me a good starting point and I will narrow it down from there based on what I expect to need. Thanks for the help!
