### ISSUE TITLE
Application report sys_wait4 symbol not defined

### ISSUE THREAD

**Issue by leyao-daily** [emscripten-core/emscripten#14574]
I use emscripten 2.0.7 to create a standalone WASM application.
And the build is successful, but when I run it, it will report the error `Failed to load Wasm module due to a missing import: env.__sys_wait4`
I have checked all my source code and find nothing related to the sys_wait.

**Comment by sbc100** [comment]
How are you trying trying to run the app?  The emscripten-generated JS will define that function if its needed: https://github.com/emscripten-core/emscripten/blob/main/src/library_syscall.js#L1489

If you are trying to directly load the wasm file with your own loader, that loader will need to implement any syscalls your application uses.

Note that if your application depends on `__sys_wait4` it probably won't work under emscripten because our JS libraries don't support fork/exec/wait or any kind of multi-process support.

**Comment by leyao-daily** [comment]
I find the root cause. I use pclose() which call sys_wait4. LOL Solve it.
