### ISSUE TITLE
wasm-ld: error: inconsistent LTO Unit splitting

### ISSUE THREAD

**Issue by mad-rain** [emscripten-core/emscripten#14694]
Hi!

We try to use '-fvirtual-function-elimination' to reduce wasm file size, it works just fine, but we have to remove emscripten cache if we compiled something before with -flto=thin otherwise we receive link error:

wasm-ld: error: inconsistent LTO Unit splitting (recompile with -fsplit-lto-unit)

Simple bat file to reproduce the bug (c:\emsdk is Emscripten installation path):

```
rem clean cache
del /S /Q C:\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\
call c:\emsdk\upstream\emscripten\emcc -flto=thin main.cpp
call c:\emsdk\upstream\emscripten\emcc -fsplit-lto-unit -fvirtual-function-elimination -flto=full main.cpp
```

main.cpp:
```

struct foo {
  virtual ~foo() { }
  virtual int a() { return 12345001; }
  virtual int b() { return 12345002; }
};

struct bar : public foo {
  virtual ~bar() { }
  virtual int a() { return 12345003; }
  virtual int b() { return 12345004; }
};

int main(int argc, char** argv) {
  foo* p = (argc & 1 ? new foo() : new bar());
  int res = p->a();
  delete p;
  return res;
}

```

**Comment by kripken** [comment]
I see the error too. Looks like we build system libs with the LTO flag we are given, due to
```python
  if settings.LTO and not force_object_files:
    flags += ['-flto=' + settings.LTO]
```
in `system_libs.py`. So we build different LTO libs depending on which LTO the user requested. That seems odd to me - is that intentional @sbc100 ?

Confirming this in the build libraries, some diffs:
``diff
- !llvm.module.flags = !{!51, !52, !53, !54, !55}
+ !llvm.module.flags = !{!51, !52, !53, !54}
```
and indeed at 55 there is
```
!54 = !{i32 1, !"ThinLTO", i32 0}
```

**Comment by sbc100** [comment]
Ah yes that does look like a bug.   I wonder if we need to support two different LTO versions of the cached libraries, or can we just always build them with full LTO?
