### ISSUE TITLE
invalid value type 's128', enable with --experimental-wasm-simd 

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14763]
Our code does not use the function of simd instruction set , compile and generate. Js library, loading times error
`uncaught (in promise) runtimeError: abort(CompileError:WebAssembly.instantiate():compiling function #332 failed: invalid value type 's128', enable with --experimental-wasm-simd ,build with -s ASSERTIONS=1 for more info`

**Comment by yangfangfang1204** [comment]
we need use .js in chrome V83 , and  i want to know why there is a error?

**Comment by kripken** [comment]
I would check `-msimd128` is not passed in to any of the source files you compile. It might also be applied in a library that you receive already compiled.

If that doesn't help, I would build with `--profiling` (so that names are kept), and then disassemble the wasm (using `wasm-dis` or `wasm2wat`), then search for `v128`. That would show where the type is used.

Side note, I'm confused why it says `s128` and not `v128` in that error - is that expected @tlively ?

**Comment by tlively** [comment]
Yes, V8 calls it s128 internally for some reason.
