### ISSUE TITLE
__sys_madvise1

### ISSUE THREAD

**Issue by MizantropLoL** [emscripten-core/emscripten#14767]
Hi.
Do you plan on adding implementation of system call __sys_madvise1?

**Comment by sbc100** [comment]
There is not really any way to implement `madvise` since there is no equivalent WebAsssembly or JavaScript feature.   

So I guess that answer is no, at least not until some WebAssembly of JS feature comes along that gives us more control over virtual memory.

If that answers your question please go ahead and close this issue.

**Comment by MizantropLoL** [comment]
I see. Thank you
