### ISSUE TITLE
emmalloc + pthread assert

### ISSUE THREAD

**Issue by MizantropLoL** [emscripten-core/emscripten#14766]
Hi.
If I use emmalloc with pthread, assert(emscripten_is_main_runtime_thread()) indicates as false, inside the initialize_malloc_heap() method (performs at main thread)

**Comment by sbc100** [comment]
Hmm, the problem seems to be that the emmalloc static constructor gives itself too high a priority making it run before the main pthread is setup:

https://github.com/emscripten-core/emscripten/blob/1abc342f0976cd0f64cb50599b0fdfd82a292805/system/lib/pthread/library_pthread.c#L982-L987

https://github.com/emscripten-core/emscripten/blob/1abc342f0976cd0f64cb50599b0fdfd82a292805/system/lib/emmalloc.cpp#L530

Fixing that will be little tricky as `Pthread.initRuntime` calls malloc (we probably should avoid that).
