### ISSUE TITLE
how to terminate the pthread created in C layer like webWorker.terminate()

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14873]
I use pthread_create create the thread in C code , then use pthread_join or return to exit the thread(pthread_exit() throw the unwind error ) , then i find the dedicated worker is still in the task manager of chrome when thread exit.
And if i create a webworker in JS , i could use ` webWorker.terminate()` to terminate the worker, and the dedicated worker in the task manager of chrome will disappear . 

so is there a similar function that can make dedicated workers  in the task manager of chrome disappear when thread exit ?

**Comment by sbc100** [comment]
Funny you should mention that, I just filed #14872 and opened #14869 because I noticed that our current `pthread_kill` implementation is basically doing exactly this (although it shouldn't be!).

We don't currently have any API for shrinking the size of the worker pool.. its grows on demand but never shrinks.  In fact we don't export the existence of workers at all, only pthreads which temporarily inhabit a given worker.

What kind of use do you have where you want to remove workers but keep the rest of the program running?  If it is really necessary I image we could add some kind new API for this:

```
int emscripten_get_pthread_pool_size();
void emscripten_set_pthread_pool_size(int);
```
