### ISSUE TITLE
node package with emscripten do not support wasm-eh

### ISSUE THREAD

**Issue by sps-gold** [emscripten-core/emscripten#15157]
currently wasm built with [-fwasm-exceptions](https://emscripten.org/docs/porting/exceptions.html#webassembly-exception-handling-proposal) cannot be run with packaged version of node (14.15.5_64bit) in emscripten 2.0.31.

Also I find that emscripten tests built with eh are [run using v8](https://github.com/emscripten-core/emscripten/blob/12b2b675c202d2abc0a3f6c756939dde39eb199e/tests/test_other.py#L7500). I believe this is temporary and will the test runtime will be switched back to node once supported. 

The latest node version available (supporting --experimental-wasm-eh handling is 16.10.0)

May I know when would you like to upgrade node version in emscripten.

**Comment by sbc100** [comment]
The Wasm EH proposal is still in flux IIUC, so its not clear that that node 16.10.0 contains a recent enough V8 version to support the latest llvm/emscripten output.  @aheejin might know if this is true.

Regardless, the version of node that we ship as part of emsdk is kept pinned to an older/stable version for several reasons.   If you want to run your generated code on a more recent version of node it should be easy to do that I think.  The version of node we include is mostly designed to run our internal tools.  In order to actually run the generated code you can use whatever version you see fit (just like its up to you what browser version you want to run the generated code under).   Is there some reason why its important to you to use the emsdk-supplied version of node to run you code?  Are you trying to run this in production or is just for running tests and such?

**Comment by sbc100** [comment]
There is even talk of downgrading the node version we ship I'm afraid: https://github.com/emscripten-core/emsdk/pull/877 

:(

**Comment by sps-gold** [comment]
Actually so far we have been using node that comes with emsdk to run our tests, so even while testing eh build I did the same with assumption it will be supported. Later when I figured out that I either need latest node or d8 to run the same, I also wanted to ensure that it is not expected to support multiple runtimes for our testing and in future also node runtime will be good enough. however thanks @sbc100 for the explanation and sharing about the ongoing downgrade node discussion. 

PS: here's a quick reference to node vs v8 version https://nodejs.org/en/download/releases/

**Comment by aheejin** [comment]
Node 16.10.0 has Wasm EH support, but I'm not sure how mature or bug-free it is. Anyway, as @sbc100 said, it is easy enough to change the Node binary you are using in the config file. I think it's emsdk/.emscripten.

**Comment by sbc100** [comment]
Do you have a working setup for running your tests under node now @sps-gold ?  Can this issue be closed?

**Comment by sps-gold** [comment]
yes, after your [reply ](https://github.com/emscripten-core/emscripten/issues/15157#issuecomment-929252512) I have started using nvm to install and use node version as per my need. So ok to close this issue.
