### ISSUE TITLE
wgpuRenderPassEncoderSetIndexBuffer(..., WGPU_WHOLE_SIZE) error

### ISSUE THREAD

**Issue by hujiajie** [emscripten-core/emscripten#15237]
Output snippet:

```js
  function _wgpuRenderPassEncoderSetIndexBuffer(passId, bufferId, format, offset_low, offset_high, size_low, size_high) {
      
      
      var pass = WebGPU.mgrRenderPassEncoder.get(passId);
      var buffer = WebGPU.mgrBuffer.get(bufferId);
      var offset = (assert(offset_high < 0x200000), offset_high * 0x100000000 + offset_low)
  ;
      var size = ((size_high === 0xFFFFFFFF && size_low === 0xFFFFFFFF) ? undefined :           (assert(size_high < 0x200000), size_high * 0x100000000 + size_low)
  );
      pass["setIndexBuffer"](buffer, WebGPU.IndexFormat[format], offset, size);
    }
```

`size_low` and `size_high` are `-1` instead of `0xFFFFFFFF` here.

cc @kainino0x

**Comment by kainino0x** [comment]
Thanks Jiajie, I must have made a totally wrong assumption about how 64 bit arguments get passed in. I thought this was working properly, so I have to investigate.

**Comment by sessamekesh** [comment]
Quick ping - I've also been running into the same issue, I've made some fixes on my development branch and opened up a PR to merge them upstream. PTAL if you're interested / opinionated about how this is implemented.

Turns out this is a pretty big "gotcha" with how JavaScript deals with numbers (go figure, eh?) - `uint64_t` numbers in C++ are legalized as two `int32` (upper and lower) pairs, but `0xFFFFFFFF` is evaluated as a Number (float64) instead of Int32.

Thanks for opening this up - I saved a _lot_ of time debugging last night by stumbling across this!
