### ISSUE TITLE
Do Mutex/Atomics require pThreads support?

### ISSUE THREAD

**Issue by jeffRTC** [emscripten-core/emscripten#15280]
@sbc100 

I need to implement a synchronization mechsmisim around unordered_map as lot of JS events call it async fashion to insert and delete elements, but I don't want to use threads. I heard somewhere that Emscripten use threads to implement Mutex/Atomics.

**Comment by jeffRTC** [comment]
@sbc100  Okay, but do locking still require pThreads support?

**Comment by sbc100** [comment]
Another way of thinking about: In single threaded wasm today there is no parallelism (no threads running at the same time) and also no concurrency (no such thing an multiple outstanding computations).  

In JS you can use async/await to get a form of concurrency but that doesn't extend to WebAssembly because you can't `await` on a WebAssembly function.
