### ISSUE TITLE
Deprecation of environment variable NODE

### ISSUE THREAD

**Issue by ymoreau** [emscripten-core/emscripten#15306]
My build gives me this warning, but I don't understand how I am supposed to switch the new variable as I never configured any of this in the first place.

> warning: honoring legacy environment variable NODE. Please switch to using EM_NODE_JS instead

Are we supposed to create this environment variable EM_NODE_JS ourself?

**Comment by sbc100** [comment]
Something in your environment is setting `NODE`.    We've had this come up before and I think we fixed it already:

See: https://github.com/emscripten-core/emsdk/issues/862
And: https://github.com/emscripten-core/emscripten/pull/14968

So it looks like this should be fixed in 2.0.30.. can you confirm what version you are using?
