### ISSUE TITLE
RuntimeError: Aborted(TypeError: Cannot convert undefined to a BigInt)

### ISSUE THREAD

**Issue by sps-gold** [emscripten-core/emscripten#15333]
Using std filesystem and building with wasm bigint results into runtime error

```
RuntimeError: Aborted(TypeError: Cannot convert undefined to a BigInt)
    at abort (/tmp/emscripten_test_wasm0_5c7f8bdv/src.js:1520:11)
    at ___syscall_getdents64 (/tmp/emscripten_test_wasm0_5c7f8bdv/src.js:4312:69)
    at readdir (wasm://wasm/00184186:wasm-function[1545]:0x26509)
```
**Reproducer:** https://github.com/emscripten-core/emscripten/pull/15332

https://app.circleci.com/pipelines/github/emscripten-core/emscripten/16340/workflows/4e6332a5-a20e-40c4-8814-0f21dcf8a940/jobs/466952?invite=true#step-106-1908

**Comment by sps-gold** [comment]
[lookupPath](https://github.com/emscripten-core/emscripten/blob/2213884b85ae8803f4a420349d55e44587364606/src/library_fs.js#L182) isnt returning the id, referenced in [syscall_getdents64](https://github.com/emscripten-core/emscripten/blob/2213884b85ae8803f4a420349d55e44587364606/src/library_syscall.js#L871), so id becomes undefined

**Comment by gl84** [comment]
A simple test case that fails similarly can be found in my pull request #15308. The test case fails since #15167.

It seems #15167 is fishy....

Unfortunately I don't know the FS part well enough to provide a fix...

**Comment by sps-gold** [comment]
> 
> I think it would be great if we could create a smaller repro based on just the opendir and readdir?

updated the [reproducer: #15332 ](https://github.com/emscripten-core/emscripten/pull/15332/files)as you suggested

**Comment by jmglogow** [comment]
I'm bitten by the same bug and can confirm it broke between 2.0.31 and 2.0.32.

Manually patching `src/library_fs.js` of the 2.0.34 `emsdk` and re-linking the LibreOffice WASM, I found that:
  * https://github.com/emscripten-core/emscripten/commit/7bdf447a38d03ca4c746adc4d4cd5899d6c2eb26 fixes my bug
  * https://github.com/emscripten-core/emscripten/pull/15332/commits/09586528bcf3b833014421cb426bbae5dd0ac8b0 doesn't fix my bug

Looking at other `FS.lookupPath` callers, they always get the node via

     var lookup = FS.lookupPath(mountpoint, { follow_mount: false });
     node = lookup.node;

and that `node` has a `node.id`.

The 2nd patch seems to be correct too, even if it doesn't fix my problem, as `FS.lookupNode` takes a node as the first argument and for `FSStream` the node is stored in its `object` attribute via `this.node`. Since that whole `prototype` has the comment `// compatibility`, I guess it's only some backward compatibility code. OTOH I couldn't find any direct assignment of `stream`'s `node`, even via `this.node`… but then, my current JavaScript knowledge is almost just from the '90s, so I might be totally wrong ;-)

**Comment by sps-gold** [comment]
hi @jmglogow they were two separate commits but are not independent fixes, so both will be required. Here is the [full PR link](https://github.com/emscripten-core/emscripten/pull/15332). However, you may notice that the PR still fails some test, so my changes miss out something but I haven't got chance to look into those.

**Comment by jmglogow** [comment]
I tried to understand what is going on (and eventually fix it). The main problem IMHO seems to be that `RAWNODEFS` doesn't create "real" `node` objects internally at a few points, like `lookup`. Instead the breaking patch copies a lot more `node` stuff into the `stream` object, so it can be passed as a `node` to

     var child = FS.lookupNode(stream, name);

My understanding is that `RAWNODEFS` should "just" properly fill stream.node instead.
