### ISSUE TITLE
Caching from a read-only base folder is impossible due to safe_copy copying the permissions bits

### ISSUE THREAD

**Issue by RaitoBezarius** [emscripten-core/emscripten#15374]
I'm using Nix to install `emscripten` (2.0.27) and the folder where it is installed is read-only (and immutable), therefore, whenever I try to use the cache setup to `~/.cache/emscripten`, it fails as: `safe_copy` uses `shutil.copy` rather than `shutil.copyfile`.

The issue is rather similar to https://github.com/mkdocs/mkdocs/issues/1292 ; making it impossible to run `embuilder build SYSTEM` and compiles something.

Would that be possible to use `shutil.copyfile` or ensure that copied files have `+w` when caching is performed?

Thanks!

**Comment by RaitoBezarius** [comment]
That did the trick! Thx you unlocked https://github.com/RaitoBezarius/nixexprs/runs/4055692165?check_suite_focus=true :-)

**Comment by wirew0rm** [comment]
It looks a bit like this issue has been reintroduced recently:

https://github.com/emscripten-core/emscripten/commit/e3dce64c61ec9717b3fb7f6f07880d4b12bb4830#diff-e5c9f13d92c2262ea8cfc14b3529f271697fce42d49e5857e20ff833e18c00d0R2461

This function directly calls shutil.copytree(src, dst, dirs_exist_ok=True) which now works with existing files, but seems to fail if the existing files are readonly. And since this method circumvents the `make_writeable` (which fixed this issue) by not calling safe_copy, if the files are read-only, emcc calls will fail with permission denied.

At least that's how I interpret the stacktraces that emcc throws back at me with my (limited) understanding of how emscripten works. Might also be some configuration issue on my side, but to me it looks like a rather trivial regression for an admittedly kind of rare setup. If I revert `copytree_exists_ok(...)` to the old implementation everything works as expected (after removing the cache with the read-only files).

My suggestion would be to either revert to the old function or probably better to (recursively) make `copytree_exists_ok` call `make_writable` on it's dst argument after the  `shutil.copytreee` call. I'll try to prepare a PR.

**Comment by sbc100** [comment]
I think I have a fix in flight: https://github.com/emscripten-core/emscripten/pull/24405
