### ISSUE TITLE
musl v1.2.2 LTO linker errors for exp_data and exp2f_data

### ISSUE THREAD

**Issue by floooh** [emscripten-core/emscripten#15506]
Related links:

- https://groups.google.com/g/emscripten-discuss/c/g_vkRRSCPUI
- https://github.com/emscripten-core/emscripten/pull/13006
- https://github.com/emscripten-core/emscripten/pull/15497

When testing the latest tot version which switched to musl v1.2.2, I'm getting linker errors in the sokol-samples project only when building with LTO enabled:

```
wasm-ld: error: /...cache/sysroot/lib/wasm32-emscripten/lto/libc.a(exp2f_data.o): undefined symbol: __exp2f_data
```
```
wasm-ld: error: /...cache/sysroot/lib/wasm32-emscripten/lto/libc.a(exp_data.o): undefined symbol: __exp_data
```

Unfortunately I'm having a hard time coming up with a minimal reproduction test case. From looking at the MUSL sources I'd expect that just using one of the ```pow(), exp(), exp2()``` calls (or their 'f' versions) in a minimal source file and compiling with LTO should trigger the problem, but so far no dice (stay tuned).

PS: the optimizer passes removed the actual function calls and replaced them with simplified expressions 🙄

Here's a reproducer for the exp2_data problem:

```c
//
//  Compile with:
//
//  emcc -flto -O3 -o bla.js bla.c   
//
#include <stdio.h>  // printf()
#include <stdlib.h> // atof()
#include <math.h>   // exp2f()
#include <assert.h> // assert()

int main(int argc, char* argv[]) {
    assert(argc > 0);
    // important to have some unpredictable input value, otherwise
    // the optimizer will remove the exp2f call alltogether
    const float val = atof(argv[1]);
    const float res = exp2f(val);
    printf("%f\n", res);
    return 0;
}
```

...and a reproducer for ```exp_data```, same code, just replace the ```exp2f()``` call with ```exp2()```:

```c
//
//  Compile with:
//
//  emcc -flto -O3 -o bla.js bla.c   
//
#include <stdio.h>  // printf()
#include <stdlib.h> // atof()
#include <math.h>   // exp2f()
#include <assert.h> // assert()

int main(int argc, char* argv[]) {
    assert(argc > 0);
    const double val = atof(argv[1]);
    const double res = exp2(val);
    printf("%f\n", res);
    return 0;
}
```

**Comment by floooh** [comment]
Ok... after trying out @sbc100's PR the exp_data and exp2_data linker errors appear fixed, but there's now a similar followup problem with ```__math_oflowf``` and ```__math_uflowf``` (slightly different error output though):

```
error: undefined symbol: __math_oflowf (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: ___math_oflowf may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: __math_uflowf (referenced by top-level compiled C/C++ code)
warning: ___math_uflowf may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
```

Also only when compiling with LTO.

Those are defined in MUSL in the source files ```src/math/__math_oflowf.c``` and ```src/math/__math_uflowf.c```, I'll check if it's enough to add those files to the file list in ```tools/system_libs.py```...

**Comment by floooh** [comment]
Ok, looks like adding the following files additionally to the new files in https://github.com/emscripten-core/emscripten/pull/15497 fixes the issue for my sokol-samples / libmodplug case:

```
      '__math_oflow.c', '__math_oflowf.c',
      '__math_uflow.c', '__math_uflowf.c',
```

...hard to say though if there are similar problems lurking in other code bases...

**Comment by floooh** [comment]
Oops, sorry, that was too early. While the libmodplug case is fixed, other sokol-sample demos now trigger a new wasm-ld error I haven't seen before.

```
wasm-ld: error: /.../lto/libc.a(__math_divzerof.o): attempt to add bitcode file after LTO.
```

This appears to happen in demos that also link with Dear ImGui, also seems LTO specific. No idea how to proceed there though, the error message looks like it's a problem with mixed LTO / non-LTO code generation?

**Comment by sbc100** [comment]
No, this is all part of known issue related to libcalls/builtins and LTO.   

Last last error you are seeing is because the reference to `__math_divzerof.o` object was generated during LTO.  i.e. that object was deemed not needed prior to LTO but needed after LTO, but since the object itself is an LTO object there is now way to now include it since LTO is done.

I believe this all relates to this upstream issue that I files: https://bugs.llvm.org/show_bug.cgi?id=44353.  And I think the reason that we seem to be the only effect folks is that nobody else is trying to compile compiler-rt and its libc dependencies as LTO.

Hopefully #15497 should fix this for you.

**Comment by floooh** [comment]
FYI @sbc100, after testing your latest PR update there was one more followup error, but adding the following files to the end of your changes seems to fix those.

```
      '__math_invalid.c', '__math_invalidf.c', '__math_invalidl.c'
```

...my sokol-samples project is still compiling but after 2/3 I guess it's working now (will followup here if it doesn't).

**Comment by yuyichao** [comment]
I'm getting a very similar error for ldexp.o when playing with yosysjs.

**Comment by sbc100** [comment]
@yuyichao could you share the full command line and the full error message?

**Comment by yuyichao** [comment]
I don't really have a minimum example to show but I have a github action to do the compilation automatically and I've just triggered a build that should show the issue (if I didn't mess anything up....)

The build is at https://github.com/yuyichao/yosysjs/runs/4804475201?check_suite_focus=true and it should finish in about 5-10min... The finally  linking step has many different files though but if there's an easy way to automatically reduce it I could give it a try.

Note that this is using 3.0.0 release since the archlinux package hasn't been updated yet but it should have the previous fix.

**Comment by yuyichao** [comment]
See the error at https://github.com/yuyichao/yosysjs/runs/4804475201?check_suite_focus=true#step:11:1094

**Comment by yuyichao** [comment]
This is with llvm/clang 13, in case that’s a new transformation they added…

**Comment by sbc100** [comment]
Emscripten is based on tip-of-tree llvm, which is currently llvm 14 (we roll in the latest changes from llvm several times a day). 

Are you sure you are using llvm 13?  I'd be surprised if that was working/possible.   See #11362 for discussions around possibly supporting older stable llvm versions.   However, I also doubt this issue is related to the specific llvm version.. i think its just a matter of crafting an imput with a certain form... which I've not managed to do yet, but I'm happy to land #16002 anyway.

**Comment by yuyichao** [comment]
Yes you are right. The archlinux package was using a specific llvm upstream commit.
