### ISSUE TITLE
The latest tag 2.0.34 is broken (fixed in main)

### ISSUE THREAD

**Issue by K-os** [emscripten-core/emscripten#15539]
The latest tag 2.0.34 is currently seriously broken for my project due to #15327. The problematic change has been reverted in main already #15460, but it is not tagged yet. This leads to Chrome browser tabs crashing with the "Aw Snap!" error when running my code built with emsdk latest.

It would be nice to have a working tag soon, especially since finding the root cause for crashing browser tabs is really hard.

Thanks

**Comment by sbc100** [comment]
We are currently looking into a few regressions from different change (#13006) before we tag the next release which will most likely be 3.0.0.

Hopefully we can tag a new release which will include #15327 before the end of the week.    I assume your concern is mostly for other users since you have determined that 2.0.34 has issues with our project and you can use 2.0.33 instead?

**Comment by K-os** [comment]
Yes, that was exactly my concern, since I spent quite a while myself trying to debug the crash.

Thanks for the clarification about the upcoming release.

**Comment by kripken** [comment]
@K-os Meanwhile you can use `emsdk install tot`, or you can use a specific hash if you want a fixed version, like `emsdk install fb7323b957ce5bcb1f492a35f024407720a604e6`

**Comment by K-os** [comment]
I'll close this, since 3.0.0 is out and the problem is fixed.
