### ISSUE TITLE
unable to use ucnv_open with USE_ICU=1

### ISSUE THREAD

**Issue by mewalig** [emscripten-core/emscripten#15720]
Hello,

Using the following code:
```
// test.c
#include <unicode/ucnv.h>

int main() {
  int e;
  const char *u = "UTF8";
  UConverter *p = ucnv_open(u, &e);
  if(p)
    ucnv_close(p);
}
```

I can compile natively with simple `gcc -licuuc test.c`. However, running `emcc -s USE_ICU=1 test.c` gives me:
```
error: undefined symbol: ucnv_close_70 (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _ucnv_close_70 may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
...
```

I've tried using EXPORTED_FUNCTIONS e.g.:
```
emcc -s USE_ICU=1 test.c -s EXPORTED_FUNCTIONS=["_main","_ucnv_close"]
```

and it has no effect.

I've also tried compiling the ICU libraries directly-- I was not able to fully install without issue, but I seemed to be able to get at least the core libraries installed-- and then running:
```
emcc -licuuc test.c -L/opt/wasm/lib
```

but then I get:
```
wasm-ld: error: unknown file type: ucnv.ao
emcc: error: '/path/to/emsdk/upstream/bin/wasm-ld -o a.out.wasm /opt/wasm/lib/libicuuc.a ....
```

Any suggestions?

**Comment by sbc100** [comment]
I tried your test program it work fine for me:  `em++ -s USE_ICU=1 test.cpp`. 

Because the ICU library you should really need link with `em++` but aside from that it works fine.

I notice that your undefined symbol is for `ucnv_close_70` but the ICU version that we ship is version 69 and the symbol in the emscripten library would be called `ucnv_close_68`:

```
$ ../llvm-build/bin/llvm-nm ./cache/sysroot/lib/wasm32-emscripten/libicu_common.a  | grep ucnv_close
0000054b T ucnv_close_68
```

So it seems that somehow the wrong version of the ICU headers is being found on your machine.   Can you run the `em++` command with `-v` so we can see which include paths are being picked up?

**Comment by mewalig** [comment]
Thank you for your response. I don't know why it didn't occur to me to update my emsdk to the latest version. After I did that, it compiled just fine (with `emcc`, did not need `em++`). If only it were always that easy!
