### ISSUE TITLE
Embind Array.from broken by closure=1 DYNAMIC_EXECUTION=0

### ISSUE THREAD

**Issue by emaxx-google** [emscripten-core/emscripten#15734]
Hello, the next issue similar to #15692 and #15585 was discovered. Repro:
```
#include <string>
#include <emscripten/val.h>
int main() {
  emscripten::val::global("Array").call<emscripten::val>("from", emscripten::val::array());
}
```
```
emcc --bind --closure=1 -O3 -s DYNAMIC_EXECUTION=0 main.cc -o a.out.html && emrun a.out.html
```
Error:
```
Uncaught TypeError: c[(h + 1)].J is not a function
    at a.out.js:30
    at j (a.out.js:30)
    at a.out.wasm:0x31f0
    at f._main (a.out.js:34)
    at a (a.out.js:36)
    at a.out.js:37
```

P.S. Just wondering - does Embind have a test suite that could be run (as a whole) under these flag combinations? Seems like these flags trigger a completely untested configuration.

**Comment by kripken** [comment]
Good question - `NO_DYNAMIC_EXECUTION` is definitely tested less, but I think that's because it limits what we can do, and some things are expected not to work. That is, I don't think the current test suite will or should fully pass under that mode. We could run it and sift through the results, but that would require a significant amount of time and digging into embind internals, and AFAIK no one is focused on that atm.

**Comment by emaxx-google** [comment]
Thank you for explaining this. Should we maybe update the Emscripten docs to explicitly say that "use closure=1 at your own risk, since its interplay with other features is undertested"? As I feel like the issue is not DYNAMIC_EXECUTION=0, but closure=1, which performs nontrivial code transformations that can explode in random places. And currently "closure=1" is documented as if it's an innocent optimization flag, just like "-O3" - but turns out their workability differs dramatically.

P.S. To explain why DYNAMIC_EXECUTION=0 is important and might be frequently used by devs is that Chrome Extensions and Apps have the "unsafe-eval" Content Security Policy, and this policy is violated by Emscripten's code unless DYNAMIC_EXECUTION=0 is specified.

**Comment by sbc100** [comment]
Actually we *do* do a lot of testing with `--closure=1`, and its even the default of `-O3`.  In this case it really is `-sDYNAMIC_EXECUTION=0` which is the less trodden (and less tested) path.     If anything it should this setting which has some kind of warning in the docs.

**Comment by sbc100** [comment]
If there are enough users of `-sDYNAMIC_EXECUTION=0` we could add a test suite configuration for this option and see if we can keep it green over time.

**Comment by emaxx-google** [comment]
Thanks.

As for `-O3` - somehow `-sDYNAMIC_EXECUTION=0` works fine if used alone and/or with `-O3`, but only breaks after adding `--closure=1`. I don't observe that `-O3` implies `--closure=1` based on file sizes too. So a test suite would require the combination `--closure=1  -sDYNAMIC_EXECUTION=0` in order to catch the bugs like this.

As for the usage of `DYNAMIC_EXECUTION=0` - unless I'm unaware of some trick, it seems to be a hard requirement for Emscripten when used in Chrome Extensions/Apps. As developers (me including :) ) are being forced to move away from NaCl, its usage should increase.

**Comment by sbc100** [comment]
Oh, I guess maybe was wrong about `-O3` implying closure!  Sorry about that.

In any case, closure is valuable tool that I would recommend to anyone shipping production emscripten output as it reduces code size significantly.   We try to get a lot of test coverage of closure output.   This is unlike `-sDYNAMIC_EXECUTION` which is a relatively niche option that, on balance, probably doesn't deserve the same share of the testing budget.    Of course, that doesn't mean its not important or that we should try harder to get better coverage..

**Comment by kripken** [comment]
(yes, closure is not on by default even in `-O3`. the reason is that it can easily break with user-provided JS code.)

Looking into this a little, the issue is `readValueFromPointer` is not minified properly. This suggests that perhaps quite a lot of embind + NO_DYNAMIC_EXECUTION code is not written in a closure-safe way, as that function does not look very special.

I would say for now to avoid closure when using the combination of embind + NO_DYNAMIC_EXECUTION. We should at some point do a complete audit of this code and understand what should be quoted and where. Alternatively, maybe we can find a way to make the NO_DYNAMIC_EXECUTION mode "just work" with closure, without finding out where to sprinkle quotes - perhaps there is a general pattern in the code.

@emaxx-google how important is it to use closure in your use case?

**Comment by emaxx-google** [comment]
> @emaxx-google how important is it to use closure in your use case?

In my use case (Google Smart Card Connector extension) it's not crucial - it was more as a "nice to have" optimization. Based on the discussion above, I'll simply hold off using `--closure=1` until it gets stabilized in Emscripten.

I guess other developers might stay unaware about this issue though, unless docs are changed to mention this culprit somewhere.

**Comment by kripken** [comment]
Ok, sounds good, and thanks for filing the issue.

I think since NO_DYNAMIC_EXECUTION is fairly niche, maybe we don't need an update to the general docs. Leaving this issue open to document the issue might be enough and is hopefully easily searchable for anyone hitting the problem.

**Comment by alexprogrammr** [comment]
@kripken JFYI, `NO_DYNAMIC_EXECUTION` is a must-have feature when developing a browser extension based on Manifest Version 3 where all `eval` and `new Function` capabilities are forbidden.

**Comment by kripken** [comment]
@alexprogrammr 

Good point, thanks - I should not have called the use case "niche".

We have had some work in this area, btw, but I don't remember if it fixed this particular issue. It might be good to check if it's still a problem.
