### ISSUE TITLE
Link Error in latest emscripten version

### ISSUE THREAD

**Issue by Mr-shadow** [emscripten-core/emscripten#15849]
hey guys,  i attached one error when i call ` WebAssembly.instantiateStreaming(fetch("./some.wasm")` , importObject), where the wasm file is generated by emscripten 3.0.1, but it works good when the wasm file generated by emscripten 1.38.45  with same code and emcc command,  what should i do for loading my wasm module in this version?
error is :
Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #0 module="env" function="__memory_base" error: global import must be a number, valid Wasm reference, or WebAssembly.Global object

**Comment by sbc100** [comment]
Normally with emscripten-generated wasm module the expectation is that they be loaded by emscripten-generated JavaScript.  It looks like you are instead attempting the load the module using your own hand-written JS code.  Is that correct?   If so, while his is possible, it is not easy and it means that you will need to track the changes that are made to emscripten's internal APIs.

Ideally you would be able to take advantage of of the JavaScript code generated by emscripten to load your module.  If that is not possible then we can help you update your JavaScript code to be able to load the newer module, but we might need some more information.   For example, can you provide the full link command used to generate your module?

It looks like perhaps you are using the `-sSIDE_MODULE` settings (since the resulting module seems to be relocatable).  Is that a requirement for you?  If you only want to build a standalone WebAssembly module that you can load with your own hand-rolled JS then its probably better (these days) to use the `-sSTANDALONE_WASM`  setting since that setting specifically designed for that purpose.

**Comment by Mr-shadow** [comment]
thank you, exactly i'm study Webassembly with a book witch write with emscripten 1.38.45, and i'm try sharing much data with javascript and webAssembly, this book introduced a method to create a shared memory between webassembly and javascript, and it needs to load the .wasm file by myself.   may i share lots of data between webassembly and javascript with the automatically generated .js file?  i can't find this from the emscripten docs, so...

**Comment by sbc100** [comment]
You don't need to use a shared memory in order to share memory between JavaScript and C++.   Shared memory is about sharing between threads.   The memory used by C++ is always exports the JavaScript so sharing data by writing directly to memory is always a possibility. 

emscripten exports the various views of the memory as `HEAP8`, `HEAP32` etc... as well as the underlying `memory` object. 

Interactivity with C++ and copying things into and out-of the C++ memory space is covered here in the docs: https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html.

There is no need to load the WebAssembly module yourself to take advantage of direct access to the memory.

**Comment by Mr-shadow** [comment]
Thank you for your patience， would you mind tell me how to build my code to .wasm file and .js file so that i can use Module._malloc() and Module._free() function? The Module loaded by the JavaScript code generated by emscripten  don't have this two. 
my command : 
```
emcc .\mem.cpp -o mem.js -s EXPORTED_FUNCTIONS="['_getOffset','_fill_2','_add_3','_release','_print_data']" -s ALLOW_MEMORY_GROWTH=1
```
my emcc-v command return this:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.1 (5ebe1d421445fa9a4a02c1efc6d42bde3ac90da2)
clang version 14.0.0 (https://github.com/llvm/llvm-project d98dfb2baabb647a6ac4c4f4399999cfc44433db)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Comment by sbc100** [comment]
If you want to use `_malloc` and `_free` then you should add them to `EXPORTED_FUNCTIONS`. 

(Also, the modern syntax for that option is much more simple: `-sEXPORTED_FUNCTIONS=_foo,_bar,_baz`)

**Comment by Mr-shadow** [comment]
thank you very much!
