### ISSUE TITLE
pthread clarification 

### ISSUE THREAD

**Issue by arsnyder16** [emscripten-core/emscripten#16408]
I am trying to compile my library that has a few external dependencies that are statically linked.

Everything is working fine currently, but i am trying to enable some pthread support for some specific cpp files. I set a few -pthread on one of my cpp files 
  ```
set_source_files_properties(
      file_using_trheads.cpp
   PROPERTIES COMPILE_FLAGS -pthread)
```

I also apply the `-pthread` option to my linker flags. 

I am getting the following error 

`wasm-ld: error: --shared-memory is disallowed by other_file.cpp.o because it was not compiled with 'atomics' or 'bulk-memory' features.`

I get this error it seems for all object files including ones from the third party libraries that don't leverage any threading.

This lead me to think in order to get any pthread support i need compile all object files linked into my application with `-pthread`

 Is this true? seems very strange that i would have to do that even if those files do no leverage anything from pthreads?

**Comment by arsnyder16** [comment]
If this is the case i am curious how the system libraries work with or without pthreads under 

./upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/

**Comment by sbc100** [comment]
You only need to compile with `-pthread` if the source code in questions uses atomics and/or TLS.   The reason is that if you compile such objects *without* `-pthread` then clang will lower those constructs away to normal loads/stores and normal global data.

In other words, if you library uses atomics/TLS, and you want to link it into a pthread-using program you need to compile with `-pthreads`.   If you doesn't use any atomics/TLS then it doesn't matter if you build with `-pthread` or not because the object file is the same either way.

**Comment by arsnyder16** [comment]
Thanks for the clarification, turns on a lot more of my third party required `-pthread` than i originally thought.
