### ISSUE TITLE
Cannot mmap Lazy Files

### ISSUE THREAD

**Issue by pfaffe** [emscripten-core/emscripten#16885]
Trying to mmap a file created with FS.createLazyFile produces an empty buffer. Reason is that the [mmap implementation](https://github.com/emscripten-core/emscripten/blob/15ce1b5a224dd4e9c90dcb5e87146ba6468737c8/src/library_memfs.js#L370) isn't aware of lazy files. Specifically, node.contents is of type LazyUint8Array in the linked code, which is not something that can be passed to TypedArray#set.

There needs to be a special case for lazy files to copy them chunk by chunk into the buffer.

**Comment by sbc100** [comment]
While I agree its worth fixing, does the code you are working on have a no-mmap-available fallback path?   Often code can be configured to avoid mmap completely since not all platforms support it.

This often works our better the emscripten target since its mmap support is completely fake with no real benefit over the malloc+fread.

**Comment by pfaffe** [comment]
I don't have a non-mmap path I'm afraid. I also don't own the mmap-using code, so I have little control over the call. Nontheless, the performance impact of the extra copy has so far been negligible on the greater scale of things!
