### ISSUE TITLE
 Out of memory: wasm memory in 32-bit chrome 

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#16955]
in 32-bit chrome, there is an error :
`Decoder.js:1 Uncaught (in promise) RuntimeError: abort(RangeError: WebAssembly.instantiate(): Out of memory: wasm memory). Build with -s ASSERTIONS=1 for more info.`

And it is no error in 64-bit chrome ?

**Comment by kripken** [comment]
This is likely because the 32-bit browser can't allocate the memory that the wasm module needs. On 32-bit it needs that amount of free memory and also it needs to be one contiguous chunk of memory, which can be hard as memory tends to fragment over time. On 64-bit this is not an issue (due to the huge virtual address space possible with 64-bit pointers).

Not much you can do about this, except to try to allocate a smaller memory.
