### ISSUE TITLE
uname inaccurately reports Emscripten version

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#16977]
It would be useful if `uname` reported the version of Emscripten:
https://github.com/emscripten-core/emscripten/blob/c1752359ec4f5183e9eee7ea68d3ce84599d1d1e/system/lib/libc/emscripten_syscall_stubs.c#L54

**Comment by hoodmane** [comment]
Or if #15917 is resolved, then `utsname->release` could be updated whenever there is an ABI break.

**Comment by sbc100** [comment]
I agree it might be nice to do this, but can you explain how it would be useful to you?

With emscripten you have to recompile your app on each upgrade so that compile time version found in `emscripten/version.h` will always match anyway.. so there is no need to call uname to find out of the version.  Unlike with a normal UNIX there is no way to take a pre-compiled program and run it on a different version of emscripten.. since the "kernel" and the program are essentially embedded together into a single object by the linker.
