### ISSUE TITLE
emscripten pulls outdated zlib with a critical bug

### ISSUE THREAD

**Issue by Laguna1989** [emscripten-core/emscripten#17592]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
laguna@DESKTOP-CM16HIU:~/emsdk$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.18 (d5ca9bba6513763d5bdddbd0efff759332bd85d7)
clang version 16.0.0 (https://github.com/llvm/llvm-project 48129cf0ed5053ed3fdf4f928180635e84892614)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/laguna/emsdk/upstream/bin
```

**Failing command line in full:**
For a webassembly project that uses SDL2 (and others) emscripten pulls zlib 1.2.11. This version is outdated and contains a critical bug that allows for remote code execution.
```
ports:INFO: retrieving port: zlib from https://storage.googleapis.com/webassembly/emscripten-ports/zlib-1.2.11.zip
ports:INFO: unpacking port: zlib
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libz.a.
```

Please find more info [on the zlib website](https://www.zlib.net/) about the bug.

It seems that [this repository](https://github.com/emscripten-ports/zlib) is not maintained anymore and I don't know who maintains the actual zlib version.

**Comment by sbc100** [comment]
We just use the zlib archive directly zlib.org.. we just happen to mirror it onto google storage for convenience and stability.

It should be easy to update to the latest version.  I'll take a look.

Aside: Bare in mind that security issues in emscripten libraries are generally less critical than in native code for a variety of reasons.  The main two being that (a) many exploits are simply not possible when running under wasm (b) Even for those exploits that are possible in the wasm world the damage a potential exploit can do is normally very limited compared to that native contacted because the code is running inside the wasm sandbox and is severely limited in the functions it can call.
