### ISSUE TITLE
cwrap returns undefined in certain scenarios, contradicting documentation

### ISSUE THREAD

**Issue by kg** [emscripten-core/emscripten#17812]
**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.12 (38d1292ba2f5b4a7c8518931f5ae6f97ef0f6827)
clang version 15.0.0 (https://github.com/llvm/llvm-project d58cc0839ee5935e649dbbc18c898a8e4bcd6724)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/kate/Projects/dotnet-runtime-wasm/src/mono/wasm/emsdk/upstream/bin
```

**Failing command line in full:**
n/a

**Full link command and output with `-v` appended:**
n/a

The implementation of `cwrap` can return `undefined` instead of a callable function if the signature is all `number`s because it returns the result of `getCFunc` directly. While turning on `ASSERTIONS` will cause it to assert in this scenario, the docs say cwrap will always return `A JavaScript function that can be used for running the C function.`, and it does for signatures containing `string` since it returns a wrapper that will invoke ccall.

**Comment by kripken** [comment]
Reading the code, yes, it looks like when assertions are disabled we have a fast path in `cwrap`. If the function being wrapped does not exist, we return undefined if its signature looks optimizable, and if it doesn't look optimizable we return a callable function that will error when later called (since the target function does not exist). That does seem somewhat confusing.

I'm not sure it's worth adding code for error handling in the non-assertions case. When assertions are disabled, we try to reduce code size by avoiding guards for incorrect API usages like this (wrapping a function that doesn't exist). Either adding an error check, or adding a wrapper function (just to "normalize" the output so it's always a function, and never undefined) would increase size.

So my inclination here is to update the docs. I opened #17833 for that now. But I'm open to other suggestions for what to do here.

**Comment by kg** [comment]
I think a docs update is fine, anyone at risk of a missing function who wants to handle it can check - it was just surprising that it was possible at all. I ran into it while troubleshooting something and it was a red herring.
