### ISSUE TITLE
Memory leak on exception catching disabled

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#17968]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.17 (fbc532773d84d2bd7da876275671970e792ad1cd)
clang version 15.0.0 (https://github.com/llvm/llvm-project 17e4c217b66305e60657a48f10fe3c428c2fe4d2)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/apple/AcroJS/emsdk/upstream/bin
```

**Failing command line in full:**
```sh
 em++ -sDISABLE_EXCEPTION_CATCHING=1  a.cpp -o a.html
```

Below is the sample program:
```cpp
#include <iostream>

class A {
    public:
        A() {
            std::cout << "Constructing a" << std::endl;
        }
        ~A() {
            std::cout << "Destroying a" << std::endl;
        }
};

int main() {
    A a;
    throw 1;
    return 0;
}
```

Compiling this program with exception catching disabled and running it doesn't call its destructor. OTOH, if I compile it with exception catching enabled or wasm exception destructor is called as excepted. Is this the expected behaviour ? Wouldn't it will cause memory leak in exception catching disabled builds ?

**Comment by sbc100** [comment]
Yes, I believe that is the expected behaviour.  When exception catching is disabled we can assume that no exception is ever caught and that the program can never recover or continue.  In this case, throwing and exception is the same as `abort()` .. in which case no destructors are run.    It also allows for a more optimal program which is why its the default in emscripten.

**Comment by ravisumit33** [comment]
Thanks. Got it 🙂
