### ISSUE TITLE
Couple of flaky pthread tests on Firefox

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#18307]
I'm commonly seeing these 5 tests in particular failing on the CI in Firefox, and working after couple of attempts:

- test_pthread_sbrk 
- test_pthread_safe_stack 
- test_pthread_run_script 
- test_pthread_run_on_main_thread_flood 
- test_pthread_run_on_main_thread 

Here's an example log from recently seen failures (attaching as a file because I'm not sure about retention duration on CircleCI):
[log.txt](https://github.com/emscripten-core/emscripten/files/10142768/log.txt)

**Comment by RReverser** [comment]
OTOH I wonder if it's something that would be accidentally fixed by my changes in https://github.com/emscripten-core/emscripten/pull/18305.

One of the things I noticed and had to do there is manually start executing messages only after Module variable has been definitely assigned. It became a pretty noticeable issue in Firefox due to my changes to `postMessage` scheduling in the same PR, but now I wonder if there was always a racy issue, just less noticeable before.

A bit suspiciously, that PR also passed on the first run, but it still might be all a coincidence...

**Comment by RReverser** [comment]
Although no, that should've affected only modularize builds, and those tests are not it...

**Comment by RReverser** [comment]
> OTOH I wonder if it's something that would be accidentally fixed by my changes in #18305.

Just tested that theory by extracting those changes separately and, no, that doesn't help. Must be some other reason, although I don't see what's common between specifically those 5 tests.

**Comment by kleisauke** [comment]
Looking at the log, I think(?) that `test_pthread_run_on_main_thread` makes the whole browser unresponsive, causing subsequent tests to fail as well. Which explains that this is only a issue on Firefox, because on Chrome this test is already disabled (see commit 6ea085c6a85484a2cc0e66324f4564a9c54efb37).

As for a possible fix, perhaps commit https://github.com/emscripten-core/emscripten/pull/13007/commits/25a6cb2bb57a8cd25eef62230b108d50e82a707c in PR #13007 would fix this? Just a wild guess, it's based upon that this test makes heavily use of those helpers in ` <emscripten/threading.h>`, which would end-up calling `emscripten_wait_for_call_v()` in most cases.

That PR also includes some other goodies, such as commit https://github.com/emscripten-core/emscripten/pull/13007/commits/fd05b3645c815fd180ff855dc911200a4a636e0f. Sorry for not further upstreaming those commits, I sometimes have limited spare-time. :(

**Comment by kleisauke** [comment]
... as always, I could certainly use some help in upstreaming these patches. FWIW, I'm currently tracking this in the "Upstream patches" card at https://github.com/users/kleisauke/projects/1.

**Comment by kleisauke** [comment]
> As for a possible fix, perhaps commit [25a6cb2](https://github.com/emscripten-core/emscripten/commit/25a6cb2bb57a8cd25eef62230b108d50e82a707c) in PR #13007 would fix this?

Though, I think the intention of PR #15681 was to deprecate `emscripten_wait_for_call_v()` in favor of the proposed APIs mentioned in comment https://github.com/emscripten-core/emscripten/pull/15705#issuecomment-985884887.

**Comment by RReverser** [comment]
> As for a possible fix, perhaps commit [25a6cb2](https://github.com/emscripten-core/emscripten/commit/25a6cb2bb57a8cd25eef62230b108d50e82a707c) in PR #13007 would fix this?

> Though, I think the intention of PR #15681 was to deprecate `emscripten_wait_for_call_v()` in favor of the proposed APIs mentioned in comment [#15705 (comment)](https://github.com/emscripten-core/emscripten/pull/15705#issuecomment-985884887).

Ok I'm not familiar with that side of the things so tagging @tlively.

**Comment by tlively** [comment]
`emscripten_wait_for_call_v` should be implemented in terms of the new proxying API (with the system proxying queue), so it's not inherently bad to use, but should only be used for things that act like signal handlers. Looking at the `test_pthread_run_on_main_thread` test, it looks like it's calling printf, which internally acquires locks. My guess is that printfs are racing, and when one acquires the lock, the system proxying queue is pumped and another starts running in the middle of the first, so the main thread is deadlocking on itself.

**Comment by RReverser** [comment]
Looks like `test_pthread_proxying_cpp` is also flaky, probably for similar reasons. A bit hard to tell as that test seems to combine several in one file.
