### ISSUE TITLE
Poppler demo is down

### ISSUE THREAD

**Issue by coolwanglu** [emscripten-core/emscripten#1841]
https://github.com/kripken/emscripten/wiki#utilities

http://syntensity.com/static/poppler.html

**Comment by tianmuji** [comment]
@coolwanglu @kripken any suggestion to rebuild poppler using emscripten?

**Comment by sbc100** [comment]
Its looks like a fairly straight forward autoconf-base project.  We build it as part of our test suite.  See `get_poppler_library` in `test/common.py`

**Comment by tianmuji** [comment]
well I follow you instruction and got following error

FreeType build system -- automatic system detection

The following settings are used:

  platform                    unix
  compiler                    /Users/yujie_wu/Documents/emscripten-main/emcc
  configuration directory     ./builds/unix
  configuration rules         ./builds/unix/unix.mk

If this does not correspond to your system or settings please remove the file
`config.mk' from this directory then read the INSTALL file for help.

Otherwise, simply type `/Library/Developer/CommandLineTools/usr/bin/make' again to build the library,
or `/Library/Developer/CommandLineTools/usr/bin/make refdoc' to build the API reference (the latter needs python).

Generating modules list in ./objs/ftmodule.h...
* module: truetype  (Windows/Mac font files with extension *.ttf or *.ttc)
* module: type1     (Postscript font files with extension *.pfa or *.pfb)
* module: cff       (OpenType fonts with extension *.otf)
* module: cid       (Postscript CID-keyed fonts, no known extension)
* module: pfr       (PFR/TrueDoc font files with extension *.pfr)
* module: type42    (Type 42 font files with no known extension)
* module: winfnt    (Windows bitmap fonts with extension *.fnt or *.fon)
* module: pcf       (pcf bitmap fonts)
* module: bdf       (bdf bitmap fonts)
* module: sfnt      (helper module for TrueType & OpenType formats)
* module: autofit   (automatic hinting module)
* module: pshinter  (Postscript hinter module)
* module: raster    (monochrome bitmap renderer)
* module: smooth    (anti-aliased bitmap renderer)
* module: smooth    (anti-aliased bitmap renderer for LCDs)
* module: smooth    (anti-aliased bitmap renderer for vertical LCDs)
* module: psaux     (Postscript Type 1 & Type 2 helper module)
* module: psnames   (Postscript & Unicode Glyph name handling)
done.
cd builds/unix; ./configure  '--disable-shared' '--without-zlib'
checking build system type... 
-- end configure stdout --
-- configure stderr --
configure: sh ./configure --disable-shared --without-zlib
Invalid configuration `aarch64-apple-darwin21.6.0': machine `aarch64-apple' not recognized
configure: error: /bin/sh ./config.sub aarch64-apple-darwin21.6.0 failed
make: *** [setup] Error 1
emconfigure: error: 'sh ./configure --disable-shared --without-zlib' failed (returned 2)

-- end configure stderr --


I referenced to freetype repo at gitlab 
https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/builds/mac/README?ref_type=heads

I found the platform unix is correct but platform not supported

Could you please help me figure out the problem?
Many thanks
