### ISSUE TITLE
emscripten_memcpy_big when bulk-memory enabled

### ISSUE THREAD

**Issue by miwelc** [emscripten-core/emscripten#18414]
I've seen in the emitted JS code that `emscripten_memcpy_big` is being defined even if `-mbulk-memory` is enabled.
Is this the expected behavior?

**Comment by RReverser** [comment]
Running into this as well, looks like this issue might've slipped under the radar?

**Comment by sbc100** [comment]
I don't see anything in the code that would stop `emscripten_memcpy_big` from being used.   What makes you think this is not expected behaviour?   Are you expecting an explict call to the `memory.copy` builtin here:
https://github.com/emscripten-core/emscripten/blob/168dafbfe4521a70096e4aadb3a0beb3813ffb15/system/lib/libc/emscripten_memcpy.c#L37-L42

One problem with doing that is that we probably wouldn't want to build a specific / separate version of libc when bulk-memory is enabled.

**Comment by RReverser** [comment]
> What makes you think this is not expected behaviour?

Nothing except that it _feels_ like it should be, sort of like `-fwasm-exceptions` reduces overhead by replacing exception imports from JS with native Wasm functionality.

> Are you expecting an explict call to the `memory.copy` builtin here:

Yeah.

**Comment by RReverser** [comment]
Looks like this was implemented in https://github.com/emscripten-core/emscripten/pull/19128.
