### ISSUE TITLE
Parallel_for with static number of workers

### ISSUE THREAD

**Issue by VolodymyrShchyhelsky** [emscripten-core/emscripten#18433]
I am trying to implement parallel_for in emscripten, that look similar to this code:
`
std::vector<std::thread> my_threads;
`
`
for(unsigned i = 0; i < nb_threads; ++i) {
`
`   my_threads.push_back(std::thread(functor, i));
`
`
}
`
`
std::for_each(my_threads.begin(), my_threads.end(), std::mem_fn(&std::thread::join));
`

I need to use PTHREAD_POOL_SIZE=navigator.hardwareConcurrency, because dynamic thread pool is not suitable for me

The problem is: if nb_threads are greater than the count of free workers it will very probably result in deadlock
My idea was to set nb_threads = EM_ASM_INT(return PThread.unusedWorkers.length) - 1; 
but if we run parallel_for inside worker PThread.unusedWorkers.length equal to 0.
How will better to define  nb_threads variable?

**Comment by sbc100** [comment]
You would need to use `MAIN_THREAD_EM_ASM` so that it runs on the main thread.  All the JS state regarding threads is stored on the main thread.

BTW, you only need to worry about the pool size of you main threads is blocked on something.  If your main threads is returning the event loop and not blocking it should be fine to start new threads from a background thread.

**Comment by sbc100** [comment]
In other words I think maybe you don't need to worry about `nb_threads` being less than the number of free threads when you are running this code on the main thread itself.

**Comment by VolodymyrShchyhelsky** [comment]
Huge thanks!
