### ISSUE TITLE
Calling an `EM_JS` function in a catch clause doesn't work with `MAIN_MODULE`

### ISSUE THREAD

**Issue by kleisauke** [emscripten-core/emscripten#18494]
Given this example program:
```c++
#include <stdexcept>

#include <emscripten/emscripten.h>

EM_JS(void, throw_error_js, (const char *msg),
      { throw new Error(UTF8ToString(msg)); });

int main() {
    try {
        throw std::invalid_argument("invalid_argument");
    } catch (const std::invalid_argument &e) {
        throw_error_js(e.what());
    } catch (...) {
        __builtin_trap();  // unreachable
    }
}
```

Fails at runtime when linking with `-sMAIN_MODULE`:
```console
$ em++ -sMAIN_MODULE -fexceptions test.cpp -o test.js
$ node test.js
/home/kleisauke/test.js:144
      throw ex;
      ^

ReferenceError: _throw_error_js is not defined
    at Object.<anonymous> (/home/kleisauke/test.js:30588:21)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.1
```

I was expecting it would throw "invalid_argument", i.e.:
```console
$ em++ -fexceptions test.cpp -o test.js
$ node test.js
/home/kleisauke/test.js:144
      throw ex;
      ^

Error: invalid_argument
    at throw_error_js (/home/kleisauke/test.js:1237:38)
    at invoke_vi (/home/kleisauke/test.js:1850:29)
    at wasm://wasm/000183ee:wasm-function[21]:0x75b
    at wasm://wasm/000183ee:wasm-function[23]:0x8c9
    at /home/kleisauke/test.js:1048:22
    at callMain (/home/kleisauke/test.js:2320:15)
    at doRun (/home/kleisauke/test.js:2374:23)
    at run (/home/kleisauke/test.js:2389:5)
    at runCaller (/home/kleisauke/test.js:2305:19)
    at removeRunDependency (/home/kleisauke/test.js:951:7)

Node.js v18.12.1
```

Tested with Emscripten v3.1.29 and the latest tip-of-tree build.

**Comment by sbc100** [comment]
I tracked down the issue.  I had to make a couple of fixes direct, but in the end found a root problem is when EM_JS functions are only imported by address, in dynamic linking mode, don't have signature.. since they are imported as `GOT.func.foo` globals, and not as functions... annoying.   I'm not sure what we can do about that. 

I guess we can recommend that folks also import the function directly to fix the issue?

**Comment by kleisauke** [comment]
> I guess we can recommend that folks also import the function directly to fix the issue?

Somehow I couldn't make this work with `--js-library` either. Let me know if you want a separate issue for that.

PR #18535 is an alternative to avoid such code.

**Comment by sbc100** [comment]
> > I guess we can recommend that folks also import the function directly to fix the issue?
> 
> Somehow I couldn't make this work with `--js-library` either. Let me know if you want a separate issue for that.

I'm not sure I understand, but yes please file another issue for that. 

> 
> PR #18535 is an alternative to avoid such code.

**Comment by sbc100** [comment]
> Ah, sorry it does seem to work, I forgot to specify `throw_error_js__sig: 'vi',` and `-sASSERTIONS=0` would throw a suspicious error if you forgot to specify that `__sig`.

I see.. sounds like that is WAI, and the ASSERTIONS build points nicely to the solution.

Shame we really doing have a good solution for the EM_JS case..

**Comment by sbc100** [comment]
The problem is that EM_JS function don't have any way to express their `__sig`.    Normally this isn't a problem since the wasm module will import the function, meaning the signature can be found in the wasm module itself.

Simply re-implementing EM_JS on top of `--js-library` won't help unless you add some kind of new syntax that allows the resulting library JS file to include the `__sig` somehow.  But any such new syntax could be used today without the JS library layering.
