### ISSUE TITLE
New threads should receive DSO module via postMessage

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#18552]
Right now we compile side modules on each thread but for module that have already been loaded at thread creation time this is not necessary.

**Comment by dschuff** [comment]
I guess the way this would work is that whenever a thread compiles a module it should postMessage that module to the other threads before loading (would this have to bounce through the main thread?). The onmessage handler would just stash the module in a data struct somewhere. When dlopen runs, it would check whether the module has already been received from another thread.
This would not help threads which just run in an infinite loop and never return to the event loop (they can still load the code because sync XHR and sync loading is allowed on workers, but they have no way to receive modules from other threads).

**Comment by sbc100** [comment]
I'm working on this change now, and I'm trying to figure out how best to test it.  Its tricky because its supposed to be un-observable to the user when a given pthread loads the module.

Any ideas for how to write this kind of test?
