### ISSUE TITLE
Events and callbacks not happening for Javascript library

### ISSUE THREAD

**Issue by goldwaving** [emscripten-core/emscripten#18809]
I have a strange problem where events are not happening at all.  In the code below, the onopen event does not occur, despite a connection (server receives a connection).  Also the interval callback never occurs.   The only thing logged is "Started".

The code is running in a separate thread from the browser's main thread.  Are threads not able to send events?

```
mergeInto(LibraryManager.library,
{
	$net:
	{
		socket: null;
	},

	createSocket__deps: [ '$net' ],
	createSocket: function( url, protocol )
	{
		net.socket = new WebSocket( 'ws://' + UTF8ToString( url ), UTF8ToString( protocol ) );
		net.socket.onopen = () => { console.log( "Connected" ); }
		setInterval( ()=> { console.log( "Interval" ); }, 1000 ) );
		console.log( "Started" );
	}
});
```

**Comment by goldwaving** [comment]
If I queue the function to the browser thread, the function works as expected.  If I use MAIN_THREAD_EM_ASM from C++ to create an interval, that works.  Creating the interval in the js library does not work.  Obviously there is something about how theads work in Emscripten that I am not understanding.  In the code below, only T0 occurs,  T1 and T2 never occur. Why?

```
// C++ called from thread
void create()
{
    MAIN_THREAD_EM_ASM( setInterval( ()=>{ console.log( "T0" ); }, 1000 ) );
    EM_ASM( setInterval( ()=>{ console.log( "T1" ); }, 1000 ) );
    jscreate();
}

// js library
mergeInto(LibraryManager.library,
{
   jscreate: function () { setInterval( ()=> { console.log( "T2" ); }, 1000 ); }
});
```

**Comment by sbc100** [comment]
Are you returning from your threads main entry point?   You can't get any events from the event loop unless you do.  

If you are returning then perhaps your thread is exiting.  In order to keep a thread alive when you return from the entry point you can either do `emscripten_exit_with_live_runtime()` or you can call `emscripten_runtime_keepalive_push()` before returning.  Or you can can do `{{{ runtimeKeepalivePush() }}}` in your library JS code.   

See `emscripten_set_interval` in `src/library_eventloop.js` for an example of code that keeps the runtime alive long enough to get a callback.  Also look at `safeSetTimeout`.

**Comment by goldwaving** [comment]
You are exactly right.  The thread contains a loop that does not exit until much later, so the events and intervals cannot occur on that thread.
