### ISSUE TITLE
C pre-processor macro to check if AudioWorklets is enabled

### ISSUE THREAD

**Issue by mackron** [emscripten-core/emscripten#18848]
I'm experimenting with adding support for AudioWorklets to my audio library, but I've got what might be a bit of a unique situation. My library is designed to be added to a project's source tree directly so I need it to Just Work in as many build environments as possible, including older versions of Emscripten which don't support the new AudioWorklets feature.

I was wondering if there's a way to detect if `-sAUDIO_WORKLET=1` has been specified on the command line so my library can detect it and enable a fallback path if it's not specified? I was hoping for something like this:

```c
#if defined(EMSCRIPTEN_ENABLE_AUDIO_WORKLET)
    // Use AudioWorklets.
#else
    // Fall back to legacy ScriptProcessorNode implementation.
#endif
```

Is there anything I can use to detect this? I'm aware of `__EMSCRIPTEN_major__`, etc., but I don't want to force the use of AudioWorklets based on the compiler version - I'd rather have a way to check if `-sAUDIO_WORKLET=1` has been explicitly specified on the command line.

**Comment by sbc100** [comment]
We don't tend to map setting to buildin macros like that.   There are several reasons for that, but to give one of them, may settings (including `AUDIO_WORKLET`) are link-time flags, so should not be specified at compile time.    This means that we  wouldn't be able to add such macros because we don't know if `AUDIO_WORKLET` is going to be used until link time.

In general, it should be simple enough to just add `-DAUDIO_WORKLET` to CFLAGS when you add `-sAUDIO_WORKLET` to your LDFLAGS.

**Comment by mackron** [comment]
Thanks. Yes, I had also thought of that, but I guess I was bit hesitant because it's just yet another compile flag that needs to be added for every single one of my users since my library does not ship with build scripts. I was just hoping there might be a macro that's already defined when `-sAUDIO_WORKLET` is specified which I could make use of just to simplify it a bit. Will go ahead and close this one. Thanks!
