### ISSUE TITLE
Wrong clang version

### ISSUE THREAD

**Issue by HakonHarnes** [emscripten-core/emscripten#18951]
Emscripten reports clang version 17.0.0. AFAIK the latest clang version is 16 (https://github.com/llvm/llvm-project/releases)

```
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.32 (eab98adf462c39f3c31d348331c4830bcaa36949)
clang version 17.0.0 (https://github.com/llvm/llvm-project df82394e7a2d06506718cafa347bf7827c79fc4f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/lib/emsdk/upstream/bin
```

**Comment by kripken** [comment]
Emscripten uses very recent clang, and the development version is now marked as 17, even though 17 is not released yet.

We do this because we sometimes need very recent updates in clang's support for wasm, and don't want to wait a full release cycle. So what we do is we pull latest clang continuously in our infrastructure and use it (assuming tests pass).

**Comment by HakonHarnes** [comment]
Thanks for the clarification. I'm closing this.
