### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by pnacht** [emscripten-core/emscripten#19037]
[GitHub recommends](https://docs.github.com/en/code-security/getting-started/securing-your-repository#setting-a-security-policy) that projects have a Security Policy (SECURITY.md). This is a simple document that explains how the project wishes to receive and handle responsible disclosure of potential vulnerabilities.

There are a few ways to receive such disclosures:
- have an email or website available to receive such reports; and/or
- use [GitHub's private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) feature (in beta)

If you're interested in GitHub's reporting system, it must be activated for the repository:
1. Open the repo's settings
2. Click on [Code security & analysis](https://github.com/emscripten-core/emscripten/settings/security_analysis)
3. Click "Enable" for "Private vulnerability reporting (Beta)"

I'll send a PR with a draft policy along with this issue.

**Comment by pnacht** [comment]
No particular reason. I just realized I forgot to add a disclosure in the issue (edited now), but I'm a Google employee working with the [Open Source Security Foundation](https://www.openssf.org) (OpenSSF) to improve the supply-chain security of important open source projects.

Emscripten fits that bill, and this was just a small thing I noticed that could be done.

You're much better positioned to know whether this is a valuable or worthwhile contribution, so feel free to close this issue and associated PR. But may I just ask why you don't think emscripten needs this? Is it because it's a compiler?

**Comment by sbc100** [comment]
Firstly I feel like maybe its worth while to push back (at least little bit) on github policies like this.    Just because we host our code on github doesn't mean we need to follow all their conventions.   e.g. if we switched to gitlab or bitbucket would we then need to convert the contents of our repo to conform to their policies.  

Secondly, yes, since emscripten itself is a compiler and its input is generally trusted, and because its output is run in the v8/chrome sandbox, I think we can/do have a different security posture to other open source projects.    For example, I'm not sure its realistic to expect emscripten to be secure against malicious input.    There are various way in which the input to the compiler can already run arbitrary code on the compiling machine.

If we did want to make emscripten secure against malicious input that would be fairly big undertaking.  For example, I'm not sure that clang and llvm (on which we build) have this goal?  

Perhaps it would help to know what type threats we are talking out.   I see two major types, but maybe you are imagining more:

1. Attacks that target the emscripten compiler user, via malicious input, or supply chain attacks?
2. Attacks that target vulnerabilities in emscripten-generated output (i.e. when running in the browser and, maybe node?)

I'm worry that trying to protect against (1) would be pretty hard.

**Comment by pnacht** [comment]
> Firstly I feel like maybe its worth while to push back (at least little bit) on github policies like this. Just because we host our code on github doesn't mean we need to follow all their conventions. e.g. if we switched to gitlab or bitbucket would we then need to convert the contents of our repo to conform to their policies.

Well, I'd argue that having a security policy should preferably be portable. That's why the most common method for security reporting is an email or an external website. The GitHub private reporting feature is merely an additional suggestion I'd be happy to remove.

> Secondly, yes, since emscripten itself is a compiler and its input is generally trusted, and because its output is run in the v8/chrome sandbox, I think we can/do have a different security posture to other open source projects. For example, I'm not sure its realistic to expect emscripten to be secure against malicious input.

Once again, I agree. Malicious input isn't emscripten's problem, it's the developer's.

> Perhaps it would help to know what type threats we are talking out. I see two major types, but maybe you are imagining more:
> 
> 1. Attacks that target the emscripten compiler user, via malicious input, or supply chain attacks?
> 2. Attacks that target vulnerabilities in emscripten-generated output (i.e. when running in the browser and, maybe node?)
> 
> I'm worry that trying to protect against (1) would be pretty hard.

Yeah, in emscripten's case the main "risk" I see is a bug in the compiler that somehow makes binaries it generates vulnerable in some fashion (I believe that's your (2)). Something like an error in how memory allocation is handled by the compiler that could be exploited by a malicious end-user. By which I mean: 

1. emscripten compiles foo.wasm.
2. That binary is used at foo.com to handle some sort of end-user input.
3. Input that should be okay actually leads to malicious behavior (stealing user credentials or something) because of a bug in emscripten.

Now, I'm no expert in emscripten or the v8/chrome sandbox, so if you tell me such a scenario is implausible or downright wrong, I'll close the issue and bid you thank you and farewell. 😁

**Comment by kripken** [comment]
That does sound like a plausible concern to me. And I agree with @sbc100 that LLVM and clang are probably the best points of comparison for us. That is, LLVM is a far larger compiler project than us, and there's a good chance we should be doing the same.

Looks like they have a minimal security file:

https://github.com/llvm/llvm-project/blob/main/SECURITY.md

That points to

https://llvm.org/docs/Security.html#how-to-report-a-security-issue

which basically says to open a bug either on github or on chromium. I guess chromium is used because bug reports can be private? Anyhow, perhaps we can suggest the same, that is, people could open a security bug on V8 and say it is for Emscripten. We sometimes have cross-over bugs anyhow with V8, and I imagine this would be rare, so I don't expect it would be a burden.

**Comment by kripken** [comment]
It's over here: https://bugs.chromium.org/p/v8/issues/list

**Comment by pnacht** [comment]
I've updated the PR. It now points to https://bugs.chromium.org/p/chromium/issues/entry?template=Security%20Bug. This isn't in the V8 section, but when I tried to post a Security issue on V8, I was told to post it on the general Chromium page.

![Screenshot 2023-03-30 at 16 39 52](https://user-images.githubusercontent.com/15221358/228946393-cf6fa468-0d8a-4498-ac22-f8b7028d0db5.png)

**Comment by kripken** [comment]
I wasn't aware of that, interesting. Sounds good.
