### ISSUE TITLE
Synchronizing between ui thread and pthreads

### ISSUE THREAD

**Issue by StillWaters77** [emscripten-core/emscripten#19545]
Lets say we have a certain state, that the worker thread needs to work with asynchronously. From our ui we want to manipulate this state so that we can interact with the worker thread.
How do i share the state between those two? I assume, since the worker thread could be running in a web worker, no variables are shared.
Also i would need to somehow wake the worker thread up, e.g. by resolving a promise, signalling that the state has changed and the worker thread can perform specific actions.
If the state is really shared and this is not solved by some sort of message passing, i think we would also need to mutual exclude both when interacting with the state.

I read that "Pthreads have a per-thread incoming proxy message queue...". Maybe this sounds like a solution to my problem? But i struggle to find the documentation on that

**Comment by sbc100** [comment]
Assuming you are using pthreads, then you want to keep all your shared state in the shared linear memory.  Than you can use all the normal pthread primitives to synchronize and communicate (e.g. pthread_cond_notify, pthread_cond_wait, etc).

If you want you can also use the work queue primitives that we built in emscripten to send work to threads: https://github.com/emscripten-core/emscripten/blob/main/system/include/emscripten/proxying.h.  However, those are not necessary and you are free to use the lower level pthread API, or the C11 thread API or the C++11 thread API.

**Comment by StillWaters77** [comment]
Could you explain this a little bit further or guide me to the documentation for the "shared linear memory"?
My scenario is that i am using Promises. One thread waits on those promises and another thread (e.g. the ui thread) resolves those promises to "unblock" the worker thread. I didnt find a way to put promises into the shared memory, as i can seemingly only really work with them in javascript code (EM_JS, EM_ASYNC_JS)

**Comment by sbc100** [comment]
IIUC there two main options that you have:

1. Have the worker thread block using some pthread primitive
2. Have the worker thread return the even loop and send it work using the `proxying.h` API.

In

In the first scenario you would have the worker thread block using something like `pthread_cond_wait`.   Then when UI thread wants to resolve the promise is can call into native code to wait up the worker using `pthread_cond_signal`.

In the second scenario the worker thread would return the event loop (by calling `exit_with_live_runtime`) and then the UI thread could send it work ("unblock" it as you say) using APIs in `emscripten/proxying.h`.  

You can't actually share promises between threads (since they as JS objects which are not shareable).

Adding @tlively in case they have a better way to explain things..
