### ISSUE TITLE
Dwarf data with O3 optimization

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#19846]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.35 (a90c5abb489c516f59c0d16864d953d4bedd37da)
clang version 17.0.0 (https://github.com/llvm/llvm-project 6865cff8ea8b07d9f2385fd92cecb422404f0f35)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/apple/emsdk/upstream/bin
```

I am working on parsing dwarf which I got from `llvm-dwarfdump`. I want to have release binary (compiled with `-O3`) and dwarf data in one go. Currently, first I build with `-O3` to have release build and then with `-g` to have dwarf data. If i use both `-g` and `-O3` flags at the same time I get warning that some optimizations cannot run as dwarf data is requested, which I do not want. I also used `-O3` and `-gseparate-dwarf` but this doesn't produce any debug data (is it a bug?). Can we use `-O3` and `-gseparate-dwarf` together to have a release binary with full optimizations(as with `-O3` alone) and other separate dwarf output at the same time?

**Comment by ravisumit33** [comment]
@dschuff Your thoughts on this?

**Comment by dschuff** [comment]
Regarding the warning: Currently there are some limitations to the DWARF support in Binaryen (the component that optimizes wasm post-link). When it optimizes (e.g. by moving code around) it tries to preserve the DWARF info by updating its pointers into the code as it moves. But a few optimizations (e.g. local variable coalescing) would require more significant rewriting of the DWARF info than Binaryen is capable of. Fixing that would be a large project that we haven't been able to prioritize. So there's currently no way to work around that. The number of optimizations that are disabled isn't huge (in particular all of LLVM's optimizations still work) and most of Binaryen's optimizations affect size more than speed. So if you are using O3 and the size and performance of your program is acceptable, then you may be OK as is. (You can also compare O3 with and without DWARF to see how much difference it actually makes).
Also I'd be curious to hear what your use case is for parsing the DWARF (since it sounds like it's not for interactive debugging in the debugger?). If you just need line number information (e.g. for processing stack traces) you might be able to use source maps for the same purpose, and get all the optimizations.

If `-O3` and `-gseparate-dwarf` don't work together, that sounds like a bug we should fix. Can you provide steps to reproduce?

**Comment by ravisumit33** [comment]
Reproduction steps are below:

1. Compile a hello-world program with `-O3 -gseparate-dwarf` to get debug and release wasm.
2. Use `llvm-dwarfdump` to check dwarf content of debug wasm.
3. No dwarf info found.


We have a use case where we want to find out all function symbols used by code inside a given folder path. We plan to use that information with wasm-split as current way of spliting using profile guided way is infeasible for us.

**Comment by dschuff** [comment]
OK, I think the issue is that `-gseparate-dwarf` just says where to put the debug info (but not the level of debug info to generate). If you add `-g` (or another debug-level flag such oas`-gline-tables-only`) to `-O3 -gseparate-dwarf`, then you get full debug info in the side file.
Maybe this is a bug or unexpected behavior, but it does work if you do that.

**Comment by ravisumit33** [comment]
Got it. Thanks.
