### ISSUE TITLE
[wasm-split] Splitting with dynamic linking increases wasm size instead of decreasing

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#19930]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.35 (a90c
5abb489c516f59c0d16864d953d4bedd37da)
clang version 17.0.0 (https://github.com/llvm/llvm-project 6865cff8ea8b07d9f2385fd9
2cecb422404f0f35)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/apple/AcroJS/acrobatjs/AJS-emcc/3.1.35/emsdk/upstream/bin
```

I am trying to do module splitting with dynamic linking on. After split, primary split size is even greater than original wasm size. On inspection with `wasm-objdump`, it can be seen that `Export` section of primary module has increased in size a lot. So is the `Import` section of deferred module. On looking into the kind of functions exported, name of majority of functions exported is having pattern `<export-prefix>*`(e.g. `<export-prefix>a`, `<export-prefix>b`, etc.) where `export-prefix` is the cmd-line option for `wasm-split`. Doesn't this size increase defeat the purpose of module splitting altogether? Or is it that it doesn't work with dynamic linking properly?

**Comment by tlively** [comment]
This can happen if the secondary functions contain lots of calls to primary functions, since all those primary functions now need to be exported. Splitting out more functions could help not only by reducing the amount of code in the primary module, but also by reducing the number of primary functions called from secondary functions, thereby reducing the number of exports.

If your exports are already named e.g. `%a`, %b`, etc. then I don't think there's much else that can be done.

**Comment by ravisumit33** [comment]
@tlively What if the functions I want to split call many functions which are also called by functions in the primary module? This is the case of splitting code which is highly correlated not like the case of splitting independent code like 3rd party libraries. If we currently want to dynamic link a highly correlated piece of code, export section of both main and side modules grow in size extensively. Does this limitation also exist with module splitting? If yes, is module splitting just a form of dynamic linking without much developer intervention or there are some other benefits of it?

**Comment by tlively** [comment]
Every primary function called by a secondary function results in an export from the primary module and an import in the secondary module, as you've noted. In the other direction, every secondary function called by a primary function becomes an indirect call through the table, so it increases the size of the element segment in the secondary module and also adds a placeholder import in the primary module.

Overall module splitting is very similar to dynamic linking, but slightly more efficient because no relocation logic needs to run. It also lets you get lazy code loading without application changes, which is not currently possible with dynamic linking. On the other hand, dynamic linking gives you much more control over how the application is split.

**Comment by ravisumit33** [comment]
Got it. Thanks
