### ISSUE TITLE
function signature mismatch will be issued even with function type convert

### ISSUE THREAD

**Issue by versaloon** [emscripten-core/emscripten#19942]
Please include the following in your bug report:

**Version of emscripten/emsdk:**

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.44 (bec42dac7873903d09d713963e34020c22a8bd2d)
clang version 17.0.0 (https://github.com/llvm/llvm-project a8cbd27d1f238e104a5d5ca345d93bc1f4d4ab1f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: D:\chips\wasm\emsdk\upstream\bin

**Background**

For some old c standard, main function can accept more than 2 arguments. eg:
```c
int xxx_main(int argc, char *argv[], char *env[]);
```
Ofc, most main function in C has only 2 arguments.

In my OS, I will call the main entry with code below, and pass a 3rd argument as environment for the best compatibility:

```c
static void __vsf_linux_main_on_run(vsf_thread_cb_t *cb)
{
    ........

    char *argv[ctx->arg.argc + 1];
    if (ctx->arg.argv != NULL) {
        memcpy(argv, ctx->arg.argv, (ctx->arg.argc + 1) * sizeof(argv[0]));
    } else {
        argv[0] = NULL;
    }

    VSF_LINUX_ASSERT(ctx->entry != NULL);
    // CONVERT entry with 3rd argument(environment)
    thread->retval = ((int (*)(int, char **, char **))ctx->entry)(ctx->arg.argc, argv, process->__environ);

    vsf_linux_exit_process(thread->retval, false);
}
```

**Problem**

This works OK in most systems, even if actual main entry accept only 2 arguments, the 3rd one will simply be ignored.
For wasm, when run the wasm code, runtime error will be issued:
```
worker.js onmessage() captured an uncaught exception: RuntimeError: null function or function signature mismatch
RuntimeError: null function or function signature mismatch
    at __vsf_linux_main_on_run (wasm://wasm/00635a66:wasm-function[334]:0x26b29)
    at __vsf_thread_entry (wasm://wasm/00635a66:wasm-function[187]:0x12151)
    at __vsf_thread_host_thread (wasm://wasm/00635a66:wasm-function[186]:0x11fd6)
    at invoke_vi (D:\chips\wasm\vsf.demo\project\cmake\wasm\build\vsf_template.js:5207:29)
    at __vsf_arch_irq_entry (wasm://wasm/00635a66:wasm-function[532]:0x3fe3a)
    at Object.invokeEntryPoint (D:\chips\wasm\vsf.demo\project\cmake\wasm\build\vsf_template.js:4378:42)
    at handleMessage (D:\chips\wasm\vsf.demo\project\cmake\wasm\build\vsf_template.worker.js:154:35)
    at MessagePort.<anonymous> (D:\chips\wasm\vsf.demo\project\cmake\wasm\build\vsf_template.worker.js:24:38)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```

I think it's because normally, the main entry accepts 2 arguments, but I convert the prototype to accept a 3rd argument, which will trigger function signature mismatch error.

Is there any option/trick and work it around？

**Comment by sbc100** [comment]
;TLDR; I don't know of any easy solution to this.

Sadly this is one of the rough edges with WebAssembly and C.  Its very hard to us to make this "just  work" like it does in C.  This is because WebAssembly is fundamentally more strict about function signatures at runtime.   We go to a lot of effort make "main with no args" and "main with 2 args" work.   There are special handling in clang for this:  https://github.com/llvm/llvm-project/blob/1416614c5147dad8415bd014740ddf59e9f171f2/clang/lib/AST/Mangle.cpp#L181-L184.

And in if you grep for __main_argc_argv in emscripten you will see how much effort we go to try to make this just work.   I would imagine that adding a 3rd variant for the 3 argument main would be even harder.

My advise to you would be to always call main with 2 arguments when `#if __EMSCRIPTEN__` and then try to patch any programs that actually use the 3 argument main..  in practice I don't know if I've ever seen any real world programs that depend on the 3rd argument, and I imagine it would be faily easy to to replace the use of the third argument with the `environ` C global?

**Comment by versaloon** [comment]
Yes, fix the application code is simple.
OK, I will add a workaround as you said, thank you.
