### ISSUE TITLE
[EH] rethrowing current exception from catch lead to loss of callstack

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#20301]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.35 (a90c5abb489c516f59c0d16864d953d4bedd37da)
clang version 17.0.0 (https://github.com/llvm/llvm-project 6865cff8ea8b07d9f2385fd92cecb422404f0f35)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: ~/emsdk/upstream/bin
```

**test.cpp**
```cpp
#include <emscripten.h>
#include <exception>

void fun2() {
    throw "error";
}

void  EMSCRIPTEN_KEEPALIVE fun1() {
    try {
        fun2();
    } catch(...) {
        auto e = std::current_exception();
        std::rethrow_exception(e);
    }
}
```

Above program is built with `-sEXCEPTION_STACK_TRACES=1`. `fun1` is exported on `Module` & is called from js side as below:

**test.js**
```js
 try {
    console.log(Module._fun1());
  } catch (e) {
    console.log(e.stack);
  }
```

Ideally, full callstack including both `fun2` & `fun1` should get printed. However, in Wasm EH no callstack is obtained while in Emscripten EH below callstack is obtained:
```
char const*
    at ___resumeException (http://localhost:8000/build/test.js:1043:25)
    at fun1 (http://localhost:8000/build/test.wasm:wasm-function[25]:0xb4d)
    at Module._fun1 (http://localhost:8000/build/test.js:1273:69)
```

Both of these scenarios are wrong and should print the actual callStack.

**Comment by aheejin** [comment]
Thanks for reporting. As I described in #20372, that we lose stack traces before rethrowing cannot be solved easily at the moment, both for Emscripten EH and Wasm EH. The native gdb backtraces don't support it either. We might be able to fix it later, but I think that will take some time.

The problem that we completely lose stack traces in Wasm EH after rethrowing is a bug, which should be fixed by #20372.
