### ISSUE TITLE
ReferenceError: emscriptenCpuProfiler is not defined 

### ISSUE THREAD

**Issue by jspanchu** [emscripten-core/emscripten#20425]
When I link with `--cpuprofiler`, the graph shows activity and it is very helpful. Although, when I click on any button, the console shows the error:
```
Uncaught ReferenceError: emscriptenCpuProfiler is not defined     at HTMLElement.onclick (index.html:21:9)
```
Any idea how to resolve this?

My cmake link options:
```cmake
  "-lembind"
  "-sMODULARIZE=1"
  "-sEXPORT_ES6=1"
  "-sENVIRONMENT=web"
  "-sALLOW_MEMORY_GROWTH=1"
  "-sMAXIMUM_MEMORY=4GB"
  "-sSINGLE_FILE=1"
  "--memoryprofiler"
  "--cpuprofiler"
  "-sEXPORTED_FUNCTIONS=['_malloc', '_free']"
  "-sEXPORTED_RUNTIME_METHODS=['ENV']"
```

**Comment by sbc100** [comment]
It looks like `--cpuprofiler` is not compatible with `-sMODULARIZE=1` since the handler it installs assume `emscriptenCpuProfiler` exists in the global scope.

I imagine it would not be too hard to fix if you want to give it a go.   One way to do that might be to explicity create emscriptenCpuProfiler in the global scope by replacing `var emscriptenCpuProfiler = ..` in `src/cpuprofiler.js` with `document.emscriptenCpuProfiler` or `globalThis.emscriptenCpuProfiler`?

**Comment by jspanchu** [comment]
Thanks for the reply. AFK, I will try this soon!
