### ISSUE TITLE
Error in UTF8ToString when calling wgpuDeviceCreateShaderModule

### ISSUE THREAD

**Issue by Ravbug** [emscripten-core/emscripten#20453]
When calling `wgpuDeviceCreateShaderModule`, occasionally the call will fail with
`Invalid UTF-8 leading byte 0x00000090 encountered when deserializing a UTF-8 string in wasm memory to a JS string!`

Code that's causing the error:
```cpp
void ShaderLibraryWG::InitFromShaderSource(decltype(owningDevice) owningDevice, const std::string_view shadercode){
        WGPUShaderModuleWGSLDescriptor shaderCodeDesc;
        shaderCodeDesc.chain.next = nullptr;
        shaderCodeDesc.chain.sType = WGPUSType_ShaderModuleWGSLDescriptor;
        shaderCodeDesc.code = shadercode.data();
        WGPUShaderModuleDescriptor moduleDesc;
        moduleDesc.nextInChain = &shaderCodeDesc.chain;
        shaderModule = wgpuDeviceCreateShaderModule(owningDevice->device, &moduleDesc);
    }
```
The shader string:
```wgsl
diagnostic(off, derivative_uniformity);

var<private> outColor : vec4f;

var<private> fragColor : vec3f;

fn main_1() {
  let x_14 : vec3f = fragColor;
  outColor = vec4f(x_14.x, x_14.y, x_14.z, 1.0f);
  return;
}

struct main_out {
  @location(0)
  outColor_1 : vec4f,
}

@fragment
fn main(@location(0) fragColor_param : vec3f) -> main_out {
  fragColor = fragColor_param;
  main_1();
  return main_out(outColor);
}
```
Call stack:
![image](https://github.com/emscripten-core/emscripten/assets/22283943/82047e4b-7631-4ce6-9737-c35fd6095149)

Maybe the issue is related to #20124 and that the shader source string in `WGPUShaderModuleWGSLDescriptor` is non-owning? Sometimes the code works without issues.

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.48-git (5b63268c904dd0e542f9c45e2b136c3d4a0bd638)
clang version 18.0.0 (https://github.com/llvm/llvm-project 25da11541c0740950e812a85d332a6d5cf4a5f87)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: C:\Users\Admin\Documents\emsdk\upstream\bin
```

**Comment by kripken** [comment]
cc @kainino0x

**Comment by kainino0x** [comment]
The string in `WGPUShaderModuleWGSLDescriptor` is indeed non-owning. But it should certainly be valid for duration of the `wgpuDeviceCreateShaderModule` call, and proxying would block the calling thread to maintain that guarantee. I'm guessing that's what the `'sync'` means, in:
```
      LibraryWebGPU[key + '__proxy'] = 'sync';
```

It seems more likely the issue is in your code. Actually, looking more closely, I think the problem is that `WGPUShaderModuleWGSLDescriptor` requires a null-terminated string, but `std::string_view::data()` does not return one. (You need `std::string::c_str()`, which isn't available on `std::string_view`.) So unless you're manually null-terminating your string before it's passed here, we (Emscripten) will read garbage past the end of your string.
