### ISSUE TITLE
wasm-ld-13: error: unknown file type: init.o

### ISSUE THREAD

**Issue by lenninghuiliu** [emscripten-core/emscripten#20669]
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.5 ()
Ubuntu clang version 13.0.1-2ubuntu2.2
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/bin

lin@DESKTOP-7BKL9RM:~/peks-project$ emcc peks.c main.c -o peks.html  -I/resource/openssl/include/include -lpbc -lssl -lcrypto -lgmp -lm -L/resource/openssl/lib
wasm-ld-13: error: unknown file type: init.o
emcc: error: '/usr/bin/wasm-ld-13 -o peks.wasm /tmp/emscripten_temp_r_4q7lvv/peks_0.o /tmp/emscripten_temp_r_4q7lvv/main_1.o /resource/openssl/lib/libpbc.a /resource/openssl/lib/libssl.a /resource/openssl/lib/libcrypto.a /resource/openssl/lib/libgmp.a -L/resource/openssl/lib -L/usr/share/emscripten/cache/sysroot/lib/wasm32-emscripten -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__stdio_exit --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=ntohs --export=htons --export=malloc --export=__dl_seterr --export=htonl --export=emscripten_builtin_memalign --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024' failed (returned 1)

I have built the libraries(pbc、gmp、openssl)  with emscripten,but there is a new error.
What can I do ?

**Comment by sbc100** [comment]
That error means that `init.o` (likely port of one of the libraries you are trying to link against) was not built with emscripten.  You cannot use libraries built for you host system with emscripten as the file format is different.  Most likely your libraries we built for your host system and are in x86 / x86_64 ELF format and not wasm object file format.

Most likely ` -L/resource/openssl/lib` is the wrong thing to do since I imagine the libraries in that directory are not emscripten built libraries?

Note: I would recommend upgrading you emscripten/llvm version.  Emscripten 3.1.5 and llvm 13 are a few years old now.

**Comment by lenninghuiliu** [comment]
I have use emconfigure again and make it.
Thank you, sir. @sbc100
