### ISSUE TITLE
Feature request: store Emscripten settings in a custom section

### ISSUE THREAD

**Issue by allsey87** [emscripten-core/emscripten#20766]
If settings/flags such as  `ALLOW_MEMORY_GROWTH`, `ALLOW_TABLE_GROWTH`, `INITIAL_MEMORY`, and `STACK_SIZE` / `ASYNCIFY_STACK_SIZE` have been passed to the compiler, it would be nice to be able to get these settings/flags out of a custom section in the WebAssembly binary. This would decouple the compilation from the runtime and allow for runtimes (e.g., Wasmer) that can run modules compiled with different settings.

Is there a reason for not adding a `emscripten.0` custom section to the WebAssembly module that uses the same format as `dynlink.0` to encode this information?

**Comment by sbc100** [comment]
My preference would be to avoid needing this is possible.

For the first three of those settings I think you can just inspect the `memory` and `__indirect_function_table` imports/exports.   The memory and table both and an initial and max size (if they are different then they are growable).

Why would you need to know `STACK_SIZE` ?  That seems like an internal implementation detail that the runtime doesn't need to know?

As for `ASYNCIFY_STACK_SIZE`, that I suppose is not available and could be useful to someone implementing asyncify?  Are you suggesting the wasmer would implement asyncify ? i.e. re-implement all of the asyncify JS logic?   @kripken does this seem feasible to you?

**Comment by kripken** [comment]
I guess it's possible in theory to implement the Asyncify JS runtime in a VM. Perhaps getting `ASYNCIFY_STACK_SIZE` would be useful in that case. But

1. You might as well add stack size handling into the VM. That is the VM could have `--async-stack-size` as a flag. This is possible since there is no coordination between the compiled wasm and the runtime regarding that size: the Asyncify pass is not even given the stack size at all, it is only used in the runtime.
2. Asyncify is a stopgap solution, and JSPI can almost be used today. It would make more sense for a VM to support that, I think.

Also note that we have `RETAIN_COMPILER_SETTINGS` that you could probably write a little script to serialize those settings into a custom section in the wasm if you needed them.

**Comment by allsey87** [comment]
> My preference would be to avoid needing this is possible.

The suggestions that you have made are good enough for my purposes. I will close this for now.

**Comment by allsey87** [comment]
Not exactly a setting per se, but how would a custom runtime go about getting the value of `__stack_low` that Emscripten uses?
