### ISSUE TITLE
No non power of two texture support for OpenGL ES2.

### ISSUE THREAD

**Issue by Lockl00p** [emscripten-core/emscripten#21083]
Even though OpenGL ES2 supports non power of two textures, there seems to be nothing to accomodate NPOT textures when translating to WebGL, even with the FULL_ES2 emcc flag. Also, it seems to not be able to create quite a few textures in the first place, weirdly enough.

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.51 (c0c2ca1314672a25699846b4663701bcb6f69cca)
clang version 18.0.0git (https://github.com/llvm/llvm-project f2464ca317bfeeedddb7cbdea3c2c8ec487890bb)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /workspaces/emsdk/upstream/bin

**Full link command and output with `-v` appended:**
'''/workspaces/emsdk/upstream/emscripten/emcc -o ../../../darkplaces-emscripten.html ../../../builddate.c sys_sdl.o vid_sdl.o thread_sdl.o menu.o mvm_cmds.o snd_main.o snd_mem.o snd_mix.o snd_ogg.o snd_wav.o snd_xmp.o snd_sdl.o cap_avi.o cap_ogg.o bih.o crypto.o cd_shared.o cl_cmd.o cl_collision.o cl_demo.o cl_ents.o cl_ents4.o cl_ents5.o cl_ents_nq.o cl_ents_qw.o cl_input.o cl_main.o cl_parse.o cl_particles.o cl_screen.o cl_video.o cl_video_libavw.o clvm_cmds.o cmd.o collision.o com_crc16.o com_ents.o com_ents4.o com_game.o com_infostring.o com_msg.o common.o console.o csprogs.o curves.o cvar.o dpvsimpledecode.o filematch.o fractalnoise.o fs.o ft2.o utf8lib.o gl_backend.o gl_draw.o gl_rmain.o gl_rsurf.o gl_textures.o hmac.o host.o image.o image_png.o jpeg.o keys.o lhnet.o libcurl.o mathlib.o matrixlib.o mdfour.o meshqueue.o mod_skeletal_animatevertices_sse.o mod_skeletal_animatevertices_generic.o model_alias.o model_brush.o model_shared.o model_sprite.o netconn.o palette.o phys.o polygon.o portals.o protocol.o prvm_cmds.o prvm_edict.o prvm_exec.o r_explosion.o r_lightning.o r_modules.o r_shadow.o r_sky.o r_sprites.o r_stats.o sbar.o sv_ccmds.o sv_demo.o sv_ents.o sv_ents4.o sv_ents5.o sv_ents_csqc.o sv_ents_nq.o sv_main.o sv_move.o sv_phys.o sv_save.o sv_send.o sv_user.o svbsp.o svvm_cmds.o sys_shared.o taskqueue.o vid_shared.o view.o wad.o world.o zone.o -O3 -fno-math-errno -fno-trapping-math                        -DVCREVISION=cd3b7da2~ -DBUILDTYPE=release -lm  -lz ../../../Darkplaces-Emscripten/builddeps/jpeg/lib/libjpeg.a ../../../Darkplaces-Emscripten/builddeps/d0_blind_id/lib/libd0_blind_id.a ../../../Darkplaces-Emscripten/builddeps/gmp/lib/libgmp.a ../../../Darkplaces-Emscripten/builddeps/d0_blind_id/lib/libd0_rijndael.a -sINITIAL_MEMORY=1500MB  -lrt -ldl -rdynamic `sdl2-config --libs` -lX11  -LDarkplaces-Emscripten/builddeps/d0_blind_id/lib/ -Wl,-rpath,Darkplaces-Emscripten/builddeps/d0_blind_id/lib/ -LDarkplaces-Emscripten/builddeps/gmp/lib -Wl,-rpath,Darkplaces-Emscripten/builddeps/gmp/lib -LDarkplaces-Emscripten/builddeps/jpeg/lib/ -Wl,-rpath,Darkplaces-Emscripten/builddeps/jpeg/lib/ -sUSE_SDL=2 -sUSE_ZLIB=1 -DUSE_GLES2 -sINITIAL_MEMORY=1500MB -sMAXIMUM_MEMORY=4GB -sSINGLE_FILE -sFULL_ES2 -sUSE_SDL=2 -sALLOW_MEMORY_GROWTH --pre-js ../../../Darkplaces-Emscripten/prejs.js -lidbfs.js -sEXPORTED_RUNTIME_METHODS=callMain --shell-file=../../../Darkplaces-Emscripten/shell.htm'''

Errors are from webgl:

'''darkplaces-emscripten (3).html:1  WebGL: INVALID_VALUE: texImage2D: invalid internalformat'''
'''darkplaces-emscripten%20(3).html:1  [.WebGL-00002FC001324700] GL_INVALID_VALUE: The texture is a non-power-of-two texture.'''

**Comment by sbc100** [comment]
@juj @kainino0x  ?

**Comment by kainino0x** [comment]
As you mentioned those errors come from WebGL. The FULL_ES2 flag can't emulate everything, and this is probably a place where Emscripten can't help.

As for why WebGL has this error when native ES2 doesn't, it's generally either:
- some additional restriction in WebGL
- actually was undefined behavior in OpenGL ES 2.0 but the drivers you've tested all allow it (typically because almost every device is ES 3.0+)

Have you tried targeting ES 3.0 (= WebGL 2.0) instead?

It may also help to look into ANGLE to see what is actually happening here:
https://source.chromium.org/chromium/chromium/src/+/main:third_party/angle/src/libANGLE/ErrorStrings.h;bpv=1;bpt=1;l=582?q=f:%5Ethird_party%2Fangle%20%22The%20texture%20is%20a%20non-power-of-two%20texture%22&ss=chromium
https://source.chromium.org/chromium/chromium/src/+/main:third_party/angle/src/libANGLE/validationES.cpp;l=1086;drc=3cc22c22d7637bc5604e8fef3b0882b51a762901

Though do prioritize fixing the first error as it could be cascading into the second one first.

**Comment by Lockl00p** [comment]
I figured out the problem. I didn’t use webgl2
