### ISSUE TITLE
More compact memory initialization?

### ISSUE THREAD

**Issue by evanw** [emscripten-core/emscripten#2188]
I noticed that the static memory initializer in the generated code uses bytes instead of 32-bit ints. Switching it to use 32-bit ints instead made the code significantly smaller in our case (we lost around 150kb). Is there a reason this isn't done when targeting typed arrays?

**Comment by dreamlayers** [comment]
Compilers generally put zero-initialized variables in a bss section, and only include non-zero initialized variables in the memory initializer. Emscripten does not do this. An `ArrayBuffer` is initialized to zero according to the specification, so variables could be initialized to zero for free.

Emscripten has the `USE_BSS` option and some associated code, but that is not getting executed. I guess it only gets executed when not using fastcomp? Is BSS not implemented with fastcomp, or is something broken?

I see that normally, clang will use bss and common sections, but when compiling with Emscripten options it only puts a few variables in common. Then the `opt` invocation moves everything into the data segment. After that, initializer splitting can help with long stretches of zeros if not using a memory init file. Finally, gzip compression can help, but no form of lossless compression can fully compensate for this.

I've also noticed that the memory init file is counterproductive with DOSBox after gzip compression:
Without .mem: 1000033 js.gz
With .mem: 856088 js.gz + 147788 mem.gz = 1003876 
I don't know if this is because of long spans of zeros removed by initializer splitting. I thought gzip should handle that sort of thing well.

**Comment by kripken** [comment]
Yes, we had someone add a BSS optimization in the old compiler, and I think nothing has been done in the current one. So we might have a suboptimal memory initializer.

I'm surprised the memory init file is worse after gzip. Startup should still be faster, though, even with a slightly larger download (handling binary data is much faster than parsing JS). But it would be nice to understand this.

**Comment by dreamlayers** [comment]
I think DOSBox might be a special case due to having very large zero initialized variables. It uses over 20 MB for the TLB (for efficient paging). I just tried https://github.com/dreamlayers/synaesthesia/ and there the memory init file definitely helps: 137182 vs.162551 bytes gzip -9 compressed.

With DOSBox, I'm not sure that using the memory init file helps startup times. Using file:// URLs in Firefox 35, startup seems faster without. That wasn't using gzip though. I'm turning off the memory init file when not using emterpreter for now.

**Comment by gagern** [comment]
I just filed #3326 about encoding the memory initializer into a string literal. Hadn't known about this report here before. I'm using base 88, not escape sequences in the literal. https://github.com/chadaustin/Web-Benchmarks/tree/master/meminit ends up at 186,700 bytes uncompressed resp. 61,366 after gzip. I haven't done any performance tests yet.

**Comment by gagern** [comment]
I did some performance tests. Turns out my base88 takes about 1.7 × the time of minstr when parsing. Replacing the `indexOf` call with a lookup table I can make that factor 1.3 or so. Still worse, and it compresses poorly as well. It's still nice in terms of uncompressed size, but I doubt that will warrant using it. Surprising thing is, however, how poorly the compression in Python is. That takes ages!

I've got a small improvement to offer for the minstr implementation: if you XOR all bytes with 32, you'll avoid all those `\0` and escape sequences for small bytes in general. That reduces uncompressed size from 230.8k to 217.9k, and although the win in compressed size, from 47.1 to 46.9, is neglgible, at least things didn't get worse there. I've got the feeling that parsing time in Chromium even decreases, while Firefox remains the same. It's hard to tell with all the fluctuation I'm seeing there, though.

**Comment by gagern** [comment]
Taking that XOR approach one step further, one could do a character frequency analysis and encode the common bytes with printable characters. See `tinylut` in https://github.com/gagern/Web-Benchmarks/tree/tinylut/meminit for an implementation. Uncompressed 187.7k resp. compressed 46.2k. Initialization time has suffered a bit, but not too much I think. Not sure how the compression would look if one were to include this in a larger emscripten output file.

**Comment by evanw** [comment]
That's awesome! Really cool idea.

**Comment by gagern** [comment]
Implemented this approach for #3326.
