### ISSUE TITLE
AUDIO_WORKLET + MODULARIZE broken in 3.1.59

### ISSUE THREAD

**Issue by kichikuou** [emscripten-core/emscripten#21908]
**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.59 (0e4c5994eb5b8defd38367a416d0703fd506ad81)
clang version 19.0.0git (https:/github.com/llvm/llvm-project df762a1643bb5b0b3c907611d118c82d4b68a39d)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Failing command line in full:**
Compile `audioworklet.c` in the Emscripten webaudio test directory:
```
cd emscripten/test/webaudio
emcc audioworklet.c -o audioworklet.html -sAUDIO_WORKLET -sWASM_WORKERS -sMODULARIZE -sEXPORT_ES6
```
And open `audioworklet.html` in the browser.

**Error:**
```
audioworklet.js:635 Aborted(Access to module property ('stackAlloc') is no longer possible via the module constructor argument; Instead, use the result of the module constructor.)
audioworklet.js:654 Uncaught RuntimeError: Aborted(Access to module property ('stackAlloc') is no longer possible via the module constructor argument; Instead, use the result of the module constructor.)
    at abort (audioworklet.js:654:11)
    at Object.get (audioworklet.js:1947:9)
    at new WasmAudioWorkletProcessor (audioworklet.aw.js:24:37)
```

It looks like a regression by #21775.

**Comment by sbc100** [comment]
Interesting.  I wonder why the test we have that (`browser.test_audio_worklet_es6`) is not failing..

**Comment by sbc100** [comment]
The reason we don't see this fail is because `browser.test_audio_worklet_es6` doesn't keep the runtime alive long enough do anything with the audio worklet, it just exits when main returns.   Also, we don't currently have any way to actually run audio tests during CI so even without this crash the test isn't actually playing any audio when run in CI.  Instead we must rely mostly on interactive tests today to test audio stuff.
