### ISSUE TITLE
When targeting NodeJS with NODERAWFS, why no use process.stdout.write and process.stderr.write?

### ISSUE THREAD

**Issue by mzoliker** [emscripten-core/emscripten#21919]
Hi! This time this is more a design question: when we are definitely targeting NodeJS and a JS build (with the following compilation flags:
	-sMODULARIZE=1
	-sENVIRONMENT=node
	-sMIN_NODE_VERSION=101900
	-sNODERAWFS
	-sWASM_ASYNC_COMPILATION=0
	-sWASM=0
), when writing to fd 1 (stdout) or fd 2 (stderr), why not directly use `process.stdout.write` and `process.stderr.write`?

I am asking this because this would certainly be cleaner (less unnecessary glue code) and also because it would also work on NodeJS ports (such as iOS) where stdout and stderr have been redirected or reimplemented. Right now it breaks because of that, as nothing shows on the console, but if I patch fd_write to use `process.stdout.write` and `process.stderr.write` for fd =1 and fd=2, it works fine.

Thanks a lot for your feedback!

Kind regards,
Maurice

**Comment by sbc100** [comment]
Under NODERAWFS I believe a write to stdout will turn into `fs.writeSync(1, ..` and a write to stderr will turn into `fs.writeSync(2, ..`  here:

https://github.com/emscripten-core/emscripten/blob/619f08d9498f417eae94deab129f3e97df8995eb/src/library_noderawfs.js#L168

This seems like a pretty sensible implementation and avoids the need to special case stdout and stderr.  Adding code to special case them would add complexity and code size.

Regarding you specific issue of "stdout and stderr have been redirected or reimplemented".. are you saying that the host is somehow intercepting `process.stdout.write` but not `fs.writeSync(2, ..` and you want the emscripten stdout to be intercepted in the same way?   Its seems odd to me that `process.stdout.write` and `fs.writeSync(1, ..` would do different things.  Perhaps this is a bug that can be fixed with the embedder?  How does the nodejs iOS port work in this respect?  Where does `process.stdout.write` go and where does  `fs.writeSync(1, ..` go?

**Comment by sbc100** [comment]
> Under NODERAWFS I believe a write to stdout will turn into `fs.writeSync(1, ..` and a write to stderr will turn into `fs.writeSync(2, ..` here:
> 
> https://github.com/emscripten-core/emscripten/blob/619f08d9498f417eae94deab129f3e97df8995eb/src/library_noderawfs.js#L168
> 
> This seems like a pretty sensible implementation and avoids the need to special case stdout and stderr. Adding code to special case them would add complexity and code size.
> 
> Regarding you specific issue of "stdout and stderr have been redirected or reimplemented".. are you saying that the host is somehow intercepting `process.stdout.write` but not `fs.writeSync(2, ..` and you want the emscripten stdout to be intercepted in the same way? Its seems odd to me that `process.stdout.write` and `fs.writeSync(1, ..` would do different things. Perhaps this is a bug that can be fixed with the embedder? How does the nodejs iOS port work in this respect? Where does `process.stdout.write` go and where does `fs.writeSync(1, ..` go?  (where even is the console in such a port?)

**Comment by mzoliker** [comment]
Hi! You are perfectly right, this was a bug in the NodeJS runtime. Redirecting `fs.writeSync(1, …)` to `process.stdout.write` and `fs.writeSync(2, …)` to `process.stderr.write` did the trick and it works like a charm now :-). Thanks a lot for your help!
Kind regards,
Maurice
