### ISSUE TITLE
emconfigure issue on windows

### ISSUE THREAD

**Issue by ILOVEPIE** [emscripten-core/emscripten#2208]
In order to compile most projects with emscripten on windows you have to use the Linux makefiles, however the Linux makefiles for many projects are generated by a bash configure script, the issue lies in that emscripten's emconfigure doesn't work with windows versions of bash, the paths defined by emconfigure and the emscripten sdk get all messed up. It is possible to work around this with some cygwin trickery but it causes a massive headaches when you go to compile with the makefiles, we need to find some way to fix this. This issue is only partially related to issue #607

**Comment by ip** [comment]
This is really important. How one is supposed to use make while even this doesn't work?
```makefile
clean:
    rm -rf ./obj ./bin

makedirs:
    mkdir -p obj/some/dir
```
I also tried to run `emmake make` from msys (mingw terminal) but encountered the same issue with Python. Using windows-specific commands in GNU makefile is not a solution. Correct me if I miss something.
Now I decided to just install Ubuntu VM and use Emscripten from there.

**Comment by mnuzzolilo** [comment]
The problem with waiting for "public interest" for these types of issues is that this is often a show stopper for each developer who encounters this problem, and waiting for a fix is not an issue. I imagine most developers don't typically spend 100% of their time using emscripten but rather have a one-off use case for this. 

So that begs the question: Are those developers going to even bother coming here to ask for the feature when it's apparent that these tools are broken in Windows?
