### ISSUE TITLE
Annotate `EmbindString` as a real string in Typescript

### ISSUE THREAD

**Issue by giuseppesalvo** [emscripten-core/emscripten#22387]
When using Embind, is there a way to annotate an `std::string` as a `string` type when exporting the Typescript types? 

It's a bit unconvenient that `std::string` is exported as:
```ts
type EmbindString = ArrayBuffer|Uint8Array|Uint8ClampedArray|Int8Array|string;
````

I understand the reasoning behind it, but maybe offering a way to annotate a field as being an actual string, could be very helpful. Otherwise, when using the type in Typescript, we're forced to always cast to a real string with `as string`.

I imagine something like this could work:

```cpp
  class_<Person>("Person")
      .property("name", &Person::name, /* TS Type */ "string");
```

Not sure how feasible, maybe there are better ways, but something like that would make things way easier.

**Comment by wffurr** [comment]
It seems like the read / return type for `std::string` fields / `std::string`-returning functions ought to be just `string`, since that's what I get in JS from embind.

But I can pass any of the types in `EmbindString` as a `std::string` parameter *to* a function or when writing a `std::string` field.

**Comment by brendandahl** [comment]
We currently already annotate functions that return strings as [plain js strings](https://github.com/emscripten-core/emscripten/blob/eb4d36d47f451d0040a0c796606eaae9aa530de3/test/other/embind_tsgen.d.ts#L131). Looks like we need to do this for properties too.

**Comment by giuseppesalvo** [comment]
Ah yes, indeed. This is only for properties, which is the use case I was dealing with.

**Comment by fbleibel-g** [comment]
Any chance that this could be handled similarly for structs as well?

For example, if instead of `std::string GetPersonName` I had a function that returned `struct Person { std::string name; int age; }`, I would currently need to use `person.name as string` etc. everywhere I pass the Person type around in typescript. I have a more complex "production" case where the structs are deeply nested and contain vectors of structs, etc.

**Comment by brendandahl** [comment]
What is the `EMSCRIPTEN_BINDINGS` code for your struct?

**Comment by fbleibel-g** [comment]
It is similar to this:

```cpp
EMSCRIPTEN_BINDINGS(my_module) {

struct LogMessage {
  std::string message;
  std::string severity;
};

emscripten::value_object<ns::LogMessage>("LogMessage")
emscripten::register_vector<ns::LogMessage>("VectorLogMessage");
// ... etc.
}
```

This currently gives me an output of:

```
type EmbindString = ArrayBuffer|Uint8Array|Uint8ClampedArray|Int8Array|string;

export type LogMessage = {
  message: EmbindString,
  severity: EmbindString
};
```

**Comment by fbleibel-g** [comment]
Do you have a guide on how I can use the latest changes to generate ts `string`s in value objects?

**Comment by brendandahl** [comment]
It should just work without any changes with the tip of tree emscripten when the second PR is merged. It will be a little while until it makes it into a release version.

**Comment by sbc100** [comment]
> It should just work without any changes with the tip of tree emscripten when the second PR is merged. It will be a little while until it makes it into a release version.

But you can try it today with `emsdk install tot`
