### ISSUE TITLE
Understanding "trying to suspend JS frames" error when using JSPI + module splitting

### ISSUE THREAD

**Issue by Mintyboi** [emscripten-core/emscripten#22469]
I am using ASYNCIFY=2 with SPLIT_MODULE settings and in application.
After loading the secondary module, and calling a JSPI'ed function, I get an error:
`RuntimeError: trying to suspend JS frames`

This error is thrown in V8, [here](https://github.com/v8/v8/blob/ae3595136ee545dcf97c1b87ebe3f2d400aa1fd4/src/wasm/wrappers.cc#L1207), when there are JS frames in the current suspender.
Unfortunately I wasn't able to reproduce this issue on a smaller test app to attach it here (it works flawlessly, so it could be something I am doing in my app).

Do you have any advice on how I can continue to debug this or find out what is the JS stackframe that exists in the stack.

Chrome version: v130 with `#enable-experimental-webassembly-jspi` enabled
emsdk version: 3.1.41
Build flags:
```
-fPIC 
-s WASM_BIGINT=1
-fwasm-exceptions 
-s SPLIT_MODULE=1 
-s MAIN_MODULE=2 
-s ASYNCIFY=2 
-s ASYNCIFY_IGNORE_INDIRECT=1 
-s NO_EXIT_RUNTIME=0
-s ASSERTIONS=1
```

**Comment by brendandahl** [comment]
There is likely a function missing that needs to be in JSPI_EXPORTS or a re-entrancy problem. You should get a backtrace in the console that will help you figure out where the issue is coming from.

I haven't run into this specific error yet, so I made a little example:

```c
#include <stdio.h>
#include <emscripten.h>

extern int not_suspending_js();
extern int suspending_js();

EMSCRIPTEN_KEEPALIVE int suspending_wasm() {
  return suspending_js();
}

int main() {
  int i = not_suspending_js();
  printf("got %d\n", i);
}
```

```js
mergeInto(LibraryManager.library, {
  not_suspending_js: () => {
    return Module._suspending_wasm();
  },
  suspending_js__async: true,
  suspending_js: async () => {
    await Promise.resolve(42);
  }
});
```

`emcc -sJSPI -g main.c -o a.out.html --js-library=library.js`

Will give the error:
```
main.c:8 Uncaught (in promise) RuntimeError: trying to suspend JS frames
    at suspending_wasm (main.c:8)
    at ret.<computed> (a.out.js:1244:24)
    at Object._suspending_wasm (a.out.js:620:12)
    at _not_suspending_js (a.out.js:1100:21)
    at main (main.c:12)
    at a.out.wasm.main (a.out.wasm:0x335)
  ```

In this case the `_not_suspending_js` should either not be calling back into wasm that will call another function that suspends, or _suspending_wasm needs to be wrapped so it can suspend. e.g. `-sJSPI_EXPORTS=suspending_wasm` and `_not_suspending_js` should be async as well. e.g.

```js
mergeInto(LibraryManager.library, {
  not_suspending_js__async: true,
  not_suspending_js: async () => {
    return await Module._suspending_wasm();
  },
  suspending_js__async: true,
  suspending_js: async () => {
    return await Promise.resolve(42);
  }
});
```
`emcc -sJSPI_EXPORTS=suspending_wasm -sJSPI -g main.c -o a.out.html --js-library=library.js`
