### ISSUE TITLE
Passing structs by value to/from JavaScript doesn't seem to work?

### ISSUE THREAD

**Issue by fadams** [emscripten-core/emscripten#2251]
I've got some C code that looks like this:

```
pn_bytes_t pn_bytes(size_t size, char *start)
{
  pn_bytes_t bytes = {size, start};
  return bytes;
}


int pn_data_put_string(pn_data_t *data, pn_bytes_t string)
{
  pni_node_t *node = pn_data_add(data);
  node->atom.type = PN_STRING;
  node->atom.u.as_bytes = string;
  return pn_data_intern_node(data, node);
}
```

I've tried to call these methods from JavaScript

```
var s = "test string";
console.log("putString " + s);
    var array = intArrayFromString(s);
console.log("array.length " + array.length);

    var ptr = allocate(array, 'i8', ALLOC_STACK);
console.log("ptr " + ptr);

    var bytes = _pn_bytes(array.length, ptr);

console.log("bytes " + bytes);
    this._check(_pn_data_put_string(this._data, bytes));
```

But this doesn't seem to work - the _pn_bytes seems to return undefined.

Is this a known issue? It seems to work OK from compiled C code but I'd like to invoke from a pure JavaScript application.

I guess that I could write a thin C wrapper function but I was wondering if there was any other way.

**Comment by SergeySeroshtan** [comment]
Maybe helpful for WASM https://stackoverflow.com/a/56405899/1763487

**Comment by juj** [comment]
Thanks for the link, that looks very relevant. The original conversation is quite old, I'll close this as resolved.

**Comment by vvuk** [comment]
This is a longstanding emscripten ABI issue, where I believe it doesn't follow the C ABI.

Given:

```
typedef struct { int value; } Thing;


int do_it(Thing x)
{
        return x.value + 1;
}

int do_it_ptr(Thing* x)
{
        return x->value + 1;
}
```

x86-64 clang 6:

```
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

%struct.Thing = type { i32 }

; Function Attrs: norecurse nounwind readnone uwtable
define i32 @do_it(i32) local_unnamed_addr #0 {
  %2 = add nsw i32 %0, 1
  ret i32 %2
}

; Function Attrs: norecurse nounwind readonly uwtable
define i32 @do_it_ptr(%struct.Thing* nocapture readonly) local_unnamed_addr #1 {
  %2 = getelementptr inbounds %struct.Thing, %struct.Thing* %0, i64 0, i32 0
  %3 = load i32, i32* %2, align 4, !tbaa !2
  %4 = add nsw i32 %3, 1
  ret i32 %4
}
```

emscripten:

```
target datalayout = "e-p:32:32-i64:64-v128:32:128-n32-S128"
target triple = "asmjs-unknown-emscripten"

%struct.Thing = type { i32 }

; Function Attrs: norecurse nounwind readonly
define i32 @do_it(%struct.Thing* byval nocapture readonly align 4 %x) local_unnamed_addr #0 {
entry:
  %value = getelementptr inbounds %struct.Thing, %struct.Thing* %x, i32 0, i32 0
  %0 = load i32, i32* %value, align 4, !tbaa !2
  %add = add nsw i32 %0, 1
  ret i32 %add
}

; Function Attrs: norecurse nounwind readonly
define i32 @do_it_ptr(%struct.Thing* nocapture readonly %x) local_unnamed_addr #0 {
entry:
  %value = getelementptr inbounds %struct.Thing, %struct.Thing* %x, i32 0, i32 0
  %0 = load i32, i32* %value, align 4, !tbaa !2
  %add = add nsw i32 %0, 1
  ret i32 %add
}
```

All compilers that I've tested, x86, x86-64, arm, ppc, and mips; clang, gcc, and msvc perform like clang does above -- the small struct by value is passed by value.  emscripten's ABI is the only one that unconditionally causes the struct to always be passed by pointer, causing unnecessary code, extra memory work, and causing large headaches with ABI compat when doing ffi calls to emscripten-compiled C from other languages.

**Comment by brion** [comment]
I think this is resolved by the upstream WebAssembly backend; with latest-upstream compiling at `-O1` I get:

```
; ModuleID = '<stdin>'
source_filename = "foo.c"
target datalayout = "e-m:e-p:32:32-i64:64-n32:64-S128"
target triple = "wasm32-unknown-emscripten"

%struct.Thing = type { i32 }

; Function Attrs: norecurse nounwind readnone
define hidden i32 @do_it(i32 %x.coerce) local_unnamed_addr #0 {
entry:
  %add = add nsw i32 %x.coerce, 1
  ret i32 %add
}

; Function Attrs: norecurse nounwind readonly
define hidden i32 @do_it_ptr(%struct.Thing* nocapture readonly %x) local_unnamed_addr #1 {
entry:
  %value = getelementptr inbounds %struct.Thing, %struct.Thing* %x, i32 0, i32 0
  %0 = load i32, i32* %value, align 4, !tbaa !2
  %add = add nsw i32 %0, 1
  ret i32 %add
}

attributes #0 = { norecurse nounwind readnone "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="generic" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { norecurse nounwind readonly "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="generic" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 9.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 922759a63d7d8edbc47578b4718a38765093d24e)"}
!2 = !{!3, !4, i64 0}
!3 = !{!"", !4, i64 0}
!4 = !{!"int", !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C/C++ TBAA"}
```

**Comment by SergeySeroshtan** [comment]
This is true if a struct contains one member, otherwise, [it is passed by pointer](https://mbebenita.github.io/WasmExplorer/?state=%7B%22options%22%3A%7B%22showGutter%22%3Atrue%2C%22showConsole%22%3Atrue%2C%22showOptions%22%3Atrue%2C%22autoCompile%22%3Atrue%2C%22showLLVM%22%3Afalse%2C%22darkMode%22%3Atrue%2C%22fastMath%22%3Afalse%2C%22noInline%22%3Afalse%2C%22noRTTI%22%3Afalse%2C%22noExceptions%22%3Afalse%2C%22cleanWast%22%3Atrue%2C%22wasmBaseline%22%3Afalse%2C%22dialect%22%3A%22C99%22%2C%22optimizationLevel%22%3A%221%22%7D%2C%22source%22%3A%22typedef%20struct%20%7B%20int%20value%3B%20int%20key%3B%20%7D%20Thing%3B%5Cn%5Cn%5Cnint%20do_it(Thing%20x)%5Cn%7B%5Cn%20%20%20%20%20%20%20%20return%20x.value%20%2B%201%3B%5Cn%7D%5Cn%5Cnint%20do_it_ptr(Thing*%20x)%5Cn%7B%5Cn%20%20%20%20%20%20%20%20return%20x-%3Evalue%20%2B%201%3B%5Cn%7D%22%7D).

**Comment by dschuff** [comment]
It doesn't make sense to say that emscripten/LLVM on wasm doesn't follow "the C ABI" because the C ABI is defined by the combination of the language and architecture. LLVM's Wasm C ABI is documented [here](https://github.com/WebAssembly/tool-conventions/blob/master/BasicCABI.md) (although that document is not complete yet, and I don't think it actually includes the relevant bits we are talking about here) and it's intended to be the source of truth. In other words, ABI details need not match exactly between architectures.

Having said that, you are right that there is room to improve the ABI, and we are planning on doing that in the future. For example, in particular when there is widespread browser support for the wasm multi-value extension, we intend to make the calling convention return small structures as multiple primitive values. When that happens it probably makes sense to also make other improvements to how structures are passed.

If you have feedback on that, I'd recommend filing an issue on the [tool-conventions](https://github.com/WebAssembly/tool-conventions) repo and we can discuss the specifics there.
