### ISSUE TITLE
WebGPU Regression?

### ISSUE THREAD

**Issue by ypujante** [emscripten-core/emscripten#22682]
I upgraded to emscripten 3.1.68 (from 3.1.66) and my project [WebGPU Shader Toy](https://github.com/pongasoft/webgpu-shader-toy) which was working fine now fails.

I am seeing error messages like these:

```text
[WebGPU] Validation error | Write range (bufferOffset: 0, size: 1887248) does not fit in [Buffer "Dear ImGui Vertex buffer"] size (119040).
 - While calling [Queue].WriteBuffer([Buffer "Dear ImGui Vertex buffer"], (0 bytes), data, (1887248 bytes))
```

I can see from the list of PRs, that there was this one: #22494 (WebGPU: support Premultiplied canvas output)

I suppose my code can be doing something wrong (but I did not change my code, just the emscripten version). Does anybody know if this PR introduced a regression?

**Comment by ypujante** [comment]
I just wanted to add that I built the demo (example_glfw_wgpu) that comes with ImGui latest version 1.91.3 and I am getting the exact same kind of error (so basically I have eliminated my code/layer)

```text
(index):41 Validation error: Write range (bufferOffset: 0, size: 592656) does not fit in [Buffer "Dear ImGui Vertex buffer"] size (115240).
(index):41  - While calling [Queue].WriteBuffer([Buffer "Dear ImGui Vertex buffer"], (0 bytes), data, (592656 bytes))
(index):41 
28Write range (bufferOffset: 0, size: 592656) does not fit in [Buffer "Dear ImGui Vertex buffer"] size (115240).
 - While calling [Queue].WriteBuffer([Buffer "Dear ImGui Vertex buffer"], (0 bytes), data, (592656 bytes))
Understand this warning
(index):41 Validation error: Write range (bufferOffset: 0, size: 547616) does not fit in [Buffer "Dear ImGui Index buffer"] size (22528).
(index):41  - While calling [Queue].WriteBuffer([Buffer "Dear ImGui Index buffer"], (0 bytes), data, (547616 bytes))
(index):41 
```

```text
> emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.68 (ceee49d2ecdab36a3feb85a684f8e5a453dde910)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

> cd examples/example_glfw_wgpu
> make -f Makefile.emscripten serve
```

**Comment by SenorBlanco** [comment]
I came here to log a similar regression in another project. I don't have a reduced test case, but a git bisect tells me the regression was introduced here:

https://github.com/emscripten-core/emscripten/commit/d0d9966daa064eef3281495d9168a5efbef3f692

**Comment by SenorBlanco** [comment]
@sbc100 FYI

**Comment by SenorBlanco** [comment]
In my case, the error I get is:

Device error: Write range (bufferOffset: 0, size: 4193888) does not fit in [Buffer (unlabeled)] size (48).
 - While calling [Queue].WriteBuffer([Buffer (unlabeled)], (0 bytes), data, (4193888 bytes))

Note that 4193888 is 0x003FFE60, which is exactly the "data" pointer passed at the C++ call site. So it's as if the formal arguments are offset by 32 bits, and "data" is falling into "size".

**Comment by juj** [comment]
The problem is with i64 legalization passthrough stub that is generated in Wasm side.

In WebGPU Shader Toy, the JS side gets generated as one would expect:

![image](https://github.com/user-attachments/assets/a51a855f-5e7c-45d3-af02-1699f5796d6f)

I added the highlighted line manually to debug/troubleshoot, and the browser prints

![image](https://github.com/user-attachments/assets/0afcd94d-337b-4382-95f3-91e526d9fca4)

![image](https://github.com/user-attachments/assets/a866259e-cceb-4ce2-9d4d-56ceef62a398)

Indeed in the above prints, the large `size=` numbers are not the sizes that the C++ code passed, but these numbers are the `bufferOffset` parameter values. The numbers have shifted like mentioned before.

The offending part here is the function `$legalfunc$wgpuQueueWriteBuffer` that gets generated in the Wasm module.

The user code function that calls `wgpuQueueWriteBuffer` does so rather straightforwardly:

![image](https://github.com/user-attachments/assets/4e6b9ab2-c835-4d1d-b700-b69d89e41ee5)

though then there is a legalization function that stands in between:

![image](https://github.com/user-attachments/assets/c3c75f50-8953-4c81-8d36-d3fe094f0898)

which calls the five parameter function 

```
void wgpuQueueWriteBuffer(WGPUQueue queue, WGPUBuffer buffer, uint64_t bufferOffset, void const * data, size_t size);
```

as six parameters on the JS side, splitting up the 64-bit `bufferOffset` integer into two 32-bit high and low parts. (this is the strategy we have had for a long while with 64-bit params)

If I manually change the JS side function to expect the two 32-bit high and low parts, that is:

![image](https://github.com/user-attachments/assets/8023b659-d20f-4408-8400-08ccce78949f)

Then the `writeBuffer` calls work correctly as expected. The run then errors out possibly on another instance of the same glitch:

![image](https://github.com/user-attachments/assets/c51be136-f12a-4169-a5ba-f453922c7723)

I haven't followed the development of the recent automatic 64-bit value marshalling with `foo__i53abi: true` (PR #19711) and `j` type in `foo__sig` since I manage 64-bit pointers and integer values manually in my [wasm_webgpu](https://github.com/juj/wasm_webgpu) library, due to wanting to be hand-craftingly precise about the code that is emitted. E.g. [wgpu_queue_write_buffer](https://github.com/juj/wasm_webgpu/blob/e7e6fddb4de6445dca6ecad5bda299d592921dcd/lib/lib_webgpu.js#L2451-L2460).

Reading the ChangeLog, it seems to me that this breakup into two 32-bit parts should not have happened, as it states:

![image](https://github.com/user-attachments/assets/4bab0aa7-893b-4a20-8b59-1dbbc598b3ab)

Suggesting that instead of hi/lo parts, adding `foo__i53abi: true` should have instead done a i64 -> Number conversion at the boundary? @sbc100 Did the `foo__i53abi: true` fault here? It looks like what has occurred is not according to what the above ChangeLog says (or maybe I interpreted the extent/conditions of the behavior described in ChangeLog incorrectly?)

If this hi/lo generation was expected, then should the `foo__i53abi: true` parameter mean Emscripten should generate a matching JS-side wrapper to combine the two i32 parts together? Or should the developer manually do that with the `receiveI64ParamAsI53()` function? (#iffing its use behind `-sWASM_BIGINT=0` only perhaps?)

-------------

Nevertheless, I tried to quickly poke at the issue by enabling BigInt support via

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2b92b2b..e514c9a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -103,6 +103,7 @@ target_compile_options(wgpu_shader_toy PUBLIC

 target_link_options(wgpu_shader_toy PUBLIC
     "-fwasm-exceptions"
+    "-sWASM_BIGINT"
     "${wgpu_shader_toy_options}"
     "--js-library" "${CMAKE_CURRENT_LIST_DIR}/src/js/lib_wgpu_shader_toy.js"
 )
```

Though that doesn't directly work, as it will receive a BigInt truly in the JS side (as is expected), and library_webgpu.js is not geared up to receive these BigInts:

![image](https://github.com/user-attachments/assets/4f6743cc-9409-451c-8f80-151e3b29e470)

manually sidestepping that via a line

![image](https://github.com/user-attachments/assets/07b203a9-cd04-424f-9d1a-5dbd758744b3)

then runs into another BigInt error at

![image](https://github.com/user-attachments/assets/4480bd4b-3aef-4cfe-a5cc-2fe5f6968df8)

Hope that helps triage the issue further.

**Comment by ypujante** [comment]
@juj Thank you for taking the time to do a deep dive into the issue. I was fairly confident that it was not an ImGui issue, but it is pretty clear now that it is a regression in Emscripten. It definitely affects a lot of projects (I guess all projects using WebGPU...)

The workaround for now is to go back to a prior version of Emscripten like 3.1.66 which does work fine.

**Comment by juj** [comment]
Err, the bug here is as simple that the regressing commit in Emscripten added this `if()`:

![image](https://github.com/user-attachments/assets/7e1a70a6-9278-404f-ae83-f49abaf0312b)

But the problem is that `library_webgpu.js` is processed before `library_sigs.js` where all the WebGPU function signatures live, so at the time that logic is parsed, the signatures don't exist, so `sig?.includes('j')` is always false.

As a local workaround, one can copy all the wgpu signatures from library_sigs.js to library_webgpu.js:

```diff
diff --git a/src/library_webgpu.js b/src/library_webgpu.js
index e7f7ba55d..966caffad 100644
--- a/src/library_webgpu.js
+++ b/src/library_webgpu.js
@@ -1643,6 +1643,197 @@ var LibraryWebGPU = {
     });
   },

+  wgpuAdapterEnumerateFeatures__sig: 'ppp',
+  wgpuAdapterGetInfo__sig: 'vpp',
+  wgpuAdapterGetLimits__sig: 'ipp',
+  wgpuAdapterGetProperties__sig: 'vpp',
+  wgpuAdapterHasFeature__sig: 'ipi',
...
+  wgpuTextureGetDimension__sig: 'ip',
+  wgpuTextureGetFormat__sig: 'ip',
+  wgpuTextureGetHeight__sig: 'ip',
+  wgpuTextureGetMipLevelCount__sig: 'ip',
+  wgpuTextureGetSampleCount__sig: 'ip',
+  wgpuTextureGetUsage__sig: 'ip',
+  wgpuTextureGetWidth__sig: 'ip',
+  wgpuTextureReference__sig: 'vp',
+  wgpuTextureRelease__sig: 'vp',
+  wgpuTextureSetLabel__sig: 'vpp',
+  wgpuTextureViewReference__sig: 'vp',
+  wgpuTextureViewRelease__sig: 'vp',
+  wgpuTextureViewSetLabel__sig: 'vpp',
```

and the WebGPU Shader Toy starts to work again after that. @sbc100 maybe the jsifier needs a custom library sort order so that library_sigs.js gets processed very first? (also I don't remember exactly why couldn't all these signatures live in the respective library_x.js files themselves?)

**Comment by juj** [comment]
Nice marble shader btw :)

![image](https://github.com/user-attachments/assets/02621d5f-6a5c-4e24-b55f-e58f825d0ef4)

**Comment by sbc100** [comment]
> (also I don't remember exactly why couldn't all these signatures live in the respective library_x.js files themselves? That would be cleaner)

This is because `library_sigs.js` is auto-generated, it is a lot simpler to just keep all the generated content seprate from the hand-edit content.   For third party libraries it is still perfectly valid to include `__sigs` in the same file.
