### ISSUE TITLE
Using module in environments without setTimeout, clearTimeout, atob causing memory leak

### ISSUE THREAD

**Issue by hellozyemlya** [emscripten-core/emscripten#22979]
Generated js files provide stubs for that(and probably any other missing\stubbed) functions, and it puts it to global scope, capturing memory and wasm code instances, creating memory leaks.

That happens within audio worklet, for example, with this flags used for compilation:
```
set(EMSCRIPTEN_COMPILE_FLAGS "${EMSCRIPTEN_COMPILE_FLAGS} -O2")
set(EMSCRIPTEN_COMPILE_FLAGS "${EMSCRIPTEN_COMPILE_FLAGS} -mnontrapping-fptoint")
set(EMSCRIPTEN_COMPILE_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -mnontrapping-fptoint")
set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s MODULARIZE=1")
set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s EXPORT_NAME=\"'lyrebird'\"")
set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s EXPORT_ES6")
set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s ENVIRONMENT=web,worker,shell")
set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s POLYFILL=1")
set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -O2 --embind-emit-tsd hello.d.ts -s SINGLE_FILE")
```

**Comment by hellozyemlya** [comment]
As a workaround I adding `globalThis.setTimeout`, `globalThis.clearTimeout` and `globalThis.atob` stubs before calling actual module, that helps avoid leaks.

It seems like globalThis must not be involved at all to avoid such issues in future.

**Comment by sbc100** [comment]
It looks like our polyfills for `globalThis.clearTimeout` and `globalThis.atob` cannot be capturing any state, so I guess it must be `globalThis.setTimeout` that is the issue: https://github.com/emscripten-core/emscripten/blob/eff9671ccb4a68c67c6d000a51f1426272103119/src/shell.js#L321-L322

However it looks like they are only supposed to be installed in the shell environment (such as spidermonkey) and not in an audio worklet.   

It looks like you trying to target the audio worklet environment but without using the `AUDIO_WORKLET` setting?   Is that right?   I don't think we have any testing for that configuration.   One possible fix is to make the above shell.js code explicitly only run if `ENVIRONMENT_IS_SHELL`.. however, given that it is already a very bespoke setup perhaps you existing workaround of adding stubs is good enough.

Finally, does the emscripten module not live as long as the audio worklet you are using?   i.e. I wonder why it matters that you cannot GC the references to it if the lifetime of the audio worklet is the same as the emscripten module?

**Comment by hellozyemlya** [comment]
@sbc100 Thanks a lot for wrapping that. Is there a version that already includes fix? 

Also, quick answers for your questions:
- my module is just a bunch of plain C math that used in JS audio worklet, and I have no idea if AUDIO_WORKLET will help me in any way(can try later a little bit)
- unfortunately there is a reasons to destroy audio-context and respective worklet many times, and this leak prevented that

Anyway, leaking modules is not good regardless of circumstances, its always good to have memory cleaned up, so thanks again.

**Comment by sbc100** [comment]
Yes version 3.1.73 includes this fix.

**Comment by lindell** [comment]
I still get this problem.

<img width="1380" height="586" alt="Image" src="https://github.com/user-attachments/assets/f16444a1-fefe-46d2-a433-35157ec2d134" />

The issue is removed if I either compile Emscripten with the `setTimeout` and `clearTimeout` polyfills removed.
Or
If I call
```js
  delete globalThis.setTimeout;
  delete globalThis.clearTimeout;
```
When I clean up the Worklet node. 

The polyfills should not be refering to the module, so it is a bit unclear why this happens to me. But they are living within a scope that has the module, so that could be why?

Note, I'm using a closure compiled version of the loader, but I don't think that matters?

<img width="528" height="86" alt="Image" src="https://github.com/user-attachments/assets/35593967-e8c4-4986-91ec-44dda0c83a73" />

**Comment by sbc100** [comment]
Hmm, is the case that even for closures that don't access any local scoped variables the local scope is still captured?


@lindell are you building with `-sENVIRONMENT=shell` and then running in an audio worklet?

**Comment by sbc100** [comment]
@lindell can you confirm that the pollyfils in question are indeed basically empty like on the main branch:

```  
  globalThis.clearTimeout ??= (id) => {};                                            
                                                                                     
  // spidermonkey lacks setTimeout but we use it above in readAsync.                 
  globalThis.setTimeout ??= (f) => f(); 
```

I don't see how assigning these closures to globalThis could keep other things module scope alive...   Neither of these closures reference anything from the containing scope, right?

**Comment by lindell** [comment]
> are you building with -sENVIRONMENT=shell and then running in an audio worklet?

Yes! (This is not using the [Wasm Audio Worklets API](https://emscripten.org/docs/api_reference/wasm_audio_worklets.html), but manually initializing the Module in an Audio Worklet) 

> can you confirm that the pollyfils in question are indeed basically empty like on the main branch:

I did run 
```js
      console.log(globalThis.setTimeout);
      console.log(globalThis.clearTimeout);
```
Just before these line (that I've confirmed fixes this issue)
```js
      delete globalThis.setTimeout;
      delete globalThis.clearTimeout;
```

The result in the terminal is:
<img width="201" height="46" alt="Image" src="https://github.com/user-attachments/assets/a78ac14c-18cf-440b-b7b1-1725dde59cd9" />

(They are referring to the code I linked before)

<img width="528" height="86" alt="Image" src="https://github.com/user-attachments/assets/8aca5c8d-e8f8-4703-8b50-8eeb1ee4459b" />

**Comment by sbc100** [comment]
Do you have any idea why these assignments to globalThis would be keeping anything alive?

I'm tempted to say that since your are running in an unsupported configuration (i.e. the code things its running in a JS shell but it isn't)  that a suitable workaround / fix is to simply include those `delete` calls in your post-js?    A more correct fix would be to officially support running emscripten code in an audio worklet directly, but I don't know that we want to add yet another config/environment for this.

**Comment by lindell** [comment]
I find it strange as well. The only explanation is that the entire closure that it is defined in is still kept as a reference (which is still strange why that should be).

I haven't tested, but `post-js`  should not work since this will happen during the init of the Module?

Defining the functions is such a way that is not considered scoped in the same scope as the module should work?

Either:
```js
globalThis.setTimeout = new Function('f', 'f()');
```
But that has implication if users are running CSPs blocking evals.

Or that they actually get defined outside

````js
function applyPolyfills() {
  globalThis.setTimeout = (f) => f();
}

function load() {
  var Module;
   ........
  applyPolyfills();
}
````

**Comment by lindell** [comment]
I'm not sure exactly how these polyfills are used, but from the comment, it seems that it is only used in that function?

"  // spidermonkey lacks setTimeout but we use it above in readAsync."

If that is true. We could (and should) simply not set it in globalcope? But do
````js
   var setTimeout = globalThis.setTimeout ?? (f) => f();
````

**Comment by lindell** [comment]
Adding delete to post-js would not work as described. But what does work is to add
```js
globalThis.setTimeout = (f) => f();
globalThis.clearTimeout = (id) => {};
```
To pre-js. Since this will avoid them being defined within the scope.
