### ISSUE TITLE
Clashed user and system environments

### ISSUE THREAD

**Issue by holub** [emscripten-core/emscripten#23082]
**Version of emscripten/emsdk:** 3.1.72
**Failing command line in full:** `emmake make ...`
**Command and output:** `error: expected member name or ';' after declaration specifiers
        static inline constexpr uint32_t PAGE_SIZE = 0x10000;`

Taking into account huge amount of projects which use the tool, mixing building environment can lead to some dangerous and unpredictable issues.

Please consider following:
* Stop polluting standard headers with architecture headers, and
* Use reserved names for their macros that start with either two underscores or an underscore followed by an uppercase letter?

**Comment by sbc100** [comment]
Can you explain what you mean by "polluting standard headers with architecture headers"?

In terms of the `PAGE_SIZE` macro, that looks like its comes directly from musl libc, not something that emscripten adds: https://github.com/emscripten-core/emscripten/blob/a335879f283a7d309438e346dcf0459054926ca6/system/lib/libc/musl/include/limits.h#L103-L105

Sadly, C was designed without namespace so avoiding collisions with macros from the C library can be a pain.

**Comment by cuavas** [comment]
C and C++ both reserve names beginning with two underscores (e.g. `__name`, `__NAME`) and names beginning with an underscore followed by an uppercase letter (e.g. `_NAME`, `_Name`).  We’ve been making an effort to avoid using these reserved names to avoid portability issues.  It gets very difficult if runtime library maintainers start defining any random generic identifiers as preprocessor macros rather than using the reserved names available to them.

**Comment by sbc100** [comment]
In this case its not emscripten, but the C library (musl) which is defining this symbol.   Unfortunately C doesn't have namespaces so there are some symbols like this one that you might have to care to avoid, or perhaps `#undef`.  Unless its causing issues a lot of use cases (unlikely since musl is used elsewhere, for example, in alpine linux) I doubt we would be patching musl headers to remove these.
