### ISSUE TITLE
mimalloc crash: memory limit above 2GB

### ISSUE THREAD

**Issue by mzukovec** [emscripten-core/emscripten#23200]
**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.73 (ac676d5e437525d15df5fd46bc2c208ec6d376a3)

**Issue**
If using mimalloc via `-sMALLOC=mimalloc` the allocation above 2GB does not seem to work and the program crashes. See the simple reproducible below. It was tested with Chrome Canary and Firefox.

```cpp
// cat main.cpp
#include <iostream>
#include <vector>

int main() {
    std::vector<char> v;
    v.resize(v.max_size());

    std::vector<char> v2;
    v2.resize(v2.max_size() - (64ull * 1024 * 10));
    std::cout << v.size() << '\n' << v2.size() << std::endl;
    return 0;
}
```

Working version:
`em++ main.cpp -o main.html -stdlib=libc++ -pthread -sSHARED_MEMORY=1 -Og -s INITIAL_MEMORY=2GB -s MAXIMUM_MEMORY=4294967296 -sALLOW_MEMORY_GROWTH -sASSERTIONS=1`

mimalloc issue:
`em++ main.cpp -o main.html -stdlib=libc++ -pthread -sSHARED_MEMORY=1 -Og -s INITIAL_MEMORY=2GB -s MAXIMUM_MEMORY=4294967296 -sALLOW_MEMORY_GROWTH -sASSERTIONS=1 -sMALLOC=mimalloc`

**Comment by kripken** [comment]
This starts to work for me if I adjust
```cpp
    v2.resize(v2.max_size() - (64ull * 1024 * 10));
```
to
```cpp
    v2.resize(v2.max_size() - (1024ull * 1024 * 32));
```
That is, the original code aims for `4GB - 640K`, and the working code does `4GB - 32MB`. So it is still able to use almost all the 4GB of memory (and so this isn't a bug related to the 2GB point or such). What I would guess is happening here is that somehow 32 MB are "lost" due to the two huge allocations + various smaller ones, either due to

1. an effect of mimalloc's larger arena sizes than dlmalloc, or
1. mimalloc ends up allocating the two huge (~2GB) pieces of memory direct from the "OS", which for us is emmalloc, so this would be an emmalloc effect.

Either way some amount of variation between allocators is expected, and 32 MB is not a huge amount compared to 4 GB (I mean that even if this is expected and intentional waste, wasting less than 1% of memory in return for efficiency elsewhere sounds reasonable).

cc @kleisauke who may be interested / have other ideas.

**Comment by mzukovec** [comment]
Thanks @kripken. I'll close this one.
