### ISSUE TITLE
Ability to set name of mem file generated...

### ISSUE THREAD

**Issue by equinox2k** [emscripten-core/emscripten#2827]
Would be great to be able to set name and path of the .mem file generated. As currently creates appname.html.mem  appname.mem would be nicer or ability to say js/appname.mem.

**Comment by dixia** [comment]
I have a similar issue. With a pre.js file below:

Module.locateFile = function(x) { return "../external/lib/" + filePath };

and option:

emcc -msse2 -O3 --pre-js pre.js -I../../Common --closure 0 --memory-init-file 1 -s EXPORTED_FUNCTIONS="['_Function1']" Function1JSWrapper.cpp compressor.bc  -o Function1.js


I got a error:

Uncaught TypeError: Cannot set property 'locateFile' of undefined

Which is not really a surprise since Module is not defined. But what is correct way to set locateFile fuction? This looks exactly like how test_browser.py:test_locate_file set the function.

**Comment by dixia** [comment]
I found the reason. I realized the problem is I need to use this declaration with js output file 

var Module = {
  'print': function(text) { alert('stdout: ' + text) }
  'printErr': function(text) { alert('stderr: ' + text) }
};

please just ignore my previous comment
