### ISSUE TITLE
Emscripten sdk installer nsis script?

### ISSUE THREAD

**Issue by trippleflux** [emscripten-core/emscripten#3121]
Because sometime the release installer is not up-to-date, i planned to host my own self-compiled binaries for emscripten sdk, and would love to if you share the nsis offline installer scripts in repo.

**Comment by kripken** [comment]
Interesting, thanks for raising this. ccing @juj who is on vacation right now, but is the right person to talk to when he gets back.

**Comment by juj** [comment]
The release cycle for prebuilt SDK release is fixed to roughly one release per two months. For direct access to the newest versions, there is the option to build latest version directly with emsdk. (Use emsdk install sdk-master-64bit or emsdk install sdk-incoming-64bit). Does that suit your case?

I'm not sure if it would be useful to put NSIS installer scripts to Emscripten repo, because packaging depends on the external LLVM repositories and other tools.

**Comment by trippleflux** [comment]
@juj
I am on windows trying to build branch incoming, and having problems compiling fastcomp-clang on visual studio 2013

146>LINK : fatal error LNK1181: cannot open input file 'Code/emscripten-fastcomp/build/tools/lto/LTO.def'
