### ISSUE TITLE
Emscripten USE_SDL=2 throws errors when building port and complains when run

### ISSUE THREAD

**Issue by ghost** [emscripten-core/emscripten#3139]
Hello,
I am attempting to build an application that uses SDL2. Currently my makefile looks like this:

``` Makefile
CC = emcc

SRCS = main.c util.c
FILES = $(addprefix src/, $(SRCS)) # Add 'src/' to each source
OBJS = $(FILES:.c=.o) # Modify file extensions of FILES

EOPT = USE_SDL=2 FULL_ES2=1 # Emscripten specific options
EOPTS = $(addprefix -s $(EMPTY), $(EOPT)) # Add '-s ' to each option

# Builds necessary files
build: $(OBJS)
    mkdir build
    $(CC) $(FILES) -O2 $(EOPTS) -o build/index.html

# Builds necessary files and cleans up object files, but leaves build directory
dist: build
    rm $(OBJS)

# Cleans up object files and build directory
clean:
    rm -rf build
    rm $(OBJS)
```

The problem is when I run the makefile, I get this output:

``` sh
[harry@harry-laptop Emscripten-WebGL-Engine]$ make
emcc    -c -o src/main.o src/main.c
emcc    -c -o src/util.o src/util.c
mkdir build
emcc src/main.c src/util.c  -O2 -s USE_SDL=2 -s FULL_ES2=1  -o build/index.html
WARNING  root: including port: sdl2
WARNING  root: building port: sdl2
In file included from /usr/lib/emscripten/tools/optimizer/parser.cpp:2:
In file included from /usr/lib/emscripten/tools/optimizer/parser.h:7:
In file included from /usr/lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/iostream:39:
In file included from /usr/lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/ostream:38:
In file included from /usr/lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/ios:38:
In file included from /usr/lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/iosfwd:40:
In file included from /usr/lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/bits/postypes.h:40:
In file included from /usr/lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/cwchar:44:
/usr/include/wchar.h:39:11: fatal error: 'stdarg.h' file not found
# include <stdarg.h>
          ^
1 error generated.
In file included from /usr/lib/emscripten/tools/optimizer/simple_ast.cpp:2:
In file included from /usr/lib/emscripten/tools/optimizer/simple_ast.h:3:
/usr/include/stdlib.h:32:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
         ^
1 error generated.
In file included from /usr/lib/emscripten/tools/optimizer/optimizer.cpp:2:
In file included from /usr/lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/cstdio:42:
/usr/include/stdio.h:33:11: fatal error: 'stddef.h' file not found
# include <stddef.h>
          ^
1 error generated.
```

If I attempt to use make again, everything goes fine, but I get this error in all web browsers:

``` sh
"ERROR: SDL_Init() failed: SDL not built with thread support!"
```

My guess is that somehow SDL2 isn't build correctly once it's included. I attempted to clear the cache and do it again, but I got the same error.

**Comment by kripken** [comment]
Build with `EMCC_DEBUG=1` in the env to see more details. I believe those errors are from the native optimizer, which fails to build on your system. After failing, it marks it as unbuildable and next build, it falls back to the slower non-native optimizer.

For the SDL problem, can you provide a testcase? Not sure what could cause that error. Maybe it depends on what you pass to `SDL_Init`?

**Comment by IcyTesseract** [comment]
Using `EMCC_DEBUG=1` gives me quite a bit of output. Is there anything I'm looking for in particular? The only errors I see are the ones I posted (other than some warnings here and there), but there's more than 8192 lines (my terminal limit) because some of the earlier output is cut off.

As for SDL,  it appears that passing `SDL_INIT_EVERYTHING` causes that error to be displayed. However, `SDL_INIT_VIDEO` appears to work fine.

**Comment by kripken** [comment]
I suspect then that `EVERYTHING` tries to init the `Timer` module, which I guess needs threads. Perhaps we should fix that to not abort, although I'm not sure what the Timer module does precisely.

The debug output is very large when building system libs. First run after clearing the cache might cause that. Second run should be clearer. I imagine it will then say something about not using the native optimizer because it failed to build previously. (This just affects compilation speed though, it's optional.)

**Comment by kripken** [comment]
We could redefine `SDL_INIT_EVERYTHING` to just init what we know can work, but no other target platform seems to, so not sure if that's the best solution. We could just document this issue and leave it there, I suppose.

**Comment by IcyTesseract** [comment]
Is it possible to build Emscripten's version of SDL2 with thread support? I personally don't have any use for anything other than the `Video` module at the moment, but someone might rely on having `SDL_INIT_EVERYTHING` work as it should. If it's not possible, then I agree that it would be best to just initialize what is known to work so no code has to be changed.

**Comment by dreamlayers** [comment]
`SDL_INIT_EVERYTHING & ~(SDL_INIT_TIMER | SDL_INIT_HAPTIC)` succeeds in Firefox. Timer doesn't work because it requires threads, and haptic support also isn't included. `SDL_INIT_AUDIO` requires Web Audio, and causes failure in IE. There is no flag for threads; they are simply initialized by default if they are enabled.

In the SDL2 version of my DOSBox port, I simply don't use `SDL_INIT_TIMER` and call `SDL_GetTicks()` anyways. Yes, that is wrong according to SDL documentation, but it works. Availability of that function is probably important for games. For audio, I use `SDL_InitSubSystem(SDL_INIT_AUDIO)`, and run in no audio mode if that fails.

I think failing in `SDL_Init()` when a requested subsystem doesn't work properly is reasonable. When porting it's a lot easier to understand that failure than than failures later on when trying to use it.

**Comment by IcyTesseract** [comment]
When you say "succeeds" in Firefox, can you give some more information? For example:

- Does it output anything unusual to the console that has to do with the way SDL was built?
- Which version of Firefox is this?
- Which branch of Firefox is this? (Default, Developer, Nightly...)
- Which OS were you using?
- Is there a crash? Or does it silently fail?

**Comment by dreamlayers** [comment]
When I said "SDL_INIT_EVERYTHING & ~(SDL_INIT_TIMER | SDL_INIT_HAPTIC) succeeds in Firefox" I meant that a call to `SDL_Init(SDL_INIT_EVERYTHING & ~(SDL_INIT_TIMER | SDL_INIT_HAPTIC))` succeeds in Firefox. It will work in 35 and Nightly. The way I wrote the parameters to that call shows you which two subsystems are [part of SDL_INIT_EVERYTHING](https://github.com/emscripten-ports/SDL2/blob/master/include/SDL.h#L83) but not successfully initialized, leading to a failure of `SDL_Init(SDL_INIT_EVERYTHING)`.  In other words, I am doing `SDL_Init(SDL_INIT_AUDIO | SDL_INIT_VIDEO | SDL_INIT_EVENTS |  SDL_INIT_JOYSTICK | SDL_INIT_GAMECONTROLLER)`. I said it succeeds. Nothing goes wrong, and there is no unexpected output. I did not test all SDL functionality in all those subsystems however.

If you try using `SDL_INIT_TIMER` then `SDL_Init()` fail and `SDL_GetError()` will return `"SDL not built with thread support"`.

If you try using `SDL_INIT_HAPTIC` then `SDL_Init()` fail and `SDL_GetError()` will return  `"SDL not built with haptic (force feedback) support"`

There is a [dummy haptic driver](https://github.com/emscripten-ports/SDL2/tree/master/src/haptic/dummy) which could be used if you really want to be able to initialize that subsystem.

**Comment by kripken** [comment]
This is where ports builds it: https://github.com/kripken/emscripten/blob/master/tools/ports/sdl.py#L14 so threads are indeed disabled.

Perhaps it's enough here to just emit a clear runtime error if threads or timer are attempted to be initialized. However, I'm not sure if SDL would like the code modified that way.

**Comment by Wohlstand** [comment]
> I simply don't use SDL_INIT_TIMER and call SDL_GetTicks() anyways.

A timer is not `SDL_GetTicks();`, there are timer API which allows you to set up a timer that will run a call on timeout.

**Comment by sherpya** [comment]
I've got this error while passing an oversized dimension to `SDL_CreateWindow()`, look at the comment at the end of:

https://github.com/libsdl-org/SDL/pull/6134
