### ISSUE TITLE
OpenAL alSourcePlay exception

### ISSUE THREAD

**Issue by cloud9370** [emscripten-core/emscripten#3170]
Hello
I'm try to use OpenAL.
alBufferData put the decoded Ogg Vorbis wave data, and then alSourcePlay.

Exception happen on TypeError which report "Cannot read property 'duration' of null, TypeError"
I attach the exception screenshot.
Please help me to solve this problem.

Thanks.

![openal_sourceplay_exception](https://cloud.githubusercontent.com/assets/7732799/6075957/897a67c0-ae17-11e4-9c43-bca5f18db170.png)

**Comment by cloud9370** [comment]
I think I found the problem.

I attach buffer to the source after alGenSources and alGenBuffers, not attach after call alBufferData.

I just trying alSourcei(source[0], AL_BUFFER,buffer[0]) right after alBufferData, and it's work to play sound.

So this issue can close.
Thanks.

**Comment by juj** [comment]
Under no circumstances should any series (that is not explicitly recognized as undefined behavior) of OpenAL function calls result in a JavaScript exception being leaked out from library_al.js out to the user, and instead an OpenAL error should be raised. Even though your usage had an error, the implementation should be more robust here to properly handle the error case.

If you are interested in improving the OpenAL library, feel free to post a test case or a patch for this, so that the behavior would mature to be more robust.

**Comment by cloud9370** [comment]
Thanks for your answering.

Here is my test code
https://github.com/cloud9370/emscripten_test_sdl_png.git
branch master

I fix it on revision aa5971a

If you want to check my test code.
You can check out revision e03bc81

Thanks again.
