### ISSUE TITLE
There are arbitrary environment variable size limitations

### ISSUE THREAD

**Issue by sstewartgallus** [emscripten-core/emscripten#3188]
The code seems to statically allocate a fixed sized buffer for holding environment variable data the first time setting an environment variable happens. I don't understand why this approach is used at all. Shouldn't this code just be regular code that dynamically expands and shrinks the environment using malloc and free?

**Comment by juj** [comment]
I think the environment code is very old, and might even predate the introduction of dlmalloc. In an ideal world, there would not be any restrictions anywhere. I am in favor of having environment code implemented in C to get it in asm.js land, since that would also have the benefit of being thread-safe in the future. It is just that nobody has had the time to do this. What do you think @kripken?

**Comment by kripken** [comment]
Yeah, optimally this would be rewritten in a more flexible way. However, i think it could be fine in normal JS too. I'd be happy either approach.
