### ISSUE TITLE
NODEFS cannot read files from sparse disk image when mounted with absolute path under OSX

### ISSUE THREAD

**Issue by janjongboom** [emscripten-core/emscripten#3222]
I have a sparse disk image (f.e. to have a case-sensitive file system) on OS/X, which is mapped from `/Volumes/repos` to `/Users/janjongboom/repos`. Now when I mount my full file system through NODEFS:

``` js
FS.mount(NODEFS, { root: '/' }, '/test');
```

And then trying to read a file from the disk image through C++:

``` cpp
FILE* fd = fopen("/test/Users/janjongboom/repos/janos/README.md", "r");
```

It fails, because NODEFS readlink() returns `/Volumes/repos`. Which is incorrect. It should take the mountpoint of the filesystem into account, because this folder is mapped on `/test/Volumes/repos`.

Patch in #3223

**Comment by sbc100** [comment]
I now think the fix for this issue was wrong.     If you have links to `/Volumes/repos` in your filesystem, but `/Volumes/repos` is not part of the emscripten VFS then they should not be readable.  i.e. they are effectivly dangling symlinks from the POV of the emscripten filesystem, even though they point a valid location in the external filesystem.

For this kind of thing to would you would either need to mount `/Volumes/repos` inside the VFS, or use NODERAWFS.

**Comment by sbc100** [comment]
We are looking at effectively reverting this change in #21805
