### ISSUE TITLE
Better variable elimination?

### ISSUE THREAD

**Issue by waywardmonkeys** [emscripten-core/emscripten#3233]
Taking this code as an example:

``` javascript
function __ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE4findEcj($this, $__c) {
 $this = $this | 0;
 $__c = $__c | 0;
 var $$0$i = 0, $0 = 0, $11 = 0, $13 = 0, $14 = 0, sp = 0;
 sp = STACKTOP;
 $0 = HEAP8[$this >> 0] | 0;
 if (!($0 & 1)) {
  $11 = ($0 & 255) >>> 1;
  $13 = $this + 1 | 0;
 } else {
  $11 = HEAP32[$this + 4 >> 2] | 0;
  $13 = HEAP32[$this + 8 >> 2] | 0;
 }
 if (!$11) {
  $$0$i = -1;
  STACKTOP = sp;
  return $$0$i | 0;
 }
 $14 = _memchr($13, $__c & 255, $11) | 0;
 if (!$14) {
  $$0$i = -1;
  STACKTOP = sp;
  return $$0$i | 0;
 }
 $$0$i = $14 - $13 | 0;
 STACKTOP = sp;
 return $$0$i | 0;
}
```

We're running the aggressive variable elimination and registerize-harder ...

Can't it get rid of `$$0$i`?

**Comment by waywardmonkeys** [comment]
cc: @chadaustin

**Comment by kripken** [comment]
The eliminator and aggressive variable elimination focus on single-assignment variables. $$0$i isn't single-assignment because the block was split in the relooper (we split return blocks sometimes); also it appears to be a phi variable? Although that part looks odd. Seeing the LLVM IR would clarify.

Registerize harder wasn't run on this code yet, I believe? Not that it would help.

To get this to be eliminated, it would need to be split into several single-assignment variables. But the main issue is that the relooper is spilling the return block - if you really want to reduce code size, you don't want that, even if it runs a little slower due to `label` variable usage. If that sounds interesting to you, I could make `-Os/-Oz` during link disable splitting in the relooper.

A separate issue is that what's going on with the phi here. Might be clearer without splitting.

**Comment by waywardmonkeys** [comment]
> Registerize harder wasn't run on this code yet, I believe? Not that it would help.

That's an interesting question.  I *believe* that it has been ... but now you have me doubting.

**Comment by kripken** [comment]
registerize and registerizeHarder output looks like this:

https://github.com/kripken/emscripten/blob/master/tests/optimizer/test-js-optimizer-asm-regs-harder-output.js

lots of i1, i2, i3 variable names. Should not have llvm variable names like `$$0$i`.
