### ISSUE TITLE
Export function tables directly in "almost asm" mode

### ISSUE THREAD

**Issue by chadaustin** [emscripten-core/emscripten#3359]
Embind performance would be improved if asm.js function tables were exported in "almost asm" mode.  They should be exported with a name that can be looked up via the signature, like Module.FUNCTION_TABLE_viii or whatever.

Then embind could look up a specific function with Module['FUNCTION_TABLE_' + signature][k].

Thanks!

**Comment by kripken** [comment]
I didn't realize this was for embind specifically. I don't think we would want this to be the default behavior in embind, would we? It would mean embind doesn't validate as asm.js anymore.

I do see the value in an option, default off, for embind to use function tables in this way.

Thoughts?

**Comment by chadaustin** [comment]
Indeed, it's for embind specifically, and primarily benefits applications that do a lot of calls between JS and C++.  Those situations may not be a great fit for asm.js anyway due to call overhead.

I agree that this behavior should not be the default: defaulting to validating asm.js makes the most sense to me.

But, in "almost asm" mode, we would benefit from smaller code and faster calls across embind, so I think it's worth turning on in that case.

Does that make sense?

**Comment by kripken** [comment]
Yes. I did though have another idea on this: We could add an option to emulate function pointers entirely, that is, not use asm.js function tables. A function pointer call would be a call to normal JS, where a normal function table exists. So you could inspect and even modify the function table as always. And the code would still be valid asm.js at full speed, just that function pointer calls would be slower. But an option there would be to disable asm validation, in which case AOT-compiling browsers (at least firefox and ie) would lose the asm.js validation speedup, but also not have any significant slowdown on function pointer calls.

What I like about that is that it seems to solve this issue here, but also opens the door to dlopen support, a better option than `RESERVED_FUNCTION_POINTERS`, and maybe allow dynamic linking (although that is blocked on some other stuff as well).

Does that sound sufficient for your purposes in this issue?

**Comment by chadaustin** [comment]
Hm, calls through function tables are very common in general, so it would be unfortunate to make them all a bit slower.  But maybe I'm misunderstanding?  How is this different from simply exporting the function tables in "almost asm" mode?  If the function tables themselves were exported, they could be modified at runtime, enabling the same use cases you describe.

But perhaps I don't fully understand what you're proposing.  :)

cc @waywardmonkeys

**Comment by kripken** [comment]
Exporting them breaks asm.js validation; having them outside in the first place, as proposed here, would validate, but each indirect call would go outside of asm (and back in). I'm actually not sure which would be faster, of those two.

Btw, I noticed we already have an option called `EXPORT_FUNCTION_TABLES`, that exports them - I don't remember how it works, but a quick glance seems to show it does what you want? Or is it not insufficient? (I didn't test it.)

**Comment by chadaustin** [comment]
I understand that exporting tables breaks asm.js today, but I'm personally okay with that, because it's not clear how much of a win asm.js is for us (@waywardmonkeys should have some data soon to see if it's a win or not).

I can clearly imagine how exporting the function tables directly in "almost asm" would be a win for us in fastcomp, but I cannot yet imagine what your proposal looks like.  Would each indirect function call become a function call?  That is, instead of:

FUNCTION_TABLE_xxx[x](...)

You would have:

function outsideAsmJs(x, a, b, c) { FUNCTION_TABLE_xxx[x](a, b, c) }
and then, inside of the asm.js:
outsideAsmJs(x, a, b, c)

?  Would the JIT inline that call?  There are enough questions here that my preference would be to simply export the tables directly in "almost asm" mode.

If I recall correctly, EXPORT_FUNCTION_TABLES was implemented with a huge amount of duplication: it still has the function tables inside of the asm.js module, but then it exports all the functions and rebuilds a table on the outside of the asm.js module too.

**Comment by kripken** [comment]
Yes, basically as you described. JITs should inline that in non-asm mode - but in non-asm mode, the other code would be slower, that's why I'm not sure which would end up faster. Might differ on different codebases.

**Comment by kripken** [comment]
I almost have this implemented. Some numbers from the benchmark suite:

 * Emulating function tables (i.e. the new option that puts them outside of the asm module) preserves full asm.js speed in almost all the benchmarks in the suite, simply because it keeps the code validating as asm.js. This is often a big (2x or more) speedup on Firefox (which AOT compiles asm.js) and Chrome (which runs TurboFan on "use asm").
 * Box2D and Bullet are good stress tests for function pointer calls, numbers for Firefox:

````
box2d
1.00 normal
1.40 emulate
1.69 normal no-asm
1.75 emulate no-asm

bullet
1.00 normal
2.75 emulate
1.94 normal no-asm
1.93 emulate no-asm
````

So either emulation or not having asm can be a significant hit. As expected, the two together is not so bad, as without asm validation, calls into asm are faster and inlining is possible. But it really depends on the codebase what is overall best: emulation with asm.js is faster on box2d, but on bullet it would be good to remove asm.js as well.

And that's for benchmarks stressing pointer calls. As mentioned earlier, in normal calls or pure computation, asm.js will be a big win in all browsers. Overall then, emulating function pointers looks like a useful thing in a significant amount of cases.

**Comment by waywardmonkeys** [comment]
@azakai, a couple of questions:

* What does this new option do to the code size?
* Is there a need anymore for the option added last year to export the function tables?
* What should be the default behavior going forward?
* Do we need an option or should / can this emulation be the new default behavior?

**Comment by kripken** [comment]
* mostly not much. function tables are just moved to a new place. but each entry in them is a little longer because we must do `asm.func` instead of `func` (the function was exported from the asm module)
 * i don't think we need the old option, if @chadaustin and you aren't using it
 * emulation can't be the default, as it is slower; it'll be optional. but it will be necessary for use cases like dynamic linking or direct function table access.

**Comment by waywardmonkeys** [comment]
That sounds pretty good.

We aren't using that option yet as we're trying to move to validating asm.js ... Once this lands and we evaluate things, I'll be able to submit a patch to remove the old option.

*Axe all of the dead things.*

**Comment by kripken** [comment]
Ok, emulated function pointers landed, as `EMULATED_FUNCTION_POINTERS`. All tests pass for me, *except* for `*.test_embind_2`, which fails on `BindingError: No dynCall invoker for signature`. Maybe one of you embind experts could take a look at that?

Once that's fixed, you should just be able to build with that option, and the function tables are on the outside, where you can access them. And as mentioned above, if you are ok with asm.js optimizations turned off, then putting the tables out has practically no detrimental effect.

**Comment by kripken** [comment]
Merged to incoming.

**Comment by kripken** [comment]
embind works now, must have been some fix last week.

This emulated function pointers feature is complete. Testing is welcome. Dynamic linking in fact is complete as well, https://github.com/kripken/emscripten/wiki/Linking
