### ISSUE TITLE
Would be nice to have custom messaging support with --proxy-to-worker, e.g. Module.ccall

### ISSUE THREAD

**Issue by hoongern** [emscripten-core/emscripten#3573]
It would be nice to be able to be able to have a standardized way to 'call' the various `Module` methods in client code. Currently, I added a 'custom' target to the worker/client messaging, along with respective `Module.onCustomMessage` handlers and `postCustomMessage` methods on both the client side as well as in a post-js module include, where I can then use the various Module provided methods directly like `ccall`, `stringToUTF16`, `_malloc`, etc., but if there was a standardized way to do this, that would be nice.

**Comment by kripken** [comment]
The problem though is that we can't do sync calls from a worker, so it would just be an async call to those methods, and the api would therefore not be the same.

**Comment by juj** [comment]
With the SharedArrayBuffer/pthreads support, we will be able to emulate some forms, although passing JS objects across as return values from the `Module['xxx']` functions would not work. That however will be quite experimental, since SAB/pthreads has not yet been adopted, and the spec is still a draft.
