### ISSUE TITLE
getting ERROR root: no input files when configuring leptonica with emscripten.

### ISSUE THREAD

**Issue by harshajayaweeraXHJ** [emscripten-core/emscripten#3581]
I'm getting this error when i run emconfigure ./configure with leptonica.

checking dynamic linker characteristics... ERROR    root: no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.C', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '.bc', '.o', '.obj', '.lo', '.dylib', '.so', '.a', '.ll', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')

What is the reason for this error. How do i fix this.
I'm bit new to cmake and build system stuff. If someone can help me with this then it would be great.

**Comment by kripken** [comment]
You need to look in the configure script (maybe config.log can help too) to find out how it invokes emcc, that causes it to emit that error. Then, the error message explains what is wrong and what you need to do.

**Comment by juj** [comment]
`./configure` invokes Unix autotools automake -based configure scripts. CMake is a separate build system that does not use `./configure` scripts, but comes with `CMakeLists.txt` files. If you are using `./configure`, that does not relate to CMake at all.

That said, `./configure` scripts typically need some amount of teaching/porting so that they understand to target Emscripten. Some scripts work out of the box (seems to be rare these days), and some can require quite a bit of work. If the project comes with a `CMakeLists.txt` file, you can try invoking `emcmake cmake /path/to/leptonica/` to try to build it via CMake, although CMake scripts can equally need some amount of teaching to target Emscripten.

**Comment by harshajayaweeraXHJ** [comment]
Thanks. I will look into that also. however i started build tesseract-ocr with visual studio using emscripten since their tesseract vs-bundle contains the all the header files and libs they need. but i'm getting some errors with it. I posted an issue for that and please could you take a look at it and provide a solution.
