### ISSUE TITLE
Something is optimising away the IMG_LoadPNG_RW set of functions.

### ISSUE THREAD

**Issue by AmandaCameron** [emscripten-core/emscripten#3605]
I'm not sure what, but [this](https://gist.github.com/dbf13627721bd4ac68cc) is as minimum a test I could whip up.

However it's also failing with my custom SDL_RWops implemtation.

This is severly impacting my game engine's ability to run, as I heavily rely on the use of custom data packs for the tilesets.

Any feedback is appreciated.

**Comment by kripken** [comment]
Emscripten's SDL 1.x support is only partial, and it looks like we don't support that method. Another option is to use SDL2 and SDL2_image, which are in [emscripten ports](http://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#emscripten-ports). I didn't check, but since those are just ports of the original codebases, I believe that method would work there.

**Comment by Daft-Freak** [comment]
The default ports build of SDL2_image doesn't link against libpng so you can only load PNGs that have been preloaded. If you built it manually with libpng enabled it should work.

**Comment by kripken** [comment]
We do have libpng in ports now, so building with `-s USE_LIBPNG=1` should work. I don't know if we automatically do that when sdl2_image is used, perhaps we should.

**Comment by Daft-Freak** [comment]
We would also need to -DLOAD_PNG when building SDL2_image. It seems that currently the build doesn't enable ANY formats. Every format except jpeg, webp and tiff can be enabled without any dependencies, but would probably make the default build a bit bigger.
