### ISSUE TITLE
Throwing raw strings and numbers makes debugging unnecessarily difficult

### ISSUE THREAD

**Issue by evanw** [emscripten-core/emscripten#3655]
Why does the compiler throw raw strings and numbers all over the place? This is really bad practice. JavaScript debugging is oriented around the Error object, which has a "stack" property with the stack trace. I have spent literally all day debugging an emscripten-compiled app in node (where our test runner is) because of this issue.

This unfortunate code is everywhere in the compiler:
- https://github.com/kripken/emscripten/blob/f5bc4226bf4f54422951ddf2e69eda2e0f1631bc/src/postamble.js#L79
- https://github.com/kripken/emscripten/blob/f5bc4226bf4f54422951ddf2e69eda2e0f1631bc/src/postamble.js#L296
- https://github.com/kripken/emscripten/blob/f5bc4226bf4f54422951ddf2e69eda2e0f1631bc/src/postamble.js#L362
- https://github.com/kripken/emscripten/blob/320d6377752a2aa04ee484d71e40eadc05d0a90b/src/preamble.js#L923
- https://github.com/kripken/emscripten/blob/86b7039e97e24bb3ad1062d6f049c6b0f460f4d4/src/runtime.js#L54
- https://github.com/kripken/emscripten/blob/86b7039e97e24bb3ad1062d6f049c6b0f460f4d4/src/runtime.js#L64
- https://github.com/kripken/emscripten/blob/86b7039e97e24bb3ad1062d6f049c6b0f460f4d4/src/runtime.js#L273
- https://github.com/kripken/emscripten/blob/86b7039e97e24bb3ad1062d6f049c6b0f460f4d4/src/runtime.js#L359
- https://github.com/kripken/emscripten/blob/86b7039e97e24bb3ad1062d6f049c6b0f460f4d4/src/runtime.js#L398
- https://github.com/kripken/emscripten/blob/667dcd241886fdb878e248d95d8e03abb09c80b7/src/library.js#L3766
- https://github.com/kripken/emscripten/blob/667dcd241886fdb878e248d95d8e03abb09c80b7/src/library.js#L3770
- https://github.com/kripken/emscripten/blob/667dcd241886fdb878e248d95d8e03abb09c80b7/src/library.js#L3962
- https://github.com/kripken/emscripten/blob/667dcd241886fdb878e248d95d8e03abb09c80b7/src/library.js#L4110
- https://github.com/kripken/emscripten/blob/667dcd241886fdb878e248d95d8e03abb09c80b7/src/parseTools.js#L1318
- ... and many more places too

Why doesn't emscripten use Error objects? The raw number thrown in [__cxa_throw](https://github.com/kripken/emscripten/blob/667dcd241886fdb878e248d95d8e03abb09c80b7/src/library.js#L3881) which calls out to [makeThrow](https://github.com/kripken/emscripten/blob/667dcd241886fdb878e248d95d8e03abb09c80b7/src/parseTools.js#L1318) is particularly painful.

**Comment by kripken** [comment]
For things like the first link,

````
throw 'could not load memory initializer ' + memoryInitializer;
````

we just throw a string because the browser console will generally show you a stack trace anyhow. But I agree that using `Error` objects is preferable, a pull request would be great.

The case of `makeThrow / __cxa_throw`, however, is different. We emulate C++ exceptions by throwing integers, where the integer is simply the C++ pointer. This is more efficient than throwing a JS object each time (and our C++ exceptions code is already fairly slow due to JS and asm.js limitations). For debugging C++ exceptions, we have an `EXCEPTION_DEBUG` option. I am open to suggestions for how to improve this.

**Comment by kgryte** [comment]
I second @evanw: throwing strings rather than exceptions create issues when debugging. Of late, I have been writing Node.js packages which attempt to load a `wasm` module. If loading fails, I fall back to an `asm.js` implementation.

However, because strings are thrown, the common `instanceof Error` check fails to capture the load failure and tracking down where the string is thrown and why becomes quite difficult.

At least for my use case, throwing exceptions in the glue code code would be highly beneficial.

**Comment by kripken** [comment]
Yeah, I think there is consensus about throwing proper exceptions instead of strings. Hopefully someone will write a PR eventually.
