### ISSUE TITLE
Meteor platform not recognised

### ISSUE THREAD

**Issue by marcogillies** [emscripten-core/emscripten#3687]
I've tried using some emscripten ported code on [meter](https://www.meteor.com), but it throws an error. 

```
ReferenceError: print is not defined
     at app/server/lda.js:91:43 
```

(lda.js is my compile emscripten file). A bit of digging around revealed that this was to do with setting the environment. It had been set to ENVIRONMENT_IS_SHELL. This is due to this code:

```
var ENVIRONMENT_IS_NODE = typeof process === 'object' && typeof require === 'function';
var ENVIRONMENT_IS_WEB = typeof window === 'object';
var ENVIRONMENT_IS_WORKER = typeof importScripts === 'function';
var ENVIRONMENT_IS_SHELL = !ENVIRONMENT_IS_WEB && !ENVIRONMENT_IS_NODE && !ENVIRONMENT_IS_WORKER;
```

Shell is what it gets set to when no other platform is matched. So this means that my platform doesn't match any of the other platforms. This isn't surprising, because I'm running it as meteor server environment, which doesn't expose the full node api. It is actually closest to the Web environment (because meteor mirrors the same api on both server and client) and it seems to work if I hack it so that it thinks it is the web platform (but I haven't tested it in detail yet). 

It would be great if meteor could be added as a formal platform, I think it would be enough for it to be equivalent to web.

**Comment by kripken** [comment]
We are hoping to clean up that environment detection code at some point, so that builds don't contain code for all environments, but rather just for one. So I would prefer to not add more emitted-by-default environment code, if possible. What do you think of these options:

1. Add a `METEOR` compiler flag to emscripten. Or perhaps `FORCE_ENVIRONMENT` whose value could be 'meteor'. When that is set, we'd include meteor code.
2. Work around this in meteor or in your code, just defining `var window = {}` should convince the environment code that is on the web.

**Comment by marcogillies** [comment]
I am happy to work around for now if there are better solutions coming
