### ISSUE TITLE
std::thread error on exit

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#3721]
This std::thread example fails during exit, an atexit looks invalid

```
// thread example
#include <iostream>       // std::cout
#include <thread>         // std::thread

void foo() 
{
  std::cout << "foo\n";
}

void bar(int x)
{
  std::cout << "bar " << x << "\n";
}

int main() 
{
  std::thread first (foo);     // spawn new thread that calls foo()
  std::thread second (bar, 123);  // spawn new thread that calls bar(0)

  std::cout << "main, foo and bar now execute concurrently...\n";

  first.join();                // pauses until first finishes
  second.join();               // pauses until second finishes

  std::cout << "foo and bar completed.\n";

  return 0;
}
```

Building with `-s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=2 -o a.html -std=c++11`

**Comment by kripken** [comment]
cc @juj

**Comment by VirtualTim** [comment]
Hey I found this issue when looking through the other multithreading issues. I was able to compile and run this successfully (latest Firefox and Chrome), output:
> main, foo and bar now execute concurrently...
> bar 123
> foo
> foo and bar completed.

I don't know if piping to cout gets sent to the main thread, because if so it could be race-y, but it seems to work.

Might be worth seeing if you can still reproduce?

**Comment by kripken** [comment]
Thanks, yes, this does look like it works now.
