### ISSUE TITLE
--emit-symbol-map doesn't work when --closure 2

### ISSUE THREAD

**Issue by svetlin-mladenov** [emscripten-core/emscripten#3743]
No symbol map is generated when --closure 2. Even the .symbols files doesn't get created.

When --closure 1 everything works as expected.

**Comment by kripken** [comment]
When closure 2 is used, we let closure do all the minifying. I tried to use closure's option to get the symbol map, but it looks like it does not emit everything we need, see 91cc2166441dea9bbc0fbb3cc394572d4b382539.

I suspect the problem is that all our asm.js code is inside a function, so closure thinks they are locals, and it doesn't emit mapping info for them. But perhaps there is a way to do it in closure that I couldn't find?
