### ISSUE TITLE
sigwait, sigsetjmp, sigsuspend

### ISSUE THREAD

**Issue by httpdigest** [emscripten-core/emscripten#3793]
Are those functions planned to be supported with pthreads on incoming?
I am not quite sure what exactly they do, but the program I want to build (jamvm) makes use of these. :)
Other functions like `sigfillset` and `sigdelset` already seem to be supported, at least emcc did not complain when compiling and linking a program that was using those functions.

**Comment by juj** [comment]
The functions `sigsetjmp` and `siglongjmp` should be possible to support, since they are just a save and restore signal mask -form of `setjmp` and `longjmp`.

Web workers have a limitation that it is not possible to pre-empt/interrupt execution of a worker from another worker, except to `.terminate()` it. That means that it will not be possible to interrupt a thread to pass "delivered signals" asynchronously to it. We could emulate this by cooperatively polling for pending signals in each thread to simulate interruption, but it won't be perfect.

The functions `sigwait` and `sugsuspend` are about cooperatively handling "accepted signals". This would not require interruption, so it should be possible technically to add support to those functions. However I don't know of anyone who'd be working on it currently. If you have a test case of what kind of code patterns you need to get working, we could take a look to see how much of signals we'll need to add.

**Comment by httpdigest** [comment]
Thanks a lot for the explanation of these functions and the limitations of web workers! Like you said, it could maybe be possible to achieve the desired things without having to interrupt (or poll). Here is the snippet of the source code of JamVM ((c) Robert Lougher) that uses these functions:

```C
void disableSuspend0(Thread *thread, void *stack_top) {
    sigset_t mask;

    thread->stack_top = stack_top;
    thread->suspend_state = SUSP_BLOCKING;
    MBARRIER();

    sigemptyset(&mask);
    sigaddset(&mask, SIGUSR1);
    pthread_sigmask(SIG_BLOCK, &mask, NULL);
}

...

void classlibSignalThread(Thread *self) {
    sigset_t mask;
    int sig;

    sigemptyset(&mask);
    sigaddset(&mask, SIGQUIT);
    sigaddset(&mask, SIGINT);

    disableSuspend0(self, &self);
    for(;;) {
        sigwait(&mask, &sig);

        /* If it was an interrupt (e.g. Ctrl-C) terminate the VM */
        if(sig == SIGINT)
            exitVM(0);

        /* It must be a SIGQUIT.  Do a thread dump */
        printThreadsDump(self);
    }
}
```
So it looks like `sigwait` and the other functions are indeed used to pass signals from one thread to another.
I would of course also like to use other maybe Emscripten-specific functions to achieve the same functionality.

**Comment by httpdigest** [comment]
Hey, sorry, is this above all information you need to devise a possible signal.h implementation or tell whether that is possible?
Please tell me if there is anything more information you need.

**Comment by juj** [comment]
I believe we should have all that is needed here, however I can't jump on implementing this just yet. I'll try to find some time once I clear my work queue. If you want to give a try, or if you can extract minimal standalone test cases to add to our test suite, that would be helpful here.
