### ISSUE TITLE
emscripten_wget seems to run asynchronously when executed in the context of a Firefox Addon

### ISSUE THREAD

**Issue by crankycoder** [emscripten-core/emscripten#3828]
I'm having trouble getting emscripten_wget to write to a file when I run the emscripten'd JS from within an add on.

The code in: https://github.com/crankycoder/minimal_addon

The README file shows how to run the code, but the same generated JS runs as expected from within the Emscripten auto-generated code when run in the default emscripten demo.

When I run it from within an addon with minimal patching to allow it to be imported from other JS, I get really weird behavior. That is - emscripten_wget seems to run asynchronously when I explicitly specify synchronous operation.

**Comment by kripken** [comment]
It sounds like there is more JS on the call stack that is allowed. The emterpreter-async magic works because we have the power to save and restore the call stack for interpreted code that we manage ourselves. But we can't do anything for normal JS. If you have

````
function normalJS() {
  console.log('before');
  Module.ccall( .. some emterpreter sync function .. )
  console.log('after');
}
````

Then you will see `'after'` printed **immediately**, because the synchronous operation returns. It has to return, since it can't really be synchronous. It will appear to be synchronous to the compiled code, though, because we manually pause the emterpreter and then continue it when the async operation is done.
