### ISSUE TITLE
Build on Windows 8

### ISSUE THREAD

**Issue by chefhj** [emscripten-core/emscripten#3885]
I am a student working on a research project and I cannot get emscripten to install the proper binaries for any of the compilers on windows.  In binaries, all I get is an executable called elevate but no emcc.  When I try installing latest updates it returns 1 and states it was unable to install. 
Any ideas?

**Comment by juj** [comment]
This could be https://github.com/juj/emsdk/commit/89df87a4608d07bdde92bf2e2fa1356aa8ebfa89 . Can you try using one of the full SDK installers?

**Comment by juj** [comment]
Emscripten 1.35.0 was released today, see https://groups.google.com/d/msg/emscripten-discuss/TW-AvHt-lc4/_59T4YBxBQAJ . The installers for those fix a known problem with emsdk installer attempting to build from source rather than trying to use a precompiled version. Can you try the new version if the issue still manifests? If it does, what is the output?
