### ISSUE TITLE
const in generated output?

### ISSUE THREAD

**Issue by waywardmonkeys** [emscripten-core/emscripten#3920]
In the IMVU build, I removed these flags from calling clang (as we call it directly):
- `-fno-vectorize`
- `-fno-slp-vectorize`

Doing that caused our (ancient) version of the Google closure compiler to blow up:

```
ERROR - Parse error. Unsupported syntax: CONST
            const Jh = la(0);
^
```

The source involved here was:

``` javascript
            var Fh = mg.abs;
            var Gh = mg.reciprocalApproximation;
            var Hh = mg.reciprocalSqrtApproximation;
            var Ih = la(0);
            const Jh = la(0);
            function Kh(newBuffer) {
                if (q(newBuffer) & 16777215 || q(newBuffer) <= 16777215 || q(newBuffer) > 2147483648) return false;
                i = new a(newBuffer);
                j = new b(newBuffer);
                k = new c(newBuffer);
                l = new d(newBuffer);
                m = new e(newBuffer);
                n = new f(newBuffer);
                o = new g(newBuffer);
                p = new h(newBuffer);
                buffer = newBuffer;
                return true;
            }
```

Why the `const`?

**Comment by waywardmonkeys** [comment]
Oh, we're on a version from around 1.34.7 ... so maybe this has been fixed since then?

**Comment by kripken** [comment]
Looks like we still have `const` there (for the float32 zero). However, why not use the default closure emscripten bundles?

**Comment by waywardmonkeys** [comment]
Because of legacy ...

Some of the build machines (and developer machines) still only have Java6, so we're locked at the last version of Closure that supported Java6.

Where is this ``float32`` zero getting set up? I'm happy to submit a pull request, just don't know where to find the offending code.

**Comment by kripken** [comment]
In `emscripten.py`, but I don't think we can change it - it's intentionally a `const`, because that `fround(0)` is actually a perf-sensitive value. It's a constant, that we emit as a global just because of code size. But we definitely don't want the engine to think it could change, so we mark it as `const` to help engines optimize.

We could have an option for this, though, if that would be useful.

However, why is it emitted for you? Causes could be either you set precise float, or you have SIMD code that needs precise float. I assume the latter based on the beginning of the bug. But do you want that SIMD code?
