### ISSUE TITLE
Support SIMD up to SSE4.1

### ISSUE THREAD

**Issue by wshager** [emscripten-core/emscripten#4030]
Quoting https://github.com/lemire/simdcomp/issues/10#issuecomment-170158051:

"Some non-SSE2 SIMD instructions we use (e.g., pshufb) cannot be emulated using SSE2 instructions. So you need to write the SIMD register to memory, reload it into regular registers, do the computation, then reload a SIMD register. That's going to be atrociously slow in some cases.

Even when the SIMD instruction can be emulated with SSE2 instructions (e.g., pmaxud), it may involve more operations than a non-SIMD algorithm would use. On the whole, you may end up with a significantly worse latency and throughput."

Please consider supporting (up to) SSE4.1

**Comment by wshager** [comment]
Well, I can't tell if it's Emscripten that doesn't support SSE4.1, or rather SIMD.js.

**Comment by wshager** [comment]
SIMD.js supports for example shuffling of all types.

**Comment by juj** [comment]
SSE3, SSSE3 and SSE4.1 support are planned to be added, but we haven't gotten around to that yet.

One thing to note is that we cannot guarantee performance with the SIMD instruction sets. We can develop support to make sure that C/C++ code depending on those intrinsics will compile so that one won't need to add Emscripten-specific #ifdef paths, but a good portion of the instructions will need to be emulated in scalar operations in the cases where SIMD.js does not have a direct mapping. Shuffle instructions are one place where good performance is expected, but in the first generation of SIMD.js, other SSE3+ instructions will be a hit or miss whether they'll be faster, depending on what functionality SIMD.js offers.

SSE3 has 11 intrinsics, SSSE3 has 32 intrinsics and SSE4.1 has 61 intrinsics. Ideally we'll add support for these in the chronological order, though it will need a bit of work given that there are so many. If you have a list of intrinsics that you are currently depending on that are missing, we could work on adding those first before doing the full house, that might be a bit faster, and you wouldn't need to have to go #ifdeffing that much.

**Comment by wshager** [comment]
@juj thanks. For https://github.com/lemire/simdcomp the following instructions are currently required (at most):
SSE4.1: PMAXSB, PMAXSD, PMAXUD, PMAXUW, PMINSB, PMINSD, PMINUD, PMINUW, PEXTRB/PEXTRD/PEXTRQ,
SSE3: PSHUFB

**Comment by juj** [comment]
Emscripten does not support assembly instructions on SIMD, but only intrinsics forms. Mapping to the intrinsics, does this mean that the needed intrinsics would be `_mm_max_epi8, _mm_max_epi32, _mm_max_epu32, _mm_max_epu16, _mm_min_epi8, _mm_min_epi32, _mm_min_epu32, _mm_min_epu16, _mm_extract_epi8, _mm_extract_epi32, _mm_extract_epi64` for SSE4.1, and for SSE3 the function `_mm_shuffle_epi8`?

**Comment by wshager** [comment]
Correct, I believe those are the corresponding intrinsics.

**Comment by wshager** [comment]
It would be very useful to find out what intrinsics correspond to SIMD.js in the tc39 spec. Is this document still relevant:
https://docs.google.com/spreadsheets/d/1QAGGf2M2IA6l4cvh8eTXdXGEUcPjdmTe_BLKGn5YCB4/htmlview

**Comment by juj** [comment]
The above pull requests have been merged, so there is now complete SSE3 and SSSE3 support, as well as preliminary SSE4.1 support which should cover the abovementioned functions.

Keeping this issue still open to track the inclusion of full SSE4.1, which will likely occur some time post GDC.

**Comment by wshager** [comment]
@juj I'd like to try out incoming, but I can't build it. See #4105

**Comment by wshager** [comment]
Compilation succeeds, but unfortunately there's no performance gain AFAICT.
