### ISSUE TITLE
Intermittent browser errors

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#4072]
I am seeing a lot more intermittent browser suite failures. For example in `browser.browser.test_glgears_proxy` which runs a lot of tests, it's likely that at least one fails and it errors.

Was there a recent change that could explain this? cc @juj

**Comment by juj** [comment]
On my Macbook Pro the test `browser.test_glgears_proxy` succeeded each time when running consecutively 10 times. On Windows desktop PC, ran 5 times and each of them failed. I'll dig into this closer.

**Comment by juj** [comment]
Oh, regarding your question - I can't think of any specific change, except perhaps the timing related commit I authored recently which began to wait until a server is up. I'll check if that can have any effect here.

**Comment by kripken** [comment]
This blocked me from merging to master today. I got 14 errors, almost all of which look intermittent, but a few of which I wasn't totally sure about like `browser.test_gles2_emulation` - which runs a bunch of tests in succession, so the chance of an intermittent is just high. I tried 10 times and it always failed, at a different point.

**Comment by juj** [comment]
Windows and linux bots are now fully green on the browser suite http://clb.demon.fi:8112/builders/ubuntu-incoming/builds/1338/steps/browser%20suite%20-%20firefox%20stable/logs/stdio and http://clb.demon.fi:8112/builders/win-incoming/builds/1192/steps/Tests-browser-firefox-stable/logs/stdio. OS X bot should be ignored for now due to system bug. The above changes look good, the only intermittent error I'm seeing on Windows/linux systems now is the `other.test_cmake` test on Windows, which seems to have a pattern of passing exactly on every second run, and failing on every other time.
