### ISSUE TITLE
Stop exporting runtime methods by default?

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#4085]
I would like to set `EXPORTED_RUNTIME_METHODS` to `[]` as its initial value. That means that we would export no parts of the runtime by default, and really make our `-O2` of hello world small.

The benefit here is that many programs don't need anything exported, if all they have is compiled C/C++ code. In addition, if a runtime method is only used in the full output - i.e., inside --pre-js, EM_ASM contents, etc., but not in a totally separate script tag - then that would work too (as we rely on JSDCE to automatically remove stuff, and JSDCE would see it it being used).

The downside is that when people want e.g. `ccall` from a separate script tag, they would need to mention that when building (on `EXPORTED_RUNTIME_METHODS`). Some current projects would need to be updated, therefore.

Thoughts?

**Comment by lucidvizion** [comment]
I think the downside you mentioned is a rather large downside.  Many of the current exported functions are an absolute requirement if you want to use your compiled C/C++ code as a shared library for a web-centric application(i.e. an existing JS application you're not compiling along with emcc).

While I personally wouldn't be too hurt by the change, it may raise the barrier for entry for newer users.  Just my 2c.

**Comment by juj** [comment]
I am not worried at all about new users or the barrier, that should be solvable via documentation, but what I am a bit worried is existing code breaking for a lot of developers.

I wonder if we would instead rather document `-s EXPORTED_RUNTIME_METHODS=[]` specifically as a good way to remove all interop facilities when one doesn't need them as a way to minimize emitted code size?

**Comment by kripken** [comment]
We could emphasize that more, but most users wouldn't see it, I suspect.

I do think the more sane default is to export nothing. We should have done it all along, probably, but I just don't think we should avoid making this optimal just because of legacy. Yes, there are downsides to changing this, but it would be a temporary bump.

**Comment by kripken** [comment]
Regarding concerns about existing projects being surprised, I think we can do what we now do for the recent filesystem change - in ASSERTIONS builds, we can export stubs that show a clear error, for the previously-default-exported things. That means that if a project sees something not working, they'll get clear instructions in an ASSERTIONS build for how to easily do the one-time fix.

**Comment by juj** [comment]
Looking at the list of things we do export: https://github.com/kripken/emscripten/blob/incoming/src/settings.js#L320, I see there are the `ALLOC_xxx` enum items that would probably at least be surprising since they are not functions, but "enum-like" symbols. Does the `__deps` machinery extend to these so that e.g. `allocate()` could depend on all of `ALLOC_xxx`?

Although, aren't `allocate()` and `ALLOC_xxx` always required, since our runtime is hardwired to depend on those starting up? Which of these items could we remove in the simplest `hello_world.c` case where the user code does not have any interop?

Do you have an estimate how much would we save by this change? I do like the goal of being able to "scale small" in the smallest `hello_world.c` case, though let's investigate a bit what the disruption would be, and how it could be minimized.
