### ISSUE TITLE
A mechanism is needed for handling constructor functions with the LLVM wasm backend.

### ISSUE THREAD

**Issue by dschuff** [emscripten-core/emscripten#4218]
When using the JSBackend, the backend emits a list of initializers with the metadata, which emscripten reads. For each initializer, it generates a JS function which calls the initializer and pushes it onto the `__ATINIT__` variable in the final JS file. A function called before main iterates over that variable and calls each function.

On modern ELF platforms, the compiler emits a pointer to each initializer function into a special section, `.init_array`. The linker creates symbols `__init_array_start` and `__init_array_end` which point to the start and end of this section. Code in the executable (e.g. in the `_start()` function of a statically-linked executable) can iterate over the array using these symbols to call each initializer, and a dynamic linker can read the section directly.

We need a mechanism to accomplish this purpose for wasm. Wasm has no direct analog to sections, but it does have a mechanism to specify the entry point (a.k.a. start function) for a module (https://github.com/WebAssembly/design/blob/master/Modules.md#module-start-function). This mechanism is sufficient for statically linked binaries to work as they do on native platforms; a function could be defined which iterates over the array and calls the constructors, and linked into the executable (e.g. as part of libc or a crt file). It would be called by the modules entry function. This could be made transparent to emscripten, which could continue to use its existing `__ATINIT__` mechanism if there were Javascript functions that also needed to run before the module runs.

**Comment by dschuff** [comment]
For dynamic linking, things get a little bit more interesting; we need a way for modules to specify their constructor functions in a way that can be used by a dynamic linker, in the absence of a single entry point. This could simply be a functional interface (e.g. the dynamic linker calls a particular function which returns a list of constructors to call), or some way to specify the constructors as data; in any case this doesn't need to be decided right away.

**Comment by kripken** [comment]
In other words, either in the LLVM backend, or in s2wasm, we would translate the ctors list into a single start function, and then that is guaranteed to be called when the module is loaded, as the wasm VM will call the start function for us?

A tricky issue might be ordering. Consider a global ctor that depends on files being preloaded. Those would need to be in wasm's linear memory before the start method is called. Currently that is not true since wasm provides its own memory, but the spec is changing, so that might be ok. However, the linear memory might be in a separate file for various reasons. And the same type of issue recurs if those files are placed into memory by JS or something else that might be async. Also, it might be nicer to instantiate the module in one frame, and call ctors in another, to reduce total noticeable pause time.

To put it another way, forcing global ctors to run when the wasm module is instantiated is a pretty strong constraint, which can make startup tricky and/or prevent some optimizations there. Instead, I'd recommend letting the outside runtime run the ctors, at the proper time. That's how emscripten works now, it knows when files have been preloaded, when linear memory has been initialized with the static data, etc., and it then calls the ctors.

In more detail, I'm proposing that s2wasm parse the `init_array` stuff into metadata that it emits alongside the other metadata it already has (like locations of globals). The driver calling s2wasm then already knows what to do with those ctors. (That data could also help a linker in dynamic linking some day.)

In that proposal, two options here could be for s2wasm to emit just one method, after creating a new method that calls the others, or it could emit the list of methods. A slight benefit to the latter is that it could be made async, i.e., split up the startup execution into multiple frames, and thus reducing the largest noticeable pause. Not a big deal for most apps either way, but some have tons of ctors.

**Comment by dschuff** [comment]
Actually what I'm proposing is not to have s2wasm translate the ctors list into a function but for it to allocate space in the linear memory for an array of pointers to the initializer functions, and create a symbol that points to that array. The function that actually calls them would be just user code from the perspective of LLVM, s2wasm, and emscripten. This is pretty analagous to how it works for modern native systems.

Now, wrt ordering.
It's actually not exactly clear from the wasm design doc when the start function is expected to be called. I think we should actually put that under the control of the user (e.g. the JS runtime, emscripten in this case). e.g. there could be some method on the object returned by `Wasm.instantiateModule`, or whatever other mechanism is exposed to the JS code. It could be something as simple as exposing which function is the entry function and requiring the JS code to call that first (as opposed to calling the entry point automatically), or something fancier. But in any case, emscripten could instantiate the module, then do whatever setup it needed, then call the entry point to kick things off.

**Comment by dschuff** [comment]
Come to think of it, this is actually already possible today; instead of using the start function mechanism we could just have a convention about which function is the entry point, and do exactly what I described. Then when the start function mechanism is implemented the way we want, we can switch.

**Comment by kripken** [comment]
Having a literal array of function pointers has the downside that it takes space in the function table. These are called statically and only once, so that seems a little unnecessary. Instead we can just export them, and provide their names as metadata.

Or, we could have a single userspace method that calls them statically, and we export just that. However, that has the downside of not being able to async those calls, so I recommend the former.

**Comment by dschuff** [comment]
You mean that it takes up space in the linear memory (not the function table), right? That's a pretty small overhead. The functions are already in the function table anyway.

**Comment by kripken** [comment]
I meant the indirect function table. For there to be an integer that represents a function in linear memory, it must be in the indirect function table, and called via call_indirect.

**Comment by dschuff** [comment]
Current status for the record:
I implemented a quick hack in #315 to create emscripten metadata for initializers to get this unblocked so we can test more stuff. 
Currently SpiderMonkey requires the linear memory to be allocated inside the `Wasm.instantiateModule` call, and both SM and V8 run the start function before `Wasm.instantiateModule` returns. So practically this means that emscripten cannot use the start function feature for now. If we eventually decide that we want to separate the allocation of linear memory from module instantiation (which I think people generally agree with, provided that the allocation can be specialized for wasm), then we could revisit that if we wanted to, but it wouldn't be strictly necessary.

I do still want to eventually allow making the initializers self-contained by linking in a `_start` function which calls the initializers and then main. Use of this should be compatible with whatever emscripten does, and it might end up being useful to allow use of different versions of that for different situations, but that can be for the future.

**Comment by palant** [comment]
Note that this issue currently makes it more complicated to run the compiled WebAssembly code without Emscripten boilerplate - you have to figure out which initializers to run. Having a start function that calls initializers automatically on module load would make things considerably easier, even if this functionality is hidden behind a flag.
