### ISSUE TITLE
Module['websocket'] undefined

### ISSUE THREAD

**Issue by Enhex** [emscripten-core/emscripten#4284]
# I try to use JavaScript-side WebSockets using Embind (using `val::global("WebSocket")`) with emscripten_set_socket_*_callback, but when I run the compiled script I'm getting an error because `Module['websocket']` is undefined:

```
MyExecutableName.html:1254 exception thrown: TypeError: Cannot read property 'on' of undefined,TypeError: Cannot read property 'on' of undefined
    at ___set_network_callback (http://localhost/urho/web_http_test/MyExecutableName.js:1:165739)
    at _emscripten_set_socket_open_callback (http://localhost/urho/web_http_test/MyExecutableName.js:1:165842)
```

The 'on' is part of this line:
`Module["websocket"]["on"](event,callback?_callback:null)`

I'm not using any native sockets in case that's related.

Using SDK version 1.35.0 on Windows 7 64-bit with the MinGW provided by Emscripten.

**Comment by Deins** [comment]
I encountered similar issue when i removed the function call that did the websocket connecting stuff in my code. It seems the issue arises when you try to set websocket callbacks but aren't using websockets (or maybe native sockets because i am using those. I don't know how you can use websockets without using native socket api) in your code. I have feeling that emscripten optimizes out Module['websocket'] when it detects you aren't using it. So i suggest getting the connection up and running and only when that is working add those callbacks. It could be nice if it would be possible to hint compiler always include Module['websocket']. Anyways, good luck and I hope this helps.
