### ISSUE TITLE
FS.createPreloadedFile throws Uncaught ReferenceError: Browser is not defined

### ISSUE THREAD

**Issue by lambdabaa** [emscripten-core/emscripten#4291]
I believe https://github.com/kripken/emscripten/blob/master/src/library_browser.js isn't getting pulled in appropriately.

**Comment by gaye** [comment]
This is with emcc version 1.36.0 fyi

**Comment by kripken** [comment]
Do you have a testcase showing the problem?

**Comment by BugraB** [comment]
@kripken I am having this exact issue in our code base after upgrading to sdk-tag-1.36.14-64bit. As a test case, I just created a simple main.cpp:

#include <iostream>

int main() {
  std::cout << "Hello world" << std::endl;
  return 0;
}

and built it as follows:
emcc main.cpp -o main.html

I cannot see any of the library_browser.js code in the generated main.js.

In our code we call FS.createPreloadedFile and it fails due to missing object "Browser". I wonder if I'm doing something wrong.

**Comment by kripken** [comment]
Yes, we don't include `Browser` if it isn't used. However, if you preload files, then it should be included, so the question is why it isn't. Are you perhaps using the file packager separately/standalone?

Even so, though, `Browser` is included if you use e.g. `emscripten_set_main_loop` or `emscripten_async_call` etc. Are you not using any of those apis either?

**Comment by BugraB** [comment]
We don't use the file packager separately. We embed some static files using --embed-file. We make FS.createPreloadedFile calls to load some localized content on-the-fly.

We don't use emscripten_set_main_loop as it was causing a constant redraw loop even when there were no user input. We never needed emscripten_async_call either.

Do we have to explicitly call something from Browser to get it included?

Thanks!

**Comment by BugraB** [comment]
Adding a dummy call to emscripten_async_call did the trick. Though I wonder if a call to FS.createPreloadedFile should also trigger the inclusion of Browser.

Though I realize we are probably an unusual case here since we don't call emscripten_set_main_loop.

Thanks for your help Alon!

**Comment by kripken** [comment]
Hmm, I think this is a bug that wasn't noticed since apps tend to use the `emscripten_` APIs that bring in `Browser`.

The problem is that `FS.createPreloadedFile` is in JS, where the compiler can't see it. We don't scan user-supplied JS, as it's not practical to statically analyze.

Not sure what the better solution is here. Another workaround is to build with `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=$Browser`, which will force-include it.

**Comment by BugraB** [comment]
That's a great workaround, thanks a lot! I will give it a try soon.

Btw, I am doing this toolset upgrade to experiment with WebAssembly using Binaryen and the results are super impressive. We see great performance improvements in CPU-bound operations with WASM (in the order of 40-70%). The app load performance is pretty terrible but I'm assuming that'll get better in time as wasm support matures in Browsers. Very exciting!

**Comment by kripken** [comment]
Nice, good to hear!
