### ISSUE TITLE
warning: unresolved symbol: sem_wait

### ISSUE THREAD

**Issue by ToniKroos** [emscripten-core/emscripten#4298]
Hello.

I'm trying to compile c code to js

sample code

```
#include <semaphore.h>
#include <stdio.h>
#include <sys/errno.h>


int main(int argc, char **argv)
{
    const char *semaphore_name = "my-test-semaphore";

    int rc = sem_unlink(semaphore_name);
    if (rc)
        perror("sem_unlink");

    sem_t *semaphore = sem_open(semaphore_name, O_CREAT, O_RDWR, 0);
    if (semaphore == SEM_FAILED) {
        perror("sem_open");
        return 1;
    }

    rc = sem_wait(semaphore);
    if (rc) {
        perror("sem_wait");
        return 1;
    }

    return 0;
}
```

command..
emcc main.cpp

```
/emsdk_portable/emscripten/1.35.0/system/include/libc/sys/errno.h:1:2: warning: redirecting incorrect #include <sys/errno.h> to <errno.h> [-W#warnings]
#warning redirecting incorrect #include <sys/errno.h> to <errno.h>
 ^
1 warning generated.
warning: unresolved symbol: sem_wait
warning: unresolved symbol: sem_unlink
warning: unresolved symbol: sem_open
```

somebody help me :)

**Comment by juj** [comment]
The first thing here is that you need to compile with multithreading enabled, so pass the `-s USE_PTHREADS=1` linker flag. See documentation at http://kripken.github.io/emscripten-site/docs/porting/pthreads.html.

Although after that, I see that the sample code fails in an error "sem_open: Too many links", which comes from sem_open calling to link, which is performing the filesystem syscall 9, which is the link operation. We don't currently support that it seems. https://github.com/kripken/emscripten/blob/master/src/library_syscall.js#L234. @kripken: how does this look to you? Was link() function always unsupported, or I wonder if this might have been lost in the syscall work? I do recall that semaphores would have worked when I did the initial pthreads implementation since I chose to include the `sem_*` functions in the libc build, but I'm not really sure if that was accurate.

**Comment by ToniKroos** [comment]
hello juj

I am your help to solve the problem .

compile option -s USE_PTHREADS=1

thank you

bye ^^

**Comment by xxseabxx** [comment]
@ToniKroos is this topic still open?
