### ISSUE TITLE
Has work been done to "bootstrap" emscripten?

### ISSUE THREAD

**Issue by mattbasta** [emscripten-core/emscripten#430]
i.e.: Is it possible to get clang running in emscripten in order to generate (and potentially run) C++ programs straight from the browser? I would imagine that this could potentially be a valuable educational tool.

**Comment by stfairy** [comment]
Any updates on this?

**Comment by viebel** [comment]
@kripken Is it possible to run emscripten in the browser?

cc: @stfairy @mattbasta

**Comment by kripken** [comment]
The only problem with this is that the emscripten toolchain uses some python scripts. Otherwise, the JS parts can just run, and the C++ parts can be compiled.

It would be nice, and not too hard, to add an option for not using the python scripts for the simple case of compiling a single input file with little dependencies to wasm, as

1. We use python for linking, but a single file doesn't need that.
2. We use python for our ports system, but a simple program wouldn't need that.
3. When compiling to JS, we use python to invoke our JS optimizer, but when compiling to wasm, we use the binaryen optimizer which is C++ and thus runnable on the web.

For educational purposes that would be enough I think?

Would be great if someone wants to work on this.

**Comment by viebel** [comment]
I agree with you that for educational purposes, it would be enough.

My goal is to use bootstrap emscripten to eval C/C++ code in the browser and to integrate it with a tool of mine named KLIPSE - https://github.com/viebel/klipse.

I'd be happy to work on this but I'll need more guidance. 
Where in the code should we add the option for not using the python scripts?

**Comment by kripken** [comment]
It would be a new place, I think. Maybe `emscripten.js` or `emcc.js` in the top level? It would then do what `emcc.py` and `emscripten.py` do now.

This would require a port of clang to the web. I had an old port in clang.js/llvm.js, but it would need to be updated to our current llvm+clang.

For simplicity, this could really just
 * Call the compiled `clang`, get bitcode.
 * Call the compiled `llc` to translate bitcode into asm.js.
 * Wrap/finalize the asm.js (can be a much simpler version of `emscripten.py`). Perhaps even without the `src/compiler.js` stuff that would link in JS libraries, maybe instead just hardcode a bunch of libraries, and include them around the asm.js.
 * Not bother with running additional optimizations etc.
