### ISSUE TITLE
Alpha channel on PNG's is ignored (SDL2)

### ISSUE THREAD

**Issue by belen-albeza** [emscripten-core/emscripten#4331]
Loading a PNG and rendering it (SDL2 + SDL2_Image) ignores the alpha channel of the picture and renders a white background instead.

The same code compiled with GCC and executed natively renders the sprite properly with a transparent background.

Online demo [here](http://belen-albeza.github.io/emscripten-glitch/) and source code [here](https://github.com/belen-albeza/emscripten-glitch/blob/master/main.c)

Does anybody know a workaround?

**Comment by juj** [comment]
I wonder if this might not be about the PNG alpha channel itself, but about the fact that canvases don't have alpha enabled by default. See #4355, and the trace of earlier discussion: #4350 and #4194 and #3406, if that might be of help? Basically after the PR you'd want to disable the `background-color: black;` on the page CSS style, and make sure the WebGL context is created with `alpha: true` context parameter enabled.

**Comment by belen-albeza** [comment]
Hi @juj thanks for your suggestions. I've disabled the style on a custom HTML shell, but I'm not sure how I'd specify that argument for the webgl context. I'm using WebGL by passing the `SDL_WINDOW_OPENGL` flag in `SDL_CreateWindow`. 

How should I do that? Thanks!

**Comment by eukarpov** [comment]
@juj i think the problem is very simple. just push changes what i did in library_sdl.js #3406

**Comment by belen-albeza** [comment]
@juj and I have been debugging this in MozLondon and he suspects that it might be the actual blending operation ignoring the alpha channel.

**Comment by juj** [comment]
Debugged this a bit further, and I notice that the file assets/captain.png does get loaded in 32-bit mode, that is, the surface format is

rmask: 000000FF, gmask: 0000FF00, bmask: 00FF0000, amask: FF000000, BytesPerPixel: 4

(already before the call to SDL_ConvertSurface, which is a no-op for this image) but the actual loaded pixels have alpha channel of 0 everywhere, which is the issue, and not the blend after all. If I programmatically adjust the alpha channel of the pixels, the blend operation does correctly blend with that alpha, so that part is ok.

At first I thought it would be the SDL2_image Emscripten-specific addition for preloaded image plugins, but that path is not taken for this, and the software libpng decoder is used. It seems as if `IMG_LoadPNG_RW` returns without alpha in the image.
