### ISSUE TITLE
Closing stream after calling mmap() with map_shared can cause file corruption

### ISSUE THREAD

**Issue by hoongern** [emscripten-core/emscripten#4352]
- Open a file and map it (with map_shared), let's say it [records the mapping](https://github.com/kripken/emscripten/blob/master/src/library_syscall.js#L877) with FD (file descriptor number) = 1.
- After closing the file descriptor, the stream with FD==1 is [`null`ed](https://github.com/kripken/emscripten/blob/master/src/library_fs.js#L415).
- If another file is opened, it could get FD=1.
- Now, if `msync`/`munmap` is called on the original file, it writes back to the file descriptor it recorded when it was mapped ([here](https://github.com/kripken/emscripten/blob/master/src/library_syscall.js#L392-L393) and [here](https://github.com/kripken/emscripten/blob/master/src/library_syscall.js#L746-L748), corrupting the second file which was opened due to the FD reuse.

I created a test case which exhibits this bug here (updated the current mmap test): [https://github.com/hoongern/emscripten/commit/9d48297fda64570368394cb02ce39f4b60de77b9](https://github.com/hoongern/emscripten/commit/9d48297fda64570368394cb02ce39f4b60de77b9)

I also created a potential fix here, which fixes the test: [https://github.com/hoongern/emscripten/commit/a14ed14c470b6f44489abdedc0d5d107bcdcfecf](https://github.com/hoongern/emscripten/commit/a14ed14c470b6f44489abdedc0d5d107bcdcfecf), however, I'm not really familiar with the file system and memory mapping behavior to know if that is the correct fix.

**Comment by kripken** [comment]
Our mmap support is rather limited, and much of the functionality is not possible to implement anyhow. So I'm not too worried about limitations in mmap, but it would definitely be good to show clear errors and warnings.

Specifically here, I don't quite understand the underlying issue yet - why is a refcount needed? Doesn't the mapping go away with the FD? That is shouldn't we clear the entry in `mappings` for the FD being closed?

**Comment by hoongern** [comment]
According to one of the [mmap specs](http://pubs.opengroup.org/onlinepubs/7908799/xsh/mmap.html) I checked (which I included in the test case),

> The mmap() function adds an extra reference to the file associated with the file descriptor fildes which is not removed by a subsequent close() on that file descriptor. This reference is removed when there are no more mappings to the file.

Also, the [man page](http://linux.die.net/man/2/mmap) states:
> On the other hand, closing the file descriptor does not unmap the region

**Comment by juj** [comment]
Is it correct program behavior to close a file descriptor that is currently mmapped? That is, is the sequence `fopen`, `mmap`, `fclose` valid?

If it is, then, is it correct program behavior to `msync`/`munmap` a file descriptor that has been closed, even though that file descriptor had previously been mmapped? That is, is the sequence `fopen`, `mmap`, `fclose`, `msync`/`munmap` valid?

If answer to both of the above is yes, then looks like that kind of refcounting is necessary. If not, then something like this might be still nice to do for debugging purposes, in order to be able to detect errors of when using a file descriptor that has already been closed.

Alternative solution might be to not reuse file descriptor numbers, but keep incrementing them for each `fopen`?
