### ISSUE TITLE
WebIDL Binder: take Prefix into account when generating JavaScript

### ISSUE THREAD

**Issue by sirudog** [emscripten-core/emscripten#4360]
The ‘Prefix’ keyword only affects the generated C++ glue code. This leads to name collisions inside the WebIDL Binder when multiple inner classes or classes inside namespaces share the same name. Also the generated JavaScript glue code does not in any way take the prefix into account.

This is for example problematic when dealing with C++ code compiled from Cap’n Proto schemas. For each message type there will be a C++ class with an inner Reader and Builder class. These inner classes are the ones through which the reading and composition of Cap’n Proto messages is done. Getters for various types also return a Reader for that type. So pretty much every class for which we would want to generate glue code in this scenario will either be called ‘Reader’ or ‘Builder’. This causes the WebIDL Binder to complain of duplicate definitions, although they are actually distinct classes. Generated JavaScript also only uses the name ‘Reader’ or ‘Builder’ without any further qualification.

Would it be possible to have the WebIDL Binder take the Prefix into account, so that it would treat interfaces adorned with different Prefixes as distinct types and generate ‘fully qualified’ JavaScript names (by prepending the Prefix to the name for example)?

**Comment by kripken** [comment]
Is the problem in the binder itself as it runs, or in the glue cpp that it emits? If the latter, perhaps the glue could be put in a namespace?

**Comment by sirudog** [comment]
Hi Kripken,

It’s the binder as it runs, complaining about duplicate definitions when I specify multiple readers in my IDL as such:
```
[Prefix=”MyClass1::”]
interface Reader {
  boolean getStuff();
};

[Prefix=”MyClass2::”]
interface Reader {
  long getOtherStuff();
};
```

If I run the binder with only one Reader definition in the IDL there seems to be no problem with the generated C++ glue code, as the Prefix is properly taken into account and the Reader is fully qualified (`MyClass1::Reader`). However in the generated JavaScript the reader is just called `Reader`, which would lead to name collisions in the generated code if the binder were actually able to process above IDL successfully.

So the problem is twofold:
* The binder cannot distinguish between `MyClass1::Reader` and `MyClass2::Reader` and complains of duplicate definitions for Reader.
* The generated JavaScript does not acknowledge the Prefix, losing the ability to distinguish between the two Readers. Probably something like generating `MyClass1_Reader` would solve this.

Thank you for looking into this and please let me know if you have any more questions.

**Comment by kripken** [comment]
I see, thanks for the details. Yes, it seems like we need to take the prefix into account in the binder itself. But also in the emitted JS, and `::` would not be valid there`. So we might need to add a `JSPrefix` option or something like that. I'm not sure offhand how easy either would be to do, but I would guess not very hard.

**Comment by kripken** [comment]
A new property like `JSPrefix` would go into `./third_party/WebIDL.py`, and the rest would be the webidl binder python script.

**Comment by jlmatchlock** [comment]
I recently ran into this issue and am currently trying to modify the WebIDL parser so it can take the prefix into account to avoid name collisions.

I'm not knowledgeable in python but here's what I've dugged up so far.

**Interface keyword parsing**

- Each interface is parsed into an instance of IDLUnresolvedIdentifier, inside the function p_Interface(self, p) in WebIDL.py (around line 3750)
- The identifier is then looked up with _lookupIdentifier() which returns an IDLInterface object in case it found an existing one
- If there's an identifier already declared, it is re-used and set non-partial, upon which an exception is raised in our case.
- If no identifier has been previously declared, an IDLInterface instance is created and resolved in the global scope to ensure it is unique (with the IDLScope.ensureUnique() function)

**Prefix keyword parsing**
- The prefix keyword is parsed and added as an extended attribute inside the function p_Definitions(self, p) in WebIDL.py (around line 3690) with the function addExtendedAttributes().
- Searching for the keyword "Prefix" inside the file, the level at which the hierarchy of classes is made aware of the "Prefix" keyword is IDLInterface.
- The function addExtendedAttributes() is first declared in base class IDLObject but must be overriden and the _extendedAttrDict variable where extended attributes are stored (for "Prefix" at least) is not declared until IDLInterface

From what I've seen (with simple print() lines spread here and there) the current implementation parses and processes the interfaces first (IDLInterface are first created and stored) and later, the prefix keyword is parsed and extended attributes are added to existing IDLInterface instances where relevant.
This means that when IDLInterface are first created, they are not aware of any Prefix keyword that might be already present (although they come before the interface keyword inside the idl file).

So, in order to fix this, I'm thinking of the following:
- parse the Prefix keyword first or at least, at the same time as interfaces
- so that when IDLInterface are first created, the prefix attribute can be stored
- so that later, when _lookupIdentifier() is called on the global scope, it can also check against the prefix attribute and not just the name
- this might also require that IDLUnresolvedIdentifier (and any classes used by ensureUnique() ?) be made aware of the prefix so ensureUnique() can work properly

Which brings me to ask a few questions:
- How is the call order for the p_Foo() functions decided ? As I'm not knowledgeable in python, I haven't yet figured out how the p_Foo() functions are registered and then called. I can just see from the debugger that they are called from the parseopt() function inside yacc.py with the line "p.callable(pslice)". Also, a search on "p_Definitions" or "p_Interface" returns nothing so I'm kinda stuck here.
- When storing the prefix attribute, would it be best to keep it separate at all times from the "name" variable or can I just mash them together, thus changing the IDLInterface name itself (into something like MyClass1_Reader and MyClass2_Reader to take the examples above) ? First option would be cleaner, second one would be more straightforward and potentially work out-of-the-box with ensureUnique() etc
- At which level would it be best to have the prefix attribute present in the hierarchy of IDL* classes ?
- Are there any other issues I might have skipped ? Or misunderstood ?

After this is done, the rest should be straightforward: once we have correctly separated IDLInterface that have the same name but a different prefix attribute, we just need to use the prefix along with the name where appropriate when outputting both cpp and js files.

PS: I haven't looked into JSPrefix yet, I'm thinking the double colon could be replaced by default with underscore - or is there any other issues I haven't considered yet ?

**Comment by froydnj** [comment]
@kripken, do you have comments on @jlmatchlock's approach?

**Comment by kripken** [comment]
Sorry for missing this.

`WebIDL.py` is a external parser we use, I don't think anyone here is familiar with the internals. Yeah, it is somewhat complex and uses some advanced python features... but I hope we don't need to mess with that here, if we are just adding a JSPrefix property?

Overall it should be ok to just add the JSPrefix property to `WebIDL.py` for parsing, and to use it from the webIDL binder code, by just prefixing `prefix + "_"` to the name. There is a risk of collisions, if something else happens to have that name, so in theory we need full name mangling like C++ uses. But given the user specifies the prefix, it would be easy to work around anyhow.

Or, an alternative to prefixing is to allow the user to provide the full name, `JSName`. That would allow full customization of the name in JS, which might be useful for more things.
