### ISSUE TITLE
The `remove_sh_exe_from_path` removes crucial executables from PATH on MinGW

### ISSUE THREAD

**Issue by JSmith-BitFlipper** [emscripten-core/emscripten#4399]
I have MinGW installed via Git Bash, and I noticed that when running a subset of my makefile, in which there is a simple procedure which calls `mkdir -p dist`, that mkdir wasn't functioning properly. That call would take the passes arguments as literals, creating 2 directories: "-p" and "dist" instead of parsing "-p" as a flag.

After more digging, I eventually established that the issue was being invoke after passing env through the `remove_sh_exe_from_path` function call. After more digging, I finally diagnosed that that call is removing a crucial path from PATH. It was removing the path to all of the basic executables (mkdir inclusive) as that path contained the hunted "sh.exe". After that purge, since my system could no longer find the correct mkdir, it seemed to default to something which is from where this undefined behavior originates.

As I do not fully understand this path for the CMake limitation, as the comment prefacing this function states, I would just like to bring up this issue for further discussion.

Here is a reference to `remove_sh_exe_from_path` for convenience.

```
  # Returns a clone of the given environment with all directories that contain sh.exe removed from the PATH.
  # Used to work around CMake limitation with MinGW Makefiles, where sh.exe is not allowed to be present. 
  @staticmethod
  def remove_sh_exe_from_path(env):
    env = env.copy()
    if not WINDOWS: return env
    path = env['PATH'].split(';')
    path = filter(lambda p: not os.path.exists(os.path.join(p, 'sh.exe')), path)
    env['PATH'] = ';'.join(path)
    return env
```

**Comment by JSmith-BitFlipper** [comment]
As it turns out, removing that `sh.exe`, regardless of where it is located (ie: if it is in a different directory so that the basic executables are not swept away with it), will still break those executables. 

Then that brings up the question of what function does this give (in the make function in shared.py around line 1177):

```
if 'mingw32-make' in args[0]:
 env = Building.remove_sh_exe_from_path(env)
```

From what I understand, `remove_sh_exe_from_path` is a patch for using CMake, but the above code has a specific switch for if the make program is mingw32-make.

**Comment by juj** [comment]
CMake "MinGW Makefiles" generator does not support MSYS or Cygwin. More information can be found at

https://cmake.org/Wiki/CMake_MinGW_Compiler_Issues
http://help.appveyor.com/discussions/problems/3193-cmake-building-for-mingw-issue-with-git-shexe
http://cmake.3232098.n2.nabble.com/mingw-vs-MSYS-makefiles-td7311490.html

MSYS/Cygwin aren't currently tested on Emscripten CMake support, and not officially supported. Try installing MinGW-GCC toolchain via the native Windows builds.

The reason why we autoremove PATH entries that contain sh.exe for the calls is that a lot of people have git and native Windows MinGW-GCC toolchain installed (Also emsdk bundles these two), so the autoremove allows git in PATH to not confuse CMake from functioning.

Alternatively you could try the "MSYS Makefiles" generator (paired with "make" instead of "mingw32-make") as suggested by people in the above links. If that generator is used, `Building.remove_sh_exe_from_path` should not kick in. I don't know how well this works, patches are welcome though.

**Comment by andrewevstyukhin** [comment]
https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/platform_dependent_issues/MinGW-Compiler-Issues
If I don't use "make" so there is no problem at all. Logic can be more clever to repair only case with a "make".

**Comment by juj** [comment]
> Logic can be more clever to repair only case with a "make".

sh.exe is currently removed from PATH under two scenarios:

Scenario 1: If invoking `emcmake cmake -G "MinGW Makefiles"` on Windows:

https://github.com/emscripten-core/emscripten/blob/19ea345e940f09156fa2c88212936afbbb23b3a5/emcmake.py#L54-L59

(note also the code block above that: if invoking `emcmake cmake` without a `-G` directive on Windows, then MinGW Makefiles is defaulted to. This is because on Windows CMake would otherwise default to Visual Studio solutions, which Emscripten does not support)

Scenario 2: If invoking `emmake make` or `emmake mingw32-make`:

https://github.com/emscripten-core/emscripten/blob/19ea345e940f09156fa2c88212936afbbb23b3a5/emmake.py#L48-L56

Executing `mingw32-make` requires sh.exe to not be present. Notice that `emmake` has a historical behavior of routing `emmake make` to invoke `mingw32-make` instead. I think this may have been due to some unit tests or cross-platform script compatibility purposes. Maybe that is the issue you are having @andrewevstyukhin ? You can execute `make` instead of `emmake make` to get direct invocation of `make` instead.

**Comment by andrewevstyukhin** [comment]
I have a problem in this invocation:

> emcmake cmake ../.. -DCMAKE_BUILD_TYPE=Debug

Environment has been set by:

> emsdk install 1.39.7
emsdk activate 1.39.7​
emsdk install mingw-7.1.0-64bit
emsdk activate mingw-7.1.0-64bit​


Also I have a working direct invocation:

> cmake ../.. -G "MinGW Makefiles" -DCMAKE_C_COMPILER=%EMSDK%/upstream/emscripten/emcc.bat -DCMAKE_CXX_COMPILER=%EMSDK%/upstream/emscripten/em++.bat -DCMAKE_MODULE_PATH=%EMSDK%/upstream/emscripten/cmake/Modules -DCMAKE_SYSTEM_NAME=EMSCRIPTEN -DCMAKE_BUILD_TYPE=Debug

**Comment by juj** [comment]
> I have a problem in this invocation:

What is the error in the resulting log?

**Comment by andrewevstyukhin** [comment]
Error happens in CMakeList.txt while spawning virtual python environment
`execute_process(COMMAND "${VPYTHON}" ...`
because our venv script uses bash which lays near sh.exe (from the git installation).

In other words deletion of paths to "sh.exe" also hides "bash.exe" and breaks our scripts.

> c:\Program Files\Git\bin:
bash.exe
git.exe
sh.exe

**Comment by juj** [comment]
Thanks - checking out the upstream CMake git repository, it looks like this workaround is no longer needed with CMake 3.17.0 and newer, which was released in March 2020. Authored #14930 to remove this workaround altogether.
