### ISSUE TITLE
Expected Token ';" got '{'

### ISSUE THREAD

**Issue by primesoftware** [emscripten-core/emscripten#4411]
Why does this work?

```
    EMSCRIPTEN_BINDINGS(my_module);
    {
        function("onloadFxn", &onload);
    }
```

But not this:

```
    EMSCRIPTEN_BINDINGS(my_module)
    {
        function("onloadFxn", &onload);
    }
```

Tutorials show the latter...

**Comment by GGAlanSmithee** [comment]
Looks like the first code snippiet has a statement which is a function call that is terminated by a `;`, followed by a second "statement", which is a code block (scope? don't know the correct terminology), that is started by a `{` and ends with a `}`.

The second code snippet however, does not terminate that first statement with a `;`, so when the code block starts with a `{` on the next line, the syntax is not valid. (the error message is accurate)

By the formatting of the code however, it almost looks as if the intention of the author was to write a function declaration rather than a function invocation + a code block.

**Comment by Drinex** [comment]
Most likely "{ ///function/// }" is not the definition of first function. "{" and "}" are used to make the program look a bit clean, and differentiate between the two functions. Not sure though, perhaps a full code will make it bit clear.
