### ISSUE TITLE
Add support for thin archives

### ISSUE THREAD

**Issue by joa** [emscripten-core/emscripten#4427]
Thin archives contain only symlinks to the actual object files. They're created by specifying the `T` modifier when invoking `ar` (e.g. `emar crsT foo.a foo.o`). While `emar` has no issue creating them, `emcc` complains about an unknown format at link time.

> ERROR:root:foo.a: Unknown format, not a static library!

If supporting thin archives isn't desired, `emar.py` could remove the `T` modifier from the command line passed to `llvm-ar`.

**Comment by kripken** [comment]
Not sure, but possibly we shouldn't support these (with a clear error message) as they might not be portable.

**Comment by joa** [comment]
Some more background: This issue arises quite early when using GYP with at least one dependency to a static library. The GYP Makefile generator will favor thin libraries when available. See https://github.com/joa/gyp/blob/master/pylib/gyp/generator/make.py#L1582

As a workaround one can set the `standalone_static_library` variable which will force GYP to emit a normal library and keeps `emcc` from complaining.

**Comment by froydnj** [comment]
It looks like thin archives are a GNU `ar` extension.

The linked GYP code only supports thin archives on not-{OS X, OpenBSD, Windows}, so by default on Linux, thin archives would be used.  Is it worth trying to disallow them in Emscripten if a build system is just going to assume the existence of support rather than probing for appropriate support?  I guess Emscripten's error messages could point out possible ways forward.
