### ISSUE TITLE
Confused by warnings building libraries

### ISSUE THREAD

**Issue by lukester1975** [emscripten-core/emscripten#4441]
Hi

I'm trying to convert my build system from generating .a static libraries (with emar) to bitcode (to avoid ordering issues like #2619).
- `echo "void LibFn() { }" > fn.cpp`
- `em++ fn.cpp -o libtest.bc`
- `echo "void LibFn(); int main() { LibFn(); return 0; }" > main.cpp`
- `em++ main.cpp -o main.html -L. -llibtest`
- WARNING:root:emcc: cannot find library "libtest"
  warning: unresolved symbol: _Z5LibFnv

OK, try .so:
- `em++ fn.cpp -o libtest.so`
- `WARNING:root:Dynamic libraries (.so, .dylib, .dll) are currently not supported by Emscripten. For build system emulation purposes, Emscripten will now generate
  a static library file (.bc) with the suffix '.so'. For best practices, please adapt your build system to directly generate a static LLVM bitcode library by setting the output suffix to '.bc.')

I'm not sure if I'm being stupid, but the warning seems a little confusing when the "link" stage then fails with .bc files!

Setting `STATICLIB_ENDINGS = ('.a','.bc')` in emcc.py allows the link to succeed with libtest.bc - is that a reasonable change to make? Using em++ to generate a .a file fails at the link stage:

ERROR:root:.\libtest.a: Unknown file suffix when compiling to LLVM bitcode!

Thanks!

**Comment by kripken** [comment]
Yes, good point, this is potentially confusing. It does seem like we should accept `.bc` files as libraries as you suggest.

What do you think, @juj? The only risk is if someone has a `.bc` file that shouldn't be found in this way. But it would be looked for only if the `.a` file isn't found first, so that seems reasonable. And in debug mode we log out the libraries we find, so this would be noticeable there.

**Comment by juj** [comment]
For reference, `em++` (nor native `clang++` or `g++`)  does not generate archive .a files, the kosher code sequence would be to use the archiver tool, which is `emar` for Emscripten (`ar` for native), with the following code sequence:

    em++ fn.cpp -o fn.o
    emar r libtest.a fn.o
    em++ main.cpp -o main.html -L. -ltest

This works parallel to native, which has the following code sequence:

    clang++ -c fn.cpp -o fn.o
    ar r libtest.a fn.o
    clang++ main.cpp -o main -L. -ltest

(if testing, remember to delete `libtest.a` if it exists before, since `ar r` will try to append to existing)

Native archive .a files are much like tape archives (.tar) in many aspects.
 
A minor behavior difference here between Emscripten and native g++ is that g++ requires `-c` directive, or otherwise it proceeds to attempt to link, but Emscripten doesn't currently need this. (passing it doesn't hurt)

In native, if one does

    clang++ -c fn.cpp -o libtest.a
    clang++ main.cpp -o main -L. -test

this works, but it does not actually create an intermediate archive file, but file `libtest.a` is just an object file with the `.a` suffix. Looks like Clang lets this pass, and it accepts `-ltest` to just pull in libtest.a and interpret it as an object file.

In Emscripten, if we do the same:

    em++ fn.cpp -o libtest.a
    em++ main.cpp -o main -L. -ltest

Emscripten will do the same as clang++ and generate an object file (just with .a suffix in disguise) in the first command, but the second command will fail with the error message "ERROR:root:./libtest.a: Unknown file suffix when compiling to LLVM bitcode!" like @lukester1975 reported.

If we'd like to have parity with native, I think we would want here to at least relax `-ltest` to allow pick up a `libtest.a` whose contents is an object file instead of an archive file. It looks like native `clang++` doesn't much care what the content of the picked up file is, since if one does a very peculiar

    clang++ -c fn.cpp -o libtest.a
    mv libtest.a libtest.so
    clang++ main.cpp -o main -L. -ltest

even that works, even though libtest.so here is nothing that resembles a real .so file. This suggests that in native clang++, `-lfoo` is an alias to take `libfoo.a` or `libfoo.so` as input, and dynamically introspect its contents, and consume it if its contents is of any supported type.

If we do that, and let `-ltest` pick up `libtest.a` that is actually an object file, then it follows that we probably would want to have `-ltest` pick up `libtest.bc` as well, since in Emscripten object files are exactly LLVM bitcode files.

Therefore,

    a) if linking in `-lfoo`, allow consuming `libfoo.a` even if it is just an object file in disguise, and
    b) allow searching for `libfoo.bc` on `-lfoo`, in the order `libfoo.a`, `libfoo.so`, `libfoo.bc`

Although I presume that the linking semantics of an `libfoo.a/.bc` with `-l` linking should be different than just plain consuming `libfoo.a/.bc`, because the `-l` linking should perform the "only satisfy all so far unmet dependencies" vs plain adding an object file should "add all symbols from the object file to the build", but I wonder if that is a separate issue from this(?)

**Comment by dschuff** [comment]
Does the linking semantics of native clang depend on whether the file was included because of `-l` vs bare on the command line, or just on what kind of file it is?

I'm fine with 1) if it's how native clang behaves (btw, is this behavior different for Linux vs OSX?)
But I think `-ltest` should not pick up `libtest.bc` because native clang would not pick up `libtest.o`.  In general we should not be moving toward more conflation of archives and object files, or using object files where we should be using archives (e.g. as we do with libc). If we want to accommodate code that has circular dependencies, then we could implement the `--whole-archive` and/or `--start-group`/`--end-group` linker flags.

**Comment by bzz** [comment]
Have just hit this issue and used @lukester1975 workaround.

Was wondering if there has been any updates on this?
