### ISSUE TITLE
emconfigure with emcc -E cause strange behavior

### ISSUE THREAD

**Issue by Kagami** [emscripten-core/emscripten#4478]
```
$ cat configure 
#!/bin/sh
emcc -s USE_ZLIB=1 -E -o 1.o 1.c && echo OK
$ cat 1.c
#include <zlib.h>
int x;
$ ./configure 
OK
$ emconfigure ./configure 
1.c:1:10: fatal error: 'zlib.h' file not found
#include <zlib.h>
         ^
1 error generated.
ERROR:root:Configure step failed with non-zero return code 1!
Command line: ['./configure'] at /tmp
```

```
$ cat configure 
#!/bin/sh
emcc -s USE_ZLIB=1 -o 1.o 1.c && echo OK
$ emconfigure ./configure
OK
```

Could you please explain what's going on? (I'm using 1.36.7 version.)

**Comment by kripken** [comment]
I think `-E` makes it only use the preprocessor. And looking in the code, it seems like in that case we stop before even processing ports, so the `USE_ZLIB=1` has no effect, and so `zlib.h` is not in the path. This is definitely a bug.

**Comment by Kagami** [comment]
But it works without emconfigure?...

It prevents me to build ffmpeg with `--enable-zlib` option using zlib port: ffmpeg configure script does a lot of sanity checks with C compiler, on of them is to check presense of `zlib.h` header. And it passes `-E` flag for this checking (probably to make it little faster).

**Comment by kripken** [comment]
Ok, reading `emcc.py` more carefully, we do in the normal case run `system_libs.process_args` even when just doing the preprocessor. But, the `emconfigure` code path (starting on line 189) lacks that. So the bug is `emconfigure`-specific, and the fix is probably to add that `system_libs.process_args` in the right place around there.
