### ISSUE TITLE
How should JS library code that doesn't specify number of arguments behave?

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4644]
Consider the following C code `test.c`:

```
extern void my_js();

int main() {
  my_js();
  return 1;
}
```

and JS code `lib_test.js`:

```
mergeInto(LibraryManager.library, {
  my_js: function() {
    console.log('hi');
  },
});
```

Compile with `emcc test.c -o a.js --js-library lib_test.js`. It prints

```
warning: unexpected number of arguments 0 in call to 'my_js', should be 1
```

This warning is odd. What should happen here?

In C code, `extern void my_js();` means `extern void my_js(...);`. The compiler should not have any specific reason to say that exactly one argument would be needed here?

In this specific code, the warning can naturally be quieted by using `extern void my_js(void);` to explicitly tell that no arguments are expected. However, how should we treat the case when that is not specified and the C "implicit number of args" is used? Consider `test2.c`:

```
extern void my_js();

int main() {
  my_js(1, 2, 3);
  return 1;
}
```

and JS code `lib_test2.js`:

```
mergeInto(LibraryManager.library, {
  my_js: function(a, b, c) {
    console.log(hi ' + a + b + c);
  },
});
```

This gives `warning: unexpected number of arguments 3 in call to 'my_js', should be 1`, and running the code prints `hi 1undefinedundefined`. That's quite wrong.

Possibilities:
    1) can we actually support implicit number of arguments cases like `test2.c` + `libtest_2.js` work correctly?
    2) if not, I think we should turn that warning to an Emscripten-specific error `error: Missing the number of arguments to pass to JS implemented function in C declaration of "my_js" ! (Use "void my_js(void)" to pass exactly 0 arguments)` to forbid implicit argument count declarations.

**Comment by kripken** [comment]
The first looks like adding `(void)` is the right thing - it's a corner case of C that without it it means "varargs".

For the second, I think the issue is that [C wants a param before the varargs](The syntax of ISO C requires at least one fixed argument before the ‘…’.), so `(int x, ...)` would work. But without `x`, you can't write `(...)`.

**Comment by juj** [comment]
Actually, to be more precise (spec checking via stackoverflow..):
  - in C before C11, `void foo()` declares a function that takes an unspecified, but not variable, number of arguments. http://stackoverflow.com/a/5929736
  - starting from C11, `void foo()` is an "obsolescent" feature. http://stackoverflow.com/a/18168441

Yeah, in the first example, the developer can resolve by adding `(void)`, and in the second case, developer can resolve by adding `(int, int, int)`. The second case is not a varargs function, so it should be valid. However in this bug I want to focus on how Emscripten deals with those two code snippets if someone happens to write them.

Do you know why Emscripten currently concludes that `void foo()` in C code would take in exactly one parameter?

**Comment by dschuff** [comment]
I'm guessing (haven't looked at the code) that it actually is considering that as varargs function, which means that it allocates a buffer in memory to store the varags, and the function itself gets a pointer to that buffer. Most native C calling conventions will tolerate mismatches in varargs vs non-varargs, in the caller vs the callee, as long as the number of arguments passed is what the callee expects. PNaCl and wasm are different though because they have no built-in support for varargs (and IIRC the asm.js way of handling this is derived from PNaCl).
