### ISSUE TITLE
Make default shell .html file allocate HEAP very early.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4712]
As part of the large-allocation response header, we need to make sure that the asm.js/wasm heap gets allocated extremely early up on the page, so that we maximize the chances of the allocation getting in to the slot that is reserved to it. (otherwise loading up a bunch of scripts and other stuff on the page could fragment that clean memory area)

We should make this by "example" of making our default shell html files all follow this practice. This means that our shell.html files would all always allocate the HEAP up front very early on, before loading anything else. That's a very good change to make even in the absence of the large-allocation response header, because we have data showing that it can dramatically reduce fragmentation related OOMing on current browsers as well. Also it allows us to OOM very early on, so we don't even attempt to load those huge .data or .asm.js files or anything else if things fail due to OOMing on the heap allocation.

Unfortunately that will impact/interfere with `Module['TOTAL_MEMORY']` field, not quite sure yet how to architect this out, but the benefits of this are so large that I think we should do this.

**Comment by kripken** [comment]
Sounds good. Notes:

1. This should be easy to do, I believe we allow preallocation of the memory buffer already - if `Module['buffer']` is set, we use that, so the HTML can just set it.
2. Good point about the risk of the user setting `TOTAL_MEMORY` at runtime after we allocate it. I guess we can show an error in that case (check `TOTAL_MEMORY` compared to the buffer size, where we currently would have allocated it, i.e., in the place were we use `Module['buffer']` instead of allocating). It then seems that the user could easily move their setting of `TOTAL_MEMORY` earlier to avoid the issue, so I don't think we need an option to not do it - let's always do it.
