### ISSUE TITLE
Better tracking of musl update history

### ISSUE THREAD

**Issue by jgravelle-google** [emscripten-core/emscripten#4795]
We currently use musl libc, by having a modified copy of the source in the Emscripten tree directly. This makes it difficult to update musl, because Emscripten-specific modifications aren't known to git, and thus git can't do much for us.

I propose we move musl from being in-tree to being a separate repo that tracks upstream musl, with an Emscripten-specific branch that Emscripten targets. Two ideas for what that would look like:
1. Emscripten refers to emscripten-musl as a submodule
2. The location of emscripten-musl is passed in via a config file, and is set up either manually or by emsdk

Option 2. seems more consistent with the current external dependencies (fastcomp, binaryen), so I have a mild preference in that direction. Other ideas?

**Comment by kripken** [comment]
General idea sounds good to me. On details, it could be in the ports system, like sdl2, zlib, bullet, freetype, etc. It would just be a port that doesn't require a special flag (like zlib requires `USE_ZLIB=1` ).

**Comment by dschuff** [comment]
What does 'in the ports system' entail? Are those ports libraries treated any differently for the purposes of e.g. system_libs? libc is definitely in a different class than those in that it is more tightly-coupled to the emscripten JS runtime. If that just means that it goes in a particular directory or whatever then that seems fine. But it probably shouldn't be 'just' a port, e.g. if a user tried to replace it, it probably wouldn't go well (whereas users should be able to replace the other ports easily if they want).

**Comment by kripken** [comment]
The benefit of being in ports is that can use the shared ports infrastructure for fetching and building the project. See e.g. the [vorbis integration code](https://github.com/kripken/emscripten/blob/master/tools/ports/vorbis.py) for an example.

It's true it's a little different than the other ports, as you say, it isn't as optional. So it should probably be built by default instead of by a flag as ports typically are.

Alternatively it could be a submodule, which is inconsistent with other stuff, but maybe this is different enough to justify that. But it does bring with it the usual git submodule annoyances (people using the project forget to get/update the submodule, etc.). But maybe there is a way around those. A benefit to using a submodule is that we would not need new code or to move our current musl-building code.
