### ISSUE TITLE
Lets start looking in switching perminately from python2

### ISSUE THREAD

**Issue by marcthe12** [emscripten-core/emscripten#4822]
Python 2 EOL is in 3 years time. What I am suggesting is to make the entire emcripten which is in python 2 in the following options:

- Python 3 - Less porting need and lots of surport in the long run
- Rewrite into another language that can be converted to asm.js or write in javascript - May not possible and needs a lot of work but gains the advantage of making javascript the only runtime depencies (only node js needs to be installed not python reducing install space

**Comment by kripken** [comment]
Moving to JS (in second option) may be possible now. It wasn't a few years back, since we use python's multiprocessing options and node.js wasn't that powerful in that area. Might be a few more python API things we depend on, hopefully all now supported in node.js. If that's the case, then it sounds like a good idea, if we can find someone with time to do it.
