### ISSUE TITLE
Multiple smart pointer constructors

### ISSUE THREAD

**Issue by arcanis** [emscripten-core/emscripten#4861]
Is it possible to define multiple smart pointers constructors on a single class? I would think so, but apparently it doesn't work. Whatever I use as first parameter of `smart_ptr_constructor` I get a "Cannot register type XXX twice" error, where `XXX` is the name of the second smart pointer constructor (why do we need different names for those, anyway?).

My binding is as such:

    emscripten::class_<Patch>("Patch")

        .smart_ptr_constructor<std::shared_ptr<Patch>>("Patch", &std::make_shared<Patch>)
        .smart_ptr_constructor<std::shared_ptr<Patch>, bool &&>("Patch", &std::make_shared<Patch>)

**Comment by AlexPerrot** [comment]
This does not work because `smart_ptr_constructor` registers the smart pointer to your class (see https://github.com/kripken/emscripten/blob/master/system/include/emscripten/bind.h#L1201 ).

A quick fix is to remove this line, but you will need to register the smart pointer type yourself using `.smart_ptr`. Also, this will break existing code, so finding a way to auto-register it only once would be great.

**Comment by ciprisava** [comment]
```
class MyClass {
public:
  MyClass();
  MyClass(std::string);
  MyClass(int, std::string);
...
};

std::shared_ptr<MyClass> myFactory() { return std::make_shared<MyClass>(); }

EMSCRIPTEN_BINDINGS(my_module) {
  class_<MyClass>("MyClass")
    .smart_ptr<std::shared_ptr<MyClass>>("shared_ptr<MyClass>")
    .constructor(&std::make_shared<MyClass>)
    .constructor(&std::make_shared<MyClass, std::string>)
    .constructor(&std::make_shared<MyClass, int, std::string>);

  function("myFactory", myFactory);
}
```
In my opinion, the solution is to:
(1) register `"shared_ptr<MyClass>"` with `.smart_ptr`
(2) define all exported constructors as above e.g., ` .constructor(&std::make_shared<MyClass, std::string>)
` instead of `.constructor<std::string>()`

Is this workaround good enough to have multiple smart pointer constructors?
