### ISSUE TITLE
Imports in WebAssembly

### ISSUE THREAD

**Issue by rahulchaphalkar** [emscripten-core/emscripten#4885]
When I generate wasm files `-s wasm=1`, the JS file has:
```
 var asm2wasmImports = { // special asm2wasm imports
    "f64-rem": function(x, y) {
      return x % y;
    },
    "f64-to-int": function(x) {
      return x | 0;
    },
.
.
.
```
Why do we have these imports for wasm? When are they used? Looks like some benchmarks, like fasta from emscripten test suite (converted to wasm) is calling `f64-to-int` , `i32u-rem` etc many times (probably from a hot path), which doesn't seem to be a good thing, switching in and out of wasm module. So I'm just curious to gain more insight on these imports.
Thanks!

**Comment by kripken** [comment]
For `f64-rem`, wasm doesn't has a floating-point remainder operation, unlike asm.js. So we call out to asm.js to do it. Instead, we could make sure to link in the relevant libc method for it. (Not sure how high a priority it is, as it tends to be a rare operation, and would increase code size. I also have a vague memory of someone working on it, but don't recall details.)

For `f64-to-int`, the issue is if we want the same semantics as asm.js or not. See discussion in #4625. Meanwhile, if you enable `BINARYEN_IMPRECISE` (which means, don't necessarily do precisely what asm.js does), then you'll get the fast version, without calls to `f64-to-int`.

**Comment by rahulchaphalkar** [comment]
Thanks, I'll try out the `BINARYEN_IMPRECISE` option. 
Apart from `f64-rem` I was primarily interested in `i32u-rem`, as it is being used quite a bit in Fasta.

> For  f64-rem , wasm doesn't has a floating-point remainder operation, unlike asm.js. So we call out to asm.js to do it.

Don't we call out to just JS, and not asm.js ? The native-wasm method is successful.

**Comment by kripken** [comment]
The imprecise option will help with i32u-rem as well. The issue there is that wasm will trap on div/rem by 0, and asm.js will not. So to be precise, we must avoid the trap (which we do by calling out, but there is a PR to optimize that, mentioned in the link from before).

And right, yeah, I mean "call out to JS".

**Comment by singpolyma-shopify** [comment]
I'm having some trouble figuring out where the  `f64-rem` uses are coming  from.  `fmod` in the included musl seems to be implemented directly without a builtin, so I assume this is not being used somehow?

**Comment by kripken** [comment]
In asm2wasm, I believe we turn asm.js `%` into calls to `f64-rem`. Can see that code around here:

https://github.com/WebAssembly/binaryen/blob/db9124f1de0478dcac525009b6f1589b44a7edd8/src/asm2wasm.h#L1939

**Comment by singpolyma-shopify** [comment]
@kripken I guess I'm wondering why/where `%` would be emitted at all when the included musl has `fmod` already?  There seem to be several cases of this, actually -- `mktime` also wants to be imported despite being present in musl.

**Comment by kripken** [comment]
I think fastcomp emits `%` because in asm.js that's the best thing - we don't need to rely on `fmod` from musl since the JS runtime provides it anyhow.

`mktime` is implemented in JS, instead of using musl, because it was easier that way to access the relevant JS APIs to actually get the current time etc. Over time we've gone back and forth though about how best to draw that boundary.
