### ISSUE TITLE
Supporting asm.js and wasm optimally with a single JS Module

### ISSUE THREAD

**Issue by dschuff** [emscripten-core/emscripten#5047]
Currently Chrome and Firefox are rolling out wasm MVP support, but it will be some months before other browsers go through their release train and get wasm out to users. Until wasm is ubiquitous emscripten users will probably want to build both asm.js and wasm versions of their code. There are a couple of possible ways to do this today.
1. Use the `native-wasm,asm.js` binaryen method. This isn't well tested and in any case won't really work now because wasm module loading needs to be asynchronous.
2. Do 2 separate builds (and generate 2 different sets of JS glue) and load one or the other based on feature testing.

Would it be possible to support both synchronous and async loading from the same generated JS glue? If so, would there be significant drawbacks (e.g. code size?). Otherwise, what can we do to make option 2 easier?

**Comment by kripken** [comment]
I'm not sure why wasm loading being asynchronous would be a problem for an asm+wasm build?

It's true we don't test those asm+wasm builds, and #5034 might be a bug there, so that's a concern.

Anyhow overall those builds are [not great for speed](https://github.com/kripken/emscripten/wiki/WebAssembly#codegen-effects), so I don't think we should recommend them.

Option 2 is probably the better way to go. I'm not sure different JS glue is enough though, might need also different HTML (when generating HTML; e.g., for asm.js we add HTML things to modify the use of fround, when `PRECISE_F32=2`). So overall, I'd say users can emit 2 separate builds with separate HTML etc. It should be the same commands except for `WASM=1` in one, so I'm not sure we need to help out there much. One thing that could be nice is for us to provide the JS snippet that decides which build to load, but that's just a few lines of code.

**Comment by kripken** [comment]
The JS might differ, e.g. we use a different libc for wasm, like we use Math.pow in asm.js but musl pow in wasm. So the imports could be slightly different. We also create a wasm Memory for wasm and an ArrayBuffer for JS. So the JS for the two may not be identical. Probably for all these things we could get them to work, but it seems risky and a source of new bugs. Generating the JS glue is fast, so I'd suggest just generating two fully separate builds for those reasons.

**Comment by dschuff** [comment]
Seeing #5333 made me think about this again. I agree that, for the reasons you mentioned above, we should be discouraging single asm+wasm builds, and users should just to 2 wholly separate builds with different generated Module objects, etc. So that means 2 points.
1. We should probably just stop supporting dual builds altogether. Our users won't waste their time doing something suboptimal, and won't have a risk of confusion (e.g. if they didn't understand the drawbacks they might think dual builds are the best option).
2. Even if we don't do number 1 (but especially if we do) we should make it easier to do separate builds. We should have some documentation/sample code (perhaps in our sample HTML shell?) for how to easily support asm and wasm. Presumably the HTML shell would do a feature test, then instantiate one or the other module (asynchronously, preferably?). I'm not super familiar with the HTML sample shell; do @kripken or @juj have any opinions about how much work that would be?

**Comment by kripken** [comment]
1. I agree we should hide or discourage those builds, like maybe they should warn at compile time. I think we should keep supporting them, though, as they are really helpful for debugging.
2. The simplest thing would be a little HTML that checks for wasm existence and then loads either a wasm build or an asm.js build. So there would be separate HTML, JS, etc. for each of the builds, and the checker would be an additional tiny HTML like:
````
<html>
<body>
<script>
if (typeof WebAssembly === 'object') {
  window.location = './wasm.html';
} else {
  window.location = './asmjs.html';
}
</script>
</body>
</html>
````
