### ISSUE TITLE
optimizer crashing on large function compilation

### ISSUE THREAD

**Issue by tesch1** [emscripten-core/emscripten#5096]
The optimizer crashes sig 11 on a project with pretty huge functions while "simplifyExpressions".  Pretty sure it's a stack overrun in the optimizer itself (dies in strtod somewhere).  Recompiling as a Debug build fixes it.  And setting ulimit -s N also fixes the Release binary.  But node wont run when using the ulimit change in the shell, so...  plopped this into optimizer-main.cpp, seems to have fixed it for me (centos7):

Took a while to figure out, there's no real message about why it fails, just says something like "optimizer failed -11".
```
  {
    const rlim_t stacksize = 128L * 1024L * 1024L;   // min stack size = 64 Mb
    struct rlimit rl;
    int result;
    result = getrlimit(RLIMIT_STACK, &rl);
    if (result == 0) {
      if (rl.rlim_cur < stacksize) {
        rl.rlim_cur = stacksize;
        result = setrlimit(RLIMIT_STACK, &rl);
        if (result != 0) {
          fprintf(stderr, "setrlimit returned result = %d\n", result);
        }
      }
    }
  }
```

**Comment by kripken** [comment]
Perhaps you are running into a bug where we use far too much stack, that is actually a pass I wouldn't expect to use that much. Or maybe the code is somewhat unique. Any chance you can share the bitcode file?

**Comment by tesch1** [comment]
Could be any of those.  I updated my 'master' recently and the outlining stage got significantly longer than it had been, on the same code.  Same thing happens with 'incoming'. Unfortunately I dont know what version I was using before.

The file is here...

**Comment by tesch1** [comment]
Oh, just noticed that now it's dying in 'eliminate', definitely used to be simplifyExpressions, not sure what changed between yesterday and today, might have been using slightly different compilation flags.

**Comment by aidanhs** [comment]
Wow that's a huge file - 733MB. And it's all one function! I'm not surprised the optimizer crashes, this is probably the single biggest function the optimizer has ever seen.

Running the command does indeed make the C++ optimizer crash as you describe. I ran the it through the O3 optimization passes in [ayzim](https://github.com/aidanhs/ayzim/) instead and it gets up to minifylocals before it errors (because your upload does not have `EXTRA_INFO` in it). If you want to try out ayzim yourself, just download the appropriate binary from https://github.com/aidanhs/ayzim/releases and replace the optimizer binary.

That said, even if it does work your users are likely going to have issues. I have managed to load a 750MB .js file into Chrome in the past, but it took 5-10mins to load the page. I assume your full project is massively larger than just this one function?

**Comment by aidanhs** [comment]
Ahhh, most of that is leading whitespace on lines. Ignore my comment about file size.

**Comment by tesch1** [comment]
I just ended up breaking down that function into smaller pieces, still does the same thing, but doesn't kill the optimizer.  I dont know what to say about this bug, it's maybe just an interesting edge case that tickles a blowup in the generated .js.  The actual function was only about 700 lines, see #5100 .

**Comment by aidanhs** [comment]
Judging by most of the filesize being in leading whitespace on lines, I guess it's just pathologically nested and so overflows the stack. Ayzim being better is probably just down to coincidentally using less stack space.
