### ISSUE TITLE
Interpret raw pointer value to JS object

### ISSUE THREAD

**Issue by saschanaz** [emscripten-core/emscripten#5126]
A C++ class receives a callback and gives a `value object`, which is mapped by embind. I can pass JS callback function using `Runtime.addFunction` but the JS callback is now receiving raw pointer value instead of expected embind-bound type.

How can I use this pointer to get the right object? Is there any helper function to do this?

**Comment by AlexPerrot** [comment]
I don't quite understand your problem, can you give a minimal code sample ?

**Comment by SaschaNaz** [comment]
Copy-pasted and simplified from [libflif.js](https://github.com/SaschaNaz/libflif.js/blob/b90646ddd331ea66425673dafcc9974c6ea08486/wrapper/bind.cpp):

```cpp
// in library:
typedef struct callback_info_struct {
    uint32_t quality;
    int64_t  bytes_read;

    // Private context
    void *populateContext;
} callback_info_t;

typedef uint32_t (*callback_t)(callback_info_t *info, void *user_data);

FLIF_DLLIMPORT void FLIF_API flif_decoder_set_callback(FLIF_DECODER* decoder, callback_t callback, void *user_data);
```

```cpp
// on my binding code: 
class FLIFDecoderWrapper {
public:
    void setCallback(size_t callback) {
        flif_decoder_set_callback(this->decoder, reinterpret_cast<callback_t>(callback), NULL);
    }
}

EMSCRIPTEN_BINDINGS(libflifem) {
    class_<FLIFDecoderWrapper>("FLIFDecoder")
        .function("setCallback", &FLIFDecoderWrapper::setCallback)
        ;
    value_object<callback_info_t>("CallbackInfo")
        .field("quality", &callback_info_t::quality)
        .field("bytesRead", &callback_info_t::bytes_read)
        ;
}
```

If you don't see yet then I will make a minimal code later today.

**Comment by AlexPerrot** [comment]
Ok, I understand your code, but I'm not sure what your problem is...
Your `callback_t`'s first argument is a pointer to a value_object, so it only seems normal to get a pointer in your js function.

Depending on what you want to achieve, I can see several options :

- If you want to send the pointer to the callback, you need to get the content of the pointer yourself (i.e. don't even use embind for your struct). Bad idea IMO.
- You can also ditch the pointer from `callback_t` if it is possible.
- If you can't, wrap every js callback with a function that will get the value_object for you and send it to the callback instead of the pointer.

**Comment by SaschaNaz** [comment]
>so it only seems normal to get a pointer in your js function.

I think embind normally prevents leaking raw pointers, and with `allow_raw_pointer()` it converts raw pointers to objects. It does at least for function bindings.

**Comment by SaschaNaz** [comment]
I have to pass the pointer to other function in the library so the third option is not for me. Currently my workaround is to wrap my callback and pass the pointer and its fields separately.

**Comment by AlexPerrot** [comment]
> I think embind normally prevents leaking raw pointers, and with allow_raw_pointer() it converts raw pointers to objects.

No, as the name implies, `allow_raw_pointers` is just a check to make sure you're aware of the raw pointer.
However, since your callback is a js function, it never went through embind, so no check was performed and you can freely use raw pointers.

**Comment by SaschaNaz** [comment]
I have several `allow_raw_pointers()` [in my code](https://github.com/SaschaNaz/libflif.js/blob/master/wrapper/bind.cpp) and they returns objects.

**Comment by AlexPerrot** [comment]
> I have several allow_raw_pointers() in my code and they return objects.
What do you mean ?
I have looked at your code, and all the functions wrapped with `allow_raw_pointers()` either return a raw pointer or take a raw pointer argument.

**Comment by SaschaNaz** [comment]
https://codepen.io/anon/pen/zwKVWv

Compiled by `em++ helloworld.cpp -std=c++11 -o helloworld.js -O2 --memory-init-file 0 --bind`

```cpp
#include <emscripten/bind.h>
using namespace emscripten;

class Foo
{
public:
  Foo() = default;
  Foo *foo()
  {
    return this;
  }
};

EMSCRIPTEN_BINDINGS(foo)
{
  class_<Foo>("Foo")
      .constructor()
      .function("foo", &Foo::foo, allow_raw_pointers());
}
```

```js
new Module.Foo().foo() // returns an object Foo, not a raw pointer integer.
```

**Comment by AlexPerrot** [comment]
OK, I see what you mean.
This object is what embind calls a raw pointer, as it represents a raw (i.e. not shared) pointer to a c++ object on the heap.
This is different from the value you get in your callback, which is just a number that has to be interpreted as the address of an object. Since the callback is not managed by embind, you have to do the conversion from address to raw pointer "object" yourself.
I think this should be possible via a utility function implemented in c++ using a `reinterpret_cast`.

**Comment by SaschaNaz** [comment]
Now I see why the conversation didn't go well 😄
