### ISSUE TITLE
Need a way to disable automatic WebGL extensions

### ISSUE THREAD

**Issue by tikotus** [emscripten-core/emscripten#5147]
I'm optimizing the start time of my emscripten app and currently about 10% of the time (in chrome) is spent on enabling webgl extensions automatically. I only need one extension so this is a waste of time in my case. I'm using SDL (and therefore GLUT?) to create the context. Looking at the source it seems like GLUT always enables all extensions.

**Comment by juj** [comment]
Oh wow, really surprising to hear that the impact is so large. I wonder if that might be caused by enabling some individual GL extension out of all of them, or if the overhead is somewhat evenly distributed across each of them?

With the HTML5 GL context initialization API, support for choosing whether to auto-enable is implemented via the `enableExtensionsByDefault` context creation parameter (https://github.com/kripken/emscripten/blob/master/system/include/emscripten/html5.h#L415). Unfortunately the SDL API does not have a direct way we could pass this over. Do you have a recommendation of what would be a good way to extend SDL to do this? It would have to be a mechanism that is suitably nonintrusive and can be ignored when not used.

**Comment by tikotus** [comment]
To be more specific, getSupportedExtension takes >200ms and all the calls to getExtension takes >200ms in total. So they add almost 500ms to my startup time (rather old macbook pro). Not really a bottleneck but the kind of thing that adds up.

Could this be added as a build flag?

**Comment by Squareys** [comment]
There is now an [enableExtensionByDefault](https://emscripten.org/docs/api_reference/html5.h.html#c.EmscriptenWebGLContextAttributes.enableExtensionsByDefault) option when creating the webgl context on emscripten.

Can this issue be closed?

Cheers, Jonathan.
