### ISSUE TITLE
General Cleanup?

### ISSUE THREAD

**Issue by greggman** [emscripten-core/emscripten#5185]
Would you be interested in patches that do general cleanup?

Examples:

remove un-needed attributes

> old
>
>        <script type="text/javascript" src="somescript.js"></script> 
>
> new
>
>        <script src="somescript.js"></script> 

Use modern meta tags

> old
>
>        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
>
> new
>
>        <meta charset="utf-8">
>

Remove deprecated css

> old
>
>        -webkit-animation: rotation .8s linear infinite;
>        -moz-animation: rotation .8s linear infinite;
>        -o-animation: rotation .8s linear infinite;
>        animation: rotation 0.8s linear infinite;
>
> new
>
>        animation: rotation 0.8s linear infinite;
>

Use `===` almost every where

> old
>
>           if (type == 0x8B30 /* GL_FRAGMENT_SHADER */) {
> 
> new
>
>           if (type === 0x8B30 /* GL_FRAGMENT_SHADER */) {
>

Use ES6/ES7 features (given things are switching to WASM and all WASM browsers are ES6/7 compatible things like

*  Use `const` where appropriate
*  Use arrow functions where appropriate

other?

**Comment by kripken** [comment]
Yeah, stuff like that is great!

One thing though about ES6/7, we do have a limitation where we use uglify to process the JS, and it can't handle many ES6/7 features. So before doing much work there, I'd check first (e.g., adding some ES6 feature in preamble.js and then doing an -O2 build, where the optimizer runs, would test that). In the long term we should either upgrade uglify or it may become less important as we focus more on wasm and less on js.

**Comment by rongjiecomputer** [comment]
There are some functions like `cwrap`, `ccall`, `run`and so on that can be benefited from ES6 default parameter. More readable and run faster (and shorter in some cases).

From
```js
function setValue(ptr, value, type, noSafe) {
  type = type || 'i8';
```
To
```js
function setValue(ptr, value, type = 'i8', noSafe = false) {
```

Latest closure compiler can accept ES6 syntax but will transpile it to ES5 syntax (they plan to support ES6 as output code this year).

Uglify shipped with Emscripten throws error. I am not familiar with uglify so I didn't test if latest version works or not.

**Comment by juj** [comment]
@greggman: yes, please, if you have knowledge to do these types of improvements, they would be very much appreciated! One wish here is that these types of modifications would be submitted one "style" of change at a time, much like you grouped in the first comment. That is because it will make regression verification much easier in the odd chance that someone will be running on a browser combination that is not so compatible.

Something to be aware of is that changes that would add towards temporary garbage pressure at the expense of writing convenience should be avoided. The most notable example is perhaps the `for (var i in foo)` vs `for(var i = 0; i < foo.length; ++i)` style of iteration, where the first one allocates a temporary iterator object in both FF and Chrome at least, and the second one doesn't, so that is preferred. (None of the items in your list are of this type of GC generating style, but just to keep in mind, since I'm not too familiar with all the conveniences that are coming in in the new specs).

IE11 and iOS Safari are perhaps the most constrained environments that people are using with Emscripten, so also want to be sure we don't break those, unless when paired with flags that are known not to work there anyways (e.g. `-s WASM=1`)

**Comment by nazar-pc** [comment]
> One thing though about ES6/7, we do have a limitation where we use uglify to process the JS, and it can't handle many ES6/7 features.

Most of ES2015+ features can be handled by modern closure compiler, it can even compile ES2015+ into ES5.

This issue depends on #5109

**Comment by rongjiecomputer** [comment]
Note that even in latest Closure Compiler v20170806 release, if output mode > ES5, certain optimizations depending on type checking might not be available yet.

https://groups.google.com/forum/#!topic/closure-compiler-discuss/hz26hXwmuIE

**Comment by nazar-pc** [comment]
I believe it will be better than version currently in use anyway
