### ISSUE TITLE
mmap and memory growth

### ISSUE THREAD

**Issue by kichikuou** [emscripten-core/emscripten#5187]
test.c:

    #include <emscripten.h>
    #include <fcntl.h>
    #include <stdio.h>
    #include <sys/mman.h>

    int main() {
      EM_ASM({ FS.writeFile('20MB', new Uint8Array(20000000), {encoding:'binary'}); });

      int fd = open("20MB", O_RDONLY);
      mmap(NULL, 20000000, PROT_READ, MAP_PRIVATE, fd, 0);
    }

`emcc -s ALLOW_MEMORY_GROWTH=1 -o test.html test.c`

This raises RangeError inside mmap(), at [this buffer.set() call](https://github.com/kripken/emscripten/blob/55c707ef5969ed8f6154228ea031a2569504a60f/src/library_memfs.js#L363).
The _malloc() call just before that may have expanded memory, but `buffer` still refers old heap area.

Emscripten 1.37.9 / Firefox 53.0

**Comment by kripken** [comment]
#5190 has some code that might help here, but I'm not sure it's the right direction.

**Comment by TysonAndre** [comment]
I've encountered the same issue when using emscripten to compile PHP.

PHP's internal allocator uses mmap to create and extend blocks of memory, and the mmap memory growth bug made me need to apply a workaround.

The workaround was to replace all calls to mmap with stubs using malloc/free instead (this workaround is an inefficient use of memory). https://github.com/TysonAndre/phan-demo/blob/master/zend_alloc.c#L423-L432

The application in question is https://github.com/TysonAndre/phan-demo#phan-in-browser - (Works better in firefox due to needing a lot of memory - it crashes after a few runs in chrome)

**Comment by kripken** [comment]
I think this has been fixed - the testcase no longer crashes, and we did modify the code in that function to handle memory growth. @TysonAndre do you still see the problem on 1.39.1?

**Comment by TysonAndre** [comment]
I'll have to double check with emscripten assertions and without the zend_alloc patch. I thought I updated the SDK first but may be mistaken.

**Comment by TysonAndre** [comment]
**Never mind, you can close this. My issue was related to mmap but seems to have been fixed.** I don't have any questions that are on-topic.

I'm no longer seeing the issue after force refreshing and recompiling the program from scratch, in 1.39.1. I suspect the problem was recompiling with an incorrect version of the patch still on disk.

Additionally, I was reusing a 137M fixed-size memory buffer and compiling with TOTAL_MEMORY_SIZE, to work around a memory leak. So the "memory growth" part of this issue doesn't apply.

--------

I had some off-topic questions, but don't expect them to be easy to answer (checked docs and didn't see anything), and the current state of the application is good enough that they were a low priority.

- Is there a recommended way to run a program with a clean slate every time and dispose of previously loaded file resources, malloced values, and memory Buffers? I'm using `buffer.fill(0)` with a reused fixed-size buffer before loading the entry point again. See https://github.com/phan/demo/blob/master/static/demo.js (generateNewPHPModule and fillReusableMemoryWithZeroes)

  (e.g. effectively reset/clear any static/global variables in C)

  Closures keep references to buffers around, leading to memory leaks
- If anyone knows how you'd properly dispose of all memory used by a webassembly instance, including the memory from preloaded files, that'd be useful. (with variable-size buffers instead of fixed-size.

**Comment by sbc100** [comment]
Maybe as on the mailing list or open a different issue regarding the "restarting" thing.   I don't know off the top of my head how to do that.
