### ISSUE TITLE
emscripten_webgl_create_context doesn't work with Shadow DOM

### ISSUE THREAD

**Issue by sgex** [emscripten-core/emscripten#5230]
I tried upgrading from Emscripten v1.36.1 to v1.37.9 and noticed that emscripten_webgl_create_context returns 0. Compiling with `GL_DEBUG=1` shows the error message

> emscripten_webgl_create_context failed: Unknown target!

Looking at the source code, the issue seems to be here:
 [https://github.com/kripken/emscripten/blob/master/src/library_html5.js#L1794](https://github.com/kripken/emscripten/blob/master/src/library_html5.js#L1794)
```javascript
target = Pointer_stringify(target);
var canvas;
if ((!target || target === '#canvas') && Module['canvas']) {
  canvas = Module['canvas'].id ? (GL.offscreenCanvases[Module['canvas'].id] || JSEvents.findEventTarget(Module['canvas'].id)) : Module['canvas'];
} else {
  canvas = GL.offscreenCanvases[target] || JSEvents.findEventTarget(target);
}
if (!canvas) {
#if GL_DEBUG
  console.error('emscripten_webgl_create_context failed: Unknown target!');
#endif
  return 0;
}
```

In my use case, `target` is `null`, `Module['canvas']` is set to a canvas from a Shadow DOM and `Module['canvas'].id` is set to some string.

Running `JSEvents.findEventTarget(Module['canvas'].id)` in console returns `null` and running `GL.offscreenCanvases[Module['canvas'].id]` returns `undefined`.

But running `Module['canvas']` correctly returns the canvas and `Module['canvas'].id` correctly returns the canvas ID.

The old version worked because it simply used `Module['canvas']` when `target` was `null`.

**Comment by DutchKevv** [comment]
+1

**Comment by juj** [comment]
> I tried upgrading from Emscripten v1.36.1 to v1.37.9

Latest Emscripten is currently 1.37.16. If you are not getting a newer version, it might be due to https://groups.google.com/forum/#!topic/emscripten-discuss/bKCQxN6Q76Y.

I am not familiar with Shadow DOM, but read a bit about this here: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Shadow_DOM. Is this something that you can create a failing test in the `tests` directory for? It sounds like it should be easy to adapt for, but would be good to have a test, since it's a relatively rare feature.

**Comment by sgex** [comment]
> Latest Emscripten is currently 1.37.16. If you are not getting a newer version, it might be due to https://groups.google.com/forum/#!topic/emscripten-discuss/bKCQxN6Q76Y.

Reinstalling from scratch worked, thank you.

> Is this something that you can create a failing test in the tests directory for? It sounds like it should be easy to adapt for, but would be good to have a test, since it's a relatively rare feature.

[Polymer](https://github.com/Polymer/polymer) is a very popular framework that is [built around Web Components and Shadow DOM](https://www.polymer-project.org/2.0/docs/devguide/shadow-dom). That's how I ran into this issue.

I would write a unit test but as noted in the [MDN link you added](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Shadow_DOM), shadow DOM is currently supported on Chrome and Safari but not Firefox. I'm not familiar with Emscripten's policy on working draft specifications that are only implemented by some browsers so I don't know how to proceed.

**Comment by juj** [comment]
> I would write a unit test but as noted in the MDN link you added, shadow DOM is currently supported on Chrome and Safari but not Firefox. I'm not familiar with Emscripten's policy on working drafts that are only implemented by some browsers so I don't know how to proceed.

One way to proceed is to do a test, but skip that from being run by default, based on being conditional to some browsers. If you are able to create and link a small test case to this bug, I could take a peek at what is needed here to fix, since I wrote the regressing change in the GL library.

**Comment by sghiaus** [comment]
I've written a small unit test locally on the `incoming` branch. Since shadow DOM isn't implemented in Firefox, I need to run the test on Chrome.

When I run existing `browser` tests on Chrome, a new window opens and nothing else happens. Every test fails after several seconds (I'm assuming by timeout). The browser's console is empty. On Firefox all `browser` tests pass without any problems.

Command line output for Chrome is:
```
$python runner.py browser
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
Test suites:
['test_browser']
Running test_browser: (326 tests)
[Browser harness server on process 29477]

Running the browser tests. Make sure the browser allows popups from localhost.

test_aniso (test_browser.browser) ... [29486:29536:0714/160807.236457:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
Created new window in existing browser session.
[browser launch: test.html ]
ERROR
test_asm_swapping (test_browser.browser) ... []
Skipping asm validation check, spidermonkey is not configured
[browser launch: test.html ]
ERROR
test_asmfs_dirent_test_readdir (test_browser.browser) ... warning: unresolved symbol: pthread_mutex_lock
warning: unresolved symbol: pthread_mutex_unlock
warning: unresolved symbol: $FS
[browser launch: test.html ]
ERROR
test_asmfs_dirent_test_readdir_empty (test_browser.browser) ... warning: unresolved symbol: pthread_mutex_lock
warning: unresolved symbol: pthread_mutex_unlock
warning: unresolved symbol: $FS
[browser launch: test.html ]
ERROR

etc...
```

Running with `EMCC_DEBUG=1` doesn't produce any useful output.
```
$ EMCC_DEBUG=1 python runner.py browser
DEBUG:root:PYTHON not defined in /home/dev/.emscripten, using "/usr/bin/python"
DEBUG:root:JAVA not defined in /home/dev/.emscripten, using "java"
DEBUG:root:Cache: PID 29836 acquiring multiprocess file lock to Emscripten cache
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 29836 released multiprocess file lock to Emscripten cache
DEBUG:root:check tells us to use asm.js backend
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
DEBUG:root:Checking JS engine ['/home/dev/emsdk-portable/node/4.1.1_64bit/bin/node']
Test suites:
['test_browser']
Running test_browser: (326 tests)
[Browser harness server on process 29843]

Running the browser tests. Make sure the browser allows popups from localhost.

test_aniso (test_browser.browser) ... DEBUG:root:PYTHON not defined in /home/dev/.emscripten, using "/usr/bin/python"
DEBUG:root:JAVA not defined in /home/dev/.emscripten, using "java"
DEBUG:root:Cache: PID 29849 acquiring multiprocess file lock to Emscripten cache
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 29849 released multiprocess file lock to Emscripten cache
DEBUG:root:check tells us to use asm.js backend
WARNING:root:invocation: /home/dev/emsdk-portable/emscripten/incoming/emcc -s IN_TEST_HARNESS=1 /tmp/emscripten_test_browser_PjECeE/aniso.c -o test.html --preload-file water.dds -s LEGACY_GL_EMULATION=1 -lGL -lSDL -Wno-incompatible-pointer-types --pre-js reftest.js -s GL_TESTING=1  (in /tmp/emscripten_test_browser_PjECeE)
DEBUG:root:Checking JS engine ['/home/dev/emsdk-portable/node/4.1.1_64bit/bin/node']
INFO:root:(Emscripten: Running sanity checks)
DEBUG:root:looking for library "GL"
DEBUG:root:looking for library "SDL"
DEBUG:root:compiling to bitcode
DEBUG:root:emcc step "parse arguments and setup" took 0.14 seconds
DEBUG:root:compiling source file: /tmp/emscripten_test_browser_PjECeE/aniso.c
DEBUG:root:running: /home/dev/emsdk-portable/clang/fastcomp/build_incoming_64/bin/clang -target asmjs-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=37 -D__EMSCRIPTEN_tiny__=16 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -isystem/home/dev/emsdk-portable/emscripten/incoming/system/include/libcxx -Xclang -isystem/home/dev/emsdk-portable/emscripten/incoming/system/lib/libcxxabi/include -Xclang -isystem/home/dev/emsdk-portable/emscripten/incoming/system/include/compat -Xclang -isystem/home/dev/emsdk-portable/emscripten/incoming/system/include -Xclang -isystem/home/dev/emsdk-portable/emscripten/incoming/system/include/SSE -Xclang -isystem/home/dev/emsdk-portable/emscripten/incoming/system/include/libc -Xclang -isystem/home/dev/emsdk-portable/emscripten/incoming/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/dev/emsdk-portable/emscripten/incoming/system/local/include -Wno-incompatible-pointer-types /tmp/emscripten_test_browser_PjECeE/aniso.c -Xclang -isystem/home/dev/emsdk-portable/emscripten/incoming/system/include/SDL -emit-llvm -c -o /tmp/tmpvpW81W/aniso_0.o
DEBUG:root:emcc step "bitcodeize inputs" took 0.08 seconds
DEBUG:root:emcc step "process inputs" took 0.00 seconds
DEBUG:root:will generate JavaScript
DEBUG:root:including dlmalloc.bc
DEBUG:root:Cache: PID 29849 acquiring multiprocess file lock to Emscripten cache
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 29849 released multiprocess file lock to Emscripten cache
DEBUG:root:including libc.bc
DEBUG:root:Cache: PID 29849 acquiring multiprocess file lock to Emscripten cache
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 29849 released multiprocess file lock to Emscripten cache
DEBUG:root:emcc step "calculate system libraries" took 0.03 seconds
DEBUG:root:linking: ['/tmp/tmpvpW81W/aniso_0.o', '/home/dev/.emscripten_cache/asmjs/dlmalloc.bc', '/home/dev/.emscripten_cache/asmjs/libc.bc']
DEBUG:root:emcc step "link" took 0.02 seconds
DEBUG:root:saving intermediate processing steps to /tmp/emscripten_temp
DEBUG:root:(not saving intermediate /tmp/emscripten_temp/emcc-0-basebc.bc because deferring linking)
DEBUG:root:emcc: LLVM opts: -strip-debug -disable-debug-info-type-map -internalize -internalize-public-api-list=main,malloc,free,__errno_location,fflush,malloc,free -globaldce -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -vectorize-slp-aggressive=false  [num inputs: 3]
[29852:29914:0714/161030.305416:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
Created new window in existing browser session.
DEBUG:root:emcc step "post-link" took 0.19 seconds
DEBUG:root:LLVM => JS
DEBUG:root:emscript: llvm backend: /home/dev/emsdk-portable/clang/fastcomp/build_incoming_64/bin/llc /tmp/tmpvpW81W/test.bc -march=js -filetype=asm -o /tmp/emscripten_temp/tmp7Wi9Vo.4.js -emscripten-stack-size=5242880 -O0 -emscripten-assertions=1 -emscripten-no-aliasing-function-pointers -emscripten-global-base=8 -enable-emscripten-cpp-exceptions
DEBUG:root:  emscript: llvm backend took 0.0389828681946 seconds
DEBUG:root:emscript: js compiler glue
DEBUG:root:  emscript: glue took 0.26695895195 seconds
DEBUG:root:emscript: python processing: function tables and exports
DEBUG:root:asm text sizes[[272453, 17856], 2708, 202, 4770, 0, 514, 819, 976, 268, 3620, 9935]
DEBUG:root:  emscript: python processing: function tables and exports took 0.00331592559814 seconds
DEBUG:root:emscript: python processing: finalize
DEBUG:root:  emscript: python processing: finalize took 0.000326871871948 seconds
DEBUG:root:emcc step "emscript (llvm => executable code)" took 0.33 seconds
DEBUG:root:setting up files
DEBUG:root:PYTHON not defined in /home/dev/.emscripten, using "/usr/bin/python"
DEBUG:root:JAVA not defined in /home/dev/.emscripten, using "java"
DEBUG:root:Cache: PID 29976 acquiring multiprocess file lock to Emscripten cache
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 29976 released multiprocess file lock to Emscripten cache
DEBUG:root:check tells us to use asm.js backend
water.dds /tmp/emscripten_test_browser_PjECeE/water.dds /tmp/emscripten_test_browser_PjECeE
Packaging file "water.dds" to VFS in path "/water.dds".
DEBUG:root:applying pre/postjses
DEBUG:root:emcc step "source transforms" took 0.04 seconds
DEBUG:root:emcc step "memory initializer" took 0.00 seconds
DEBUG:root:emcc step "js opts" took 0.00 seconds
DEBUG:root:generating HTML
DEBUG:root:emcc step "final emitting" took 0.00 seconds
DEBUG:root:total time: 0.69 seconds
[browser launch: test.html ]
ERROR
test_asm_swapping (test_browser.browser) ... []

etc...
```

I disabled all extensions and pop-up blocking. Chrome version is `59.0.3071.115 (Official Build) (64-bit)` on Ubuntu 17.04.

```
test_aniso (test_browser.browser) ... [29486:29536:0714/160807.236457:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
```
This output only appears once. Could it be related to why all tests fail? My `chrome://gpu` page shows:

```
Graphics Feature Status
Canvas: Hardware accelerated
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Native GpuMemoryBuffers: Software only. Hardware acceleration disabled
Rasterization: Software only. Hardware acceleration disabled
Video Decode: Hardware accelerated
Video Encode: Hardware accelerated
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
```

I'd like to submit the unit test but can't without being able to run it.

**Comment by juj** [comment]
Not quite sure about what would be going wrong. On Windows to run on Chrome I do

```
C:\code\emsdk\emscripten\incoming>set EMSCRIPTEN_BROWSER="C:/Users/juj/AppData/Local/Google/Chrome SxS/Application/chrome.exe"

C:\code\emsdk\emscripten\incoming>python tests\runner.py browser
```

which does work. There is a "popup blocked" notification that appears on the top right, which will need to be set to always allow popups for localhost:8000. I wonder if the popup blocking might have gone to "always disable" in your case?

**Comment by Jero9999** [comment]
It looks like this has never really been fixed. I just came up against it unfortunately.
The issue with trying to run inside a shadow DOM is that the code inside `findEventTarget(target)` uses the code `document.querySelector()`
This will not find the element inside a shadow DOM. 
For background the `document.querySelector()` is only good for querying the "light DOM" which is the overall webpage. That used to be the entire page but now, with custom elements being able to use their own shadow DOMs things are a little more complicated. any html inside a shadow DOM is in a kind of sandbox. To use `querySelector()` and actually find something, you need to use `[shadowDomRoot].querySelector()` rather than `document`. 
It feels to me that the fix here is to allow the webGL create context call to be able to pass in the actual HTMLElement object rather than just an ID. From the OP it sounds like this was the behaviour back in v1.36. Is that the case?

My background: I am actually not the developer of the component using emscripten, I am the dev tasked with trying to get it to run in a custom element which uses a shadow DOM. I finally tracked it down to the call `emscripten_webgl_create_context()` and then to the internal `findEventTarget()`

Oh and I have been using the latest emscripten as at this writing so that should be 2.0.31

**Comment by Jero9999** [comment]
I have actually found a solution for this so I am going to post it here in case anyone gets to this page from google.

You need to be able to modify the module's `specialHTMLTargets` array. There is a compile time switch to export it, otherwise you will get an error.
Then you need to add an entry to it that refers to the DOM element for your canvas (where the webgl context is created on).

So step 1: add the following command line switch to your build script 
    `-s EXPORTED_RUNTIME_TYPES=['specialHTMLTargets']`

Once you have got this done, you can call 
```
    const theWebGlCanvas = <the canvas DOM element inside your shadow DOM>;
    Module.specialHTMLTargets['#the-canvas-id'] = theWebGlCanvas;
```
NB: in the above `#the-canvas-id` is whatever id you pass in to `emscripten_webgl_create_context()`
NB2: that code is in javascript not cpp.
NB3: `Module` will be whatever you decided to call your module when compiling ( using the `EXPORT_NAME=`<module name>` compile switch)
NB4: do not reassign `specialHTMLTargets` to a new object. That will not work. Make sure you modify the existing object as in the example above.

Hopefully this helps
