### ISSUE TITLE
'pipe': symbol multiply defined

### ISSUE THREAD

**Issue by promethe42** [emscripten-core/emscripten#5253]
Hi there,

using Emscripten 1.37.9 on Ubuntu 16.04 64bits, the following code:

```
int pipe;

int main(int argc, char const *argv[]) {

    return 0;
}
```

will produce the following error when linking:

```
error: Linking globals named 'pipe': symbol multiply defined!
```

Renaming the variable to anything but "pipe" (such as "_pipe") fixes the problem.

Regards,

**Comment by kripken** [comment]
What seems to be going on here is that `pipe` is defined in libc, and is not a weak symbol. So both it and your `pipe` are in conflict. Adding `static` to yours fixes it, as then the linker knows to resolve such conflicts.

I'm afraid I'm not enough of a C linker expert to know if this is a bug in the linker, or in musl libc, or somewhere else.

**Comment by juj** [comment]
I wonder what the stance of this is in general in musl or gcc or C standard specifications - where would this kind of behavior be specified? Some functions from musl can currently be overridden since they are weak, but should all of them be? Or in general should one not be able to override any of them?
