### ISSUE TITLE
Problem with old version

### ISSUE THREAD

**Issue by vladbpython** [emscripten-core/emscripten#5257]
Error: No tool or SDK found by name 'sdk-1.12.0-64bit'. Ubuntu 16.04

**Comment by juj** [comment]
Unfortunately we don't have precompiled builds for such old versions. You can try installing the `sdk-incoming-64bit` branch and then manually `git checkout 1.12.0` in Emscripten, LLVM and Clang repositories and reissue `make` in llvm's build directory if that might work. Otherwise building from source is your best bet.
