### ISSUE TITLE
emcc: cannot find library "dl"

### ISSUE THREAD

**Issue by wolf188** [emscripten-core/emscripten#5318]
appear some error message when compile. for example, 
emmake make
Scanning dependencies of target hello.html
[ 50%] Building CXX object CMakeFiles/hello.html.dir/src/main.cpp.o
[100%] Linking CXX executable hello.html
WARNING:root:emcc: cannot find library "dl"
warning: unresolved symbol: glfwWindowHint
[100%] Built target hello.html

**Comment by wolf188** [comment]
I can find the file of libdl.a  at this directory.  "/usr/lib/x86_64-redhat-linux6E/lib64"

**Comment by cpitclaudel** [comment]
You need an emscripten-compiled copy of that library (dl).   Compile it separately, from source (with emscripten), and then add the appropriate flags to `./configure` (presumably something like `env CPPFLAGS="-I${YOUR_COMPILED_LIB's_ROOT}" LDFLAGS="-L${YOUR_COMPILED_LIB's_ROOT}/.libs" emconfigure ./configure`.

**Comment by juj** [comment]
It is safe to ignore that link warning, since Emscripten implements `dlopen()` already in the core shipped libraries.

However there are some caveats. @kripken knows the details here the best. @kripken : would it make sense to add `-ldl` to the set of ignored core libraries? (at https://github.com/kripken/emscripten/blob/master/tools/shared.py#L1984 ?) Or does our support fundamentally differ in some ways from what `libdl` can offer?

**Comment by kripken** [comment]
Probably it makes sense to add to that list, we do have core dlopen functionality working. It has some limitations, but I don't think enough to justify not including it.

**Comment by wolf188** [comment]
https://github.com/wolf188/emscripten_project.git
The test project can not run . why ?? Who can help me ?
emmake make
Scanning dependencies of target hello.html
[ 50%] Building CXX object CMakeFiles/hello.html.dir/src/main.cpp.o
[100%] Linking CXX executable hello.html
warning: unresolved symbol: glfwWindowHint

**Comment by juj** [comment]
`glfwWindowHint` does seem to be present, but looks like it is part of GLFW 3 and requires `-s USE_GLFW=3` linker flag set to enable GLFW 3 instead of the default GLFW 2. Perhaps that is the reason?
