### ISSUE TITLE
Could emscripten::val have a default constructor returning an "undefined"?

### ISSUE THREAD

**Issue by ghost** [emscripten-core/emscripten#5351]
Like the thing that emscripten::val::undefined() gives me. I work with a C++ code generator I can only partially control, and it tries to initialize newly defined variables of type val with val(), which doesn't exist. I can work around this, but an initialization with "undefined" would help. Plus, JavaScript does it like that, if that means anything.

**Comment by noxpo** [comment]
Ok, after taking a closer look, let me convince myself that this could actually be a bad idea :). `val` provides access to the properties of a JavaScript-like object, but it is not a direct representation of it and it probably isn't supposed to be. The lack of e default constructor is just one indicator, the other is the behavior of the copy constructor: it behaves like one and copies the important member, the handle, of the source object `s` to a new object `n`. For the two represented "JS"-objects, this does **NOT** mean copying, it means identity. I assume there are technical reasons for this (rule of three?), so I will wrap `val` into something that shows the expected behavior for the "JS"-object.
