### ISSUE TITLE
Accessing unresolved symbols cause undefined results at runtime

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#5361]
Here is an interesting behavior:

```c
#include <stdio.h>

extern int foo;

int main()
{
	printf("foo: %d\n", foo);
}
```

Build with `emcc a.c -o a.js` and run with `node a.js`. This will print out a warning ```warning: unresolved symbol: foo```

but curiously at runtime, the build will output ```foo: 1668509029```, as opposed to aborting, like we do at runtime if any functions happen to be missing.

As a workaround, one can

a) build with `-s ERROR_ON_UNDEFINED_SYMBOLS=1`, which will complain at build time, or

b) build with `-s SAFE_HEAP=1`, which will abort at segfault at runtime (accidentally I think)

however a) has the disadvantage that the build won't work, and b) has the disadvantage of losing all performance.

Is there a way to make the above type of code follow the idiom "I know there are unresolved symbols in my build, but please complain only if they are actually reached"? (which was the original motivation to default to `-s ERROR_ON_UNDEFINED_SYMBOLS=0` in the first place)

(not a priority at all)

**Comment by kripken** [comment]
Not easily. For functions code is called, so we just put an aborting function there. For global vars, they turn into an import of an integer from js, so we can't abort if the integer is actually used.

We could add a js optimizer pass that turns usages of that import into abort calls. Probably we don't want that by default, but we could do it in safe heap mode perhaps (only when not in LINKABLE mode, as otherwise we don't know at compile time if the import is going to be undefined).
