### ISSUE TITLE
64-bit code generation

### ISSUE THREAD

**Issue by copy** [emscripten-core/emscripten#5370]
https://github.com/WebAssembly/binaryen/issues/964#issuecomment-293648385 says that native 64-bit operations are possible when using the default (asm2wasm) backend. However, when generating standalone modules, function calls such as `getTempRet0` and `___muldi3` are emitted.

```
	emcc src/native/all.c \
	    --llvm-opts 3 \
	    -O3 \
	    -g4 \
	    -s "BINARYEN_TRAP_MODE='allow'" \
	    -s WASM=1 -s SIDE_MODULE=1 -o build/out.wasm
```

```c
int64_t test64(int64_t x, int64_t y)
{
    return x * y;
}
```

```
  (func $_test64 (type $t9) (param $p0 i32) (param $p1 i32) (param $p2 i32) (param $p3 i32) (result i32)
    (block $B0 (result i32)
      (set_local $p0
        (call $___muldi3
          (get_local $p2)
          (get_local $p3)
          (get_local $p0)
          (get_local $p1)))
      (set_local $p1
        (call $getTempRet0))
      (call $setTempRet0
        (get_local $p1))
      (get_local $p0)))
```

This is using `sdk-incoming-64bit` from emsdk.

**Comment by kripken** [comment]
This looks like an issue only with SIDE_MODULE, because by default in code that might be linked we set `EMULATED_FUNCTION_POINTERS`, and that disables wasm-only. That's a temporary limitation, which we need to fix. In fact it might be close to working now, a good starting point would be to try to allow wasm-only mode with that setting and see if any test breaks.

**Comment by copy** [comment]
Setting `LEGALIZE_JS_FFI=0` also forces wasm-only mode, which works for us.

**Comment by sbc100** [comment]
This came up on stackoverflow recently: https://stackoverflow.com/questions/53053297/how-to-generate-a-webassembly-wat-with-i64-instead-of-i32-from-a-c-code/53287391#53287391

**Comment by gerald-dotcom** [comment]
@sbc100 There is a JSON Lib I need to use and I see that it perform well in 64 bit. So what's the compiler flag to compile for 64 bit?

I am not using side modules

**Comment by sbc100** [comment]
Wasm MPV (what llvm calls wasm32) supports 64-bit just fine... the only 32-bit limitation is on the size of the addressable memory, which should not be an issue.   So as long a the JSON library doesn't need to use more than 2Gb of memory it should be just fine.    All arithmetic operations support 64-bit natively already.

**Comment by gerald-dotcom** [comment]
I see. I however get warning,

The simdjson library is designed for 64-bit processors and it seems that you are not compiling for a known 64-bit
      platform. All fast kernels will be disabled and performance may be poor. Please use a 64-bit target such as x64 or 64-bit ARM.

**Comment by sbc100** [comment]
You will probably need to modify the input source code so that i knows about wasm.   Wasm it its own architecture and.. it doesn't support x86-64 or arm64.   Any software that wants to do lower level stuff below the level of normal C code will need to be modified to know about this new architecture.
