### ISSUE TITLE
Settings to make a .wasm file with Emscripten just like in WasmExplorer?

### ISSUE THREAD

**Issue by ghost** [emscripten-core/emscripten#5384]
I am looking for Emscripten command line settings to compile a C file into wasm, exactly like [WasmExplorer](https://mbebenita.github.io/WasmExplorer/) does.

In WasmExplorer console welcome message there is a line:
`Built with Clang/LLVM, AngularJS, Ace Editor, Emscripten, SpiderMonkey, Binaryen and Capstone.js.`.
So it uses the same compiler, no?

In my example `smath.zip` (simple math), there are two .wasm files; one compiled with WasmExplorer and one compiled in Emscripten.  The C source file is there and an html file that loads everything( open the console F12).

The latter was compiled with `emcc smath.c -Os -s WASM=1 -s SIDE_MODULE=1 -o smath-emcc.wasm`, which was the closest I could get. It is still twice the size, and the loading involves a little more JS.

How can I get same results with Emscripten?

[download smath.zip](https://github.com/kripken/emscripten/files/1145616/smath.zip)

**Comment by kripken** [comment]
`SIDE_MODULE` should create a minimal module, so that should have worked. What is the extra size coming from? (Can use binaryen `wasm-dis` or another tool to disassemble the different wasms, and compare them.) And what is the "little more JS" that you mention?

Note that wasm explorer might use the wasm backend instead of the standard compilation method, I'm not sure. Although, that should lead to larger code sizes, not smaller, so something is odd here.

**Comment by juj** [comment]
The output of wasm explorer looks a bit like it could have been compiled with the linker flag `-s ONLY_MY_CODE=1`? i.e. even if one references to malloc or printf, those will not be present, which is what that linker flag does.

**Comment by rbgo** [comment]
The extra space in `SIDE_MODULE` is for dynamic linking provisions inside the wasm, because thats what `MAIN_MODULE` and `SIDE_MODULE` symbols exists for.
I tryed `ONLY_MY_CODE=1` but that makes a +2K .wasm, dumps a big +9MB core file,  a js and html file.
It also gives a traceback dump in the console.

About:  "little more JS"...
Inside the example `smath.zip`, there are two wasm files. They also use their own loader;
smath_emcc.wasm demands the extra importObject be filled in with the right things.
Its not possible to load smath_emcc.wasm on the smath_wax.wasm loader and vice versa. (crash)

WebAssembly Explorer doesn't use Emscripten but the wasm32 LLVM backend, I was told in an issue at their site. The service for the application is here: https://github.com/wasdk/wasmexplorer-service.

I got in touch with WebAssembly and LLVM two weeks ago so there is a lot to learn for me.
But the WebAssembly Explorer compiler service is obviously a lighter weight compiler than Emscripten.
Emscripten is more versatile and comprehensive for compiling complete C applications to the web and so needs a lot more provisions ready to be build in.
So if I come with my 20 lines of C, that results in a .wasm twice the size (150 vs 300 bytes) I will not make a big deal out of it anymore. Sorry for that!

**Comment by kripken** [comment]
Yeah, different compilers here, and the emcc output is stable and supports more things, so there is a little more code there (emcc adds the `post-instantiate` method to set up a dynamic library stack, imports for memory and table, etc.) Only really noticeable in tiny files like this, though, in general wasm-backend output is larger.
