### ISSUE TITLE
Support for std::async (emscripten 1.37.16, firefox 55.0b13)

### ISSUE THREAD

**Issue by guillaumeblanc** [emscripten-core/emscripten#5430]
Hi,

I found all the required information about pthread to make it work properly. However I couldn't find notes about std::async support. I tried a basic exemple (http://en.cppreference.com/w/cpp/thread/async) with the same environment as where pthread is working (emscripten 1.37.16, firefox 55.0b13), but I face the following error: 

TypeError: asm.js type error: asm.js Atomics only enabled in wasm test mode  test_async.js:3:3423
Preallocating 2 workers for a pthread spawn pool.  test_async.html:1237:13
TypeError: asm.js type error: asm.js Atomics only enabled in wasm test mode test_async.js:3:3423
Preallocating 1 workers for a pthread spawn pool. test_async.html:1237:13
Error: Script terminated by timeout at:_emscripten_futex_wait@file:....

Enabling wasm (-s WASM=1) requires to remove pthread compilation flags. It builds but the result is also that the script doesn't ends / blocks.

Did I miss something about std::async support, or compilation options?

Regards,
Guillaume

**Comment by kripken** [comment]
asm.js atomics and multithreading are not supported in browsers, who are focusing on wasm. However, wasm doesn't have multithreading yet.

In principle, though, pthreads works in asm.js, just without the browser optimizing it as asm.js (see tests in the test suite for working examples). So the question is what APIs are needed for std::async, building with LIBRARY_DEBUG to log out library calls might help (it may be using an unsupported part of pthreads).

**Comment by juj** [comment]
C++11 based multithreading API is still in the works, currently multithreading is tested to work only with the pthread API. (I think C++11 threads use the C++11 thread keyword for TLS which I haven't yet gotten around to implementing, which is where most of C++11 threading code will fail at)

If you have small C++11 based test apps to showcase the nonfunctional features, those will be helpful when I get to creating a C++11 threading test suite.

To resolve the error `TypeError: asm.js type error: asm.js Atomics only enabled in wasm test mode`, you can set the environment variable `JIT_OPTION_asmJSAtomicsEnable` to `true` for the environment where you run Firefox in. This env. var is because asm.js based SharedArrayBuffer is currently not intended to ship in Firefox.

The messages `Preallocating 2 workers for a pthread spawn pool.` are ok if you don't need to synchronously create threads. You can pass a `-s PTHREAD_POOL_SIZE=4` linker flag to "pre-warm" a pool of pthreads to enable support for synchronously spawning threads. It is possible that missing this linker flag is the cause of `std::async` not working.

Also remember to pass `-s NO_EXIT_RUNTIME=1` if you want pthreads to stay alive when `main()` exits on the main thread, otherwise they will be terminated as the C runtime closes at the end of `main()`.

**Comment by guillaumeblanc** [comment]
I didn't get more info with `LIBRARY_DEBUG` which I might have misused.

I created PR #5476 with std::async unit tests. I hope it can help.

`-s PTHREAD_POOL_SIZE=4` doesn't fix the issue (reproduced in the unit test). I found that if enough threads (>= 15, don't know why!) are preallocated, then the test passes. It can mean the issue is about thread pooling, or maybe it's just a timing luckiness.

**Comment by guillaumeblanc** [comment]
You asked for a small c++11 based app that showcases the nonfunctional feature. I submitted one: https://github.com/guillaumeblanc/ozz-animation/tree/master/samples/multithread. It reproduces the same issue as #5476 unit tests. Even if many threads are preallocated, it still hangs after some time, like if threads from the pool aren't reused.

**Comment by juj** [comment]
> -s PTHREAD_POOL_SIZE=4 doesn't fix the issue (reproduced in the unit test). I found that if enough threads (>= 15, don't know why, it should be 10!) are preallocated though, then the test passes.

This sounds like the issue is then as mentioned here http://kripken.github.io/emscripten-site/docs/porting/pthreads.html:

```
"When the linker flag -s PTHREAD_POOL_SIZE=<integer> is not specified
and pthread_create() is called, the new thread will not actually start to run
immediately, but the main JS thread must yield execution back to browser
first. This behavior is a result of #1049079."
```

This is something that the new Multithreading series of PRs will resolve, after which, if `-s PROXY_TO_PTHREAD=1` flag is used, then threads are able to start synchronously and the above effect is avoided.

**Comment by FrancoisChastel** [comment]
Any news about the support of `async` on `wasm`/`asm.js` ? @kripken

**Comment by kripken** [comment]
@FrancoisChastel no news I am aware of. but wasm threads are progressing well, so if someone wants to take a look at that now might be a good time.

**Comment by FrancoisChastel** [comment]
I will make a try with wasm threads, if I see any bug(s) or/and if I can contribute at anytime on it I will do so !

**Comment by VirtualTim** [comment]
So I just stumbled upon this issue googling something else, and I though I'd mention that I'm using std::async without problems. My code looks like this (function/class names changed to protect their identity):
```
std::future<Error> futureError( std::async([&]{
  return aClass->Open(openInfo);
}) );

anError = futureError.get();
```

**Comment by Anil8753** [comment]
> So I just stumbled upon this issue googling something else, and I though I'd mention that I'm using std::async without problems. My code looks like this (function/class names changed to protect their identity):
> 
> ```
> std::future<Error> futureError( std::async([&]{
>   return aClass->Open(openInfo);
> }) );
> 
> anError = futureError.get();
> ```

Could you please provide the complete source of std::async/std::thread with the compilation flags

```
    auto a2 = std::async(std::launch::async, [](){
        std::cout << "Worker thread=" << std::this_thread::get_id() << std::endl;
        return "hello from defered\n";
    });

    a2.get();
```

**Comment by VirtualTim** [comment]
I was using this as part of a much larger project.
However I did log this bug (#8988) a while back which included a complete example. Does that help?

**Comment by Anil8753** [comment]
> I was using this as part of a much larger project.
> However I did log this bug (#8988) a while back which included a complete example. Does that help?

Yes, it helped. Thank you.
