### ISSUE TITLE
Simpler memory allocation when using with pointers

### ISSUE THREAD

**Issue by nazar-pc** [emscripten-core/emscripten#5449]
It is quite painful for JavaScript developers to allocate memory for calls to the functions, that expect pointers as arguments.
Would be nice to have some wrapper methods that hide the complexity and provide nice and clean interface for memory allocation.

Currently several steps are needed:
* allocate memory on the heap
* create a array view using pointer from previous step
* set value on view
* use pointer in function call
* free allocated memory

More conveniently would be to:
* allocate memory (with optional default value)
* use pointer from previous step in function call
* free allocated memory (optionally free all of allocated memory since the beginning with single call for stateless use)

This saves a few lines and requires less variables each time user wants to allocate memory.

I'll provide a reference implementation with examples shortly.

**Comment by juj** [comment]
It is recommend not to create temporary views to the allocated pointers, but reuse the existing `HEAP32`, `HEAPF32`, etc. views, since that is a JS garbage collector free way to access the memory. E.g.

```javascript
var foo = _malloc(4);
HEAP32[foo>>2] = value;
_callCFunction(foo);
_free(foo);
```

Of course you can create such helpers that create typed arrays if desirable. In JS libraries you can also use the `{{{ makeGetValue(...) }}}` and `{{{ makeSetValue(...) }}}` helpers to write to memory.

**Comment by nazar-pc** [comment]
I've updated PR using what you've said, should be slightly simpler and more efficient.
