### ISSUE TITLE
Releasing memory from module

### ISSUE THREAD

**Issue by m-karcz** [emscripten-core/emscripten#5456]
Hi,
I've got problem with memory taken by each module instance - once memory is allocated by module, it is not returned to OS after releasing it. It can be reused by same module, but it is never released to OS, even after end of main() or emscripten_force_exit(). Even simple new/delete[] program suffers from that. 

```cpp
int main()
{
    char* ptr = new char[255*1024*1024];
    delete[] ptr;
}
```

After creating and closing few instances of module, Chrome just crashes because of having more than 4GB allocated. The only flag I use is ALLOW_MEMORY_GROWTH=1 in this case, but I create modules using MODULARIZE=1 and WASM=1

Is there any way to release memory taken by module?

**Comment by juj** [comment]
Try using browser's profiling tools to figure out what is holding on to the memory of a module. Once all references to it are released, it should get garbage collected automatically and freed.

**Comment by mamcienahita** [comment]
When I had single Module object, i had to remove also reference to all global HEAPxxx objects and global 'buffer' object. It's annoying, but works. 

But when it comes to MODULARIZE=1, I've got no idea what's going on. There is reference 'buffer' in 'system / Context' but I've got no idea what and where it is. There are some references to 'Module', but had other name in EXPORT_NAME='"test"'.
![memoryprofiler](https://user-images.githubusercontent.com/9076175/29170676-047d47e6-7dda-11e7-8a29-a25cf7988f06.PNG)
![module](https://user-images.githubusercontent.com/9076175/29170677-04843a7e-7dda-11e7-9060-883465f9d99d.PNG)

**Comment by kripken** [comment]
In principle MODULARIZE should keep everything in a single function scope. So unless you capture something from it and keep it alive that way, it should all be dce'able once the instance is not held on to. Unless we are somehow leaking something to the global scope?

Another possibility is that you are hitting a chrome bug, might be worth trying in other browsers and their memory devtools.

**Comment by Mirovsky** [comment]
I know it might be a late but I tried to solve same issue, we are creating multiple module (about 500MB per object of memory) objects almost at the same time (deleting the old ones along the way) and the memory wasn't being freed after all the references were cleared.

Thanks to https://github.com/kripken/emscripten/pull/6205 I was able to solve it because of attached `gamepadconnected` and `gamepaddisconnected` events. This may be the same cause, confirming the leak to global scope.

**Comment by jymaps** [comment]
Hi guys, can anyone post the solution to this problem? I am having the same issue of releasing memory from module.

**Comment by tdmaienschein** [comment]
I think the following event listener may cause a leak:
- https://github.com/emscripten-core/emscripten/blob/474daf4ac237c5566f2a545f469506f1989ad591/src/library_browser.js#L287

It seems that the `pointerLockChange` function would keep `Module` alive, and it's never removed from `document`.  Some evidence for this is that when experiencing the leak using FIrefox, I see the following retaining paths on the `ArrayBuffer`:

![retaining paths x10 - event](https://user-images.githubusercontent.com/21227813/68513210-0dbeec00-0240-11ea-9ced-a0e9e631310d.png)

Note the presence of `mCallback`.  Now, if I comment out the lines indicated above which add the `pointerLockChange` event listener, I see the following retaining paths:

![retaining paths x10 - no event](https://user-images.githubusercontent.com/21227813/68513337-62fafd80-0240-11ea-9227-3f4bdfb90f76.png)

Note the absence of `mCallback`.  In this case garbage collection does take place and the memory is freed as expected (it doesn't happen immediately, which is why In the screenshots the memory usage looks the same--but it does fall back down to the baseline memory usage in the latter case).

**Comment by kripken** [comment]
@tdmaienschein Event handlers can keep everything alive on the web, that's very true, yeah. You need to remove event handlers when the application can be cleaned up - that has to be done manually. Things like `SDL_Quit` should do it for you. If you called one of those to exit, but this still happens, that would be a bug.

Thinking on this now, I wonder if we can use WeakRef support to avoid this, by making event handlers only refer weakly to the module. I opened https://github.com/emscripten-core/emscripten/issues/9820 to think more on that.
