### ISSUE TITLE
Portable install fails on Windows

### ISSUE THREAD

**Issue by l0calh05t** [emscripten-core/emscripten#5472]
We are on Windows 10, and the portable install fails on all machines for us. Example (run from a directory with a fresh unzip of `emsdk-1.35.0-portable-64bit.zip`):

```
D:\tools\emscripten-portable>emsdk update
Error parsing emsdk_manifest.json!
[Errno 2] No such file or directory: 'D:/tools/emscripten-portable/emsdk_manifest.json'
Downloading: D:/tools/emscripten-portable/zips/emsdk_windows_update.zip from https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_windows_update.zip
Unpacking 'D:/tools/emscripten-portable/zips/emsdk_windows_update.zip' to 'D:/tools/emscripten-portable'
Unzipping file 'D:/tools/emscripten-portable/zips/emsdk_windows_update.zip' failed due to reason: [Error 183] Cannot create a file when that file already exists: 'D:/tools/emscripten-portable'
Fetching all tags from Emscripten Github repository...
Done. 105 tagged releases available, latest is 1.37.18.
The batch file cannot be found.

D:\tools\emscripten-portable>emsdk install latest
'emsdk' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by juj** [comment]
The Windows specific getting started documentation has changed a bit, see https://github.com/kripken/emscripten/blob/incoming/site/source/docs/getting_started/downloads.rst (we don't quite yet have that uploaded to newest live docs due to merge issues)

Can you try downloading latest emsdk afresh from https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable-64bit.zip?

**Comment by l0calh05t** [comment]
Sadly, the refs like :ref:`install Emscripten SDK on Windows <sdk-installation-instructions>`. Are all broken and I can’t find any new documentation for Windows on that page.

**Comment by l0calh05t** [comment]
However, the linked version works fine with the generic instructions.

**Comment by juj** [comment]
Kripken pushed updated documentation live now, try checking it out again on the doc page.

**Comment by russaa** [comment]
this problem seems to still exist:  
apparently, the update process tries to unzip the downloaded file `emsdk_windows_update.zip` into to the Emscripten root directory, but Windows 10 won't allow it, because it already exists(?)

maybe it could be solved by using some additional options/flags when trying to unzip(?)

as a workaround:  
I could proceed by unzipping the file manually and copying the contents to the Emscripten root folder, and then continue with the next step of the general instructions, i.e. running `emsdk install latest`

**Comment by clach04** [comment]
I hit this too, @russaa workaround allowed me to avoid this.

Setting VERBOSE in the environment enabled some debug tracing it its attempting to remove the SDK directory.
