### ISSUE TITLE
node.js support and npm repository

### ISSUE THREAD

**Issue by dcollien** [emscripten-core/emscripten#55]
It should be simple (and very useful) to have node.js running emscripten, as a npm module

**Comment by k2snowman69** [comment]
> Having a single runtime to completely run emscripten sounds like hell of a benefit to me :)

Agreed. Running a mixed build windows and mac here and since most developers are either C++ or JavaScript the dependency on python seems very unnecessary and quite large. Where anyone using this tool likely has node running somewhere. This doubles with the current workaround documented (http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html) that requires windows users to install python separately (e.g. barrier to entry).

That said, as of today there are 237 `.py` files in the emscripten repository which would make this task quite large.
