### ISSUE TITLE
Building with LLVM's WASM backend fails autotools configuration checks

### ISSUE THREAD

**Issue by rakuco** [emscripten-core/emscripten#5549]
I'm trying to port an existing autotools-based project, and decided to give the bleeding-edge workflow a try to see how it would compare to the traditional, asm.js-based one.

With LLVM/clang's master branches + Binaryen's master branch + Emscripten's incoming branch, several configuration checks are failing due to the way autotools detects whether some functions are present or not.

    AC_CHECK_FUNCS(strnlen)

becomes a C-file that looks like

```c
char strnlen();
int main() { return strnlen(); }
```

which clang, GCC and clang+fastcomp all build and link just fine despite the fact that `strnlen` has a different prototype in `string.h` (autotools is only interested in whether the function exists).

With LLVM's WASM backend, that configuration check fails with a very long message that boils down to

    [wasm-validator error in function $main] unexpected false: call param number must match, on
    [i32] (call $strnlen)

**Comment by rakuco** [comment]
@kripken @juj

**Comment by juj** [comment]
The story here is that

`a.c`:

```c
char strnlen();
int main() { return strnlen(); }
```

with `gcc a.c -o a` does indeed finish with success (running gives a segfault), but the program is undefined behavior due to [C99 6.5.22](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf):

```
If the expression that denotes the called function has a type that does not include
a prototype, [...]. If the number of arguments does not equal the number of
parameters, the behavior is undefined.
```

The same standard clarifies about undefined behavior in section 3.4.3:

```
undefined behavior

behavior, upon use of a nonportable or erroneous program construct or
of erroneous data, for which this International Standard imposes no requirements

NOTE Possible undefined behavior ranges from ignoring the situation completely
with unpredictable results, to behaving during translation or program execution
in a documented manner characteristic of the environment (with or without the
issuance of a diagnostic message), to terminating a translation or execution
(with the issuance of a diagnostic message).
```

So the C99 standard agrees that aborting already at compilation time is valid treatment of undefined behavior, and the proper fix should go to Autotools to stop relying on undefined behavior.

That being said, if you can come up with a good PR to contribute to make Emscripten turn the blind eye for this kind of broken behavior, perhaps that could be added in as an option, perhaps as some kind of autotools specific configure hack. (we already have an `EMCONFIGURE_JS` environment variable that is a bit similar)

**Comment by dschuff** [comment]
I'll add a general +1, and a specific opinion:
We (emscripten) should definitely not change our behavior to tolerate this by default. Hacking around this kind of UB in a general way just leads to madness. (our recent experience with a  pass in the LLVM wasm backend that does something similar has shown that as well). Autotools should just not be doing this. Having said that though, I totally recognize that even if autotools were fixed today, it might not propagate to all the autotools users before the heat death of the universe. So since we do already have some autotools hacks that you have to opt into (correct me if I'm wrong about that), then I'd be ok with adding one of those to handle this case.

**Comment by juj** [comment]
Yeah, we would not need to do this by default, but having an option to specifically hack for this for legacy compatibility would help here.

**Comment by Kagami** [comment]
So seems like it's not possible to use LLVM WebAssembly backend with autotools currently? I've encountered this issue with lame library (it checks for `strtol` function).

**Comment by dschuff** [comment]
It looks like it, (at least for some versions of autotools?). I guess nobody has attempted to make a workaround. One possibility might be to compile a list of functions that autotools might check for and call the wrong way (e.g. `strnlen` and `strtol` in this case), make a library that just has no-op implementations of those, and then make emscripten automatically link that library by default in the autotools-hack mode (then those functions would not be linked in from libc). We'd have to make sure that the set of functions we put in that shim library matches the set of functions we actually have in our libc.
