### ISSUE TITLE
Generated js wrapper is massive

### ISSUE THREAD

**Issue by yetithefoot** [emscripten-core/emscripten#5560]
I'm playing with `emcc` and realized that resulting js file contains instructions for different environments. I'm going to use my assembly only in worker environment, but have to deal with code like:
```javascript
if(ENVIRONMENT_IS_NODE){
...
}
```

Is there a way to not generate environment specific code and save few bytest? I dug thru sources and found that some options applied at compile time, but some at runtime. What is design behind this?

<img width="660" alt="screenshot at sep 06 19-47-32" src="https://user-images.githubusercontent.com/699027/30126604-ac452d5a-933c-11e7-9c27-62d9ccdf563f.png">

**Comment by kripken** [comment]
Yeah, we could save a little code size here. See #5554 for a current discussion on the matter.

I think this hasn't happened yet because the savings is pretty slim - there isn't much node.js specific code, for example. While in comparison, the pthreads code is both large, and must be included only when needed (as it does things that don't work otherwise, so not including it is not just an optimization).

**Comment by echeese** [comment]
The reason that some are done at runtime is because the same `.js` file can be used in node and browser and other environments. Personally, I've created my own minimal `shell.js` and passed it in via `emcc`'s `-s SHELL_FILE` option. Didn't really cut down by too much, however.

**Comment by yetithefoot** [comment]
One more question is if my intent is just use code in WebWorker, do I really need NODE_FS in this file?

**Comment by puzrin** [comment]
> I think this hasn't happened yet because the savings is pretty slim - there isn't much node.js specific code, for example.

@kripken i would not agree with this statement. Benefit can be in sync init & sybc functions api. For example, see wrapper for google's `woff2` webassembly build https://github.com/fontello/wawoff2/blob/master/compress.js. All necessary functions are sync, but we had to use async interface because of event-driven (async) emscripten core init.

PS. browsers have size limits for sync wasm load (async load is limitless). I don't know situation with nodejs, but i'm sure this can be solved.

**Comment by kripken** [comment]
@puzrin I don't understand, the sync/async issue seems separate from whether node.js support is included or not?

**Comment by puzrin** [comment]
@kripken from my point of view, it's the only reason for wrapper change, because it adds significant value.
