### ISSUE TITLE
Custom linker data sections and __start/__stop pseudo symbols?

### ISSUE THREAD

**Issue by martijnthe** [emscripten-core/emscripten#5572]
In our project we're making use of a linker feature to gather variables from different compilations units in a particular section, using `__attribute__ ((section(my_custom_section)))`.
GNU ld automagically emits `__start_my_section_name` and `__stop_my_section_name` pseudo-symbols that point to the beginning and end of the section and are really handy to iterate over the variables you put into the section.

When transpiling code that uses this feature, we're getting errors that those `__start...` and `__stop...` symbols cannot be resolved.

Are we missing something? Or is just not supported at all?

**Comment by dschuff** [comment]
I'm guessing that due to the way emscripten links programs (i.e. it has its own custom linking logic and merges LLVM bitcode itself), that this functionality is just not implemented. For WebAssembly, we are working on a port of lld to hopefully replace all this logic, and it should support that behavior.

**Comment by martijnthe** [comment]
cc @jiangzidong

**Comment by sbc100** [comment]
This is now fixed in upstream llvm
