### ISSUE TITLE
Legacy OpenGL status - state saving and etc.

### ISSUE THREAD

**Issue by xprogram** [emscripten-core/emscripten#5590]
As far as I know (from diving into `src/library.js` and compilation attempts), there is no support for `glPushAttrib` and `glPopAttrib`. I was attempting to compile a small physics library with a demo that used those functions and I ran into `unresolved symbol` messages. I figured I might as well implement them in the JS library, because it would help everybody else with the problem, instead of trying to compile Regal or implement it directly into C++; the former is just too much work for a simple physics library targeting an extra platform, and the latter is just plain odd in my opinion. However, looking through the library file I found it pretty hard to understand anything; all emulations were right next to each other. Maybe have different library files for each implementation (`src/library_oldgl.js`, `src/library_gles.js`)? That could potentially make compilation faster, because you're only reading half of the code you normally would to fetch the required symbols (unless I'm missing something), because an average GL application only uses one version of GL.

Also, it doesn't seem that error reporting is supported with legacy GL, in addition to its missing commands. Temporary design choice, I guess?

**Comment by juj** [comment]
I have wanted to split off legacy GL emulation away from `src/library_gl.js` as well for a long time, due to "out of sight - out of mind" reasons. I'll see if I can give that a go at some point - in general you can see all the emulation related code inside `#if LEGACY_GL_EMULATION` blocks in that file, which might help separating those two a bit.
