### ISSUE TITLE
timezone variable keeps improper value

### ISSUE THREAD

**Issue by Zdreni** [emscripten-core/emscripten#5652]
For a code below, native and emscripten results are different:
```
#include <time.h>
#include <stdio.h>

int main()
{
	tzset();
	printf("timezone = %ld, daylight = %d\n", timezone, daylight);
	return 0;
}
```

$ ./a.out
timezone = -7200, daylight = 1
$ node a.out.js
timezone = 10800, daylight = 1

**Comment by lpotter** [comment]
I am seeing different values as well:

emsdk: timezone = 36000 daylight = 0
native: timezone = -36000 daylight = 1

**Comment by brion** [comment]
There appear to be two things wrong:

First, the timezone is mistakenly negated when converted from minutes to seconds: https://github.com/kripken/emscripten/blob/f585dcbc2d929ef8b8bc6813e0710ec3215ac0b1/src/library.js#L2085 This should have the "-" removed.

Second, the daylight savings check fails in node... I'm not exactly sure but I think node (at least node 4.2) only knows the last few years' worth of timezone history. This value is filled in with a heuristic to check if DST existed in the year 2000: https://github.com/kripken/emscripten/blob/f585dcbc2d929ef8b8bc6813e0710ec3215ac0b1/src/library.js#L2087-L2089

which fails in node, because it sees only the non-DST time at least in my timezone, for year 2000. Bumping up to year 2006 seems to fix the heuristic check?

**Comment by froydnj** [comment]
I submitted #6125 to fix the negation issue.  

> Second, the daylight savings check fails in node... I'm not exactly sure but I think node (at least node 4.2) only knows the last few years' worth of timezone history. This value is filled in with a heuristic to check if DST existed in the year 2000:

I skimmed through the node sources, but I didn't see anywhere obvious that would only record a few years of timezone history; AFAICT node relies on v8 here, which in turn relies on the system libc, which ought to be correct?  Or perhaps recent versions of node depended more explicitly on v8 here, rather than rolling a custom solution?

@brion, do you remember anything more here?

**Comment by brion** [comment]
Hmm, the tz check is coming up as '1' for me in both node 4.1.1 and 9.4.0 on Mac OS X 10.13.2. I think I tested that under Ubuntu previously? Will try to repro again...

**Comment by brion** [comment]
Ok, I can repro the 'daylight=0' on:
* node 7.10 on Windows 10 (current Insider build)
* node 8.9.4 on Windows 10 (current Insider build)
* node 4.1.1 on Ubuntu 16.04 running in Windows 10's WSL environment

I can resolve it on Ubuntu/WSL by setting `export TZ=America/Los_Angeles` (it was previously unset!). Not sure how to handle on raw Windows...

**Comment by brion** [comment]
Answer to the DST issue: my Windows VM had timezone set to "Coordinated Universal Time -8" instead of to the actual local timezone ("Pacific Time (US & Canada)"). Probably a side effect of Parallels Tools syncing my time with the Mac host environment. :(

Thus it had the correct timezone offset for current dates but wrong for those in the opposite DST state... Fix is to set the timezone to the correct value in Settings/Control Panel instead of the wrong one:

![whoopstime](https://user-images.githubusercontent.com/103075/35331826-96ce92ba-00bd-11e8-8444-362fe9cddf29.png)

I don't think there's anything much to be done to work around the time zone just being set wrong, so I think we're ok to close this bug after the prior fix for the sign of the offset.


Details:

V8's Date class on Node's Windows backend depends on the system `localtime_s` function to get local timezone information -- however the returned `tm` structure returns 0 in the `is_dst` member for both the January 1, 2000 and July 1, 2000 dates where I expect to see `is_dst == 1` for one of them (depending on hemisphere) if supported timezone.

Can verify this with a short C++ program:

```cpp
// tztest.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <time.h>
#include <stdio.h>

int main()
{
	// first date: 946713600
	// second date: 962434800
	time_t ts = static_cast<time_t>(946713600);
	tm mytm;
	errno_t err = localtime_s(&mytm, &ts);

	printf("err is %d\n", (int)err);
	printf("mytm.tm_hour is %d\n", mytm.tm_hour);
	printf("mytm.tm_isdst is %d\n", mytm.tm_isdst);

	ts = static_cast<time_t>(962434800);
	err = localtime_s(&mytm, &ts);

	printf("err is %d\n", (int)err);
	printf("mytm.tm_hour is %d\n", mytm.tm_hour);
	printf("mytm.tm_isdst is %d\n", mytm.tm_isdst);


	getchar();

    return 0;
}
```

That ends up correct when the system TZ is an actual timezone, but fails when it's a fixed offset, as one might reasonably expect.
