### ISSUE TITLE
I am using MS Visual Studio 2013, can I use it instead of Visual Studio 2010 for emscripten?

### ISSUE THREAD

**Issue by xiajiuyan** [emscripten-core/emscripten#5730]
I have already installed MS Visual Studio 2013.
When I install emscripten, it tells me to install Visual Studio 2010.
Must I install install Visual Studio 2010 ?

Thanks for your reply.

**Comment by juj** [comment]
Visual Studio 2010 is no longer supported, it was required for the vs-tool integration, but vs-tool has since been discontinued.

Upstream LLVM no longer supports building with Visual Studio 2013. We recommend using Visual Studio 2015, or Visual Studio 2017 (Community Edition is preferred over Express).

You can try your luck with Visual Studio 2013 with

```
git clone https://github.com/juj/emsdk.git
cd emsdk
emsdk install --vs2013 --build=Release sdk-incoming-64bit binaryen-master-64bit
emsdk activate --vs2013 --build=Release sdk-incoming-64bit binaryen-master-64bit
cd emscripten\incoming
em++ tests\hello_world.cpp -o a.html
```

but I think this will run into trouble with some errors.
