### ISSUE TITLE
Sub-process utilities in Python?

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#5876]
Continuing a discussion in #5859: we use sub-processes quite a lot, both in the toolchain and in the test suite. It's not clear what the best practices are for that.

 * `tools/shared.py` has some wrappers, `execute, check_execute, check_call`, should we always call those?
 * Is it ok to call `subprocess.check_call` directly in test code, where we don't need the extra logging those wrappers provide, and it looks more like regular python? Or should we do it there too for regularity?
 * Why does `execute` have `cmd[0] = Building.remove_quotes(cmd[0])` but none of the others? Is it a bugfix or just for clarity of the error logging?
 * How does the universal-newlines problem fit in here?
 * We modify `Popen` on Windows, so that code can use `Popen` normally - should we override `subprocess.check_call` etc.?

We should probably write up a guide for this.

**Comment by dschuff** [comment]
- In general I am of the opinion that if wrappers exist, they should be used everywhere they might apply (even if e.g. they are most useful in the compiler rather than test code). Both for general consistency, and if in the future someone wants to change the wrapper behavior such that it becomes relevant for the test code.
- No idea about the `remove_quotes` bit or the universal-newlines problem.
- Also not sure about the details of the windows thing, but based on the comment it might only apply when we are trying to capture the streams with `PIPE`, so maybe `check_call` would be ok?

One trick I did to make this kind of thing easier in the waterfall script, was to create a drop-in replacement for subprocess: https://github.com/WebAssembly/waterfall/blob/master/src/proc.py 
It imports and re-exports all of subprocess except for the things it overrides, so it's easy to implement and modify. (to use it, we just do `proc.check_call` instead of `subprocess.check_call`).

**Comment by dschuff** [comment]
Oh btw it might also make sense to have some special-case utilities e.g. for calling emcc recursively. @aheejin found a fun bug on the waterfall (https://github.com/WebAssembly/waterfall/pull/290) and it occurred to me that disabling sanity checks on recursive emcc calls could speed things up even in "normal" use.

**Comment by saschanaz** [comment]
That `WindowsPopen` thing is not documented and is completely optional even on Windows (as it requires `EM_POPEN_WORKAROUND`). I guess somehow this is fixed on MSYS side, if there was no issue for a long time?

**Comment by kripken** [comment]
#5843 resolved some of this, but still some open stuff. Also, we should document the best practices here (also with strings).
