### ISSUE TITLE
Provide a test for #5905

### ISSUE THREAD

**Issue by saschanaz** [emscripten-core/emscripten#5908]
#5905

Opening this so that we won't forget it. @kripken @dschuff

**Comment by kripken** [comment]
I'm not sure what the issue was there, but if it was that all wasm backend usage was broken, then we could probably check that easily by adding a test with `EMCC_WASM_BACKEND=1` in the env, in `other`. Even without a stock LLVM, the wasm backend in fastcomp may be capable of building a hello world. (However, maybe not, given all the changes to s2wasm and that stuff, so I'm not sure...)

**Comment by dschuff** [comment]
You could make a test for clang version and for backend support with it, although I don't think the backend support checks are prepared for an LLVM that has both JSBackend and wasm. but then the real problem is that to use it you'd need to actually build either 2 LLVMs (as we do on the waterfall) or a single LLVM that supports both. And if you do have that and want to test the wasm backend, then every single emscripten test covers this code. so the problem isn't that this failure went unnoticed, it's just about where it's noticed. If we want to see the failures on github we could get builds of the upstream backend from the wasm-stat.us waterfall the way we do with emsdk builds.

**Comment by dschuff** [comment]
IIUC this is basically fixed because emscripten's CI uses builds from the new releases system.
