### ISSUE TITLE
--proxy-to-worker forces WebGL to rollback to 1.0?

### ISSUE THREAD

**Issue by ziocleto** [emscripten-core/emscripten#5961]
I've read about WebGL being implemented on web workers on issue #2396 but that was 3 years ago.

Now if I use --proxy-to-worker I can see that there's an attempt to map webGL functions into a _GLctx_ but it's incomplete for **WebGL2.0** as functions as bindBufferBase are not present.

By querying OpenGL capabilities at startup I also obtain 2 different outputs:

With --proxy-to-worker:

> WebKit WebGL
> **WebGL 1.0** (OpenGL ES 2.0 Chromium)
> OpenGL ES GLSL ES 1.00 (WebGL **GLSL ES 1.0** (OpenGL ES GLSL ES 1.0 Chromium))
> 

No --proxy-to-worker:

> WebKit WebGL
> OpenGL ES 3.0 (**WebGL 2.0** (OpenGL ES 3.0 Chromium))
> OpenGL ES GLSL ES 3.00 (WebGL **GLSL ES 3.00** (OpenGL ES GLSL ES 3.0 Chromium))

(There's also a bug querying GL_VERSION inside worker.js but that's for another day)

**Comment by kripken** [comment]
Yes, the WebGL proxying was written before WebGL 2.0, and it has not been updated. It might make sense to improve that, but another option will eventually be to use threads, @juj is working on running GL from a background thread, including with proxy-to-worker, and I think that will work with WebGL 2.0.

**Comment by juj** [comment]
There is a fundamental web spec limitation with proxying via postMessage that all proxying needs to be asynchronous, and synchronous proxying is not possible. This restricts the extent that `--proxy-to-worker` can perform proxying of WebGL, and it's more an experimental work rather than something that one could rely on in a stable manner. This proxying was implemented in WebGL 1 era, and after WebGL 2 came out, because of the limitations, nobody has had much interest in expanding it to WebGL 2, so WebGL 2 does not work like you're seeing. (If you're interested, feel free to submit patches)

The proper way we'll get WebGL 1 & 2 to Web Workers / pthreads is to use SharedArrayBuffer and OffscreenCanvas. This support will be proper and gives all the features. You can try it out today if you link with `-s OFFSCREENCANVAS=1` and/or `-s PROXY_TO_PTHREAD=1`, although this may be a bit too early, since neither OffscreenCanvas and SharedArrayBuffer-in-Wasm has yet shipped, so you'll need a Firefox Nightly or a Chrome Canary to test this out.
