### ISSUE TITLE
wasm backend: memory alignment problem

### ISSUE THREAD

**Issue by tbfleming** [emscripten-core/emscripten#5996]
```alignof(max_align_t)``` is 16, but ```malloc``` sometimes aligns to 8.

build:
```
em++ --std=c++11 test-alignment.cpp -o test-alignment.html
```

Example output:
```
max alignment: 16
malloc:        0x501670
malloc:        0xd01678
```

test-alignment.cpp:
```cpp
#include <cstddef>
#include <malloc.h>
#include <stdio.h>

int main()
{
    printf("max alignment: %d\n", alignof(std::max_align_t));
    printf("malloc:        %p\n", malloc(0x800000));
    printf("malloc:        %p\n", malloc(16));
}
```

**Comment by kripken** [comment]
For comparison, the asm.js backend reports a max alignment of `8`. But we do intend the stack to be 16-byte aligned, so perhaps we should fix everything in both backends and malloc to be 16? I think @sunfishcode said that would be useful for future SIMD.

**Comment by tbfleming** [comment]
Is there a downside to moving everything to 16?

**Comment by kripken** [comment]
Probably not much. I think all that's missing is to modify dlmalloc. It might waste a little space on small mallocs.

**Comment by dschuff** [comment]
`max_align_t` is defined as having the max alignment of any scalar type, so not SIMD. So I think it should have align 8, not 16 (i.e. we should change it). The stack alignment is separate though; I do think it should stay aligned at 16.

**Comment by sunfishcode** [comment]
@dschuff The standard's wording is "the greatest alignment supported by the implementation in
all contexts", which I interpret to include any SIMD types present, and __int128 (which clang also supports). I favor aligning malloc at 16.

**Comment by dschuff** [comment]
§ 18.2 says "The type max_align_t is a POD type whose alignment requirement is at least as great as that of every scalar type". The text you quote is from § 3.11 where it defines a fundamental alignment. But you are right about __int128, and I don't really object to making malloc align at 16. Especially if it only applies to allocations of size 16 or more.

**Comment by sunfishcode** [comment]
Oh, you're right about `max_align_t`. I was too hasty in my reading of the spec. And yeah, aligning to 16 bytes only for allocations of size 16 or more sounds good to me.

**Comment by juj** [comment]
Running in non-wasm backend either with asm.js or wasm indeed gives 8:

```
max alignment: 8
malloc:        0x5012e8
malloc:        0xd012f0
```

which is because `max_align_t` comes from

```
/Users/juj/emsdk/emscripten/incoming/system/include/libcxx/cstddef:
   51: #if defined(__CLANG_MAX_ALIGN_T_DEFINED) || defined(_GCC_MAX_ALIGN_T)
   52: // Re-use the compiler's <stddef.h> max_align_t where possible.
   53: using ::max_align_t;
   55: typedef long double max_align_t;

/Users/juj/emsdk/emscripten/incoming/system/include/libcxx/stddef.h:
   55: // Re-use the compiler's <stddef.h> max_align_t where possible.
   56: #if !defined(__CLANG_MAX_ALIGN_T_DEFINED) && !defined(_GCC_MAX_ALIGN_T)
   57: typedef long double max_align_t;
```

and in fastcomp, `sizeof(long double)=8` and hence `alignof(long double)=8`.

I presume in wasm backend `long double` is 128-bit? Does it get software 128-bit arithmetic ops code embedded in it if one does `long double` operations?

**Comment by dschuff** [comment]
Long double in wasm backend is 128 bit (with all software-emulated ops), although I think we'd more or less decided to go back to just making it the same as double to line up the ABIs and because it wasn't worth the trouble (and caused complications with some parts of musl). Interesting that it's long double though; I guess clang's interpretation of § 18.2 is that "every scalar type" only includes the standard types and not __int128.
Assuming we do get SIMD in wasm though, it probably makes sense for malloc to align suitably for those types anyway, since the wasm design has the nice weasel-y warning that unaligned accesses might be really super slow.
