### ISSUE TITLE
failed to asynchronously prepare wasm: CompileError: wasm validation error: at offset 0: failed to match magic number

### ISSUE THREAD

**Issue by DavisOwen** [emscripten-core/emscripten#6048]
I am getting this error

 `failed to asynchronously prepare wasm: CompileError: wasm validation error: at offset 0: failed to match magic number`

when running this code test.cpp

int main() {
return 10;
}

(yes simple because I'm trying to debug)

compiled via 

`emcc test.cpp -O3 -o test.js -s WASM=1 -Wall -s MODULARIZE=1 -s ASSERTIONS=1`

Then loaded into javascript via

`import Module from 'test.js';
module = Module({wasmBinary: 'test.wasm'});`

which causes the error. Anyone have any leads to what this 'magic number' offset 0 error means?

**Comment by kripken** [comment]
The magic number is `\0asm` (in 4 bytes) which identifies the binary as a wasm binary. I think the issue here is that `wasmBinary` needs to be the actual binary, not the filename.

If you need to customize the filename at runtime, you can use [locateFile](https://kripken.github.io/emscripten-site/docs/api_reference/module.html#Module.locateFile). Or you could use the node.js API to load the binary.

**Comment by kripken** [comment]
(Did our docs say otherwise somewhere? If so we should fix that)

**Comment by motin** [comment]
Info for others that ended up here via a google search: For me this was due to a typo in the path to the .wasm file. The error occurred because the emscripten glue code found a 404 page instead of the .wasm file. Obviously the 404 page won't have the magic number :), but the error message is not so obvious...
