### ISSUE TITLE
getting started docs mention installing node, which already comes with emsdk

### ISSUE THREAD

**Issue by froydnj** [emscripten-core/emscripten#6093]
I followed the [download and installation instructions](https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#download-and-install), which mention doing a bunch of `emsdk` invocations, and then installing packages specific to your OS.  One of those packages is node...but it looks like the version of the SDK I downloaded (1.37.28) already includes node.

Are the docs out-of-date on this point?  I'm happy to fix them if so.

**Comment by kripken** [comment]
I am not sure if the emsdk always includes node. @juj, does it do that just with binary builds?

**Comment by juj** [comment]
Good observation - initially we only included node.js on Windows and not on macOS or Linux, but at some point started shipping node.js on all platforms to make sure we have the identical version to supply for each platform. Dropping the necessity to install node.js on macOS and Linux definitely sounds good, though there is a question for exotic linuxes that I'm not sure if the bundled node.js will be functional to run (due to possible dynamic library .so incompatibilities?)

Node.js is a distinct package in emsdk, and it's included when installing a full sdk bundle, be it from source or from prebuilt tag. It is possible to use emsdk prebuilt versions wihtout installing node.js, but that requires manually specifying the individual desired packages instead of specifying a full sdk bundle.

**Comment by froydnj** [comment]
I think if you're not taking explicit steps to build the binary packages to ensure the broadest compatibility (e.g. building in a chroot or VM that uses an older distribution and therefore an older glibc/libstdc++/etc.), then you're probably leaving exotic Linux distributions out in the cold anyway.  I don't know details of how the binary packages are being built; is that sort of step happening?

@juj, I think you're saying that dropping the node.js installation is fine, is that correct?   I'm unsure of what to do about exotic Linuxes.  My tendencies are to let them deal with their own problems--since they are doing exotic things already, one more thing doesn't matter much--unless supporting them by default involves minimal cost.  Having a section in the docs that most people aren't going to need doesn't sound like minimal cost.
