### ISSUE TITLE
Shrinking GL bookkeeping arrays and counter on resource deallocation

### ISSUE THREAD

**Issue by jlmatchlock** [emscripten-core/emscripten#6118]
Hello,

emscripten currently keeps track of various GL resource allocations through the GL.counter variable shared across several arrays and maps (such as GL.buffers, GL.textures, GL.uniforms, GL.shaders, GL.programs etc) but doesn't seem to shrink those arrays nor reset the GL.counter variable.

Over the course of several hours (in games for example), the counter and those arrays can grow very quickly (even though most entries would be null if properly deallocating resources when no longer used)

I was thinking, would it be possible to add a cleanup function that would shrink the arrays and the associated counter, possibly called at certain intervals (or called by the user) ?

Something along the lines of (forgive the fomatting and javascript code possibly not efficient)

```
function EmscriptenFindLastNonNullElement(array)
{
    for (var i = array.length - 1; i >= 0; i--)
    {
        if (array[i] !== undefined && array[i] !== null)
            return i;
    }
}

function EmscriptenShrinkIdTables()
{
    var highestFoundId = 0;
    var result;

    highestFoundId = (result = EmscriptenFindLastNonNullElement(GL.contexts)) > highestFoundId ? result : highestFoundId;
    highestFoundId = (result = EmscriptenFindLastNonNullElement(GL.buffers)) > highestFoundId ? result : highestFoundId;
    highestFoundId = (result = EmscriptenFindLastNonNullElement(GL.uniforms)) > highestFoundId ? result : highestFoundId;
    highestFoundId = (result = EmscriptenFindLastNonNullElement(GL.shaders)) > highestFoundId ? result : highestFoundId;
    highestFoundId = (result = EmscriptenFindLastNonNullElement(GL.programs)) > highestFoundId ? result : highestFoundId;
    highestFoundId = (result = EmscriptenFindLastNonNullElement(GL.textures)) > highestFoundId ? result : highestFoundId;
    
    GL.counter = highestFoundId+1;
    GL.contexts.length = highestFoundId+1;
    GL.buffers.length = highestFoundId+1;
    GL.uniforms.length = highestFoundId+1;
    GL.shaders.length = highestFoundId+1;
    GL.programs.length = highestFoundId+1;
    GL.textures.length = highestFoundId+1;
}

```

There's also the special case of GL.programInfos and its uniforms map: for each associated program there are possibly dozen of uniforms, which can grow very quickly as well.
Currently, calling glDeleteProgram() will null the entries but the references into GL.uniforms remain.
A modification to glDeleteProgram would make sure each uniform associated with a program to be deleted will be properly null'ed as well before removing the entry completely
```
      for (var key in GL.programInfos[id].uniforms) {
        var uniformId = GL.programInfos[id].uniforms[key][1];
        GL.uniforms[uniformId] = null;
      }

      delete GL.programInfos[id];
```

Please let me know if this is something you can consider adding.

**Comment by kripken** [comment]
Yeah, I've wondered if this could become an issue eventually. Is your game creating new uniforms on each frame, though - no way to reuse them?

Anyhow, it would be good to fix this. I think adding a "free list" might be a good way, that is, whenever something is destroyed, we null the place in the array, and in another array on the side we push that index. When we need a new index, we check if there are free indexes for use to use, and we use one of them first.

**Comment by jlmatchlock** [comment]
Our middleware is reusing the uniforms but while I was debugging I stumbled upon GL.uniforms that did not seem cleared and I've wondered if it could grow very quickly (particularly with program-generated shaders) between each load/unload of assets. Our tests only used a handful of shaders so it was not actually an issue.

A free list indeed sounds a much better idea.
However, does it mean each array will need its own free list (while GL.counter is still shared) ?

**Comment by kripken** [comment]
If the ids are globally unique, which I guess they are since GL.counter is used for all of them, then a single free list should be enough.

**Comment by juj** [comment]
Wasm has been designing towards a concept of object tables that could be passed as handles into Wasm. I think if we are to do some fixes to GL here, it would be great to implement on the JS side a global object table and utilize that one array to contain all kinds of objects, and we could then eventually migrate to OpenAL and others also sharing the same. Then eventually when Wasm gets object tables, this polyfill-like implementation could possibly be substituted with the real thing in Wasm, allowing all those JS objects to be directly referenced in Wasm side.

The same problem of empty slots arises in all other object tables as well, such as OpenAL, our JS SDL 1.4, etc. so having this one global object table (`JS.objects[]`?) that had this kind of compressed usage of reusing freed indices, would then solve the same memory problem as more of JS libraries migrate to using the same?

Btw, as per the OpenGL specification, there are some complications to immediately reusing freed object IDs for new objects, because of OpenGL semantics for marking certain objects for deletion, which means that in order to be safe, the kind of free object list would be best to be delayed a bit, so that

```c
{
   int t;
   glGenTextures(1, &t);
   glBindTexture(GL_TEXTURE2D, t);
   glDeleteTextures(1, &t);
   glGenTextures(1, &t);
}
```

will not generate the same ID twice. I think a good model would be to have each deleted ID put into the end of a free list (as a queue), and only when the size of the free list is e.g. > 1000, then an element from the front of that free list is returned, otherwise a new fresh one is allocated. This way immediately deleted IDs will not be right away reassigned to the next allocation, which could have an effect of masking bugs as well, if one deletes something but keeps referring to the old deleted ID, which all of a sudden is now referencing something new (vs referencing something that is known to be freed).

**Comment by juj** [comment]
See also #2500.
