### ISSUE TITLE
Use table from outside / remove dynCalls from wasm backend

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#6155]
The wasm backend output doesn't need dynCalls, if we can access the Table from outside. That would be more efficient and compact. (asm.js and asm2wasm can't do this, since asm.js has separate tables for each signature, and we'd need to know how that maps to the single wasm table - possible, but not trivial.)

When trying to do this I saw that the wasm backend's output doesn't export or import the table, so it isn't accessible from the outside. Is this intentional?

**Comment by kripken** [comment]
To be concrete on what the optimization here could be,
 * No need to emit dynCalls in the wasm.
 * In dynCall and invokes in JS, replace `Module['dynCall_..'](..)` with `Module['wasmTable'].get(..)(..)`.

**Comment by aheejin** [comment]
Doesn't that mean all functions that are callable from dynCalls need to be exported as well?

**Comment by kripken** [comment]
I don't think so, why? Do you mean they might be removed by DCE?

**Comment by dschuff** [comment]
Yeah, IIUC that should work. I think the dyncall support dates back to before the Table JS API was defined. Also, I thought we always imported tables in emscripten, regardless of whether we used the wasm backend or not?

**Comment by kripken** [comment]
asm2wasm imports it, but looks like the wasm backend doesn't, at least [not in s2wasm](https://github.com/WebAssembly/binaryen/blob/master/test/dot_s/indirect-import.wast#L14).

**Comment by dschuff** [comment]
OK, interesting. In the JS we create the table unconditionally but I guess it just gets ignored at instantiation. That could be confusing, we probably shouldn't do that if we arent going to import the table. But I like your idea, so let's just import the table :D

**Comment by kripken** [comment]
I think importing is reasonable too. However, a downside is that it means anything in the table is a root for dce (not that it's easy to remove something even when the table is private, but at least it's possible in theory...). Just want to make sure we consider all angles here.

**Comment by dschuff** [comment]
How is it possible to remove an address-taken function? I guess you could prove that there are no indirect calls with a particular signature, and then remove all the functions with that signature. But beyond that, I don't think you can?

**Comment by kripken** [comment]
Yeah, exactly, you can do it by signature. Not easy/common probably... still, we'd lose that option.

**Comment by kripken** [comment]
This came up in the context of VM optimizations with @lukewagner , where it might be better to not export or import the table (since it can see functions in the table can't be called from outside, so generating support for that is not necessary). I actually misremembered this issue, the situation is actually that the wasm backend path already doesn't import or export the table. Unless that has changed in lld, where @sunfishcode says is where this would now be determined?

Overall, the tradeoffs here seem to be:

 * If the table is accessible on the outside, then we don't need to emit `dynCall` stubs in the wasm, making it slightly smaller (order of the number of indirect call types), and also we can call from JS into the table in a direct way instead of calling into `dynCall` with the function pointer and params.
 * If the table is not accessible on the outside, then wasm VMs may have less work to do (order of the number of functions in the table, perhaps), and also binaryen may be able to do slightly more dce (based on indirect call type, likely pretty minor).

I'd guess since there are many more functions in the table than types that the latter is better, but it's hard to say. Given it's what the wasm backend/lld already do, might make sense to just keep it that way.

**Comment by NWilson** [comment]
Aha, thanks for linking my binaryen issue (https://github.com/WebAssembly/binaryen/issues/1466), I hadn't seen this.

As regards DCE, I don't see how it makes muchdifference? Neither browsers nor binaryen are able to do much DCE on address-taken functions: if you export a dynCall trampoline, then in principle any function with matching signature could be called. And for every function in the Wasm table, there's going to be a `call_indirect` somewhere in the code with a matching type! I might be missing something, but it would require very fancy data-flow flow analysis to work out that certain functions in the table are not callable. (Remember LLD does Garbage Collection of totally unused code - maybe it didn't though at the time this was originally discussed.)

What would make sense is if browsers were able to optimise the function table if they can deduce that it's const (never changed). Is there any evidence however that they actually do that?

My preference would be using the available facilities in WebAssembly.Table, and prod the browser vendors to look into any performance issues that are discovered. It oughtn't to be the case that that interface is unused because of VM inefficiencies, or else it was a mistake to put it in the spec!

**Comment by NWilson** [comment]
Regarding "VM optimisations" - I've done a benchmark to try and work that one out.

### Benchmark one

Wasm file that does `call_indirect` in a loop. The function pointer is passed in via JS to prevent the engine flattening to a simple `call` during compilation.

Test code:
```
int ret42() { return 42; }

typedef int (*i32Fn)();

i32Fn __attribute__((visibility("default"))) getRet42() { return ret42; }

int __attribute__((visibility("default"))) callI32(i32Fn f) {
  int rv = 0;
  for (int i = 0; i < 1000000; ++i)
    rv += f();
  return rv;
}
```

Test JavaScript:

```
  const ptr = inst.exports.getRet42();
  console.log("Calling now...");
  const perf = window.performance;
  const before = perf.now();
  inst.exports.callI32(ptr);
  const after = perf.now();
  console.log("done, time=" + (after - before));
```

Regardless of whether the module exports the table, I get 3.15ms to do 1,000,000 loops in Chrome, and 3.44ms in Firefox (12 cycles per loop average), averaged over many runs - although the score is consistently in between 3 and 3.9ms. There was no difference between the case where the Wasm table is exported and not.

That suggests that VMs do _not_ care about whether the table is exported. Ordinary Wasm-to-Wasm indirect calls don't get a faster path based on whether the table is modifiable from JavaScript.

### Benchmark two

Test code calls from JS into Wasm, to see if fetching from the table imposes a significant cost.

Chrome: 0.103us per switch to Wasm, Firefox 0.152 per switch. That's just doing `instance.exports.getRet42()` in a loop to see what the cost of the JS-to-Wasm transition is. Obviously, no difference in cost with/without exported table (since not using the table at all).

Then - calling a function pointer via the Table.get API. Chrome: 0.30us per combined call to `table.get(ptr)()` which fetches the cached JS function object and invokes it. Firefox: 0.23us per call.

Then - calling a function pointer via a dynCall stub. I must be doing something really wrong here... but it's taking 8ms (!!!) per call via dynCall. I've tried calling it in various different ways, it's just astonishingly slow, again regardless of whether the table is exported or not. Is there some horrendously slow that happens when switching from JS to Wasm when there are function arguments!?

**Comment by kripken** [comment]
Sorry for not going into more detail before, the VM optimization issues that I am aware of are mostly not to do with speed, but with memory: when the table is exported, the functions might be called from JS, so the VM needs to emit support thunks for them. When there are a great many functions in the table, those thunks can add up, I am told. @lukewagner can perhaps elaborate.

**Comment by NWilson** [comment]
Aha, I see! Thanks, I hadn't really thought of the memory angle. The spec mentions the caching behaviour of `Table.get()` (namely that it returns the exact same function object every time for a given index). I suppose it would be possible to build the thunks lazily, rather than create the JS objects in the table up-front. So I can see why you're thinking the dynCall thunks (one per type) might be less overhead. The browsers should be able to do per-type thunks as well though, so when the implementations are more mature might it break even?

**Comment by lukewagner** [comment]
The entry stubs for table functions are [now generated lazily in FF](https://bugzilla.mozilla.org/show_bug.cgi?id=1422043) so there should be no concern on that angle, at least for FF.

The only issue I'm aware of is that indirect calls are faster when they may possibly contain elements from another instance (which we conservatively assume to be the case when a table is imported, exported, or initialized with imported functions).  If you're not able to observe that in practice, then using an exported table's `Table.get(i)()` instead of `dynCall` seems cleaner and could reduce boilerplate size.  (Also, one day, I'd like to do [an optimization](https://bugzilla.mozilla.org/show_bug.cgi?id=1340235#c12) so that there is only overhead if the table *dynamically* contains multiple instances.)

**Comment by NWilson** [comment]
Presumably that's "slower if they may contain functions from another instance".

Thanks for the information!

**Comment by lukewagner** [comment]
Hah, right.

**Comment by dschuff** [comment]
If the options are 
1) Use a private table, and generate an extra stub per signature in wasm (current option), a small extra size cost and an extra complexity cost in the toolchain.
2) Import the table, populating it partially from JS and partly from wasm initializers. `Module['dyncall_v'](index)` would become `Module['table'].get(index)()` or some such. That would be simpler, although initialization would be more complex (I imagine it would end up being similar to how we handle memory). 

Maybe as an optimization we could make dyncall-ability optional; currently the stubs are just always generated for every function in the table, but maybe the user knows they will never call them from JS. We could do this either way, actually, although I'm guessing metaDCE is already powerful enough to remove the dynCall stubs that we have today.

More generally, wasm has a feature (imported/exported tables) that is exactly intended for this use case. It does seem a little silly to make toolchains do some kind of workaround just to avoid using it. It sort of makes more sense to keep things as simple as possible (and of course avoid using features we don't need) and let JS engines optimize the features that are there.

**Comment by kripken** [comment]
> I'm guessing metaDCE is already powerful enough to remove the dynCall stubs that we have today.

Correct.

**Comment by NWilson** [comment]
What about option 3: Export the table? You suggested importing it, to allow it to be populated partially from JS and partially from wasm initializers. However since it's currently private, changing it to be an export should also work, since you're not losing any capability that was? For Emscripten an import is however more flexible, just curious why an export was ruled out.

**Comment by dschuff** [comment]
It's not ruled out, I'm just considering equivalent to importing from the perspective of potential extra cost. Given that, it would probably be simpler in the emscripten code to import, because you can do the setup before you instantiate the module (this is what we do for memory, and the code would probably be in the same place). Other than that you're right, it would work.

**Comment by brion** [comment]
Just to make sure I understand the current state of this -- as of 1.37.39 in wasm I'm seeing that using a function pointer as an index to `Module['wasmTable'].get()` gives me the wrong function.

Function pointers for each signature have to be added to a signature-specific constant offset to get the actual index into the table, which is what the `dynCall_*` invokers do (or inlined with call_indirect invocations in the wasm code).

Is the proposal to remove these offsets, so there's a single pointer namespace for all signatures? This would also allow for adding arbitrarily many runtime functions without reserving function pointer space, and would avoid pointer aliasing across signatures.

**Comment by kripken** [comment]
Yeah, it's confusing, sorry about that. You can force a single table with `EMULATED_FUNCTION_POINTERS`, and that is also what the wasm backend does anyhow.
