### ISSUE TITLE
Avoid startup exceptions creating default directories and devices

### ISSUE THREAD

**Issue by shooshx** [emscripten-core/emscripten#6343]
When I need to debug something in the startup of the page, in chrome I'm setting the "Pause on caught exceptions" checkbox to be checked.  Then, when reloading the page, I get stopped in about 8-9 exceptions inside `createDefaultDirectories()` and `createDefaultDevices()` when its trying to create directories that don't exist. This is rather annoying and it makes my debugging cycle that much slower.  
Since I don't really care for these directories, is there a way to just disable their creation somehow?  
I do need `FS` to be present since I am reading and writing files at some point.  
As far as I can tell, `staticInit()` is called from the top level of my compiled js, so there's nowhere I can monkey patch these functions to do nothing.

**Comment by kripken** [comment]
What's the specific exception thrown? Maybe you're seeing a bug we need to fix.

If it's not a bug, then in general there isn't a mechanism to not create those defaults, but I'd be ok with adding one (something like `ADD_POSIX_DIRS` maybe, defaulted to on).

**Comment by shooshx** [comment]
The exception is `ErrnoError` with `ENOENT`
it's thrown in `lookup:function (parent, name)` and is caught in `mayCreate:function (dir, name)`
The stack looks like
```lookup
lookup
lookupNode
mayCreate
mknod
mkdir
createDefaultDirectories
staticInit
```

Maybe there's a way for this startup procedure that happens every page load to not throw an exception?

An old Technion professor in a C++ course used to say that exceptions should be reserved for exceptional circumstances...

**Comment by kripken** [comment]
Ah, that sounds familiar. Yes, I think in some places the FS code uses exceptions to check if things exist. I agree with you that that should be done differently.

**Comment by kg** [comment]
Has any thought gone into how this might be cleaned up at some point in the future? Would a PR to clean it up be welcome?
At present any time we debug an emscripten-based application we have to find a magical spot to set a breakpoint, disable uncaught exceptions in the debugger, hit f5, then enable uncaught exceptions once we reach that magical spot. Then we have to hope we don't get more ErrnoError spam during application execution caused by I/O. It's simply not realistic to step through the hundreds of spurious caught ErrnoErrors you get during startup of a real app.

It feels like it would be ideal if the FS stuff didn't rely on throwing tons of Errors during normal execution for both performance and debugging UX, but I don't know the emscripten codebase well enough to know if it's even possible to fix this without breaking back-compat.

**Comment by kripken** [comment]
@kg In general the plan here is to replace the JS FS with [WasmFS](https://emscripten.org/docs/api_reference/Filesystem-API.html#new-file-system-wasmfs). That is implemented in C++, so no JS exceptions happen there at all.

WasmFS is already usable now, perhaps you can switch to it?
