### ISSUE TITLE
Pthreads and OpenGL shaders

### ISSUE THREAD

**Issue by lecopivo** [emscripten-core/emscripten#6372]
I'm having troubles with OpenGL shaders when I compile my application with `-s USE_PTHREADS=1` flag. It appears that during the shader compilation the shaders are empty.

I'm using the [Magnum engine](https://github.com/mosra/magnum) and I'm trying to build the [triangle example](http://magnum.graphics/showcase/triangle/) with `-s USE_PTHREADS=1` flag but it does not work.

Examples build for WASM(Asm.js behaves the same way):
The [triangle example without `-s USE_PTHREADS=1`](http://pub.ist.ac.at/~tskrivan/triangle-no-pthreads/magnum-triangle.html), this should run for you.

The [triangle example with  `-s USE_PTHREADS=1`](http://pub.ist.ac.at/~tskrivan/triangle-with-pthreads/magnum-triangle.html), this does not work for me. The error:
```
Shader::compile(): compilation of vertex shader 1 failed with the following message:
ERROR: 0:? : '' : syntax error
```
Indicates that the shader is empty. The weird thing is that there is no threading in the application. The only difference is in the presence of the flag.

Just to test that I can compile and run code with `-s USE_PTHREADS=1` I have created a small testing [application](http://pub.ist.ac.at/~tskrivan/pthreads-test/main.html). Which runs fine on Firefox Nightly.

To produce these tests I have used the `incoming` branch of emscripten.

**Comment by kripken** [comment]
Is this with very latest incoming? @dschuff fixed a pthreads bug quite recently (but that may have been wasm-only).

If that's not it, it could be a bug in compiling with pthreads, which is less tested. Might be no other option than to just debug this to see where things go wrong (see if that shader is indeed empty and why etc.). Might help to build with `ASSERTIONS` and `SAFE_HEAP`, those may find something.

**Comment by mosra** [comment]
Hi, I tracked the issue down to the `Pointer_stringify()` function implementation that's used for workers: https://github.com/kripken/emscripten/blob/7f89560101843198787530731f40a65288f6f15f/src/fetch-worker.js#L54-L58 (see the issue in the magnum repo linked above for further details).

The problem is that this function returns an empty string if it encounters any UTF-8 character. This then results in empty string being passed to the GL shader compiler. For now I worked around this by patching all shader sources to not contain any UTF-8 characters (such as e.g. `©` in license headers), but that's far from an ideal solution :)

I was not able to discover why this is a problem when passing strings to GL and not when reading the memory directly through `char*`.

**Comment by kripken** [comment]
Good find!

Yeah, that code looks like we should fix it. I think a good plan would be to move `Pointer_stringify` (and anything else needed there) to a separate file (could be `src/support.js`, but might need some more refactoring for that). Then to remove the hackish stuff and replace it with an `#include` of that separate file (like there is an include for `Fetch.js` already).
