### ISSUE TITLE
Implement DEAD_FUNCTIONS for compiled code (tell the compiler to remove certain functions you are sure will not be run)

### ISSUE THREAD

**Issue by cpitclaudel** [emscripten-core/emscripten#6379]
Hi there,

One thing I've noticed when compiling large projects is that dead code elimination tends to have a fairly hard time knowing statically what can and cannot run.

Take Z3 (a SAT/SMT solver) as an example: it has support for multiple input languages, multiple types of problems, extended logging and debugging options, etc.  A full build takes 17MB, roughly, at -O3.

I only need it with a single input language, a single type of problem, and no logging.  I build my emscripten application by wrapping a tiny subset of Z3's API in C, and exporting only that — but even from this tiny API it's very hard for the dead code eliminator to realize that most of the Z3 code won't be called. For example, if my small wrapper only calls `init_solver("smt2")`, the dead-code eliminator will mark init_solver as used, and it'll pull all functions called by init_solver (essentially all solvers), instead of just the one I want.

Is there a way to tell the dead-code eliminator to remove a function (and its dependencies), even if it looks like it may be called?  Is there a way to make it print a list of all included functions, and why each of them are included?

Thanks!

**Comment by kripken** [comment]
There isn't currently a method to do this. We used to have the `DEAD_FUNCTIONS` option, but it wasn't that useful in practice. Overall, the recommendation is to refactor the codebase to allow regular dce to work.

**But**, yeah, there are cases where that's not enough, like
 * An existing project you're porting, that you can't do a major refactor of (upstream might not want it).
 * Code using indirect calls or other things that defeat dce.

So perhaps we should bring back an option to do this? Implementing it for wasm would be pretty easy. Thoughts?

Btw, for the Z3 case, it's possible that LTO can optimize `init_solver("smt2")` so it sees only smt2 is needed. How does `--llvm-lto 1` work?

**Comment by kripken** [comment]
Thanks - yeah, lto is hard to rely on, and often it increases code size instead...

I'll rename this issue to focus on the DEAD_FUNCTIONS feature, I think it would be nice to have that if someone's interested to implement it.

**Comment by caiiiycuk** [comment]
I'am very interested in this feature.
My case: ```An existing project you're porting, that you can't do a major refactor of (upstream might not want it).```

 I think about 2 options:
1) Much more aggressive dce that counts only direct calls + white list for functions
or
2) list of dead functions that should be simply removed

I like **first option** because you not need any statistic to remove dead functions. You will use it from start, and add required function in white list one by one. Like we do when work with proguard on android. I don't know how many functions this dce will found, because as I imagine it will not work for code like this:
```
void runsome(std::string name) {
   if (name == "A") {
        A();
   } else if // tons of functions
}
```
I think this is not hard to implement as llvm pass.

For **second option** (from mailing list):
 * To do it in LLVM IR, the pass itself would be pretty easy, but you'd need to maintain a fork of LLVM (unless you get them to accept it upstream).
 * Doing it on asm.js should be easy,  we can add a js optimizer pass for that.
 * Doing it on wasm should also be easy, we can add a binaryen pass for that.

Recently I tried to do dead function removal on asm.js file (that produced by emcc), and it was hard. Actually remove functions is easy operation, but make asm.js valid again is very hard (or I miss something).

@kripken I don't agree about ```but you'd need to maintain a fork of LLVM```. As I understand how clang/llvm works, we can write LLVM IR pass as standalone pass based on clang/llvm api. We can use it with ```opt -load dce.so```. I imagine that we can extend emcc to allow users to run their custom passes through build command, like this:
```emcc a.o b.o c.o --custom-llvm-passes="['dead_functions_pass', '...']" -o asm.js```

I think it can be very useful, cause for example I have pass to extract all symbol constants from sources. Currently to run it I should hack build system.

**Comment by caiiiycuk** [comment]
In meanwhile I share this code to function elimination, maybe it will be useful for someone else. You should compile it as llvm pass, and use with opt on emitted bc.
```c++
#include <llvm/Pass.h>
#include <llvm/IR/Function.h>
#include <llvm/IR/Module.h>
#include <llvm/Support/raw_ostream.h>
#include <llvm/IR/Instructions.h>

using namespace llvm;

namespace {

    struct FcePass : public ModulePass {
        static char ID;

        FcePass() : ModulePass(ID) {
        }

        bool runOnModule(Module &M) override {
            bool changed = false;

            for (Function &F: M) {
                if (strstr(F.getName().data(), "Png") != NULL) { // use your matchers
                    F.getBasicBlockList().clear();
                    BasicBlock *block = BasicBlock::Create(F.getContext(), "entry", &F);
                    block->getInstList().push_back(new UnreachableInst(F.getContext()));
                    changed = true;
                }
            }

            return changed;
        }
    };

}

char FcePass::ID = 0;
static RegisterPass<FcePass> X("fce", "function code elimination",
                                  false /* Only looks at CFG */,
                                  false /* Analysis Pass */);

```
