### ISSUE TITLE
Multiple inheritance with EMSCRIPTEN_BINDINGS

### ISSUE THREAD

**Issue by flatmax** [emscripten-core/emscripten#6382]
Hi there,

I am trying to do declare multiple inheritance in the EMSCRIPTEN_BINDINGS but can't get the syntax right - is it supported ?

It attempts something like so :
`emscripten::class_<Test, emscripten::base<Base1>, emscripten::base<Base2>>("Test") // this doesn't work
`

The file of interest is here :
https://github.com/madChopsCoderAu/WASM/blob/multipleInheritance/src/Test.C

The header file with class definitions is here :
https://github.com/madChopsCoderAu/WASM/blob/multipleInheritance/include/Test.H

The repo which fails is here (multipleInheritance branch) :
https://github.com/madChopsCoderAu/WASM/tree/multipleInheritance

**Comment by JasonHuang3D** [comment]
This won't work, since  js or any es standard scripting languages using single inheritance chain. As you may noticed in TS, that it only has"interfaces" as the feature of "multiple inheritance", in fact those interfaces are faked in js level( store a string symbol as an Identifier, and when you need to check or cast type, you need to use a custom function to achieve this). 

For embind, it used a "wrapper" to simulating the behavior of real inheritance relations inside of c++, e.g. if you need to expose a class that can be extended in js side, then embind extends that class in c++ side first, so any js object created from that wrapper object will have a pointer that has already has inherited from c++ side.  All above only make sense if all js object follows the rule of "single inheritance chain".

However good news  for embind, I have achieved optional parameter( function parameters with default values), using additional function table and store those values on init phase of all bindings, I simulated the same theory of what c++ compiler dose over c compiler.  Also I have achieved full inheritance tool chain for any scripting language that can be compiled to js( currently as3(customized falcon compiler) and ts ), including getter setter, function overriding, (can be called from c++ ).   the repo is :https://github.com/JasonHuang3D/AJC-Flash-WebAssembly-Examples.  we have achieved 50% of flash api so far, but only put 20% on that repo, hopefully will arrange a big release this month. 

I will make a pull request for what I did for embind. Hopefully @kripken will do a merge on it:)

**Comment by devshgraphicsprogramming** [comment]
What about making
```cpp
template<typename BaseClass>
struct base {
```

 a variadic to support multiple inheritance?
