### ISSUE TITLE
200 MB disk space wasted by toolchain: clang symlinks lost in archives

### ISSUE THREAD

**Issue by primiano** [emscripten-core/emscripten#6607]
Today I was investigating why the emscripten-llvm toolchain is so big (900 MB) from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/osx_64bit/emscripten-llvm-e1.38.4.tar.gz, which is causing some problems in travis.

Turns out the clang binary is repeated 5 times in the archive:
$ shasum clang{++,-cpp,-cl,-6.0,}
6515bda74b90eafb562d249611d63394f11ce6b0  clang++
6515bda74b90eafb562d249611d63394f11ce6b0  clang-cpp
6515bda74b90eafb562d249611d63394f11ce6b0  clang-cl
6515bda74b90eafb562d249611d63394f11ce6b0  clang-6.0
6515bda74b90eafb562d249611d63394f11ce6b0  clang

In any other distributions (e.g., chromium) there is only one clang binary and the others are symlinks.

**Comment by kripken** [comment]
Oh wow, thanks @primiano for noticing this and figuring it out! We really need to fix this.

I think the code creating those downloads is somewhere in https://github.com/juj/emslave/blob/master/bin/deploy_emscripten_llvm.py

**Comment by dschuff** [comment]
I'm guessing that the script copies the binaries with python code, rather than letting CMake install things into the right place. In the waterfall builder we do that, and also explicitly symlink to make extra copies where possible (e.g. https://github.com/WebAssembly/waterfall/blob/master/src/build.py#L937) but unfortunately this is still a problem on Windows.

**Comment by kripken** [comment]
We are now using the new builders, which don't have this issue.
