### ISSUE TITLE
Local static variables may collide with dynamic allocated memory on the heap

### ISSUE THREAD

**Issue by Miguel0888** [emscripten-core/emscripten#6667]
I figured out that local static variables may colide with some callees if they allocate memory dynamically on the heap. As you can see in the picture below, my (local) static stackpointer was overwritten as the dynamic allocated memory was initialized with zero. You see that the addresses overlap and the sp has changed its value, which was a fault. As I defined the Stackpointer as global variable the error was gone, so that this workaround should work. I have also attached the code snipped where the error was caused. How is that possible? I am sure my programm is not faulty but I am sorry I can't share it, it's not mine.
![2018-06-08 21](https://user-images.githubusercontent.com/40050873/41139572-be8e21a4-6ae8-11e8-94ea-9b4d253efd2d.png)
![2018-06-08 22](https://user-images.githubusercontent.com/40050873/41139579-c3b5a81e-6ae8-11e8-92a6-4cbe7bd5cda1.png)

**Comment by kripken** [comment]
Are you running a C compiler here, or running code generated from it?

In general for emscripten output, it's possible there is memory corruption or some other problem going on. Building with `-s SAFE_HEAP=1 -s ASSERTIONS=1` may help find the issue. However, if the issue is in code generated from your C compiler, the issue might be how you set up the stack etc.
