### ISSUE TITLE
How to reduce the size of the generated file

### ISSUE THREAD

**Issue by lokpoi888** [emscripten-core/emscripten#6965]
The size of the generated file is  21Mb in my project. after I use --llvm-lto -Oz -s ELIMINATE_DUPLICATE_FUNCTIONS=1.
I don't know if there are any other ways to reduce the size？Will the unused methods or classes be exported to the js file? How to remove them? Any suggestions for writing c++ code?

**Comment by kripken** [comment]
In general unused methods etc. will be removed, if the LLVM optimizer can do that. It actually can't remove indirect call targets, global constructors, etc., in the general case. So simple direct calls will be dce'd when obviously not in use, but complex stuff is best to avoid linking in.

Some general code size tips here: https://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html#code-size

Also @floooh has some great posts about writing compact c++, like this: http://floooh.github.io/2016/08/27/asmjs-diet.html

**Comment by floooh** [comment]
Also worth mentioning: Bloaty McBloatface (https://github.com/google/bloaty), this got direct WASM support since recently, and it's easy to use on the resulting wasm file (just add -g to your compile options to get basic debugging info, e.g. symbol names).

Running bloaty on a .wasm file with ```-d symbols``` gives you a sorted list of the biggest size contributors:

![image](https://user-images.githubusercontent.com/1699414/43857433-94d25c3e-9b4b-11e8-8fab-0a8f3e1914be.png)

**Comment by lokpoi888** [comment]
Thank u for your advice, I have another question now, I include <locale> in my project,  and I notice that all functions in <locale> has been exported to the generated JS file.  how can I remove the functions that I didn't use？

**Comment by kripken** [comment]
The optimizer should automatically remove functions that are not used, if you build with `-O1` or above. In `-O3` and `-Os` and above it will also remove unnecessary JS functions very effectively.

If you still see a function that you think should be removed, but wasn't, please provide a testcase, it could be a bug.
