### ISSUE TITLE
Is it possible to generate standalone wasm with exported memory/stack top?

### ISSUE THREAD

**Issue by d07RiV** [emscripten-core/emscripten#7058]
Using clang compiler, it is possible to get output similar to this:

    (module
      (type $t0 (func))
      (type $t1 (func (result i32)))
      (func $__wasm_call_ctors (type $t0))
      (func $main (export "main") (type $t1) (result i32)
        i32.const 42)
      (table $T0 1 1 anyfunc)
      (memory $memory (export "memory") 2)
      (global $g0 (mut i32) (i32.const 66560))
      (global $__heap_base (export "__heap_base") i32 (i32.const 66560))
      (global $__data_end (export "__data_end") i32 (i32.const 1024)))

The memory is exported (instead of imported), but more importantly it also exports `__heap_base`, which can be used for dynamic memory management on JS side.

However, building clang and libraries from sources is a massive pain, so I'm looking for a way to get a similar result with EMCC. Is it possible to achieve something similar, or am I stuck with parsing the generated `.js` to build a minimal environment?

**Comment by kripken** [comment]
There are some options for emitting standalone wasm with emcc, see https://github.com/kripken/emscripten/wiki/WebAssembly-Standalone

The second method (a dynamic library) will contain a "dylink" section which describes memory usage, see https://github.com/WebAssembly/tool-conventions/blob/master/DynamicLinking.md#the-dylink-section Note that dynamic linking adds some overhead, though, for keeping code relocatable.

Otherwise, for the first method (optimize out the runtime, when possible), we could make it emit metadata about the `__heap_base`, etc., I think that would not be too hard. Maybe a script to parse the `.js` could be enough.

**Comment by d07RiV** [comment]
Thanks, I found an older issue with the same discussion, and the conclusion was that side module is probably a bad idea unless a relocatable module is actually required. I did find definitions of STACKTOP et al, so that could be a good starting point.

I think it would be handy to have a standalone mode that lets WASM fully manage its memory and stack, though.
