### ISSUE TITLE
[libc] mmap fails with `TypeError: attempting to access detached ArrayBuffer`

### ISSUE THREAD

**Issue by kumpera** [emscripten-core/emscripten#7118]
If you try to MMAP_PRIVATE from the file system and the _malloc call trigger a heap expansion, it will fail with the above.

**Comment by kumpera** [comment]
It happens here: https://github.com/kripken/emscripten/blob/incoming/src/library_memfs.js#L359

The `buffer` argument HEAPU8 comes from here: https://github.com/kripken/emscripten/blob/ddfc3e32f653add658c1d730ac208757910eed7c/src/library_syscall.js#L929

If the `_malloc` call detaches the ArrayBuffer, mmap will bomb.

**Comment by kripken** [comment]
Thanks for reporting!

In general, mmap is not comprehensively tested, and memory growth has also not been heavily tested due to how it worked in the asm.js days, so I am not surprised we have a bug when combining them.

To fix this, we should probably add a notification mechanism for heap growth events, and then mmap would need to listen and handle things accordingly.
