### ISSUE TITLE
GL errors in Chrome CI

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#7145]
See e.g.

* https://circleci.com/gh/kripken/emscripten/39766?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
* https://circleci.com/gh/kripken/emscripten/39212?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

This doesn't happen all the time, but when it does it seems like the GL ones are failing, while non-GL ones (including simple non-GL canvas rendering) pass.

Setting `EMTEST_LACKS_GRAPHICS_HARDWARE` to skip those tests may be useful temporarily. Or, we can just agree to not worry about those results for now - the other browser CI results give decent coverage.

cc @sbc100

**Comment by sbc100** [comment]
I noticed that too :(

I think its because a new stable version of chrome shipped. 

Happy to set EMTEST_LACKS_GRAPHICS_HARDWARE=1 for now until we find another solution.

Perhaps we can configure this job to not be required for landing changes, but I'd like to be notified if/when any of them start failing.

**Comment by kripken** [comment]
Oh, it's not an intermittent issue then? Then I think setting `EMTEST_LACKS_GRAPHICS_HARDWARE` for now makes sense.

**Comment by sbc100** [comment]
This was re-enabled in #9009 so I guess its fixed!
