### ISSUE TITLE
WASM module fails to compile

### ISSUE THREAD

**Issue by pixelherodev** [emscripten-core/emscripten#7187]
I'm on the latest git commit, and i have a huge problem: `dlopen` fails to work when using WASM. Instead, there's an error message about how "Compilation of wasm over 4k is not allowed on main thread etc."

dlopen works fine on the non-wasm builds (asm.js IIRC), but fails on wasm builds. Is there a fix for this?

**Comment by kripken** [comment]
This issue is specific to chrome + wasm, as sync compilation is currently limited there.

One workaround is to use asm.js for now, which is a little slower but is just flipping a compiler flag. Alternatively, there is an async compilation API for shared libraries, see #6663, but you do need to refactor your code for it.

**Comment by pixelherodev** [comment]
I am currently using asm.js instead of wasm (at least I think so; I just use the `emsc-make-release` config for fips instead of `wasm-make-release`, but I'm fairly certain the emsc configs use asm.js), but the workaround simply won't for me - won't work around, that is. I'm using a dynamic plugin system which allows the user to specify the URL of a module to load, which doesn't work for preloading AFAICT.
