### ISSUE TITLE
wasm shared library preload-plugin loading just preloads, need to doc that people must load the lib later (and loadDynamicLibrary must look in preloaded libs)

### ISSUE THREAD

**Issue by waterlike86** [emscripten-core/emscripten#7220]
ref : https://github.com/kripken/emscripten/pull/6663
i have a function in a side module which i call during Module['onRuntimeInitialized'] called FOO which is exported from my side module using EMSCRIPTEN_KEEPALIVE

i used to be able to call Module \[\"\_FOO" ](), I seems that after this PR i am not longer able to find this function.
i found that while using --use-preload-plugins, handle was calling Module['loadWebAssemblyModule'] directly, but the code to import the symbols into the Module object was in loadDynamicLibrary, so we can never find the functions exported in the side modules

**Comment by kripken** [comment]
That PR should not have regressed any existing uses, so this is surprising. @mdboom, do you maybe have a guess?

Otherwise, @waterlike86, can you provide a testcase showing the issue?

**Comment by waterlike86** [comment]
@kripken @mdboom  sorry for the late reply

the output to this test is ->
Uncaught TypeError: Module._sidey is not a function
    at Object.Module.onRuntimeInitialized (test.js:1)
    at doRun (test.js:1)
    at test.js:1

[jscall_to_side.zip](https://github.com/kripken/emscripten/files/2459309/jscall_to_side.zip)

**Comment by kripken** [comment]
Ok, looking into this, there are some issues:

 * The testcase defines `preRun` in the pre-js. That shadows an emscripten local variable, which causes problems. Renaming it avoids that.
 * Using the preload plugin calls `loadWebAssemblyModule`. That is enough to preload it, so that `dlopen` can work synchronously later, but it does not fully link in the dynamic library. To do that, we must call `loadDynamicLibrary`. However, that doesn't look in the preloaded section, so we need to update it the same way dlopen is.

I'll rename the issue for that.
