### ISSUE TITLE
createPreloadedFile is extremely slow. (iOS 12)

### ISSUE THREAD

**Issue by leno72** [emscripten-core/emscripten#7320]
Hi. I'm new here:) I tested on iOS 12 Safari and createPreloadedFile is extremely slow. (.wav audio file)
https://github.com/kripken/emscripten/blob/20602efb955a7c6c20865a495932427e205651d2/src/library_browser.js#L222-L226

it seems `canplaythrough` is always not fired. So, I added `audio.load();`.  
```
audio.src = url; 
audio.load(); //here~~
 // workaround for chrome bug 124926 - we do not always get oncanplaythrough or onerror 
 Browser.safeSetTimeout(function() { 
   finish(audio); // try to use it even though it is not necessarily ready to play 
 }, 10000);
```

 Now, it works well. If this is a correct way, can you change it?

**Comment by kripken** [comment]
Thanks for checking. If I understand correctly, I think we should

1. Add a call to `load()` where you suggested.
2. Remove that 10 second chrome workaround - the chrome issue has been closed a while ago, and the workaround should no longer be needed.
3. We should document that users should initiate the app through a user click (so that the preloading code is reached from a user interaction and safari will load it).

Does that make sense? In particular, can you please verify that things work well even with the 2nd item (removing that 10 second workaround thing)?

**Comment by leno72** [comment]
Thanks for quick reply. It works without workaround. And the 3rd item is wrong, wherever `load()` is works and then `canplaythrough` will be fired. But, audio is never played even if `play()` is placed in loaded event of createPreloadedFile. users should be careful about play(). 

Summary, users can preload file on load, but can't play it without user interaction. I checked some cases with OpenAL.

**Comment by kripken** [comment]
Thanks, I see. Another question, is load() even needed - does it work without it? (I assume it would only do the load on the call to play(), so there might be a delay, but I'm curious if it works at all.)

**Comment by leno72** [comment]
Hi. I tried. It doesn't works but change code like this, 

```
audio.src = url; 
 // workaround for chrome bug 124926 - we do not always get oncanplaythrough or onerror 
// Browser.safeSetTimeout(function() {  
   finish(audio); // try to use it even though it is not necessarily ready to play 
// }, 10000);
```

It works. you need `finish(audio);`, because createPreloadedFile won't make the file available without finish function.
