### ISSUE TITLE
Advanced async functions support

### ISSUE THREAD

**Issue by FrancoisChastel** [emscripten-core/emscripten#7365]
Hello !

When trying to port with `emscripten` an existing project using threading.

I got the following errors :
```
error: undefined symbol: _longjmp
error: undefined symbol: _setjmp
error: undefined symbol: getcontext
error: undefined symbol: makecontext
error: undefined symbol: pthread_setaffinity_np
error: undefined symbol: setcontext
```

After reading along the [documentation](http://kripken.github.io/emscripten-site/docs/porting/asyncify.html?highlight=longjmp) it seem that async is not supporting with some of the functions used. I have the following question coming to my mind: 

- Regarding it's coming from the linking process why these symbols are missing, it seem to be partially supported ?
- Does any support is expected anytime soon ?
- Is there any workaround ?

Thank you very much :)

**Comment by kripken** [comment]
setjmp/longjmp are supported, however, only if they are called directly (calling them indirectly via a function pointer is undefined behavior). Maybe that's why they are not found?

The `context` APIs there seem to be posix APIs for which there is no current support. Your app may run without them, though.

The pthread function just sets the thread CPU affinity - also, your app may run without it (although, without customizing the affinity, obviously - that's not possible on the web).

**Comment by FrancoisChastel** [comment]
Yes Indeed, thank you for your feedback !

By the way does all the `future` and `async` capabilities are covered by EmScripten ? (related to my issue)

**Comment by kripken** [comment]
I'm not sure how future and async are implemented underneath. If they use pthreads then they should work in a pthreads build.
