### ISSUE TITLE
wasm-backend linking behavior

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#7383]
Linking using the wasm backend leads to larger wasm files in most cases it seems. For example, building `tests/matrix_multiply.cpp` with `-Os --llvm-lto 1 --profiling-funcs`, the wasm backend binary is almost twice as big (45K).

One reason seems to be that code from libcxxabi lingers. Both libcxxabi and libcxx are candidates for being linked in in both cases, while in the asm2wasm path it only ends up linking in one file from libcxx, for `new` support, and then `can_catch` and other stuff form libcxxabi is all removed. The llvm-ld behavior on the other hand ends up keeping `can_catch` and others, as if it linked in more files from libcxx? A `.a` file is used in both cases, which lets the linker avoid linking in unneeded files IIUC.

cc @sbc100

**Comment by sbc100** [comment]
Yes, I believe this is a known issue: https://github.com/WebAssembly/tool-conventions/issues/64

Its because we end up exporting anything with attribute(visibility("default")).   This is used to implement EMSCRIPTEN_KEEPALIVE, but its also used in these libraries.   As a temporary measure we can try to compile these libraries without this attribute.  I'll investigate.

**Comment by kripken** [comment]
The testcase here has improved, now the wasm backend binary is 7% smaller!
