### ISSUE TITLE
test_glgears_proxy_jstarget seems flaky on firefox

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#7421]
e.g. https://circleci.com/gh/kripken/emscripten/49323?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Anyone else seeing this?

**Comment by kripken** [comment]
I hadn't noticed it myself. We can add `@flaky` to it for now until we investigate.

**Comment by kripken** [comment]
I saw this fail now and looked into it a little. It's a reftest, and I guess async because of the proxying, so it needs the manual reftest stuff I added recently. This is slightly trickier though (than the usual case, where you just mark it as manually_reftested and add the manual call in an EM_ASM) because of the proxying, as adding the manual call to `doReftest()` in the C won't work, as that's not on the thread where the canvas is.
