### ISSUE TITLE
Call sync proxied JS library method from pthread?

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#7535]
In our test suite we have `test_pthread_call_sync_on_main_thread` which defines a JS library method with
```
  NAME__proxy: 'sync',
```
The test does not create a pthread itself. It does work in `PROXY_TO_PTHREAD` mode, though, which suggests it should work from a pthread. However, I get a hang when I try that. Here is a testcase:

```
#include <unistd.h>
#include <stdio.h>
#include <pthread.h>
#include <emscripten.h>
#include <emscripten/threading.h>
#include <assert.h>

#define NUM_THREADS 1

void *ThreadMain(void *arg)
{
  // The critical line. sysconf is proxied sync
  printf("in a thread: %ld\n", sysconf(_SC_PAGESIZE));

  pthread_exit(0);
}

int main()
{  
  pthread_attr_t attr;
  pthread_attr_init(&attr);
  pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_JOINABLE);
  pthread_attr_setstacksize(&attr, 4*1024);

  printf("Main thread has thread ID %d\n", (int)pthread_self());
  assert(pthread_self() != 0);

  pthread_t thread[NUM_THREADS];

  for(int i = 0; i < NUM_THREADS; ++i)
  {
    int rc = pthread_create(&thread[i], &attr, ThreadMain, NULL);
    assert(rc == 0);
  }

  pthread_attr_destroy(&attr);

  for(int i = 0; i < NUM_THREADS; ++i)
  {
    int status = 1;
    int rc = pthread_join(thread[i], (void**)&status);
    assert(rc == 0);
    assert(status == 0);
  }

  printf("Done.\n");
}
```

The call to `sysconf` is sync proxied. Building with e.g. `emcc a.cpp -s USE_PTHREADS=1 -o a.html -s PTHREAD_POOL_SIZE=8` it hangs when it runs, unless it was compiled with the sysconf line commented out.

On the other hand, building with `PROXY_TO_PTHREAD=1` it works with the sysconf call.

Is this expected behavior? cc @juj @dschuff

**Comment by juj** [comment]
This is a good observation.

The current implementation of JS library `__proxy` mechanism is still based on `postMessage` - in generated code for `_sysconf`, there's

```javascript
  function _sysconf(name) {
  if (ENVIRONMENT_IS_PTHREAD) return _emscripten_sync_run_in_browser_thread_ii(3, name);
      // long sysconf(int name);
      // http://pubs.opengroup.org/onlinepubs/009695399/functions/sysconf.html
      switch(name) {
        case 30: return PAGE_SIZE;
        case 85:
   ...
  }
```

where the generated code for `_emscripten_sync_run_in_browser_thread_ii` is

```javascript
function _emscripten_sync_run_in_browser_thread_ii(func, p0) {
  var waitAddress = stackSave();
  var returnValue = waitAddress + 4;
  Atomics.store(HEAP32, waitAddress >> 2, 0);
  postMessage({ proxiedCall: 2, func: func, waitAddress: waitAddress, returnValue: returnValue, p0: p0 });
  Atomics.wait(HEAP32, waitAddress >> 2, 0);
  return HEAP32[returnValue >> 2];
}
```

So what happens is that the pthread sends a postMessage to main browser thread, then synchronously starts to wait for result. The main thread on the other hand is synchronously blocked in the `pthread_join()` function, waiting for the thread to finish.

The backstory is that the implementation of `__proxy` mechanism, i.e. the `emscripten_sync_run_in_browser_thread_*` functions, predate the migration to "generic" function signatures (the long block of `EM_FUNC_SIG_`s in threading.h), and back then one could only proxy functions in wasm heap that were explicitly listed in library_pthread.c. The JS side proxying was then created as a `postMessage()` thinking that it'll be easier that way to not depend on compiled code from library_pthread.c, and the impression was that migrating that to using the wasm-embedded per-thread message pipe in library_pthread.c will be just a performance optimization - but this test case points out that this is not the case, it is more than a performance limitation since mutual blocking can occur.

To navigate around this, one should
1) avoid having main thread synchronously block on a pthread (the ".. sync blocking on main thread is bad.." mantra), so dropping the `pthread_join()` (and ensuring NO_EXIT_RUNTIME so runtime stays alive) should also avoid the hang,
2) run with `-s PROXY_TO_PTHREAD=1` so that main browser thread remains free, or,
3) ultimately, migrate implementation of JS `__proxy`/`emscripten_sync_run_in_browser_thread_*` mechanism to post the message in the message queue that lives in the wasm heap (as implemented in library_pthread.c), instead of postMessaging. This will avoid the hang because `pthread_join()` is a cancellation point, so inside it, the main browser thread is already polling its inbound wasm thread event queue for any proxied tasks it might receive, and it'll serve them while its doing its own wait. That is why you'll see the program abort at

```
Error: Script terminated by timeout at:
_emscripten_current_thread_process_queued_calls@file:///C:/code/emsdk/emscripten/incoming/aa.js:10356:6
_emscripten_main_thread_process_queued_calls@file:///C:/code/emsdk/emscripten/incoming/aa.js:10461:2
asm._emscripten_main_thread_process_queued_calls@file:///C:/code/emsdk/emscripten/incoming/aa.js:17695:10
_emscripten_futex_wait@file:///C:/code/emsdk/emscripten/incoming/aa.js:5170:11
_pthread_join@file:///C:/code/emsdk/emscripten/incoming/aa.js:6588:9
_main@file:///C:/code/emsdk/emscripten/incoming/aa.js:7238:10
asm._main@file:///C:/code/emsdk/emscripten/incoming/aa.js:17809:10
callMain@file:///C:/code/emsdk/emscripten/incoming/aa.js:18165:15
doRun@file:///C:/code/emsdk/emscripten/incoming/aa.js:18223:42
run/<@file:///C:/code/emsdk/emscripten/incoming/aa.js:18234:7
```

i.e. from inside `pthread_join()`, the main thread is polling its inbound task queue. (but the proxied sysconf message is unfortunately not coming in there, but will come in as a postMessage, which it won't see until it'd yield back to browser)

**Comment by kripken** [comment]
@juj, how much work do you think option 3 here would be (`migrate implementation of JS __proxy/emscripten_sync_run_in_browser_thread_* mechanism to post the message in the message queue that lives in the wasm heap (as implemented in library_pthread.c), instead of postMessaging.`)?
