### ISSUE TITLE
Implement dummy llvm.returnaddress intrinsic

### ISSUE THREAD

**Issue by atrosinenko** [emscripten-core/emscripten#7634]
When trying to implement Binaryen backend for QEMU (see WebAssembly/binaryen#1494), I got a crash because of the function `llvm_returnaddress` is not defined. From the [documentation](https://llvm.org/docs/LangRef.html#llvm-returnaddress-intrinsic), looks like it is quite safe to make it always return `0`.

As I understand, I cannot implement it in C, because it will get a `_` prefix in its name. On the other hand, implementing it in JS seems to be not efficient (though, when I manually patched the generated .js file to make the `llvm_returnaddress` return `0`, QEMU started correctly).

**Comment by kripken** [comment]
Defining it in `src/library.js`, as `llvm_returnaddress: function() { return 0 },`, should work ok (the prefix etc. will be handled for you) for testing purposes and proof of concept.

If it turns out it's called many times and speed is an issue, we can implement it in the backend in theory. However, first we should see if QEMU actually works with that function returning 0 all the time.

**Comment by atrosinenko** [comment]
Thank you, I will test it.
