### ISSUE TITLE
int64_t variables are done as int32 operations even when function is not exported

### ISSUE THREAD

**Issue by Mintyboi** [emscripten-core/emscripten#7637]
Details:
When MAIN_MODULE=0, int64_t variables are added using 64-bit operations.
However when we flip it to MAIN_MODULE=2, without exporting any functions, the int64_t variables are adding using 32-bit operations.

Testcase:
main.cpp
```
#include <stdint.h>

int64_t foo(int64_t x, int64_t y)
{
  return x + y;
}

int main() {
  int64_t res = foo(1152921504606846975, 8070450532247928832);

  return (int)res;
}
```

Compile with:
```
emcc main.cpp -Oz -std=c++11 -s WASM=1 -s MAIN_MODULE=2 -s ASSERTIONS=1 --profiling -s DEMANGLE_SUPPORT=1 -o %config%\index.html
```

Expected Result in wast:
```
(func $__Z3fooxx (type $t10) (result i64)
    i64.const 9223372036854775807)
```

Actual result in wast:
```
(func $__Z3fooxx (type $t6) (result i32)
    (local $l0 i32) (local $l1 i32)
    i32.const 0
    i32.const 1879048192
    i32.const -1
    i32.const 268435455
    call $_i64Add
    set_local $l1
    call $getTempRet0
    call $setTempRet0
    get_local $l1)
```

**Comment by Mintyboi** [comment]
Only when we pass `-emscripten-only-wasm` into backend by returning true in is_wasm_only() (https://github.com/kripken/emscripten/blob/incoming/tools/shared.py#L2238). Are we able to get the expected results

**Comment by kripken** [comment]
That's correct, currently `is_wasm_only` will return false for a main module, because of `EMULATED_FUNCTION_POINTERS`.

We made progress on that in #7128 but the case of emulated function pointers + dynamic linking still needs some work. I believe this is related to the legalization of i64 exports, which we don't have a clear plan for yet.

**Comment by kripken** [comment]
Yes, the issue is that when in a shared module + emulated function pointers we disable wasm-only mode. That means that all functions do not benefit from wasm-only benefits like native i64 operations (exported or not) And the reason we have this is that when enabling wasm-only mode things break with exports. So it's a current limitation that could be optimized.

But I think it's better to first have a plan for i64 exports, and also it's unclear how much we should work to optimize the asm2wasm path, when the wasm backend path is getting closer (including shared modules).

**Comment by awtcode** [comment]
@kripken and @sbc100 , as get/setTempRet0 are causing a significant slowdown in our codebase, we would not mind having to implement a temporary solution while waiting for the plan for i64 exports to materialize. Do you have an idea on how to optimize this limitation? e.g. restrict the legalization of i64 exports to address taken functions only? Thanks.

**Comment by kripken** [comment]
I'd be ok with a temporary solution if it's important for your use case, yeah. I'm not sure though how to do it. The key issue is

 * When a wasm function is exported, it can be called from JS or from wasm.
 * When we call it from JS, we must call something legalized to JS.
 * When we call it from wasm, we want it to be fully optimized, which may not be legal for JS.
 * In a dynamic linking situation, it's not clear if an export will be called from JS or from wasm: a module exports stuff, but doesn't know who will call it.

So figuring out what to do here is the real issue, which needs some investigation and thought.

If you investigate it, I'd start by running the test suite to see which tests fail when you enable wasm-only mode for this case (i.e. remove the relevant `return False` in `is_wasm_only` in `tools/shared.py`).

But maybe this is simpler than all that, if we just want a temporary option for your codebase. One option worth looking into here might be "assume illegal things are never called from JS", which basically means to build with `-s LEGALIZE_JS_FFI=1` (i.e., tell the compiler not to legalize anything, and if JS calls it, it's JS's problem). This may work for you - if not, perhaps it can be improved a little so it does?

**Comment by awtcode** [comment]
Can I just confirm if a Wasm function can only be called from JS if it is explicitly exported e.g. with EMSCRIPTEN_KEEPALIVE or -s EXPORTED_FUNCTIONS? If this is the case, perhaps, we can first check if a function is exported, if it is, then we force legalization for i64 types?

**Comment by sbc100** [comment]
@awtcode I think one problem is that in the MAIN_MODULE case its quite common to simply export all symbols because you don't know which ones will be called from JS.
