### ISSUE TITLE
Disable Alignment check for SAFE_HEAP When Using Wasm

### ISSUE THREAD

**Issue by awtcode** [emscripten-core/emscripten#7662]
Any slowdown associated with unaligned accesses will not be contributed by the browser or VMs but the underlying hardware. Since most hardware already support unaligned accesses, the check may not be necessary for WASM anymore. FYI @kripken.

**Comment by gabrielcuvillier** [comment]
Maybe alignment check could be kept with a SAFE_HEAP=2, and not if =1

**Comment by kripken** [comment]
Another option may be to add `SAFE_HEAP_CHECK_ALIGNMENT`, defaulting to 1 (seems the right default since it is still useful to know alignment is right even in wasm, it may affect speed).

Regardless of the flag, implementation-wise SAFE_HEAP is implemented as a binaryen pass. We should add a variant of that pass, `--safe-heap-no-align` perhaps, that ignores alignment. If someone's interested to start on this, an example of adding a variant to a pass is here: https://github.com/WebAssembly/binaryen/pull/1824/files

**Comment by kripken** [comment]
I still think this is worth doing if someone has the time to write a patch.

**Comment by sbc100** [comment]
But why?   Isn't it easy to filter the warning you don't case about in such cases?   Is the problem that it make SAFE_HEAP slower or less useful somehow?

Isn't unaligned access still something that one would want to fix in the program source?
