### ISSUE TITLE
Errors appear in javascript console when running sdl2_gl_frames_swap.c

### ISSUE THREAD

**Issue by YiannisBourkelis** [emscripten-core/emscripten#7713]
I am getting some errors in the javascript console of chrome when running one of the sdl tests located here: [https://github.com/kripken/emscripten/blob/5187ea263120ff57424a184c1bc73259e24dc9a9/tests/sdl2_gl_frames_swap.c](https://github.com/kripken/emscripten/blob/5187ea263120ff57424a184c1bc73259e24dc9a9/tests/sdl2_gl_frames_swap.c)

The errors are:
Calling stub instead of sigaction()

emscripten_set_main_loop_timing: Cannot set timing mode for main loop since a main loop does not exist! Call emscripten_set_main_loop first to set one up.

Here is the output I get on chrome browser:
[https://pasteboard.co/HSM07xb.png](https://pasteboard.co/HSM07xb.png)

To compile I used this command, that finished without any errors:
emcc main.cpp -o yiannis2.html -s USE_SDL=2

main.cpp contains the exact code as in the sdl2_gl_frames_swap.c

How can I clear these errors?

**Comment by mscmajidGit** [comment]
I am getting the same error. Please help me

**Comment by mscmajidGit** [comment]
[INFO] (/home/fatemeh/Engine_Shader/src/engine/Engine.cpp:28) Initializing SDL game.js:2457:13
Calling stub instead of sigaction()
game.js:11998:7
uncaught exception: emscripten_get_num_gamepads() can only be called after having first called emscripten_sample_gamepad_data() and that function has returned EMSCRIPTEN_RESULT_SUCCESS!
exception thrown: emscripten_get_num_gamepads() can only be called after having first called emscripten_sample_gamepad_data() and that function has returned EMSCRIPTEN_RESULT_SUCCESS!
