### ISSUE TITLE
Compiling a C library into WASM produces ambiguous export names

### ISSUE THREAD

**Issue by oboforty** [emscripten-core/emscripten#7732]
Hello, I'm trying to compile a C library with the following command:

```
emcc ./c/aes.c \
    -s WASM=1 \
    -O3 \
    -s "EXPORTED_FUNCTIONS=['_aes_setkey_dec', '_aes_setkey_enc', '_aes_crypt_cbc', '_aes_crypt_ctr']" \
    -o src/wasm/aes.js
```

However, the 4 exported functions are exported as "a", "b", "c" and "d". Is this a bug, or am I supposed to give other option for exports?

I have checked the exports with this code:

```
fetch(wasmBinaryFile, {
  credentials: "same-origin"
}).then(response => 
  response.arrayBuffer()
).then(bytes => 
  WebAssembly.compile(bytes)
).then(function(mod) {

  let imps = {
    'env': {
      "a": 0,
      "memory": new WebAssembly.Memory({
        "initial": TOTAL_MEMORY / WASM_PAGE_SIZE,
        "maximum": TOTAL_MEMORY / WASM_PAGE_SIZE
      }),
    },
  };

  // for (let imp of WebAssembly.Module.imports(mod)) {
  // }

  WebAssembly.instantiate(mod, imps).then(function(instance){
    console.log(instance.exports)
  });
});
```

**Comment by kripken** [comment]
The export names are minified, to save space, in higher optimization levels. Emscripten coordinates things so the JS knows and uses the minified names.

I don't think there's an option to disable that optimization currently, but we could add one. Note though that in general you are expected to let the generated JS load the wasm, and not do it directly yourself - otherwise you may be missing a lot of the necessary runtime support. See https://github.com/kripken/emscripten/wiki/WebAssembly-Standalone

**Comment by roecrew** [comment]
@oboforty @kripken 

It may be worth trying an example like the one below.

> emcc -Oz some.c -o my.wasm

```C
#include "emscripten.h"

EMSCRIPTEN_KEEPALIVE
float total(float *arr, int len)
{
    float result = 0;
    for (int i = 0; i < len; ++i)
    {
        result += arr[i];
    }
    return result;
}
```
Export function names are preserved in this example. Unfortunately there's no generated JS file to load the outputted WASM. So you'll have to do it on your own.
I often use the below example when loading WASM.

```JS
const memory = new WebAssembly.Memory({ initial: 256, maximum: 256 });
const importObj = {
    env: {
        table: new WebAssembly.Table({ initial: 0, maximum: 0, element: 'anyfunc' }),
        __table_base: 0,
        memory: memory,
        __memory_base: 1024,
        STACKTOP: 0,
        STACK_MAX: memory.buffer.byteLength
    }
};
fetch('/a.out.wasm').then((response) => {
  return response.arrayBuffer();
}).then((buffer) => {
  if(WebAssembly.validate(buffer)) {
    return WebAssembly.instantiate(buffer, importObj);
  }
}).then(({module, instance}) => {
  //Do something with instance.exports functions etc...
}).catch((err) => {
 console.log(err); 
});
```

Hope this helps!

**Comment by sbc100** [comment]
The names exported by the generated JS file are not minified.     The names exported by the wasm module are designed to be consumed by the generated JS file, not directly accessed.

If you load the generated js file you should be able to access `Module['_aes_setkey_dec']` as expected.

Loading the wasm file directly is not recommended/supported for this reason but also because the ABI between the JS ans the wasm is an implementation detail that is liable to change and not documented.
