### ISSUE TITLE
Different wasm opts in LLVM wasm backend with WASM_OBJECT_FILES

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#7928]
STR:
```
#include <emscripten.h>

int main() {
  EM_ASM({ 5 });
}
```

Run
 * `emcc a.cpp -s WASM_OBJECT_FILES=0 -o a.wasm`
 * `emcc a.cpp -s WASM_OBJECT_FILES=1 -o b.o -c` (building without `-c` will fail, but that's not relevant here)

Then view `a.wasm` vs `b.o`, say using wasm-dis, and look for the import of `env.emscripten_asm_const_*`. In the first case we have
```
  (drop
   (call $fimport$7
    (i32.const 0)
    (i32.add
     (local.get $0)
     (i32.const 8)
    )
    (i32.const 0)
   )
  )
```
while in the second
```
  (local.set $7
   (i32.const 0)
  )
  (local.set $8
   (i32.const 0)
  )
  (drop
   (call $fimport$3
    (local.get $7)
    (local.get $5)
    (local.get $8)
   )
  )
```
Note how the former uses fewer temporary locals. That is, it seems that `WASM_OBJECT_FILES` affects codegen optimizations - is that expected? (Filing in emscripten repo since I'm not sure if this is a backend issue, lld issue, or something in how emcc invokes those.)

I noticed this because of the failure to compile the second - `wasm-emscripten-finalize` doesn't recognize the second pattern. If this is expected behavior, then we need to fix binaryen.

**Comment by jgravelle-google** [comment]
`emcc foo.c -o foo.wasm` should be running `wasm-opt`, I'd imagine (having not checked) that that optimization is implemented in binaryen, and hasn't ran yet in the `b.o` case. What does `emcc a.cpp -s WASM_OBJECT_FILES=1 -o c.wasm` do, or is that the part that just fails?

**Comment by aheejin** [comment]
Looks like `wasm-ld --lto-O0` actually runs the default optimization for llc, which is O2. Looking at how to fix the issue.

**Comment by aheejin** [comment]
lld's `--lto-O0` option is fed into [this line](https://github.com/llvm/llvm-project/blob/cdc201fcdea869c6bd6290bd2611714eb195db0c/lld/wasm/LTO.cpp#L54), setting `lto::Config::OptLevel`. But the backend compilation process controlled by `lto::Config::CGOptLevel`, which we don't touch, and its default value is `CodeGenOpt::Default`, which is -O2.

But I'm also not sure if it's a bug for lld, because all other file formats (ELF, COFF, MachO) are doing the same thing, meaning they don't touch `lto::Config::CGOptLevel`. So fixing this part only for wasm does not seem to make much sense. @sbc100, any thoughts?

Per @kripken, we are switching to `WASM_OBJECT_FILES = 0` fort the default anyway in very near future, so maybe this doesn't need to be fixed.
