### ISSUE TITLE
Module.HeapU8.get: Bulk getValue

### ISSUE THREAD

**Issue by DesWurstes** [emscripten-core/emscripten#7965]
`Module.HEAPU8.set` copies from the array to heap. Then we have to loop using `Module.getValue` to copy from heap to array. I don't like looping, so why don't we have `Module.HEAPU8.get` that does the inverse?

**Comment by juj** [comment]
Emscripten did not design `Module.HEAPU8.set`, but it comes from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set . (HEAPU8 is of type Uint8Array) You can search for something like https://stackoverflow.com/questions/12760643/how-to-convert-a-javascript-typed-array-into-a-javascript-array to convert back. There does not seem to exist a function that would avoid a loop, if you want to copy to an existing array and not create a new one, though.

Instead of using `myArr[i] = Module.getValue(ptr+i)`, you can use `myArr[i] = HEAPU8[ptr+i];` to get a much faster copy, since you statically know you are dealing with the type Uint8. (getValue is useful for scenarios where you only dynamically know the type of the copy)

**Comment by DesWurstes** [comment]
Thanks! If `myArr[i] = HEAPU8[ptr+i];` is possible, I'll do
```javascript
myArr.set(HEAPU8.subarray(ptr, ptr + len));
````
 to avoid loops. That solved my question 👍
