### ISSUE TITLE
Create release archives of emscripten suitable for emsdk users

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#8029]
This is needed for https://github.com/emscripten-core/emscripten/issues/7538.

Today AFAICT emsdk users download emscripten directly from the automatically generate github releases page.    It looks like the emslave builder seems to upload a copy of emscripten to S3 but `./emsdk install` seems to ignore this and always use the github release.    If I'm wrong about this please let me know.

So, I'd like to create a separate archive for each release which contains more than just the contents of `git clone --bare` which is the github default. Specifically I'd like to include the following:

 - node_modules (generated by `npm install`)
 - the results of `git submodule update` (right now we don't have any submodules but I'd like to be able to add some).

I think the best way to do this is to have circle CI automatically create and upload these archives for each tagged release.

We might want to also strip out any files that are not needed by end users (e.g. test/... and any dotfiles such as .gitattributes or .circleci).

**Comment by sbc100** [comment]
@juj can you confirm that emsdk users are already getting emscripten archive from the github releases page?

**Comment by torch2424** [comment]
Hello!

So to resolve the node_modules problem, may I suggest another way of handling this?

On the [AMP project](https://github.com/ampproject/amphtml/tree/master/third_party), and some of my personal JS projects, we just keep a `third_party` directory of certain modules that we need to use. This directory just stores the modules that we need, and all the appropriate licensing and things of that sort. And, we actually do this along side of a package.json. And here are some good reasons (in my opinion), why something like this is a good idea:

* Packages may/may not be on npm
* Maintaining versions manually
* Module may be a core piece of functionality in the lib, that you have made changes to.
* Module may not be used in the lib, and is actually used by an external tool that should be outside of `devDependencies`.
* Modules may be used in the lib, but built dynamically for certain versions, thus isn't a true dependency of the project as a whole.
* Etc...

Personally, I think this would be a great fit for this project, rather than maintaining multiple `package.json`. Especially since it seems that the `optimizer` / `tools` only use a few packages each. The only major downside I see to this, is that updating the package doesn't come for free. But something like Uglify hasn't been updated in quite a while (and I think it is no longer maintained?). And it's not too uncommon in my opinion to do something like this.

This is all just my opinion however, still very new to the project. There may be a good reason to keep the node_modules committed I am not aware of yet.

Let me know what you think, cc @sbc100

**Comment by sbc100** [comment]
Just to confirm, it seems like you are suggesting that we continue to store the modules in git, but in a directory called third_party, rather than called node_modules?

I wouldn't be averse to that, and you are right, these dependencies almost never change.  In that case we could completely remove the package.json as well.  (At least until we want be a consumable module which we are not today).

BTW, how would node find the modules in `third_party`  would it need some kind --module-path or $MODULE_PATH at runtime?   My understanding is that right now it simply keeps looking up the tree until it finds something called `module_path`.

**Comment by sbc100** [comment]
@mathiasbynens

**Comment by juj** [comment]
> @juj can you confirm that emsdk users are already getting emscripten archive from the github releases page?

Yes, these are defined in 

https://github.com/emscripten-core/emsdk/blob/ea5d631a5446632e195765d89a53ead71cd6de45/emsdk_manifest.json#L850

**Comment by kripken** [comment]
@torch2424 - good points! Yeah, we do have crucial local changes to those packages (PRs have been opened upstream, but there doesn't seem interest in them...).

**Comment by torch2424** [comment]
Thanks for considering @sbc100 @kripken !

> Just to confirm, it seems like you are suggesting that we continue to store the modules in git, but in a directory called third_party, rather than called node_modules?

Yes. I do agree on the surface it does sound silly. But when you commit node_modules, you are getting the package, its dependencies, and anything else it *thinks* you should have (meaning source and tests and things if the package author decides so). In our case, we just care about the built output, and not anything else I don't think.

> I wouldn't be averse to that, and you are right, these dependencies almost never change. In that case we could completely remove the package.json as well. (At least until we want be a consumable module which we are not today).

😄 🎉 

Even when the time for the consumable module comes, this shouldn't be a huge blocker going down this path.

> BTW, how would node find the modules in `third_party` would it need some kind --module-path or $MODULE_PATH at runtime? My understanding is that right now it simply keeps looking up the tree until it finds something called `module_path`.

So instead of doing something like `require('uglify-js')`, we would do `require('../../third_party/uglify.cjs.js')`. Where, `uglify.cjs.js` is a *"compiled"* output of whatever module. From my understanding and looking through the code, seems like relative paths shouldn't be a problem. And we only have a few modules currently, thus wouldn't be too much work.

Let me know what you think, wouldn't mind opening a PR for this. Though, if anyone has concerns with this, let me know a good way to test that it's all working 👍

**Comment by sbc100** [comment]
My JS knowledge is not sufficient to be sure this is right direction, but it sounds like it is.    We don't really want to participate in the node module dependency graph, we just want to depend on these external tools that happen to be written in node.  So I you can propose change to move our current node_modules into third_party that would be great (and also remove the package.json file completely I think).

**Comment by juj** [comment]
>  It looks like the emslave builder seems to upload a copy of emscripten to S3 but `./emsdk install` seems to ignore this and always use the github release.

Oh, this is something I recall I made the emslave script to do, but then later we started to use Emscripten as-is, I just forgot to remove the copy from occurring in emslave. At some point we did have the practice of nuking `tests/` subdirectory from being shipped to end user zip builds, hence packaging different versions; but then enough users asked how to run tests, and being surprised when they weren't able to run the tests, that it was simpler to just add them in.

The use case of creating an absolutely minimal sized Emscripten for end users was something that was hard to do, because what is minimal to some, might not be minimal to others (should have docs? should have closure? and so on), and people had different needs, so instead the emsdk "--embedded" build mode was added to let people locally emsdk install a setup they want, then delete unwanted bits, and then zip the resulting tree up as a local minimal version they would internally distribute in their company. (Which is how emslave installer also works)

**Comment by sbc100** [comment]
In this case the proposal is to have the user build more of superset than a subset of what is stored in git.  E.g. allows us to use git submodules, or npm sub modules, that git users would pull down on demand, but SDK users want to have pre-packaged (with no extra downloading).  Something like "make dist" in the traditional open source world. 

Given the arguments made by @torch2424 so far it seems this might not be necessary for the node modules case at least.

**Comment by torch2424** [comment]
Hello!

Sorry for the delay on replying here, been extremely busy at work lately launching some features.

Just a quick status update from me: Still interested in opening a PR for this. I've had this issue in an open tab on my TODO list. Things will wind down in the next couple of weeks, so hopefully then I can dedicate some time for this 😄 

In the meantime, I'll try and get another JS developer from my team to take a look at this, and give me a thumbs up on my approach. And reply here with there opinion.

> So I you can propose change to move our current node_modules into third_party that would be great (and also remove the package.json file completely I think).

Yes, we wouldn't need a `package.json` with this approach, and it could be removed.

> The use case of creating an absolutely minimal sized Emscripten for end users was something that was hard to do, because what is minimal to some, might not be minimal to others (should have docs? should have closure? and so on), and people had different needs, so instead the emsdk "--embedded" build mode was added to let people locally emsdk install a setup they want, then delete unwanted bits, and then zip the resulting tree up as a local minimal version they would internally distribute in their company. (Which is how emslave installer also works)

> In this case the proposal is to have the user build more of superset than a subset of what is stored in git. E.g. allows us to use git submodules, or npm sub modules, that git users would pull down on demand, but SDK users want to have pre-packaged (with no extra downloading). Something like "make dist" in the traditional open source world.

Ahh, @juj makes a very good point. and I think @sbc100 explains this well. Just to give some context from me, the idea I had was that we were looking into making emscripten more "js friendly", as in it can hook in with other JS projects (in pursuit of WASM support). Thus, that is the direction I was thinking of. Though personally, I don't see any superset or subset of whats in the current release as @juj mentioned being affect by what I am suggesting (which is essentially freezing our current JS dependencies that have modifications that we have made), as they would still function in whatever is currently being released.

Let me know if I am making sense.

Thanks! 😄
