### ISSUE TITLE
Proposal: async emscripten_fetch with sync polling

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#8032]
Currently the `emscripten_fetch` API allows both sync and async fetches. Sort of a "third" or "middle" case might be creating async fetches but polling their results synchronously. That is,

 * The fetch would be created with a new attribute, `EMSCRIPTEN_FETCH_POLLING` or such.
 * The callbacks are not automatically called. To get them, one would call `emscripten_fetch_poll()` which would synchronously call callbacks.

This would allow a pthread to run a main loop that looks like a normal native loop,
```
while (1) {
  // other stuff
  //   may call emscripten_fetch() here
  // ..
  // handle network events
  emscripten_fetch_poll();
  // sleep
  emscripten_sleep(..);
}
```
Otherwise, the pthread would need to be refactored to use `emscripten_set_main_loop` or otherwise return to the browser's main event loop. This proposal could save that. Implementation-wise, this would do the fetch on a background thread that does return to the main event loop, to receive network events, so this would depend on pthreads support.

Thoughts?

**Comment by kripken** [comment]
cc @juj

**Comment by juj** [comment]
Hmm, I think this already exists as a "waitable fetch". You can wait for a waitable fetch with `emscripten_fetch_wait()`. If the wait timeout is 0, it is then a poll. If timeout is > 0, it will synchronously wait up to that long time slice, and one can pass INT_MAX for infinite synchronous wait. This is like how the mutex trylock API works.

`emscripten_fetch_wait()` returns the results, see https://emscripten.org/docs/api_reference/fetch.html#waitable-fetches .

When using a waitable fetch, you'd leave the callback pointers as zero if you'd like to just synchronously process the results. (You can then manually fire event handlers for the fetches)

Perhaps that works for the purpose?

**Comment by kripken** [comment]
I see, thanks @juj! That does look sufficient.

**Comment by malytomas** [comment]
Is it possible to use `emscripten_fetch_wait` WITH event handlers?
Currently, the `emscripten_fetch_wait` is returning `EMSCRIPTEN_RESULT`, which is far from intuitive.

Furthermore, would it be possible to call `emscripten_fetch_wait(nullptr, 0)`, which would poll all fetches associated with the current thread?

I am compiling with `-s WASM=1 -s USE_PTHREADS=1 -s FETCH=1`.

**Comment by juj** [comment]
> https://emscripten.org/docs/api_reference/html5.h.html#c.EMSCRIPTEN_RESULT
> does not mention `EMSCRIPTEN_RESULT_TIMED_OUT`. Also I am not sure whether it means that the fetch itself has timed out, or whether the `emscripten_fetch_wait` has timed out.

A return of `EMSCRIPTEN_RESULT_TIMED_OUT` means that the wait timed out without the fetch finishing within that time.

> Furthermore, would it be possible to call `emscripten_fetch_wait(nullptr, 0)`, which would poll all fetches associated with the current thread?

Unfortunately not. Such a "wait for many fetches, whichever finishes first" feature (basically a [select()](http://man7.org/linux/man-pages/man2/select.2.html) function) is something that does not exist. For such behavior, using async fetch completion event handlers is the only way to go.  For "wait for many fetches until they all finish", one can wait for each of them in turn, but naturally must track a list of fetches manually.

It is better to leave it up to the user code to track "all the fetches in the current thread", since if fetch api did that built-in, it would increase code size for all users of fetch, and many users do not need such functionality (and can be managed manually anyways).
