### ISSUE TITLE
Migrate to -s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1 mode

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#8047]
We should, with proper cadence,

1. switch to `-s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1` mode as default build mode, and issue a warning if `-s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=0` mode is used,

and 2. drop support for `-s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=0`.

Flipping the default from 0 to 1 could occur as part of 1.39.0 version bump.

**Comment by juj** [comment]
For details, see https://github.com/emscripten-core/emscripten/pull/7977.

**Comment by juj** [comment]
For more details on the mailing list, see https://groups.google.com/d/msg/emscripten-discuss/xScZ_LRIByk/_gEy67utDgAJ

**Comment by VirtualTim** [comment]
`DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR` was added ~10 months ago. Is it time to set the default to 1?
@kripken?

**Comment by kripken** [comment]
Good point, that does seem like a sufficient amount of time. If someone wants to drive that, it sounds ok to me.

**Comment by hugoam** [comment]
Seriously, no one thought in the 10 months that this has been evolving, to maybe update the **documentation** ?
https://emscripten.org/docs/api_reference/html5.h.html#target-parameter-html5-api

Also, the function signature themselves are the FIRST thing a developer will look at when trying to figure out how a function must be used. And types are more than half of that understanding.

Do you seriously think it's a good idea that this function takes a `const char *target`, when half of the new, very very silently introduced usage of this function is taking parameters that are **NOT** strings ?
At the **very least** typedef that in a `EmscriptenEventTarget` type, and have **SOME** kind of information tying that to parameter type to the `EMSCRIPTEN_EVENT_TARGET_XXX` defines...

Developers using Emscripten that won't lose hours of their time trying to figure out what the hell is the updated usage of this function will thank you for that

**Comment by hugoam** [comment]
Also, if the id passed to those functions doesn't correspond to any element on the page, we get this:

```example-00-helloworldDebug:1246 exception thrown: TypeError: Cannot read property 'addEventListener' of null,TypeError: Cannot read property 'addEventListener' of null
    at Object.registerOrRemoveHandler (https://hugoam.github.io/two/bgfx/example-00-helloworldDebug.js:5083:31)
    at __registerKeyEventCallback (https://hugoam.github.io/two/bgfx/example-00-helloworldDebug.js:5435:16)
    at _emscripten_set_keypress_callback_on_thread (https://hugoam.github.io/two/bgfx/example-00-helloworldDebug.js:5442:7)
    at entry::Context::run(int, char const* const*) (wasm-function[1111]:0x7ecb5)
    at main (wasm-function[1110]:0x7ebc6)
    at Module._main (https://hugoam.github.io/two/bgfx/example-00-helloworldDebug.js:6991:32)
    at callMain (https://hugoam.github.io/two/bgfx/example-00-helloworldDebug.js:7309:15)
    at doRun (https://hugoam.github.io/two/bgfx/example-00-helloworldDebug.js:7370:23)
    at https://hugoam.github.io/two/bgfx/example-00-helloworldDebug.js:7381:7
```

Which is pretty much the worst possible way to handle a potential mis-use of those functions, aka not doing anything at all and letting something else fail silently further down the line.

**Comment by juj** [comment]
Thanks for the rant, now I started my Sunday morning pissed too. Instead of contributing to answers, I am wondering why bother spending my free time collaborating with idiots. I'll get back to this in a month or two once I feel like reading whining like this and don't have anything better to do. You want to share emotions, you'll get emotions back.

**Comment by hugoam** [comment]
If you want some non-whiny rational and constructive points, on a project of that scale with that many users, there needs to be a stronger review process that makes it *physically* impossible to merge this kind of refactors that will silently break the code of thousands of users, because they just shouldn't be. It's simple reasonable common sense.

If enough peer safety was added on reviewing the changes involved, the things I have said would have been said, in the form of regular PR criticism, in a regular tone, and would have prevented merging. Those things need to be enforced at this stage, because if they are not everything goes haywire, people encounter breakage, wonder where it comes from, spend a significant amount of time looking for the cause, do not find it, find contradicting documentation that says what they are doing is correct, then finally maybe find it, are (very) frustrated, open issues (duplicate issues probably, there are already a couple in the month that the new breaking behavior has been silently forced active) and voice them in whatever state of mind the unexplained sudden breakage made them.

Now those comments weren't expressed nicely in a review, but in an angry tone, uncalled for, obviously, from an angry user. I'm sorry. I am not entitled to anything from anyone and that was indeed wrong of me.

But please, when doing breaking changes, you need to have a stone-written rule that it is *required* to be done in the *least silent way possible*. That usually involves a compiler error. Your non-frustrated happy users will thank you.

**Comment by juj** [comment]
Thank you for the backhanded apology and the great guidance on how to avoid regressions in development.

**Comment by kripken** [comment]
Looks like the unconstructive comments have been deleted here already.

Please in the future be respectful of everyone on this issue tracker.
