### ISSUE TITLE
Future of Fetch?

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#8070]
Background: #7024 - fetch does not fully work with wasm. Opening this issue to ask @juj some questions about the current code, and what plans might make sense, both for that wasm issue, and some additional things.

Right now, asm.js fetch can create a special worker. This is not compiled, but made in `make_fetch_worker` (which is asm.js specific, hence incompatible with wasm). But I don't understand yet how that worker is used - is it just for pthreads mode?

In pthreads mode, a pthread could do async stuff, return to the main event loop, etc., and another thread could send it stuff to do, wait on it, etc., basically letting the other thread use a more native-like API. Is the that the goal of the current asm.js worker? If so, could it be removed, and similar functionality added using a normal pthread, in normal C code in system/lib/fetch/, which would then work in both asm.js and wasm? Or does that worker do stuff in non-pthreads builds too?

#6202 adds backproxying of HTML5 events - should fetch have a similar capability, that is, should one thread be able to create a fetch, and schedule the callback on another thread?

And how does all this relate to asmfs?

cc @juj @sbc100 @dschuff

**Comment by juj** [comment]
> But I don't understand yet how that worker is used

The worker performs asynchronous XHRs and asynchronous IndexedDB accesses, and passes results back to the calling pthread, so that

a) the calling pthread can behave as if it achieved to do a synchronous XHR or a synchronous IndexedDB operation, and
b) the calling pthread can behave as if it achieved to do an asynchronous XHR or an asynchronous IndexedDB operation, but instead of receiving a JS event callback in the pthread, it can gather the results off the Fetch object on the asm heap. This is important for pthreads that run an infinite `for(;;){}` main loop, so they would not be able to yield back to the browser to receive events, so Fetch makes this automatic for those use cases.

Also, it should be noted that it is critical that only exactly one Worker on a page performs IndexedDB operations against a database, because otherwise coherency issues will happen. (IDB is transactional, but multiple workers storing and loading files independently would not maintain coherently consistent view of the same in asm code, unless asm side code modeled the same transactionality to avoid racing, which is not needed here)

> is it just for pthreads mode?

Yes, in singlethreaded mode the main browser thread cannot achieve a synchronous XHR or a synchronous IndexedDB operation even if such a background worker is used, since the main thread cannot block. So cases a) and b) are not useful there, and in singlethreaded mode Fetch allows one to do async XHRs.

> In pthreads mode, a pthread could do async stuff, return to the main event loop, etc., and another thread could send it stuff to do, wait on it, etc., basically letting the other thread use a more native-like API. Is the that the goal of the current asm.js worker?

The issue that a dedicated fetch-worker.js set out to solve was that each worker has a full JS context, and if it was a full pthread, then in a large application, that would mean having to load all the compiled JS (+ asm.js) code in that worker as well, which takes up memory. In asm.js multithreading threads are super-expensive, hence the design to do a dedicated Worker that only has the minimal JS + asm.js bits needed to perform these operations. Then the compiled JS code size in that Worker is minimal compared to other threads, which could easily be hundred+ megs of memory in UE4/Unity asm.js multithreading builds. This work predates wasm, and naturally in wasm multithreading this concern is smaller. At that time, we did not know how the compiled code memory duplication would end up being removed, so dedicated worker was the simple solution to make Fetch worker not contribute towards compiled code memory bloat.

> Or does that worker do stuff in non-pthreads builds too?

No, the worker does not exist in singlethreaded builds.

> #6202 adds backproxying of HTML5 events - should fetch have a similar capability, that is, should one thread be able to create a fetch, and schedule the callback on another thread?

Ideally yes. The evolution of these APIs is that HTML5 was the first "general" `do_x_on_thread()` API that got implemented. Then the couple of GL functions (which are a bit more complex, since they `do_x_on_the_thread_that_owns_the_given_gl_context()`), and most recent is the library_websocket.js library, which is very similar to the library_html5.js API `do_x_on_thread()`.

Fetch predates all of this completely generic proxying and backproxying message pipe on the heap, which is why it does not use it, but has its own solution embedded in the `Fetch` structure. This could be updated now that the message queue mechanism is there.

> And how does all this relate to asmfs?

Asmfs implements a Unix-like filesystem in C++ code. It backs on top of Fetch library to do XHR and IndexedDB operations when it needs to read or persist files. The thread affinity is already "solved" by the Fetch library for asmfs, and you see all asmfs code runs directly in their calling thread.

**Comment by VirtualTim** [comment]
So FETCH + WASM don't work in blocking mode, but this wasn't documented in the API reference. I've created a pull request for the doco: https://github.com/emscripten-core/emscripten/pull/8075/files

**Comment by juj** [comment]
Looks like with small change, it is possible to run blocking fetches in fastcomp wasm. Posted PR #8077 to patch, and added a test.

**Comment by kripken** [comment]
Thanks @juj!

It sounds like we want to keep the worker for asm.js builds, then, assuming we care about asm.js + pthreads. Do we? If not, is the best path to getting full fetch working in wasm to remove the current worker and use a normal pthread?

Or, should we make `make_fetch_worker` work on wasm too?

**Comment by juj** [comment]
> It sounds like we want to keep the worker for asm.js builds, then, assuming we care about asm.js + pthreads. Do we?

I think we do - I still do all my debugging of multithreading impl in asm.js (e.g. debugging src/worker.js script, MODULARIZE=1 with pthreads, mutex lock issues), because it lets one do window.dump()s interleaved in asm.js code to quickly mutate a build to a debug annotated state.

Keeping the worker for asm.js builds sounds fine. Once there is a C/C++ pthread based replacement, dropping the dedicated JS worker is alright, that won't be needed anymore (the extra memory bloat that using a C/C++ pthread there brings is no longer a concern)

> Or, should we make `make_fetch_worker` work on wasm too?

In upstream LLVM wasm, I think trying to make `make_fetch_worker` JS scraping approach work would not make sense. Probably best to just create a C/C++ pthread for that. For short term for fastcomp wasm, it looks like having that `make_fetch_worker` script there is a quick way to get fastcomp wasm access sync fetches.

**Comment by VirtualTim** [comment]
One other notable issue with the current fetch API is that is uses `XMLHttpRequest`, which only supports streaming downloads in Firefox (via `moz-chunked-arraybuffer`). Using the fetch JS API seems to support that (at least in Chrome ≥43 / Firefox ≥ 65), but it does seem to be missing things like local file system access.
