### ISSUE TITLE
-s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR breaks mouse callback canvasX/canvasY

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#8087]
Compiling with "-s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR" breaks the following code snippet:
```
EMSCRIPTEN_RESULT click_callback(int eventType, const EmscriptenMouseEvent* e, void* userdata) {
    printf("(x=%ld, y=%ld)", e->canvasX, e->canvasY);
}
int main {
    emscripten_set_mousedown_callback("#canvas", 0, EM_TRUE, click_callback);
    return EXIT_SUCCESS;
}
```
Wherever I click I get `(x=0, y=0)`.

Obviously this is just a smaller section of something much more complex , so if this isn't enough info let me know and I'll create a minimal example.
#8047

**Comment by juj** [comment]
Yeah, this is expected behavior. Check out the email about this in the mailing list:

https://groups.google.com/d/msg/emscripten-discuss/xScZ_LRIByk/_gEy67utDgAJ

"A related change is that the following event callback fields are deprecated:

long EmscriptenMouseEvent::canvasX;
long EmscriptenMouseEvent::canvasY;
long EmscriptenTouchPoint::canvasX;
long EmscriptenTouchPoint::canvasY;

these fields referenced mouse and touch coordinates relative to the
"Module.canvas" object, which is going away. Instead, refer to the
targetX and targetY fields that report coordinates relative to the
target DOM element in question."

**Comment by VirtualTim** [comment]
Ah great, I missed the mailing list.
Changing canvasX to targetX changed the behaviour to what I was expecting.
