### ISSUE TITLE
Thoughts about Cheerp's performance numbers?

### ISSUE THREAD

**Issue by evanw** [emscripten-core/emscripten#8192]
Cheerp just released an article saying how their generated WebAssembly is on average 7% faster than emscripten's: https://medium.com/leaningtech/cheerp-2-0-release-880f249a5677. I haven't verified this myself but it sounds plausible. They say that improvements to the relooper algorithm are responsible for some of the performance gains. 

Are there performance numbers accurate? If so, are there any plans to improve the performance of emscripten's WebAssembly output to match Cheerp?

**Comment by kripken** [comment]
I don't think their numbers are accurate :) But this is a discussion I've had with them in the past, and we haven't reached clear conclusions. Part of the issue is that good, meaningful benchmarking is just hard to do.

Here are some of the issues I have with their numbers:

 * They report a subset of the emscripten benchmark suite. On the ones they don't report, emscripten is quite faster - for example, emscripten is 20% faster on Havlak, 52% faster on ifs, and 11% faster on primes.
 * I can't reproduce their numbers. On many tests the results are the same, but on several they are 5-10% faster in their reported results than what I get when I run locally. To some extent this may be due to CPU or other differences between the machines, but it's still odd. Might be interesting for a third party to run them.
 * Several of our more interesting benchmarks (that run real-world code) don't run on Cheerp, they hit compiler or runtime errors, for example, SQLite, Lua, LZMA, and Poppler. Those might be limitations or bugs in Cheerp (for example, lua needs longjmp, which Cheerp doesn't seem to support). I'd be more comfortable assessing the compilers once Cheerp can run all those real-world codebases (and preferably more - not just the emscripten benchmark suite, which is far from great).
 * There are significant system library differences, so the comparisons are not apples-to-apples. For example, some tests depend on malloc (Havlak) or libc math (Box2D). For malloc, emscripten uses dlmalloc but and optionally offers a smaller but slower one (emmalloc). It's not clear what the "right" comparison is, if Cheerp's default allocator made a different tradeoff decision (which it seems to, based on its size and its performance on havlak).

With all that said, there are interesting things in their numbers. I looked carefully at them and at the generated code, and identified a few things we can do better, such as:

 * Remove 2.5K of unneeded code from printf (oops!) https://github.com/emscripten-core/emscripten/pull/8133
 * On zlib they are indeed faster, and it turns out that we are in fact missing some important optimization work there, which I hope to do this week. One preparation for that is https://github.com/WebAssembly/binaryen/pull/1918

Also worth mentioning that the compiler backend they tested against will soon not be the interesting one, as emscripten is close to switching from the fastcomp asm.js backend to the upstream LLVM wasm backend. The numbers for that one are quite different - it actually uses all the power of LLVM's backend codegen infrastructure, unlike fastcomp and Cheerp - and it's been our main optimization focus for a while now.

Btw, regarding the relooper, which as you say they claim to have improved on: there seem to be several misunderstandings in what they write. One thing is that they call it "the aging Relooper algorithm" ;) but a more accuate description is that they copied the old Relooper code from fastcomp, but it's gotten a lot better since. The current main implementation is in Binaryen here: https://github.com/WebAssembly/binaryen/blob/master/src/cfg/Relooper.h it will emit much better code than the older Relooper (in particular, fewer label variable usages - smaller, faster, and simpler code).

Emscripten's plan is to use the upstream LLVM backend by default soon, as mentioned earlier, which has a CFGStackify pass, and we run Binaryen optimizations afterwards, which may include the Relooper depending on the optimization level (at lower optimization levels, the power of the Relooper is probably not wanted). This works very well, and we are still improving it together with other LLVM backend.

**Comment by alexp-sssup** [comment]
> I don't think their numbers are accurate :)

I am sorry to have to intervene in this discussion, but I am surprised by your statement. I am the person that actually, physically gathers all the performance numbers that we publish and I personally vouch for their validity. You said it yourself Alon, that you actually **can** reproduce many of the results. I understand that you get different results on some tests, which are most probably caused by differences in the CPU being used. For the record this is the machine used for testing: https://support.apple.com/kb/SP715?locale=en_US (2.9GhZ version). As a matter of fact we think that, especially with the latest 2.0 release, we have been fully transparent as we have:

- Contributed back to Emscripten all the minor changes required to run the test suite
- Documented the specific commits of V8 and SpiderMonkey used (for reference V8: 46cc15b1905af6d43e39500aaecc7f430a8b93a4, SM: 1206de2a542c)
- Published the specific machine used for the test (referenced above)
- For additional clarity, all our benchmarking was done from Emscripten commit 2e82c860f75cb62005e0b37ab367dcf5590b3ce4 (our patches to Emscripten should be reapplied on top of this commit to get the exact same configuration)

All of this should prove that we are absolutely certain about our results, although CPU-dependent effects on performance clearly exist.

**Comment by kripken** [comment]
Hi @alexp-sssup - perhaps I should have been clearer before, sorry if so. When I said I don't think the Cheerp 2.0 blogpost results are accurate, I mainly meant that I don't think the main claim "On average, WebAssembly code generated by Cheerp 2.0 is 5% faster than the one generated by Emscripten" is accurate. (That's in the Chrome section, which is what I focused on.)

To be more specific, on the one hand, yes, I can reproduce most of your reported individual results fairly closely. However, on the other hand,

1. Not all Emscripten benchmarks are reported, and as mentioned above, Emscripten is faster on many of those unreported ones (see above). This by itself means my overall average is significantly different than your 5%.
2. Not all emscripten benchmarks compile and run properly on Cheerp, so we just have a partial picture even when including the unreported ones. This includes many of the more realistic tests like SQLite, Lua, Poppler.
3. On some of the reported results there is a [significant difference](https://github.com/emscripten-core/emscripten/pull/8135#issuecomment-466131290) compared to what I see locally, your results favor Cheerp while mine favor Emscripten.

Given those, I disagree with the claim that Cheerp is 5% faster than Emscripten.

As you said, perhaps CPU differences on our machines can explain part of point 3. However, even there it's a little odd that the pattern is one-sided. A similar one-sided pattern is in point 1. So there is probably more here than just a CPU difference. One possible explanation is that Cheerp first investigates a benchmark, then once you understand it you add it to your reported ones. If you tune Cheerp while investigating, then that could explain part of why your reported results favor Cheerp. But then the unreported benchmarks may actually be more relevant for new code that users compile - it's debatable.

And in the end, as I said before, good, meaningful benchmarking is just hard to do - that's not a specific complaint about Cheerp, but about compiler benchmarking in general. As I said earlier, the Emscripten benchmark suite is really not that good. I've tried to make it better by adding Poppler, SQLite, Lua, and other real-world code - as I said, if we can measure Cheerp on those as well, I think that would make for more interesting results. Also good would be to see both compilers run on something interesting that **isn't** in any benchmark suite, and to report numbers **before** any performance tuning, like say [Doom 3 that was very recently ported with Emscripten](http://www.wasmrocks.com/topic/330/doom-3-running-in-the-browser-using-emscripten-webassembly).

I do appreciate the effort you made to report accurate results, including contributing benchmark runner changes, documenting your setup, etc. I think those things are very good!

**Comment by alexp-sssup** [comment]
Thanks for clarifying your statement. We will try to add more and larger public benchmark in the future.

**Comment by MaxGraey** [comment]
Hmm, Cheerp published details about its improvements:

https://medium.com/leaningtech/solving-the-structured-control-flow-problem-once-and-for-all-5123117b1ee2

**Comment by kripken** [comment]
Thanks for the link @MaxGraey.

As mentioned above, the complaints about the Relooper are obsolete, both in the old post and this new one. The original Relooper did indeed have such limitations, but for years now the modern version has not. For example, here is what `emcc -O3` does to that switch example that they give there:
```
  (block $label$1
   (block $label$2
    (block $label$3
     (block $label$4
      (br_table $label$4 $label$3 $label$2 $label$1
       (call $_A)
      )
     )
     (call $_B)
    )
    (call $_C)
   )
   (call $_D)
  )
  (call $_E)
```
(which is the optimal result)
