### ISSUE TITLE
LLVM backend emits bulk copy operations when compiling with -pthread

### ISSUE THREAD

**Issue by brion** [emscripten-core/emscripten#8224]
Testing dav1d decoder with latest LLVM upstream backend, I get validation errors like this:

```
[wasm-validator error in function $dav1d_data_ref] unexpected false: Bulk memory operation (bulk memory is disabled), on 
[none] (memory.copy
 [i32] (local.get $0)
 [i32] (local.get $1)
 [i32] (i32.const 56)
)
```

These bulk-memory copy operations aren't valid yet in browsers as far as I know, and probably shouldn't be being emitted unless opted in.

This happens both when using `-s USE_PTHREADS=1` or not, if `-pthread` is passed during compile of object files. Removing the `-pthread` option seems to resolve it, though I'm not sure that's ... correct.

Testing upstream commit a77638d5c1fe7833118083 with emscripten commit d6ae4efbab8c0ed5042 This didn't happen a couple days ago as of my last upstream-clang update.

Repro repo: https://github.com/brion/emscripten-llvm-pthread-bug

**Comment by sbc100** [comment]
Ah yes, we probably want to not enable `-mbulk-memory` when using pthreads just yet.  In the long run it will be used to memory initialization for multi-threaded programs.   But I think emscripten currently supports extracting the data sections and manual initialization as a stop gap so we should continue to do that.

**Comment by tlively** [comment]
It should be fine to have bulk-memory enabled by default with pthreads as soon as it is stable in LLVM because browswers will ship bulk-memory before or alongside threads. And we don't expect emscripten to work with pthreads and the LLVM backend right now anyway, so I don't think this could be regressing anything except bleeding-edge testing.

But I don't want to block separate testing of pthreads in emscripten, so I will disable bulk-memory by default with threads until it is more stable in LLVM.

**Comment by tlively** [comment]
https://reviews.llvm.org/D58854

**Comment by tlively** [comment]
The LLVM fix has landed, so closing this issue. Just be aware that bulk memory operations will come back by default with -pthread in the near future!
