### ISSUE TITLE
Emscripten-generated JS peculiarity? App keeps generating prompt() for input

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emscripten#8231]
There's this issue in Emscripten-generated JavaScript glue-code where it generates the message to ask for input via the `window.prompt` method multiple times, even after it's been given the input needed.  I have to click the checkbox to get it to not produce any more messages.  Is there no way to fix that?  

There's also another thing I need to ask that's related to that: is there no way to take the prompt for input from the original C++ code and send it to the JavaScript glue code generated by Emscripten so that I can use it as the string input to the `window.prompt` method?  I tried to cut a part of the text displayed in the textarea on the HTML page, but it didn't work like I wanted so I had to give up and just manually edit the string passed to the `window.prompt` method.  

And I'd prefer to be able to use an HTML form instead of `window.prompt`, so I was wondering if there was a way to do that that actually worked.

**Comment by adrianbg** [comment]
I was able in Safari to get it to stop asking by pressing escape (cancel) twice in a row.

**Comment by arasouli91** [comment]
It has been a long time since I was working with this, but I believe there is at least one issue discussing this already and possibly a solution. In my case, I was taking input from a textbox, in which case you can rewrite the stdin functionality. I believe if you define the stdin function, the prompt goes away.

`` 

       emModule.stdin = function () {
                // Return ASCII code of character, or null if no input remains
                    if (i < inputText.length) {
                        let c = inputText.charCodeAt(i++);
                        return c;
                    } else 
                        return null;
        };
``
It is iterating through a string that stored the input that was retrieved from the textbox. However, the program is only run after the user submits the input. So, you could write code on the JS side that prompts the user before running the wasm, puts the input in a string, then use the code above.

I'd also suggest looking for the other issue(s) discussing this.

**Comment by jensbodal** [comment]
Solved this with just doing 

```
const originalPrompt = window.prompt;
window.prompt = () => {};

// restore at the end
window.prompt = originalPrompt;
```
