### ISSUE TITLE
does emscripten support WASM backend now?

### ISSUE THREAD

**Issue by yylittlefish** [emscripten-core/emscripten#8245]
### when I use emcc to build wasm file with "EMCC_WASM_BACKEND=1", it shows :+1: shared:CRITICAL: WebAssembly set as target, but LLVM has not been built with the WebAssembly backend, llc reports:
===========================================================================

    js     - JavaScript (asm.js, emscripten) backend
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64

===========================================================================
shared:ERROR: failing sanity checks due to previous llvm failure

it seems emscripten not support wasm backend yet, right?
is there any method to generate wasm backend?

**Comment by sbc100** [comment]
In order to used the llvm wasm backend you need to point your LLVM_ROOT at
a recent build of llvm.   In fact, thats all you need to do.  There is no
need to set EMCC_WASM_BACKEND.

To get a llvm you can either build it yourself and set LLVM_ROOT in your
~/.emscripten file, or you can try using emsdk to install it using `emsdk
install sdk-incoming-64bit`.
