### ISSUE TITLE
Feature Request: Build Main/Side Modules with USE_PTHREADS=1

### ISSUE THREAD

**Issue by fibbo** [emscripten-core/emscripten#8316]
Is this on the road map already? Or is this something that is not feasible to achieve. We would like to be able to link dynamically while also benefit from pthreads.

The goal is to reduce startup time for our program (by having smaller modules and only load certain modules on demand) and also improve performance (rendering in parallel with pthreads).

**Comment by kripken** [comment]
No concrete plans on this - but perhaps @sbc100 has thoughts?

**Comment by sbc100** [comment]
I would say its certainly something we want to be able to do, but we are more focused right now on getting these two features independently working with the wasm backend.

Off the top of my head, loading modules on demand seems tricky because modules need to be posted to workers using `postMessage`.  This means at the every least each of your worker threads will need to be returning the browser event loop periodically, which limits the kind of works you can do in workers.
