### ISSUE TITLE
Bring the emcc compiler to the browser

### ISSUE THREAD

**Issue by loxaxs** [emscripten-core/emscripten#8336]
Is it possible to use emcc from the browser to (live) compile C code?
How?
Has it already be done?

I'm not sure how emcc is built, so I'm not sure my initial idea of using it to compile itself to wasm would work.

**Comment by curiousdannii** [comment]
In theory it might be possible. In practice it has hundreds, maybe thousands of files, which makes packaging it for the web difficult.

**Comment by jgravelle-google** [comment]
In theory anything is possible. In practice:
1) there's a hard dependency on LLVM to compile the C code, which means we need to compile LLVM to wasm first. Given that LLVM is large and complicated, this seems non-trivial.
2) Emscripten also has a hard dependency on Binaryen. Binaryen does have a wasm build, so that's just a question of interfacing to it.
3) Emscripten itself is built in Python, so we need to compile Python to wasm. I believe this already mostly works (we actually have a test for it https://github.com/emscripten-core/emscripten/blob/007d839136b78a4beb5d5b8721a4a3af9d36b555/tests/test_core.py#L5681), though there's some runtime shenaniganry around interpreters and wasm lacking gotos.

So it would be really really tricky to re-coordinate those different codebases, not to mention the actual compilation, not to mention the overall size of the built .wasm files.
