### ISSUE TITLE
MEMFS not freeing memory

### ISSUE THREAD

**Issue by feliwir** [emscripten-core/emscripten#8351]
Hey, 
our application is doing a lot of File IO used for caching files. We have an internal filesystem limit of 512MB, so we start deleting files to stay below that limit. Unfortunaly it seems like MEMFS is not reusing / freeing the deleted files memory, so our HEAP keeps growing until the application crashes.

Is there any ways to tell MEMFS that it should free the memory of the deleted files? Is that "leak" due to Javascripts garbage collection? Unfortunaly using a persistent filesystem like IDBFS isn't an option either due to the limit of 50MB and that it still stores files in RAM.

We are using WASM and our options are as follows:
```
-s ALLOW_MEMORY_GROWTH=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s WASM=1 
-s USE_SDL=2 -std=c++1z -s "BINARYEN_TRAP_MODE='clamp'"
```

Thanks

**Comment by kripken** [comment]
JavaScript GC and HEAP growing are entirely separate. So first we should find out which is the problem here. If HEAP keeps growing, then it's not related to JS GC, and the question is what causes those allocations - mmaping a file could do it, for example, but offhand I'm not sure what else (there's no other malloc in the memfs code).

May be useful to instrument malloc/free to see where the calls are coming from.
