### ISSUE TITLE
browser.test_fetch_stream_file fails on chrome

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#8397]
It throws "Invalid typed array length". Works on firefox somehow.

**Comment by VirtualTim** [comment]
`EMSCRIPTEN_FETCH_STREAM_DATA` uses `moz-chunked-arraybuffer`, which is Firefox only. It looks like that test is already [disabled on Chrome](https://github.com/emscripten-core/emscripten/blob/incoming/tests/test_browser.py#L4187), so this can probably be closed.
I'm working on a PR to update the doco since that's not actually listed anywhere.
