### ISSUE TITLE
Using C va_args in JavaScript

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#8399]
So if I have a function like: `extern "C" bool vaFunction(...)` which internally uses something like `va_arg(va, unsigned int)`, and I attempt to call it from JavaScript like `Module._vaFunction(50)` Emscripten interprets '50' as a pointer, not as a number.

Is this expected behaviour?

**Comment by sbc100** [comment]
On Thu, Apr 4, 2019 at 10:35 PM Tim Lander <notifications@github.com> wrote:

> So if I have a function like: extern "C" bool vaFunction(...) which
> internally uses something like va_arg(va, unsigned int), and I attempt to
> call it from JavaScript like Module._vaFunction(50) Emscripten interprets
> '50' as a pointer, not as a number.
>
> Is this expected behaviour?
>

The C standard requires that you have at least one argument prior to the
ellipsis ("...").    C++ seems to not have that restriction, but its
probably worth doing it the C way, especially if you want to use va_start
(which requires naming the last regular argument) on the native side.

I think that real cause of your problem is the wasm C ABI passes all var
args arguments as a pointer to memory.  So you need to write all your args
to a buffer and then call the function with a pointer to the buffer.

**Comment by VirtualTim** [comment]
> The C standard requires that you have at least one argument prior to the ellipsis ("...").

Ah I wasn't aware of this. In the actual code I was using there was one prior argument, I was just trying to simplify things.

> I think that real cause of your problem is the wasm C ABI passes all var args arguments as a pointer to memory.

Sounds like it's working as designed then. I'll close this issue. The behaviour was just different to pure C++ so I thought I would check to confirm.
