### ISSUE TITLE
undefined symbol: $FS

### ISSUE THREAD

**Issue by rianhunter** [emscripten-core/emscripten#8421]
When I compile a small program like this using `emcc file.c`

```
#include <sys/time.h>
#include <stddef.h>
int main() {
    return utimes(NULL, NULL);
}
```

It fails to compile erroring out with: `error: undefined symbol: $FS`

This seems to be due to this line:

https://github.com/emscripten-core/emscripten/blob/0d77e1688a1bc3a979e743b7fc2d13f45233fe6b/emscripten.py#L620

It seems like there are many FS dependencies for which this doesn't account. I could post a patch but wanted to check if this was intentional first.

**Comment by kripken** [comment]
I think that's a bug, yeah. That optimization assumes that syscalls are the only thing that can require FS support, but there are things like `utimes` which are implemented in `library.js` and need the FS.

The simple solution might be to have a list of such methods in emscripten.py there, which is not pretty. A cleaner solution might be to make the jsifier/modules.js code load the filesystem JS library when it appears in a dependency, but that's not a small change since we load the JS libraries before looking at deps currently.

**Comment by rianhunter** [comment]
> The simple solution might be to have a list of such methods in emscripten.py there, which is not pretty. A cleaner solution might be to make the jsifier/modules.js code load the filesystem JS library when it appears in a dependency, but that's not a small change since we load the JS libraries before looking at deps currently.

Yeah I could do the more elegant solution but it would be a bit out of my depth. The more I think about it, the more I question the validity of this optimization in the first place. Why not punt the job of optimizing out the file system to the user? This optimization seems to apply to a small specialized set of users.

**Comment by kripken** [comment]
Yeah, I understand that point of view. On the other hand, that's actually the common case - it lets us optimize programs using just printf or a few other stdio methods to not include the full filesystem code, which is quite large (and impossible to optimize out later, because it uses indirect calls etc.).

Maybe another option here is to improve that error message to say "you should build with `-s FORCE_FILESYSTEM=1`" (which skips that optimization).

**Comment by rianhunter** [comment]
> Yeah, I understand that point of view. On the other hand, that's actually the common case - it lets us optimize programs using just printf or a few other stdio methods to not include the full filesystem code, which is quite large (and impossible to optimize out later, because it uses indirect calls etc.).

I think most users of emscripten are writing code that certainly uses more than close, ioctl, llseek, and writev. Maybe this case is common in the tests, but I don't think in real life.

> Maybe another option here is to improve that error message to say "you should build with -s FORCE_FILESYSTEM=1" (which skips that optimization).

I think that would be a surprising default. Every other compiler can compile my example code without having to set a special option.

**Comment by sbc100** [comment]
Users who use on of those calls either directly or indirectly are already fine.   They will get filesystem support.

Its users like this example that only call utimes who might not actually want the full filesystem. 

I think that rational here is that the filesystem support in emscripten is a strange enough beast and big enough that its reasonable to opt into it unless its very obvious that you really need it.   At least thats my interpretation.   Certainly the error should be better.

**Comment by rianhunter** [comment]
> I think that rational here is that the filesystem support in emscripten is a strange enough beast and big enough that its reasonable to opt into it unless its very obvious that you really need it. At least thats my interpretation. Certainly the error should be better.

That may be the case, my interpretation is that including the file system is a matter of correctness, and excluding it is a matter of optimization. It seems that emscripten should err on the side of including the file system since it's a matter of correctness, and for users that care about the optimization details can opt out of it at potentially their own peril.

**Comment by sbc100** [comment]
You make a good point.  Perhaps @kripken knows more of the background here.

**Comment by kripken** [comment]
Sorry if I wasn't clear before - yes, this is a bug, and we should fix it. I'm looking into some options here currently. (The problem is that it's hard to do this without regressing code size, which we should avoid, but hopefully a proper fix here isn't too hard.)

**Comment by wblakey** [comment]
Is this closed? I am still getting the 
error: undefined symbol: $FS
on the latest version

**Comment by kripken** [comment]
@wblakey we are not aware of current bugs there, please provide a testcase if you are still seeing it.

**Comment by wblakey** [comment]
it appears to be when I am building to web assembly, its not present with .30 but is with .31, I have moved back to the previous version for the time being, i use a cmake to compile the wasm, the error i get says:
error: undefined symbol: $FS
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
Error: Aborting compilation due to previous errors
shared:ERROR: 'emsdk/emscripten/1.38.31/src/compiler.js emsdk/emscripten/1.38.31/src/embind/emval.js emsdk/emscripten/1.38.31/src/embind/embind.js emsdk/emscripten/1.38.31/src/library_pthread_stub.js' failed (1)

**Comment by wblakey** [comment]
Do you need more information?

**Comment by kripken** [comment]
@wblakey yes, we need more information. Either a testcase showing the issue, or if you can't provide that, if you can bisect to find the commit that broke things for you, that might be good enough too - not always, but usually it is. Also an option is if you can provide the output when building with `-s VERBOSE=1` (which logs out all the dependencies) - that also might be enough.

**Comment by wblakey** [comment]
VERBOSE is on, this generates a lot of output and can slow down compilation
adding ___buildEnvironment and deps $ENV : function ___buildEnvironment(environ) {

adding ENV and deps  : {}
adding ___cxa_allocate_exception and deps  : function ___cxa_allocate_exception(size)
adding ___cxa_begin_catch and deps _ZSt18uncaught_exceptionv,$EXCEPTIONS : function ___cxa_begin_catch(ptr) {
    v
adding EXCEPTIONS and deps __cxa_free_exception : {last:0,caught:[],infos:{},deAdjust:func
adding ___cxa_free_exception and deps  : function ___cxa_free_exception(ptr) {
  
adding ___cxa_pure_virtual and deps  : function ___cxa_pure_virtual() {
    ABO
adding ___cxa_throw and deps _ZSt18uncaught_exceptionv,__cxa_find_matching_catch,$EXCEPTIONS : function ___cxa_throw(ptr, type, destruc
adding ___cxa_find_matching_catch and deps __resumeException,$EXCEPTIONS : function ___cxa_find_matching_catch() {

adding ___resumeException and deps $EXCEPTIONS,function () { Functions.libraryFunctions['___resumeException'] = 1 } : function ___resumeException(ptr) {
    i
adding ___cxa_uncaught_exception and deps _ZSt18uncaught_exceptionv : function ___cxa_uncaught_exception() {
 
adding ___gxx_personality_v0 and deps _ZSt18uncaught_exceptionv,__cxa_find_matching_catch : function ___gxx_personality_v0() {
  }
adding ___lock and deps  : function ___lock() {}
adding ___map_file and deps __setErrNo : function ___map_file(pathname, size) {
 
adding ___setErrNo and deps  : function ___setErrNo(value) {
    if (Mo
adding ___syscall140 and deps $SYSCALLS : function ___syscall140(which, varargs) {
adding SYSCALLS and deps  : {buffers:[null,[],[]],printChar:function
adding ___syscall145 and deps $SYSCALLS : function ___syscall145(which, varargs) {
adding ___syscall146 and deps $flush_NO_FILESYSTEM,$SYSCALLS : function ___syscall146(which, varargs) {
adding flush_NO_FILESYSTEM and deps  : function flush_NO_FILESYSTEM() {
    // 
adding ___syscall4 and deps $SYSCALLS : function ___syscall4(which, varargs) {SY
adding ___syscall54 and deps $SYSCALLS : function ___syscall54(which, varargs) {S
adding ___syscall6 and deps $SYSCALLS : function ___syscall6(which, varargs) {SY
adding ___syscall91 and deps $SYSCALLS : function ___syscall91(which, varargs) {S
adding ___unlock and deps  : function ___unlock() {}
adding __embind_register_bool and deps $getShiftFromSize,$readLatin1String,$registerType : function __embind_register_bool(rawType,
adding getShiftFromSize and deps  : function getShiftFromSize(size) {
    sw
adding readLatin1String and deps $embind_charCodes : function readLatin1String(ptr) {
    var
adding embind_charCodes and deps $embind_init_charCodes : undefined
adding embind_init_charCodes and deps  : function embind_init_charCodes() {
    v
adding registerType and deps $awaitingDependencies,$registeredTypes,$typeDependencies,$throwBindingError,$whenDependentTypesAreResolved : function registerType(rawType, registere
adding awaitingDependencies and deps  : {}
adding registeredTypes and deps  : {}
adding typeDependencies and deps  : {}
adding throwBindingError and deps $BindingError : function throwBindingError(message) {
  
adding BindingError and deps $extendError : undefined
adding extendError and deps $createNamedFunction : function extendError(baseErrorType, erro
adding createNamedFunction and deps $makeLegalFunctionName : function createNamedFunction(name, body)
adding makeLegalFunctionName and deps $char_0,$char_9 : function makeLegalFunctionName(name) {
 
adding char_0 and deps  : 48
adding char_9 and deps  : 57
adding whenDependentTypesAreResolved and deps $awaitingDependencies,$registeredTypes,$typeDependencies,$throwInternalError : function whenDependentTypesAreResolved(m
adding throwInternalError and deps $InternalError : function throwInternalError(message) {
 
adding InternalError and deps $extendError : undefined
adding __embind_register_emval and deps _emval_decref,$emval_handle_array,_emval_register,$readLatin1String,$registerType,$simpleReadValueFromPointer : function __embind_register_emval(rawType
adding __emval_decref and deps $emval_free_list,$emval_handle_array : function __emval_decref(handle) {
    if
adding emval_free_list and deps  : []
adding emval_handle_array and deps  : [{},{value:undefined},{value:null},{valu
adding __emval_register and deps $emval_free_list,$emval_handle_array,$init_emval : function __emval_register(value) {

    
adding init_emval and deps $count_emval_handles,$get_first_emval : function init_emval() {
    Module['coun
adding count_emval_handles and deps $emval_handle_array : function count_emval_handles() {
    var
adding get_first_emval and deps $emval_handle_array : function get_first_emval() {
    for (va
adding simpleReadValueFromPointer and deps  : function simpleReadValueFromPointer(poin
adding __embind_register_float and deps embind_repr,$floatReadValueFromPointer,$getShiftFromSize,$readLatin1String,$registerType : function __embind_register_float(rawType
adding _embind_repr and deps  : function _embind_repr(v) {
    if (v ===
adding floatReadValueFromPointer and deps  : function floatReadValueFromPointer(name,
adding __embind_register_integer and deps embind_repr,$getShiftFromSize,$integerReadValueFromPointer,$readLatin1String,$registerType : function __embind_register_integer(primi
adding integerReadValueFromPointer and deps  : function integerReadValueFromPointer(nam
adding __embind_register_memory_view and deps $readLatin1String,$registerType : function __embind_register_memory_view(r
adding __embind_register_std_string and deps $readLatin1String,$registerType,$simpleReadValueFromPointer,$throwBindingError : function __embind_register_std_string(ra
adding __embind_register_std_wstring and deps $readLatin1String,$registerType,$simpleReadValueFromPointer : function __embind_register_std_wstring(r
adding __embind_register_void and deps $readLatin1String,$registerType : function __embind_register_void(rawType,
adding _abort and deps  : function _abort() {
    Module['abort'](
adding _emscripten_asm_const_int and deps  : true
adding _emscripten_get_heap_size and deps  : function _emscripten_get_heap_size() {
 
adding _emscripten_resize_heap and deps emscripten_get_heap_size,$abortOnCannotGrowMemory,$emscripten_realloc_buffer : function _emscripten_resize_heap(request
adding abortOnCannotGrowMemory and deps  : function abortOnCannotGrowMemory(request
adding emscripten_realloc_buffer and deps  : function emscripten_realloc_buffer(size)
adding _getenv and deps $ENV : function _getenv(name) {
    // char *ge
adding _llvm_bswap_i32 and deps  : function _llvm_bswap_i32(x) {
    x = x|
adding _llvm_stackrestore and deps  : function _llvm_stackrestore(p) {
    var
adding _llvm_stacksave and deps  : function _llvm_stacksave() {
    var sel
adding _llvm_trap and deps  : function _llvm_trap() {
    abort('trap!
adding _memcpy and deps emscripten_memcpy_big,Int8Array,Int32Array : function _memcpy(dest, src, num) {
    d
adding _emscripten_memcpy_big and deps  : function _emscripten_memcpy_big(dest, sr
adding _memmove and deps memcpy : function _memmove(dest, src, num) {
    
adding _memset and deps Int8Array,Int32Array : function _memset(ptr, value, num) {
    
adding _pthread_cond_broadcast and deps  : function _pthread_cond_broadcast(x) {
  
adding _pthread_cond_wait and deps  : function _pthread_cond_wait() { return 0
adding _pthread_mutexattr_destroy and deps  : function _pthread_mutexattr_destroy() {}
adding _pthread_mutexattr_init and deps  : function _pthread_mutexattr_init() {}
adding _pthread_mutexattr_settype and deps  : function _pthread_mutexattr_settype() {}
adding _rintf and deps round,Math_floor : function _rintf(f) {
    f = +f;
    ret
adding _round and deps Math_floor,Math_ceil : function _round(d) {
    d = +d;
    ret
adding _sbrk and deps __setErrNo,emscripten_get_heap_size,emscripten_resize_heap,$abortOnCannotGrowMemory : function _sbrk(increment) {
    incremen
adding _strftime_l and deps strftime : function _strftime_l(s, maxsize, format,
adding _strftime and deps _isLeapYear,_arraySum,_addDays,_MONTH_DAYS_REGULAR,_MONTH_DAYS_LEAP : function _strftime(s, maxsize, format, t
adding __isLeapYear and deps  : function __isLeapYear(year) {
      retu
adding __arraySum and deps  : function __arraySum(array, index) {
    
adding __addDays and deps _isLeapYear,_MONTH_DAYS_LEAP,_MONTH_DAYS_REGULAR : function __addDays(date, days) {
    var
adding __MONTH_DAYS_LEAP and deps  : [31,29,31,30,31,30,31,31,30,31,30,31]
adding __MONTH_DAYS_REGULAR and deps  : [31,28,31,30,31,30,31,31,30,31,30,31]
adding _sysconf and deps __setErrNo : function _sysconf(name) {
    // long sy

**Comment by wblakey** [comment]
Does this help? do you want more?

**Comment by wblakey** [comment]
wait apologies that is the .30 when it worked ill do it again with .31

**Comment by wblakey** [comment]
VERBOSE is on, this generates a lot of output and can slow down compilation
adding ___buildEnvironment and deps $ENV : function ___buildEnvironment(environ) {

adding ENV and deps  : {}
adding ___cxa_allocate_exception and deps  : function ___cxa_allocate_exception(size)
adding ___cxa_begin_catch and deps _ZSt18uncaught_exceptionv,$EXCEPTIONS : function ___cxa_begin_catch(ptr) {
    v
adding EXCEPTIONS and deps __cxa_free_exception : {last:0,caught:[],infos:{},deAdjust:func
adding ___cxa_free_exception and deps  : function ___cxa_free_exception(ptr) {
  
adding ___cxa_pure_virtual and deps  : function ___cxa_pure_virtual() {
    ABO
adding ___cxa_throw and deps _ZSt18uncaught_exceptionv,__cxa_find_matching_catch,$EXCEPTIONS : function ___cxa_throw(ptr, type, destruc
adding ___cxa_find_matching_catch and deps __resumeException,$EXCEPTIONS : function ___cxa_find_matching_catch() {

adding ___resumeException and deps $EXCEPTIONS,function () { Functions.libraryFunctions['___resumeException'] = 1 } : function ___resumeException(ptr) {
    i
adding ___cxa_uncaught_exception and deps _ZSt18uncaught_exceptionv : function ___cxa_uncaught_exception() {
 
adding ___gxx_personality_v0 and deps _ZSt18uncaught_exceptionv,__cxa_find_matching_catch : function ___gxx_personality_v0() {
  }
adding ___lock and deps  : function ___lock() {}
adding ___map_file and deps __setErrNo : function ___map_file(pathname, size) {
 
adding ___setErrNo and deps  : function ___setErrNo(value) {
    if (Mo
adding ___syscall140 and deps $SYSCALLS : function ___syscall140(which, varargs) {
adding SYSCALLS and deps $FS,$ERRNO_CODES,$PATH : {DEFAULT_POLLMASK:5,mappings:{},umask:51
error: undefined symbol: $FS
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
adding FS and deps  : function FS() {
err('missing function: $
adding ERRNO_CODES and deps  : {EPERM:1,ENOENT:2,ESRCH:3,EINTR:4,EIO:5,
adding PATH and deps  : {splitPath:function (filename) {
      v
adding ___syscall145 and deps $SYSCALLS : function ___syscall145(which, varargs) {
adding ___syscall146 and deps $SYSCALLS : function ___syscall146(which, varargs) {
adding ___syscall4 and deps $SYSCALLS : function ___syscall4(which, varargs) {SY
adding ___syscall54 and deps $SYSCALLS : function ___syscall54(which, varargs) {S
adding ___syscall6 and deps $SYSCALLS : function ___syscall6(which, varargs) {SY
adding ___syscall91 and deps $SYSCALLS : function ___syscall91(which, varargs) {S
adding ___unlock and deps  : function ___unlock() {}
adding __embind_register_bool and deps $getShiftFromSize,$readLatin1String,$registerType : function __embind_register_bool(rawType,
adding getShiftFromSize and deps  : function getShiftFromSize(size) {
    sw
adding readLatin1String and deps $embind_charCodes : function readLatin1String(ptr) {
    var
adding embind_charCodes and deps $embind_init_charCodes : undefined
adding embind_init_charCodes and deps  : function embind_init_charCodes() {
    v
adding registerType and deps $awaitingDependencies,$registeredTypes,$typeDependencies,$throwBindingError,$whenDependentTypesAreResolved : function registerType(rawType, registere
adding awaitingDependencies and deps  : {}
adding registeredTypes and deps  : {}
adding typeDependencies and deps  : {}
adding throwBindingError and deps $BindingError : function throwBindingError(message) {
  
adding BindingError and deps $extendError : undefined
adding extendError and deps $createNamedFunction : function extendError(baseErrorType, erro
adding createNamedFunction and deps $makeLegalFunctionName : function createNamedFunction(name, body)
adding makeLegalFunctionName and deps $char_0,$char_9 : function makeLegalFunctionName(name) {
 
adding char_0 and deps  : 48
adding char_9 and deps  : 57
adding whenDependentTypesAreResolved and deps $awaitingDependencies,$registeredTypes,$typeDependencies,$throwInternalError : function whenDependentTypesAreResolved(m
adding throwInternalError and deps $InternalError : function throwInternalError(message) {
 
adding InternalError and deps $extendError : undefined
adding __embind_register_emval and deps _emval_decref,$emval_handle_array,_emval_register,$readLatin1String,$registerType,$simpleReadValueFromPointer : function __embind_register_emval(rawType
adding __emval_decref and deps $emval_free_list,$emval_handle_array : function __emval_decref(handle) {
    if
adding emval_free_list and deps  : []
adding emval_handle_array and deps  : [{},{value:undefined},{value:null},{valu
adding __emval_register and deps $emval_free_list,$emval_handle_array,$init_emval : function __emval_register(value) {

    
adding init_emval and deps $count_emval_handles,$get_first_emval : function init_emval() {
    Module['coun
adding count_emval_handles and deps $emval_handle_array : function count_emval_handles() {
    var
adding get_first_emval and deps $emval_handle_array : function get_first_emval() {
    for (va
adding simpleReadValueFromPointer and deps  : function simpleReadValueFromPointer(poin
adding __embind_register_float and deps embind_repr,$floatReadValueFromPointer,$getShiftFromSize,$readLatin1String,$registerType : function __embind_register_float(rawType
adding _embind_repr and deps  : function _embind_repr(v) {
    if (v ===
adding floatReadValueFromPointer and deps  : function floatReadValueFromPointer(name,
adding __embind_register_integer and deps embind_repr,$getShiftFromSize,$integerReadValueFromPointer,$readLatin1String,$registerType : function __embind_register_integer(primi
adding integerReadValueFromPointer and deps  : function integerReadValueFromPointer(nam
adding __embind_register_memory_view and deps $readLatin1String,$registerType : function __embind_register_memory_view(r
adding __embind_register_std_string and deps $readLatin1String,$registerType,$simpleReadValueFromPointer,$throwBindingError : function __embind_register_std_string(ra
adding __embind_register_std_wstring and deps $readLatin1String,$registerType,$simpleReadValueFromPointer : function __embind_register_std_wstring(r
adding __embind_register_void and deps $readLatin1String,$registerType : function __embind_register_void(rawType,
adding _abort and deps  : function _abort() {
    Module['abort'](
adding _emscripten_asm_const_int and deps  : true
adding _emscripten_get_heap_size and deps  : function _emscripten_get_heap_size() {
 
adding _emscripten_resize_heap and deps emscripten_get_heap_size,$abortOnCannotGrowMemory,$emscripten_realloc_buffer : function _emscripten_resize_heap(request
adding abortOnCannotGrowMemory and deps  : function abortOnCannotGrowMemory(request
adding emscripten_realloc_buffer and deps  : function emscripten_realloc_buffer(size)
adding _getenv and deps $ENV : function _getenv(name) {
    // char *ge
adding _llvm_bswap_i32 and deps  : function _llvm_bswap_i32(x) {
    x = x|
adding _llvm_stackrestore and deps  : function _llvm_stackrestore(p) {
    var
adding _llvm_stacksave and deps  : function _llvm_stacksave() {
    var sel
adding _llvm_trap and deps  : function _llvm_trap() {
    abort('trap!
adding _memcpy and deps emscripten_memcpy_big,Int8Array,Int32Array : function _memcpy(dest, src, num) {
    d
adding _emscripten_memcpy_big and deps  : function _emscripten_memcpy_big(dest, sr
adding _memmove and deps memcpy : function _memmove(dest, src, num) {
    
adding _memset and deps Int8Array,Int32Array : function _memset(ptr, value, num) {
    
adding _pthread_cond_broadcast and deps  : function _pthread_cond_broadcast(x) {
  
adding _pthread_cond_wait and deps  : function _pthread_cond_wait() { return 0
adding _pthread_mutexattr_destroy and deps  : function _pthread_mutexattr_destroy() {}
adding _pthread_mutexattr_init and deps  : function _pthread_mutexattr_init() {}
adding _pthread_mutexattr_settype and deps  : function _pthread_mutexattr_settype() {}
adding _rintf and deps round,Math_floor : function _rintf(f) {
    f = +f;
    ret
adding _round and deps Math_floor,Math_ceil : function _round(d) {
    d = +d;
    ret
adding _sbrk and deps __setErrNo,emscripten_get_heap_size,emscripten_resize_heap,$abortOnCannotGrowMemory : function _sbrk(increment) {
    incremen
adding _strftime_l and deps strftime : function _strftime_l(s, maxsize, format,
adding _strftime and deps _isLeapYear,_arraySum,_addDays,_MONTH_DAYS_REGULAR,_MONTH_DAYS_LEAP : function _strftime(s, maxsize, format, t
adding __isLeapYear and deps  : function __isLeapYear(year) {
      retu
adding __arraySum and deps  : function __arraySum(array, index) {
    
adding __addDays and deps _isLeapYear,_MONTH_DAYS_LEAP,_MONTH_DAYS_REGULAR : function __addDays(date, days) {
    var
adding __MONTH_DAYS_LEAP and deps  : [31,29,31,30,31,30,31,31,30,31,30,31]
adding __MONTH_DAYS_REGULAR and deps  : [31,28,31,30,31,30,31,31,30,31,30,31]
adding _sysconf and deps __setErrNo : function _sysconf(name) {
    // long sy
Error: Aborting compilation due to previous errors

**Comment by wblakey** [comment]
this is the correct one, let me know if you need more

**Comment by kripken** [comment]
Thanks, I'm not sure what's causing this though - it requests FS from SYSCALLS, but that should be ok. We did fix a few bugs related to that, so perhaps this works on latest incoming, worth checking there.

**Comment by wblakey** [comment]
thanks for looking into it, ill see if the next release helps

**Comment by wblakey** [comment]
I am pulling from git when i build, does this have all the latest bug fixes?

**Comment by kripken** [comment]
the `incoming` branch in git has all the latest fixes, yes.

**Comment by kkimdev** [comment]
I was hitting the same error with 1.38.31 and updating to 1.38.32 solved it.
```
/opt/emsdk-portable/emsdk install sdk-tag-1.38.32-64bit
/opt/emsdk-portable/emsdk activate sdk-tag-1.38.32-64bit
```
