### ISSUE TITLE
Rust: Uint8Array as argument and return value

### ISSUE THREAD

**Issue by nazar-pc** [emscripten-core/emscripten#8441]
I'm a total newbie in Rust and after spending a few hours I still can't figure out how to make simple operation on Uint8Array in Rust when compiled to WebAssembly.

Essentially, my use case involves Rust function like this:
```rust
#[no_mangle]
pub extern fn generate(input: Vec<u8>) -> Vec<u8> {
    // Something is happening here, new Vec<u8> is generated
}
```

Essentially I'd like to get an API on JavaScript's side something like this (I'm used to working with this):
```c
int generate(uint8_t *input, size_t input_size, uint8_t *output) {
    // Something is happening here, output is filled with useful data
    // and 0 or 1 is return as status code
}
```

There are no issues with numerical (except `u64`, which turns into something different on Rust side when used) and boolean types, but `Vec<u8>` feels unnecessary complex to work with.

Is there an easy way to do this?
Ideal API would be to just specify `Uint8Array` instance as an argument, but I guess that will never happen.

**Comment by brion** [comment]
I haven't done a lot of Rust/Wasm work directly, but you might want to look
into wasm-bindgen or another bindings helper tool.

Using wasm-bindgen, you should be able to export a binding for a function
that takes a &[u8] as input (rather than a Vec<u8>):
https://rustwasm.github.io/docs/wasm-bindgen/reference/types/number-slices.html

(The Uint8Array may need to be allocated _in_ the Wasm memory region for
this to work, though, it's a bit unclear from the docs and I haven't used
it directly.)

If you want to skip binding generator helpers and make your own binding,
you'd want to make a function that takes a *u8 as pointer and a usize as
length, and then call that from the JS side -- potentially writing your own
wrapper JS function that gets the offset for the Uint8Array for you, so you
just pass it a Uint8Array.

Again, this only works if the Uint8Array is a view on the Wasm memory
buffer -- the simplest way to do this is to call Module._malloc and
Module._free directly, or you can write allocators/deallocators in the Rust
side that use Vec<u8> something similar.

-- brion

**Comment by nazar-pc** [comment]
So I know how to allocate memory on Wasm memory buffer, no problems there. Also I'd like to avoid wasm-bindgen at this point, since 2 functions with mentioned signatures are the only ones I have issues with. I've tried `wasm-pack`, but faced issues with glibc, so how using `wasm32-unknown-emscripten` target and it works quite well so far.

More precisely, I have difficulties with bridging Rust with C, since while Emscripten happily compiles mentioned code, it is not clear how to use it correctly. And there seem to be too many ways to do bad things when dealing with cross-language boundaries in Rust.

**Comment by brion** [comment]
You shouldn't need to write any C, as long as your Rust<->JS API is "C-like" (using `#[no-mangle]` on names, and using unsafe wrappers to deal with any pointer management.) You will though have to write a little JavaScript to marshal between `Uint8Array`s and pointer/length pairs.

Something like this on your Rust side:

```rust
// Internal code has a nice Rust interface using slices.
fn generate_impl(input: &[u8], output: &mut [u8]) {
    // Something is happening here, with data written to the output slice.
}

// The "C-like" external API function uses pointers and lengths.
#[no_mangle]
pub extern fn generate_api(input: *const u8, input_size: usize, output: *mut u8, output_size: usize) {
    unsafe {
        generate(std::slice::from_raw_parts(input, input_size), 
                       std::slice::from_raw_parts(output, output_size));
    }
}
```

Then add a JS function which wraps them. You can append these onto the `Module` object with a `--pre-js` or `--post-js` file at compile time. Something like:

```js
// Creates a buffer for use in generate function.
// It'll be a regular Uint8Array pointing to an allocated area in the wasm memory.
Module.generate_alloc = function(length) {
   return new Uint8Array(Module._malloc(length), length);
};

// Frees a created buffer.
Module.generate_free = function(buffer) {
    // buffer must be a Uint8Array view of our memory
    Module._free(buffer.byteOffset);    
};

// Generate stuff from an input buffer into an output buffer.
// Buffers must be Uint8Array views of the wasm memory,
// as created by generate_alloc and freed with generate_free.
Module.generate = function(input, output) {
  Module._generate(input.byteOffset, input.length, output.byteOffset, output.length);
};
```

In this case you have to manually free (or reuse) buffers or they'll take up extra space in wasm memory. Unfortunately there's no way to plug into JavaScript's garbage collection at this granularity, so you need to manually free data after use... alternately, or if you find you want data to live on beyond the lifetime of the wasm module, you could copy things to/from a separate Uint8Array that doesn't alias the wasm memory.

**Comment by nazar-pc** [comment]
OK, so after trial and error this works for me:
```rust
fn generate_impl(input: Vec<u8>) -> Vec<u8> {
    // ...
}

#[no_mangle]
pub extern fn generate(
    input: *const u8,
    input_size: usize,
    output: *mut *const u8,
    output_size: *mut usize
) -> u8 {
    unsafe {
        let output_generated = generate_impl(
            slice::from_raw_parts(input, input_size).to_vec()
        );
        *output = output_generated.as_slice().as_ptr();
        *output_size = output_generated.len();
        mem::forget(output_generated);
        return 0;
    }
}
```

Obviously, I had to allocate pointers in JS, dereference them after this call and free `output_generated` allocated by Rust once I have `Uint8Array` copy of it in JavaScript.

It works, but is there anything wrong with this code?

**Comment by brion** [comment]
Looks like it'll function correctly, leaving the output buffer detached from Rust-land so it can be freed later from JS. However I think the `to_vec()` on the input slice actually does a copy of the input data, which you might want to avoid to speed things up a little.

If you can change the `generate_impl` fn to take a slice instead of a `Vec` that'll be simplest, but there should be a way to build a `Vec` from an existing memory buffer too; just not sure offhand glancing at the docs. :)

**Comment by nazar-pc** [comment]
I should be able to change function signature, thanks for your help, really appreciate it!
