### ISSUE TITLE
how to solve huge symbols  which is exported by side_module in main_module's js?

### ISSUE THREAD

**Issue by ck7colin** [emscripten-core/emscripten#8489]
as title, if my prj is a huge prj, my side_module will be exported huge symbols. as a result, my main_module's js is very very large. that's unacceptable!

**Comment by sbc100** [comment]
I guess you could write some kind of post-processor that takes that side module and the main module and minified the imports/exports.

I'm not sure emscripten can do at build time since the main module and the side modules are compiled separately.

Such a post-link tool would also be able to GC any unsed symbols in the main module.
