### ISSUE TITLE
C library imports are different depending on wasm backend

### ISSUE THREAD

**Issue by rianhunter** [emscripten-core/emscripten#8500]
The import list for C library symbols in generated WASM files is different depending on the wasm backend. If using the binaryen backend, the symbols are prefixed with an underscore, if using the LLVM backend the symbols don't have an underscore prefix.

This is a problem for third-party users of emscripten generated wasm binaries because the exports provided would need to change depending on the backend with which the wasm binary was compiled.

Should this be normalized? If so, which naming convention is canonical? If not, I'll need to add this to the emscripten metadata section.

**Comment by kripken** [comment]
We plan to normalize this on the wasm backend's version (no extra underscore) - basically by switching the default to that backend, and eventually removing support for the old backend entirely (i.e., we don't intend to fix up the old backend).

**Comment by rianhunter** [comment]
Interesting, would you be amenable to changing the binaryen backend to use the newer convention in the meantime?

**Comment by kripken** [comment]
(To make sure we're talking about the same thing, when you say "binaryen backend" do you mean fastcomp + binaryen's asm2wasm? We intend to remove fastcomp, but asm2wasm may still be useful for some things. In any case, asm2wasm doesn't depend on the prefix stuff, so not a problem here.)

I wouldn't be opposed to a patch to fix fastcomp, but the larger amount of work would be to update the emscripten JS and python support code - a lot of stuff scattered around. We'll be just removing all that support code instead of fixing it up, basically.

We hope to switch the default fairly soon. Everything is done except for buildbots, which we are working on now.

**Comment by rianhunter** [comment]
Hmm let me investigate a bit more to see if there is a quick and dirty yet robust way to fix this (with the expectation that fastcomp will be removed in the short term)

**Comment by sbc100** [comment]
Yes, there is a fair amount of complexity in emscripten for papering over this difference.   

The plan going forward is to simply converge on llvm upstream and remove fastcomp.    In the mean time emscripten (or any tool that wants to directly consume emscripten-built wasm files as I think you are trying to do?) will need to handle this difference (in addition to the other differences that exist).
