### ISSUE TITLE
Simple example show console errors 'Calling stub instead of sigaction()'

### ISSUE THREAD

**Issue by SrMordred** [emscripten-core/emscripten#8567]
I shrink it to the very minimal: 

```
#include <SDL2/SDL.h>
int main(int argc, char *argv[]) 
{
	(void) argv;
	(void) argc;
	SDL_Init( SDL_INIT_VIDEO );
	return 0;
}
```
and the console shows 
```
Calling stub instead of sigaction()
Calling stub instead of sigaction()
Calling stub instead of sigaction()
```

But, this is not a issue for me. 
On a more complete code, emscripten main loop works fine even after the errors. 

Just curious trying to found where this errors come from without success.

**Comment by sbc100** [comment]
SDL_Init makes calls to `sigaction`.   When building with ASSERTIONS on emscripten will warn about such calls because signal as not supported.   So I would say this is expected behaviour.  If you don't like have such warnings we could looking to removing the logging, or modifying SDL_init.  But as you say its not a problem.
