### ISSUE TITLE
Difference between "emscripten_set_canvas_size" and "emscripten_set_canvas_element_size"

### ISSUE THREAD

**Issue by eduardodoria** [emscripten-core/emscripten#8590]
I used to call `emscripten_set_canvas_size` in fullscreenchange callback like this:

```
EM_BOOL fullscreenchange_callback(int eventType, const EmscriptenFullscreenChangeEvent *e, void *userData) {
    if (e->isFullscreen){
        int w, h, fs;
        emscripten_get_canvas_size(&w, &h, &fs);
        originalWidth = w;
        originalHeight = h;

        emscripten_set_canvas_size(e->screenWidth, e->screenHeight);
        updateScreenSize(e->screenWidth, e->screenHeight);
    }else{
        emscripten_set_canvas_size(originalWidth, originalHeight);
        updateScreenSize(originalWidth, originalHeight);
    }

    return 0;
}
```
Now, with deprecation of `emscripten_set_canvas_size` I'm not getting the same result with `emscripten_set_canvas_element_size`. It's like canvas don't change when called in fullscreenchange callback. I tried with "#canvas" and "NULL".

What is the difference between these two functions?

Also, I don't know how can I get canvas size after fullscreen change. Because `emscripten_get_canvas_size` and `emscripten_set_canvas_element_size` get it size before changed. I need this info to send to my engine.

**Comment by Apivan** [comment]
I found the replacement function from this discussion https://groups.google.com/forum/#!topic/emscripten-discuss/h5Gz0gQrziQ. At the time I submit the change in https://github.com/OGRECave/ogre/issues/857
I short-circuited ropts in the very first commit so that I can pass the canvas size in. I also did test it by hard code the canvas size. 

What I notice from your code is that the code tries to acquire the canvas size after entering the fullscreen mode. 

So could you first please check the return result from 
   EMSCRIPTEN_RESULT r = emscripten_get_canvas_element_size("#canvas", &w, &h); 

And please have a look on this discussion too. 
https://groups.google.com/forum/#!msg/emscripten-discuss/mc3T1SYycdw/bsMoxcMjMdQJ
Thanks

**Comment by eduardodoria** [comment]
`emscripten_get_canvas_element_size` is getting correct values. But if even remove it putting `width` and `height` with fixed values the different behavior still occur.

> I think the different between emscripten_set_canvas_element_size and the deprecated one is that the former specify which canvas to set by passing css selector as first argument.

I made several tests and `emscripten_set_canvas_element_size` has different behavior from `emscripten_set_canvas_size` when called in fullscren change callback. The new function don't update canvas size.

**Comment by eduardodoria** [comment]
I my recent tests this behavior occur only in `Module.requestFullscreen`. When I use `emscripten_request_fullscreen` it seems work as expected.
