### ISSUE TITLE
Emscripten should not set a precision on vertex shaders

### ISSUE THREAD

**Issue by greggman** [emscripten-core/emscripten#8627]
this line

https://github.com/emscripten-core/emscripten/blob/49d9559997774f828309d70b3a8d3aef50e86bfb/src/library_glemu.js#L366

 is adding

```
precision mediump float;
```

to any vertex shader that doesn't have a precision set. While fragment shaders need a precision specified vertex shaders do not in WebGL and they default to `highp`. Setting them to `mediump` is breaking content on mobile for no reason

the solution is to delete that line.

While we're on the topic there is similar code for fragment shaders. I'd argue that code should default to `highp`. Why ... because lots of lighting code breaks (using world positions for lights etc) when in mediump.  I get that it's probably set to mediump because some old phones don't support highp in fragment shaders but I suspect that's a pretty low percentage in 2019?

In any case, the vertex shader side should have that check removed.

**Comment by greggman** [comment]
for reference

https://stackoverflow.com/questions/56157030/how-to-deal-with-opengl-serious-z-fighting-in-webassembly

**Comment by solidpixel** [comment]
For OpenGL ES you must specify a default precision for float variables in shaders, and will get compilation errors without it unless all variables have an explicit precision applied. 

The problem is not so much the presence of a default, it's just that `mediump` is the wrong default precision for vertex shaders; fp16 just isn't precise enough for position transforms.

The default selected should be based on shader type - use a `highp` default for vertex shaders and a `mediump` default for fragment shaders.

**Comment by greggman** [comment]
> For OpenGL ES you must specify a default precision for float variables in shaders

This *NOT* true. Only fragment shaders need a default. Vertex shaders do not!!!

**Comment by solidpixel** [comment]
> This NOT true. Only fragment shaders need a default. Vertex shaders do not!!!

Heh, worked with it for years, and never noticed that one =) Thanks for the correction.
