### ISSUE TITLE
[test] Contribute more WASM SIMD intrinsics tests

### ISSUE THREAD

**Issue by Honry** [emscripten-core/emscripten#8639]
**Motivation**

We are working on WASM SIMD instrinsics testing for the purpose of comparing generated WASM bytecodes with native code to figure out inefficiency parts in WASM and provide optimization solutions to LLVM. We use [SIMD tests](https://github.com/emscripten-core/emscripten/blob/wasm-simd-intrinsics/tests/test_wasm_intrinsics_simd.c) in `wasm-simd-intrinsics` branch as start point, and plan to develop more tests to improve the test coverage. We hope these tests could also benefit emscriten testing, hence, I create this issue as a meta issue to track our test contribution and also a place to seek feedback from this community.

**Test Design**

Note: Following are initial proposals on test design, still need to be polished based on your feedback and further development practices.

- Parameter tests: covers each parameter using valid value in supported scope(can leverage Equivalence Partitioning and Boundary Value Analysis), invalid value with same type but out of range, parameter combination for the instructions, and all return codes
- Combination tests: figure out optimal instruction combinations. e.g. splat vs extract_lane, load vs store, arithmetic instructions combination, etc..
- Statement tests: testable statement, including common usage, traps, algorithm steps, and etc.. 

**Opens**
- Is that possible to write/run a trap test in current test framework? Could anyone do me a favor on this? Please forgive me as a newbie here.
- Any convention for test file naming, classification, allocation and so on? I didn't find any guidelines/documents.
- SIMD tests allocation, how about creating a folder named "simd" under `tests/wasm/`? Or maybe you have other preference?

Hi all, I'm not sure if the community would like to accept such kinds of functional tests. Please help provide your comments, very appreciate!

cc/ @tlively, @rrwinterton, @jing-bao

**Comment by tlively** [comment]
Great to see interest in making wasm SIMD better! A few thoughts:

> Parameter tests: covers each parameter using valid value in supported scope(can leverage Equivalence Partitioning and Boundary Value Analysis), invalid value with same type but out of range, parameter combination for the instructions, and all return codes

The value of doing this kind of testing for the lowering from the LLVM or C/C++ source level to WebAssembly is limited, since the lowering is very straightforward and does not have many edge cases. This testing would be very valuable to do for WebAssembly engines, though. These tests sound exactly like the spec tests we will need in order to advance the SIMD proposal toward standardization, so I suggest you focus your efforts here on implementing spec tests. That would benefit a wider community and have a larger impact than just writing this kind of test in Emscripten.

> Combination tests: figure out optimal instruction combinations. e.g. splat vs extract_lane, load vs store, arithmetic instructions combination, etc.

All these decisions are made in the LLVM WebAssembly backend. For example, we already optimize constants to use either `v128.const` or `*.splat` [here](https://github.com/llvm/llvm-project/blob/76e3a04951f9b64e5932273fe27c0a0afc547fa1/llvm/lib/Target/WebAssembly/WebAssemblyISelLowering.cpp#L1210). It would therefore be better to test these instruction selection optimizations in the LLVM repository, since emscripten is not the only project in which they are relevant.

> Statement tests: testable statement, including common usage, traps, algorithm steps, and etc.

The trap tests sound like they would belong in spec tests, but the tests of common algorithms and other uses sound like they would be a good fit for emscripten.

> Is that possible to write/run a trap test in current test framework? Could anyone do me a favor on this? Please forgive me as a newbie here.

See what `test_binaryen_trap_mode` in test_core.py does.

> Any convention for test file naming, classification, allocation and so on? I didn't find any guidelines/documents.

Usually the test input files have the same name as the test they are used in. For example, `test_wasm_builtin_simd` in test_core.py reads file tests/test_wasm_builtin_simd.c.

SIMD tests allocation, how about creating a folder named "simd" under tests/wasm/? Or maybe you have other preference?

That sounds good to me, especially if we are going to have lots of tests.

**Comment by Honry** [comment]
@tlively, many thanks for your exhaustive comments! I'll consider transferring more efforts to implement spec tests and focus only on tests of common algorithms and other uses in emscripten.

**Comment by tlively** [comment]
This was resolved and work has been steadily progressing on the spec tests.
