### ISSUE TITLE
Feature request: support minifying wasm imports with --emit-symbol-map

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#8686]
We are currently always using the `--emit-symbol-map` option, since it is convenient for debugging and profiling activities after the fact - thinking that it would not increase generated code size otherwise, if user ignores the generated `.symbols` file. However now I see that wasm imports and exports do not get minified when `--emit-symbol-map` is passed, with the code having a mention

https://github.com/emscripten-core/emscripten/blob/incoming/tools/shared.py#L2516-L2517

Would it be possible to lift this TODO?

**Comment by awtcode** [comment]
Thanks for creating this issue @juj . I have been looking at this for the past few days as well. These are my findings:
1) Removing `--emit-symbol-map` will minify the key/value pair in asmLibraryArg.
2) This will break dynamic linking because some of the internal Emscripten functions e.g. `tempDoublePtr` are needed in both the main and side module but only the main module has imports that are properly minified.

Perhaps, one solution is to add both pairings to asmLibraryArg? e.g. `tempDoublePtr:tempDoublePtr` and `a:tempDoublePtr` WDYT @kripken ?

**Comment by sbc100** [comment]
It looks like the dynamic linking issue is separate (the code is separately guarded with `if not LINKABLE`).  Perhaps for dynamic linking case we could have the SIDE_MODULE consume the symbol map of the main module so it can map the symbols its own symbols to match?   I think it would still break dlsym though.

**Comment by awtcode** [comment]
@sbc100 , I spoke with @kripken and there's a bug whereby `MAIN_MODULE=2` doesn't set the `LINKABLE` flag but I agree that this is separate from dynamic linking since metaDCE was not designed to work across modules in the first place. I will log a separate issue for this.

**Comment by kripken** [comment]
I agree the dynamic linking issue is separate. I'm not sure I fully understand it. But in general, we can't minify or dce out things that other modules might look at, which is why some optimizations, like metadce, are disabled for main and side modules. We forgot about mode 2 though, I opened #8700 for that.

@juj For the non-dynamic linking issue, yes, we should fix this. I'll take a look this week. Basically, we just need to emit the symbol map at the very end of the pipeline, after metadce, which probably means adding a new binaryen pass.

**Comment by kripken** [comment]
PR with a fix for metadce/ minifying imports, and also the wasm backend, is in #8724
