### ISSUE TITLE
Fatal: separating relocatable segments not implemented

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#8797]
Wasm backend hits an error
```
Fatal: separating relocatable segments not implemented
```
when building the proxied sockets code in PR #7672. The PR sidesteps this by skipping proxied sockets from being built by default. To reproduce, run
```
python embuilder.py build libc-sockets-proxy --pic
```
in PR branch #7672, or after it lands.

**Comment by kripken** [comment]
I believe this is a current limitation of the dynamic linking code; the problem happens from using `-s USE_PTHREADS=1 -s RELOCATABLE=1` as those two flags don't work together yet. @sbc100 and @tlively know more details, but for now we can disable building that library in relocatable mode perhaps.

**Comment by juj** [comment]
Proceeded like that - the proxying sockets code is probably not that commonly used feature, so left it out from the list of SYSTEM libraries in system_libs.py build.

**Comment by tlively** [comment]
I will take a look at this in LLD. I cannot think of why this combination shouldn't be supported off the top of my head, and I'm overdue to fix LLD to use conditional segment initialization when pthreads is enabled anyway.

**Comment by tlively** [comment]
Thanks for the ping. Will investigate tomorrow.

**Comment by tlively** [comment]
It looks like the remote branch where this issue was observed has changed so I can no longer reproduce the issue there. Testing on tip of tree by adding `-s RELOCATABLE=1` to browser.test_glgears_pthreads seems to cause some sort of issue, though. Specifically, there seems to be a deadlock or infinite loop inside `emscripten_main_thread_process_queued_calls`. Does this ring any bells for anyone?
