### ISSUE TITLE
 gl_only_in_pthread.cpp does not fade to red, but snaps to red.

### ISSUE THREAD

**Issue by ghost** [emscripten-core/emscripten#8903]
I try to run gl_only_in_pthread.cpp provided in the tests.  I compile using

`emcc -s NO_EXIT_RUNTIME=1 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=5 -s OFFSCREENCANVAS_SUPPORT=1 gl_only_in_pthread.cpp -o gl_only_in_pthread.html`

On my Chrome Browser (Version 75.0.3770.100).  I see the color does not "fade to red" but instead "snaps" to red after a small delay.

Further examining the issue I add a delay (emscripten_thread_sleep) to the main in "gl_only_in_pthread.cpp" at the every end before the return...

```
int main()
{
...
  emscripten_async_call(PollThreadExit, 0, 100);
  
  emscripten_thread_sleep(10000);
	
  return 0;
}
```

Compiling and running it again yields the same results, but the delay for the snapping to red is even longer?   The sleep however is outside of the thread, yet seems to affect it.

**Comment by kripken** [comment]
I think this is expected given the current OffscreenCanvas spec: there is no explicit `.commit()`, and instead `requestAnimationFrame()` is needed to render a frame. That testcase doesn't use `emscripten_main_loop` (which would use `requestAnimationFrame()`), so all the rendering is not seen until the very end.

**Comment by sbc100** [comment]
It this worth fixing anyway, so we document the current recommended way to do things?

**Comment by kripken** [comment]
Probably ok to fix, but we should check if the testcase isn't also being used to check things not compatible with using `requestAnimationFrame` - I'm not familiar enough with the gl code to know offhand.

**Comment by spoon-vertiv** [comment]
Ok I tried again by adding a main loop

`void main_loop()
{
	//emscripten_request_animation_frame(0, NULL);
	if (!emscripten_atomic_load_u32(&threadRunning))
	{
		printf("Test finished.\n");
#ifdef REPORT_RESULT
		REPORT_RESULT(0);
#endif
		emscripten_cancel_main_loop();
	}
}`

then in the "main" ...

`int main()
{
  ...
  emscripten_set_main_loop(main_loop, 0, 1);
  //emscripten_async_call(PollThreadExit, 0, 100);
  ...
}`

If i've read the documentation right this should call requestAnimationFrame by virtue of the "0" i'm setting on the emscripten_set_main_loop call for param 2.  After compiling I get the same thing.  Only snapping to red.   Do I have to explicity call requestAnimationFrame in the main_loop?  or was that enough?

**Comment by spoon-vertiv** [comment]
so I tried adding an explicit call to "emscripten_request_animation_frame" in case that was needed inside "main_loop" unfortunately it made no difference?   Is there some trick to it?  @kripken any further advice?

**Comment by kripken** [comment]
The main loop needs to be where the rendering is happening, so that requestAnimationFrame is used there. In that test it looks like the rendering happens in a pthread, `ThreadMain`. That pthread is written in a synchronous manner,
```
    double now = emscripten_get_now();
    while(emscripten_get_now() - now < 16) /*no-op*/;
```
which won't work on the Web. But if you use the [wasm backend with emscripten](https://v8.dev/blog/emscripten-llvm-wasm) and the [Bysyncify option](https://github.com/emscripten-core/emscripten/pull/8808), adding `-s BYSYNCIFY` to emcc, and replacing those two quoted lines with
```
    emscripten_sleep(16);
```
(with bysyncify, that synchronous-looking call becomes async), then it smoothly fades the red. Note though that this requires a bysyncify fix with pthreads that landed very recently, so you'd need very latest emscripten incoming.

Alternatively you can rewrite the `ThreadMain` function to be async, and using a main loop there, instead of bysyncify doing it for you.
