### ISSUE TITLE
Asyncify + EM_ASM + async/await

### ISSUE THREAD

**Issue by davlhd** [emscripten-core/emscripten#8991]
Hello, I want to run a function that has await inside it:

```
async function loadStuff() {
    await stuffLoading();
}
```

if I use `emscripten_run_script` its telling me that `await is only valid in async function`

```
EM_ASM(
    await loadStuff();
)
```

Gives me an `error SyntaxError: Unexpected token`

How do I call async functions?

**Comment by kripken** [comment]
I think the immediate problem here is that we emit an EM_ASM in a JS `function` (can look in the output JS to see) but it must be marked as an `async` function as that error message says.

The larger issue is that even if we marked it as such, the C code underneath it is not async, at least not unless we built with Asyncify or such. We can probably get that working together, if someone's interested to look into it.

**Comment by kripken** [comment]
Renamed, let's keep this open if someone wants to look at Asyncify + EM_ASM + await in JS.

**Comment by jrynkiew** [comment]
I tried this example from the Emscripten Asyncify documentation available here: https://emscripten.org/docs/porting/asyncify.html

In the example they use EM_JS, but turns out you can use EM_ASM just as well.

So I run this is in synchroneous single threaded C++ app.

```
 #if defined(__EMSCRIPTEN__)
EM_ASM({
                Asyncify.handleAsync(async () => {
                    let resp = await window.antenna.iotx.sendTransfer({
                        to: "io1098h946aa5us8h4fql6zptv9kjqn7cu9x9uzm0",
                        from: window.antenna.iotx.accounts[0].address,
                        value: toRau("1", "Iotx"),
                        gasLimit: "100000",
                        gasPrice: toRau("1", "Qev")
                    });
                });
            });
#endif
```

Then in the compiler flags you need to add 

`-s ASYNCIFY -s 'ASYNCIFY_IMPORTS=["emscripten_asm_const_int"]'`

I checked this, and it works. You just need to be aware that the underlying C code will need to be multi-threaded, or you need to handle worked threads in emscripten is some other way, otherwise the entire application will pause and wait for the response from the await function.

This is just an example I wrote to await a blockchain transaction approval from a soft wallet, but it should work for all other uses just as well

**Comment by RReverser** [comment]
I believe this is resolved since `Asyncify.handleAsync` was added (which was after the original issue date).
