### ISSUE TITLE
`em_asm.h` uses C++11 features (variadic templates), but is supposed to be compiled with -std=c++03

### ISSUE THREAD

**Issue by yeputons** [emscripten-core/emscripten#9053]
# Description

Currently (as of 55a9c76c89ff4f53e53dc749d063b09bb66e67b1), `<emscripten/em_asm.h>` is [included by `<emscripten/emscripten.h>`](https://github.com/emscripten-core/emscripten/blob/55a9c76c89ff4f53e53dc749d063b09bb66e67b1/system/include/emscripten/emscripten.h#L23) and [uses](https://github.com/emscripten-core/emscripten/blob/55a9c76c89ff4f53e53dc749d063b09bb66e67b1/system/include/emscripten/em_asm.h#L105-L118) C++11's variadic templates.

However, `<emscripten/emscripten.h>` is included by a bunch of tests (e.g. `test_em_asm.cpp`) which do not provide `-std=c++11` key to `emcc` and there is a special test which ensures that `emcc` compiles with `-std=c++03` by default.

**Real behavior**: tests compile and pass
**Expected behavior**: tests fail because C++11 features are used in C++03 mode

# Reason
Clang does not prohibits C++11 features in `-std=c++03` mode even with `-pedantic`, it's only a warning. Moreover, warnings are suppressed in system headers (`em_asm.h` is provided with `-isystem`) even with `-Werror`. So, Clang happily eats the header and executes it correctly (unlike [some other cases](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68209)).

# Discussion

Clang's libcxx [expects](http://libcxx.llvm.org/docs/DesignDocs/ExtendedCXX03Support.html) some C++11 features even in C++03, variadic templates are explicitly included. So maybe it's not an issue until the compiler is changed.

# Consequences

One may freely use some C++11 language features in emscripten headers, but not others: `decltype`, standard library (e.g. `<tuple>`). I'm not even sure if there are any guarantees on correctness of such usage. Specifically, that makes fixing #9030 slightly more cumbersome.

# Ideas of fixes

1. Remove C++03 support altogether (nuclear)
2. Make tests compile with C++11 (effectively the same as previous, as all bets for C++03 are off)
3. Add something like `--no-system-header-prefix` to tests so that warnings in emscripten's headers are not ignored. May be a good idea as the only warning I've got when running `emcc emscripten.h` directly was the one about variadic templates in `em_asm.h`. I was unable to make `--no-system-header-prefix` work, though.
4. Prohibit `em_asm.h` in C++03 (and possibly separate it from `emscripten.h`)
5. Add explicit support of C++03 to `em_asm.h` by replacing variadic templates with macros in C++03 mode, and keeping variadic templates in C++11.

**Comment by jgravelle-google** [comment]
> Clang does not prohibits C++11 features in -std=c++03 mode even with -pedantic, it's only a warning. Moreover, warnings are suppressed in system headers (em_asm.h is provided with -isystem) even with -Werror. So, Clang happily eats the header and executes it correctly (unlike some other cases).

Interesting, I was wondering why that worked.

However I don't see this as a problem per se. Is the problem that this is clang-specific behavior to allow some C++11 features? I cannot fathom a world in which we don't assume clang as a hard dependency for emscripten. Is it that em_asm.h is spuriously ignoring the warnings because it's included as a system header? It *is* a system-provided header though (in that emscripten is the system in this context), so it seems fine to me that it isn't a warning because the authors of the system are able to make assumptions about the system that general user code can't.

The fix ideas that I think are reasonable from a product perspective are 4 and 5. I'm relatively okay with limiting places where EM_ASM can be used (4). I'm vaguely okay with having complexity hiding behind the scenes in the system headers, where 5 is asking to re-implement EM_ASM in terms of macros in a third way. I don't think that's congruous with the statement: "Specifically, that makes fixing #9030 slightly more cumbersome.", because I think reimplementing EM_ASM as upstream-LLVM-friendly C++ macros is way more cumbersome than using an ill-defined subset of C++11 features. (I'm also not sure it's actually possible, we don't have type information in the C preprocessor and `_Generic` is a C-only feature. Though we could use macros to defer to C++ overloaded functions, or even non-C++11 templates, given that we don't need to support parameter packing in that implementation)

So, I think #9054 is a good fix, and I don't think we need to change the system header C++11 shenanigans that are currently in place.

Thank you for documenting this though, there's a lot of subtlety and clang-specific behavior that that relies on.

**Comment by yeputons** [comment]
Don't think it's a problem as long as the projects keeps with Clang and Clang does not suddenly change variadic templates in C++03 to undefined behaviour. If they change it to compilation errors, that's ok, because it can be caught.

As far as I understand, warnings in `em_asm.h` are ignored as long as one of its parent directories is passed through `-isystem` (like `emcc.py` does with `emscripten/system/include`).

**Comment by sbc100** [comment]
This the last comments here we also switched to C++11 by default to requiring C++11 for EM_ASM seems fine at this point.
