### ISSUE TITLE
Assertion failed: undefined, when running multiple EmterpreterAsync operations in parallel

### ISSUE THREAD

**Issue by aaaristo** [emscripten-core/emscripten#9083]
I've a C function foo() that uses `emscripten_idb_exists` via EmterpreterAsync, I'm compiling with the following flags:

EMFLAGS = \
	--memory-init-file 0 \
	-s RESERVED_FUNCTION_POINTERS=64 \
	-s EXPORTED_FUNCTIONS=@src/exported_functions.json \
	-s EXTRA_EXPORTED_RUNTIME_METHODS=@src/exported_runtime_methods.json \
	-s SINGLE_FILE=0 \
	-s NODEJS_CATCH_EXIT=0 \
	-s EMTERPRETIFY=1 \
	-s EMTERPRETIFY_ASYNC=1 \
	-s ASSERTIONS=1 \
	-s SAFE_HEAP=1

Whenever that function is called multiple times in a row without waiting for the promise in between calls this assertion fails:

https://github.com/emscripten-core/emscripten/blob/incoming/src/library_async.js#L380

example invocation (would like to run IO in parallel):

Promise.all([foo(), foo()]).then((results) => console.log(results))

I've a similar problem with generator functions making use of foo() after yield.

Is this a bug or a design choice? I'd like to work on it, but some context would greatly help.

**Comment by kripken** [comment]
In general, the emterpreter assumes a single "sleep" is happening at a time. I think that assertion means that another starts before the former completes. That shouldn't normally be possible since it should block the C code from continuing until the first finishes, but if you fire off multiple such sleeps from JS, that can hit the assert.

If it's not that though, then it could well be a bug.

Note that the emterpreter is deprecated, since it doesn't work in the new llvm backend. We have the new Asyncify which can do the same type of things. Would be good to see if the `emscripten_idb_exists` error exists there too, if this is a bug.

**Comment by aaaristo** [comment]
So I did the following:

1. installed the emsdk latest-upstream to use the new llvm backend 
2. export EMCC_WASM_BACKEND=1
3. rebuilt my project with the following EMFLAGS
EMFLAGS = \
	--memory-init-file 0 \
	-s RESERVED_FUNCTION_POINTERS=64 \
	-s EXPORTED_FUNCTIONS=@src/exported_functions.json \
	-s EXTRA_EXPORTED_RUNTIME_METHODS=@src/exported_runtime_methods.json \
	-s SINGLE_FILE=0 \
	-s NODEJS_CATCH_EXIT=0 \
	-s ASYNCIFY=1 \
	-s ASSERTIONS=1 \
	-s SAFE_HEAP=1

Unfortunately when I run the app now this _malloc:

https://github.com/emscripten-core/emscripten/blob/0e292986c6a1b10b3d7a0caea9b3f70d4dea3dbd/src/library_idbstore.js#L197

returns undefined on the first _emscripten_idb_load and then I get a "segmentation fault".

**Comment by aaaristo** [comment]
Forgot to mention I'm also using the following:

EMFLAGS_WASM = \
	-s WASM=1 \
	-s ALLOW_MEMORY_GROWTH=1 

EMFLAGS_DEBUG = \
	-s INLINING_LIMIT=10 \
	-g

**Comment by aaaristo** [comment]
It seems like the issue has to do with the foo() method terminating immediately even if called with the { async: true } option of ccall. Maybe my lack of knowledge about asyncify works with ccall (how one is supposed to wait for the async result).

**Comment by aaaristo** [comment]
Seems related to #9029
