### ISSUE TITLE
MINIMAL_RUNTIME and js library deps

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#9139]
@juj - Opening this for more discussion on this topic, which came up in a few issues.

E.g. I see you have `abort()` as a JS library function in the minimal runtime. That forces you to add js library `__deps` for it where it is used. That's more verbose, and more different from the non-minimal runtime, which are downsides.

I'm not sure what the benefit is, so maybe I don't understand something here. If it isn't in the js library, it will still be dce'd out by the JS optimizer, so there is no code size advantage that I can see?

**Comment by juj** [comment]
> If it isn't in the js library, it will still be dce'd out by the JS optimizer

That is the main reason: optimizing away `abort()` will require a JS optimizer pass. I think it is a weaker code assembling model to first add code in, and then use an optimizer pass to optimize things away, compared to having a strong linking model where code is introduced into the generated output when it is specifically used.

Most of the code size issues in our traditional runtime arise as a side effect/"blind side" from the fact that we rely on an after-the-fact optimization pass to make it look small. Then it kind of did not happen in all cases, and we need to use custom/special settings.js directives to indicate how DCEing of those is performed.

Having `abort()` as a JS library function also has the benefit of unifying the internal-external code boundary: depending on a JS library function from external unvisible code, vs depending on an internal runtime symbol from external unvisible code looks different; but if everything moves to being a JS library symbol, then linking is more unified, and building up dependencies is more unified.

Finally, there is also the appeal that debug builds then look more the same as release builds do, as code is introduced based on linking decision, and debug builds don't run an optimizer pass to DCE.

**Comment by kripken** [comment]
>  I think it is a weaker code assembling model to first add code in, and then use an optimizer pass to optimize things away, compared to having a strong linking model where code is introduced into the generated output when it is specifically used.

It is weaker in that sense, I agree. But it avoids the unnecessary work of adding `__deps`, and it avoids differences between the minimal and non-minimal runtimes (complexity and a source of bugs), and therefore it gives us a simpler and shorter path for progress on the minimal runtime, I think?

I do agree there is some benefit in your points, debug builds are more like release, etc. However the extra work and delay worry me more than those benefits.

My concern is also related to this comment of yours from the other issue:

> However it was too difficult to move those functions to JS library. The difference is that in MINIMAL_RUNTIME, there is no "untracked" JS runtime code depends on these, but in traditional runtime, there is JS code in the runtime files that call into these functions, making it infeasible to also directly move these to become JS library functions in traditional runtime, without more detailed refactor.

If we want the minimal runtime to eventually replace the default one, we must eventually do all that work, don't we? That's what worries me.

If the benefits were major, I'd say we should do the work. But as the benefits don't help release builds, I am skeptical it is worth it.

There may be more than one way to avoid that work. The obvious way is to not use a different deps mechanism between the two runtimes. Another is maybe we can get rid of `__deps` from JS library files entirely. We could compute the deps offline (once every time the JS library changes), by scanning the JS in js library functions and seeing which things are not in scope. Then we'd emit a single big autogenerated file that contains the computed `__deps`.

**Comment by juj** [comment]
> If we want the minimal runtime to eventually replace the default one, we must eventually do all that work, don't we?

Eventually we would just deprecate and delete the traditional runtime, so we would be able to avoid the work. I think that is the better way to migrate users (both ways keep working, break everything when you switch over), instead of introducing a series of small breakages as one-off disrupting refactors would be done to traditional runtime.

> But it avoids the unnecessary work of adding `__deps`

I don't think it is unnecessary work, but desirable work.

> Another is maybe we can get rid of `__deps` from JS library files entirely. We could compute the deps ...

I think that is orthogonal to the question at hand - moving to autoparsed deps can be a great thing (although it will then lead to having to declare externs when code refers to things that are not visible to the parser/linker, but perhaps there are fewer of those)

> it gives us a simpler and shorter path for progress on the minimal runtime, I think?

> the extra work and delay worry me more than those benefits.

I don't know how else to make progress - the whole point of MINIMAL_RUNTIME has been to avoid introducing bloat in the preamble code by basing the runtime on the explicit linking model, and I don't like to give up with that and start doing lax mode now. I have already done the work of specifically modelling the dependencies - going back and doing something else would cause more extra work and delay?

> If the benefits were major, I'd say we should do the work. But as the benefits don't help release builds, I am skeptical it is worth it.

In my view MINIMAL_RUNTIME is the iteration of the runtime "done right", i.e. having Emscripten be as close to a generic JS<->C/C++ code linker without special functionality in a monolithic/inseparable runtime JS code block, but instead the JS libraries make up the runtime using the same model as how users add in their own JS code.

I don't see explicitly having to mark in the __deps to be a problem at all, but the opposite - that should be the desired way to architect JS code. An automatic deps parser can give some nice conveniences, but not really needed even.

Ultimately, there aren't event that many places where MINIMAL_RUNTIME-specific __deps are added, and even when there are, the code seems uncomplicating to me. It is not that there would be a running tally of ever-growing MINIMAL_RUNTIME-specific deps, but instead, there are a constant number of those that old preamble.js/support.js/postamble.js had, most of which have already been covered. I think multithreading brings in a few more, but not really a massive change.

**Comment by kripken** [comment]
Thanks, I see. Ok, this sounds good to me. I do agree this is a nicer design, I just worry that the amount of work adds delay and risk. But if you are willing to do this work then that's good.

Good point that the number of places with `MINIMAL_RUNTIME`-specific `__deps` probably won't be that extensive, too.

Agreed automatic deps could be an orthogonal issue.

> I think that is the better way to migrate users (both ways keep working, break everything when you switch over), instead of introducing a series of small breakages as one-off disrupting refactors would be done to traditional runtime.

I'd say there are advantages both ways. I think we have good experience with doing the other approach carefully, though, like the gradual removing of default runtime exports from `EXPORTED_RUNTIME_METHODS`, which could in theory cause disrupting refactors, but with lots of helpful error messages ("this is what broke, do this to fix it", for users) I think we got through that well. I'm doing something similar now with `INCOMING_MODULE_JS_API` which changes internal/undocumented APIs, also very carefully.

But yes, I agree your approach may be better for something like a new runtime, and sounds good to continue! :)
