### ISSUE TITLE
libjpeg

### ISSUE THREAD

**Issue by ThorstenBux** [emscripten-core/emscripten#9170]
Hi release notes state that libJPEG is not precompiled
```
v1.38.31: 04/24/2019
--------------------
 - Change ino_t/off_t to 64-bits. (#8467)
 - Add port for bzip2 library (`libbz2.a`). (#8349)
 - Add port for libjpeg library. (#8361)
```

but I can't find it on https://github.com/emscripten-ports. Can you please tell me how to use it.

Thank you

**Comment by kbumsik** [comment]
Most of ports are maintained in the source here: https://github.com/emscripten-core/emscripten/blob/incoming/tools/ports . You can see the [libjpeg port](https://github.com/emscripten-core/emscripten/blob/incoming/tools/ports/libjpeg.py) here.
AFAIK https://github.com/emscripten-ports host only libraries that require significant modifications in order to work in Emscripten.

**Comment by ThorstenBux** [comment]
Thanks, do you know how to integrate that into a cmake build ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
