### ISSUE TITLE
Using of WebGL2 "3.10 es" context?

### ISSUE THREAD

**Issue by remoe** [emscripten-core/emscripten#9276]
Does anyone know how to create a WebGL2-compute "3.10 es" context with latest emscripten/SDL2? And is it possible to use the "GL_EXT_shader_io_blocks" extension with it?

Sorry, I'm new with WebGL/emscripten, thanks.

**Comment by hujiajie** [comment]
@remoe Thanks for your interest in webgl2-compute! Currently the feature is maintained as a fork based on Emscripten v1.38.39, so it may be a little inconvenient to try this with [emsdk](https://emscripten.org/docs/getting_started/downloads.html). Please take a look at the following:

```bash
git clone -b webgl2-compute https://github.com/hujiajie/emscripten.git
# install emsdk
# ...
# install and activate SDK tools
./emsdk install 1.38.39
./emsdk activate 1.38.39
source ./emsdk_env.sh
export PATH=/path/to/emscripten:$PATH
```

For webgl2-compute, you should pass `-s USE_WEBGL2_COMPUTE=1` to `emcc`/`em++`. Unfortunately SDL2 cannot work with webgl2-compute yet. The main gap is that SDL2 requires `EGL_KHR_create_context` to create an OpenGL ES 3.1 context, but Emscripten does not provide emulation for this EGL extension at the moment. Also, I'm afraid you cannot use `GL_EXT_shader_io_blocks` because this extension is not supported by browsers.

Note: webgl2-compute is an experimental feature in Chrome behind flags (`--use-gl=angle --use-cmd-decoder=passthrough --enable-webgl2-compute-context`).

**Comment by remoe** [comment]
@hujiajie, thanks for this detailed explanation! I've tried it without emsdk. I found this branch doesn't use latest master of LLVM 10.0 (it use 9.0). But my current build stack use 10.0. For my current test I need ```GL_EXT_shader_io_blocks``` , so it's not possible to do this test.

**Comment by hujiajie** [comment]
> I found this branch doesn't use latest master of LLVM 10.0 (it use 9.0).

True. I think LLVM 10.0 is used since Emscripten 1.38.40 and I happen to be working on an upgrade. The SDL2 limitation also sounds important to me, and I believe it's not quite hard to solve, though there isn't an ETA yet. `GL_EXT_shader_io_blocks` is the real pity.
