### ISSUE TITLE
Definining dlmalloc (or other dl symbol) in user code can interfere with allocator.

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#9337]
The following code will abort in the default emscripten build config.

```
#include <malloc.h>
#include <stdlib.h>
#include <stdio.h>

void *dlmalloc(size_t s) {
  abort();
}

int main() {
  printf("in main\n");
  void *y = memalign(4, 8);
  printf("%p\n", y);
}
```

This is because `system/lib/dlmalloc.c` weakly defines the dlxxxx symbols.  This means that user code can interfere with dlmalloc in ways that it probably shouldn't.

Possible solutions:
1. Use the normal malloc/free etc names in dlmalloc.c rather than having them be weak aliases to the dl-prefixed functions.
2. Make the dl* functions in dlmalloc.c static so they are not visible outside the file.

(1) is probably better, bug could have side-effects I'm currently no aware of since the original author probably had a reason for using aliases.

(2) Seems to work fine, and we could land that change but (1) would reduce the number hacks.

**Comment by juj** [comment]
Hmm, why is this something that needed solving? Users can override the malloc implementation the way they choose, and the intent is also then that Emscripten built-in code that needs to dynamically allocate will then use the user-provided malloc implementation (rather e.g. than having two copies of a malloc implementation generated in the code).

In the provided code snippet, the problem is on the line
```c
void *dlmalloc(size_t s) {
  abort();
}
```
User wrote an aborting malloc, and got an aborting malloc? Works as expected?

If the issue is just with the names, i.e. user would like to use Emscripten provided dlmalloc for system allocation, and still also bundle a copy of dlmalloc to their own code, and use dlmalloc's memory arenas feature to localize/silo allocations, and the concern is in conflicting symbol names there - we could then just change the default dlmalloc prefix from `dl` to `emscripten_dl` or something like that?

**Comment by juj** [comment]
It is also worth mentioning that a valid way to implement custom malloc and free is to back to system dlmalloc and dlfree, e.g.

```c
void *malloc(size_t sz)
{
   void *ptr = dlmalloc(sz); // Get dlmalloc provided by emscripten
   my_custom_malloc_tracer(ptr, sz);
   return ptr;
}
void free(void *ptr)
{
  my_custom_free_tracer(ptr);
  dlfree(ptr);
}
```
i.e. to inject in-between.

Not sure if we had tests for such use. Although for that use, we can also require to lean on `emscripten_dlmalloc` and `emscripten_dlfree`, though just having the default `dlmalloc` and `dlfree` have been fine.

**Comment by sbc100** [comment]
My understanding is that the valid way to override malloc and free in emscripten is:

```
void *malloc(size_t sz)
{
   void *ptr = emscripten_builtin_malloc(sz); // Get dlmalloc provided by emscripten
   my_custom_malloc_tracer(ptr, sz);
   return ptr;
}
void free(void *ptr)
{
  my_custom_free_tracer(ptr);
 emscripten_builtin_free (ptr);
}
```

This use case is still value and works for various emscripten mallocs.

**Comment by sbc100** [comment]
I thought that was why we have emscripten_builtin_malloc and emscripten_builtin_free?

To explain the exact failure case we were seeing:  We have an internal customer use is using dlmalloc as a library themselves (I don't know exactly why).  The don't wan to override the system allocator though.   My understanding is that the dl prefixes are designed to be used when dlmalloc is library, and not used when its acting as the system allocator.

**Comment by sbc100** [comment]
From dlmalloc.c:  ```Add 'USE_DL_PREFIX' to quickly allow co-existence with existing               
 memory allocation routines.```

Our users are defining USE_DL_PREFIX for exactly this reason but there were interfering with emscripten's existing memory allocation routines.

Simply internalizing emscripten's internal symbols fixed the issue although not using the prefixes at is is probably a more correct solution (nut I ran into issues with faspcomp trying that).

Since we already have emscripten_builtin_malloc for the purpose of calling the system allocator when overiding malloc it seemed like a good solution.
