### ISSUE TITLE
 __syscall337 // recvmmsg: it always returns 0, meaning EOF.

### ISSUE THREAD

**Issue by socketpair** [emscripten-core/emscripten#9339]

**Comment by socketpair** [comment]
!

**Comment by sbc100** [comment]
Emscripten doesn't support sockets out of the box because the web platforms doesn't.

See https://emscripten.org/docs/porting/networking.html

Here is the code for recvmsg:

https://github.com/emscripten-core/emscripten/blob/fa91e13b25fbe7146651ad9303b1cdcc2ff05b2c/src/library_syscall.js#L1435

You can define `-s PROXY_POSIX_SOCKETS` to get a kind of socket support via WebSockets, but you even in that mode we don't support recvmsg as far as I can tell.

**Comment by socketpair** [comment]
So if you don't support the syscall, it must return -1 and EOPNOTSUPP error

**Comment by sbc100** [comment]
As of #14491 I believe we now consistently return ENOSYS for all unimplemented syscalls including this one.

Assuming that is correct (The man page says `ENOSYS          Function not implemented (POSIX.1-2001).`) then I think this issue can be closed?

**Comment by socketpair** [comment]
The issue is very old. I did not check. If it really returns -1, yes, please close.
