### ISSUE TITLE
Link failure with `-fno-exceptions` and `-s DISABLE_EXCEPTION_CATCHING=1`

### ISSUE THREAD

**Issue by dschuff** [emscripten-core/emscripten#9361]
#3953 reported a link failure when `-fno-exceptions` is in use (along with the default of `-s DISABLE_EXCEPTION_CATCHING=1`): undefined references to `__cxa_uncaught_exception` (and possibly `__cxa_uncaught_exceptions` and `__cxa_begin_catch` are being generated somehow. IIRC we don't have great testing for `-fno-exceptions`.

**Comment by kripken** [comment]
I did a run of our test suite with `-fno-exceptions` added whenever exceptions were not explicitly enabled (so, pretty much everywhere). I didn't see any unexpected failures.

@evanw maybe you can provide a testcase for that error?

**Comment by evanw** [comment]
I just manually combed through the binary WebAssembly output from the successful build I did in #3953 with the three __cxa abort stubs. I used the node REPL and [@webassemblyjs/wasm-parser](https://www.npmjs.com/package/@webassemblyjs/wasm-parser).

It appears that `std::uncaught_exception()` is only called in a single place, which is from inside `std::__2::basic_ostream<char, std::__2::char_traits<char> >::sentry::~sentry()`. With that, I'm able to get a reliable repro. Here it is:

1. Make a file called `main.cpp` containing this code:

```c++
#include <iostream>

int main() {
  std::cout << 1.23f << std::endl;
  return 0;
}
```

2. Build it using -fno-exceptions.

The build fails due to an error about the symbol `__cxa_uncaught_exceptions` being undefined:

```
$ emcc main.cpp -fno-exceptions 
error: undefined symbol: __cxa_uncaught_exceptions
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
Error: Aborting compilation due to previous errors
```

**Comment by kripken** [comment]
Thanks @evanw!

Looking into this, it seems like some code in libc++ uses exceptions but is not behind `_LIBCPP_NO_EXCEPTIONS`, for example in `future` there is code that uses `std::exception_ptr` like [`set_exception_at_thread_exit`](https://github.com/llvm-mirror/libcxx/blob/958c9be283fdb26b6a293d93c8be51bd43e1f2df/src/future.cpp#L251).

I'm not sure if that's ok or not - maybe we should not assume that `-fno-exceptions` actually prevents any exceptions code from being added?

**Comment by evanw** [comment]
Ah, interesting. So it sounds like calling abort() when these functions are hit is a reasonable workaround for now?

**Comment by kripken** [comment]
`abort()` when they are called is probably a reasonable workaround, yeah. I hope we can understand the underlying issue though, maybe someone else here knows more about c++ stdlib internals / the c++ spec.

**Comment by sbc100** [comment]
I'd like to get the bottom of this too.   

Adding __cxa_uncaught_exceptions to `src/library_exceptions_stub.js` certainly seems like a good step and will turn this into a compile time error.

Then we just need to figure out why the error is happening ..
