### ISSUE TITLE
Incorrect or potentially confusing behavior when using Asyncify

### ISSUE THREAD

**Issue by jgautier** [emscripten-core/emscripten#9401]
I am not sure if this is an issue or just confusing behavior with asyncify.  Given the following program

```
// example.c
#include <emscripten.h>
#include <stdio.h>

EM_JS(void, do_timeout, (), {
  out("starting sleeping");
  Asyncify.handleSleep(function(wakeUp) {
    out("waiting for timeout");
    setTimeout(function () {
      out("got the timeeout");
      wakeUp();
    }, 500)
  });
});

void do_thing () {
  puts("before");
  do_timeout();
  puts("after");
}

EM_JS(void, do_thing_js, (), {
  console.log("doing thing");
  const doThing = cwrap('do_thing', null, [], { async: true });
  doThing().then(() => {
    console.log('done');
  });
})

int main() {
  do_thing_js();
}
```

Compiled with 
```
emcc example.c -O0 -o a.html -s ASYNCIFY -s 'ASYNCIFY_IMPORTS=["do_timeout"]' -s 'EXPORTED_FUNCTIONS=["_do_thing", "_main"]'
```
I would expect the output to be
```
doing thing
before
starting sleeping
waiting for timeout
got the timeeout response
after
done
```

But I see
```
doing thing
before
starting sleeping
waiting for timeout
got the timeeout response
doing thing
starting sleeping
after
done
done
```

Seems like some things are being called twice?

If I change the program to this
```
// example.c
#include <emscripten.h>
#include <stdio.h>

EM_JS(void, do_timeout, (), {
  out("starting sleeping");
  Asyncify.handleSleep(function(wakeUp) {
    out("waiting for timeout");
    setTimeout(function () {
      out("got the timeeout");
      wakeUp();
    }, 500)
  });
});

void do_thing () {
  puts("before");
  do_timeout();
  puts("after");
}

EM_JS(void, do_thing_js, (), {
  Asyncify.handleSleep((wakeUp) => {
    console.log("doing thing");
    const doThing = cwrap('do_thing', null, [], { async: true });
    doThing().then(() => {
      console.log('done');
    });
  })
})

int main() {
  do_thing_js();
}
```

It seems to work as expected. Notice the `Asyncify.handleSleep` inside of `do_thing_js`.  Is this expected behavior? Do we need to wrap asynchronous ccalls with `Asyncify.handleSleep`? Does the working example not violate having nested asyncify calls? Happy to help fix or update documentation as needed.

**Comment by AjayP13** [comment]
This likely has to do with the fact that you are calling a `cwrap`ed function from within a C function instead of from JavaScript. i.e. the calling chain looks like

(JavaScript context) → (WASM context) → `main` → (JavaScript context) → `do_thing_js` → (WASM context) → `do_thing` →  (JavaScript context)  → `do_timeout`

I believe this is caused by the fact that we are stepping into `→ (WASM context)` twice, which is generally unsafe to do (?) since we don't allow concurrent execution of WASM functions.

**Comment by AjayP13** [comment]
Normally, you would be warned if you do this by this `assert` statement:

https://github.com/emscripten-core/emscripten/blob/34a0be62d6a10148f80f1d310a4cc222c8c4160d/src/preamble.js#L146

However, it is not being triggered since we use `Asyncify.currData` to detect if asynchronous execution is happening and `currData` is set *after* (L681):
https://github.com/emscripten-core/emscripten/blob/e242e539280f71dce29087668d3ddfcf4cd2db7f/src/library_async.js#L681

the `startAsync` function parameter of `handleSleep` gets called (L651):
https://github.com/emscripten-core/emscripten/blob/e242e539280f71dce29087668d3ddfcf4cd2db7f/src/library_async.js#L651

Unfortunately, I don't think there is any way to tell if there is going to be asynchronous execution earlier since the code is calling `startAsync` and using whether the callback is reached immediately as indication of whether something "truly asynchronous" happened like a `setTimeout`. This means it would be hard to implement an `assert` warning for this case. The only thing I can think of here is to somehow detect if a `cwrap` is used inside a `handleSleep` just for the purposes of `assert`-ing a warning which seems janky or just document it somewhere.

**Comment by jgautier** [comment]
Thanks @AjayP13 for the detailed write up.  I think I'll submit a PR to document this.
