### ISSUE TITLE
Dynamic ASYNCIFY_STACK_SIZE

### ISSUE THREAD

**Issue by AjayP13** [emscripten-core/emscripten#9556]
I ran into needing to increase `ASYNCIFY_STACK_SIZE`, but I don't necessarily know ahead of time how much space the stack needs, and I don't want to over-allocate memory by setting a large value.

I was able to fix this in my code by measuring the stack and dynamically changing it:

```c
void* _stack_start;

void EMSCRIPTEN_KEEPALIVE exported_func() {
    void* p = NULL;
    _stack_start = (void*)&p;
    do_stuff();
}

EM_JS(void, set_asyncify_stack_size, (int size), {
  Asyncify.StackSize = size;
});

void set_stack_and_sleep(long time) {
    void* p = NULL;
    void* _stack_end = (void*)&p;
    size_t calculated = (_stack_start-_stack_end); // Approximate stack size
    set_asyncify_stack_size(calculated + 4096); // Some extra space for good measure (4096)
    emscripten_sleep(time);
}

void do_stuff() {
    ... // Do some stuff that will increase the stack size greatly
   set_stack_and_sleep(1000);
    ...
}
```
This fixed it for me, but it's a little hacky. I'm measuring the stack size at runtime using the addresses of two stack variables: one near the beginning of execution and the other right before the sleep.

I believe something like this could be implemented into emscripten directly, but I'm not even sure I'm measuring the amount right since its unclear as to what is being stored in `ASYNCIFY_STACK_SIZE`. I presume it's just anything on the stack + some metadata. Perhaps there's a better way of measuring the stack than this sort of instrumentation.

**Comment by kripken** [comment]
I think that code measures the C stack, and uses it as an estimate of the Asyncify stack. There might be a connection between the two, but only a correlation on average, since it's possible for one to be very large and the other small (or even zero - like many wasm locals but no C stack usage at all).

In general, it's impossible to know the necessary stack size (C or Asyncify) due to recursion. But if we ignore recursion, we could inspect the binary and add up all the asyncify stack sizes to get an upper limit. That would be a big over-estimate, though, if there are many functions.

**Comment by AjayP13** [comment]
I see, that makes sense, my method does seem like it's consistently over-estimating the WASM stack size (as I can reduce it by a little bit and it will still work without crashing), but it is positively correlated as it hasn't seemed to crash yet. I guess it wouldn't be tenable to add to emscripten if there isn't a good way to measure the stack. 

There might be another way though. The other thing I played around with was modifying `library_async.js`. I increased the buffer by 4 bytes and added a random 32-bit value (a [stack canary](https://en.wikipedia.org/wiki/Stack_buffer_overflow#Stack_canaries) at the end of the buffer. If `asyncify_start_unwind` overflowed the buffer, you would be able to detect it by seeing if the canary value at the end of the buffer was overwritten. This worked well, I was able to detect when the buffer "overflowed" and thus the ASYNC_STACK_SIZE needed to be increase.

Perhaps, with the canary approach, we could re-`_malloc()` a new buffer with twice the space and retry the `asyncify_start_unwind` operation? If it overflows again, then double the space of the buffer again, and again, and again, until it succeeds (or memory runs out I guess).

**Comment by kripken** [comment]
Some form of stack growth could work in principle, yeah. I think it can work even without a canary, as the asyncify data structure knows where the stack begins and ends, and it asserts on that after it finishes unwinding. It could check during unwinding as well, and invoke growth if necessary.

But that would require some changes to the current model - right now, the asyncify API isn't aware of allocation at all, it gets the buffer and just uses it. It would need to know how to call malloc or such. A second downside is that this would also add overhead due to extra checks.

However, if we really need this I'm not opposed. I'm curious though, can you not just allocate say 64K or some other large amount? What size stacks do you need in practice?

**Comment by AjayP13** [comment]
Ah, the problem is I'm compiling CPython for general purpose use. As it turns out, as a Python program's stack grows, the C stack grows, thus the WASM stack grows. Since I don't know what Python scripts someone will run, I don't know what to pre-allocate (since some Python scripts might use very little stack, some use a lot). 

I could pre-allocate a large chunk, but that seems not great for this purpose, it would be nice if it could be flexible within the entire space from zero to the `TOTAL_MEMORY` of the WebAssembly memory.

It's not really a problem for me anymore since the above hack works for CPython (presumably, I haven't seen anymore crashes), but yeah making the `asyncify_*` functions aware of allocation and letting it allocate the proper size buffer would be a nice solution, I presume that would have to be done on `binaryen` though.

**Comment by kripken** [comment]
I see, yeah, if it's running user scripts you haven't seen, it could be arbitrarily deeply nested...

A simple thing we can do is to check the stack depth (getting a JS stack trace and seeing how many lines it has), then multiplying by a factor (which should probably be a param; asyncify could emit that as metadata actually).

**Comment by AjayP13** [comment]
That could work, although the JS stack is a [non-standard property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack) so it could break in the future (although, unlikely) / might not work in obscure JS engines. 

Alternatively, if [Asyncify.cpp](https://github.com/WebAssembly/binaryen/blob/fb217c80c6d9c4b52d90571c435fc52dc868df47/src/passes/Asyncify.cpp) has knowledge of the total size needed, could we just implement a function there called `asyncify_get_stack_size(data : i32)` and call it in `library_async.js` via `Module['_asyncify_get_stack_size'](<int pointer address>)`  and then call `_malloc(<value of int pointer>)` to allocate the proper size?

**Comment by kripken** [comment]
Asyncify can only estimate how much a single function needs. We need to multiply that by the number of functions on the call stack, which we can only tell at runtime. (Unless there is no recursion and the compiler can figure out the maximum call stack at compile time...)

**Comment by AjayP13** [comment]
I see, then I think using `((new Error()).stack)` and counting the lines and then multiplying should work, it's non-standard but support on nearly every major JS engine. We could also have a fallback by keeping the `ASYNCIFY_STACK_SIZE` setting and making it a lower bound on the memory allocated, so that people can still control it for environments where `((new Error()).stack)`  might not work.

I can work on a PR for the changes on the `emscripten` side, but don't think I'm familiar enough with `Asyncify.cpp` to know where to calculate the multiplying factor from though.

**Comment by kripken** [comment]
Thanks! Emscripten PR would be great.

For the Asyncify side, I actually had an idea for how to do it without changes there. They key thing is the number of locals in each function. Running `wasm-opt --func-metrics` on a wasm file prints out a line with `[vars]    : X` that has the number. So we could have a python script that runs that and generates an estimate. The user may be able to do better than the naive maximum, btw, since some huge functions may be known to not be recursive, so I'm not sure what the UI for that should be...

**Comment by AjayP13** [comment]
I suppose the user could narrow it down with ASYNCIFY_WHITELIST and we only look at the maximum of the functions in the whitelist if it's specified.

We could also keep around the ASYNC_STACK_SIZE setting and make it so that if it is 0 it auto-allocates and if it is > 0 it does the old behavior.

**Comment by kripken** [comment]
Yeah, I think we definitely want to keep around the old behavior. This might be an extra option.
