### ISSUE TITLE
Using pthreads and dynamic linking?

### ISSUE THREAD

**Issue by bplevin36** [emscripten-core/emscripten#9582]
I have a project that is blocked by the mutual exclusivity of pthreads and dlopen support.  Is there any documentation or test coverage anywhere giving an indication of why these options create so much trouble if you try to use them together?  #3494 was all I could find.

I've also tried to circumvent the need for native dlopen in my project by spoofing it with generated code creating data structures of function pointers and statically linking the libraries, but I cannot find any combination of link flags that doesn't result in DCE removing all the functions I try to address (at least that's what the debug tables appear to show).  Maybe there's something there I'm missing as well.

**Comment by sbc100** [comment]
I reopened #3494 since this still isn't fixed AFAIK.  Can we close this in favor of that one?

On your specific issue it sounds like you are trying to eliminate the use of dlopen from your project which is probably you fastest way to success.   Dynamic linking in emscripten is kind of pain and should only be used by those who really need it.  For example it has both a code size and a runtime impact.    In your case you probably have function pointer in your main application that are intially set to null and  then get filled in by dlopen at runtime?  To ensure the functions from the DLL are being included in the main program I would recomment insuring that those function pointer are *not* compiled in.  that will force the linker to look for a definition elsewhere and pull in the code form the other library.

**Comment by bplevin36** [comment]
I can close this, but I was hoping to gain some additional understanding about how Emscripten handles function pointers.  The WebAssembly spec says one thing, but it is implied that Emscripten handles them differently, which seems to be further complicated by the fastcomp/upstream division.  Is there any more information on this anywhere?

**Comment by sbc100** [comment]
In general, and especially for static linking, function pointers should be handled in the same way for both fastcomp and the llvm backend.

If you take the address of a function an store it in a static data structure that should result in that function being included at link time, and not DCE'd  (as long as the data structure itself is not DCE'd).  Undefined symbols are not allowed by default so you will see a linker error if the symbol in question is missing.  Can you dump the contents of the data structure in question to see what the linker is filling it with?

**Comment by jbkempf** [comment]
We are in the same situation, where we are blocked by this issue.

**Comment by kripken** [comment]
Yes, let's close this in favor of the original issue.
