### ISSUE TITLE
How to monitor wasm memory? (abort with cannot enlarge memory arrays)

### ISSUE THREAD

**Issue by bsoy** [emscripten-core/emscripten#9599]
Hi,

I'm using pthreads + fixed memory that's automatically initialized in JS glue code.
My code process and display images repeatedly, and will abort with 'cannot enlarge memory arrays to size * bytes' when the number of images that has been processed or the image zoom-in factor reach to centain value. However I didn't find any piece of memory that I malloced in JS for a image but not be freed.. 

In Chrome, the heap snapshot only shows the entire 512MB that reserved for wasm; in Firefox, it shows that the SharedArrayBuffer is always about 50MB before abort (as the pic below shows). 
Is there any way to monitor the wasm memory, so I can check how much memory that is currently used and then debug my code?
![image](https://user-images.githubusercontent.com/4518254/66387381-6a877680-e9f6-11e9-855b-e83abbe9ea0d.png)

Thanks a lot for any help in advance!

- Emscripten version: 1.38.39
- Stack trace:
```sh
abort@http://localhost:3000/render.js:9535:44
abortOnCannotGrowMemory@http://localhost:3000/render.js:6947:7
_emscripten_resize_heap@http://localhost:3000/render.js:6949:7
_sbrk@http://localhost:3000/render.wasm:wasm-function[6904]:0x3379d6
_malloc@http://localhost:3000/render.wasm:wasm-function[6400]:0x313ef2
_internal_memalign@http://localhost:3000/render.wasm:wasm-function[6407]:0x316d3d
_memalign@http://localhost:3000/render.wasm:wasm-function[6406]:0x316ccd
Module._memalign@http://localhost:3000/render.js:8713:37
__emscripten_syscall_mmap2@http://localhost:3000/render.js:5541:15
___syscall192@http://localhost:3000/render.js:5560:14
_emscripten_receive_on_main_thread_js@http://localhost:3000/render.js:5989:19
__do_call@http://localhost:3000/render.wasm:wasm-function[6444]:0x318540
_emscripten_current_thread_process_queued_calls@http://localhost:3000/render.wasm:wasm-function[6412]:0x317430
_emscripten_main_thread_process_queued_calls@http://localhost:3000/render.wasm:wasm-function[6414]:0x3174bc
Module._emscripten_main_thread_process_queued_calls@http://localhost:3000/render.js:8587:72
allocateUnusedWorkers/</worker.onmessage@http://localhost:3000/render.js:2098:17
```

**Comment by kripken** [comment]
You can use standard C things like [mallinfo](http://man7.org/linux/man-pages/man3/mallinfo.3.html). Emscripten also has special profiling tools (`--memoryprofiler`), see https://github.com/emscripten-core/emscripten/issues/8082 and the discussion there.

**Comment by bsoy** [comment]
@kripken Thanks! I've tried --memoryprofiler. It categorizes memory allocations by the code location where the memory is allocated. That is useful. It shows there's a trace item that doesn't start from my code but the _emscripten_receive_on_main_thread_js. I'm wondering whether it means that my memory problem is related to the multithreading. And where can I find more details about memoryprofiler, such as when it updates the alloc count?

Besides, could you make the profiler div fixed or floated on the webpage so that it'll not disappear when I scroll?

**Comment by kripken** [comment]
I'm not that familiar with the memoryprofiler code myself. Might have to just read the code to see, if the docs aren't enough. (And hopefully it's not hard to change the div as you want, but I don't know myself.)

That a trace includes `_emscripten_receive_on_main_thread_js` means proxying is involved, but the question is probably what is proxied. The code called from that method should help figure that out, what is it?

**Comment by bsoy** [comment]
@kripken Yeah it's easy to change the div myself, thank you. 
The trace item that relates to the unintended memory allocations is:
```sh
28.7 MB/13 allocs: at _malloc (wasm-function[7158]:0x34184f)
at _internal_memalign (wasm-function[7165]:0x34339e)
at _memalign (wasm-function[7164]:0x34332e)
at Module._memalign (http://localhost:3000/render.js:8518:37)
at __emscripten_syscall_mmap2 (http://localhost:3000/render.js:5954:15)
at ___syscall192 (http://localhost:3000/render.js:5973:14)
at _emscripten_receive_on_main_thread_js (http://localhost:3000/render.js:6444:19)
```
The C++ code that I compile to wasm includes an external library, which is quite complex and uses multithreading and runs stably in native app. I'm not so familiar with details in it, and not sure where to debug.. it'll be very appreciated if you give me any clue.

***
Another problem in my scenario is that I got errors when (perhaps I should open another issue for this..)
- use automatically-generated instance of my wasm module in web worker, or
- compile with MODULARIZE=1 and use MyModule() in worker

The basic compile options I'm using:
```sh
-Os -s WASM=1 -s USE_ZLIB=1 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=4 -s SAFE_HEAP=1 -s TOTAL_MEMORY=512MB
```
The errors are as follow in both cases.
```sh
render.worker.js:208 worker.js onmessage() captured an uncaught exception: TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
onmessage @ render.worker.js:208
render.worker.js:208 worker.js onmessage() captured an uncaught exception: TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
onmessage @ render.worker.js:208
render.worker.js:209 TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at onmessage (render.worker.js:126)
onmessage @ render.worker.js:209
render.worker.js:52 Pthread 0 uncaught exception in http://localhost:3000/render.worker.js:126:29: Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.. Error object:
(anonymous) @ render.worker.js:52
error (async)
(anonymous) @ render.worker.js:48
render.worker.js:53 TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at onmessage (render.worker.js:126)
(anonymous) @ render.worker.js:53
error (async)
(anonymous) @ render.worker.js:48
render.js:2281 pthread sent an error! http://localhost:3000/render.worker.js:126: Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
```
Then if I try to instantiate wasm module by myself, it always throws TypeError.
```sh
Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #141 module="global" error: module is not an object or function
```
The importObject:
```sh
let importObject = {
    env: {
        '__memory_base': 0,
        'memory': memory,
        '__table_base': 0,
        'table': new WebAssembly.Table({
            initial: 256,
            maximum: 256,
            element: 'anyfunc'
        }),
        'STACKTOP': 0,
        'STACK_MAX': memory.buffer.byteLength,
        'abortStackOverflow': _ => {
            throw new Error('overflow');
        },
        'abort': _ => {
            throw new Error('aborted');
        },
    }
}
```
Seems the importObject is still not correct.. could you tell me how to set the importObject right?

**Comment by bsoy** [comment]
@kripken  Could you please help me to figure them out?? Thanks

**Comment by kripken** [comment]
Why are you creating your own import object? Are you writing your own JS instead of emscripten's? If so, see https://github.com/emscripten-core/emscripten/wiki/WebAssembly-Standalone

**Comment by bsoy** [comment]
@kripken As said in my last reply, I'd like to use wasm instance in web worker, however got 'createObjectURL' error when using the automatically-generated one with both two methods (maybe there's something about file path needed to pay attention to when using worker?)

So I turned to instantiate wasm module by myself, but got the TypeError. I had read your standalone example, and my importObject referred to it. The SIDE_MODULE=1 cannot work with USE_PTHREADS>0 so I didn't add the option, just output .wasm instead of .js


Besides, any clues about the memory allocation? Thanks

**Comment by kripken** [comment]
Not sure what that createObjectURL error could be, it doesn't sound like a known issue. Please try to provide a reproducing testcase so we can debug and fix it.

Not sure what 
```
Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #141 module="global" error: module is not an object or function
```
means. Disassembling the wasm file and looking for the 141-th import might help understand.

**Comment by sbc100** [comment]
If you want to use emscripten output we have the `--proxy-to-worker` flag that is supposed to do that for you.

Trying to build a JS loader that loads the emscripten-generated wasm file is a lot more work, and something that will require you to learn a lot about the internals of emscripten.  The ABI is also not stable so your code is liable to break with each emscripten release.

**Comment by DebaoD** [comment]
Hi @kripken, regarding memoryprofiler.js, I tried to print logs in onMalloc()/onFree() callback so we can locate a memory leak issue. It works well when we allocate memory in main thread. But onMalloc() is not invoked if we allocate memory in a sub-thread in C++ code. Do you know why? Is there anything special to allocate memory in a C++ sub-thread? 

Here is the code snippet to test this:

void *thread_func(void *arg) {
		int i=0;
		while(1) {
			if (i==0) {
				void* p = malloc(41943040);  // onMalloc() is not invoked.
				LOGI("in sub thread. malloc. new address=", (int)p);
				i++;
			}
			usleep(2000000);
			LOGI("in sub thread. running.");
		}

	}

	int startThread(){
		pthread_t tid;
		void* p = malloc(41943040);  // onMalloc() is invoked.
		LOGI("in main thread. malloc. new address=", (int)p);
		char* arg = "thread_run~~~~~";
		int tret = pthread_create(&tid, NULL, thread_func, (void*)arg);
		int ret = pthread_join(tid, NULL);
		LOGI("in main thread. end.");
		return 0;
	}

**Comment by kripken** [comment]
I think onMalloc is called from `emscripten_trace_record_allocation`. You can check there why it isn't being called. One possible problem is if you define Module.onMalloc on the main thread, but not in worker threads (the Module object is a JS object and cannot be shared between threads, so each thread has its own copy).

**Comment by DebaoD** [comment]
Thanks @kripken , emscripten_trace_record_allocation is invoked by both main thread and subthread. We are monitoring memory by adding logs here. 
The problem we met is, after running our program for some time, it will crash with "cannot enlarge memory arrays". We set TOTAL_MEMORY = 512M. And from the log we can see the total size of allocated heap is only around 200M. There is around 300M heap available. But it gives us "cannot enlarge memory" exception. 

Here is the log:

reder.js:15 :  .emscripten_trace_record_free.in.address=335812496;free size=10835340;totalAllocated memory=156992577
reder.js:15 :  .emscripten_trace_record_free.in.address=400877144;free size=10835340;totalAllocated memory=146157237
reder.js:15 :  .emscripten_trace_record_free.in.address=350421656;free size=10835340;totalAllocated memory=135321897
reder.js:15 :  .MEMORY.updateRenderTask.create bitmap size=11412096
reder.js:15 :  .emscripten_trace_record_allocation.in.address=463278744;request size=11412096;totalAllocated memory=146733993
reder.js:15 :  .MEMORY.updateRenderTask.create bitmap size=11412096
reder.js:15 :  .emscripten_trace_record_allocation.in.address=474690848;request size=11412096;totalAllocated memory=158146089
reder.js:15 :  .MEMORY.updateRenderTask.create bitmap size=11412096
reder.js:15 :  .emscripten_trace_record_allocation.in.address=486102952;request size=11412096;totalAllocated memory=169558185
reder.js:15 :  .MEMORY.updateRenderTask.create bitmap size=11412096
reder.js:15 :  .emscripten_trace_record_allocation.in.address=497515056;request size=11412096;totalAllocated memory=180970281
reder.js:15 :  .MEMORY.updateRenderTask.create bitmap size=11412096
reder.js:15 :  .emscripten_trace_record_allocation.in.address=508927160;request size=11412096;totalAllocated memory=192382377
reder.js:15 :  .MEMORY.updateRenderTask.create bitmap size=11412096
reder.js:15 :  .emscripten_trace_record_allocation.in.address=520339264;request size=11412096;totalAllocated memory=203794473
reder.js:15 :  .MEMORY.updateRenderTask.create bitmap size=11412096
render.js:9543 Cannot enlarge memory arrays to size 543166464 bytes (OOM). Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 536870912, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
render.js:9544 Cannot enlarge memory arrays to size 543166464 bytes (OOM). Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 536870912, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
abort @ render.js:9544
abortOnCannotGrowMemory @ render.js:6965
_emscripten_resize_heap @ render.js:6967
_sbrk
_malloc
Module._malloc @ render.js:8726
(anonymous) @ reder.js:232
updateRenderTask @ reder.js:229
(anonymous) @ reder.js:83
(anonymous) @ reder.js:62
setTimeout (async)
(anonymous) @ reder.js:60
render.js:2551  CFX_DIBitmap::Create.in.pBuffer empty?1
reder.js:250 Uncaught (in promise) abort(Cannot enlarge memory arrays to size 543166464 bytes (OOM). Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 536870912, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ) at Error
    at jsStackTrace (http://localhost:3000/render.js:1176:13)
    at stackTrace (http://localhost:3000/render.js:1193:12)
    at abort (http://localhost:3000/render.js:9550:44)
    at abortOnCannotGrowMemory (http://localhost:3000/render.js:6965:7)
    at _emscripten_resize_heap (http://localhost:3000/render.js:6967:7)
    at _sbrk (wasm-function[7024]:0x2cbdff)
    at _malloc (wasm-function[6517]:0x2ac166)
    at Object.Module._malloc (http://localhost:3000/render.js:8726:35)
    at http://localhost:3000/js/render/reder.js:232:33
    at Array.forEach (<anonymous>)

It's very strange why it doesn't allocate memory from the 300M freed heap.

**Comment by kripken** [comment]
Memory fragmentation might be an issue in a long-running program.
