### ISSUE TITLE
Duplicate symbol linker error in upstream

### ISSUE THREAD

**Issue by r0mai** [emscripten-core/emscripten#9638]
Linking two instances of the same `*.bc` file causes duplicate symbol errors during linking in the upstream compiler, but not with fastcomp.

Repro steps:

Create a `main.cpp`:
```cpp
int main() {}
```

Create a `lib.cpp`:
```cpp
void foo() {}
```

Run the following script, which compiles both cpps; creates a static lib (.bc) out of lib.o, and links an executable linking `lib.bc` twice:

```sh
#/bin/sh

set -xe

CXX=em++

$CXX -c main.cpp -o main.o
$CXX -c lib.cpp -o lib.o
$CXX lib.o -o lib.bc
$CXX main.o lib.bc lib.bc
```

This script succeeds with `1.38.47`, but fails with `1.38.47-upstream`, with the following error:

```
wasm-ld: error: duplicate symbol: foo()
>>> defined in lib.bc
>>> defined in lib.bc
```

My expectation is that the linker survives such duplicated linked libraries as it does on native platforms, and as it does with fastcomp.

This is a reduced case of an issue that we encountered from build files generated by cmake.

You can also just clone this gist, that has all these scripts prepared along with a script `build-clang.sh`, that does the same thing but with the native linker:
https://gist.github.com/r0mai/30ae6b39770edd60ca811703dbe96977

**Comment by sbc100** [comment]
The issue here is that a bitcode file isn't a library, its an object file.

To get the desired behavior you can add the bitcode (or object) file a library using `emar cr libfoo.a lib.o`

Another thing to note is that in the above example, by default, the upstream backend produces an objects file not bitcode files, so using the .bc extension there is little misleading.  (Run `file lib.bc` to see that its wasm object file and not a bitcode file).

I would advise using emar to create your libraries. 

So I think this is working as intended.

**Comment by r0mai** [comment]
`emar` method indeed works. The bitcode based workaround was a leftover for some old emscripten  [issue](https://github.com/emscripten-core/emscripten/issues/2142) which has been fixed since then.

Thank you for you help!
