### ISSUE TITLE
thread function don't excute 

### ISSUE THREAD

**Issue by Y0QIN** [emscripten-core/emscripten#9667]
I have a very strange problem by using pthread. After the thread is created, the thread function isn't executed. And this is an occasional problem that happend when I fresh or enter the page.
Has someone meet the same or similar issues?
Can someone give me some advice?

**Comment by sbc100** [comment]
Something this can happen if you don't yield on the main thread.  In general threads can't start until the main thread yield (returns from to JS event loop).

If you don't want to break up you main thread code you can also use PROXY_TO_PTHREAD to PTHREAD_POOL_SIZE to solve this problem.

**Comment by Y0QIN** [comment]
@sbc100 Could you say something about why this happened. 
I don't quite understand that the thread has used the join mode and will wait for the sub thread to finish. Why does this happen? Maybe it's because of the browser's event mechanism？

**Comment by sbc100** [comment]
What i'm describing might not be the problem you are seeing, but assuming it is, the problem is this:

In order to create a new thread the browser needs to create a new WebWorker and send messages to it.  In order to do that the JS event loop needs to run, but the JS event loop only runs when you return all the way out of your program.  So if you call pthread_create() (unless you use PROXY_TO_PTHREAD or PTHREAD_POOL_SIZE) the new thread won't actually start until you return out and let the JS event loop run.

@kripken is about to land change that will make this a lot more obvious: https://github.com/emscripten-core/emscripten/pull/9579

**Comment by sbc100** [comment]
If you enable PROXY_TO_PTHREAD and the problem goes away then you will know that you are seeing this problem.

**Comment by Y0QIN** [comment]
@sbc100  use PROXY_TO_PTHREAD to PTHREAD_POOL_SIZE means to -s PROXY_TO_PTHREAD or -s PTHREAD_POOL_SIZE=PROXY_TO_PTHREAD？
when I use  -s PROXY_TO_PTHREAD -PTHREAD_POOL_SIZE=4 to re-compile my code , it success but it occur the following problem:
 ffmpeg.worker.js:226 ReferenceError: wasmAlready is not defined
    at Array.ASM_CONSTS (http://192.168.4.104/js/ffmpeg/ffmpeg.js?va08v:1:19399)
    at _emscripten_asm_const_i (http://192.168.4.104/js/ffmpeg/ffmpeg.js?va08v:1:19880)
    at wasm-function[1547]:0xb7d00
    at Module._main (http://192.168.4.104/js/ffmpeg/ffmpeg.js?va08v:1:164816)
    at ___call_main (http://192.168.4.104/js/ffmpeg/ffmpeg.js?va08v:1:31600)
    at wasm-function[1447]:0xb0c56
    at wasm-function[1426]:0xaf7a6
    at Object.Module.dynCall_ii (http://192.168.4.104/js/ffmpeg/ffmpeg.js?va08v:1:166121)
    at onmessage (http://192.168.4.104/js/ffmpeg/ffmpeg.worker.js:191:42)
onmessage @ ffmpeg.worker.js:226

that because I use EM_ASM in C code? How could I solve this problem?
```
int main()
{ 
    printf("########FFmpeg library import complete#########\n");
    EM_ASM(wasmAlready());
    memset(&g_context, 0, sizeof(struct _ffmpeg_context_t) * MAX_CHAN_NUM);
    emscripten_exit_with_live_runtime();
    return 0;
}
```

**Comment by sbc100** [comment]
Where are you defining `wasmAlready`?   Since your code is now running in worker so you'd want to make sure `wasmAlready` is defined in the js file along with the module.  One way to do include it via `--pre-js` or `--post-js`.

Alternatively forget about PROXY_TO_PTHREAD and just add PTHREAD_POOL_SIZE which should be simpler.

**Comment by Y0QIN** [comment]
@sbc100 I solved the error above about `wasmAlready`.
But it still occur thread deadlock that the thread function do not excute after thread create ,before thread_jion

**Comment by sbc100** [comment]
Did you try add PTHREAD_POOL_SIZE=N? ( where N > 1)

Can you run simple thread test?  e.g. ./tests/runner.py browser.test_pthread_create?

**Comment by Y0QIN** [comment]
I have add PTHREAD_POOL_SIZE=4 already. And it test success when I run the simple test by cmd
`python ./tests/runner.py browser.test_pthread_create`.
In addition, my wasm files is normal in win7,but occasionally deadlock in win10
