### ISSUE TITLE
Upstream backed doesn't work with "-fstack-protector"

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#9780]
I don't know if this is something we care about. This compiles without error in the fastcomp backed (but I haven't actually verified it does anything).
In the upstream backend I get multiple errors like:
`wasm-ld: error: CMakeFiles/path/to/file.cpp.o: undefined symbol: __stack_chk_guard`

Emscripten 1.39.0

**Comment by sbc100** [comment]
Sounds like its worth having for completeness.   Whole classes of stack smashing attacks are already rendered useless in webassembly due to the fact the control stack is not stored in memory, but I'm sure there are still many others.

**Comment by kripken** [comment]
We did add a [SAFE_STACK](https://github.com/emscripten-core/emscripten/blob/incoming/src/settings.js#L264) option, which runs a binaryen pass. Maybe that overlaps with `-fstack-protector`? Not sure if we looked into the feasibility of using that option.

**Comment by sbc100** [comment]
We should make this work I think...

**Comment by gracicot** [comment]
The stalebot is wrong, it would be useful if this one worked

**Comment by sbc100** [comment]
@gracicot does the existing settings work for you: https://emscripten.org/docs/tools_reference/settings_reference.html?highlight=environment#stack-overflow-check

**Comment by dschuff** [comment]
I'm find with @sbc100's change linked above, which enables -fstack-protector in emscripten by linking the necessary runtime functions.

Thinking about this a little bit though, I'm actually kind of surprised this actually works without any LLVM-side work. The [documentation](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-fstack-protector) suggests that the backend is responsible for placing the stack guard in the right place but I don't recall adding any specific support for this to the wasm backend, and our stack is a bit weird compared to other platforms. It's actually not super obvious what the best place is, since we don't have a return address to protect.  I assume the usual/default place would be above all of the locals (i.e. between the locals and the return address). If we do that, we don't protect anything in the current frame, but we do protect the contents of the frames above the current frame.
Another option would be between the statically-sized objects and the dynamically-sized objects in the current frame (see [here](https://github.com/WebAssembly/tool-conventions/blob/main/BasicCABI.md#the-linear-stack) for a diagram of LLVM's wasm stack frames). If we did that, then we could detect overruns from dynamically-sized objects that clobber other locals but don't go beyond them.
Maybe that's not too useful though; I'd guess that even large stack arrays are mostly statically-sized.
And for completeness, there's not as much point in putting the guard at the bottom: it could detect underruns (which I'm guessing are not as common as overruns?) but there's no live data below to protect.
