### ISSUE TITLE
Unknown option '--strip-dwarf'

### ISSUE THREAD

**Issue by lorafib** [emscripten-core/emscripten#9894]
Hi everyone,

I just installed emsdk and wanted to run the first test by running 
`EMCC_DEBUG=1 python tests/runner.py test_hello_world`

However, it failed.. like most other tests I started.

I couldn't find anything in the FAQ, so, I appreciate any advises if the error is on my side and is due to improper setup or so.

[test_hello_world_output.txt](https://github.com/emscripten-core/emscripten/files/3884261/test_hello_world_output.txt)

**Comment by lorafib** [comment]
Oh.. and i just realized that I should have put this to the emsdk repo... let me know if I should move it there

**Comment by sbc100** [comment]
The `--strip-dwarf` option was relatively recently added to binaryen:
https://github.com/WebAssembly/binaryen/pull/2454/

I think what is happening here is that you using your checkout of
emscripten which as at tip-of-tree, but the packaged version of
binaryen doesn't yet support that flag.

Your options are:

1) Is the emscripten from the emsdk
2) Build your own binaryen from tip-of-tree.
3) Install `sdk-tot` rather than `sdk-latest` to get an even more
bleeding edge version of the SDK to match the bleeding edge emscripten
you are using.

**Comment by lorafib** [comment]
Ah, I see! Thanks for your help! Sorry, this actually a pretty obvious version mismatch ...
