### ISSUE TITLE
RESERVED_FUNCTION_POINTERS and addFunction/removeFunction

### ISSUE THREAD

**Issue by cggallant** [emscripten-core/emscripten#9903]
addFunction and removeFunction used to use a backing array but now appear to be adding the JavaScript function to the Table object directly at runtime.

Adding the function to the Table object is fine with me but my issue is that the removeFunctionWasm function doesn't remove the function pointer from the Table object.

I end up with the following error: `Unable to grow wasm table. Use a higher value for RESERVED_FUNCTION_POINTERS or set ALLOW_TABLE_GROWTH.`

Is there a flag to tell it to use the old way with the backing array until the removeFunction is implemented?

**Comment by cggallant** [comment]
Looking at the WebAssembly Table spec and there's no delete option. The best that could be done would be to set a table element to null and maybe reuse indexes that are null.

**Comment by sbc100** [comment]
I'm curious what your use case for add/removeFunction is?  

I think you are correct the only way to do this correctly would be set entries to null and keep a free list of empty slots.  This could confuse C code though since function pointer equality will break.  Imagine code that takes two function pointers and compares them.. if you are allows to remove entries from the table then two different function could end with the same address (at different points in time, but those addresses could be stored).   So i'm tempted to say "don't do this", but I'm curious what your use case is.

**Comment by cggallant** [comment]
The idea was that the JavaScript code could pass in a temporary anonymous function and, once the code completes, it would be released. Basically, implement a Promise type thing by passing in success and error functions for the calling JavaScript function.

**Comment by cggallant** [comment]
Is the backing array approach gone now? There are other ways to write the code. It was just neat being able to specify functions on demand.

**Comment by sbc100** [comment]
Could you instead do that via an additional level of indirection?  i.e. pass an int32 which as index into you array of JS callbacks?

So instead of write `call_indirect <callback_address>` you would write `call RunJSCallback` which takes an index as arg0?  (I guess you would need one RunJSCallback imported per signature too).

Trying to use wasm table indexes (at least right now, and at last for C languages)  is tricky for a couple of reasons:

1) C programs will see many functions with the same address over time. 
2) Adding a JS callback to the wasm table is currently *very* expensive. We actually have to create a tiny wasm module on the fly each time you do this!

**Comment by sbc100** [comment]
Did the backing array approach ever with with wasm?   I'm afraid its been a while since I looked at that part of the code, but I imagine it was an asmjs thing?

**Comment by sbc100** [comment]
I've said all that we should just make removeFunction work.. since its an API we ostensibly support.

**Comment by cggallant** [comment]
When compiled using the RESERVED_FUNCTION_POINTERS it used to use a backing array. It set up a function in the module with the signature and called into the generated JS which looked up the function in the array to call. The JS backing array was what was getting modified.

I can do the same on my side. or just pass in the functions the once at start up. It was just neat being able to do things dynamically.

**Comment by cggallant** [comment]
The addFunction code from 1.38.48:

`function addFunction(func, sig) {
  assert(typeof func !== 'undefined');

  var base = 0;
  for (var i = base; i < base + 4; i++) {
    if (!functionPointers[i]) {
      functionPointers[i] = func;
      return jsCallStartIndex + i;
    }
  }
  throw 'Finished up all reserved function pointers. Use a higher value for RESERVED_FUNCTION_POINTERS.';
}`

**Comment by sbc100** [comment]
I believe that codepath only existed for the fastcomp backend, and it looks like it still does today if you use this backend.

It doesn't looks like this was ever an option with the wasm backend. 

I think the short term solution is to implement removeFunction for wasm backend.   But be aware of the addFunction overhead.

**Comment by cggallant** [comment]
Looks like this issue is being resolved with the following pull request: https://github.com/emscripten-core/emscripten/pull/9944
