### ISSUE TITLE
python fork bomb running emconfigure using SDL2

### ISSUE THREAD

**Issue by claudeha** [emscripten-core/emscripten#9904]
Not sure exactly what happens but when trying to compile Gem, the `emconfigure` step spawns 1000s (!) of python processes eventually causing a denial of service to my interactive desktop session.

The offending command seems to be:
```
CXXFLAGS="-s USE_REGAL=1 -DREGAL_LOG=1 -DREGAL_LOG_ALL=1 -DREGAL_LOG_ONCE=1 -s USE_SDL=2 -s LEGACY_GL_EMULATION=0 -s ERROR_ON_UNDEFINED_SYMBOLS=0" \
CFLAGS="-s USE_REGAL=1 -DREGAL_LOG=1 -DREGAL_LOG_ALL=1 -DREGAL_LOG_ONCE=1 -s USE_SDL=2 -s LEGACY_GL_EMULATION=0 -s ERROR_ON_UNDEFINED_SYMBOLS=0" \
EMMAKEN_CFLAGS="-s USE_REGAL=1 -DREGAL_LOG=1 -DREGAL_LOG_ALL=1 -DREGAL_LOG_ONCE=1 -s USE_SDL=2 -s LEGACY_GL_EMULATION=0 -s ERROR_ON_UNDEFINED_SYMBOLS=0" \
GL_CFLAGS="-s USE_REGAL=1 -DREGAL_LOG=1 -DREGAL_LOG_ALL=1 -DREGAL_LOG_ONCE=1 -s USE_SDL=2 -s LEGACY_GL_EMULATION=0 -s ERROR_ON_UNDEFINED_SYMBOLS=0" \
GL_LIBS="-s USE_REGAL=1 -s USE_SDL=2 -s LEGACY_GL_EMULATION=0 -s ERROR_ON_UNDEFINED_SYMBOLS=0" \
GLU_CFLAGS="-s USE_REGAL=1 -DREGAL_LOG=1 -DREGAL_LOG_ALL=1 -DREGAL_LOG_ONCE=1 -s USE_SDL=2 -s LEGACY_GL_EMULATION=0 -s ERROR_ON_UNDEFINED_SYMBOLS=0" \
GLU_LIBS="-s USE_REGAL=1 -s USE_SDL=2 -s LEGACY_GL_EMULATION=0 -s ERROR_ON_UNDEFINED_SYMBOLS=0"  \
LIBS="-s USE_REGAL=1 -s USE_SDL=2 -s LEGACY_GL_EMULATION=0 -s ERROR_ON_UNDEFINED_SYMBOLS=0" \
emconfigure ./configure \
  --prefix=${HOME}/opt \
  --with-pd=${HOME}/opt/src/libpd/pure-data/src \
  --without-ALL --disable-multicontext --without-glew --without-glewmx --without-glut
```

and the spawned python processes all seem to be:
`/usr/bin/python /home/emscripten/emsdk/upstream/emscripten/emcc.py -c /home/emscripten/.emscripten_ports/sdl2/SDL2-version_18/src/SDL.c -O2 -o /home/emscripten/.emscripten_cache/wasm-obj/ports-builds/sdl2/src/SDL.c.o -I/home/emscripten/.emscripten_cache/wasm-obj/ports-builds/sdl2/include -O2 -DUSING_GENERATED_CONFIG_H -w -s USE_PTHREADS`
which don't consume much CPU but end up consuming 10s of GB of RAM.

In one test there was one more python process apart from the emconfigure and bomb processes, namely:
`/usr/bin/python /home/emscripten/emsdk/upstream/emscripten/emcc.py -c /home/emscripten/.emscripten_ports/sdl2/SDL2-version_18/src/events/SDL_dropevents.c -O2 -o /home/emscripten/.emscripten_cache/wasm-obj/ports-builds/sdl2/src/events/SDL_dropevents.c.o -I/home/emscripten/.emscripten_cache/wasm-obj/ports-builds/sdl2/include -O2 -DUSING_GENERATED_CONFIG_H -w -s USE_PTHREADS`

I am building in a Debian Buster chroot, which has its /dev/shm and /proc mounted.

**Comment by kripken** [comment]
`EMCC_DEBUG=1` logging output might help debug this.

Does `emcc --clear-ports` and then building help?

In general, `EMCC_CORES=X` can set the # of cores, and we should never use any more than that. The default is the number of cores the OS reports. We should enforce that even when multiple processes are used, as they take a global system lock when doing things like building ports (at least on recent versions - which version are you on?)

**Comment by claudeha** [comment]
I got past it somehow, not sure what I did to solve it.  Not really keen 
to retry as it's quite disruptive...
> they take a global system lock when doing things like building ports
I think all the 1000s of processes were blocked waiting for the lock to 
be released, so were not consuming CPU time.

Maybe the lock could be taken before spawning more processes instead of 
by each process after spawning?

strace showed something with emscripten cache lock, which is what my 
conjectures are based on.

**Comment by sbc100** [comment]
I'm kind of confused out configure could of causes this issue since its inherently serial isn't it?  Or is this some bespoke configure that uses parallelism?

We can't really check before the spawn since the lock is really there to protect against this `make -j100` case.    In this make will spawn 100 copies python emcc and if you specify USE_SDL then each emcc instance will to build SDL.. which would be bad.   So we only let one of them do the SDL build and the others wait for the lock.

Its not ideal, and I dislike the "build the libs on demand" approach that we have today, but mabye that helps explain what is going on.

The question is.. how did your machine end up trying compiler SDL that many times when only one verion of SDL should have been allowed to compile at once?   Any why during the configure stage?

**Comment by juj** [comment]
Try `EMCC_CORES=2` or `EMCC_CORES=1` environment variable to adjust how Emscripten internally spawns new processes. Does that affect the issue?

**Comment by claudeha** [comment]
@sbc100 yes the configure is serial, I don't know how it continued past waiting for the first conftest.c to build SDL.  I dislike the "build on demand" too.

@juj I saw that suggested on another ticket, I did try `EMCC_CORES=1` at some point, though I'm not sure if it is the thing that got me past my impasse.

I can't test again for at least a week.  If I can't reproduce it in a fresh chroot then, I'll close this as a heisenbug.

**Comment by juj** [comment]
Btw I have seen something similar on my dev system, which is a Threadripper 2990WX with 64 threads. I had a hunch to attribute it to a O(N^2) growth of spawned threads in the build process, where top level build system (essentially a `make` tool) would spawn #numthreads Emscripten build tasks, and each Emscripten task would spawn #numthreads python multiprocessing pool workers, probably resulting in 64*64=4096 python subprocesses. 

However now I am not completely certain about that, since I think an Emscripten process only spawns #numthreads python subprocesses if doing a link to html/js step, and there should not be #numthreads concurrent link steps active in my build system. Perhaps there is something else in play here.

**Comment by mmatyas** [comment]
I've just run into this issue after a fresh install of Emscripten. I've managed to fix it with a workaround, but it can also be always reproduced with a clean cache.

Using the following simple `main.c`:

```c
#include <stdio.h>
int main() {
  printf("hello, world!\n");
  return 0;
}
```

and with an empty cache (eg. `emcc --clear-ports`), the following command always produces the error:

`EMMAKEN_CFLAGS="-v -s USE_SDL=2" emcc main.c`

It starts spamming `cache:INFO: generating port: libSDL2.a...` and keeps consuming memory until my system dies.

However, the following command works perfectly (again, with a clean cache):

`emcc -v -s USE_SDL=2 main.c`

Pulling the ports first with this can be used as a workaround, and after that the `EMMAKEN_CFLAGS` version works too.

**Comment by kripken** [comment]
Thanks @mmatyas , that does look like a bug. Should be errored on in #10671 - basically, using `EMMAKEN_CFLAGS` that way makes each build command in the port try to build the port again. That PR checks for such recursion.

**Comment by kripken** [comment]
(I'm not sure that explains the other problems discussed earlier, so not marking that PR as closing this issue.)

**Comment by sbc100** [comment]
I think the problem is that the system_libs / ports system should not be effected by the user's current EMMAKEN_CFLAGS.  Shouldn't it be hermetic?

**Comment by kripken** [comment]
I guess it depends on how we define that env var (which I'm not sure we ever did). I can see arguments going both ways (like maybe someone wants to use that env var to change how a port is built, to a different opt level say).

**Comment by sbc100** [comment]
I'd rather ask such a person edit the port file.  Seems like a bad idea to allow ports and system libs to depend on the environment in this way.
