### ISSUE TITLE
Emscripten compiler/ABI version in the Wasm binary

### ISSUE THREAD

**Issue by MarkMcCaskey** [emscripten-core/emscripten#9951]
Hello!   Does Emscripten store the version used to compile it anywhere in the Wasm itself?  Perhaps this is using Emscripten incorrectly, but it'd be nice to be able to find out which version of Emscripten a Wasm binary is from so that tools can more intelligently interact with it.

I looked through the documentation and tried compiling a module but wasn't able to find that information anywhere.

If this isn't something that currently exists is it something you'd consider adding?

**Comment by kripken** [comment]
The `EMIT_EMSCRIPTEN_METADATA` option does something related, see https://github.com/emscripten-core/emscripten/blob/incoming/src/settings.js#L1482 and here are the current fields it emits: https://github.com/emscripten-core/emscripten/blob/29d08bec15ab008c4082b2de700db4b311117b21/tools/shared.py#L3239

Looks like that stores the ABI version currently, but not the emscripten version. We could append that though if it would be useful.

**Comment by sbc100** [comment]
There is a specification for the producers section: 
https://github.com/WebAssembly/tool-conventions/blob/master/ProducersSection.md
You can enable this in emscripten by passing `-s EMIT_PRODUCERS_SECTION` at link time. 

However emscripten doesn't not include this by default.  For the rational you can see the discussion here: https://github.com/WebAssembly/tool-conventions/issues/93.

If your goal is to load wasm modules that are built by emscripten outside of emscripten then there are also other options available to you:

1. `EMIT_EMSCRIPTEN_METADATA`: T his is an option that was added a while back by somebody who, IIRC, wanted to include extra metadata so that they could load the resulting wasm file without any JS.    It includes things like the static data size, and memory layout, etc. 

2. `STANDALONE_WASM`: Building with this option is results in a binary that looks a lot more like the WASI standard binaryies.

Of these two options I would always prefer `STANDALONE_WASM`.  Its being actively worked and supported.   IMHO `EMIT_EMSCRIPTEN_METADATA` was kind of ah-hoc stop gap and I personally would like to see it disappear one day.

**Comment by MarkMcCaskey** [comment]
Great -- thanks for the quick and detailed replies!
