### ISSUE TITLE
is it possible to get stuff from compiler_rt to be in the modules?

### ISSUE THREAD

**Issue by SetLinux** [emscripten-core/emscripten#9964]
i am having an attempt at creating a wasm module from emscripten and then linking it to rust and for the most part it works p good but i tried to do it with "FreeType" and then noticed that when trying to link it in rust i get "undefined symbol : __THREW__" which if i understand correctly makes sense because such function is only added at the final stages so how can i get such thing to be embedded in the module

**Comment by sbc100** [comment]
How are you linking the wasm module?  compiler-rt, just like libc should be linked into the wasm file.

**Comment by GreatIndieDeveloper** [comment]
Firstly I compile with the flags "-s MODULAR=1 -s EXPORT_ES6=1 -s LINKABLE=1" then I generate bitcode static file and take that file and link against it

**Comment by GreatIndieDeveloper** [comment]
It's working fine with C++ projects (linked harfbuzz and Bullet successfully)

**Comment by sbc100** [comment]
So it sounds like you are not linking at all, basically building a big object file?   So that result won't have any libc or copiler-rt of any library as part of it.   And then how do you link the resulting library/object?  Are you trying to link it with emscripten or with some other linker?  

Or are you actually doing a link step to produce that bitcode?    I believe that "-s MODULAR=1 -s EXPORT_ES6=1 -s LINKABLE=1" are all link-time only flags that should not be needed if you are just building an object file.. i.e. only effect the linker output, not the compiler output.

**Comment by GreatIndieDeveloper** [comment]
Oah I see what you mean I used to use these flags on my other emscripten projects so didn't think much of it ; and I am then linking the bitcode file with rust

**Comment by sbc100** [comment]
I'm not sure how the rust+emscripten thing works.  Perhaps @tlively knows more.

But in general emscripten-generated code can end up depending on emscripten's compiler-rt and other core libraries being available at link time.

**Comment by GreatIndieDeveloper** [comment]
Is there anyway to have this inside the bitcode file ?

**Comment by tlively** [comment]
@GreatIndieDeveloper how are you linking Emscripten's output with your rust code? Are you using the `wasm32-unknown-emscripten` Rust target triple?

**Comment by GreatIndieDeveloper** [comment]
Nope I am using the wasm32-unknown-unknown and I been able to get C++ libs linking successfully

**Comment by tlively** [comment]
Ah, that is not expected to work right now due to a mismatch between the C ABI used by Rust with the wasm32-unknown-unknown target and the actual C ABI used by clang and Emscripten. If you want to link C/C++ objects into your Rust wasm project, you have to use the wasm32-unknown-emscripten Rust target for now.

**Comment by GreatIndieDeveloper** [comment]
Is there any plans to have this working in the near future ? :) As this would be extremely useful

**Comment by GreatIndieDeveloper** [comment]
And this is actually a bit weird as I got Bullet linking successfully before

**Comment by GreatIndieDeveloper** [comment]
With extern C for the interface I will be using and a custom malloc

**Comment by GreatIndieDeveloper** [comment]
..

**Comment by tlively** [comment]
There are plans to resolve the ABI mismatch by introducing a new C ABI that will be used by both Rust and C, but there is a lot of work that will have to happen first, so this is not going to be a short term solution. See https://github.com/WebAssembly/tool-conventions/issues/88 for more details.
