### ISSUE TITLE
Fortran support

### ISSUE THREAD

**Issue by arjo129** [emscripten-core/emscripten#998]
Recently I tried to build GNU octave through emscripten, however it failed because of parts written in Fortran. may

 be it would be possible to add fortran, as I understand currently emscripten is translating llvm bytecode to javascript. And in extension, one could add Ada and Obj-C support?

**Comment by gagern** [comment]
I've been using a similar workaround today (in an attempt to compile LAPACK), except I've used a shell script instead of Python code to run `gfortran` and `llvm-as`. And I did so without intermediate file, using a stdout to stdin pipeline instead.

I get warnings that the bytecode of the Fortran files is from a different triple than what emcc compils from C. So I guess one would have to compile Dragonegg against the LLVM version of emscripten. Not sure (yet) how to do that.

If I feed a Fortran file to my native `clang` it compiles that all right. I don't know how it does that, whether it's calling `gfortran` or `gcc` behind the scenes, and if so, whether it relies on Dragonegg. I also don't know where that capability gets configured, how to enable that for the emscripten build of LLCM and clang.

Once Fortran can be compiled, we should investigate ways to compile libgfortran as well, to offer a suitable runtime environment. But Fortran sources first.

> Search the issues and mailing list, I think some of these have work on them done already.

Some pointers:

* [Fortran compilation](https://groups.google.com/d/msg/emscripten-discuss/isZ-Z_58ypE/SpdYiLNrh-cJ) looks like the most thorough discussion so far, but apparently petered out at some point with no tangible results remaining.
* [Emfortran](https://groups.google.com/d/msg/emscripten-discuss/Nt2Sm0MhunQ/k2FC71FuwyUJ) where @zmaril suggested [his emfortran script](https://github.com/zmaril/emscripten/blob/herecomesdrtran/emfortran).
* [Porting R](https://groups.google.com/d/msg/emscripten-discuss/_FrjNDrUa-Q/jrpo7Rnh83gJ) used `f2c` to port its Fortran 77 code. Not an option for more recent dialects.
* [Port of BLAS, LAPACK, etc?](https://groups.google.com/d/msg/emscripten-discuss/4Qt1OXKCKrk/KPFXhalxpeAJ) is what I'm currently interested in. Apparently used the `f2c` approach as well.

**Comment by jandoerntlein** [comment]
> I get warnings that the bytecode of the Fortran files is from a different triple than what emcc compils from C. So I guess one would have to compile Dragonegg against the LLVM version of emscripten. Not sure (yet) how to do that.

I believe you can safely ignore that as long as you make sure that the target architecture (like x86, x64 etc) matches. But still it would be nice to fix this :)

**Comment by jakirkham** [comment]
Related to issue ( https://github.com/kripken/emscripten/issues/5553 ).

**Comment by jakirkham** [comment]
Yeah I guess this or #5553 should be closed and marked as a duplicate.

**Comment by sbc100** [comment]
Closing as a duplicate.
